<?php

return [
    'login' => [
        'title' => 'تسجيل الدخول',
        'email' => 'البريد الإلكتروني',
        'password' => 'كلمة المرور',
        'button' => 'تسجيل الدخول',
        'editor_save_context' => "Log in to save your skin to the gallery. Your work won\\'t be lost.",
        'forgot' => 'هل نسيت كلمة المرور؟',
        'reset' => 'إعادة تعيين',
        'register' => 'ليس لديك حساب؟',
        'signup' => 'إنشاء حساب',
        'google' => 'تسجيل الدخول بجوجل',
        'microsoft' => 'تسجيل الدخول بمايكروسوفت',
        'facebook' => 'تسجيل الدخول بفيسبوك',
        'twitter' => 'تسجيل الدخول بتويتر',
        'divider' => 'أو',
    ],
    'signup' => [
        'title' => 'إنشاء حساب',
        'existing' => 'لديك حساب بالفعل ؟',
        'button' => 'الموافقة والاستمرار',
        'terms_by_selecting' => 'عن طريق تحديد',
        'terms_agree_to' => '، أنا متفق مع SkinMC',
        'terms_acknowledge' => 'واعترف بـ',
    ],
    'recover' => [
        'title' => 'استرجاع الحساب',
        'description' => 'فقدت كلمة المرور الخاصة بك؟ استعادها عن طريق إدخال عنوان البريد الإلكتروني الخاص بك.',
        'button' => 'إرسال رسالة الاسترجاع',
        'found' => 'هل وجدت كلمة المرور؟',
    ],
    'logout' => [
        'title' => 'تسجيل الخروج',
        'description' => 'هل أنت متأكد من رغبتك في تسجيل الخروج من حساب SkinMC؟',
        'logout' => 'تسجيل الخروج',
        'cancel' => 'إلغاء',
    ],
    'profile_qrcode' => [
        'title' => 'مسح رمز QR',
        'done' => 'تم',
    ],
    'language' => [
        'title' => 'اللغة',
        'description' => 'إختر لغتك',
        'contribute' => 'المشاركة في الترجمة',
        'contribute_add' => 'إضافة ترجمات',
        'updated' => 'لقد تم تعيين لغتك',
    ],
    'copied' => 'تم النسخ إلى الحافظة!',
    'close' => 'إغلاق',
    'feedback' => [
        'title' => 'الملاحظات',
        'type' => [
            'select' => 'حدد نوع الملاحظة',
            'label' => 'نوع الملاحظة',
            'comment' => 'التعليقات',
            'question' => 'الأسئلة',
            'bug' => 'أُبلغ عن خلل',
            'feature' => 'اقتراح ميزة جديدة',
        ],
        'submit' => 'إرسال',
        'nps' => 'من 0 إلى 10 كم من المحتمل أن توصي SkinMC لصديق؟',
        'success' => [
            'title' => 'شكراً لك!',
            'message' => 'لقد تم إرسال رسالتك، توقع ردا قريبا! لمزيد من الأسئلة، لا تتردد في الانضمام إلى ديسكورد أو قم بتقديم رسالة أخرى.',
        ],
    ],
];
