<?php

return [
    'skins' => 'السكنات',
    'avatars' => 'الافتارات',
    'editor' => 'المحرر',
    'heads' => 'الادمغة',
    'capes' => 'الكيبات',
    'servers' => 'السيرفرات',
    'achievement' => 'الإنجازات',
    'armor' => 'ارمور ستاند',
    'banners' => 'البنرات',
    'banner' => 'Banner Editor',
    'profile' => 'ملفي الشخصي',

    'generators' => 'Generators',

    // Navigation dropdowns
    'feed' => 'Feed',
    'discover' => 'Discover',
    'mods' => 'Mods',
    'shaders' => 'Shaders',
    'resource_packs' => 'Resource Packs',
    'modpacks' => 'Modpacks',
    'datapacks' => 'Data Packs',
    'plugins' => 'Plugins',

    'logout' => 'تسجيل الخروج',
    'register' => 'إنشاء حساب',
    'login' => 'تسجيل الدخول',
    'about' => 'عنا',
    'contact' => 'تواصل معنا',
    'faqs' => 'الأسئلة الشائعة',

    'minecraft_name' => 'اسم ماين كرافت',
    'minecraft_uuid' => 'UUID ماينكرافت',
    'what' => 'مالذي',
    'recent_searches' => 'عمليات البحث الأخيرة',
    'username' => 'إسم المستخدم',
    'uuid' => 'UUID',
    'search' => 'بحث',
    'search_placeholder' => 'جرّب',
    'search_placeholder_uuid' => 'أدخل UUID',
    'start_search' => 'ابدأ البحث',
    'cancel_search' => 'إلغاء',
    'search_type' => 'نوع البحث',
    'search_type_all' => 'جميع النتائج',
    'profiles' => 'الملفات الشخصية',
    'view_skin' => 'رؤية السكن',
    'edit_skin' => 'تعديل السكن',
    'make_avatar' => 'صنع افتار',
    'find_heads' => 'ايجاد دماغ الاعب',

    'home' => 'الرئيسية',
    'help' => 'مساعدة',
    'tools' => 'الأدوات',
    'more-tools' => 'المزيد من الأدوات',
    'skin_viewer' => 'عارض السكنات',
    'avatar_maker' => 'صانع الافتارات',
    'collections' => 'المجموعات',
    'popular_skins' => 'السكنات الشائعة',
    'cartoon_skins' => 'سكن كارتوني',
    'animal_skins' => 'سكنات الحيوانات',
    'community' => 'المجتمع',
    'imprint' => 'بصمة',
    'cookies' => 'ملفات تعريف الارتباط',
    'terms' => 'شروط الخدمة',
    'privacy' => 'سياسة الخصوصية',
    'app' => 'التطبيق',
    'mod' => 'مود',
    'totem' => 'Totems',
    'cube' => 'Cube',
    'new' => 'New',

    'feedback' => 'الملاحظات',
    'status' => 'الحالة',
    'recent_searches_placeholder' => 'عندما تبدأ في البحث، ستظهر هنا عمليات البحث السابقة.',
    'recent_views_placeholder' => 'بعد زيارة بعض الملفات الشخصية، سيتم عرض الملفات السابقة التي قمت بزيارتها هنا.',
    'moderate' => 'إدارة',
    'listings' => 'القوائم',
    'add' => 'إضافة',

    'theme' => [
        'title' => 'Theme',
        'dark' => 'داكن',
        'light' => 'فاتح',
        'auto' => 'Auto'
    ],
];
