<?php

return [
    'auth' => [
        'login' => [
            'title' => 'مرحبا بكم في SkinMC',
        ],
        'register' => [
            'title' => 'التسجيل في SkinMC',
            'subtitle' => 'ابدأ وقم بإنشاء حسابك للوصول الكامل.',
        ],
    ],

    'home' => [
        'hero_slogan' => 'مكانك في سكنات ماين كرافت.',
        'hero_slogan_alt_1' => 'Everything Minecraft. One place.',
        'hero_slogan_alt_2' => 'Where Minecrafters meet.',
        'hero_cta' => 'أدهشني',
        'hero_explore_cta' => 'استكشف السكنات',
        'skin_viewer' => 'عارض السكنات',
        'skin_viewer_detail' => 'تصفح :count سكنات',
        'skin_editor' => 'محرر السكنات',
        'skin_editor_detail' => 'صمم سكنك الخاص',
        'avatar_maker' => 'صانع الافتارات',
        'avatar_maker_detail' => 'اصنع افتارك',
        'trending' => 'رائج',
        'minecraft_skin' => 'سكن ماينكرافت ',
        'favourite' => 'المفضل',
        'collections' => 'المجموعات',
        'collections_detail' => 'سكن ماينكرافت في كل مناسبة',
        'creations_title' => 'Skin creations',
        'creations_description' => 'Browse and upload custom Minecraft skin creations.',
        'about_skinmc' => 'حول SkinMC',
        'about_find' => 'البحث عن أي سكن',
        'about_find_detail' => 'استخدم بحث SkinMC عن أي اسم مستخدم Minecraft للعثور على السكن الجديد التالي الخاص بك وعرضه وتحميله.',
        'about_download' => 'تحميل أو تعديل',
        'about_download_detail' => 'وجدت سكن اعجبك؟ أضفه إلى المفضلة الخاصة بك، تحرير أو تنزيل وجعله الخاص بك.',
        'about_platform' => 'منصة مشتركة',
        'about_platform_detail' => 'عايز تاخد السكن معاك؟ امسح رمز Qr وخده معاك.',
        'meta' => [
            'title' => 'عارض سكنات ماينكرافت ',
            'description' => 'عرض وتنزيل سكنات Minecraft، واكتشف أفضل السكنات في المجموعات المنحوتة، والتحقق من توفر اسم المستخدم والسجل وأكثر بكثير!',
        ],
        'recently_viewed' => 'أحدث مُشاهداتك',
        'explore_title' => 'جرب شيئا جديدا',
        'explore' => 'استكشاف الأفكار والأدوات الجديدة',
        'servers_browse' => 'استعراض السيرفرات',
        'servers' => 'اكتشف أفضل خوادم ماين كرافت',
        'servers_new_upcoming' => 'New & upcoming servers',
        'servers_new_upcoming_browse' => 'Find fresh servers with smaller communities that are currently online.',
        'servers_upcoming_players' => 'players',
        'servers_upcoming_badge' => 'New',
        'heads' => 'رؤوس ماينكرافت',
        'head_description' => 'تصفح قاعدة بيانات رؤوس ماين كرافت, أو إنشاء قاعدة بيانات جديدة.',
        'achievement' => 'مولد الانجازات',
        'achievement_detail' => 'قم بإنشاء إنجازاتك الخاصة والمخصصة.',
        'continue' => 'متابعة التصفح',
        'totem' => 'Minecraft Totem Generator',
        'totem_description' => 'Create a custom Minecraft resource pack with a Totem of Undying from any skin.',
        'banner' => 'Minecraft Banner Generator',
        'banner_description' => 'Generate and preview custom Minecraft banners and patterns.',
        'capes' => 'Minecraft Capes',
        'capes_description' => 'Browse the largest collection of Minecraft capes, or create your own.',

    ],
    'profile' => [
        'verified' => 'تم التحقق من الملف الشخصي',
        'minecraft_profile' => 'ملف ماينكرافت',
        'show_qr_code' => 'إظهار رمز QR',
        'favourite' => 'المفضلة',
        'user_title' => 'سكن ماين كرافت :username',
        'user_views' => 'تم المشاهدة :views مرة|تم الشاهدة :views مرات',
        'uuid' => 'UUID',
        'copy' => 'نسخ',
        'link' => 'الرابط',
        'skin_history' => 'سجل سكن ماينكرافت (:skins)',
        'username_history' => 'سجل اسم المستخدم',
        'username_history_name' => 'الإسم',
        'username_history_timestamp' => 'تم التغيير في',
        'username_history_initial_name' => 'الاسم الاول',
        'user_downloads' => ':downloads تحميل|:downloads تحميلات',
        'download_skin' => 'تنزيل السكن',
        'apply_skin' => 'حفظ السكن',
        'capes' => 'الكيبات',
        'claim_profile' => 'هل أنت :username؟ اطلب ملفك الشخصي للتحقق من ذلك وتخصيصه!',
        'claimed' => 'الحسابات الخاصه بك',
        'meta_description' => 'عرض وتنزيل :username Minecraft Skin. انظر UUID، سجل الاسم، الاحصائيات التفصيلية، والمزيد',
        'created_at' => 'تم التحديث: :changed_at',
        'skins' => [
            'meta_title' => 'سجل سكن ماين كرافت :username',
            'meta_description' => 'عرض :username Minecraft Skins و Skins المستخدمة مسبقاً. استخدم المحفوظات للتصفح من خلال الأشكال القديمة أو الماضية المستخدمة، والنسخ الاحتياطي والرد أو جمع الأشكال الجديدة.',
            'title' => 'سجل سكن ماينكرافت',
        ],
        'qr_code' => [
            'meta_title' => 'رمز QR الخاص بـ :username',
            'meta_description' => 'رمز QR الخاص بـ :username مخصص Minecraft',
        ],
        'sub_nav' => [
            'skin' => 'السكن',
            'about' => 'عنا',
            'usernames' => 'اسماء المستخدمون',
            'head' => 'الرأس',
            'comments' => 'التعليقات',
        ],
        'cape' => 'الكيبات',
        'elytra' => 'اليترا',
        'nametag' => 'اسم العلامة',
        'animation' => 'الحركة',
        'rotation' => 'الدوران',
        'none' => 'بدون',
        'idle' => 'خامل',
        'walk' => 'مشي',
        'run' => 'تشغيل',
        'fly' => 'الطيران',
        'follow' => 'تابِع',
        'following' => 'إتباع',
        'unfollow' => 'إلغاء المتابعة',
        'followers' => 'متابع|متابعون',
        'toast' => [
            'following' => 'أنت الآن تتابع :username!',
            'follow-self-error' => 'آسف :username، لا يمكنك متابعة نفسك.',
            'unfollowed' => 'لقد ألغيت متابعة :username',
        ],
        'edit' => 'تعديل الملف الشخصي',
        'joined' => 'تم الإنضمام',
        'role' => 'Role',
        'server-fav-list-empty' => 'يبدو أن :username لم يحصل على أي سيرفرات مفضلة حتى الآن. بمجرد أن يقوم :username بحفظ سيرفر كمفضله، يمكنك رؤيته هنا.',
        'server-own-list-empty' => 'Looks like :username hasn\'t got any servers yet. Once :username has listed a server, you can see it here.',
        'capes-list-empty' => 'Looks like :username isn\'t wearing any capes yet. Once :username is wearing a cape, you can see it here.',
        'feed-own-list-empty' => 'Looks like you haven\'t posted anything to the feed yet! Once you post, you can see your posts here.',
        'feed-list-empty' => 'Hmm, it seems like :username hasn\'t posted anything to the feed yet. Once :username posts something you can see it here.',
        'following-own-list-empty' => 'يبدو أنك لا تتابع أي شخص بعد! بمجرد أن تبدأ في متابعة الناس، يمكنك رؤيتهم هنا.',
        'following-list-empty' => 'همم، يبدو أن :username لا يتابع أي شخص. بمجرد أن يبدأ :username في متابعة أشخاص يمكنك رؤيتهم هنا.',
        'followers-own-list-empty' => 'بمجرد أن يبدأ الناس في متابعة ملفك الشخصي، سيظهرون هنا.',
        'followers-list-empty' => 'همم، يبدو أن :username لا يتبعه أحد. كن أول من يتبع :username. بمجرد متابعة المزيد من الأشخاص، يمكنك رؤيتهم هنا.',
        'render' => 'عارض الرسوميات',
        '3d' => 'عرض ثلاثي الأبعاد',
        '2d' => 'عرض ثنائي الأبعاد',
        'name-history-info' => 'تاريخ اسم المستخدم يذهب بعيدا. قام Mojang بإزالة الدعم للوصول إلى تاريخ API في 13 سبتمبر 2022، مما أدى إلى عدم توفر تاريخ الاسم الدقيق بعد الآن. إذا كنت ترغب في إخفاء سجل اسمك، قم بمطالبة ملفك الشخصي والذهاب إلى الإعدادات لجعله خاصًا.',
        'edit-skins' => 'تعديل سجل السكن',
        'hide-skin' => 'إخفاء السكن',
        'show-skin' => 'إظهار السكن',
        'edit-skin' => 'تعديل السكن',
        'servers' => [
            'title' => ':username\'s servers',
        ],
        'cape-list' => [
            'title' => ':username\'s capes',
        ],
    ],
    'skin' => [
        'meta' => [
            'title' => 'سكن ماين كرافت:username',
            'description' => 'سكن ماينكرافت. قم بتنزيل وعرض السكن، وشاهد أي اللاعبين يرتدون نفس السكن.',
            'tags' => ':username Minecraft Skin, :username Skin, Minecraft Skin, :username tom Minecraft Skin, تحميل Skin, Players بنفس الجلد',
        ],
        'title' => 'سكن ماين كرافت:username',
        'head' => 'اوامر اعطاء الرأس',
        'head_info' => 'لاستخدام مع الكوماند بلوك',
        'first_wearing' => 'أول لاعب شوهد يرتدي هذا السكن:',
        'profiles' => 'الملف الشخصي :profiles|الملفات الشخصيه :profiles',
        'profiles_title' => ':profiles profile with this skin|:profiles profiles with this skin',
        'screenshot' => 'Screenshot',
    ],
    'skins' => [
        'meta' => [
            'title' => 'Page :current — All Minecraft Skins',
            'description' => 'Browse through our :last pages list of :total custom Minecraft skins and download your favourite next skin!',
            'tags' => ':username Minecraft Skin, :username Skin, Minecraft Skin, :username Custom Minecraft Skin, Download Skin, Players with the same skin',
            'tags-title' => ':tag Minecraft Skins',
            'tags-description' => 'Browse through our :last pages list of :total :tag Minecraft skins and download your favourite :tag skin!',
            'tags-metatags' => ':tag Minecraft Skin, :tag Skin, Minecraft Skin, :tag Custom Minecraft Skin, Download :tag Skin, Minecraft :tag Skins',
        ],
        'title-skin-tags' => 'Tagged Minecraft Skins',
        'subtitle' => 'Page :current of :last from :total Minecraft Skins',
        'subtitle-skin-tags' => 'Page :current of :last from :total Tagged Minecraft Skins',
        'sort_by' => 'فرز حسب',
        'latest' => 'آخر السكنات',
        'most_profiles' => 'السكنات الاكثر استخدما',
        'profiles_today' => 'الأكثر استخداما اليوم',
        'profiles_this_week' => 'الأكثر استخداما هذا الأسبوع',
        'profiles_this_month' => 'الأكثر استخداما هذا الشهر',
        'default' => 'الفرز الافتراضى',
        'this_month' => 'تمت الإضافة هذا الشهر',
        'this_week' => 'أضيف هذا الأسبوع',
        'today' => 'تمت الإضافة اليوم',
        'random' => 'عشوائي',
        'similar' => 'سكنات متشابهة',
        'no_similar_skins' => 'لم يتم العثور على سكنات مشابهة حتى الآن.',
        'favorite' => ':count المفضلة|:count المفضلة',
    ],
    'skin-tags' => [
        'faq' => 'ما هي العلامات؟',
        'about' => 'العلامات هي طريقة لإضافة الفئات ذات الصلة إلى المظلات. إضافة العلامات يسمح لك باكتشاف المزيد من المظاهر التي تحبها بسهولة!',
        'guidelines' => [
            'good' => [
                'title' => 'وفيما يلي المبادئ التوجيهية العامة للعلامات الجيدة:',
                'short' => 'قصيرة',
                'descriptive' => 'Descriptive',
                'spelled' => 'Spelled correctly',
            ],
            'bad' => [
                'title' => 'Do not add tags such as:',
                'general' => 'Too general',
                'specific' => 'Too specific',
                'too-many-tags' => 'Should be three separate tags',
                'spelling' => 'Should be :example',
            ],
        ],
        'toast' => [
            'added' => 'Tag ”:tag” added for voting',
            'removed' => 'Tag ”:tag” has been removed',
            'upvote' => 'Upvoted ”:tag”',
            'downvote' => 'Downvoted ”:tag”',
        ],
        'vote' => [
            'up' => 'Upvote',
            'down' => 'Downvote',
            'remove' => 'Remove vote',
        ],
    ],
    'contact' => [
        'contact' => 'Contact',
        'email' => 'Please feel free to write us at <a href="mailto:support@skinmc.net">support@skinmc.net</a> for any questions you have.',
        'faq' => 'We kindly ask to first check out the <a href=":link">FAQ page</a> if your question is already answered there.',
        'other' => 'Other ways to connect',
        'other_discord' => 'Join the Discord server and connect with others, chat about games, share your favourite packs and get help from the community.',
        'other_twitter' => 'Follow on Twitter to see when a new update or feature is released, see the skin of the week and more.',
        'other_instagram' => 'Follow SkinMC on Instagram to browse and discover cool new featured Minecraft Skins and images.',
        'other_bluesky' => 'Follow SkinMC on Bluesky to see when a new update or feature is released, see the skin of the week and more.',
    ],
    'about' => [
        'intro' => '<span>Your</span> <span>platform</span> <span>for</span> <span>Minecraft</span> <span>Skins.</span>',
        'header_credit' => 'Illustration "Epic Nether Battle" by',
        'info' => 'Keep track of everything.',
        'info_explainer' => 'View a players name history, see their previous skins, add them as a friend, download skins, and even get details statistics.',
        'card_find_title' => 'Find any minecrafter',
        'card_find_detail' => 'Get started by searching for any players username or UUID of your choice.',
        'card_view_title' => 'عرض وحفظ وتحرير',
        'card_view_detail' => 'عثرت على جلدك؟ حفظه عن طريق تحميل أو استخدام المحرر لجعله خاصتك.',
        'card_claim_title' => 'Get verified',
        'card_claim_detail' => 'Link up your Minecraft account and claim your profile to unlock cool new features!',
        'card_customise_title' => 'Customise your profile',
        'card_customise_detail' => 'Verified players can add their social media links and make their profile their own.',
        'card_friends_title' => 'Add your friends',
        'card_friends_detail' => 'Get connected with your friends on SkinMC and show your friend list on the profile.',
        'card_history_title' => 'Username & skin history',
        'card_history_detail' => 'Use the advanced search to find and see the username/skin history of a player.',
        'founders' => 'The founders',
        'founders_cofounder' => 'Cofounder of SkinMC',
        'head_of_design' => 'Head of design',
        'head_of_code' => 'Head of code',
        'feedback' => 'Send us feedback',
        'faq' => 'Questions about Minecraft, Skins, and more? Read our FAQs with answers to most frequently asked questions.',
        'faq_link' => 'Visit FAQ center',
        'contact' => 'Do you want to reach out or have further questions? Contact us directly.',
        'contact_link' => 'Contact us',

    ],
    'faq' => [
        'title' => 'FAQs',
        'subtitle' => 'Frequently asked questions',
        'help' => 'Need more help?',
        'discord' => 'Join the Discord server to chat with other Minecraft players.',
        'contact' => 'Contact us',
        'q' => [
            'change_skin_t' => 'How do I change my Minecraft Skin?',
            'change_skin' => '
                <p>To change your Skin do the following:</p>
                <ol>
                    <li>Visit <a href="https://my.minecraft.net/en-us/login/">https://my.minecraft.net/en-us/login/</a> and sign in with your Mojang account.</li><li>Once signed in, select <b>"Skin"</b> on the left menu.</li><li>Then, choose a Model you prefer and upload a the Skin of your liking.</li>
                </ol>',
            'change_username_t' => 'How do I change my Minecraft Username?',
            'change_username' => '
                <p>To change your Username do the following:</p>
                <ol>
                    <li>Visit <a href="https://account.mojang.com/login" target="_blank" rel="nofollow">https://account.mojang.com/login</a> and log in with your Mojang account.</li>
                    <li>Find your Minecraft Profile Name and press the <b>"(Change)"</b> button</li>
                    <li>On the next page, enter your desired new username.</li>
                    <li>Finally, confirm the changes by entering your password and pressing "Change name".</li>
                </ol>',
            'dl_t' => 'How do I download someones Minecraft Skin?',
            'dl' => '
                <p>To download anyones Minecraft Skin do the following:</p>
                <ol>
                    <li>Press on the search bar and enter the username of the player you would like to download the skin from.</li>
                    <li>On the profile page you can preview the skin</li>
                    <li>Click on the <strong>Download Skin</strong> button under the preview</li>
                </ol>',
            'submit_q' => 'How do I submit a skin to a collection?',
            'submit_a' => '<p>Please fill out the following short form with the usernames and their category of which you would like to add to the collections. <a href="https://forms.gle/f4Jh5RpGfsHAZ5xE8" target="_blank">Collection submission form</a>',
            'mcpe_t' => 'Can I use the Skin on Minecraft PE?',
            'mcpe' => '
                <p>Yes. To use the Skin in Minecraft Pocket Edition do the following:</p>
                <ol>
                    <li>Open SkinMC.net on your smartphone and tap the search bar</li>
                    <li>Enter the username of the player\'s skin you would like to download</li>
                    <li>Tap the <strong>Download Skin</strong> button under the preview </li>
                    <li>Open Minecraft PE and tap on <strong>Profile</strong> on the right side</li>
                    <li>Tap on the <strong>+</strong>, or edit character and go to the "classic skins tab"</li>
                    <li>Tap on "owned", then "import", then "choose new skin"</li>
                </ol>',
            'change_times_t' => 'How often can I change my username?',
            'change_times' => '<p>You can change your Minecraft Username <strong>once</strong> every <strong>30 days</strong>.</p>',
            'available_t' => 'After I changed my username, when does it become available for others to claim it?',
            'available' => '<p>If you want to change back to your previous username, you can change back <strong>after 30 days.</strong> Everyone else needs to wait an additional <strong>7 days</strong> (37 days after changing) before they can claim your old username. </p>',
            'username_history_t' => 'Can you remove my username history please?',
            'username_history' => '
                <p>As the username history data comes from Mojang, the username history can not be removed. Mojang has previously stated that their intention was that previous usernames can be seen¹, and that they provide a direct method for the public to access this information².</p>
                <p class="font-14">¹<a href="https://help.minecraft.net/hc/en-us/articles/360034636712-Minecraft-Usernames" target="_blank" rel="noreferrer">https://help.minecraft.net/hc/en-us/articles/360034636712-Minecraft-Usernames</a></p>
                <p class="font-14 mb-0">²<a href="https://twitter.com/dinnerbone/status/554739042529849345" target="_blank" rel="noreferrer">https://twitter.com/dinnerbone/status/554739042529849345</a> (Tweet archived 2 years ago: <a href="http://archive.is/TeAyj" target="_blank" rel="noreferrer">http://archive.is/TeAyj</a>)
                </p>',
        ],
    ],
    'avatars' => [
        'start' => [
            'title' => 'Create your own Minecraft avatar',
            'subtitle' => 'Use the Minecraft avatar generator to create a fun avatar from any skin!',
            'avatar_face' => 'Face style avatar',
            'avatar_bust' => 'Bust style avatar',
            'avatar_cube' => 'Cube style avatar',
            'avatar_head3d' => '3D headshot',
            'avatar_bust3d' => '3D bust',
        ],
        'user' => [
            'title' => 'Choose skin',
            'subtitle' => 'Enter the Minecraft Username for the avatar you would like to generate',
            'form_label' => 'Minecraft username',
            'form_submit' => 'Continue',
        ],
        'output' => [
            'title' => 'Preview and save',
            'subtitle' => 'Enjoy using your new Minecraft avatar',
            'download_info' => 'Happy with the result? Start using your new avatar by downloading it here',
            'download_button' => 'Download avatar',
            'avatar_style' => 'Avatar style',
            'skin_username' => 'Skin username',
            'change' => 'Change',
            'generate' => 'Generate',
            'avatar_colour' => 'Background colour',
            'avatar_colour_palette' => 'Palette',
            'avatar_colour_basic' => 'Basic',
            'show_nametag' => 'Show nametag',
            'loading_3d' => 'Loading 3D viewer…',
        ],
        'meta' => [
            'title' => 'Minecraft Avatar Generator',
            'description' => 'Minecraft Avatar Maker: create custom Minecraft profile pictures using your Minecraft skin',
        ],
    ],
    'totem' => [
        'title' => 'Custom Minecraft Totem',
        'subtitle' => 'Use the Minecraft Totem generator to create a custom resource pack with a Totem of Undying from any skin.',
        'download_info' => 'Happy with the preview? Choose your Minecraft version to save your custom resource pack:',
        'download_failed' => 'Could not load skin image. Check the username or try uploading an image.',
        'base64_size' => 'The image must be less than 256KB.',
        'meta' => [
            'title' => 'Minecraft Custom Totem Generator',
            'description' => 'Custom Minecraft Totems: generate and create a custom Minecraft Resource Pack with a Totem of Undying using your or any other players Minecraft skin.',
        ],
        'type' => [
            'mini' => 'A mini version of your skin!',
            'full' => 'A full version of your skin!',
            'model3d' => 'A 3d model of your skin!',
            'add_designs' => 'Want to see more designs? Submit your design suggestion here:',
        ],
    ],
    'achievement' => [
        'header' => [
            'title' => 'Create your own Minecraft Achievement',
            'subtitle' => 'Use the Minecraft Achievement Generator to create your very own custom achievement and use show your advancements in anything you like to!',
        ],
        'generator' => [
            'yellow_text' => 'Yellow text',
            'white_text' => 'White text',
            'choose_icon' => 'Choose icon',
            'face' => 'Minecraft face instead of icon',
            'form_submit' => 'Download',
            'form_label' => 'Minecraft username',
            'download' => 'Download',
            'embed' => 'Embed',
            'embed_copy' => 'Copy',
        ],
        'meta' => [
            'title' => 'Minecraft Achievement Generator',
            'description' => 'Generate custom Minecraft Achievements and Advancements with the Achievement creator. Download the image directly, use it in forum signatures, embed with HTML or BB code, and more',
        ],
    ],
    'armor' => [
        'header' => [
            'title' => 'Minecraft Armor Stand Creator',
            'subtitle' => 'Generate and create your very own custom Minecraft Armor Stands. Create different poses, positions, place items, and much more.',
        ],
        'meta' => [
            'title' => 'Minecraft Armor Stand Creator',
            'description' => 'Easily generate and create custom Minecraft Armor Stands. The editor helps you make different poses, positions, place items, custom skins, and much more.',
        ],
    ],
    'banner' => [
        'editor' => [
            'header' => [
                'title' => 'Minecraft Banner Editor',
                'subtitle' => 'Design and create your very own custom Minecraft Banners. These can be used to decorate your world or also commonly seen used as <a href="https://optifine.net" target="_blank" rel="nofollow">Optifine</a> capes.',
            ],
            'meta' => [
                'title' => 'Minecraft Banner Creator',
                'description' => 'Create and design your very own custom Minecraft Banners designs with all the patterns and colors from the game! These can be used to decorate your world or be worn as an Optifine Cape using the Banner Cape. You can generate give codes for banners or shields.',
            ],
            'toolbar' => [
                'title' => 'Banner Editor',
                'randomise' => 'Randomise',
                'clear_layers' => 'Clear layers',
                'help' => 'Help',
                'save_banner' => 'Save banner',
                'submit_to_gallery' => 'Add to gallery',
                'reset_from_url' => 'Load from link',
                'minecraft_version' => 'Minecraft version',
                'texture_type' => 'Texture type',
                'banner' => 'Banner',
                'shield' => 'Shield',
                'version_1_21' => '1.21+',
                'version_1_16' => '1.16 - 1.20',
                'version_1_13' => '1.13 - 1.15',
                'version_1_8' => '1.8 - 1.12',
            ],
            'tools' => [
                'share_link' => 'Share link',
                'share_link_placeholder' => 'Share link',
                'generate_codes' => 'Generate codes',
                'target_selector' => 'Target selector',
                'command_give' => 'Give',
                'command_setblock' => 'Setblock',
                'command_replaceitem_shield' => 'Shield',
                'code_placeholder' => 'Pick a command to generate code',
                'import_code' => 'Import code',
                'background_grass' => 'Grass background',
            ],
            'modal' => [
                'save_banners' => 'Saved banners',
                'share_saved_gallery' => 'Share saved gallery',
                'share_saved_gallery_placeholder' => 'Share saved gallery',
                'export_to_chest' => 'Export to chest',
                'delete_all' => 'Delete all',
            ],
        ],
        'gallery' => [
            'header' => [
                'title' => 'Minecraft Banner Gallery',
                'subtitle' => 'Browse the gallery of :count custom designed Minecraft banners and patterns. Use it as a shield or cape to make your Minecraft skin more unique, or as a flag to decorate your world.',
            ],
            'meta' => [
                'title' => 'Minecraft Banner Gallery',
                'description' => 'Browse the gallery of :count custom designed Minecraft Banners. You can use a Banner Design and Pattern as a Shield or cape to make your Minecraft skin more unique, or use it as a flag to decorate your world.',
            ],
            'add_design' => 'Add design',
            'sort' => 'Sort:',
            'sort_trending' => 'Trending',
            'sort_best' => 'Best of',
            'sort_newest' => 'Newest',
            'sort_oldest' => 'Oldest',
            'sort_favorites' => 'Most favourites',
            'sort_views' => 'Most views',
            'sort_last_week' => 'Last week',
            'sort_last_30d' => 'Last 30 days',
            'clear_filters' => 'Clear filters',
            'no_banners' => 'No banners yet',
            'no_banners_message' => 'No designs yet. Be the first to share one.',
            'create_banner' => 'Create a banner',
        ],
        'publish' => [
            'title' => 'Publish banner',
            'publish_button' => 'Publish',
            'title_label' => 'Title',
            'description_label' => 'Description',
            'tags_label' => 'Tags',
            'tags_max_reached' => 'Maximum 5 tags reached',
            'tags_add_placeholder' => 'Add a tag',
            'tags_help' => 'Press enter, tab, or comma to add a tag.',
            'tags_max_error' => 'You can add a maximum of 5 tags.',
            'generate_banner_error' => 'Create a design first.',
            'invalid_code_format' => 'Invalid banner code format.',
            'invalid_base_color' => 'Invalid base colour. Must be between 0 and 15.',
            'invalid_patterns_format' => 'Invalid patterns format.',
            'invalid_pattern_structure' => 'Invalid pattern structure.',
            'invalid_pattern_unknown' => 'Unknown pattern.',
            'invalid_pattern_color' => 'Invalid pattern colour. Must be between 0 and 15.',
        ],
        'edit' => [
            'title' => 'Edit banner',
            'title_label' => 'Title',
            'description_label' => 'Description',
            'tags_label' => 'Tags',
            'tags_max_reached' => 'Maximum 5 tags reached',
            'tags_add_placeholder' => 'Add a tag',
            'tags_help' => 'Press enter, tab, or comma to add a tag.',
            'tags_max_error' => 'You can add a maximum of 5 tags.',
            'save_changes' => 'Save changes',
            'cancel' => 'Cancel',
            'edit_details' => 'Edit banner details',
            'delete' => 'Delete banner',
            'delete_confirm' => 'Delete this banner? This cannot be undone.',
        ],
        'show' => [
            'edit_design' => 'Edit design',
            'banner_give_command' => 'Banner give command',
            'setblock_command' => 'Setblock command',
            'shield_give_command' => 'Shield give command',
            'views_count' => ':count view|:count views',
            'favourites_count' => ':count favourite|:count favourites',
            'favourite_label' => 'favourite',
            'favourites_label' => 'favourites',
            'similar_banners' => 'Similar banners',
        ],
        'already_exists' => 'This banner is already in the gallery.',
    ],
    'skin_creations' => [
        'search_tab' => 'Creations',
        'gallery' => [
            'title' => 'Skin Creations',
            'description' => 'Browse :count custom Minecraft skin creations.',
            'header' => [
                'title' => 'Skin Creations',
                'subtitle' => ':count creation|:count creations',
            ],
            'tab_creations' => 'Creations',
            'upload' => 'Upload skin',
            'downloadable_only' => 'Downloadable only',
            'sort_trending' => 'Trending',
            'sort_best' => 'Best',
            'sort_newest' => 'Newest',
            'sort_oldest' => 'Oldest',
            'sort_favorites' => 'Most favourites',
            'sort_views' => 'Most views',
            'sort_last_week' => 'Last week',
            'sort_last_30d' => 'Last 30 days',
            'sort_recently_updated' => 'Recently updated',
            'empty_title' => 'No creations yet',
            'empty_message' => 'Be the first to share a skin creation.',
            'clear_filters' => 'Clear',
        ],
        'upload' => [
            'title' => 'Upload skin creation',
            'description' => 'Upload a Minecraft skin to the gallery.',
            'heading' => 'Upload skin',
            'subtitle' => 'Drag and drop a PNG or choose a file. Add a title, description, and tags.',
            'drop_here' => 'Drop here',
            'drag_or_click' => 'Drag and drop a skin or click to choose',
            'format_hint' => 'PNG · 64×32 or 64×64',
            'choose_file' => 'Choose file',
            'title_label' => 'Title',
            'title_placeholder' => 'e.g. Mystical Warrior Skin',
            'description_label' => 'Description',
            'description_placeholder' => 'Tell others about your skin creation...',
            'tags_label' => 'Tags',
            'tags_placeholder' => 'e.g. fantasy, knight, blue',
            'tags_hint' => 'Up to 12 tags, comma-separated.',
            'downloadable' => 'Allow download',
            'downloadable_hint' => 'Allow other users to directly download your creation.',
            'visibility_label' => 'Visibility',
            'more_options' => 'More options',
            'credit_label' => 'Credit',
            'credit_placeholder' => 'Optional credit or attribution',
            'alt_text_label' => 'Alt text',
            'alt_text_subtitle' => 'This helps people using screen readers understand what your skin is about.',
            'alt_text_placeholder' => 'Describe what your skin looks like (optional)',
            'submit' => 'Publish',
            'cancel' => 'Cancel',
            'edit_in_editor' => 'Edit skin',
            'please_upload_skin' => 'Please upload a skin first.',
            'remixable' => 'Allow remixing',
            'remixable_hint' => 'Allow other users to remix your creation.',
        ],
        'edit' => [
            'title' => 'Edit skin creation',
            'description' => 'Edit your skin creation.',
            'heading' => 'Edit creation',
            'subtitle' => 'Update title, description, tags, or re-upload the skin.',
            'submit' => 'Save changes',
        ],
        'show' => [
            'download' => 'Download',
            'download_button' => 'Download skin',
            'open_in_editor' => 'Open in editor',
            'edit' => 'Edit details',
            'delete' => 'Delete',
            'delete_confirm' => 'Delete this creation? This cannot be undone.',
            'similar' => 'Similar creations',
            'created_at_ago' => 'Created :time',
            'updated_at_ago' => 'Updated :time',
            'created_and_updated' => 'Created :created · Updated :updated',
            'version_number' => 'Version :number',
            'version_history' => 'Version history',
            'iterations' => 'Iterations',
            'before_after' => 'Before & after',
            'previous' => 'Previous',
            'current' => 'Current',
            'tagged' => 'Tagged',
            'tagged_alt' => 'Tagged',
            'no_tags' => 'No tags',
            'stats' => 'Stats',
            'no_stats' => 'No stats',
        ],
        'validation' => [
            'invalid_skin_format' => 'Invalid skin format. Minecraft skins must be 64×32 or 64×64 PNG.',
            'tags_max_error' => 'You can add a maximum of 12 tags.',
        ],
        'deleted' => 'Creation deleted.',
        'download_disabled' => 'This creation is not available for download.',
        'editor' => [
            'save_to_gallery' => 'Save to gallery',
            'save_new_version' => 'Save new version',
            'save_updated_skin_version' => 'Save updated skin version',
            'save_as_new_creation' => 'Save as new creation',
            'published_successfully' => 'Your skin has been published successfully!',
            'saved_new_version' => 'New version saved.',
            'previous_skin_available' => 'A previously edited skin was found. Would you like to restore it?',
            'restore_skin' => 'Restore',
            'skin_loaded' => 'Skin loaded successfully',
            'preparing_upload' => 'Preparing your upload…',
            'bridge_fail_missing' => 'Your skin is still safe in the editor. Try saving to gallery again.',
            'bridge_fail_invalid' => 'Your skin is still safe in the editor. We couldn\'t use the saved copy — please try saving to gallery again.',
            'bridge_fail_server' => 'Your skin is still safe in the editor. Something went wrong — please try saving to gallery again.',
            'pending_replaced' => 'Your previous pending upload was replaced with your latest skin.',
            'claim_step' => 'Step 1 of 2',
            'claim_title' => 'Link your Minecraft account',
            'claim_description' => 'To publish skins to the gallery, link your Minecraft account first. This is a quick, one-time setup.',
            'claim_skin_safe' => 'Your skin is saved and will be ready to publish right after linking.',
            'claim_button' => 'Link Minecraft Account',
            'claim_reassurance' => 'Your skin is safe — you\'ll continue to publishing after linking.',
            'claim_posting' => 'Saving your skin…',
            'claim_fail' => 'Something went wrong — your skin is safe in the editor. Please try again.',
        ],
        'visibility' => [
            'public' => 'Public',
            'unlisted' => 'Unlisted',
            'draft' => 'Draft',
        ],
    ],
    'search' => [
        'meta' => [
            'title' => 'Search results: :search',
        ],
        'what_are_you_searching_for' => 'What are you searching for?',
        'title' => 'Search results',
        'results' => 'Page :current for :count result|Page :current of about :count results ',
        'results_count' => ':count result|:count results',
        'time' => '(:time seconds)',
        'username_available' => 'Username available*',
        'username_unavailable' => 'Username not available',
        'username_status' => 'Status',
        'username_status_available' => 'Available*',
        'username_status_unavailable' => 'Unavailable',
        'username_searches' => 'Searches',
        'username_searches_count' => ':count / day',
        'username_available_disclaimer' => '*Unless the name is temporarily or permanently banned by Mojang.',
        'no_results' => 'No profiles found. Try searching with UUID by changing the search type.',
        'no_results_tags' => 'No tagged skins found. Try searching for other tags such as "blue", "girl", "fox", etc...',
        'again' => 'Search again',
        'sorry' => 'عذراً...',
        'view_profile' => 'عرض ملف التعريف',
        'view_all' => 'View all',
        'filters' => 'Filters',
        'more_results' => 'more results',
        'more_results_fallback' => 'more results',
        'close' => 'Close',
        'clear_filters' => 'Clear all',
        'profiles' => 'Profiles',
        'verified_only' => 'Verified only',
        'verification' => 'Verification',
        'all' => 'All',
        'verified' => 'Verified',
        'not_verified' => 'Not verified',
        'country' => 'Country',
        'country_placeholder' => 'e.g. US, UK',
        'no_types_found' => 'No project types found for this search',
        'no_categories_found' => 'No categories found for this search',
        'featured' => 'Featured',
        'yes' => 'Yes',
        'no' => 'No',
        'skins' => 'Skins',
        'tags' => 'Tags',
        'no_tags_found' => 'No tags found for this search',
        'min_profiles' => 'Min profiles using',
        'try_different' => 'Try a different search term',
        'skins_no_results' => 'No skins found',
        'empty_state' => [
            'title' => 'No matches this time',
            'message' => "We didn't find any results for this search. Try adjusting your keywords or browsing instead.",
        ],
    ],
    'collection' => [
        'title' => 'Minecraft skin collection',
        'subtitle' => 'Browse through our curated collection of Minecraft skins.',
        'filters' => 'Filters',
        'title_trending' => 'Trending',
        'title_all' => 'All Minecraft Skins',
        'skin_tags' => 'Tagged Skins',
        'filters_skin_type' => 'Skin type',
        'filter_skin_type_steve' => 'Steve type',
        'filter_skin_type_alex' => 'Alex type',
        'cancel' => 'إلغاء',
        'apply' => 'تطبيق',
        'username_minecraft_skin' => ':username\'s Minecraft skin',
        'user_downloads' => '<span class="fw-500">:downloads</span> download|<span class="fw-500">:downloads</span> downloads',
    ],
    'favourites' => [
        'title' => 'المفضلة',
        'subtitle' => 'View and manage skins and servers you saved for later in your favourites list',
        'sort' => 'فرز حسب',
        'toast' => [
            'added' => 'Added to your favourites list',
            'removed' => 'Removed from your favourites list',
            'login_required' => 'Sign in to add to favourites',
        ],
        'skins' => [
            'button' => 'Skins',
            'empty_headline' => 'No skins saved yet.',
            'empty_subtitle' => 'Skins you save will appear here.',
            'empty_browse' => 'Browse skins',
            'meta' => [
                'title' => 'My favourite skins',
                'description' => 'My favourite saved Minecraft skins',
            ],
        ],
        'creations' => [
            'heading' => 'Skin creations',
            'empty_headline' => 'No favourite skin creations yet',
        ],
        'servers' => [
            'button' => 'Servers',
            'empty_headline' => 'No servers saved yet.',
            'empty_subtitle' => 'Save servers you want to revisit later.',
            'empty_browse' => 'Browse servers',
            'meta' => [
                'title' => 'My favourite servers',
                'description' => 'My favourite Minecraft servers',
            ],
        ],
        'banners' => [
            'button' => 'Banners',
            'empty_headline' => 'No banners saved yet.',
            'empty_subtitle' => 'Banners you save will be shown here.',
            'empty_browse' => 'Browse banners',
            'meta' => [
                'title' => 'My favourite banners',
                'description' => 'My favourite Minecraft banners',
            ],
        ],
    ],
    'cape' => [
        'editor' => [
            'title' => 'Minecraft cape editor',
            'subtitle' => 'Use the Minecraft cape editor to create your very own custom designed cape.',
            'meta' => [
                'title' => 'Minecraft Cape Editor',
                'description' => 'Use the Minecraft Cape Editor to create your very own custom designed cape.',
            ],
        ],
        'list' => [
            'title' => 'Minecraft capes',
            'subtitle' => 'Official capes of Minecraft. Capes are commemorative items and are worn as addition to the player skin. They can also change the appearance when an elytra is worn.',
            'meta' => [
                'title' => 'Minecraft Capes List',
                'description' => 'Minecraft cape list: View all official Minecraft capes including Mojang, Minecon, Personal, Special and vanity capes',
            ],
        ],
        'detail' => [
            'title' => ':cape Cape',
            'info' => 'Cape information',
            'profile_list' => 'Profiles with this cape',
            'profiles' => ':profiles profile|:profiles profiles',
            'meta' => [
                'title' => ':cape Minecraft Cape',
                'description' => 'Check out the :cape Minecraft Cape and see players wearing it!',
            ],
        ],
        'list-custom' => [
            'title' => 'Custom Minecraft Capes',
            'description' => 'Browse and view custom capes which have been created and are used by SkinMC members.',
        ],
    ],
    'servers' => [
        'title' => 'Minecraft servers',
        'subtitle' => 'Browse and explore minecraft servers',
        'all' => 'All servers',
        'manage_your_servers' => 'Manage your servers',
        'add_new_server' => 'Add new server',
        'filters' => [
            'trending' => 'Trending',
            'updated' => 'Updated',
            'new' => 'New',
            'most_viewed' => 'Most viewed',
            'top_voted' => 'Top voted',
            'sorting' => 'Sorting',
            'sort_by_latest' => 'Sort by latest',
            'sort_by_oldest' => 'Sort by oldest',
            'categories' => 'Categories',
            'server_location' => 'Server location',
            'show_results' => 'Show results',
            'show_more' => 'Show more',
            'show_less' => 'Show less',
            'clear_filters' => 'Clear filters',
            'reviews' => 'Reviews',
            'sort_by_highest_rating' => 'Sort by highest rating',
            'sort_by_lowest_rating' => 'Sort by lowest rating',
            'bedrock_and_java_support' => 'Bedrock and Java support',
            'sort_by' => 'Sort:',
            'sort_ranking' => 'Best',
            'sort_newest' => 'Newest',
            'sort_new_upcoming' => 'New & upcoming',
            'sort_most_players' => 'Most players',
            'sort_top_rated' => 'Top rated',
            'sort_most_votes' => 'Most votes',
        ],
        'review-count' => ':count Review|:count Reviews',
        'meta' => [
            'title' => 'Minecraft Server List',
            'description' => 'Browse and explore the Minecraft Servers list to find the best Minecraft server! Filter by the latest, most popular and much more',
        ],
        'reviews' => [
            'meta' => [
                'title' => 'Write a review',
            ],
            'editing' => 'You\'re editing your review from :date. Would you like to delete your review instead?',
            'welcome' => 'Hi :username. How was your overall experience with :servername?',
            'subtitle' => 'Leave an overall score of your past experience with the server.',
            'scale' => [
                'great' => 'Great',
                'good' => 'Good',
                'okay' => 'Okay',
                'meh' => 'Meh',
                'bad' => 'Bad',
            ],
            'rate-experience' => 'Next, rate your experience in these areas',
            'overall' => 'Overall',
            'server-team' => 'Server team',
            'community' => 'Community',
            'experience' => 'Experience',
            'availablility' => 'Uptime and availability',
            'shop' => 'Shop',
            'write-review-title' => 'Write a review',
            'write-review-subtitle' => 'Leave a few notes, you can highlight what you enjoyed, what made your experience special, or offer a few suggestions.',
            'write-review-helper' => 'Write a server review to share your experience with new players, and help the server owners with feedback.',
            'write-review-tips' => 'Here are some tips',
            'submit-title' => 'Ready to submit your review?',
            'submit-subtitle' => 'Almost done!',
            'submit-review' => 'Submit my review',
            'back' => 'Back',
            'continue' => 'Continue',
            'delete-title' => 'Are you sure you would like to delete your review?',
            'tos-checkbox-part-1' => 'By submitting this form you accept SkinMC\'s Terms of Service, Privacy Policy, and Community Guidelines. You also confirm that all of the information is accurate, and follows the',
            'tos-checkbox-part-2' => 'review guidelines.',
            'tos-checkbox-part-3' => 'Your review will be published after submission, but can be subject to review.',
            'cannot_review_own_server' => 'You cannot review your own server.',
        ],
        'slots' => 'Slots',
        'empty-helper' => 'You can try to do another search.',
        'empty' => 'Hmm it\'s still empty here.',
        'verified' => 'Verified',
        'review_translate_show_original' => 'Show original',
        'review_translate' => 'Translate review',
        'description_translate' => 'Translate description',
        'create' => [
            'welcome' => 'Welcome',
            'basics' => 'Basics',
            'categories' => 'Categories',
            'social_links' => 'Social links',
            'trailer_video' => 'Trailer video',
            'images' => 'Images',
            'images_description' => 'You can upload photos afterwards, to showcase what your server offers.',
            'submit' => 'Submit',
            'lets_get_your_server_added' => 'Let\'s get your server added.',
            'basics-subtitle' => 'Let people know what your server is about.',
            'description' => 'Description',
            'description_tips' => 'Here are some tips',
            'description_hint' => 'Write a good description for your server to attract new players.',
            'categories-subtitle' => 'Choose some categories for your server',
            'missing-category' => 'Missing a category?',
            'social_links_description' => 'Where can players connect with your server on social media?',
            'trailer_video_description' => 'Showcase your server with a YouTube video.',
            'trailer_video_hint' => 'Paste the video URL or ID:',
            'ready_to_submit_your_server' => 'Ready to submit your server?',
            'review-hint' => 'After submission the team will carefully review your server listing application. Then upon decision, your server will be published, or changes requested before going live.',
            'terms' => [
                'part-1' => 'By submitting this form you are authorised to accept SkinMC\'s Terms of Service, Privacy Policy, and Community Guidelines. You also confirm that all of the information above is accurate, you have properly followed the',
                'part-2' => 'server requirements for setup',
                'part-3' => ', and that the Minecraft server is owned and managed by the entity you are representing.',
            ],
            'submit-application' => 'Submit application',
            'video-id-helper' => [
                'part-1' => 'The video ID is the string of numbers and letters after',
                'part-2' => 'For example if your video url is',
                'part-3' => ', then your video ID would be',
            ],
            'welcome_description' => 'In this step, we\'ll get started on adding your server. Tell us a bit about it, write a description, and in the next step you can upload some images.',
        ],
        'votes' => [
            'vote' => 'Vote',
            'voted' => 'Voted',
            'success' => 'Your vote has been recorded!',
            'login_required' => 'Please log in to vote for this server.',
            'profile_required' => 'Link your Minecraft account to vote.',
            'server_ineligible' => 'This server is not currently eligible for voting.',
            'self_vote_blocked' => 'You cannot vote for your own server.',
            'cooldown' => 'You can only vote once every 24 hours.',
            'cooldown_tooltip' => 'You can vote again :time',
            'count' => ':count vote|:count votes',
        ],
        'copy_server_ip' => 'Copy server IP',
        'all_minecraft_servers' => 'All Minecraft Servers',
        'promo' => [
            'title' => 'Do you host a Minecraft Server?',
            'ready_to_list_your_server' => 'Ready to list your Server?',
            'everything_you_need' => 'Everything you need to grow your server',
            'list_your_server' => 'List your server',
            'list_your_server_description' => 'Create a listing for your server, add photos, social media and more.',
            'find_players' => 'Find players',
            'find_players_description' => 'Find and reach new players to join your server and grow your community.',
            'get_reviews' => 'Get reviews',
            'get_reviews_description' => 'Ask your community to review your server, and reward them in game.',
            'why_list_on_skinmc' => 'Why you should list your Server on SkinMC',
            'others' => 'Others',
            'quality_check_and_confirmation' => 'Quality check and confirmation',
            'quality_check_description' => 'Our team reviews every server to ensure quality.',
            'verified_players' => 'Reviews from verified Minecraft players',
            'verified_players_description' => 'Collect authentic player reviews from legitimate accounts with Votifier integration.',
            'international' => 'International',
            'international_description' => 'With translation features your listing is available to more players.',
            'server_listing_page' => 'Powerful Server listing page',
            'server_listing_page_description' => 'Add photos, description texts, youtube videos, and highlight why players should join your server.',
            'social_connections' => 'Social media connections',
            'social_connections_description' => 'Connect your Servers social accounts and show new players where they can find you.',
            'verified_badge' => 'Verification badge',
            'verified_badge_description' => 'Authentic servers can apply for a verification badge.',
            'owner_profile' => 'Owner profile',
            'owner_profile_description' => 'Add a personal touch, by completing your custom profile.',
            'categories' => 'Categories',
            'categories_description' => 'Different categories to make it easier to find your server.',
            'vote' => 'Vote',
            'vote_description' => 'Ask users to vote for your server.',
            'review' => 'Review',
            'review_description' => 'Ask users to review your server.',
            'fair_listings' => 'Fair listings',
            'fair_listings_description' => 'Server listings can not be artificially boosted in results on SkinMC.',
            'support' => '24h support',
            'support_description' => 'Do you need help or have questions? You can always reach out and receive a fast reply.',
            'custom_features' => 'Custom features',
            'custom_features_description' => 'Missing a feature for your server? Open a ticket, and we\'ll implement it.',
            'faq' => [
                'title' => 'Answers to your questions',
                'suited-question' => 'Is my Minecraft Server suited for SkinMC?',
                'suited-answer' => 'Minecraft Players on SkinMC love to discover new experiences, content and engage with communities. On the platform you\'ll find a large variety of different, unique, fun Minecraft servers. From a large network to even a small survival server, it can make someones day!',
                'get-started-question' => 'How do I get started?',
                'get-started-answer' => 'Adding your Minecraft Server to the SkinMC Server List is very easy! You will first need to create an account, if you haven\'t already, and then follow the setup guide to get your server listed. Add a few photos and a nice description, and your server will be published in no time!',
                'players-question' => 'How can I get more players on my Minecraft Server?',
                'players-answer' => 'Building a community is the most crucial part of a long lasting Minecraft Server. Use the Minecraft Server List on SkinMC to find a new audience and continue to build your community. Ask your players to recommend your Server, or share your listing on social media platforms. Collecting good reviews can also play an important role to a great Server listing presence that attracts new players.',
                'more-question' => 'I have more questions. Where can I get help?',
                'more-answer' => 'You can reach out to SkinMC at any time, 24 hours, by using either the help button, the help desk, or by joining the Discord server.',
            ],
            'ready_to_list_description' => 'Add your Minecraft Server to the SkinMC Server List in just a few minutes. If you need any help, you can reach out around the clock and receive answers quickly.',
        ],
        'manage' => [
            'index' => [
                'welcome' => 'Welcome back, :username',
                'your_servers' => 'Your servers',
                'reviews_today' => 'Reviews today',
                'no_reviews_today' => 'No reviews today',
                'no_reviews_text' => 'Your servers haven\'t received any reviews today. Why not ask your players to leave one?',
                'tips' => [
                    'title' => 'Tips',
                    'description-title' => 'Write a good server description',
                    'description-body' => 'Helpful tips and advice to write a great server description.',
                    'images-title' => 'Adding server images',
                    'images-body' => 'Make your server listing stand out with great images.',
                ],
            ],
            'listings' => [
                'title' => 'Your Minecraft servers (:count)',
            ],
            'insights' => [
                'title' => 'Insights',
                'metrics' => [
                    'servers' => 'Servers',
                    'live_count' => ':count live',
                    'votes_30d' => 'Votes (30 days)',
                    'all_time_count' => ':count all-time',
                    'favorites' => 'Favourites',
                    'reviews_count' => ':count reviews',
                    'average_rating' => 'Average rating',
                    'pending_draft_count' => ':pending pending, :draft draft',
                ],
                'trends' => [
                    'votes_title' => 'Vote trend',
                    'reviews_title' => 'Review trend',
                    'last_days' => 'Last :days days',
                    'vs_previous' => 'vs previous period',
                ],
                'opportunities' => [
                    'title' => 'Top opportunities',
                    'click_to_view' => 'Click an item to view affected servers.',
                    'missing_photos_draft' => 'Draft listings blocked by missing photos',
                    'no_votes_30d' => 'Live servers with no votes in 30 days',
                    'low_completeness' => 'Listings below 75% completeness',
                    'low_rating' => 'Servers below 3.5 rating (3+ reviews)',
                    'meta_missing_photos' => ':count/5 photos',
                    'meta_no_votes_30d' => '0 votes / 30d',
                    'meta_incomplete' => ':score%',
                    'meta_low_rating' => ':rating/5',
                    'none' => 'No servers in this category.',
                ],
                'review_breakdown' => [
                    'title' => 'Review category breakdown',
                    'empty' => 'No review data yet.',
                    'weakest' => 'Weakest category: :category',
                ],
                'top_lists' => [
                    'by_favorites' => 'Top by favourites',
                    'by_votes_30d' => 'Top by votes (30 days)',
                    'lowest_rated' => 'Lowest rated (3+ reviews)',
                    'empty' => 'No server data available.',
                    'empty_votes' => 'No vote data available.',
                    'empty_ratings' => 'Not enough review data yet.',
                ],
                'table' => [
                    'server' => 'Server',
                    'status' => 'Status',
                    'listing_score' => 'Listing score',
                    'avg_rating' => 'Avg',
                    'votes_30d' => 'Votes 30d',
                    'votes_all' => 'Votes',
                    'last_review' => 'Last review',
                    'live' => 'Live',
                    'pending' => 'Pending',
                    'draft' => 'Draft',
                    'empty_title' => 'No servers yet',
                    'empty_subtitle' => 'Add your first listing to see insights.',
                ],
                'activity' => [
                    'title' => 'Recent activity',
                    'review' => 'Review',
                    'vote' => 'Vote',
                    'vote_summary' => 'New vote received',
                    'view_review' => 'View review',
                    'by_user' => 'by :user',
                    'unknown_user' => 'Unknown',
                    'empty_title' => 'No activity yet',
                    'empty_subtitle' => 'Votes and reviews will appear here.',
                ],
            ],
            'edit_server' => 'Edit server',
            'listing' => 'Listing',
            'to_do' => 'To do',
            'last_update' => 'Last update',
            'add_more_photos_to_publish' => 'Add more photos to publish',
            'looks_empty_here' => 'Looks empty here.',
            'get_started_by_adding_a_new_server' => 'Get started by adding a new server?',
        ],
        'status' => [
            'approved' => 'Approved',
            'pending_approval' => 'Pending approval',
            'published' => 'Published',
            'draft' => 'Draft',
            'need_more_images' => 'Need :count more to publish',
            'ready_for_approval' => 'Ready for approval',
            'in_review' => 'In review',
        ],
    ],
    'editor' => [
        'import' => [
            'title' => 'Import Skin',
            'import_by_username' => 'Import by username',
            'import_button' => 'Import',
            'drag' => 'Drag and drop a skin here, or click',
            'click' => 'Select image',
        ],
        'download' => [
            'error' => [
                'no-data' => 'No skin data was provided. Please try again.',
                'invalid-format' => 'The skin data format is invalid. Please try again.',
                'invalid-data' => 'The skin data is corrupted. Please try again.',
                'generic' => 'Something went wrong while downloading your skin. Please try again.',
            ],
        ],
        'draw' => 'Draw',
        'eyedropper' => 'Eyedropper',
        'fill' => 'Fill',
        'move' => 'Move',
        'decrease_brightness' => 'Decrease brightness',
        'increase_brightness' => 'Increase brightness',
        'erase' => 'Erase',
        'undo' => 'Step back (CTRL+Z)',
        'redo' => 'Step forward (CTRL+Y)',
        'default_view' => 'Default view',
        'zoom_in' => 'Zoom in (CTRL +)',
        'zoom_out' => 'Zoom out (CTRL -)',
        'saved' => 'Last saved just now',
        'saving' => 'Auto saving...',
        'save_error' => 'An error occurred',
        'new_skin' => 'New skin',
        'automatically_saved_skins' => 'Automatically saved skins',
        'recovered_skins' => 'Recovered skins',
        'load' => 'Load',
        'delete' => 'Delete',
        'backed_up_title' => 'Automatically saved skins',
        'backed_up_info' => 'Temporarily backed up to your local storage.',
        'backed_up_empty_title' => 'It\'s empty here',
        'backed_up_empty_info' => 'Once you start editing skins you\'ll see your 32 last edited skins here.',
        'recovered_empty_title' => 'No recovered skins',
        'recovered_empty_info' => 'Recovered skins will appear here when you navigate away or close the editor.',
        'backed_up_skins_count' => 'of 32 skin backups used',
        'backed_up_skins_count_info' => 'You can back up to up 32 skins. Once you reach 32 skins an older skin will be replaced with a new one.',
        'layers' => 'Layers',
        'body' => [
            'title' => 'Body',
            'overlay' => 'Overlay',
            'head' => 'Head',
            'torso' => 'Torso',
            'l_arm' => 'Left arm',
            'r_arm' => 'Right arm',
            'l_leg' => 'Left leg',
            'r_leg' => 'Right leg',
        ],
        'model' => 'Model',
        'steve' => 'Steve',
        'alex' => 'Alex',
        'stance' => [
            'title' => 'Position',
            'default' => 'Default',
            'walk' => 'Walk',
            'run' => 'Run',
            'hug' => 'T-pose',
            'fly' => 'Fly',
        ],
        'fullscreen' => 'Fullscreen',
        'fullscreen_exit' => 'Exit fullscreen',
        'grid' => 'Grid',
        'show_grid' => 'Show grid',
        'download' => [
            'title' => 'Save & Download',
            'subtitle' => 'SkinMC Account',
            'description' => 'Would you like to create a free SkinMC account to save your skin and future ones to the cloud?',
            'start_description' => 'Start download directly without saving to the cloud',
            'start' => 'Download skin',
        ],
        'help' => [
            'title' => 'Minecraft Skin Editor',
            'about' => 'Create and edit your custom Minecraft Skin easily with the SkinMC Editor. You can choose between Steve and Alex models, import skins from a file or username, and create your very own Minecraft Skin.',
            'draw' => 'Draw using the pen tool. Select a colour from the swatch to use with it.',
            'eyedropper' => 'Use the eyedropper to select a colour from your skin and add it to your current palette.',
            'fill' => 'Fill entire areas of your skin using the fill tool. Select a colour before using fill.',
            'move' => 'Pan and move around the skin editor canvas with the move tool.',
            'decrease_brightness' => 'Decrease the brightness of the currently active colour.',
            'increase_brightness' => 'Increase the brightness of the currently active colour.',
            'erase' => 'Erase pixels drawn on the secondary overlay layer.',
            'minimap' => 'Minimap',
            'minimap_info' => 'The minimap can show you the skin texture in a flat view while in 3D mode. In 2D mode the minimap switches to a 3D preview of your skin. You can zoom in and out.',
            'autosave' => 'Autosave',
            'autosave_info' => 'The autosave feature saves your skin automatically every 30 seconds. You can access the autosaved skins in the editor by pressing the folder icon, and choosing "Previous skins".',
            '2d_editor' => '2D and 3D editor',
            '2d_editor_info' => 'Toggle between editing your Minecraft skin in 2D or 3D mode.',
        ],
    ],
    'account' => [
        'level' => 'Level',
        'level_history' => 'Level history',
        'xp' => 'XP',
        'my_xp' => 'My XP',
        'xp_to_next_level' => ':xp XP to next level',
        'xp_info' => 'What are XP?',
        'xp_info_tooltip' => 'XP is earned for various activities such as adding tags to skins, inviting friends, commenting, and much more. With each XP earned you can level up and unlock cool things!',
        'table' => [
            'description' => 'Description',
            'points' => 'Points',
        ],
        'my_stuff' => [
            'title' => 'My stuff',
            'creations' => 'Creations',
            'collections' => 'Collections',
            'favourites' => 'Favourites',
            'skins' => 'Manage skins',
            'capes' => 'Capes',
            'banners' => 'Banners',
            'servers' => 'Servers',
        ],
        'settings' => [
            'title' => 'Account',
            'show_profile' => 'Go to profile',
            'friends' => 'Friends',
            'friends_detail' => 'Stay connected by using your friends list on SkinMC.',
            'security' => 'Security',
            'security_detail' => 'Update your login password and keep your account safe',
            'social' => 'Social media accounts',
            'social_detail' => 'Customise your profile by adding your social media',
            'link' => 'Link Minecraft account',
            'link_detail' => 'Link your Minecraft account and claim your profile.',
            'logout' => 'Do you want to log out from your SkinMC account?',
            'automatic_backups' => 'Automatic skin backups',
            'automatic_backups_info' => 'As a SkinMC plus member your skins are backed up daily.',
        ],
        'capes' => [
            'title' => 'SkinMC Minecraft Cape',
            'description' => 'Wear any cape you wish in-game with SkinMC Capes for free.',
            'drop' => 'Drag and drop a cape here',
            'drop-hint' => 'Dimensions 64x32px',
            'select' => 'Select image',
            'upload-cape' => 'Upload & use cape',
            'save-and-use' => 'Save & use',
            'uploaded-cape' => 'Uploaded cape',
            'no-cape' => 'No cape',
            'remove-cape' => 'Remove cape',
            'download' => 'Download the SkinMC Mod to see your and other players capes in-game.',
            'learn-more' => 'Learn more',
            'link-account' => 'Please link your Minecraft account to upload a cape.',
            'updated' => 'Your cape has been updated!',
            'removed' => 'Your cape has been removed.',
            'active' => 'Your cape is activated!',
        ],
        'favourite' => 'Favourite',
        'remove_favourite' => 'Remove favourite',
        'added_to_favourites' => 'Added to favourites',
        'removed_from_favourites' => 'Removed from favourites',
        'welcome' => 'Nice to see you!',
        'view-profile' => 'View my profile',
        'security' => [
            'title' => 'Security',
            'email' => 'Email address',
            'email-title' => 'Update your email address.',
            'save' => 'Save',
            'password' => 'Password',
            'password-title' => 'Change your password at any time.',
            'social-provider' => 'To update your account information, such as your password, please visit your login provider:',
            'social-provider-email' => 'Your associated email address with your login provider',
            'social-provider-connected' => 'Currently connected login providers',
            'current-password' => 'Current password',
            'forgot' => 'Forgot password?',
            'edit' => 'Edit',
            'delete' => 'Delete my account',
            'account-deletion' => 'Delete your SkinMC account.',
            'delete-info' => 'Please confirm to continue',
            'delete-confirmation' => 'Deleting your account is irreversible. All your personal information and content such as posts, favourites, uploaded capes, customisations, etc. will be deleted and can not be recovered.',
            'delete-confirmation-info' => 'Enter your password to continue',
            'delete-confirmation-info-social' => 'Type "delete" to confirm account deletion',
            'type-delete' => 'Type "delete" to confirm',
            'type-delete-label' => 'Type "delete" to confirm',
            'yes-confirm-delete' => 'Yes, confirm delete',
            'account-successfully-deleted' => 'Your account and data has been successfully deleted.',
        ],
        'social' => [
            'title' => 'Social accounts',
            'edit' => 'Edit',
            'save' => 'Save',
            'link-account' => 'Link your Minecraft account to SkinMC to display your social links on your profile.',
            'finish-setup' => 'Finish setup',
            'connect-account' => 'Connect your accounts',
            'connect-description' => 'Choose which accounts you wish to connect and unlock special SkinMC integrations.',
            'empty' => 'No accounts added',
            'empty-description' => 'Your social media accounts will show up here and on your public profile. Once added they will add more personalisation to your page as well as enable integrations.',
            'connect' => 'Connect',
            'username' => 'username',
            'spotify' => 'Add your Spotify username to show your Spotify information on your profile.',
            'discord' => 'Enter your Discord username and number to display your Discord information on your SkinMC profile.',
            'youtube' => 'Add your YouTube channel to SkinMC which will display your YouTube channel on your profile.',
            'youtube-format' => 'Use the following format depending on your channel link:',
            'twitter' => 'Enter your X (formerly Twitter) username to display it on your profile.',
            'bluesky' => 'Enter your Bluesky handle e.g. username.bsky.social to display your Bluesky profile on your profile.',
            'twitch' => 'Enter your Twitch username to display your Twitch channel on your profile.',
            'reddit' => 'Enter your Reddit username to display your Reddit profile on your profile.',
            'github' => 'Enter your GitHub username to display your GitHub profile on your profile.',
            'telegram' => 'Enter your Telegram username to display your Telegram link on your profile.',
            'tiktok' => 'Enter your TikTok username to display your TikTok profile on your profile.',
            'snapchat' => 'Enter your Snapchat username to display your Snapchat profile on your profile.',
            'instagram' => 'Enter your Instagram username to display your Instagram profile on your profile.',
            'facebook' => 'Enter your Facebook username to display your Facebook profile on your profile.',
            'includes_skinmc_plus_benefits' => 'Includes SkinMC plus benefits',
        ],
        'recover' => [
            'title' => 'Recover your account',
            'subtitle' => 'Please enter your new password and confirm it to finish recovering your account.',
            'new_password' => 'New password',
            'repeat_new_password' => 'Repeat new password',
            'submit' => 'Recover account',
        ],
        'customise' => [
            'title' => 'Customise your profile',
            'description' => 'Add your social media, choose an emoji, set your location and more',
            'information' => 'Information',
            'preview' => 'Preview',
            'location' => [
                'title' => 'Location',
                'description' => 'Choose which location you would like to add to your profile.',
            ],
            'biography' => [
                'title' => 'About me',
                'description' => 'Write a bio for your profile.',
            ],
            'status' => 'Status',
            'status-toggle' => 'Show my online status',
            'emoji' => 'Emoji',
            'name-history-toggle' => 'Make username history private',
            'name-history-info' => 'Your Minecraft username history is currently',
            'name-history-toggle-on' => 'private',
            'name-history-toggle-off' => 'public',
            'theme' => 'Profile theme',
            'theme-primary' => 'Primary',
            'theme-secondary' => 'Secondary',
            'appearance' => 'Appearance',
        ],
        'link' => [
            'manage' => 'Manage linked Minecraft account',
            'description' => 'See and manage your linked Minecraft account',
            'title' => 'Linked Minecraft account',
            'current' => 'Currently linked Minecraft account.',
            'status' => 'You now have full access to all SkinMC features!',
            'linked' => 'Linked',
            'disconnect' => 'Disconnect',
            'disconnect-title' => 'Disconnect Minecraft account',
            'disconnect-info' => 'Are you sure you would like to disconnect your Minecraft account?',
            'disconnect-features' => 'You will lose access to commenting, customisation and other features which require a linked Minecraft account. To use these again you will be required to link a Minecraft account.',
            'disconnect-following' => 'Disconnecting your Minecraft account will permanently remove all your followed profiles.',
            'disconnect-posts' => 'Your created feed posts and liked will be deleted.',
            'can-not-undo' => 'This can\'t be undone.',
            'are-you-sure' => 'Are you sure?',
            'confirm' => 'Yes, confirm disconnect',
            'cancel' => 'No, cancel',
            'success' => 'Your account was successfully disconnected!',
        ],
        'finish-setup' => [
            'title' => 'Finish account setup',
            'description' => 'Finish setting up your account, and get full access to all features by linking your Minecraft account to SkinMC.',
            'link' => 'Link Minecraft account',
            'get-started' => 'Get started',
            'skip' => 'Skip',
            'download_skin' => 'Download skin',
            'claim' => 'Claim your profile',
            'pending_upload' => 'Link your Minecraft account to finish publishing your skin.',
            'customise' => 'Customise your page',
            'social' => 'Add social links',
            'comment' => 'Access to comment system',
            'direct_message' => 'Send direct messages',
            'feed' => 'Post status updates to the feed',
            'follow' => 'Follow your friends',
            'badge' => 'Badge displayed on your profile',
            'cape' => 'Custom Minecraft cape',
            'backup' => 'Automatic skin backup',
            'more' => 'And more...',
        ],
        'creations' => [
            'title' => 'Creations',
            'published' => 'Published',
            'private' => 'Private',
            'unlisted' => 'Unlisted',
            'drafts' => 'Drafts',
            'empty_title' => 'No creations yet',
            'empty_published' => 'You have no published creations. Upload a skin and set visibility to "Public" to show it here.',
            'empty_private' => 'You have no private (unlisted) creations.',
            'empty_unlisted' => 'You have no unlisted creations.',
            'empty_drafts' => 'You have no drafts. Save a creation as draft from the editor or upload page.',
            'empty_browse' => 'Browse gallery',
            'empty_upload' => 'Upload skin',
            'meta' => [
                'title' => 'My creations',
                'description' => 'View and manage your skin creations.',
            ],
        ],
        'banners' => [
            'title' => 'Banners',
            'published' => 'Published',
            'drafts' => 'Drafts',
            'empty_title' => 'No banners yet',
            'empty_published' => 'You have no published banners. Create a banner in the editor and publish it to show it here.',
            'empty_drafts' => 'You have no draft banners. Create a banner in the editor without publishing to save as draft.',
            'empty_browse' => 'Browse gallery',
            'empty_create' => 'Create banner',
            'meta' => [
                'title' => 'My banners',
                'description' => 'View and manage your Minecraft banners.',
            ],
        ],
        'skins' => [
            'title' => 'Manage skins',
            'subtitle' => 'Choose which skins appear on your profile. Your current Minecraft skin is always shown.',
            'toggle' => 'Skin visibility toggled',
            'section_currently_worn' => 'Currently worn in Minecraft',
            'section_profile_skins' => 'Skins on your profile',
            'active_badge' => 'Active in Minecraft',
            'active_synced_copy' => 'Synced from your Minecraft account.',
            'active_action_copy' => 'Always visible on your profile. To hide it, change your skin in Minecraft.',
            'open_minecraft_skin_settings' => 'Open Minecraft skin settings',
            'show_on_profile' => 'Show on profile',
            'show_on_profile_tooltip' => 'Controls visibility on your SkinMC profile.',
            'empty' => 'No skins in your history yet. Skins you wear in Minecraft will appear here.',
            'empty_other' => 'No other skins yet. Skins you have worn will appear here; you can show or hide them on your profile.',
            'empty_not_claimed_title' => 'Link your Minecraft account',
            'empty_not_claimed' => 'Connect your Minecraft account to see your skin history and choose which skins appear on your profile.',
        ],
        'invite' => [
            'title' => 'My invites',
            'headline' => 'Invite your friends',
            'info' => 'Create an invite code to share with your friend. Once they accept it, you\'ll both earn some extra XP!',
            'description' => 'Create an invite for your friends and you\'ll both earn some extra XP.',
            'generate' => 'Create invite code',
            'empty' => 'You haven\'t created any invites yet.',
            'code' => 'Code',
            'expiry' => 'Each code works once.',
            'status' => [
                'title' => 'Status',
                'pending' => 'Pending',
                'accepted' => 'Accepted',
            ],
            'add_invite' => [
                'button' => 'Have an invite?',
                'title' => 'Add an invite code',
                'redeem' => 'Redeem invite',
            ],
            'share' => 'Send your friend an invite link',
        ],
        'emoji' => [
            'title' => 'SkinMC Emoji',
            'introducing' => 'Introducing',
            'info' => 'Customise your profile with emoji. Unlock more as you level up.',
            'unlocked_at' => 'Unlocked at level :level',
            'unlocks_at' => 'Reach level :level to unlock',
            'turn_off' => 'Show emoji',
        ],
    ],
    'notifications' => [
        'title' => 'Notifications',
        'view_all' => 'View all',
        'view_all_notifications' => 'View all notifications',
        'image' => 'Notification photo',
        'archived' => 'Archived',
        'inbox' => 'Inbox',
        'settings' => [
            'title' => 'Notification settings',
            'open' => 'Open notification settings',
            'save' => 'Save',
            'saved' => 'Notification settings updated.',
            'server_owner_alerts' => [
                'title' => 'Server owner alerts',
                'description' => 'Receive reminders and listing insights to help keep your server visible and up to date.',
                'toggle' => 'Enable server owner alerts',
                'unavailable' => 'This alert preference is managed globally by the administrators.',
            ],
        ],
        'empty' => [
            'title' => 'You\'re up to date!',
            'text' => 'New notifications will show up here.',
            'text-archived' => 'Archived notifications will show up here.',
        ],
        'action' => [
            'archive' => 'Move to archive',
            'unarchive' => 'Unarchive',
            'open' => 'Tap to open',
        ],
        'toast' => [
            'archive' => 'Notification moved to archive',
            'unarchive' => 'Notification moved to inbox',
            'undo' => 'Undo',
        ],
    ],
    'error' => [
        'offline' => [
            'title' => 'No internet',
            'subtitle' => 'Your internet was disconnected. Please check your connection and reload the page to try again.',
            'try_again' => 'Try again',
        ],
        '404' => [
            'title' => '404 — Page not found.',
            'subtitle' => 'Hm, it looks like nothing was found at this location. Maybe try going back, or start a new search?',
            'try_again' => 'Back home',
        ],
    ],
    'heads' => [
        'list' => [
            'meta' => [
                'title' => 'Minecraft heads database',
                'description' => 'Explore the database of Minecraft heads to decorate your world with, or generate your own give command. View official heads, player heads and custom heads that feature textures which never change.',
            ],
            'header' => [
                'title' => 'Minecraft heads',
                'subtitle' => 'Explore our database of Minecraft heads to decorate your world, or generate your own give command. Player heads show the current skin worn by a user, and can change as the user updates their skin. Custom heads are linked to the Mojang skin file and never change. Custom heads must be summoned using a command block as the command is very long.',
            ],
            'count' => [
                'heads' => ':heads head|:heads heads',
            ],
            'customheads' => [
                'title' => 'Custom heads',
                'description' => 'Custom heads use the direct path to the texture file on the Mojang servers. Hence textures will never be deleted and the heads never change.',
                'version' => 'Minecraft 1.8 or later',
            ],
            'playerheads' => [
                'title' => 'Player heads',
                'description' => 'Player heads use the current skin texture of a Minecraft player. As they are username based, when the player changes their name or skin, the head changes.',
                'version' => 'All Minecraft versions',
            ],
        ],
    ],
    'mod' => [
        'title' => 'SkinMC Mod: Free custom capes',
        'headline' => 'Introducing the SkinMC Mod for more customisation',
        'description' => 'Giving back to the Minecraft community, with a free mod which enables players more customisation with custom capes, available and visible for anyone using the mod.',
        'download' => 'Download now',
        'download-title' => 'Download the mod',
        'requires' => 'Requires',
        'select-version' => 'Choose your Minecraft version',
        'get-started' => 'Getting started is simple',
        'step-1' => '1. Get the mod',
        'step-1-detail' => 'Install Fabric, then download the mod for your game version and install it by putting the jar in your mods folder.',
        'step-2' => '2. Link your account',
        'step-2-detail' => 'If you haven\'t already, sign up/in and connect your Minecraft account to SkinMC.',
        'step-3' => '3. Upload your cape',
        'step-3-detail' => 'Go to your account and upload your custom cape. It will be visible in-game.',
        'all-versions' => 'All versions',
        'latest' => 'Latest',
        'logged-in' => 'Upload your cape',
        'mirror' => 'Mirror',
        'download-via' => 'Download via:',
        'curseforge' => 'CurseForge',
    ],
    'app' => [
        'title' => 'SkinMC Android App',
        'headline' => 'Say hello to the SkinMC Android App.',
        'play-store-attribution' => 'Google Play and the Google Play logo are trademarks of Google LLC.',
        'features' => 'Convenient features for on the go',
        'feature-qr' => 'Built in QR-Code scanner',
        'feature-qr-detail' => 'Use the built in QR-Code scanner to easily get a skin from your Desktop to the app, or scan your friends custom profile QR-Code.',
        'feature-files' => 'Saves directly to files',
        'feature-files-detail' => 'With the usage of Android Files Manager, the app can conveniently save Skins, making it easier to apply in Bedrock Edition.',
        'feature-noads' => 'No ads',
        'feature-noads-detail' => 'A clean designed interface, without distractions. Enjoy an Ad-free experience without intrusive annoyances from web to app.',
        'feature-experience' => 'Experience',
        'feature-experience-detail' => 'Enjoy the full SkinMC experience anywhere, with added features. Customise your profile, add your bio, create a fun QR-Code and more!',
        'get-app-headline' => 'Get the SkinMC App',
        'get-app-detail' => 'Your very own Minecraft companion for your Android — available for free.',
    ],
    'random' => [
        'title' => 'Loading random Minecraft skin',
        'description' => 'Loading random Minecraft skin',
        'headline' => 'Please wait...',
        'redirect' => 'You will be automatically redirected. Page not loading?',
        'click-here' => 'Click here',
        'messages' => [
            '1' => 'Loading random Minecraft skin...',
            '2' => 'Digging down...',
            '3' => 'Creeper, aw man...',
            '4' => 'Searching through chests...',
            '5' => 'Did you know the coming skin is completely random?',
            '6' => 'Random skin incoming...',
            '7' => 'One more block...',
            '8' => 'Sorting inventory...',
            '9' => 'Crafting diamond pickaxe...',
            '10' => 'Looking for Herobrine...',
        ],
    ],
    'feed' => [
        'title' => 'Feed',
        'following' => 'Following',
        'sign-up' => 'Sign up or log in to join the conversation.',
        'link-account' => 'Link your Minecraft account to join the conversation.',
        'placeholder' => 'What is happening?',
        'audience' => 'Audience',
        'audience-title' => 'Who can see this?',
        'everyone' => 'Everyone',
        'everyone-info' => 'Anyone on or off SkinMC.',
        'followers' => 'Followers',
        'followers-info' => 'Signed in or members following me.',
        'private' => 'Only me',
        'private-info' => 'Private post only I can see.',
        'submit' => 'Post',
        'like' => 'Like',
        'comment' => 'Reply',
        'share' => 'Share',
        'remaining' => 'Remaining',
        'profile' => 'Posts by :username',
        'posts' => 'All posts',
        'my-posts' => 'My posts',
        'view-all' => 'View all posts',
        'post' => [
            'meta' => ':username on SkinMC: :text',
            'title' => 'Post',
            'created' => 'Status update posted!',
            'confirm-delete' => 'Are you sure you would like to delete this post? It can not be undone.',
            'delete' => 'Delete post',
            'deleted' => 'Your post was deleted.',
        ],
        'repost' => [
            'button' => 'Repost',
            'quote_button' => 'Quote',
            'title' => 'Repost this post',
            'quote_title' => 'Quote post',
            'quote_label' => 'Add a comment (optional)',
            'quote_placeholder' => 'Add your thoughts...',
            'reposted' => 'reposted',
            'success' => 'Reposted!',
            'removed' => 'Repost removed.',
            'already_reposted' => 'You have already reposted this.',
            'undo' => 'Undo repost',
            'original_deleted' => 'The original post has been deleted.',
            'deleted_post' => 'This post has been deleted',
        ],
        'hashtags' => [
            'title' => 'Trending',
            'trending-now' => 'Trending now',
            'post' => 'post',
            'posts' => 'posts',
            'posts-count' => ':count post|:count posts',
            'hashtag' => 'Hashtag',
            'hashtags' => 'Hashtags',
            'no-results' => 'No hashtags found',
        ],
        'search' => [
            'title' => 'Search',
            'placeholder' => 'Search posts, hashtags...',
            'no-results' => 'No results found',
            'posts' => 'Posts',
            'no-hashtags-found' => 'No hashtags found matching ":query"',
            'no-results-found' => 'No results found for ":query"',
        ],
        'poll' => [
            'title' => 'Poll',
            'create' => 'Create a poll',
            'option' => 'Option',
            'add_option' => 'Add option',
            'duration' => 'Duration',
            'duration_1' => '1 day',
            'duration_3' => '3 days',
            'duration_7' => '7 days',
            'votes' => '{0} votes|{1} vote|[2,*] votes',
            'ended' => 'Poll ended',
            'ends_in' => 'Ends :time',
            'login_required' => 'Sign in to vote',
        ],
        'gif' => [
            'title' => 'GIF',
            'search_placeholder' => 'Search KLIPY for GIFs...',
            'no_results' => 'No GIFs found',
            'powered_by' => 'Powered by',
            'categories' => 'Categories',
            'trending' => 'Trending',
        ],
        'media' => 'Media',
        'follow-suggestions' => 'Follow the team',
        'explore' => 'Explore',
        'hashtag' => 'Hashtag',
        'no_users' => 'No users found.',
        'stories' => [
            'archive' => [
                'title' => 'Story Archive',
                'subtitle' => 'Your archived stories are only visible to you',
                'empty' => 'No archived stories yet',
                'empty-description' => 'Stories you post will appear here after 24 hours.',
                'action' => 'Archive',
                'archived' => 'Story moved to archive.',
                'already-archived' => 'Story is already archived.',
            ],
        ],
    ],
    'private' => [
        'title' => 'Private posts',
        'text' => 'This post is private.',
    ],
    'liked' => [
        'title' => 'Liked',
    ],
    'following' => [
        'title' => 'Following',
        'text' => 'Sign in to view this post.',
    ],
    'tags' => [
        'empty' => 'No tags to vote on yet',
        'empty-subtitle' => 'Be the first to add one',
    ],
    'inbox' => [
        'title' => 'Messages',
        'details' => 'Details',
        'message_user' => 'Message',
        'write_message' => 'Write a message',
        'empty' => [
            'no_message_selected' => 'No message selected',
            'open_or_start_conversation' => 'Open a conversation from the message list, or start a new one.',
            'no_messages' => 'No unread messages',
            'start_conversation' => 'Once you start a new conversation, your messages will be displayed here.',
            'conversation' => 'This is the beginning of your conversation with :username.',
            'users' => 'Unable to find any users that match the current query.',
        ],
        'typing' => ':username is typing...',
        'new_message' => 'New message',
        'mark_unread' => 'Mark unread',
        'send_message' => 'Send message',
        'delete_message' => 'Delete message for you',
        'latest_conversations' => 'Latest conversations',
        'delete_conversation' => 'Delete conversation',
        'show_details' => 'Show details',
        'hide_details' => 'Hide details',
        'unread' => 'Unread',
        'deleted' => 'Deleted',
        'report_message' => 'Report message',
        'add_reaction' => 'Add reaction',
        'today' => 'Today',
        'reconnect' => 'Please reconnect your Minecraft account to chat',
        'account_disconnected' => 'This user disconnected their linked Minecraft account.',
        'saved_messages' => 'Saved messages',
        'new_message_to_label' => 'To',
        'external-link-to' => 'This link will take you to',
        'external-link-confirmation' => 'Are you sure you want to go there?',
        'external-link' => 'External link',
        'reply' => 'Reply',
    ],
    'server' => [
        'manage' => [
            'stats' => 'Stats',
        ],
    ],
    'report' => [
        'button' => 'Report',
        'title' => 'Report content',
        'describe' => 'Briefly describe why you are reporting this',
        'select' => 'Select report reason',
        'submit' => 'Submit report',
        'reasons' => [
            'INAPPROPRIATE_CONTENT' => 'Inappropriate content',
            'SPAM' => 'Spam',
            'HARASSMENT' => 'Harassment',
            'OTHER' => 'Other',
        ],
    ],
    'leaderboard' => [
        'title' => 'Leaderboard',
        'description' => 'View the SkinMC leaderboard of users.',
        'headline' => 'Top 10',
        'all-time-invites' => 'All time invites',
        'all-time-xp' => 'All time XP',
        '30-day-xp' => '30 days XP',
    ],
    'boards' => [
        'title' => 'Boards',
        'meta_title' => 'My Boards',
        'meta_description' => 'Organize your saved Minecraft skins, creations, and banners into boards.',
        'all_pins' => 'All Pins',
        'save' => 'Save',
        'saved' => 'Saved',
        'save_to_board' => 'Save to board',
        'save_to_label' => 'Save to: :board',
        'saved_to_label' => 'Saved to :board',
        'choose_board' => 'Choose board',
        'search_boards' => 'Search',
        'no_boards' => 'No boards yet',
        'no_boards_match' => 'No boards found',
        'create_board' => 'Create board',
        'create' => 'Create',
        'cancel' => 'Cancel',
        'add' => 'Add',
        'create_placeholder' => 'Like "Medieval Builds" or "PvP Loadouts"',
        'field_name' => 'Name',
        'secret_label' => 'Secret',
        'secret_description' => 'So only you and collaborators can see it.',
        'keep_secret' => 'Keep this board secret',
        'add_collaborators' => 'Add collaborators (optional)',
        'collaborator_search_placeholder' => 'Search by name or email',
        'edit_board' => 'Edit board',
        'leave_board' => 'Leave board',
        'leave_board_confirm' => 'Leave this board? You will no longer be able to add pins to it.',
        'delete_board' => 'Delete board',
        'delete_confirm' => 'Are you sure you want to delete this board? All pins will be removed.',
        'empty_headline' => 'No pins yet',
        'empty_subtitle' => 'Start saving skins, creations, and banners to this board.',
        'empty_boards_headline' => 'No boards yet',
        'empty_boards_subtitle' => 'Save your first skin to automatically create a board.',
        'browse_skins' => 'Browse skins',
        'pins_count' => '{0} No pins|{1} 1 pin|[2,*] :count pins',
        'secret_badge' => 'Secret',
        'public_boards' => 'Boards',
        'collaborator_unknown_user' => 'Someone',
        'collaborating' => 'Collaborating',
        'your_boards' => 'Your boards',
        'boards_you_collaborate_on' => 'Boards you collaborate on',
        'empty_collaborating' => 'No boards you collaborate on yet.',
        'toast' => [
            'saved_to' => 'Saved to :board',
            'removed' => 'Pin removed',
            'created' => 'Board created',
            'updated' => 'Board updated',
            'deleted' => 'Board deleted',
            'collaborator_added' => 'Collaborator added',
            'collaborator_removed' => 'Collaborator removed',
            'left_board' => 'You left the board',
        ],
    ],
];
