<?php

return [
    'title' => 'SkinMC.me', 'subtitle' => 'Your corner of Minecraft.', 'links' => 'Links',
    'configure' => 'Your links', 'configure_hint' => 'Add your favourites. Make them yours.',
    'add_collection' => 'Add collection', 'collection_title' => 'Collection title',
    'collection_list' => 'List', 'collection_grid' => 'Grid', 'collection_carousel' => 'Carousel',
    'collection_untitled' => 'Untitled collection', 'collection_item' => 'item', 'collection_items' => 'items',
    'collection_hidden' => 'Hidden', 'collection_actions' => 'Collection actions',
    'hide_collection' => 'Hide collection', 'show_collection' => 'Show collection',
    'edit_title' => 'Edit title', 'edit_link' => 'Edit link', 'link_actions' => 'Link actions', 'link_collapse' => 'Collapse link',
    'hide_link' => 'Hide link', 'show_link' => 'Show link',
    'insert_here' => 'Add here', 'insert_link' => 'Link', 'insert_collection' => 'Collection', 'dismiss' => 'Dismiss',
    'collection_collapse' => 'Collapse collection', 'collection_expand' => 'Expand collection',
    'collection_remove' => 'Remove collection',
    'collection_remove_hint' => 'Links stay on your page. Only this collection and its selected creations are removed.',
    'collection_empty' => 'Drag links here, or add something below.',
    'collection_hidden_hint' => 'This collection and everything inside it are hidden.',
    'add_creations' => 'Add creations', 'creation_actions' => 'Creation actions', 'creation_unavailable' => 'Creation unavailable',
    'creation_unavailable_hint' => 'It may be private or no longer available. You can remove it from this collection.',
    'creations_description' => 'Choose which public creations to show in this collection.',
    'creations_categories' => 'Creation categories', 'creations_retry' => 'Try again',
    'creations_loading' => 'Loading creations', 'creations_selected' => 'selected',
    'creations_cancel' => 'Cancel', 'creations_done' => 'Done', 'close' => 'Close',
    'add_link' => 'Add new link', 'empty_links' => 'Add your first link to get started.',
    'link_title' => 'Link title', 'destination' => 'Destination URL', 'icon' => 'Icon', 'visible' => 'Visible',
    'remove' => 'Remove', 'up' => 'Move up', 'down' => 'Move down', 'reorder' => 'Drag to reorder',
    'layout' => 'Layout', 'thumbnail' => 'Thumbnail', 'compact' => 'Compact', 'featured' => 'Featured',
    'compact_hint' => 'A simple, direct link.', 'featured_hint' => 'Make your link stand out with a large card.',
    'example_link' => 'My link', 'thumbnail_hint' => 'JPEG, PNG or WebP, up to 5 MiB. A wide image (1200 × 375) works well for Featured.',
    'upload_image' => 'Upload image', 'change_image' => 'Change image', 'uploading' => 'Uploading…',
    'remove_image' => 'Remove image', 'socials' => 'Social icons',
    'socials_hint' => 'A few more places to find you.', 'add_social' => 'Add social icon', 'empty_socials' => 'No social icons yet.',
    'platform' => 'Platform', 'status' => 'Status', 'status_title' => 'What’s happening?',
    'status_hint' => 'A little update, right above your avatar.', 'status_label' => 'Status message',
    'status_publish_hint' => 'Plain text and emoji, up to 80 characters.',
    'clear' => 'Clear', 'design' => 'Design', 'design_title' => 'Design your page',
    'design_hint' => 'Choose your theme, wallpaper, buttons and colours.', 'theme' => 'Theme',
    'wallpaper' => 'Wallpaper', 'wallpaper_hint' => 'JPEG, PNG or WebP, up to 5 MiB and 20 megapixels.',
    'buttons' => 'Buttons', 'button_style' => 'Button style', 'button_shape' => 'Button shape',
    'text' => 'Text', 'font' => 'Font', 'colors' => 'Colours', 'stickers' => 'Stickers',
    'sticker' => 'Sticker', 'your_stickers' => 'Your stickers', 'add_sticker' => 'Add sticker', 'done' => 'Done',
    'turn_left' => 'Turn left', 'turn_right' => 'Turn right', 'move_to' => 'Move to',
    'position_top' => 'Top', 'position_middle' => 'Middle', 'position_bottom' => 'Bottom',
    'decorate' => 'Decorate', 'sticker_hint' => 'Tap a sticker to edit it. Drag it on the preview to move it.',
    'sticker_search' => 'Find a sticker', 'search' => 'Search', 'trending' => 'Trending', 'more_stickers' => 'More stickers',
    'sticker_unavailable' => 'This sticker can’t be previewed right now.',
    'sticker_empty' => 'No stickers found. Try another search.', 'previous' => 'Previous', 'next' => 'Next',
    'anchor' => 'Anchor', 'profile' => 'Profile', 'footer' => 'Footer', 'x' => 'Horizontal position', 'y' => 'Vertical position',
    'size' => 'Size', 'rotation' => 'Rotation', 'z_index' => 'Layer', 'save' => 'Save changes',
    'publish' => 'Publish changes', 'unpublish' => 'Unpublish', 'draft' => 'Private draft',
    'published' => 'Published',
    'publication_toggle' => 'Publish page', 'publication_on_hint' => 'Your page is public. Save changes to update it.',
    'publication_off_hint' => 'Your page is private. Turn this on to publish it.',
    'pending_publication' => 'Saved changes are waiting to go live.', 'all_saved' => 'All changes saved',
    'custom' => 'Custom', 'image' => 'Image', 'fill' => 'Fill',
    'sticker_loading' => 'Loading stickers…', 'sticker_limit' => 'You’ve added 12 stickers. Remove one to add another.', 'unpublished_changes' => 'Unsaved changes', 'saving' => 'Saving…',
    'read_only' => 'You need an active Minecraft profile without restrictions to edit your page. Your saved page and analytics are still here.',
    'no_profile' => 'Connect a Minecraft profile to create your page.', 'profile_settings' => 'Edit profile information',
    'synced' => 'Your name, biography, avatar and badges stay in sync with your SkinMC profile.',
    'preview' => 'Live preview', 'copy' => 'Copy address', 'preview_wait' => 'Loading your SkinMC.me preview…',
    'preview_pending' => 'Add a title and URL to each visible link to update the preview.',
    'preview_size' => 'Preview width', 'mobile' => 'Mobile', 'desktop' => 'Desktop',
    'preview_unavailable' => 'The preview couldn’t load. Your edits are still here.', 'retry_preview' => 'Retry preview',
    'reload' => 'Reload saved draft',
    'conflict' => 'This page was updated somewhere else. Your edits are still here. Reload the saved draft before trying again.',
    'retained' => 'Your saved pages', 'new_page' => 'Current profile', 'analytics' => 'Analytics',
    'edit_page' => 'Edit page', 'insights' => 'Insights', 'editor_tabs' => 'Page editor', 'preview_tab' => 'Preview',
    'analytics_overview' => 'Overview', 'analytics_range' => 'Time period',
    'analytics_loading' => 'Loading the last :days days…',
    'analytics_page_views' => 'Page views', 'analytics_link_clicks' => 'Link clicks',
    'analytics_chart_title' => 'Daily page views and link clicks',
    'analytics_chart_summary' => 'Page views: :views. Link clicks: :clicks. :range. Exact daily counts are available below.',
    'analytics_explore_chart' => 'Explore daily activity', 'analytics_chart_help' => 'Use the left and right arrow keys to explore each day. Home and End move to the first and last day.',
    'analytics_day_summary' => 'Views: :views · Clicks: :clicks',
    'analytics_daily' => 'Daily breakdown', 'analytics_no_activity' => 'No activity yet',
    'analytics_top_links' => 'Top links', 'analytics_top_links_hint' => 'Links and social icons, ordered by clicks.',
    'analytics_no_clicks' => 'Your most-clicked links will appear here.',
    'analytics_show_all' => 'Show all links', 'analytics_show_less' => 'Show fewer',
    'analytics_hint' => 'Totals are approximate, not unique visitors. Blocked requests aren’t counted and some bot traffic may be included.',
    'days' => ':days days', 'views' => 'Total views', 'clicks' => 'Total clicks', 'date' => 'Date (UTC)',
    'link_click' => 'click', 'link_clicks' => 'clicks',
    'item' => 'Link or social icon', 'removed_link' => 'Removed link', 'analytics_empty' => 'Your totals will appear after your page receives visits.',
    'themes' => ['clean' => 'Clean', 'midnight' => 'Midnight', 'grass' => 'Grass', 'amethyst' => 'Amethyst'],
    'fonts' => ['system' => 'System', 'satoshi' => 'Satoshi', 'minecraft' => 'Minecraft'],
    'styles' => ['outline' => 'Outline', 'filled' => 'Filled'],
    'shapes' => ['pill' => 'Pill', 'rounded' => 'Rounded', 'square' => 'Square'],
    'color_labels' => ['background' => 'Background', 'surface' => 'Surface', 'text' => 'Text', 'muted' => 'Secondary text',
        'button' => 'Button', 'button_text' => 'Button text', 'border' => 'Border', 'accent' => 'Accent'],
    'validation' => [
        'invalid' => 'Check your page settings and try again.',
        'collection_link' => 'Choose a link that isn’t already in another collection.',
        'collection_source' => 'A creation can appear only once in each collection.',
        'collection_limit' => 'Choose up to :max creations on this page.',
        'content_order' => 'Something went wrong with the page order. Please try again.',
        'creation_unavailable' => 'This creation is no longer available. Choose another public creation.',
        'creation_category' => 'Choose an available creation category.',
        'creation_page' => 'Choose a valid page of creations.',
        'length' => 'Use at most :max characters. Some emoji count as two.', 'boolean' => 'Choose on or off.',
        'integer' => 'Enter a whole number.', 'number' => 'Enter a valid number.', 'url' => 'Enter a valid URL without spaces or login details.',
        'duplicate' => 'Something was duplicated. Please try again.', 'anchor' => 'Choose an existing link, profile or footer.',
        'static' => 'Animated stickers need a static preview image.', 'area' => 'Use an image with no more than 20 megapixels.',
        'image' => 'Upload a valid JPEG, PNG or WebP image.', 'asset' => 'Choose an image uploaded for this page.',
        'storage' => 'Image uploads are unavailable right now. Please try again later.',
        'selection' => 'Please select this sticker again from KLIPY. We couldn’t verify it.',
        'selection_expired' => 'This sticker selection expired. Search for it and select it again.',
    ],
    'js' => [
        'collection_untitled' => 'Untitled collection',
        'collection_added' => 'Collection added.',
        'collection_removed' => 'Collection removed. Your links are still here.',
        'content_moved' => 'Position updated.',
        'creation_removed' => 'Creation removed from this collection.',
        'creations_updated' => 'Collection updated.',
        'link_added' => 'Link added.',
        'saved' => 'Saved! Your page is private.', 'published' => 'Published! Your page will update in a moment.',
        'unpublished' => 'Unpublished! Your page will be hidden in a moment.',
        'failed' => 'Something went wrong. Your edits are still here. Try again.',
        'conflict' => 'This page was updated somewhere else. Your edits are still here. Reload the saved draft before trying again.',
        'copied' => 'Address copied!', 'copy_failed' => 'Couldn’t copy the address. You can copy it above.',
        'image_uploaded' => 'Image added. Save when you’re ready.',
        'analytics_failed' => 'Insights couldn’t load. Please try again.',
    ],
];
