<?php

return [
    'login' => [
        'title' => 'התחבר',
        'email' => 'כתובת אימייל',
        'password' => 'סיסמה',
        'button' => 'התחבר',
        'editor_save_context' => "Log in to save your skin to the gallery. Your work won\\'t be lost.",
        'forgot' => 'שכחת סיסמא?',
        'reset' => 'איפוס',
        'register' => 'עדיין אין לך חשבון?',
        'signup' => 'הירשם',
        'google' => 'היכנס באמצעות גוגל',
        'microsoft' => 'המשך עם מיקרוסופט',
        'facebook' => 'היכנס באמצעות פייסבוק',
        'twitter' => 'היכנס באמצעות טוויטר',
        'divider' => 'או',
    ],
    'signup' => [
        'title' => 'הירשם',
        'existing' => 'כבר יש לך משתמש?',
        'button' => 'קבל והמשך',
        'terms_by_selecting' => 'על ידי בחירה של',
        'terms_agree_to' => ', אני מסכים ל-SkinMC',
        'terms_acknowledge' => 'ומבין את ה',
    ],
    'recover' => [
        'title' => 'שחזר משתמש',
        'description' => 'איבדת את הסיסמה שלך? שחזר את הסיסמה שלך על ידי הזנת כתובת המייל שאיתה נרשמת.',
        'button' => 'שלח מייל לשחזור',
        'found' => 'מצאת את הסיסמה שלך?',
    ],
    'logout' => [
        'title' => 'התנתק',
        'description' => 'האם אתה בטוח שברצונך להתנתק ממשתמש הSkinMC שלך?',
        'logout' => 'התנתק',
        'cancel' => 'ביטול',
    ],
    'profile_qrcode' => [
        'title' => 'סרוק ברקוד',
        'done' => 'סיום',
    ],
    'language' => [
        'title' => 'שפה',
        'description' => 'בחר את השפה שלך',
        'contribute' => 'תרום',
        'contribute_add' => 'הוספת תרגום',
        'updated' => 'השפה שלך נקבעה',
    ],
    'copied' => 'הועתק ללוח!',
    'close' => 'סגור',
    'feedback' => [
        'title' => 'משוב',
        'type' => [
            'select' => 'בחר סוג משוב',
            'label' => 'סוג משוב',
            'comment' => 'תגובות',
            'question' => 'שאלות',
            'bug' => 'דיווח באג',
            'feature' => 'בקשת תכונה',
        ],
        'submit' => 'שלח',
        'nps' => 'מ-0 עד 10 מה הסיכוי שהיית ממליץ על SkinMC לחבר?',
        'success' => [
            'title' => 'תודה רבה!',
            'message' => 'הודעתך נשלחה, צפה לתשובה בהקדם! לשאלות נוספות, תרגיש חופשי להצטרף לדיסקורד או לשלוח עוד הודעה.',
        ],
    ],
];
