<?php

return [
    'skins' => 'סקינים',
    'avatars' => 'אווטרים',
    'editor' => 'עורך',
    'heads' => 'ראשים',
    'capes' => 'קייפס',
    'servers' => 'שרתים',
    'achievement' => 'הישגים',
    'armor' => 'ארמור סטנד',
    'banners' => 'באנרים',
    'banner' => 'Banner Editor',
    'banner_gallery' => 'Banner Gallery',
    'profile' => 'הפרופיל שלי',

    'generators' => 'מחוללים',

    // Navigation dropdowns
    'feed' => 'Feed',
    'discover' => 'Discover',
    'mods' => 'Mods',
    'shaders' => 'Shaders',
    'resource_packs' => 'Resource Packs',
    'modpacks' => 'Modpacks',
    'datapacks' => 'Data Packs',
    'plugins' => 'Plugins',

    'logout' => 'התנתק',
    'register' => 'הירשם',
    'login' => 'התחבר',
    'about' => 'מידע',
    'contact' => 'צרו קשר',
    'faqs' => 'שאלות נפוצות',

    'minecraft_name' => 'שם משתמש',
    'minecraft_uuid' => 'UUID',
    'what' => 'מה',
    'recent_searches' => 'חיפושים אחרונים',
    'username' => 'שם משתמש',
    'uuid' => 'UUID',
    'search' => 'חיפוש',
    'search_placeholder' => 'נסה',
    'search_placeholder_uuid' => 'הכנס UUID',
    'start_search' => 'התחל בחיפוש',
    'cancel_search' => 'ביטול',
    'search_type' => 'סוג חיפוש',
    'search_type_all' => 'כל התוצאות',
    'profiles' => 'פרופילים',
    'view_skin' => 'הצג סקין',
    'edit_skin' => 'ערוך סקין',
    'make_avatar' => 'צור אווטאר',
    'find_heads' => 'מצא ראשי שחקנים',
    'no_results_found' => 'No suggestions yet. Hit Enter to look it up.',

    'home' => 'בית',
    'help' => 'עזרה',
    'tools' => 'כלים',
    'more-tools' => 'כלים נוספים',
    'skin_viewer' => 'מציג סקינים',
    'avatar_maker' => 'יוצר אווטארים',
    'collections' => 'קולקציות',
    'popular_skins' => 'סקינים פופולריים',
    'cartoon_skins' => 'סקינים מצוירים',
    'animal_skins' => 'סקינים של חיות',
    'community' => 'קהילה',
    'imprint' => 'חותמות',
    'cookies' => 'עוגיות',
    'terms' => 'תנאי השירות',
    'privacy' => 'מדיניות פרטיות',
    'app' => 'אפליקציה',
    'mod' => 'מוד',
    'totem' => 'טוטמים',
    'cube' => 'Cube',
    'new' => 'New',

    'feedback' => 'משוב',
    'status' => 'סטאטוס',
    'recent_searches_placeholder' => 'תוך כדי הקלדה, החיפושים הקודמים שלך יופיעו כאן.',
    'recent_views_placeholder' => 'לאחר ביקור בכמה פרופילים, הפרופילים שבהם ביקרת בעבר יופיעו כאן.',
    'moderate' => 'נהל',
    'listings' => 'רשימות',
    'add' => 'הוסף',

    // Autocomplete types
    'autocomplete' => [
        'profile' => 'Profile',
        'server' => 'Server',
        'project' => 'Project',
        'skin_tag' => 'Skin Tag',
        'server_category' => 'Server Category',
        'modrinth_category' => 'Project Category',
    ],

    'theme' => [
        'title' => 'Theme',
        'dark' => 'כהה',
        'light' => 'בהיר',
        'auto' => 'Auto',
    ],

    'language' => 'Language',
];
