<?php

return [
    'auth' => [
        'login' => [
            'title' => 'ברוך הבא לSkinMC',
        ],
        'register' => [
            'title' => 'הירשם לSkinMC',
            'subtitle' => 'התחל וצור לעצמך משתמש כדי לקבל גישה מלאה.',
        ],
    ],

    'home' => [
        'hero_slogan' => 'המקום שלך בשביל סקינים למיינקראפט.',
        'hero_slogan_alt_1' => 'Everything Minecraft. One place.',
        'hero_slogan_alt_2' => 'Where Minecrafters meet.',
        'hero_cta' => 'תפתיע אותי',
        'hero_explore_cta' => 'גלה סקינים',
        'skin_viewer' => 'מציג סקינים',
        'skin_viewer_detail' => 'מצא :count סקינים',
        'skin_editor' => 'עורך סקינים',
        'skin_editor_detail' => 'עצב סקין משלך',
        'avatar_maker' => 'יוצר אווטרים',
        'avatar_maker_detail' => 'צור לעצמך תמונת פרופיל של אווטר משלך.',
        'trending' => 'פופולרי',
        'minecraft_skin' => 'סקין מיינקראפט',
        'favourite' => 'מועדף',
        'collections' => 'קולקצייה',
        'collections_detail' => 'מגוון סקינים בשביל כל מצב',
        'about_skinmc' => 'על SkinMC',
        'about_find' => 'מצא כל סקין',
        'about_find_detail' => 'השתמש בחיפוש של SkinMC כדי לחפש כל משתמש מיינקראפט כדי למצוא ולהוריד את הסקין החדש הבא שלך.',
        'about_download' => 'הורד או ערוך',
        'about_download_detail' => 'מצאת סקין שאתה אוהב? הוסף אותו למועדפים, וערוך או הורד אותו כדי להפוך אותו לשלך.',
        'about_platform' => 'חוצה פלטפורמות',
        'about_platform_detail' => 'רוצה לקחת את הסקין לדרך? סרוק את הברקוד ותשמור את התמונה בטלפון שלך בשביל מיינקראפט PE.',
        'meta' => [
            'title' => 'מציג סקינים של מיינקראפט',
            'description' => 'ראה או הורד סקינים של מיינקראפט, מצא את הסקינים הכי טובים באוספים נבחרים, בדוק זמינות של שמות משתמש והיסטוריה ועוד כל כך הרבה דברים!',
        ],
        'recently_viewed' => 'נראה לאחרונה',
        'explore_title' => 'נסה משהו חדש',
        'explore' => 'גלה רעיונות וכלים חדשים',
        'servers_browse' => 'רשימת שרתים',
        'servers' => 'גלה את שרתי המיינקראפט הכי טובים',
        'heads' => 'ראשי מיינקראפט',
        'head_description' => 'גלה את הדאטאבייס של ראשי המיינקראפט, או צור חדשים כאלה.',
        'achievement' => 'גנרטור הישגים',
        'achievement_detail' => 'צור משלך הישגים מותאמים אישית.',
        'continue' => 'המשך לגלות',
    ],
    'profile' => [
        'verified' => 'פרופיל מאומת',
        'minecraft_profile' => 'פרופיל מיינקראפט',
        'show_qr_code' => 'הצג ברקוד',
        'favourite' => 'מועדף',
        'user_title' => 'הסקין של :username',
        'user_views' => 'נצפה :views פעם|נצפה :views פעמים',
        'uuid' => 'UUID',
        'copy' => 'העתק',
        'link' => 'קישור',
        'skin_history' => 'היסטוריית סקינים (:skins)',
        'username_history' => 'היסטוריית שמות',
        'username_history_name' => 'שם',
        'username_history_timestamp' => 'שונה ב',
        'username_history_initial_name' => 'שם התחלתי',
        'user_downloads' => ':downloads הורדות|:downloads הורדות',
        'download_skin' => 'הורד סקין',
        'apply_skin' => 'השתמש בסקין',
        'capes' => 'קייפס',
        'claim_profile' => 'האם אתה :username? קבל את הפרופיל שלך כדי לאמת אותו ולהתאים אותו!',
        'claimed' => 'פרופיל תפוס',
        'meta_description' => 'צפה והורד את הסקין של :username. ראה את הUUID, היסטוריית השמות, נתונים מפורטים, ועוד לגביהם',
        'created_at' => 'עודכן: :changed_at',
        'skins' => [
            'meta_title' => 'היסטוריית הסקינים של :username',
            'meta_description' => 'הצג את היסטוריית הסקינים והסקינים הישנים של :username. השתמש בהיסטוריה כדי לצפות בסקינים ישנים, גיבוי ושימוש בהם.',
            'title' => 'היסטוריית הסקינים',
        ],
        'qr_code' => [
            'meta_title' => 'הברקוד של :username',
            'meta_description' => 'הברקוד המותאם אישית של הפרופיל של :username',
        ],
        'sub_nav' => [
            'skin' => 'סקין',
            'about' => 'מידע',
            'usernames' => 'שמות משתמש',
            'head' => 'ראשים',
            'comments' => 'תגובות',
        ],
        'cape' => 'קייפס',
        'elytra' => 'אלייטרה',
        'nametag' => 'תג שם',
        'animation' => 'אנימציה',
        'rotation' => 'תזוזה',
        'none' => 'ללא',
        'idle' => 'בהמתנה',
        'walk' => 'הולך',
        'run' => 'רץ',
        'fly' => 'עף',
        'follow' => 'עקוב',
        'following' => 'עוקב',
        'unfollow' => 'הסר מעקב',
        'followers' => 'עוקב|עוקבים',
        'toast' => [
            'following' => 'אתה עכשו עוקב אחרי :username!',
            'follow-self-error' => 'מצטערים :username, אתה לא יכול לעקוב אחר עצמך.',
            'unfollowed' => 'אתה כבר לא עוקב אחרי :username',
        ],
        'edit' => 'ערוך פרופיל',
        'joined' => 'הצטרף',
        'role' => 'Role',
        'server-fav-list-empty' => 'Looks like :username hasn\'t got any favourite servers yet. Once :username has saved a server as their favourite, you can see it here.',
        'server-own-list-empty' => 'Looks like :username hasn\'t got any servers yet. Once :username has listed a server, you can see it here.',
        'capes-list-empty' => 'Looks like :username isn\'t wearing any capes yet. Once :username is wearing a cape, you can see it here.',
        'feed-own-list-empty' => 'Looks like you haven\'t posted anything to the feed yet! Once you post, you can see your posts here.',
        'feed-list-empty' => 'Hmm, it seems like :username hasn\'t posted anything to the feed yet. Once :username posts something you can see it here.',
        'following-own-list-empty' => 'נראה שאתה לא עוקב אחרי אף אחד עדיין! ברגע שתתחיל לעקוב אחרי אנשים, תוכל לראות אותם כאן.',
        'following-list-empty' => 'הממ, נראה ש :username לא עוקב אחרי אף אחד. ברגע ש :username יתחיל לעקוב אחרי אנשים תוכל לראות אותם כאן.',
        'followers-own-list-empty' => 'ברגע שאנשים יתחילו לעקוב אחריך, הם יופיעו כאן.',
        'followers-list-empty' => 'הממ, נראה שאף אחד לא עוקב אחרי :username . תהיה הראשון לעקוב אחרי :username. ברגע שיותר אנשים יתחילו לעקוב, תוכל לראות אותם כאן.',
        'render' => 'מציג',
        '3d' => 'הצגת תלת-מימד',
        '2d' => 'הצגת דו-מימד',
        'name-history-info' => 'היסטוריית השמות מתחילה להעילם. Mojang מחקה את הגישה להיסטוריית השמות בAPI שלהם ב13 בספטמבר 2022, מה שגרם להם לא להיות זמינים יותר. אם אתה רוצה להסתיר את היסטוריית השמות שלך, תפוס את הפרופיל שלך, לך להגדרות והפוך את זה לפרטי.',
        'edit-skins' => 'Edit skin history',
        'hide-skin' => 'הסתר סקין',
        'show-skin' => 'חשוף סקין',
        'edit-skin' => 'ערוך סקין',
        'servers' => [
            'title' => ':username\'s servers',
        ],
        'cape-list' => [
            'title' => ':username\'s capes',
        ],
    ],
    'skin' => [
        'meta' => [
            'title' => 'הסקין של :username',
            'description' => 'סקין של מיינקראפט. צפה והורד את הסקין, וראה איזה עוד שחקנים משתמשים בסקין הזה.',
            'tags' => 'הסקין של :username, סקין :username, סקין מיינקראפט, הסקין המותאם אישית של :username, הורד סקין, שחקנים נוספים עם אותו הסקין',
        ],
        'title' => 'הסקין של :username',
        'head' => 'פקודות לראשים',
        'head_info' => 'לשימוש עם קומנד בלוקס',
        'first_wearing' => 'השחקן הראשון שנראה לובש את הסקין הזה:',
        'profiles' => 'הפרופיל של :profile|הפרופילים של :profiles',
        'profiles_title' => ':profiles פרופילים עם הסקין הזה|:profiles פרופילים עם הסקין הזה',
        'screenshot' => 'Screenshot',
    ],
    'skins' => [
        'meta' => [
            'title' => 'דף :current - כל הסקינים',
            'description' => 'Browse through our :last pages list of :total custom Minecraft skins and download your favourite next skin!',
            'tags' => 'הסקין של :username, סקין :username, סקין מיינקראפט, הסקין המותאם אישית של :username, הורד סקין, שחקנים נוספים עם אותו הסקין',
            'tags-title' => 'סקינים מיינקראפט של:tag',
            'tags-description' => 'Browse through our :last pages list of :total :tag Minecraft skins and download your favourite :tag skin!',
            'tags-metatags' => ':tag Minecraft Skin, :tag Skin, Minecraft Skin, :tag Custom Minecraft Skin, Download :tag Skin, Minecraft :tag Skins',
        ],
        'title-skin-tags' => 'Tagged Minecraft Skins',
        'subtitle' => 'Page :current of :last from :total Minecraft Skins',
        'subtitle-skin-tags' => 'Page :current of :last from :total Tagged Minecraft Skins',
        'sort_by' => 'Sort by',
        'latest' => 'Latest skins',
        'most_profiles' => 'Most used skins',
        'profiles_today' => 'Most used today',
        'profiles_this_week' => 'Most used this week',
        'profiles_this_month' => 'Most used this month',
        'default' => 'Default sorting',
        'this_month' => 'Added this month',
        'this_week' => 'Added this week',
        'today' => 'התווסף היום',
        'random' => 'רנדומלי',
        'similar' => 'סקינים דומים',
        'no_similar_skins' => 'לא נמצאו סקינים דומים עדיין.',
        'favorite' => ':count מועדפים|:count מועדפים',
    ],
    'skin-tags' => [
        'faq' => 'What are tags?',
        'about' => 'Tags are a way you to add relevant categories to skins. Adding tags allows you to discover more skins you like easily!',
        'guidelines' => [
            'good' => [
                'title' => 'General guidelines for good tags are:',
                'short' => 'Short',
                'descriptive' => 'Descriptive',
                'spelled' => 'Spelled correctly',
            ],
            'bad' => [
                'title' => 'Do not add tags such as:',
                'general' => 'Too general',
                'specific' => 'Too specific',
                'too-many-tags' => 'Should be three separate tags',
                'spelling' => 'Should be :example',
            ],
        ],
        'toast' => [
            'added' => 'Tag ”:tag” added for voting',
            'removed' => 'Tag ”:tag” has been removed',
            'upvote' => 'Upvoted ”:tag”',
            'downvote' => 'Downvoted ”:tag”',
        ],
        'vote' => [
            'up' => 'Upvote',
            'down' => 'Downvote',
            'remove' => 'Remove vote',
        ],
    ],
    'contact' => [
        'contact' => 'צור קשר',
        'email' => 'תרגישו חופשיים לכתוב לנו לכתובת <a href="mailto:support@skinmc.net">support@skinmc.net</a> במידה ויש לכם שאלות.',
        'faq' => 'אנחנו קודם נבקש ממכם לבדוק את <a href=":link">דף השאלות הנפוצות</a> אם השאלה שלכם נענתה כבר שם.',
        'other' => 'דרכים אחר ליצירת קשר',
        'other_discord' => 'הצטרפו לשרת הדסיקורד כדי להתחבר עם אחרים, לדבר על משחקים, לשתף את החבילות האהובות עליכם ולקבל עזרה מהקהילה.',
        'other_twitter' => 'עקבו אחרינו בטוויטר כדי להתעדכן אם יש עדכון או אפשרות חדשה שיוצאת, וכדי לראות את הסקין של השבוע ועוד.',
        'other_instagram' => 'עקבו אחרי SkinMC באינטסגרם כדי לצפות סקינים מגניבים ומדהימים.',
        'other_facebook' => 'הפכו למעריצים שלנו בפייסבוק ותראו את כל הפוסטים שתוכלו להגיב עליהם ולדבר עם אחרים בזמן שאתם נהנים מתוכן של מיינקראפט.',
    ],
    'about' => [
        'intro' => '<span>הפלטפורמה</span> <span>שלכם</span> <span>למציאת</span> <span>סקינים</span> <span>למיינקראפט.</span>',
        'header_credit' => 'אילוסטריציות על ידי "Epic Nether Battle"',
        'info' => 'עקבו אחר הכל.',
        'info_explainer' => 'ראו היסטוריית שמות של משתמש, הסקינים הישנים שלהם, הוסיפו אותם בתור חברים, הורידו סקינים, ואפילו נתונים מפורטים על משתמשים.',
        'card_find_title' => 'תמצאו כל מיינקראפטר',
        'card_find_detail' => 'התחילו בחיפוש אחר משתמשים על פי שם המשתמש שלהם או הUUID.',
        'card_view_title' => 'צפו, שתפו וערכו',
        'card_view_detail' => 'מצאתם סקין שאתם אוהבים? שמרו אותו בכך שתורידו אותו או שתערכו ותעצבו אותו בשבילכם.',
        'card_claim_title' => 'להיות מאומת',
        'card_claim_detail' => 'חברו את משתמש המיינקראפט שלכם כדי לתפוס את הפרופיל שלכם ולפתוח פיצ\'רים חדשים!',
        'card_customise_title' => 'התאימו אישית את הפרופיל שלכם',
        'card_customise_detail' => 'משתמשים מאומתים יכולים לחבר את הרשתות החברתיות שלהם וכך להתאים את הפרופיל שלהם.',
        'card_friends_title' => 'הוסף חברים',
        'card_friends_detail' => 'צור קשר עם החברים שלך דרך SkinMC והצג את רשימת החברים בפרופיל שלך.',
        'card_history_title' => 'היסטוריית שמות משתמש וסקינים',
        'card_history_detail' => 'השתמשו בחיפוש המתקדם כדי למצוא היסטוריית שם משתמש או סקינים של שחקן.',
        'founders' => 'המייסדים',
        'founders_cofounder' => 'מייסד שותף',
        'head_of_design' => 'אחראי עיצוב',
        'head_of_code' => 'אחראי קוד',
        'feedback' => 'שלחו לנו משוב',
        'faq' => 'יש לכם שאלות לגבי מיינקראפט, סקינים, ועוד? קראו את השאלות הנפוצות שלנו.',
        'faq_link' => 'בקרו בשאלות הנפוצות',
        'contact' => 'צריכים עזרה בקשר לשאלה? פנו אלינו ישירות.',
        'contact_link' => 'צרו קשר',

    ],
    'faq' => [
        'title' => 'שאלות נפוצות',
        'subtitle' => 'שאלות נפוצות',
        'help' => 'צריכים עוד עזרה?',
        'discord' => 'הצטרפו לשרת הדיסקורד ודבר עם עוד שחקני מיינקראפט.',
        'contact' => 'צרו קשר',
        'q' => [
            'change_skin_t' => 'איך אני משנה את הסקין שלי במיינקראפט?',
            'change_skin' => '             
   <p>כדי לשנות את הסקין תעשו את הדברים הבאים:</p>
                <ol>
                    <li>היכנס אל <a href="https://my.minecraft.net/en-us/login/">https://my.minecraft.net/en-us/login/</a>והתחבר עם המשתמש שלך.</li><li>לאחר שהתחברת, בחר ב<b>"Skin"</b> בתפריט שבצד שמאל.</li><li>אחר כך, העלה את הסקין שאתה רוצה שיהיה שלך.</li>
                </ol>',
            'change_username_t' => 'איך אני משנה את שם המשתמש שלי במיינקראפט?',
            'change_username' => '
                <p>כדי לשנות את שם המשתמש בצעו את הדברים הבאים:</p>
                <ol>
                    <li>היכנסו אל <a href="https://account.mojang.com/login" target="_blank" rel="nofollow">https://account.mojang.com/login</a> והתחברו למשתמש שלכם.</li>
                    <li>תמצאו את שם המשתמש של הפרופיל שלכם ולאחר מכן לחצור על כפתור ה <b>"(Change)"</b></li>
                    <li>בדף שלאחר מכן, רשמו את השם שתרצו.</li>
                    <li>לבסוף, אשרו את השינויים על ידי הכנסת הסיסמה של המשתמש שלכם ולחיצה על הכפתור "Change name".</li>
                </ol>',
            'dl_t' => 'איך אני מוריד סקין של משתמש כלשהו?',
            'dl' => '
                <p>כדי להוריד סקין של מישהו מסוים תעשו את הדברים הבאים:</p>
                <ol>
                    <li>לחצו על איזור החיפוש ורשמו את השם של השחקן שאת הסקין שלו תרצו להוריד.</li>
                    <li>בדף הפרופיל תוכלו לראות תצוגה מקדימה של הסקין</li>
                    <li>לחצו על הכפתור <strong>הורד סקין</strong> שמתחת לתצוגה המקדימה</li>
                </ol>',
            'submit_q' => 'איך אני מוסיף סקין לקולקצייה?',
            'submit_a' => '<p>Please fill out the following short form with the usernames and their category of which you would like to add to the collections. <a href="https://forms.gle/f4Jh5RpGfsHAZ5xE8" target="_blank">Collection submission form</a>',
            'mcpe_t' => 'Can I use the Skin on Minecraft PE?',
            'mcpe' => '
                <p>Yes. To use the Skin in Minecraft Pocket Edition do the following:</p>
                <ol>
                    <li>Open SkinMC.net on your smartphone and tap the search bar</li>
                    <li>Enter the username of the player\'s skin you would like to download</li>
                    <li>Tap the <strong>Download Skin</strong> button under the preview </li>
                    <li>Open Minecraft PE and tap on <strong>Profile</strong> on the right side</li>
                    <li>Tap on the <strong>+</strong>, or edit character and go to the "classic skins tab"</li>
                    <li>Tap on "owned", then "import", then "choose new skin"</li>
                </ol>',
            'change_times_t' => 'How often can I change my username?',
            'change_times' => '<p>You can change your Minecraft Username <strong>once</strong> every <strong>30 days</strong>.</p>',
            'available_t' => 'After I changed my username, when does it become available for others to claim it?',
            'available' => '<p>If you want to change back to your previous username, you can change back <strong>after 30 days.</strong> Everyone else needs to wait an additional <strong>7 days</strong> (37 days after changing) before they can claim your old username. </p>',
            'username_history_t' => 'Can you remove my username history please?',
            'username_history' => '
                <p>As the username history data comes from Mojang, the username history can not be removed. Mojang has previously stated that their intention was that previous usernames can be seen¹, and that they provide a direct method for the public to access this information².</p>
                <p class="font-14">¹<a href="https://help.minecraft.net/hc/en-us/articles/360034636712-Minecraft-Usernames" target="_blank" rel="noreferrer">https://help.minecraft.net/hc/en-us/articles/360034636712-Minecraft-Usernames</a></p>
                <p class="font-14 mb-0">²<a href="https://twitter.com/dinnerbone/status/554739042529849345" target="_blank" rel="noreferrer">https://twitter.com/dinnerbone/status/554739042529849345</a> (Tweet archived 2 years ago: <a href="http://archive.is/TeAyj" target="_blank" rel="noreferrer">http://archive.is/TeAyj</a>)
                </p>',
        ],
    ],
    'avatars' => [
        'start' => [
            'title' => 'Create your own Minecraft avatar',
            'subtitle' => 'Use the Minecraft avatar generator to create a fun avatar from any skin!',
            'avatar_face' => 'Face style avatar',
            'avatar_bust' => 'Bust style avatar',
            'avatar_cube' => 'Cube style avatar',
            'avatar_head3d' => 'Custom 3D head',
        ],
        'user' => [
            'title' => 'Choose skin',
            'subtitle' => 'Enter the Minecraft Username for the avatar you would like to generate',
            'form_label' => 'Minecraft username',
            'form_submit' => 'Continue',
        ],
        'output' => [
            'title' => 'Preview and save',
            'subtitle' => 'Enjoy using your new Minecraft avatar',
            'download_info' => 'Happy with the result? Start using your new avatar by downloading it here',
            'download_button' => 'Download avatar',
            'avatar_style' => 'Avatar style',
            'skin_username' => 'Skin username',
            'change' => 'Change',
            'generate' => 'Generate',
            'avatar_colour' => 'Background colour',
            'avatar_colour_palette' => 'Palette',
            'avatar_colour_basic' => 'Basic',
        ],
        'meta' => [
            'title' => 'Minecraft Avatar Generator',
            'description' => 'Minecraft Avatar Maker: create custom Minecraft profile pictures using your Minecraft skin',
        ],
    ],
    'totem' => [
        'title' => 'Custom Minecraft Totem',
        'subtitle' => 'Use the Minecraft Totem generator to create a custom resource pack with a Totem of Undying from any skin.',
        'download_info' => 'Happy with the preview? Choose your Minecraft version to save your custom resource pack:',
        'meta' => [
            'title' => 'Minecraft Custom Totem Generator',
            'description' => 'Custom Minecraft Totems: generate and create a custom Minecraft Resource Pack with a Totem of Undying using your or any other players Minecraft skin.',
        ],
        'type' => [
            'mini' => 'A mini version of your skin!',
            'full' => 'A full version of your skin!',
            'model3d' => 'A 3d model of your skin!',
            'add_designs' => 'Want to see more designs? Submit your design suggestion here:',
        ],
    ],
    'achievement' => [
        'header' => [
            'title' => 'Create your own Minecraft Achievement',
            'subtitle' => 'Use the Minecraft Achievement Generator to create your very own custom achievement and use show your advancements in anything you like to!',
        ],
        'generator' => [
            'yellow_text' => 'Yellow text',
            'white_text' => 'White text',
            'choose_icon' => 'Choose icon',
            'face' => 'Minecraft face instead of icon',
            'form_submit' => 'Download',
            'form_label' => 'Minecraft username',
            'download' => 'Download',
            'embed' => 'Embed',
            'embed_copy' => 'Copy',
        ],
        'meta' => [
            'title' => 'Minecraft Achievement Generator',
            'description' => 'Generate custom Minecraft Achievements and Advancements with the Achievement creator. Download the image directly, use it in forum signatures, embed with HTML or BB code, and more',
        ],
    ],
    'armor' => [
        'header' => [
            'title' => 'Minecraft Armor Stand Creator',
            'subtitle' => 'Generate and create your very own custom Minecraft Armor Stands. Create different poses, positions, place items, and much more.',
        ],
        'meta' => [
            'title' => 'Minecraft Armor Stand Creator',
            'description' => 'Easily generate and create custom Minecraft Armor Stands. The editor helps you make different poses, positions, place items, custom skins, and much more.',
        ],
    ],
    'banner' => [
        'editor' => [
            'header' => [
                'title' => 'Minecraft Banner Editor',
                'subtitle' => 'Design and create your very own custom Minecraft Banners. These can be used to decorate your world or also commonly seen used as <a href="https://optifine.net" target="_blank" rel="nofollow">Optifine</a> capes.',
            ],
            'meta' => [
                'title' => 'Minecraft Banner Creator',
                'description' => 'Create and design your very own custom Minecraft Banners designs with all the patterns and colors from the game! These can be used to decorate your world or be worn as an Optifine Cape using the Banner Cape. You can generate give codes for banners or shields.',
            ],
            'toolbar' => [
                'title' => 'SkinMC Banner Editor',
                'randomise' => 'Randomise',
                'clear_layers' => 'Clear layers',
                'help' => 'Help',
                'save_banner' => 'Save banner',
                'submit_to_gallery' => 'Submit design to banner gallery',
                'reset_from_url' => 'Reset to banner from URL',
                'minecraft_version' => 'Minecraft Version',
                'texture_type' => 'Texture Type',
                'banner' => 'Banner',
                'shield' => 'Shield',
                'version_1_21' => '1.21+',
                'version_1_16' => '1.16 - 1.20',
                'version_1_13' => '1.13 - 1.15',
                'version_1_8' => '1.8 - 1.12',
                'color_black' => 'Black',
                'color_dark_grey' => 'Dark grey',
                'color_grey' => 'Grey',
                'color_white' => 'White',
                'color_pink' => 'Pink',
                'color_magenta' => 'Magenta',
                'color_purple' => 'Purple',
                'color_blue' => 'Blue',
                'color_cyan' => 'Cyan',
                'color_light_blue' => 'Light blue',
                'color_green' => 'Green',
                'color_lime' => 'Lime',
                'color_yellow' => 'Yellow',
                'color_orange' => 'Orange',
                'color_brown' => 'Brown',
                'color_red' => 'Red',
            ],
            'tools' => [
                'share_link' => 'Share link',
                'share_link_placeholder' => 'Share link',
                'generate_codes' => 'Generate codes',
                'target_selector' => 'Target selector',
                'command_give' => 'Give',
                'command_setblock' => 'Setblock',
                'command_replaceitem_shield' => 'Shield',
                'code_placeholder' => 'Select a command to generate code',
                'import_code' => 'Import code',
                'background_grass' => 'Grass background',
            ],
            'modal' => [
                'save_banners' => 'Save banners',
                'share_saved_gallery' => 'Share saved gallery',
                'share_saved_gallery_placeholder' => 'Share saved gallery',
                'export_to_chest' => 'Export to chest',
                'delete_all' => 'Delete all',
            ],
        ],
        'gallery' => [
            'header' => [
                'title' => 'Minecraft Banner Gallery',
                'subtitle' => 'Browse the gallery of :count custom designed Minecraft Banners. You can use a Banner as a cape to make your Minecraft skin more unique, or use a Banner as a flag to decorate your world.',
            ],
            'meta' => [
                'title' => 'Minecraft Banner Gallery',
                'description' => 'Browse the gallery of :count custom designed Minecraft Banners. You can use a Banner as a cape to make your Minecraft skin more unique, or use a Banner as a flag to decorate your world.',
            ],
        ],
    ],
    'search' => [
        'meta' => [
            'title' => 'Search results: :search',
        ],
        'title' => 'Search results',
        'results' => 'Page :current for :count result|Page :current of about :count results ',
        'time' => '(:time seconds)',
        'username_available' => 'Username available*',
        'username_unavailable' => 'Username not available',
        'username_status' => 'Status',
        'username_status_available' => 'Available*',
        'username_status_unavailable' => 'Unavailable',
        'username_searches' => 'Searches',
        'username_searches_count' => ':count / day',
        'username_available_disclaimer' => '*Unless the name is temporarily or permanently banned by Mojang.',
        'no_results' => 'No profiles found. Try searching with UUID by changing the search type.',
        'no_results_tags' => 'No tagged skins found. Try searching for other tags such as "blue", "girl", "fox", etc...',
        'again' => 'Search again',
        'sorry' => 'Sssssssorry...',
        'view_profile' => 'View profile',
    ],
    'collection' => [
        'title' => 'Minecraft skin collection',
        'subtitle' => 'Browse through our curated collection of Minecraft skins.',
        'filters' => 'Filters',
        'title_trending' => 'Trending',
        'title_all' => 'All Minecraft Skins',
        'skin_tags' => 'Tagged Skins',
        'filters_skin_type' => 'Skin type',
        'filter_skin_type_steve' => 'Steve type',
        'filter_skin_type_alex' => 'Alex type',
        'cancel' => 'Cancel',
        'apply' => 'Apply',
        'username_minecraft_skin' => 'הסקין של :username',
        'user_downloads' => '<span class="fw-500">:downloads</span> הורדות|<span class="fw-500">:downloads</span> הורדות',
    ],
    'favourites' => [
        'title' => 'מועדפים',
        'subtitle' => 'View and manage skins and servers you saved for later in your favourites list',
        'sort' => 'Sort by',
        'toast' => [
            'added' => 'Added to your favourites list',
            'removed' => 'Removed from your favourites list',
        ],
        'skins' => [
            'button' => 'Skins',
            'empty_headline' => 'No favourite skins yet',
            'empty_subtitle' => 'You do not have any skins saved to your favourites list yet. Visit the server page and discover your next favourite!',
            'empty_browse' => 'Browse skins',
            'meta' => [
                'title' => 'My favourite skins',
                'description' => 'My favourite saved Minecraft skins',
            ],
        ],
        'servers' => [
            'button' => 'Servers',
            'empty_headline' => 'No favourite servers yet',
            'empty_subtitle' => 'You do not have any servers saved to your favourites list yet. Visit the server page and discover your next favourite!',
            'empty_browse' => 'Browse servers',
            'meta' => [
                'title' => 'My favourite servers',
                'description' => 'My favourite Minecraft servers',
            ],
        ],

    ],
    'cape' => [
        'editor' => [
            'title' => 'Minecraft cape editor',
            'subtitle' => 'Use the Minecraft cape editor to create your very own custom designed cape.',
            'meta' => [
                'title' => 'Minecraft Cape Editor',
                'description' => 'Use the Minecraft Cape Editor to create your very own custom designed cape.',
            ],
        ],
        'list' => [
            'title' => 'Minecraft capes',
            'subtitle' => 'Official capes of Minecraft. Capes are commemorative items and are worn as addition to the player skin. They can also change the appearance when an elytra is worn.',
            'meta' => [
                'title' => 'Minecraft Capes List',
                'description' => 'Minecraft cape list: View all official Minecraft capes including Mojang, Minecon, Personal, Special and vanity capes',
            ],
        ],
        'detail' => [
            'title' => ':cape Cape',
            'info' => 'Cape information',
            'profile_list' => 'Profiles with this cape',
            'profiles' => ':profiles profile|:profiles profiles',
            'meta' => [
                'title' => ':cape Minecraft Cape',
                'description' => 'Check out the :cape Minecraft Cape and see players wearing it!',
            ],
        ],
        'list-custom' => [
            'title' => 'Custom Minecraft Capes',
            'description' => 'Browse and view custom capes which have been created and are used by SkinMC members.',
        ],
    ],
    'servers' => [
        'title' => 'Minecraft servers',
        'subtitle' => 'Browse and explore minecraft servers',
        'all' => 'All servers',
        'manage_your_servers' => 'Manage your servers',
        'add_new_server' => 'Add new server',
        'filters' => [
            'trending' => 'Trending',
            'updated' => 'Updated',
            'new' => 'New',
            'most_viewed' => 'Most viewed',
            'top_voted' => 'Top voted',
            'sorting' => 'Sorting',
            'sort_by_latest' => 'Sort by latest',
            'sort_by_oldest' => 'Sort by oldest',
            'categories' => 'Categories',
            'server_location' => 'Server location',
            'show_results' => 'Show results',
            'show_more' => 'Show more',
            'show_less' => 'Show less',
            'clear_filters' => 'Clear filters',
            'reviews' => 'Reviews',
            'sort_by_highest_rating' => 'Sort by highest rating',
            'sort_by_lowest_rating' => 'Sort by lowest rating',
            'bedrock_and_java_support' => 'Bedrock and Java support',
        ],
        'review-count' => ':count Review|:count Reviews',
        'meta' => [
            'title' => 'Minecraft Server List',
            'description' => 'Browse and explore the Minecraft Servers list to find the best Minecraft server! Filter by the latest, most popular and much more',
        ],
        'reviews' => [
            'meta' => [
                'title' => 'Write a review',
            ],
            'editing' => 'You\'re editing your review from :date. Would you like to delete your review instead?',
            'welcome' => 'Hi :username. How was your overall experience with :servername?',
            'subtitle' => 'Leave an overall score of your past experience with the server.',
            'scale' => [
                'great' => 'Great',
                'good' => 'Good',
                'okay' => 'Okay',
                'meh' => 'Meh',
                'bad' => 'Bad',
            ],
            'rate-experience' => 'Next, rate your experience in these areas',
            'overall' => 'Overall',
            'server-team' => 'Server team',
            'community' => 'Community',
            'experience' => 'Experience',
            'availablility' => 'Uptime and availability',
            'shop' => 'Shop',
            'write-review-title' => 'Write a review',
            'write-review-subtitle' => 'Leave a few notes, you can highlight what you enjoyed, what made your experience special, or offer a few suggestions.',
            'write-review-helper' => 'Write a server review to share your experience with new players, and help the server owners with feedback.',
            'write-review-tips' => 'Here are some tips',
            'submit-title' => 'Ready to submit your review?',
            'submit-subtitle' => 'Almost done!',
            'submit-review' => 'Submit my review',
            'back' => 'Back',
            'continue' => 'Continue',
            'delete-title' => 'Are you sure you would like to delete your review?',
            'tos-checkbox-part-1' => 'By submitting this form you accept SkinMC\'s Terms of Service, Privacy Policy, and Community Guidelines. You also confirm that all of the information is accurate, and follows the',
            'tos-checkbox-part-2' => 'review guidelines.',
            'tos-checkbox-part-3' => 'Your review will be published after submission, but can be subject to review.',
        ],
        'slots' => 'Slots',
        'empty-helper' => 'You can try to do another search or',
        'empty' => 'Hmm it\'s still empty here.',
        'verified' => 'Verified',
        'review_translate_show_original' => 'Show original',
        'review_translate' => 'Translate review',
        'description_translate' => 'Translate description',
        'create' => [
            'welcome' => 'Welcome',
            'basics' => 'Basics',
            'categories' => 'Categories',
            'social_links' => 'Social links',
            'trailer_video' => 'Trailer video',
            'images' => 'Images',
            'images_description' => 'You can upload photos afterwards, to showcase what your server offers.',
            'submit' => 'Submit',
            'lets_get_your_server_added' => 'Let\'s get your server added.',
            'basics-subtitle' => 'Let people know what your server is about.',
            'description' => 'Description',
            'description_tips' => 'Here are some tips',
            'description_hint' => 'Write a good description for your server to attract new players.',
            'categories-subtitle' => 'Choose some categories for your server',
            'missing-category' => 'Missing a category?',
            'social_links_description' => 'Where can players connect with your server on social media?',
            'trailer_video_description' => 'Showcase your server with a YouTube video.',
            'trailer_video_hint' => 'Paste the video URL or ID:',
            'ready_to_submit_your_server' => 'Ready to submit your server?',
            'review-hint' => 'After submission the team will carefully review your server listing application. Then upon decision, your server will be published, or changes requested before going live.',
            'terms' => [
                'part-1' => 'By submitting this form you are authorised to accept SkinMC\'s Terms of Service, Privacy Policy, and Community Guidelines. You also confirm that all of the information above is accurate, you have properly followed the',
                'part-2' => 'server requirements for setup',
                'part-3' => ', and that the Minecraft server is owned and managed by the entity you are representing.',
            ],
            'submit-application' => 'Submit application',
            'video-id-helper' => [
                'part-1' => 'The video ID is the string of numbers and letters after',
                'part-2' => 'For example if your video url is',
                'part-3' => ', then your video ID would be',
            ],
            'welcome_description' => 'In this step, we\'ll get started on adding your server. Tell us a bit about it, write a description, and in the next step you can upload some images.',
        ],
        'copy_server_ip' => 'Copy server IP',
        'all_minecraft_servers' => 'All Minecraft Servers',
        'promo' => [
            'title' => 'Do you host a Minecraft Server?',
            'ready_to_list_your_server' => 'Ready to list your Server?',
            'everything_you_need' => 'Everything you need to grow your server',
            'list_your_server' => 'List your server',
            'list_your_server_description' => 'Create a listing for your server, add photos, social media and more.',
            'find_players' => 'Find players',
            'find_players_description' => 'Find and reach new players to join your server and grow your community.',
            'get_reviews' => 'Get reviews',
            'get_reviews_description' => 'Ask your community to review your server, and reward them in game.',
            'why_list_on_skinmc' => 'Why you should list your Server on SkinMC',
            'others' => 'Others',
            'quality_check_and_confirmation' => 'Quality check and confirmation',
            'quality_check_description' => 'Our team reviews every server to ensure quality.',
            'verified_players' => 'Reviews from verified Minecraft players',
            'verified_players_description' => 'Collect authentic player reviews from legitimate accounts with Votifier integration.',
            'international' => 'International',
            'international_description' => 'With translation features your listing is available to more players.',
            'server_listing_page' => 'Powerful Server listing page',
            'server_listing_page_description' => 'Add photos, description texts, youtube videos, and highlight why players should join your server.',
            'social_connections' => 'Social media connections',
            'social_connections_description' => 'Connect your Servers social accounts and show new players where they can find you.',
            'verified_badge' => 'Verification badge',
            'verified_badge_description' => 'Authentic servers can apply for a verification badge.',
            'owner_profile' => 'Owner profile',
            'owner_profile_description' => 'Add a personal touch, by completing your custom profile.',
            'categories' => 'Categories',
            'categories_description' => 'Different categories to make it easier to find your server.',
            'vote' => 'Vote',
            'vote_description' => 'Ask users to vote for your server.',
            'fair_listings' => 'Fair listings',
            'fair_listings_description' => 'Server listings can not be artificially boosted in results on SkinMC.',
            'support' => '24h support',
            'support_description' => 'Do you need help or have questions? You can always reach out and receive a fast reply.',
            'custom_features' => 'Custom features',
            'custom_features_description' => 'Missing a feature for your server? Open a ticket, and we\'ll implement it.',
            'faq' => [
                'title' => 'Answers to your questions',
                'suited-question' => 'Is my Minecraft Server suited for SkinMC?',
                'suited-answer' => 'Minecraft Players on SkinMC love to discover new experiences, content and engage with communities. On the platform you\'ll find a large variety of different, unique, fun Minecraft servers. From a large network to even a small survival server, it can make someones day!',
                'get-started-question' => 'How do I get started?',
                'get-started-answer' => 'Adding your Minecraft Server to the SkinMC Server List is very easy! You will first need to create an account, if you haven\'t already, and then follow the setup guide to get your server listed. Add a few photos and a nice description, and your server will be published in no time!',
                'players-question' => 'How can I get more players on my Minecraft Server?',
                'players-answer' => 'Building a community is the most crucial part of a long lasting Minecraft Server. Use the Minecraft Server List on SkinMC to find a new audience and continue to build your community. Ask your players to recommend your Server, or share your listing on social media platforms. Collecting good reviews can also play an important role to a great Server listing presence that attracts new players.',
                'more-question' => 'I have more questions. Where can I get help?',
                'more-answer' => 'You can reach out to SkinMC at any time, 24 hours, by using either the help button, the help desk, or by joining the Discord server.',
            ],
            'ready_to_list_description' => 'Add your Minecraft Server to the SkinMC Server List in just a few minutes. If you need any help, you can reach out around the clock and receive answers quickly.',
        ],
        'manage' => [
            'index' => [
                'welcome' => 'Welcome back, :username',
                'your_servers' => 'Your servers',
                'reviews_today' => 'Reviews today',
                'no_reviews_today' => 'No reviews today',
                'no_reviews_text' => 'Your servers haven\'t received any reviews today. Why not ask your players to leave one?',
                'tips' => [
                    'title' => 'Tips',
                    'description-title' => 'Write a good server description',
                    'description-body' => 'Helpful tips and advice to write a great server description.',
                    'images-title' => 'Adding server images',
                    'images-body' => 'Make your server listing stand out with great images.',
                ],
            ],
            'listings' => [
                'title' => 'Your Minecraft servers (:count)',
            ],
            'insights' => [
                'title' => 'Insights',
            ],
            'edit_server' => 'Edit server',
            'listing' => 'Listing',
            'to_do' => 'To do',
            'last_update' => 'Last update',
            'add_more_photos_to_publish' => 'Add more photos to publish',
            'looks_empty_here' => 'Looks empty here.',
            'get_started_by_adding_a_new_server' => 'Get started by adding a new server?',
        ],
        'status' => [
            'approved' => 'Approved',
            'pending_approval' => 'Pending approval',
            'published' => 'Published',
            'in_review' => 'In review',
        ],
    ],
    'editor' => [
        'import' => [
            'title' => 'Import Skin',
            'import_by_username' => 'Import by username',
            'import_button' => 'Import',
            'drag' => 'Drag and drop a skin here, or click',
            'click' => 'Select image',
        ],
        'download' => [
            'error' => [
                'no-data' => 'No skin data was provided. Please try again.',
                'invalid-format' => 'The skin data format is invalid. Please try again.',
                'invalid-data' => 'The skin data is corrupted. Please try again.',
                'generic' => 'Something went wrong while downloading your skin. Please try again.',
            ],
        ],
        'draw' => 'Draw',
        'eyedropper' => 'Eyedropper',
        'fill' => 'Fill',
        'move' => 'Move',
        'decrease_brightness' => 'Decrease brightness',
        'increase_brightness' => 'Increase brightness',
        'erase' => 'Erase',
        'undo' => 'Step back (CTRL+Z)',
        'redo' => 'Step forward (CTRL+Y)',
        'default_view' => 'Default view',
        'zoom_in' => 'Zoom in (CTRL +)',
        'zoom_out' => 'Zoom out (CTRL -)',
        'saved' => 'Last saved just now',
        'saving' => 'Auto saving...',
        'save_error' => 'An error occurred',
        'new_skin' => 'New skin',
        'previous_skins' => 'Previous skins',
        'backed_up_title' => 'Automatically saved skins',
        'backed_up_info' => 'Temporarily backed up to your local storage.',
        'backed_up_empty_title' => 'It\'s empty here',
        'backed_up_empty_info' => 'Once you start editing skins you\'ll see your 32 last edited skins here.',
        'backed_up_skins_count' => 'of 32 skin backups used',
        'backed_up_skins_count_info' => 'You can back up to up 32 skins. Once you reach 32 skins an older skin will be replaced with a new one.',
        'layers' => 'Layers',
        'body' => [
            'title' => 'Body',
            'overlay' => 'כיסוי',
            'head' => 'ראש',
            'torso' => 'טורסו',
            'l_arm' => 'יד שמאלית',
            'r_arm' => 'יד ימנית',
            'l_leg' => 'רגל שמאלית',
            'r_leg' => 'רגל ימנית',
        ],
        'model' => 'דגם',
        'steve' => 'סטיב',
        'alex' => 'אלקס',
        'stance' => [
            'title' => 'מיקום',
            'default' => 'רגיל',
            'walk' => 'הליכה',
            'run' => 'ריצה',
            'hug' => 'צורת T',
            'fly' => 'עף',
        ],
        'fullscreen' => 'Fullscreen',
        'fullscreen_exit' => 'Exit fullscreen',
        'grid' => 'רשת',
        'show_grid' => 'הצג רשת',
        'download' => [
            'title' => 'שמור והורד',
            'subtitle' => 'משתמש SkinMC',
            'description' => 'האם תרצה ליצור משתמש SkinMC בחינם ולשמור את הסקין הזה ועוד אחרים בענן שלנו?',
            'start_description' => 'התחל להוריד ישירות מבלי לשמור בענן',
            'start' => 'הורד סקין',
        ],
        'help' => [
            'title' => 'Minecraft Skin Editor',
            'about' => 'Create and edit your custom Minecraft Skin easily with the SkinMC Editor. You can choose between Steve and Alex models, import skins from a file or username, and create your very own Minecraft Skin.',
            'draw' => 'Draw using the pen tool. Select a colour from the swatch to use with it.',
            'eyedropper' => 'Use the eyedropper to select a colour from your skin and add it to your current palette.',
            'fill' => 'Fill entire areas of your skin using the fill tool. Select a colour before using fill.',
            'move' => 'Pan and move around the skin editor canvas with the move tool.',
            'decrease_brightness' => 'Decrease the brightness of the currently active colour.',
            'increase_brightness' => 'Increase the brightness of the currently active colour.',
            'erase' => 'Erase pixels drawn on the secondary overlay layer.',
            'minimap' => 'Minimap',
            'minimap_info' => 'The minimap can show you the skin texture in a flat view while in 3D mode. In 2D mode the minimap switches to a 3D preview of your skin. You can zoom in and out.',
            'autosave' => 'Autosave',
            'autosave_info' => 'The autosave feature saves your skin automatically every 30 seconds. You can access the autosaved skins in the editor by pressing the folder icon, and choosing "Previous skins".',
            '2d_editor' => '2D and 3D editor',
            '2d_editor_info' => 'Toggle between editing your Minecraft skin in 2D or 3D mode.',
        ],
    ],
    'account' => [
        'level' => 'Level',
        'level_history' => 'Level history',
        'xp' => 'XP',
        'my_xp' => 'My XP',
        'xp_to_next_level' => ':xp XP to next level',
        'xp_info' => 'What are XP?',
        'xp_info_tooltip' => 'XP is earned for various activities such as adding tags to skins, inviting friends, commenting, and much more. With each XP earned you can level up and unlock cool things!',
        'settings' => [
            'title' => 'משתמש',
            'show_profile' => 'צפה בפרופיל',
            'friends' => 'חברים',
            'friends_detail' => 'הישאר מחובר על ידי הוספת החברים שלך לSkinMC.',
            'security' => 'אבטחה',
            'security_detail' => 'עדכן את הסיסמה שלך וכך שמור על המשתמש שלך מוגן',
            'social' => 'רשתות חברתיות',
            'social_detail' => 'התאם אישית את הפרופיל שלך על ידי הוספת רשתות חברתיות',
            'link' => 'קשר את המשתמש מיינקראפט',
            'link_detail' => 'קשר את משתמש המיינקראפט שלך ותפוס את הפרופיל שלך.',
            'logout' => 'האם ברצונך להתנתק ממשתמש הSkinMC שלך?',
            'automatic_backups' => 'Automatic skin backups',
            'automatic_backups_info' => 'As a SkinMC plus member your skins are backed up daily.',
        ],
        'capes' => [
            'title' => 'מיינקראפט קייפ של SkinMC',
            'description' => 'לבש איזה קייפ שתרצה בתוך המשחק בעזרת SkinMC קייפ בחינם.',
            'drop' => 'גרור והשלך קייפ כאן',
            'drop-hint' => 'מידות 64x32px',
            'select' => 'בחירת תמונה',
            'upload-cape' => 'העלה את הקייפ שלך',
            'save-and-use' => 'שמור והשתמש',
            'uploaded-cape' => 'קייפ הועלה',
            'no-cape' => 'אין קייפ',
            'remove-cape' => 'הסר קייפ',
            'download' => 'הורד את המוד של SkinMC כדי לראות אותך ועוד שחקנים אחרים עם קייפ בתוך המשחק.',
            'learn-more' => 'מידע נוסף',
            'link-account' => 'אנא קשר את משתמש המיינקראפט שלך כדי להעלות קייפ.',
            'updated' => 'הקייפ שלך עודכן!',
            'removed' => 'הקייפ שלך נמחק.',
            'active' => 'הקייפ שלך מופעל!',
        ],
        'favourite' => 'מועדף',
        'remove_favourite' => 'הסר מהמועדפים',
        'added_to_favourites' => 'נוסף למועדפים',
        'removed_from_favourites' => 'הסרה מהמועדפים',
        'welcome' => 'נחמד לראות אותך!',
        'view-profile' => 'צפה בפרופיל',
        'security' => [
            'title' => 'אבטחה',
            'email' => 'כתובת אימייל',
            'email-title' => 'עדכן את כתובת המייל.',
            'save' => 'שמור',
            'password' => 'סיסמה',
            'password-title' => 'שנה את הסיסמה שלך בכל זמן.',
            'social-provider' => 'To update your account information, such as your password, please visit your login provider:',
            'social-provider-email' => 'Your associated email address with your login provider',
            'social-provider-connected' => 'Currently connected login providers',
            'current-password' => 'הסיסמה הנוכחית',
            'forgot' => 'שכחת סיסמה?',
            'edit' => 'ערוך',
            'delete' => 'Delete my account',
            'account-deletion' => 'Delete your SkinMC account.',
            'delete-info' => 'Please confirm to continue',
            'delete-confirmation' => 'Deleting your account is irreversible. All your personal information and content such as posts, favourites, uploaded capes, customisations, etc. will be deleted and can not be recovered.',
            'delete-confirmation-info' => 'Enter your password to continue',
            'delete-confirmation-info-social' => 'Type "delete" to confirm account deletion',
            'type-delete' => 'Type "delete" to confirm',
            'type-delete-label' => 'Type "delete" to confirm',
            'yes-confirm-delete' => 'Yes, confirm delete',
            'account-successfully-deleted' => 'Your account and data has been successfully deleted.',
        ],
        'social' => [
            'title' => 'רשתות חברתיות',
            'edit' => 'ערוך',
            'save' => 'שמור',
            'link-account' => 'קשר את משתמש המיינקראפט שלך לאתר SkinMC כדי להציג את הרשתות החברתיות שלך.',
            'finish-setup' => 'סיים את הסדר',
            'connect-account' => 'קשר את החשבונות שלך',
            'connect-description' => 'בחר איזה חשבונות תרצה לקשר ופתח אפשרויות מיוחדות.',
            'empty' => 'לא נוספו חשבונות',
            'empty-description' => 'הרשתות החברתיות שלך יופיעו כאן בפרופיל הציבורי שלך. ברגע שהם ייתווספו לדף שלך הם יתנו לך יותר התאמה אישית.',
            'connect' => 'קשר',
            'username' => 'שם משתמש',
            'spotify' => 'הוסף את שם המשתמש של הSpotify שלך כדי להציג מידע על הSpotify שלך בפרופיל שלך.',
            'discord' => 'הוסף את שם המשתמש והמספר של הDiscord שלך כדי להציג מידע על הDisocrd שלך בפרופיל שלך.',
            'youtube' => 'הוסף את שם ערוץ הYoutube שלך כדי להציג מידע על הערוץ שלך בפרופיל שלך.',
            'youtube-format' => 'השתמש בפורמט המתאים בהתאם לקישור של הערוץ שלך:',
            'twitter' => 'Enter your X (formerly Twitter) username to display it on your profile.',
            'bluesky' => 'Enter your Bluesky handle e.g. username.bsky.social to display your Bluesky profile on your profile.',
            'twitch' => 'הוסף את שם המשתמש של Twitch שלך כדי להציג מידע על הTwitch שלך בפרופיל שלך.',
            'reddit' => 'הוסף את שם המשתמש של הReddit שלך כדי להציג מידע על הReddit שלך בפרופיל שלך.',
            'github' => 'הוסף את שם המשתמש של הGithub שלך כדי להציג מידע על הGithub שלך בפרופיל שלך.',
            'telegram' => 'הוסף את שם המשתמש של הTelegram שלך כדי להציג מידע על הTelegram שלך בפרופיל שלך.',
            'tiktok' => 'הוסף את שם המשתמש של הTikTok שלך כדי להציג מידע על הTikTok שלך בפרופיל שלך.',
            'snapchat' => 'הוסף את שם המשתמש של הSnapchat שלך כדי להציג מידע על הSnapchat שלך בפרופיל שלך.',
            'instagram' => 'הוסף את שם המשתמש של הInstagram שלך כדי להציג מידע על הInstagram שלך בפרופיל שלך.',
            'facebook' => 'הוסף את שם המשתמש של הFacebook שלך כדי להציג מידע על הFacebook שלך בפרופיל שלך.',
            'includes_skinmc_plus_benefits' => 'Includes SkinMC plus benefits',
        ],
        'recover' => [
            'title' => 'שחזר את המשתמש',
            'subtitle' => 'אנא הכנס סיסמה חדשה ואשר אותה בשביל לשחזר את המשתמש שלך.',
            'new_password' => 'סיסמה חדשה',
            'repeat_new_password' => 'אישור סיסמה',
            'submit' => 'שחזר חשבון',
        ],
        'customise' => [
            'title' => 'התאם את הפרופיל שלך',
            'description' => 'הוסף את הרשתות החברתיות שלך, בחר אימוג\'י, הוסף מיקום ועוד',
            'information' => 'מידע',
            'preview' => 'תצוגה מקדימה',
            'location' => [
                'title' => 'מיקום',
                'description' => 'בחר איזה מיקום תרצה להוסיף לפרופיל שלך.',
            ],
            'biography' => [
                'title' => 'מידע עליי',
                'description' => 'כתוב מידע לפרופיל שלך.',
            ],
            'status' => 'Status',
            'status-toggle' => 'Show my online status',
            'emoji' => 'אימוג\'י',
            'name-history-toggle' => 'הפוך את הסיטוריית השמות לפרטית',
            'name-history-info' => 'היסטוריית השמות שלך כרגע היא',
            'name-history-toggle-on' => 'פרטית',
            'name-history-toggle-off' => 'ציבורית',
            'theme' => 'Profile theme',
            'theme-primary' => 'Primary',
            'theme-secondary' => 'Secondary',
            'appearance' => 'Appearance',
        ],
        'link' => [
            'manage' => 'קשר משתמשי מיינקראפט',
            'description' => 'ראה וקשר את משתמשי המיינקראפט שלך',
            'title' => 'משתמשי מיינקראפט מקושרים',
            'current' => 'משתמש המיינקראפט שלך מקושר.',
            'status' => 'יש לך גישה מלאה לכל האפשרויות של SkinMC!',
            'linked' => 'מקושר',
            'disconnect' => 'נתק',
            'disconnect-title' => 'נתק את משתמש המיינקראפט שלך',
            'disconnect-info' => 'האם אתה בטוח שברצונך לנתק את משתמש המיינקראפט שלך?',
            'disconnect-features' => 'אתה תאבד גישה לכתוב תגובות, להתאמות אישיות ועוד אפשרויות אחרות שזמינות רק אם המשתמש מקושר. כדי להשתמש בהם שוב אתה תצטרך לקשר מחדש את המשתמש מיינקראפט שלך.',
            'disconnect-following' => 'ניתוק המשתמש שלך ימחק את רשימת הפרופילים שעוקבים אחריך לצמיתות.',
            'disconnect-posts' => 'Your created feed posts and liked will be deleted.',
            'can-not-undo' => 'This can\'t be undone.',
            'are-you-sure' => 'האם אתה בטוח?',
            'confirm' => 'כן, נתק',
            'cancel' => 'לא, בטל',
            'success' => 'המשתמש שלך נותק בהצלחה!',
        ],
        'finish-setup' => [
            'title' => 'סיים לסדר את החשבון שלך',
            'description' => 'סיים לסדר את החשבון שלך, וקבל גישה מלאה לכל האפשרויות שיש לSkinMC להציע על ידי קישור משתמש המיינקראפט שלך לאתר.',
            'link' => 'קשר את המשתמש',
            'get-started' => 'בוא נתחיל',
            'skip' => 'דלג',
            'claim' => 'תפוס את הפרופיל',
            'customise' => 'התאם אישית את הדף שלך',
            'social' => 'קשר רשתות חברתיות',
            'comment' => 'קבל גישה לתגובות',
            'direct_message' => 'Send direct messages',
            'feed' => 'Post status updates to the feed',
            'follow' => 'עקוב אחר החברים שלך',
            'badge' => 'קבל תג לפרופיל שלך',
            'cape' => 'קייפ מותאם אישית',
            'backup' => 'Automatic skin backup',
            'more' => 'ועוד...',
        ],
        'skins' => [
            'title' => 'Manage skins',
            'toggle' => 'Skin visibility toggled',
        ],
        'invite' => [
            'title' => 'My invites',
            'headline' => 'Invite your friends',
            'info' => 'Create an invite code to share with your friend. Once they accept it, you\'ll both earn some extra XP!',
            'description' => 'Create an invite for your friends and you\'ll both earn some extra XP.',
            'generate' => 'Create invite code',
            'empty' => 'You haven\'t created any invites yet.',
            'code' => 'Code',
            'expiry' => 'Each code works once.',
            'status' => [
                'title' => 'Status',
                'pending' => 'Pending',
                'accepted' => 'Accepted',
            ],
            'add_invite' => [
                'button' => 'Have an invite?',
                'title' => 'Add an invite code',
                'redeem' => 'Redeem invite',
            ],
            'share' => 'Send your friend an invite link',
        ],
        'emoji' => [
            'title' => 'SkinMC Emoji',
            'introducing' => 'Introducing',
            'info' => 'Customise your profile with emoji. Unlock more as you level up.',
            'unlocked_at' => 'Unlocked at level :level',
            'unlocks_at' => 'Reach level :level to unlock',
            'turn_off' => 'Show emoji',
        ],
    ],
    'notifications' => [
        'title' => 'התראות',
        'view_all' => 'הצג הכל',
        'view_all_notifications' => 'View all notifications',
        'image' => 'Notification photo',
        'archived' => 'Archived',
        'inbox' => 'Inbox',
        'empty' => [
            'title' => 'You\'re up to date!',
            'text' => 'New notifications will show up here.',
            'text-archived' => 'Archived notifications will show up here.',
        ],
        'action' => [
            'archive' => 'Move to archive',
            'unarchive' => 'Unarchive',
            'open' => 'Tap to open',
        ],
        'toast' => [
            'archive' => 'Notification moved to archive',
            'unarchive' => 'Notification moved to inbox',
            'undo' => 'Undo',
        ],
    ],
    'error' => [
        'offline' => [
            'title' => 'אין אינטרנט',
            'subtitle' => 'האינטרנט שלך התנתק. אנא בדוק את החיבור שלך וטען מחדש את הדף כדי לנסות שוב.',
            'try_again' => 'נסה שוב',
        ],
        '404' => [
            'title' => '404 — הדף אינו נמצא.',
            'subtitle' => 'הממ, נראה ששום דבר לא נמצא כאן. אולי תנסה לחזור אחורה, או להתחיל מחדש?',
            'try_again' => 'חזור לדף הבית',
        ],
    ],
    'heads' => [
        'list' => [
            'meta' => [
                'title' => 'דאטאבייס של ראשי מיינקראפט',
                'description' => 'חקור את הדאטאבייס של ראשי המיינקראפט וקשט את עולם המיינקראפט שלך איתם, או קבל פקודת give. הצג ראשים מקוריים, ראשי שחקנים וראשים מותאים אישית עם טקסטורה שלעולם לא משתנה.',
            ],
            'header' => [
                'title' => 'ראשי מיינקראפט',
                'subtitle' => 'חקור את הדאטאבייס של ראשי המיינקראפט וקשט את עולם המיינקראפט שלך איתם, או קבל פקודת give. הצג ראשים מקוריים, ראשי שחקנים וראשים מותאים אישית עם טקסטורה שלעולם לא משתנה. ראשי מיינקראפט מקושרים לMojang ולעולם לא יימחקו. בשביל לקבל ראשים מותאמים אישית צריכים קומנד בלוק כי הפקודה מאוד ארוכה.',
            ],
            'count' => [
                'heads' => ':heads ראש|:heads ראשים',
            ],
            'customheads' => [
                'title' => 'ראשים מותאמים אישית',
                'description' => 'ראשים מותאמים אישית מגיעים לטקסטורה שלהם דרך השרתים של Mojang. בגלל זה הטקסטורות שלהם תמיד יהיו קיימות ולעולם לא יימחקו.',
                'version' => 'מיינקראפט 1.8 או גרסה מאוחרת יותר',
            ],
            'playerheads' => [
                'title' => 'ראשי שחקנים',
                'description' => 'ראשי שחקנים משתמשים בסקין הרגיל של שחקן המיינקראפט. בגלל שהם מבוססי שם משתמש, כששחקן משנה את הסקין שלו, הראש משתנה בהתאם.',
                'version' => 'כל גרסאות המיינקראפט',
            ],
        ],
    ],
    'mod' => [
        'title' => 'SkinMC מוד: קייפים מותאמים אישית בחינם',
        'headline' => 'מציגים את המוד של SkinMC בשביל עוד התאמות במשחק',
        'description' => 'בשביל קהילת השחקנים, מוד חינמי המאפשר לכם לשים לעצמכם קייפ מותאם אישית, זמין לכל אחד שמשתמש במוד הזה.',
        'download' => 'הורידו עכשיו',
        'download-title' => 'הורידו את המוד',
        'requires' => 'דורש',
        'select-version' => 'בחר את גרסת המיינקראפט שלך',
        'get-started' => 'להתחיל זה מאוד פשוט',
        'step-1' => '1. השג את המוד',
        'step-1-detail' => 'התקן Fabric, ואז הורד את המוד לגרסת המיינקראפט שלך והתקן אותו על ידי העברה של קובץ הjar אל תיקיית הmods שלך.',
        'step-2' => '2. קשר את המשתמש',
        'step-2-detail' => 'אם לא עשית את זה עדיין, הירשם או התחבר ואז קשר את המשתמש שלך לאתר SkinMC.',
        'step-3' => '3. העלה את הקייפ',
        'step-3-detail' => 'לך אל המשתמש שלך והעלה את הקייפ שלך. זה יוצג בתוך המשחק.',
        'all-versions' => 'כל הגרסאות',
        'latest' => 'לאחרונה',
        'logged-in' => 'העלה את הקייפ שלך',
        'mirror' => 'מראה',
        'download-via' => 'הורד דרך:',
        'curseforge' => 'CurseForge',
    ],
    'app' => [
        'title' => 'אפליקציית האנדרואיד של SkinMC',
        'headline' => 'תגידו שלום לאפליקציית SkinMC לאנדרואיד.',
        'play-store-attribution' => 'גוגל פליי והלוגו של גוגל פליי הם טריידמארקים של חברת גוגל LLC.',
        'features' => 'שימוש באפליקציה על הדרך',
        'feature-qr' => 'סורק ברקוד מובנה',
        'feature-qr-detail' => 'השתמשו בסורק הברקוד המובנה באפליקצייה כדי לסרוק בקלות מהאתר לאפליקציה את הברקודים של שלל השחקנים, או רק של חברים שלכם.',
        'feature-files' => 'שומר אוטומטית למכשיר',
        'feature-files-detail' => 'עם השימוש במנהל הקבצים של אנדרואיד, אתם יכולים להוריד ישירות מהאפליקצייה סקינים, מה שעוזר בשביל סקינים לבדרוק.',
        'feature-noads' => 'ללא פרסומות',
        'feature-noads-detail' => 'עיצוב נוח ונגיש, ללא הפרעות. תהנו מחוויה ללא פרסומות ובלי הצקות בתוך האפליקציה.',
        'feature-experience' => 'חוויה',
        'feature-experience-detail' => 'תהנו מהחוויה המלאה של SkinMC בכל מקום, עם פיצ\'רים מיוחדים. התאימו את הפרופיל שלכם, ערכו את המידע עליכם, וצרו ברקודים מגניבים ועוד מלא דברים!',
        'get-app-headline' => 'הורידו את האפליקצייה',
        'get-app-detail' => 'חווית המיינקראפט הייוחדית שלכם באנדרואיד — זמין להורדה בחינם.',
    ],
    'random' => [
        'title' => 'טוען סקין רנדומלי',
        'description' => 'טוען סקין רנדומלי',
        'headline' => 'אנא המתן...',
        'redirect' => 'אתה תועבר באופן אוטומטי. הדף לא נטען?',
        'click-here' => 'לחץ כאן',
        'messages' => [
            '1' => 'טוען סקין רנדומלי...',
            '2' => 'חוצב למטה...',
            '3' => 'קריפר, או מאן...',
            '4' => 'מחפש בתיבות...',
            '5' => 'האם אתם ידעתם שהסקין הבא הוא לגמרי רנדומלי?',
            '6' => 'סקין רנדומלי מגיע...',
            '7' => 'רק עוד בלוק אחד...',
            '8' => 'מסדר את האינונטורי...',
            '9' => 'מכין דיימנוד פיקקס...',
            '10' => 'מחפש את הירובריין...',
        ],
    ],
    'feed' => [
        'title' => 'Feed',
        'following' => 'Following',
        'sign-up' => 'Sign up or log in to join the conversation.',
        'link-account' => 'Link your Minecraft account to join the conversation.',
        'placeholder' => 'What is happening?',
        'audience' => 'Audience',
        'audience-title' => 'Who can see this?',
        'everyone' => 'Everyone',
        'everyone-info' => 'Anyone on or off SkinMC.',
        'followers' => 'Followers',
        'followers-info' => 'Signed in or members following me.',
        'private' => 'Only me',
        'private-info' => 'Private post only I can see.',
        'submit' => 'Post',
        'like' => 'Like',
        'comment' => 'Reply',
        'share' => 'Share',
        'remaining' => 'Remaining',
        'profile' => 'Posts by :username',
        'posts' => 'All posts',
        'my-posts' => 'My posts',
        'view-all' => 'View all posts',
        'post' => [
            'meta' => ':username on SkinMC: :text',
            'title' => 'Post',
            'created' => 'Status update posted!',
            'confirm-delete' => 'Are you sure you would like to delete this post? It can not be undone.',
            'delete' => 'Delete post',
            'deleted' => 'Your post was deleted.',
        ],
        'repost' => [
            'button' => 'Repost',
            'quote_button' => 'Quote',
            'title' => 'Repost this post',
            'quote_title' => 'Quote post',
            'quote_label' => 'Add a comment (optional)',
            'quote_placeholder' => 'Add your thoughts...',
            'reposted' => 'reposted',
            'success' => 'Reposted!',
            'removed' => 'Repost removed.',
            'already_reposted' => 'You have already reposted this.',
            'undo' => 'Undo repost',
            'original_deleted' => 'The original post has been deleted.',
            'deleted_post' => 'This post has been deleted',
        ],
        'hashtags' => [
            'title' => 'Trending',
            'trending-now' => 'Trending now',
            'post' => 'post',
            'posts' => 'posts',
            'hashtag' => 'Hashtag',
            'hashtags' => 'Hashtags',
            'no-results' => 'No hashtags found',
        ],
        'search' => [
            'title' => 'Search',
            'placeholder' => 'Search posts, hashtags...',
            'no-results' => 'No results found',
            'posts' => 'Posts',
            'no-hashtags-found' => 'No hashtags found matching ":query"',
            'no-results-found' => 'No results found for ":query"',
        ],
        'poll' => [
            'title' => 'Poll',
            'create' => 'Create a poll',
            'option' => 'Option',
            'add_option' => 'Add option',
            'duration' => 'Duration',
            'duration_1' => '1 day',
            'duration_3' => '3 days',
            'duration_7' => '7 days',
            'votes' => '{0} votes|{1} vote|[2,*] votes',
            'ended' => 'Poll ended',
            'ends_in' => 'Ends :time',
            'login_required' => 'Sign in to vote',
        ],
        'gif' => [
            'title' => 'GIF',
            'search_placeholder' => 'Search KLIPY for GIFs...',
            'no_results' => 'No GIFs found',
            'powered_by' => 'Powered by',
            'categories' => 'Categories',
            'trending' => 'Trending',
        ],
        'media' => 'Media',
        'follow-suggestions' => 'Follow the team',
        'explore' => 'Explore',
        'hashtag' => 'Hashtag',
        'no_users' => 'No users found.',
        'stories' => [
            'archive' => [
                'title' => 'Story Archive',
                'subtitle' => 'Your archived stories are only visible to you',
                'empty' => 'No archived stories yet',
                'empty-description' => 'Stories you post will appear here after 24 hours.',
                'action' => 'Archive',
                'archived' => 'Story moved to archive.',
                'already-archived' => 'Story is already archived.',
            ],
        ],
    ],
    'private' => [
        'title' => 'Private posts',
        'text' => 'This post is private.',
    ],
    'liked' => [
        'title' => 'Liked',
    ],
    'following' => [
        'title' => 'Following',
        'text' => 'Sign in to view this post.',
    ],
    'tags' => [
        'empty' => 'No tags to vote on yet',
        'empty-subtitle' => 'Be the first to add one',
    ],
    'inbox' => [
        'title' => 'Messages',
        'details' => 'Details',
        'message_user' => 'Message',
        'write_message' => 'Write a message',
        'empty' => [
            'no_message_selected' => 'No message selected',
            'open_or_start_conversation' => 'Open a conversation from the message list, or start a new one.',
            'no_messages' => 'No unread messages',
            'start_conversation' => 'Once you start a new conversation, your messages will be displayed here.',
            'conversation' => 'This is the beginning of your conversation with :username.',
            'users' => 'Unable to find any users that match the current query.',
        ],
        'typing' => ':username is typing...',
        'new_message' => 'New message',
        'mark_unread' => 'Mark unread',
        'send_message' => 'Send message',
        'delete_message' => 'Delete message for you',
        'latest_conversations' => 'Latest conversations',
        'delete_conversation' => 'Delete conversation',
        'show_details' => 'Show details',
        'hide_details' => 'Hide details',
        'unread' => 'Unread',
        'deleted' => 'Deleted',
        'report_message' => 'Report message',
        'add_reaction' => 'Add reaction',
        'today' => 'Today',
        'reconnect' => 'Please reconnect your Minecraft account to chat',
        'account_disconnected' => 'This user disconnected their linked Minecraft account.',
        'saved_messages' => 'Saved messages',
        'new_message_to_label' => 'To',
        'external-link-to' => 'This link will take you to',
        'external-link-confirmation' => 'Are you sure you want to go there?',
        'external-link' => 'External link',
        'reply' => 'Reply',
    ],
    'server' => [
        'manage' => [
            'stats' => 'Stats',
        ],
    ],
    'report' => [
        'button' => 'Report',
        'title' => 'Report content',
        'describe' => 'Briefly describe why you are reporting this',
        'select' => 'Select report reason',
        'submit' => 'Submit report',
        'reasons' => [
            'INAPPROPRIATE_CONTENT' => 'Inappropriate content',
            'SPAM' => 'Spam',
            'HARASSMENT' => 'Harassment',
            'OTHER' => 'Other',
        ],
    ],
    'leaderboard' => [
        'title' => 'Leaderboard',
        'description' => 'View the SkinMC leaderboard of users.',
        'headline' => 'Top 10',
        'all-time-invites' => 'All time invites',
        'all-time-xp' => 'All time XP',
        '30-day-xp' => '30 days XP',
    ],
];
