<?php

return [
    'login' => [
        'title' => 'Log in',
        'email' => 'Email address',
        'password' => 'Password',
        'button' => 'Log in',
        'editor_save_context' => "Log in to save your skin to the gallery. Your work won\'t be lost.",
        'forgot' => 'Forgot your password?',
        'reset' => 'Reset',
        'register' => 'Don\'t have an account yet?',
        'signup' => 'Sign up',
        'google' => 'Continue with Google',
        'microsoft' => 'Continue with Microsoft',
        'facebook' => 'Continue with Facebook',
        'twitter' => 'Continue with Twitter',
        'divider' => 'or',
    ],
    'signup' => [
        'title' => 'Sign up',
        'existing' => 'Already have an account?',
        'button' => 'Agree and continue',
        'terms_by_selecting' => 'By selecting',
        'terms_agree_to' => ', I agree to SkinMC\'s',
        'terms_acknowledge' => 'and acknowledge the',
    ],
    'recover' => [
        'title' => 'Recover account',
        'description' => 'Lost your password? Recover it by entering your email address to get it back.',
        'button' => 'Send recovery email',
        'found' => 'Found your password?',
    ],
    'logout' => [
        'title' => 'Log out',
        'description' => 'Are you sure you would like to log out of your SkinMC account?',
        'logout' => 'Log out',
        'cancel' => 'Cancel',
    ],
    'profile_qrcode' => [
        'title' => 'Scan QR code',
        'done' => 'Done',
    ],
    'language' => [
        'title' => 'Language',
        'description' => 'Choose your language',
        'contribute' => 'Contribute',
        'contribute_add' => 'Add translation',
        'updated' => 'Your language has been set',
    ],
    'copied' => 'Copied to clipboard!',
    'close' => 'Close',
    'feedback' => [
        'title' => 'Feedback',
        'type' => [
            'select' => 'Select feedback type',
            'label' => 'Feedback type',
            'comment' => 'Comments',
            'question' => 'Questions',
            'bug' => 'Bug report',
            'feature' => 'Feature request',
        ],
        'submit' => 'Submit',
        'nps' => 'On a scale from 0 to 10 how likely would you recommend SkinMC to a friend?',
        'success' => [
            'title' => 'Thank you!',
            'message' => 'Your message has been sent, expect a reply soon! For further questions, feel free join the Discord or submit another message.',
        ],
    ],
];
