<?php

return [
    'skins' => 'Skins',
    'avatars' => 'Avatars',
    'editor' => 'Editor',
    'heads' => 'Heads',
    'capes' => 'Capes',
    'servers' => 'Servers',
    'achievement' => 'Achievement',
    'armor' => 'Armor stand',
    'banners' => 'Banners',
    'banner' => 'Banner Editor',
    'profile' => 'My profile',

    'generators' => 'Generators',

    // Navigation dropdowns
    'feed' => 'Feed',
    'discover' => 'Discover',
    'mods' => 'Mods',
    'shaders' => 'Shaders',
    'resource_packs' => 'Resource Packs',
    'modpacks' => 'Modpacks',
    'datapacks' => 'Data Packs',
    'plugins' => 'Plugins',

    'logout' => 'Log out',
    'register' => 'Sign up',
    'login' => 'Log in',
    'about' => 'About',
    'contact' => 'Contact',
    'faqs' => 'FAQs',

    'minecraft_name' => 'Minecraft Name',
    'minecraft_uuid' => 'Minecraft UUID',
    'what' => 'What',
    'recent_searches' => 'Recent searches',
    'username' => 'Username',
    'uuid' => 'UUID',
    'search' => 'Search',
    'search_placeholder' => 'Try',
    'search_placeholder_uuid' => 'Enter UUID',
    'start_search' => 'Start searching',
    'cancel_search' => 'Cancel',
    'search_type' => 'Search type',
    'search_type_all' => 'All results',
    'profiles' => 'Profiles',
    'view_skin' => 'View skin',
    'edit_skin' => 'Edit skin',
    'make_avatar' => 'Make avatar',
    'find_heads' => 'Find player heads',
    'no_results_found' => 'No suggestions yet. Hit Enter to look it up.',

    'home' => 'Home',
    'help' => 'Help',
    'tools' => 'Tools',
    'more-tools' => 'More tools',
    'skin_viewer' => 'Skin viewer',
    'avatar_maker' => 'Avatar maker',
    'collections' => 'Collections',
    'popular_skins' => 'Popular skins',
    'cartoon_skins' => 'Cartoon skins',
    'animal_skins' => 'Animal skins',
    'community' => 'Community',
    'imprint' => 'Imprint',
    'cookies' => 'Cookies',
    'terms' => 'Terms of Service',
    'privacy' => 'Privacy policy',
    'app' => 'App',
    'mod' => 'Mod',
    'totem' => 'Totems',
    'cube' => 'Cube',
    'new' => 'New',

    'feedback' => 'Feedback',
    'status' => 'Status',
    'recent_searches_placeholder' => 'As you start searching, your past searches will show here.',
    'recent_views_placeholder' => 'After visiting some profiles, your past visited ones will show here.',
    'moderate' => 'Moderate',
    'listings' => 'Listings',
    'add' => 'Add',

    // Autocomplete types
    'autocomplete' => [
        'profile' => 'Profile',
        'server' => 'Server',
        'project' => 'Project',
        'skin_tag' => 'Skin Tag',
        'server_category' => 'Server Category',
        'modrinth_category' => 'Project Category',
    ],

    'theme' => [
        'title' => 'Theme',
        'dark' => 'Dark',
        'light' => 'Light',
        'auto' => 'Auto',
    ],

    'language' => 'Language',
];
