<?php

return [
    'login' => [
        'title' => 'Anmelden',
        'email' => 'E-Mail-Adresse',
        'password' => 'Passwort',
        'button' => 'Anmelden',
        'editor_save_context' => "Melde dich an, um deinen Skin in der Galerie zu speichern. Deine Arbeit geht nicht verloren.",
        'forgot' => 'Passwort vergessen?',
        'reset' => 'Zurücksetzen',
        'register' => 'Noch kein Konto?',
        'signup' => 'Registrieren',
        'google' => 'Mit Google fortfahren',
        'microsoft' => 'Mit Microsoft fortfahren',
        'facebook' => 'Mit Facebook fortfahren',
        'twitter' => 'Mit Twitter fortfahren',
        'divider' => 'oder',
    ],
    'signup' => [
        'title' => 'Registrieren',
        'existing' => 'Account bereits vorhanden?',
        'button' => 'Zustimmen und fortfahren',
        'terms_by_selecting' => 'Indem ich unten ',
        'terms_agree_to' => 'auswähle, erkläre ich mich mit folgenden Regeln von SkinMC einverstanden:',
        'terms_acknowledge' => 'und',
    ],
    'recover' => [
        'title' => 'Konto wiederherstellen',
        'description' => 'Passwort vergessen? Wiederherstellen durch Eingabe deiner E-Mail-Adresse, um es zurückzuerhalten.',
        'button' => 'Wiederherstellungs-E-Mail senden',
        'found' => 'Passwort gefunden?',
    ],
    'logout' => [
        'title' => 'Abmelden',
        'description' => 'Bist du dir sicher, dass du dich von deinem SkinMC-Konto abmelden möchtest?',
        'logout' => 'Abmelden',
        'cancel' => 'Abbrechen',
    ],
    'profile_qrcode' => [
        'title' => 'QR-Code scannen',
        'done' => 'Fertig',
    ],
    'language' => [
        'title' => 'Sprache',
        'description' => 'Wähle deine Sprache',
        'contribute' => 'Mitwirken',
        'contribute_add' => 'Übersetzung hinzufügen',
        'updated' => 'Deine Sprache wurde eingestellt',
    ],
    'copied' => 'In die Zwischenablage kopiert!',
    'close' => 'Schließen',
    'feedback' => [
        'title' => 'Feedback',
        'type' => [
            'select' => 'Feedback-Typ wählen',
            'label' => 'Feedbackart',
            'comment' => 'Kommentare',
            'question' => 'Fragen',
            'bug' => 'Fehlerbericht',
            'feature' => 'Funktionsanfrage',
        ],
        'submit' => 'Absenden',
        'nps' => 'Auf einer Skala von 0 bis 10: Wie wahrscheinlich ist es, dass du SkinMC deinen Freunden empfiehlst?',
        'success' => [
            'title' => 'Vielen Dank!',
            'message' => 'Deine Nachricht wurde gesendet, erwarte bald eine Antwort! Für weitere Fragen melde dich bei unserem Discord oder schicke eine weitere Nachricht.',
        ],
    ],
];
