<?php

return [
    'skins' => 'Skins',
    'avatars' => 'Avatare',
    'editor' => 'Editor',
    'heads' => 'Köpfe',
    'capes' => 'Umhänge',
    'servers' => 'Server',
    'achievement' => 'Errungenschaften',
    'armor' => 'Rüstungsständer',
    'banners' => 'Banner',
    'banner' => 'Banner Editor',
    'profile' => 'Mein Profil',

    'generators' => 'Generatoren',

    // Navigation dropdowns
    'feed' => 'Feed',
    'discover' => 'Entdecken',
    'mods' => 'Mods',
    'shaders' => 'Shader',
    'resource_packs' => 'Resource Packs',
    'modpacks' => 'Modpacks',
    'datapacks' => 'Data Packs',
    'plugins' => 'Plugins',

    'logout' => 'Abmelden',
    'register' => 'Registrieren',
    'login' => 'Anmelden',
    'about' => 'Über',
    'contact' => 'Kontakt',
    'faqs' => 'FAQ',

    'minecraft_name' => 'Minecraft-Name',
    'minecraft_uuid' => 'Minecraft-UUID',
    'what' => 'Was',
    'recent_searches' => 'Letzte Suchen',
    'username' => 'Benutzername',
    'uuid' => 'UUID',
    'search' => 'Suchen',
    'search_placeholder' => 'Probiere z.B.',
    'search_placeholder_uuid' => 'Gebe die UUID ein',
    'start_search' => 'Suche starten',
    'cancel_search' => 'Abbrechen',
    'search_type' => 'Suchtyp',
    'search_type_all' => 'Alle Ergebnisse',
    'profiles' => 'Profile',
    'view_skin' => 'Skin anzeigen',
    'edit_skin' => 'Skin bearbeiten',
    'make_avatar' => 'Avatar erstellen',
    'find_heads' => 'Spielerköpfe anzeigen',

    'home' => 'Startseite',
    'help' => 'Hilfe',
    'tools' => 'Werkzeuge',
    'more-tools' => 'Mehr Werkzeuge',
    'skin_viewer' => 'Skin Betrachter',
    'avatar_maker' => 'Avatar ersteller',
    'collections' => 'Sammlungen',
    'popular_skins' => 'Beliebte Skins',
    'cartoon_skins' => 'Cartoon Skins',
    'animal_skins' => 'Tier Skins',
    'community' => 'Gemeinschaft',
    'imprint' => 'Impressum',
    'cookies' => 'Cookies',
    'terms' => 'Nutzungsbedingungen',
    'privacy' => 'Datenschutzerklärung',
    'app' => 'App',
    'mod' => 'Mod',
    'totem' => 'Totem',
    'cube' => 'Cube',
    'new' => 'New',

    'feedback' => 'Feedback',
    'status' => 'Status',
    'recent_searches_placeholder' => 'Wenn du mit der Suche beginnst, werden deine vorherigen Suchanfragen hier angezeigt.',
    'recent_views_placeholder' => 'Nachdem du einige Profile besucht hast, werden hier deine zuletzt besuchten angezeigt.',
    'moderate' => 'Moderieren',
    'listings' => 'Inserate',
    'add' => 'Hinzufügen',

    'theme' => [
        'title' => 'Theme',
        'dark' => 'Dunkel',
        'light' => 'Hell',
        'auto' => 'Auto'
    ],
];
