<?php

return [
    'auth' => [
        'login' => [
            'title' => 'Willkommen bei SkinMC',
        ],
        'register' => [
            'title' => 'Registriere dich bei SkinMC',
            'subtitle' => 'Starte jetzt und erstelle deinen Account für einen vollen Zugriff.'
        ]
    ],

    'home' => [
        'hero_slogan' => 'Dein Platz für Minecraft Skins.',
        'hero_cta' => 'Überrasche mich',
        'hero_explore_cta' => 'Skins erkunden',
        'skin_viewer' => 'Skin Betrachter',
        'skin_viewer_detail' => 'Durchsuche :count Skins',
        'skin_editor' => 'Skin-Editor',
        'skin_editor_detail' => 'Gestalte deinen eigenen Skin',
        'avatar_maker' => 'Avatar-Generator',
        'avatar_maker_detail' => 'Erstelle deine eigenen Minecraft Profilbilder.',
        'trending' => 'Beliebt',
        'minecraft_skin' => 'Minecraft-Skin',
        'favourite' => 'Favorit',
        'collections' => 'Sammlungen',
        'collections_detail' => 'Kuratierte Minecraft Skins für jede Gelegenheit',
        'about_skinmc' => 'Über SkinMC',
        'about_find' => 'Finde jeden Skin',
        'about_find_detail' => 'Verwende die SkinMC Suche um nach jedem Minecraft Usernamen, und deinen nächsten Skin zu finden, um ihn herunterzuladen.',
        'about_download' => 'Herunterladen oder bearbeiten',
        'about_download_detail' => 'Einen Skin gefunden, den du magst? Füge ihn zu deinen Favoriten hinzu, bearbeite oder lade ihn herunter.',
        'about_platform' => 'Plattformübergreifend',
        'about_platform_detail' => 'Möchtest du den Skin unterwegs nutzen? Scanne den QR-Code und speichere das Bild auf deinem Handy für Minecraft PE.',
        'meta' => [
            'title' => 'Minecraft-Skin Betrachter',
            'description' => 'Schau dir Minecraft-Skins an und lade sie herunter, entdecke die besten Skins in gekuratierten Sammlungen, überprüfe die Verfügbarkeit und Geschichte des Benutzernamens und vieles mehr!',
        ],
        'recently_viewed' => 'Kürzlich angesehen',
        'explore_title' => 'Versuch etwas Neues',
        'explore' => 'Entdecke neue Ideen und Werkzeuge',
        'servers_browse' => 'Entdecke Server',
        'servers' => 'Entdecke die besten Minecraft Server',
        'heads' => 'Minecraft Köpfe',
        'head_description' => 'Durchsuche die Minecraft Kopf-Datenbank, oder erstelle neue.',
        'achievement' => 'Errungenschaften Generator',
        'achievement_detail' => 'Erstelle deine eigenen, benutzerdefinierten und persönlichen Errungenschaften.',
        'continue' => 'Suchen fortsetzen'
    ],
    'profile' => [
        'verified' => 'Verifiziertes Profil',
        'minecraft_profile' => 'Minecraft-Profil',
        'show_qr_code' => 'QR-Code anzeigen',
        'favourite' => 'Favorit',
        'user_title' => ':username Minecraft Skin',
        'user_views' => ':views mal angesehen|:views male angesehen',
        'uuid' => 'UUID',
        'copy' => 'Kopieren',
        'link' => 'Link',
        'skin_history' => 'Minecraft Skin Historie (:skins)',
        'username_history' => 'Benutzernamen-Verlauf',
        'username_history_name' => 'Name',
        'username_history_timestamp' => 'Geändert am',
        'username_history_initial_name' => 'Initialname',
        'user_downloads' => ':downloads download|:downloads downloads',
        'download_skin' => 'Skin herunterladen',
        'apply_skin' => 'Skin anwenden',
        'capes' => 'Umhänge',
        'claim_profile' => 'Bist du :username? Bestätige dein Profil um es zu verifizieren und anzupassen!',
        'claimed' => 'Bestätigtes Profil',
        'meta_description' => 'Lade :username Minecraft Skin herunter. Siehe UUID, Namensverlauf, detaillierte Statistiken und mehr',
        'created_at' => 'Aktualisiert: :changed_at',
        'skins' => [
            'meta_title' => ':username Minecraft Skin Historie',
            'meta_description' => ':username Minecraft Skins Historie und bereits verwendete Skins anzeigen. Verwende die Historie, um vorherige oder alte Skins als Backups und Rollback zu speichern oder um neue Skins zu sammeln.',
            'title' => 'Minecraft Skin Historie'
        ],
        'qr_code' => [
            'meta_title' => ':username\'s QR-Code',
            'meta_description' => ':username Benutzerdefinierter Minecraft-Profil-QR-Code'
        ],
        'sub_nav' => [
            'skin' => 'Skin',
            'about' => 'Über',
            'usernames' => 'Benutzernamen',
            'head' => 'Kopf',
            'comments' => 'Kommentare'
        ],
        'cape' => 'Umhang',
        'elytra' => 'Elytra',
        'nametag' => 'Name Tag',
        'animation' => 'Animation',
        'rotation' => 'Drehung',
        'none' => 'Keine',
        'idle' => 'Wartend',
        'walk' => 'Gehen',
        'run' => 'Laufen',
        'fly' => 'Fliegen',
        'follow' => 'Folgen',
        'following' => 'Du folgst',
        'unfollow' => 'Nicht mehr folgen',
        'followers' => 'Follower',
        'toast' => [
            'following' => 'Du folgst nun :username!',
            'follow-self-error' => 'Sorry, :username, du kannst dir nicht selbst folgen.',
            'unfollowed' => 'Du hast :username entfolgt'
        ],
        'edit' => 'Profil bearbeiten',
        'joined' => 'Beigetreten',
        'server-fav-list-empty' => 'Es sieht so aus das :username noch keine Lieblingsserver hat. Sobald :username einen Server als einen Lieblingsserver speichert, kannst du ihn sehen.',
        'server-own-list-empty' => 'Es sieht so aus das :username noch keine Server hat. Sobald :username einen Server auflistet, kannst du ihn hier sehen.',
        'capes-list-empty' => 'Anscheinend trägt :username im Augenblick noch keine Umhänge. Sobald :username einen Umhang trägt, kannst du ihn hier sehen.',
        'feed-own-list-empty' => 'Looks like you haven\'t posted anything to the feed yet! Once you post, you can see your posts here.',
        'feed-list-empty' => 'Hmm, it seems like :username hasn\'t posted anything to the feed yet. Once :username posts something you can see it here.',
        'following-own-list-empty' => 'Sieht so aus, als ob du noch niemandem folgst! Sobald du beginnst Leuten zu folgen, kannst du sie hier sehen.',
        'following-list-empty' => 'Hmm, es scheint als ob :username niemandem folgt. So bald :username Personen folgt, kannst du sie hier sehen.',
        'followers-own-list-empty' => 'Sobald die Leute deinem Profil folgen, werden sie hier angezeigt.',
        'followers-list-empty' => 'Hmm, es scheint, als ob niemand :username folgt. Sei der Erste, der :username folgt. So bald mehr Leute folgen, kannst du sie hier sehen.',
        'render' => 'Render',
        '3d' => '3D-Render',
        '2d' => '2D-Render',
        'name-history-info' => 'Der Benutzername Verlauf wird entfernt. Mojang hat den Zugriff auf die API zur Namenshistorie am 13. September 2022 entfernt, was dazu geführt hat, dass eine genauer Namensverlauf nicht mehr verfügbar ist. Wenn du deinen Namensverlauf verstecken möchten, gehe auf dein Profil, und dann auf Einstellungen um deinen Namensverlauf zu verbergen.',
        'edit-skins' => 'Skin-Verlauf bearbeiten',
        'hide-skin' => 'Skin ausblenden',
        'show-skin' => 'Skin anzeigen',
        'edit-skin' => 'Skin bearbeiten',
        'servers' => [
            'title' => ':username\'s Server',
        ],
        'cape-list' => [
            'title' => ':username\'s Umhänge',
        ]
    ],
    'skin' => [
        'meta' => [
            'title' => ':username Minecraft Skin',
            'description' => 'Minecraft Skin. Lade den Skin herunter und schau dir an, welche Spieler denselben Skin nutzen.',
            'tags' => ':username Minecraft Skin, :username Skin, Minecraft Skin, :username Maßangefertigte Minecraft Skins, Download Skin, Spieler mit dem gleichen Skin',
        ],
        'title' => ':username Minecraft Skin',
        'head' => 'Befehle',
        'head_info' => 'Mit Befehlsblöcken verwenden',
        'first_wearing' => 'Erster Spieler mit diesem Skin:',
        'profiles' => ':profiles profile|:profiles profile',
        'profiles_title' => ':profiles Profil mit diesem Skin|:profiles Profile mit diesem Skin',
        'screenshot' => 'Screenshot',
    ],
    'skins' => [
        'meta' => [
            'title' => 'Seite :current — Alle Minecraft Skins',
            'description' => 'Durchsuche unsere :last Seitenübersicht von :total benutzerdefinierte Minecraft Skins und lade dir dein nächsten Lieblingsskin runter!',
            'tags' => ':username Minecraft Skin, :username Skin, Minecraft Skin, :username Benutzerdefinierte Minecraft Skins, Download Skin, Spieler mit dem gleichen Skin',
            'tags-title' => ':tag Minecraft Skins',
            'tags-description' => 'Durchsuche unsere :last Seitenübersicht von :total :Tag Minecraft Skins und lade deinen Lieblingsskin runter!',
            'tags-metatags' => ':tag Minecraft Skin, :tag Skin, Minecraft Skin, :tag Eigener Minecraft Skin, Download :tag Skin, Minecraft :tag Skins',
        ],
        'title-skin-tags' => 'Getaggte Minecraft-Skins',
        'subtitle' => 'Seite :current von :last von :total Minecraft Skins',
        'subtitle-skin-tags' => 'Seite :current von :last von :total getaggten Minecraft Skins',
        'sort_by' => 'Sortieren nach',
        'latest' => 'Letzte Skins',
        'most_profiles' => 'Meistverwendete Skins',
        'profiles_today' => 'Meistgenutzte heute',
        'profiles_this_week' => 'Meistgenutzte diese Woche',
        'profiles_this_month' => 'Meistgenutzte diesen Monat',
        'default' => 'Standard-Sortierung',
        'this_month' => 'Diesen Monat hinzugefügt',
        'this_week' => 'Diese Woche hinzugefügt',
        'today' => 'Heute hinzugefügt',
        'random' => 'Zufällig',
        'similar' => 'Ähnliche Skins',
        'no_similar_skins' => 'Keine ähnlichen Skins gefunden.',
        'favorite' => ':count Favorit|:count Favoriten',
    ],
    'skin-tags' => [
        'faq' => 'Was sind Tags?',
        'about' => 'Tags sind eine Möglichkeit, um Kategorien zu Skins hinzuzufügen. Mit Tags kannst du einfach mehr Skins entdecken, die dir gefallen!',
        'guidelines' => [
            'good' => [
                'title' => 'Allgemeine Richtlinien für gute Tags sind:',
                'short' => 'Kurz',
                'descriptive' => 'Beschreibend',
                'spelled' => 'Richtig geschrieben',
            ],
            'bad' => [
                'title' => 'Füge keine Tags hinzu wie:',
                'general' => 'Zu allgemein',
                'specific' =>  'Zu spezifisch',
                'too-many-tags' =>  'Sollte drei separate Tags sein',
                'spelling' => 'Sollte :example sein',
            ],
        ],
        'toast' => [
            'added' => 'Der Tag ":tag" würde zur Abstimmung hinzugefügt',
            'removed' => 'Der Tag ":tag" wurde entfernt',
            'upvote' => 'Der Tag ":tag" wurde hochgevotet',
            'downvote' => 'Der Tag ":tag" wurde runtergevotet'
        ],
        'vote' => [
            'up' => 'Hochvoten',
            'down' => 'Runtervoten',
            'remove' => 'Vote entfernen',
        ],
    ],
    'contact' => [
        'contact' => 'Kontakt',
        'email' => 'Bitte schreiben Sie uns gerne bei Fragen unter: <a href="mailto:support@skinmc.net">support@skinmc.net</a>',
        'faq' => 'Bitte schauen Sie erst bei <a href=":link">FAQ page</a> vorbei, falls ihre Fragen dort bereits beantwortet werden können.',
        'other' => 'Andere Wege zu verbinden',
        'other_discord' => 'Trede den Discord Server bei und verbinde dich mit anderen, schreibe über Spiele, teile deine Lieblings Packs und hole dir Hilfe von der Community.',
        'other_twitter' => 'Folge uns auf Twitter um zu sehen wenn ein neues Update oder Feature, Skin der Woche sowie noch vieles mehr veröffentlicht wird.',
        'other_instagram' => 'Folge SkinMC auf Instagram, um neue Minecraft Skins und Bilder zu entdecken.',
        'other_facebook' => 'Werde Fan auf Facebook und sehe alle Beiträge, in denen du kommentieren und mit anderen reden kannst, während du neue Minecraft-Inhalte finden kannst.'
    ],
    'about' => [
        'intro' => '<span>Deine</span> <span>Plattform</span> <span>für</span> <span>Minecraft</span> <span>Skins.</span>',
        'header_credit' => 'Illustration "Epic Nether Battle" von',
        'info' => 'Behalte alles im Auge.',
        'info_explainer' => 'Zeige einen Spielernamenverlauf, sehe seine vorherigen Skins, füge sie als Freund hinzu, lade Skins herunter und erhalte sogar Detailstatistiken.',
        'card_find_title' => 'Finde jeden Minecrafter',
        'card_find_detail' => 'Beginne mit der Suche nach einem beliebigen Spielernamen oder UUID deiner Wahl.',
        'card_view_title' => 'Ansehen, Speichern & Bearbeiten',
        'card_view_detail' => 'Gefunden einen Skin, den du magst? Speichern Sie ihn durch Herunterladen oder verwenden Sie den Editor, um ihn zu Ihrem eigenen zu machen.',
        'card_claim_title' => 'Verifizieren',
        'card_claim_detail' => 'Verbinde dein Minecraft-Konto und bestätige dein Profil, um coole neue Funktionen freizuschalten!',
        'card_customise_title' => 'Profil anpassen',
        'card_customise_detail' => 'Verifizierte Spieler können ihre Social Media Links hinzufügen und ihr Profil zu ihrem eigenen Profil machen.',
        'card_friends_title' => 'Freunde hinzufügen',
        'card_friends_detail' => 'Verbinde dich mit Freunden auf SkinMC und zeige deine Freundesliste im Profil.',
        'card_history_title' => 'Benutzername & Skin Verlauf',
        'card_history_detail' => 'Benutze die erweiterte Suche um den Benutzernamen/Skin Verlauf eines Spielers zu finden und zu sehen.',
        'founders' => 'Die Gründer',
        'founders_cofounder' => 'Mitbegründer von SkinMC',
        'head_of_design' => 'Leiter des Designs',
        'head_of_code' => 'Leiter des Codes',
        'feedback' => 'Sende uns Feedback',
        'faq' => 'Fragen zu Minecraft, Skins und mehr? Lesen Sie unsere FAQs mit Antworten auf häufig gestellte Fragen.',
        'faq_link' => 'FAQ Center besuchen',
        'contact' => 'Möchten Sie uns erreichen oder haben weitere Fragen? Kontaktieren Sie uns direkt.',
        'contact_link' => 'Kontaktieren Sie uns',

    ],
    'faq' => [
        'title' => 'FAQ',
        'subtitle' => 'Häufig gestellte Fragen',
        'help' => 'Benötigst du weitere Hilfe?',
        'discord' => 'Trete dem Discord-Server bei, um mit anderen Minecraft-Spielern zu chatten.',
        'contact' => 'Kontaktiere uns',
        'q' => [
            'change_skin_t' => 'Wie ändere ich meinen Minecraft-Skin?',
            'change_skin' => '
                <p>Um deinen Skin zu ändern, folgendes tun:</p>
                <ol>
                    <li>Besuche <a href="https://my.minecraft.net/en-us/login/">https://my. inecraft.net/de-us/login/</a> und melde dich mit deinem Mojang-Konto an.</li><li>Nachdem du dich angemeldet hast, wähle <b>"Skin"</b> im linken Menü.</li><li>Dann wähle ein Modell aus, das du bevorzugst und lade den Skin deiner Wahl hoch.</li>
                </ol>',
            'change_username_t' => 'Wie ändere ich meinen Minecraft-Benutzername?',
            'change_username' => '
                <p>Um Ihren Benutzernamen zu ändern, gehen Sie folgendermaßen vor:</p>
                <ol>
                    <li>Besuchen Sie <a href="https://account.mojang.com/login" target="_blank" rel="nofollow">https://account. ojang.com/login</a> und melden Sie sich mit Ihrem Mojang-Konto an.</li>
                    <li>Finde deinen Minecraft-Profilnamen und drücke <b>"(Ändern)"</b> Button</li>
                    <li>auf der nächsten Seite geben Sie Ihren gewünschten neuen Benutzernamen ein.</li>
                    <li>Endlich bestätigen Sie die Änderungen, indem Sie Ihr Passwort eingeben und "Name ändern".</li>
                </ol>',
            'dl_t' => 'Wie lade ich jemanden Minecraft Skin herunter?',
            'dl' => '
                <p>Um Minecraft Skin herunterzuladen, machen Sie folgendes:</p>
                <ol>
                    <li>Tippen Sie auf die Suchleiste und geben Sie den Benutzernamen des Players ein, von dem Sie den Skin herunterladen möchten.</li>
                    <li>Auf der Profilseite können Sie eine Vorschau des Skins anzeigen</li>
                    <li>Klicken Sie auf den <strong>Skin herunterladen</strong> Button unter der Vorschau</li>
                </ol>',
            'submit_q' => 'Wie füge ich einen Skin zu einer Sammlung hinzu?',
            'submit_a' => '<p>Bitte füllen das folgende kurze Formular mit dem Benutzernamen und der Kategorie aus, welche du zu deiner Sammlung hinzufügen möchtest. <a href="https://forms.gle/f4Jh5RpGfsHAZ5xE8" target="_blank">Einreichungsformular für Sammlungen</a>',
            'mcpe_t' => 'Kann ich den Skin auf Minecraft PE verwenden?',
            'mcpe' => '
                <p>Ja. Um das Skin in der Minecraft Pocket Edition nutzen zu können, müssen Sie Folgendes tun:</p>
                <ol>
                    <li>Öffnen Sie SkinMC. et auf deinem Smartphone und tippe auf die Suchleiste</li>
                    <li>Gib den Benutzernamen des Skin des Spielers ein, den du herunterladen möchtest</li>
                    <li>Tippe auf den <strong>Skin herunter</strong> Button unter der Vorschau </li>
                    <li><li> Öffne Minecraft PE und tippe auf <strong>Profil</strong> rechts</li>
                    <li>Tippe auf die <strong>+</strong>, oder bearbeiten Sie das Zeichen und gehen Sie zum "klassischen Skins Tab"</li>
                    <li>Tippen Sie auf "Eigentum", dann "importieren", dann "neue Haut auswählen"</li>
                </ol>',
            'change_times_t' => 'Wie oft kann ich meinen Benutzernamen ändern?',
            'change_times' => '<p>Du kannst deinen Minecraft Benutzernamen <strong>einmal</strong> alle <strong>30 Tage</strong>ändern.</p>',
            'available_t' => 'Wenn ich meinen Benutzernamen geändert habe, wann steht es anderen zur Verfügung?',
            'available' => '<p>Wenn Sie zu Ihrem vorherigen Benutzernamen zurückkehren möchten, können Sie <strong>nach 30 Tagen wieder ändern.</strong> Alle anderen müssen zusätzlich <strong>7 Tage</strong> (37 Tage nach dem Wechsel) warten, bevor sie Ihren alten Benutzernamen beanspruchen können. </p>',
            'username_history_t' => 'Können Sie meinen Benutzernamen-Verlauf bitte entfernen?',
            'username_history' => '
                <p>Da die Benutzernamen-Historie von Mojang stammt der Benutzername Verlauf kann nicht entfernt werden. Mojang hat zuvor erklärt, dass ihre Absicht darin bestand, vorherige Benutzernamen zu sehen1 und dass sie eine direkte Methode für die Öffentlichkeit bieten, um auf diese Informationen zuzugreifen.</p>
                <p class="font-14">1<a href="https://help.minecraft.net/hc/en-us/articles/360034636712-Minecraft-Usernames" target="_blank" rel="noreferrer">https://help. inecraft. et/hc/de-de/articles/360034636712-Minecraft-Benutzernamen</a></p>
                <p class="font-14 mb-0">2<a href="https://twitter.com/dinnerbone/status/554739042529849345" target="_blank" rel="noreferrer">https://twitter. om/dinnerbone/status/554739042529849345</a> (Tweet archiviert vor 2 Jahren: <a href="http://archive.is/TeAyj" target="_blank" rel="noreferrer">http://archive. s/TeAyj</a>)
                </p>',
        ],
    ],
    'avatars' => [
        'start' => [
            'title' => 'Erstelle deinen eigenen Minecraft-Avatar',
            'subtitle' => 'Benutze den Minecraft Avatar Generator, um einen lustigen Avatar von jedem Skin zu erstellen!',
            'avatar_face' => 'Face-Avatar',
            'avatar_bust' => 'Avatar Bust-Stil',
            'avatar_cube' => 'Cube Stil Avatar',
            'avatar_head3d' => 'Eigener 3D Kopf',
        ],
        'user' => [
            'title' => 'Skin wählen',
            'subtitle' => 'Gib den Minecraft-Benutzernamen für den Avatar ein, den du erzeugen möchtest',
            'form_label' => 'Minecraft-Benutzername',
            'form_submit' => 'Weiter',
        ],
        'output' => [
            'title' => 'Vorschau und Speichern',
            'subtitle' => 'Viel Spaß mit deinem neuen Minecraft-Avatar',
            'download_info' => 'Mit dem Ergebnis zufrieden? Benutze deinen neuen Avatar, indem du ihn hier herunterlädst',
            'download_button' => 'Avatar herunterladen',
            'avatar_style' => 'Avatar Stil',
            'skin_username' => 'Skin-Benutzername',
            'change' => 'Ändern',
            'generate' => 'Generieren',
            'avatar_colour' => 'Hintergrundfarbe',
            'avatar_colour_palette' => 'Farbpalette',
            'avatar_colour_basic' => 'Einfach',
        ],
        'meta' => [
            'title' => 'Minecraft Avatar Generator',
            'description' => 'Minecraft Avatar Maker: Erstelle eigene Minecraft-Profilbilder mit deinem Minecraft-Skin',
        ],
    ],
    'totem' => [
        'title' => 'Eigenes Minecraft-Totem',
        'subtitle' => 'Benutze den Minecraft Totem Generator, um ein eigenes Ressource pack mit einem Totem der Unsterblichkeit von jedem Skin zu erstellen.',
        'download_info' => 'Sieht\'s gut aus? Wähle deine Minecraft-Version aus, um dein benutzerdefiniertes Ressource pack zu speichern:',
        'meta' => [
            'title' => 'Eigenes Minecraft Totem Generator',
            'description' => 'Eigene Minecraft-Totems: generiere und erstelle ein eigenes Ressource pack mit einem Totem der Unsterblichkeit mit deinem oder einem anderen Spieler Skin.',
        ],
        'type' => [
            'mini' => 'Eine Mini-Version von deinem Skin!',
            'full' => 'Eine volle Version von deinem Skin!',
            'model3d' => 'Ein 3D-Modell deines Skins!',
            'add_designs' => 'Möchtest du mehr Designs sehen? Reiche hier deine Designvorschläge ein:'
        ]
    ],
    'achievement' => [
        'header' => [
            'title' => 'Erstelle deine eigene Minecraft-Errungenschaft',
            'subtitle' => 'Verwende den Minecraft Achievement Generator um deine ganz eigene benutzerdefinierte Leistung zu erstellen und zeige deine Fortschritte in allem, was du möchtest!',
        ],
        'generator' => [
            'yellow_text' => 'Gelber Text',
            'white_text' => 'Weißer Text',
            'choose_icon' => 'Symbol auswählen',
            'face' => 'Minecraft-Skin statt Symbol',
            'form_submit' => 'Herunterladen',
            'form_label' => 'Minecraft-Benutzername',
            'download' => 'Herunterladen',
            'embed' => 'Einbetten',
            'embed_copy' => 'Kopieren',
        ],
        'meta' => [
            'title' => 'Minecraft Errungenschaft Generator',
            'description' => 'Erstelle benutzerdefinierte Minecraft-Errungenschaften und Achievements mit dem Generator von Errungenschaften. Lade das Bild direkt herunter, verwende es als Forumssignatur, Einbette es mit HTML oder BB-Code und mehr',
        ],
    ],
    'armor' => [
        'header' => [
            'title' => 'Minecraft Rüstungsstand Ersteller',
            'subtitle' => 'Generiere und erstelle deine eigenen Minecraft Rüstungsständer. Erstelle verschiedene Posen, Positionen, Platziere Items und vieles mehr.',
        ],
        'meta' => [
            'title' => 'Minecraft Rüstungsstand Ersteller',
            'description' => 'Generieren und erstellen einfach benutzerdefinierte Minecraft Rüstungsstände. Der Editor hilft bei erstellen von verschiedene Posen, Positionen, platzieren von Items, benutzerdefinierten Skins und vieles mehr.',
        ],
    ],
    'banner' => [
        'editor' => [
            'header' => [
                'title' => 'Minecraft Banner Editor',
                'subtitle' => 'Designe und erstelle deine eigenen Minecraft-Banner. Diese können verwendet werden, um deine Welt zu dekorieren oder auch häufig als <a href="https://optifine.net" target="_blank" rel="nofollow">Optifine</a> Capes verwendet werden.',
            ],
            'meta' => [
                'title' => 'Minecraft Banner Ersteller',
                'description' => 'Erstelle und gestalte deine eigenen Minecraft Banner Designs mit allen Mustern und Farben aus dem Spiel! Diese können verwendet werden, um deine Welt zu schmücken oder als Optifine Cape mit dem Banner getragen werden. Du kannnst auch Codes für Banner oder Schilde generieren.',
            ],
        ],
        'gallery' => [
            'header' => [
                'title' => 'Minecraft Banner Galerie',
                'subtitle' => 'Durchsuchen Sie die Galerie von :count individuell gestalteten Minecraft-Bannern. Du kannst ein Banner als Cape verwenden, um deinen Minecraft-Skin einzigartiger zu machen, oder benutze ein Banner als Fahne, um deine Welt zu dekorieren.',
            ],
            'meta' => [
                'title' => 'Minecraft Banner Galerie',
                'description' => 'Durchsuche die Galerie von :count individuell gestalteten Minecraft-Bannern. Du kannst ein Banner als Cape verwenden, um deinen Minecraft-Skin einzigartiger zu machen, oder benutze ein Banner als Fahne, um deine Welt zu dekorieren.',
            ],
        ],
    ],
    'search' => [
        'meta' => [
            'title' => 'Suchergebnisse: :search',
        ],
        'title' => 'Suchergebnisse',
        'results' => 'Seite :current für :count Ergebnis|Seite :current von etwa :count Ergebnissen ',
        'time' => '(:time Sekunden)',
        'username_available' => 'Benutzername verfügbar*',
        'username_unavailable' => 'Benutzername nicht verfügbar',
        'username_status' => 'Status',
        'username_status_available' => 'Verfügbar*',
        'username_status_unavailable' => 'Nicht verfügbar',
        'username_searches' => 'Suchen',
        'username_searches_count' => ':count / Tag',
        'username_available_disclaimer' => '*Es sei denn, der Name wird vorübergehend oder dauerhaft von Mojang gebannt.',
        'no_results' => 'Keine Profile gefunden. Versuche mit UUID zu suchen, indem du den Suchtyp änderst.',
        'no_results_tags' => 'Keine markierten Skins gefunden. Versuche nach anderen Tags wie "blue", "girl", "fox" usw. zu suchen...',
        'again' => 'Suche wiederholen',
        'sorry' => 'Sssssssssorry...',
        'view_profile' => 'Profil ansehen',
    ],
    'collection' => [
        'title' => 'Minecraft-Skin-Sammlung',
        'subtitle' => 'Durchsuche unsere kuratierte Sammlung von Minecraft-Skins.',
        'filters' => 'Filter',
        'title_trending' => 'Beliebt',
        'title_all' => 'Alle Minecraft-Skins',
        'skin_tags' => 'Markierte Skins',
        'filters_skin_type' => 'Skintyp',
        'filter_skin_type_steve' => 'Steve Typ',
        'filter_skin_type_alex' => 'Alex Typ',
        'cancel' => 'Abbrechen',
        'apply' => 'Anwenden',
        'username_minecraft_skin' => ':username Minecraft-Skin',
        'user_downloads' => '<span class="fw-500">:downloads</span> download|<span class="fw-500">:downloads</span> downloads',
    ],
    'favourites' => [
        'title' => 'Favoriten',
        'subtitle' => 'Zeige und verwalte Skins, für die du später in deiner Favoritenliste gespeichert hast',
        'sort' => 'Sortieren nach',
        'toast' => [
            'added' => 'Zu deinen Favoriten hinzugefügt',
            'removed' => 'Von deinen Favoriten entfernt'
        ],
        'skins' => [
            'button' => 'Skins',
            'empty_headline' => 'Noch keine Lieblingsskins',
            'empty_subtitle' => 'Du hast noch keine Skins in deiner Favoritenliste gespeichert. Besuche die Server-Seite und entdecke deinen nächsten Favoriten!',
            'empty_browse' => 'Skins durchsuchen',
            'meta' => [
                'title' => 'Meine Lieblings Skins',
                'description' => 'Meine Lieblings Minecraft skins',
            ],
        ],
        'servers' => [
            'button' => 'Server',
            'empty_headline' => 'Keine lieblings Server bisher',
            'empty_subtitle' => 'Du hast noch keine Server in deiner Favoritenliste gespeichert. Besuchen die Server-Seite und entdecke deinen nächsten Favoriten!',
            'empty_browse' => 'Server durchsuchen',
            'meta' => [
                'title' => 'Meine Lieblings Server',
                'description' => 'Meine Lieblings-Minecraft-Server',
             ],
        ],

    ],
    'cape' => [
        'editor' => [
            'title' => 'Minecraft Umhang Editor',
            'subtitle' => 'Benutze den Minecraft Umhangs Editor, um deinen eigenen individuellen Umhang zu erstellen.',
            'meta' => [
                'title' => 'Minecraft Umhang Editor',
                'description' => 'Benutze den Minecraft Umhangs Editor, um deinen eigenen individuellen Umhang zu erstellen.',
            ],
        ],
        'list' => [
            'title' => 'Minecraft Capes',
            'subtitle' => 'Offizielle Umhänge (Capes) von Minecraft',
            'meta' => [
                'title' => 'Minecraft Umhänge (Capes) Liste',
                'description' => 'Minecraft Cape Liste: Schau dir alle offiziellen Minecraft-Umhänge an, einschließlich Mojang, Minecon, Personal, Spezial und Vanity Capes an',
            ],
        ],
        'detail' => [
            'title' => ':cape Umhang',
            'info' => 'Cape Informationen',
            'profile_list' => 'Profile mit diesem Umhang',
            'profiles' => ':profiles profile|:profiles profile',
            'meta' => [
                'title' => 'Minecraft Umhänge (Capes) Liste',
                'description' => 'Minecraft Cape-Liste: Schau dir alle offiziellen Minecraft-Umhänge an, einschließlich Mojang, Minecon, Personal, Spezial und Vanity Capes an',
            ],
        ],
        'list-custom' => [
            'title' => 'Eigene Minecraft Capes',
            'description' => 'Durchsuche und schaue dir capes an, die von SkinMC Nutzern erstellt oder benutzt werden.'
        ]
    ],
    'servers' => [
        'title' => 'Minecraft-Server',
        'subtitle' => 'Durchsuchen und Minecraft-Server erkunden',
        'all' => 'Alle Server',
        'manage_your_servers' => 'Server verwalten',
        'add_new_server' => 'Server hinzufügen',
        'filters' => [
            'trending' => 'Beliebt',
            'updated' => 'Aktualisiert',
            'new' => 'Neu',
            'most_viewed' => 'Meistangesehen',
            'top_voted' => 'Top bewertet',
            'sorting' => 'Sortierung',
            'sort_by_latest' => 'Nach neuesten sortieren',
            'sort_by_oldest' => 'Nach ältesten sortieren',
            'categories' => 'Kategorien',
            'server_location' => 'Serverstandort',
            'show_results' => 'Ergebnisse anzeigen',
            'show_more' => 'Mehr anzeigen',
            'show_less' => 'Weniger anzeigen',
            'clear_filters' => 'Filter zurücksetzen',
            'reviews' => 'Bewertungen',
            'sort_by_highest_rating' => 'Nach bester Bewertung sortieren',
            'sort_by_lowest_rating' => 'Nach niedrigster Bewertung sortieren',
            'bedrock_and_java_support' => 'Bedrock und Java Unterstützung'
        ],
        'review-count' => ':count Bewertung|:count Bewertungen',
        'meta' => [
            'title' => 'Minecraft-Server-Liste',
            'description' => 'Durchsuche und erkunde die Minecraft-Serverliste, um den besten Minecraft-Server zu finden! Filtere nach dem aktuellsten, beliebtesten und viel mehr',
        ],
        'reviews' => [
            'meta' => [
                'title' => 'Schreibe eine Bewertung',
            ],
            'editing' => 'Du bearbeitest deine Bewertung von :date. Möchtest du stattdessen deine Bewertung löschen?',
            'welcome' => 'Hi :username. Wie war deine Erfahrung mit :servername?',
            'subtitle' => 'Hinterlasse eine Gesamtbewertung deiner Erfahrung auf diesem Server.',
            'scale' => [
                'great' => 'Perfekt',
                'good' => 'Gut',
                'okay' => 'OK',
                'meh' => 'Na ja',
                'bad' => 'Schlecht',
            ],
            'rate-experience' => 'Bewerte als nächstes deine Erfahrung in diesen Bereichen',
            'overall' => 'Insgesamt',
            'server-team' => 'Serverteam',
            'community' => 'Community',
            'experience' => 'Erfahrung',
            'availablility' => 'Uptime und Verfügbarkeit',
            'shop' => 'Shop',
            'write-review-title' => 'Schreibe eine Bewertung',
            'write-review-subtitle' => 'Hinterlasse ein paar Bemerkungen. Du kannst hervorheben, was dir gefallen hat, was dein Erlebnis besonders gemacht hat, oder ein paar Verbesserungsvorschläge anbieten.',
            'write-review-helper' => 'Schreibe eine Bewertung, um deine Erfahrungen mit neuen Spielern zu teilen, und dem Besitzer Feedback zu geben.',
            'write-review-tips' => 'Hier sind einige Tipps',
            'submit-title' => 'Bereit deine Bewertung abzusenden?',
            'submit-subtitle' => 'Fast geschafft!',
            'submit-review' => 'Meine Bewertung absenden',
            'back' => 'Zurück',
            'continue' => 'Weiter',
            'delete-title' => 'Bist du sicher, dass du deine Bewertung löschen möchtest?',
            'tos-checkbox-part-1' => 'Mit dem Absenden dieses Formulars akzeptierst du die Nutzungsbedingungen, die Datenschutzrichtlinien und die Community-Richtlinien von SkinMC. Du bestätigst außerdem, dass alle oben genannten Informationen korrekt sind, und folgen dem',
            'tos-checkbox-part-2' => 'Bewertungs-Richtlinien.',
            'tos-checkbox-part-3' => 'Deine Bewertung wird nach der Einreichung veröffentlicht, kann aber überprüft werden.'
        ],
        'slots' => 'Slots',
        'empty-helper' => 'Du kannst versuchen, eine andere Suche durchzuführen oder',
        'empty' => 'Hmm ist es hier noch leer.',
        'verified' => 'Verifiziert',
        'review_translate_show_original' => 'Original anzeigen',
        'review_translate' => 'Bewertung übersetzen',
        'description_translate' => 'Beschreibung übersetzen',
        'create' => [
            'welcome' => 'Willkommen',
            'basics' => 'Allgemein',
            'categories' => 'Kategorien',
            'social_links' => 'Social-Links',
            'trailer_video' => 'Trailer-Video',
            'images' => 'Bilder',
            'images_description' => 'Du kannst anschließend Fotos hochladen, um zu zeigen, was dein Server bietet.',
            'submit' => 'Absenden',
            'lets_get_your_server_added' => 'Lass uns deinen Server hinzufügen.',
            'basics-subtitle' => 'Lass die Leute wissen, worum es bei deinem Server geht.',
            'description' => 'Beschreibung',
            'description_tips' => 'Hier sind einige Tipps',
            'description_hint' => 'Schreibe eine gute Beschreibung für deinen Server, um neue Spieler anzuziehen.',
            'categories-subtitle' => 'Wähle einige Kategorien für deinen Server',
            'missing-category' => 'Fehlt eine Kategorie?',
            'social_links_description' => 'Wo können Spieler sich mit deinem Server in sozialen Medien verbinden?',
            'trailer_video_description' => 'Stelle deinen Server mit einem YouTube-Video vor.',
            'trailer_video_hint' => 'Füge die Video-URL oder -ID ein:',
            'ready_to_submit_your_server' => 'Bereit deinen Server abzusenden?',
            'review-hint' => 'Nach der Einreichung wird das Team deinen Antrag auf einen Servereintrag sorgfältig prüfen. Wenn die Entscheidung gefallen ist, wird dein Server veröffentlicht oder es werden Änderungen angefragt, bevor der Server freigeschaltet wird.',
            'terms' => [
                'part-1' => 'Mit dem Absenden dieses Formulars erklärst du dich mit den Nutzungsbedingungen, der Datenschutzrichtlinie und den Community-Richtlinien von SkinMC einverstanden. Du bestätigst außerdem, dass alle oben genannten Informationen korrekt sind, du die',
                'part-2' => 'Server-Anforderungen für die Einrichtung',
                'part-3' => ', und dass der Minecraft-Server im Besitz der von dir vertretenen Entität ist.'
            ],
            'submit-application' => 'Bewerbung abschicken',
            'video-id-helper' => [
                'part-1' => 'Die Video-ID ist die Zeichenkette von Zahlen und Buchstaben nach',
                'part-2' => 'Zum Beispiel, wenn deine Video-URL ist',
                'part-3' => ', dann wäre deine Video-ID'
            ],
            'welcome_description' => 'In diesem Schritt fangen wir an, deinen Server hinzuzufügen. Erzähle uns ein bisschen von deinem Server, schreibe eine Beschreibung, und im nächsten Schritt kannst du ein paar Bilder hochladen.'
        ],
        'copy_server_ip' => 'Server-IP kopieren',
        'all_minecraft_servers' => 'Alle Minecraft-Server',
        'promo' => [
            'title' => 'Hostest du einen Minecraft-Server?',
            'ready_to_list_your_server' => 'Bereit deinen Server zu inserieren?',
            'everything_you_need' => 'Alles, was du brauchst, um deinen Server wachsen zu lassen',
            'list_your_server' => 'Server hinzufügen',
            'list_your_server_description' => 'Erstelle ein Inserat für deinen Server, füge Fotos, Social Media und mehr hinzu.',
            'find_players' => 'Finde Spieler',
            'find_players_description' => 'Finde und erreiche neue Spieler, welche deinem Server beizutreten und deine Community vergrößern.',
            'get_reviews' => 'Bewertungen erhalten',
            'get_reviews_description' => 'Bitte deine Community deinen Server zu bewerten und belohne sie dafür im Spiel.',
            'why_list_on_skinmc' => 'Warum du deinen Server auf SkinMC inserieren solltest',
            'others' => 'Andere',
            'quality_check_and_confirmation' => 'Qualitätsüberprüfung und Bestätigung',
            'quality_check_description' => 'Unser Team überprüft jeden Server, um die Qualität zu gewährleisten.',
            'verified_players' => 'Bewertungen von verifizierten Minecraft-Spielern',
            'verified_players_description' => 'Sammle authentische Spielerbewertungen von legitimen Konten mit Votifier Integration.',
            'international' => 'International',
            'international_description' => 'Mit Übersetzungsfunktionen ist dein Inserat für mehr Spieler verfügbar.',
            'server_listing_page' => 'Leistungsstarkes Server-Inserat',
            'server_listing_page_description' => 'Füge Fotos, Beschreibungstexte, YouTube-Videos hinzu und hebe hervor, warum Spieler deinem Server beitreten sollen.',
            'social_connections' => 'Social-Media-Verbindungen',
            'social_connections_description' => 'Verbinde deine sozialen Konten vom Server und zeige neue Spieler, wo sie dich finden können.',
            'verified_badge' => 'Verifizierungs-Abzeichen',
            'verified_badge_description' => 'Authentische Server können ein Verifizierungszeichen beantragen.',
            'owner_profile' => 'Besitzerprofil',
            'owner_profile_description' => 'Füge eine persönliche Note hinzu, indem du dein persönliches Profil ausfüllst.',
            'categories' => 'Kategorien',
            'categories_description' => 'Verschiedene Kategorien, um die Suche nach deinem Server zu vereinfachen.',
            'vote' => 'Abstimmen',
            'vote_description' => 'Bitte Spieler um Abstimmung für deinen Server.',
            'fair_listings' => 'Faire sortierung',
            'fair_listings_description' => 'Servereinträge können in den Ergebnissen von SkinMC nicht künstlich aufgewertet werden.',
            'support' => '24h-Unterstützung',
            'support_description' => 'Brauchst du Hilfe oder hast Fragen? Du kannst dich jederzeit mit uns in Verbindung setzen und eine schnelle antwort erhalten.',
            'custom_features' => 'Individuelle Funktionen',
            'custom_features_description' => 'Fehlt ein Feature für deinen Server? Öffne ein Ticket und wir werden es implementieren.',
            'faq' => [
                'title' => 'Antworten auf deine Fragen',
                'suited-question' => 'Ist mein Minecraft Server für SkinMC geeignet?',
                'suited-answer' => 'Minecraft-Spieler/innen auf SkinMC lieben es, neue Erfahrungen und Inhalte zu entdecken und sich in Communities zu engagieren. Auf der Plattform findest du eine große Auswahl an verschiedenen, einzigartigen und lustigen Minecraft-Servern. Von einem großen Netzwerk bis hin zu einem kleinen Survival-Server - hier kann jedem der Tag verschönert werden!',
                'get-started-question' => 'Wie fange ich an?',
                'get-started-answer' => 'Das Hinzufügen deines Minecraft-Servers zur SkinMC-Serverliste ist ganz einfach! Du musst zuerst einen Account erstellen, falls du das noch nicht getan hast, und dann der Anleitung folgen, um deinen Server in die Liste aufzunehmen. Füge ein paar Fotos und eine aussagekräftige Beschreibung hinzu und dein Server wird im Handumdrehen veröffentlicht!',
                'players-question' => 'Wie kann ich mehr Spieler auf meinem Minecraft-Server bekommen?',
                'players-answer' => 'Der Aufbau einer Community ist der wichtigste Teil eines dauerhaften Minecraft Servers. Nutze die Minecraft Server-Liste auf SkinMC, um ein neues Publikum zu finden und deine Community weiter auszubauen. Bitte deine Spielerinnen und Spieler, deinen Server weiterzuempfehlen, oder teile deinen Eintrag auf Social Media Plattformen. Auch das Sammeln von guten Bewertungen kann eine wichtige Rolle für eine gute Serverliste spielen, die neue Spieler anzieht.',
                'more-question' => 'Ich habe weitere Fragen. Wo kann ich Hilfe bekommen?',
                'more-answer' => 'Du kannst jederzeit auf SkinMC zugreifen, 24 Stunden, indem du entweder den Hilfe-Button verwendest, das Helpdesk, oder indem du dem Discord Server beitritt.'
            ],
            'ready_to_list_description' => 'Füge deinen Minecraft-Server in wenigen Minuten zur SkinMC Server-Liste hinzu. Wenn Du Hilfe benötigst, kannst du dich rund um die Uhr austauschen und schnell Antworten erhalten.'
        ],
        'manage' => [
            'index' => [
                'welcome' => 'Willkommen zurück, :username',
                'your_servers' => 'Deine Server',
                'reviews_today' => 'Bewertungen heute',
                'no_reviews_today' => 'Noch keine Bewertungen heute',
                'no_reviews_text' => 'Deine Server haben heute noch keine Bewertungen erhalten. Warum bittest du deine Spieler nicht, eine zu hinterlassen?',
                'tips' => [
                    'title' => 'Tipps',
                    'description-title' => 'Schreibe eine gute Serverbeschreibung',
                    'description-body' => 'Hilfreiche Tipps und Ratschläge zum Verfassen einer guten Serverbeschreibung.',
                    'images-title' => 'Serverbilder hinzufügen',
                    'images-body' => 'Hebe dein Server-Inserat mit tollen Bildern hervor.'
                ]
            ],
            'listings' => [
                'title' => 'Deine Minecraft-Server (:count)'
            ],
            'insights' => [
                'title' => 'Einblicke'
            ],
            'edit_server' => 'Server bearbeiten',
            'listing' => 'Anzeige',
            'to_do' => 'Zu erledigen',
            'last_update' => 'Letztes Update',
            'add_more_photos_to_publish' => 'Weitere Fotos zum Veröffentlichen hinzufügen',
            'looks_empty_here' => 'Hier sieht\'s leer aus.',
            'get_started_by_adding_a_new_server' => 'Lege los, indem du einen Server hinzufügst.'
        ],
        'status' => [
            'approved' => 'Freigegeben',
            'pending_approval' => 'Ausstehende Genehmigung',
            'published' => 'Veröffentlicht',
            'in_review' => 'Wird überprüft'
        ]
    ],
    'editor' => [
        'import' => [
            'title' => 'Skin importieren',
            'import_by_username' => 'Nach Benutzername importieren',
            'import_button' => 'Importieren',
            'drag' => 'Ziehe einen Skin hierher oder klicke',
            'click' => 'Bild auswählen'
        ],
        'draw' => 'Zeichnen',
        'eyedropper' => 'Farbpipette',
        'fill' => 'Füllen',
        'move' => 'Verschieben',
        'decrease_brightness' => 'Helligkeit verringern',
        'increase_brightness' => 'Helligkeit erhöhen',
        'erase' => 'Radiergummi',
        'undo' => 'Rückgängig (Strg+Z)',
        'redo' => 'Vorwärts (Strg+Y)',
        'default_view' => 'Standardansicht',
        'zoom_in' => 'Vergrößern (Strg +)',
        'zoom_out' => 'Verkleinern (Strg -)',
        'saved' => 'Zuletzt gespeichert',
        'saving' => 'Auto-Speichern...',
        'save_error' => 'Ein Fehler ist aufgetreten',
        'new_skin' => 'Neuer Skin',
        'previous_skins' => 'Vorherige Skins',
        'backed_up_title' => 'Automatisch gespeicherte Skins',
        'backed_up_info' => 'Vorübergehend auf den lokalen Speicher gesichert.',
        'backed_up_empty_title' => 'Hier sieht\'s leer aus',
        'backed_up_empty_info' => 'Sobald du mit der Bearbeitung von Skins begonnen hast, wirst du deine 32 letzten Skins hier sehen.',
        'backed_up_skins_count' => 'von 32 verwendeten Skin Backups',
        'backed_up_skins_count_info' => 'Du kannst bis zu 32 Skins wiederherstellen. Sobald du 32 Skins erreicht hast, wird ein älterer Skin durch einen neuen ersetzt.',
        'layers' => 'Ebenen',
        'body' => [
            'title' => 'Körper',
            'overlay' => 'Overlay',
            'head' => 'Kopf',
            'torso' => 'Oberkörper',
            'l_arm' => 'Linker Arm',
            'r_arm' => 'Rechte Arm',
            'l_leg' => 'Linkes Bein',
            'r_leg' => 'Rechtes Bein',
        ],
        'model' => 'Modell',
        'steve' => 'Steve',
        'alex' => 'Alex',
        'stance' => [
            'title' => 'Position',
            'default' => 'Standard',
            'walk' => 'Gehe',
            'run' => 'Ausführen',
            'hug' => 'T-Posten',
            'fly' => 'Fliegen',
        ],
        'fullscreen' => 'Vollbildmodus',
        'fullscreen_exit' => 'Vollbildmodus beenden',
        'grid' => 'Raster',
        'show_grid' => 'Raster anzeigen',
        'download' => [
            'title' => 'Speichern & herunterladen',
            'subtitle' => 'SkinMC Konto',
            'description' => 'Möchten Sie ein kostenloses SkinMC-Konto erstellen, um Ihre Haut und zukünftige in der Cloud zu speichern?',
            'start_description' => 'Download direkt starten ohne in der Cloud zu speichern',
            'start' => 'Skin herunterladen',
        ],
        'help' => [
            'title' => 'Minecraft Skin Bearbeitungsprogramm',
            'about' => 'Erstelle und bearbeite deinen eigenen Minecraft Skin einfach mit dem SkinMC Editor. Du kannst zwischen Steve und Alex Modellen wählen, Skins aus einer Datei oder einem Benutzernamen importieren und so deinen eigenen Minecraft Skin erstellen.',
            'draw' => 'Zeichne mit dem Mal-Werkzeug. Wähle eine Farbe aus dem Farbfeld aus, die du verwenden möchtest.',
            'eyedropper' => 'Wähle mit der Pipette eine Farbe aus deinem Minecraft Skin aus und füge sie zu deiner aktuellen Palette hinzu.',
            'fill' => 'Fülle ganze Bereiche deines Minecraft Skin mit dem Füllwerkzeug aus. Wähle vor der Füllung eine Farbe aus.',
            'move' => 'Verschieben und bewege dich mit dem Bewegungs-Button um den Skin Editor.',
            'decrease_brightness' => 'Verringert die Helligkeit der aktuell aktiven Farbe.',
            'increase_brightness' => 'Erhöht die Helligkeit der aktuell aktiven Farbe.',
            'erase' => 'Lösche Pixel, die auf der sekundären Overlay-Ebene gezeichnet wurden.',
        ],
    ],
    'account' => [
        'level' => 'Level',
        'level_history' => 'Levelverlauf',
        'xp' => 'XP',
        'my_xp' => 'Mein XP',
        'xp_to_next_level' => ':xp XP zum nächsten Level',
        'xp_info' => 'Was sind XP?',
        'xp_info_tooltip' => 'XP erhält man für verschiedene Aktivitäten wie das Hinzufügen von Tags zu Skins, das Einladen von Freunden, Kommentieren und vieles mehr. Mit jedem verdienten XP kannst du aufleveln und coole Dinge freischalten!',
        'settings' => [
            'title' => 'Konto',
            'show_profile' => 'Gehe zum Profil',
            'friends' => 'Freunde',
            'friends_detail' => 'Bleiben Sie mit Ihrer Freundesliste auf SkinMC verbunden.',
            'security' => 'Sicherheit',
            'security_detail' => 'Aktualisiere dein Login-Passwort und halte dein Konto sicher',
            'social' => 'Social-Media-Konten',
            'social_detail' => 'Personalisiere dein Profil, indem du deine sozialen Medien hinzufügst',
            'link' => 'Minecraft-Konto verknüpfen',
            'link_detail' => 'Verbinde dein Minecraft-Konto und erhalte dein Profil.',
            'logout' => 'Möchtest du dich von deinem SkinMC-Konto abmelden?',
            'automatic_backups' => 'Automatische Skin-Backups',
            'automatic_backups_info' => 'Als SkinMC plus Mitglied werden deine Skins täglich gesichert.',
        ],
        'capes' => [
            'title' => 'SkinMC Minecraft Cape',
            'description' => 'Trage kostenlos ein beliebiges Cape mit SkinMC Capes.',
            'drop' => 'Ziehe ein Cape hierher',
            'drop-hint' => 'Abmessungen 64x32px',
            'select' => 'Bild auswählen',
            'upload-cape' => 'Hochladen & Cape benutzen',
            'save-and-use' => 'Speichern & verwenden',
            'uploaded-cape' => 'Hochgeladenes Bild',
            'no-cape' => 'Kein Cape',
            'remove-cape' => 'Cape entfernen',
            'download' => 'Lade die SkinMC Mod herunter, um deine und die Capes anderer Spieler im Spiel zu sehen.',
            'learn-more' => 'Weitere Informationen',
            'link-account' => 'Bitte verlinke deinen Minecraft-Account, um ein Cape hochzuladen.',
            'updated' => 'Ihr Cape wurde aktualisiert!',
            'removed' => 'Dein Cape wurde entfernt.',
            'active' => 'Dein Cape wurde aktiviert!'
        ],
        'favourite' => 'Favorit',
        'remove_favourite' => 'Favorit entfernen',
        'added_to_favourites' => 'Zu Favoriten hinzugefügt',
        'removed_from_favourites' => 'Von Favoriten entfernen',
        'welcome' => 'Schön, dich zu sehen!',
        'view-profile' => 'Profil ansehen',
        'security' => [
            'title' => 'Sicherheit',
            'email' => 'E-Mail-Adresse',
            'email-title' => 'Ändere deine E-Mail-Adresse.',
            'save' => 'Speichern',
            'password' => 'Passwort',
            'password-title' => 'Ändere jederzeit dein Passwort.',
            'social-provider' => 'Um deine Kontoinformationen, wie z.B. dein Passwort, zu aktualisieren, besuche bitte deinen Login-Anbieter:',
            'social-provider-email' => 'Deine mit deinem Login-Anbieter verbundene E-Mail-Adresse',
            'social-provider-connected' => 'Derzeit verbundene Login-Anbieter',
            'current-password' => 'Aktuelles Passwort',
            'forgot' => 'Passwort vergessen?',
            'edit' => 'Bearbeiten',
            'delete' => 'Mein Konto Löschen',
            'account-deletion' => 'Lösche dein SkinMC Konto.',
            'delete-info' => 'Um fortzufahren bitte bestätigen',
            'delete-confirmation' => 'Das Löschen deines Kontos ist unwiderruflich. All deine persönlichen Informationen und Inhalte wie Beiträge, Favoriten, hochgeladene Umhänge, Anpassungen usw. werden gelöscht und können nicht wiederhergestellt werden.',
            'delete-confirmation-info' => 'Gib dein Passwort ein, um fortzufahren',
            'yes-confirm-delete' => 'Ja, Löschen bestätigen',
            'account-successfully-deleted' => 'Dein Konto und deine Daten wurden erfolgreich gelöscht.'
        ],
        'social' => [
            'title' => 'Soziale Konten',
            'edit' => 'Bearbeiten',
            'save' => 'Speichern',
            'link-account' => 'Verbinde dein Minecraft-Konto mit SkinMC, um deine Social-Media Links auf deinem Profil anzuzeigen.',
            'finish-setup' => 'Fertig stellen',
            'connect-account' => 'Verknüpfe deine Accounts',
            'connect-description' => 'Wähle aus, welche Konten du verbinden möchtest und entsperre spezielle SkinMC-Integrationen.',
            'empty' => 'Keine Konten hinzugefügt',
            'empty-description' => 'Deine Social-Media-Konten werden hier und auf deinem öffentlichen Profil erscheinen. Nach dem Hinzufügen fügen fügen sie mehr Personalisierung zu deiner Seite hinzu und ermöglichen Integrationen.',
            'connect' => 'Verbinde',
            'username' => 'benutzername',
            'spotify' => 'Füge deinen Spotify-Benutzernamen hinzu, um deine Spotify-Informationen in deinem Profil anzuzeigen.',
            'discord' => 'Gib deinen Discord Benutzernamen und deine Nummer ein, um deine Discord Informationen auf deinem SkinMC Profil anzuzeigen.',
            'youtube' => 'Füge deinen YouTube-Kanal zu SkinMC hinzu, um den YouTube-Kanal auf deinem Profil anzuzeigen.',
            'youtube-format' => 'Benutze das folgende Format, entsprechend deines Kanallinks:',
            'twitter' => 'Gebe deinen Twitter-Benutzernamen ein, um ihn auf deinem Profil anzuzeigen.',
            'twitch' => 'Gebe deinen Twitch-Benutzernamen ein, um ihn auf deinem Profil anzuzeigen.',
            'reddit' => 'Gebe deinen Reddit Benutzernamen ein, um dein Reddit Profil auf deinem Profil anzuzeigen.',
            'github' => 'Gebe deinen GitHub Benutzernamen ein, um dein GitHub Profil auf deinem Profil anzuzeigen.',
            'telegram' => 'Gebe deinen Telegram Benutzernamen ein, um dein Telegram link auf deinem Profil anzuzeigen.',
            'tiktok' => 'Gebe deinen TikTok Benutzernamen ein, um dein TikTok Profil auf deinem Profil anzuzeigen.',
            'snapchat' => 'Gebe deinen Snapchat Benutzernamen ein, um dein Snapchat Profil auf deinem Profil anzuzeigen.',
            'instagram' => 'Gebe deinen Instagram Benutzernamen ein, um dein Instagram Profil auf deinem Profil anzuzeigen.',
            'facebook' => 'Gebe deinen Facebook Benutzernamen ein, um dein Facebook Profil auf deinem Profil anzuzeigen.',
            'includes_skinmc_plus_benefits' => 'Enthält SkinMC Plus Vorteile',
        ],
        'recover' => [
            'title' => 'Konto wiederherstellen',
            'subtitle' => 'Bitte gebe dein neues Passwort ein und bestätige es, um die Wiederherstellung Ihres Kontos abzuschließen.',
            'new_password' => 'Neues Passwort',
            'repeat_new_password' => 'Neues Passwort wiederholen',
            'submit' => 'Konto wiederherstellen',
        ],
        'customise' => [
            'title' => 'Profil anpassen',
            'description' => 'Füge deine Social-Media-Kanäle hinzu, wähle ein Emoji, stelle deinen Standort ein und mehr',
            'information' => 'Informationen',
            'preview' => 'Vorschau',
            'location' => [
                'title' => 'Standort',
                'description' => 'Wähle den Standort, den du auf deinem Profil hinzufügen möchten.',
            ],
            'biography' => [
                'title' => 'Über mich',
                'description' => 'Schreibe ein Bio für dein Profil.',
            ],
            'status' => 'Status',
            'status-toggle' => 'Meinen Online-Status anzeigen',
            'emoji' => 'Emoji',
            'name-history-toggle' => 'Namensverlauf privat machen',
            'name-history-info' => 'Dein Minecraft-Namensverlauf ist derzeit',
            'name-history-toggle-on' => 'Privat',
            'name-history-toggle-off' => 'öffentlich',
            'theme' => 'Profil-Design',
            'theme-primary' => 'Primär',
            'theme-secondary' => 'Sekundär',
            'appearance' => 'Appearance',
        ],
        'link' => [
            'manage' => 'Verwalte dein verlinktes Minecraft-Konto',
            'description' => 'Sehe und verwalte dein verknüpftes Minecraft-Konto',
            'title' => 'Minecraft-Konto verknüpfen',
            'current' => 'Derzeit verlinktes Minecraft-Konto.',
            'status' => 'Du hast nun vollen Zugriff auf alle SkinMC Funktionen!',
            'linked' => 'Verknüpft',
            'disconnect' => 'Trennen',
            'disconnect-title' => 'Minecraft Konto getrennt',
            'disconnect-info' => 'Bist du dir sicher, dass du dein Minecraft-Konto trennen möchtest?',
            'disconnect-features' => 'Du verlierst Zugriff auf Kommentieren, Anpassungen und andere Funktionen, die ein verknüpftes Minecraft-Konto erfordern. Um diese wieder verwenden zu können, musst du ein Minecraft-Konto verknüpfen.',
            'disconnect-following' => 'Durch das Trennen deines Minecraft-Kontos werden alle deine folgenden Profile dauerhaft entfernt.',
            'disconnect-posts' => 'Deine erstellten Beiträge und Likes werden gelöscht.',
            'can-not-undo' => 'Dies kann nicht rückgängig gemacht werden.',
            'are-you-sure' => 'Bist du dir sicher?',
            'confirm' => 'Ja, die Trennung bestätigen',
            'cancel' => 'Nein, abbrechen',
            'success' => 'Dein Account wurde erfolgreich getrennt!'
        ],
        'finish-setup' => [
            'title' => 'Kontoeinrichtung beenden',
            'description' => 'Beende die Einrichtung deines Kontos und erhalte vollen Zugriff auf alle Funktionen, indem du dein Minecraft-Konto mit SkinMC verbindest.',
            'link' => 'Minecraft-Konto verknüpfen',
            'get-started' => 'Lege los',
            'skip' => 'Überspringen',
            'claim' => 'Sichere dir dein Profil',
            'customise' => 'Personalisiere deine Seite',
            'social' => 'Social-Media Links hinzufügen',
            'comment' => 'Zugriff aufs Kommentarsystem',
            'direct_message' => 'Direktnachrichten senden',
            'feed' => 'Statusänderungen im Feed posten',
            'follow' => 'Folge deinen Freunden',
            'badge' => 'Abzeichen in deinem Profil',
            'cape' => 'Eigenes Minecraft-Cape',
            'backup' => 'Automatische Skin-Backups',
            'more' => 'Und mehr...'
        ],
        'skins' => [
            'title' => 'Skins verwalten',
            'toggle' => 'Skin Sichtbarkeit geändert',
        ],
        'invite' => [
            'title' => 'Meine Einladungen',
            'headline' => 'Lade deine Freunde ein',
            'info' => 'Erstelle einen Einladungscode, den du mit einem Freund teilen kannst. Sobald er ihn akzeptiert, erhaltet ihr beide zusätzliche XP!',
            'description' => 'Erstelle eine Einladung für deine Freunde und ihr erhaltet beide zusätzliche XP.',
            'generate' => 'Erstelle einen Einladungscode',
            'empty' => 'Bisher hast du noch keine Einladungen erstellt.',
            'code' => 'Code',
            'expiry' => 'Jeder Code funktioniert einmalig.',
            'status' => [
                'title' => 'Status',
                'pending' => 'Ausstehend',
                'accepted' => 'Akzeptiert'
            ],
            'add_invite' => [
                'button' => 'Hast du eine Einladung?',
                'title' => 'Einladungscode hinzufügen',
                'redeem' => 'Einladung einlösen',
            ],
            'share' => 'Sende deinem Freund einen Einladungslink'
        ],
        'emoji' => [
            'title' => 'SkinMC Emoji',
            'introducing' => 'Einführung von',
            'info' => 'Gestalte dein Profil mit Emoji. Schalte mehr frei, wenn du levelst.',
            'unlocked_at' => 'Freigeschaltet auf Level :level',
            'unlocks_at' => 'Erreiche Level :level zum entsperren',
            'turn_off' => 'Emoji anzeigen'
        ]
    ],
    'notifications' => [
        'title' => 'Benachrichtigungen',
        'view_all' => 'Alle anzeigen',
        'view_all_notifications' => 'Alle Benachrichtigungen anzeigen',
        'image' => 'Benachrichtigungs-Bild',
        'archived' => 'Archiviert',
        'inbox' => 'Posteingang',
        'empty' => [
            'title' => 'Du bist auf dem neusten Stand!',
            'text' => 'Neue Benachrichtigungen werden hier angezeigt.',
            'text-archived' => 'Archivierte Benachrichtigungen werden hier angezeigt.',
        ],
        'action' => [
            'archive' => 'Archivieren',
            'unarchive' => 'Wiederherstellen',
            'open' => 'Zum Öffnen tippen',
        ],
        'toast' => [
            'archive' => 'Benachrichtigung ins Archiv verschoben',
            'unarchive' => 'Benachrichtigung zum Posteingang verschoben',
            'undo' => 'Rückgängig',
        ]
    ],
    'error' => [
        'offline' => [
            'title' => 'Kein Internet',
            'subtitle' => 'Deine Internetverbindung wurde getrennt. Bitte überprüfe deine Verbindung und lade die Seite neu, um es erneut zu versuchen.',
            'try_again' => 'Erneut versuchen'
        ],
        '404' => [
            'title' => '404 — Seite nicht gefunden.',
            'subtitle' => 'Hm, es sieht so aus, als ob hier nichts gefunden wurde. Versuche es vielleicht zurück zu gehen oder starte eine neue Suche?',
            'try_again' => 'Zurück zur Startseite'
        ],
    ],
    'heads' => [
        'list' => [
            'meta' => [
                'title' => 'Minecraft Heads-Datenbank',
                'description' => 'Entdecke die Datenbank von Minecraft-Köpfen, um deine Welt zu dekorieren, oder generiere einen give command. Sehen Sie offizielle Köpfe, Spielerköpfe und benutzerdefinierte Köpfe mit Texturen, die sich nie ändern.'
            ],
            'header' => [
                'title' => 'Minecraft Köpfe',
                'subtitle' => 'Entdecke unsere Datenbank mit Minecraft-Köpfen, um deine Welt zu schmücken, oder generiere deinen eigenen give Befehl. Spielerköpfe zeigen den aktuellen Skin eines Benutzers an und können sich ändern, wenn der Benutzer seinen Skin aktualisiert. Benutzerdefinierte Köpfe sind mit der Mojang Skin Datei verbunden und ändern sich nicht. Benutzerdefinierte Köpfe müssen mit einem Befehlsblock geladen werden, da der Befehl sehr lang ist.',
            ],
            'count' => [
                'heads' => ':heads Kopf|:heads Köpfe',
            ],
            'customheads' => [
                'title' => 'Eigene Köpfe',
                'description' => 'Benutzerdefinierte Köpfe verwenden den direkten Pfad zur Texturdatei auf den Mojang-Servern. Daher werden Texturen nie gelöscht und die Köpfe bleiben unverändert.',
                'version' => 'Minecraft 1.8 oder höher',
            ],
            'playerheads' => [
                'title' => 'Spielerkopf',
                'description' => 'Spieler Köpfe verwenden die aktuelle Skintextur eines Minecraft-Spielers. Wenn der Spieler seinen Namen oder seine Haut ändert, ändert sich der Kopf.',
                'version' => 'Alle Minecraft-Versionen',
            ]
        ],
    ],
    'mod' => [
        'title' => 'SkinMC Mod: Kostenlose capes',
        'headline' => 'Einführung der SkinMC Mod für mehr Anpassung',
        'description' => 'Gibt der Minecraft-Community eine kostenlose Mod, die Spielern mehr Anpassungen mit benutzerdefinierten Capes ermöglicht, verfügbar und für jeden sichtbar, der die Mod benutzt.',
        'download' => 'Jetzt herunterladen',
        'download-title' => 'Mod herunterladen',
        'requires' => 'Erfordert',
        'select-version' => 'Wähle deine Minecraft-Version',
        'get-started' => 'Erste Schritte sind einfach',
        'step-1' => '1. Hol dir die Mod',
        'step-1-detail' => 'Installiere Fabric, lade dann die Mod für deine Spielversion herunter und installiere die Mod durch Einfügen der jar in deinen Mods Ordner.',
        'step-2' => '2. Profil verlinken',
        'step-2-detail' => 'Wenn du es noch nicht getan hast, melde dich an und verbinde dein Minecraft-Konto mit SkinMC.',
        'step-3' => '3. Lade dein Cape hoch',
        'step-3-detail' => 'Gehe zu deinem Account und lade dein eigenes Cape hoch. Es wird im Spiel sichtbar sein.',
        'all-versions' => 'Alle Versionen',
        'latest' => 'Neueste',
        'logged-in' => 'Lade dein Cape hoch',
        'mirror' => 'Mirror',
        'download-via' => 'Herunterladen über:',
        'curseforge' => 'CurseForge',
    ],
    'app' => [
        'title' => 'SkinMC Android App',
        'headline' => 'Sag hallo, zur SkinMC Android App.',
        'play-store-attribution' => 'Google Play und das Google Play Logo sind Markenzeichen der Google LLC.',
        'features' => 'Praktische Funktionen für unterwegs',
        'feature-qr' => 'Eingebauter QR-Code Scanner',
        'feature-qr-detail' => 'Verwenden den eingebauten QR-Code Scanner, um einfach einen Skin von deinem Desktop zur App zu bekommen, oder scanne den benutzerdefinierten QR-Code deines Freundes.',
        'feature-files' => 'Speichert direkt in Dateien',
        'feature-files-detail' => 'Mit der Verwendung von Android Files Manager, kann die App deine Skins bequem speichern, was es einfach macht sie in der Bedrock Edition anzuwenden.',
        'feature-noads' => 'Keine Werbung',
        'feature-noads-detail' => 'Eine saubere Oberfläche, ohne Ablenkungen. Genieße ein werbefreies Erlebnis ohne Störungen von Web zur App.',
        'feature-experience' => 'Erfahrung',
        'feature-experience-detail' => 'Genieße die volle SkinMC erfahrung überall mit hinzugefügten Funktionen. Passe dein Profil an, füge deine Biografie hinzu, erstelle einen lustigen QR-Code und mehr!',
        'get-app-headline' => 'Hole dir die SkinMC App',
        'get-app-detail' => 'Dein ganz eigener Minecraft-Begleiter für dein Android - konstenlos verfügbar.'
    ],
    'random' => [
        'title' => 'Lade einen zufälligen Minecraft-Skin',
        'description' => 'Lade einen zufälligen Minecraft-Skin',
        'headline' => 'Bitte warten...',
        'redirect' => 'Du wirst automatisch weitergeleitet. Seite wird nicht geladen?',
        'click-here' => 'Klicke hier',
        'messages' => [
            '1' => 'Lade einen zufälligen Minecraft-Skin...',
            '2' => 'Tiefer graben...',
            '3' => 'Creeper, aw man...',
            '4' => 'Truhen werden druchsucht...',
            '5' => 'Wusstest du, dass der kommende Skin völlig zufällig ist?',
            '6' => 'Zufälliger Skin kommt...',
            '7' => 'Nur noch ein Block dann hab ich\'s...',
            '8' => 'Inventar wird sortiert...',
            '9' => 'Diamantspitzhacke wird gecraftet...',
            '10' => 'Halte Ausschau nach Herobrine...',
        ],
    ],
    'feed' => [
        'title' => 'Feed',
        'following' => 'Gefolgt',
        'sign-up' => 'Registriere dich oder melde dich an, um an der Unterhaltung teilzunehmen.',
        'link-account' => 'Verbinde deinen Minecraft-Account, um an der Unterhaltung teilzunehmen.',
        'placeholder' => 'What is happening?',
        'audience' => 'Zielgruppe',
        'audience-title' => 'Wer kann das sehen?',
        'everyone' => 'Jeder',
        'everyone-info' => 'Jeder auf SkinMC.',
        'followers' => 'Follower',
        'followers-info' => 'Eingeloggte oder Mitglieder die mir folgen.',
        'private' => 'Nur ich',
        'private-info' => 'Privater Beitrag nur kann ich ihn sehen.',
        'submit' => 'Beitrag',
        'like' => 'Like',
        'comment' => 'Antwort',
        'share' => 'Teilen',
        'remaining' => 'Verbleibend',
        'profile' => 'Beiträge von :username',
        'posts' => 'Alle Beiträge',
        'my-posts' => 'Meine Beiträge',
        'view-all' => 'Alle Beiträge anzeigen',
        'post' => [
            'meta' => ':username auf SkinMC: :text',
            'title' => 'Beitrag',
            'created' => 'Status aktualisiert!',
            'confirm-delete' => 'Möchtest du den Beitrag wirklich löschen? Das kann nicht Rückgängig gemacht werden.',
            'delete' => 'Beitrag löschen',
            'deleted' => 'Dein Beitrag wurde gelöscht.',
        ],
        'follow-suggestions' => 'Folge dem Team',
        'explore' => 'Entdecken',
        'hashtag' => 'Hashtag',
    ],
    'private' => [
        'title' => 'Private Beiträge',
        'text' => 'Dieser Beitrag ist privat.'
    ] ,
    'liked' => [
        'title' => 'Gefällt mir'
    ],
    'following' => [
        'title' => 'Folgend',
        'text' => 'Melde dich an, um diesen Beitrag zu sehen.'
    ],
    'tags' => [
        'empty' => 'Noch keine Tags zum Abstimmen',
        'empty-subtitle' => 'Sei der Erste, der ein hinzufügt',
    ],
    'inbox' => [
        'title' => 'Nachrichten',
        'details' => 'Einzelheiten',
        'message_user' => 'Nachricht schreiben',
        'write_message' => 'Schreibe eine Nachricht',
        'empty' => [
            'no_message_selected' => 'Keine Nachricht ausgewählt',
            'open_or_start_conversation' => 'Öffne eine Unterhaltung aus der Nachrichtenliste oder starte eine neue.',
            'no_messages' => 'Keine ungelesenen Nachrichten',
            'start_conversation' => 'Sobald du eine neue Unterhaltung startest, werden deine Nachrichten hier angezeigt.',
            'conversation' => 'Dies ist der Anfang deiner Unterhaltung mit :username.',
            'users' => 'Es konnten keine Benutzer gefunden werden, die mit der aktuellen Abfrage übereinstimmen.'
        ],
        'typing' => ':username schreibt...',
        'new_message' => 'Neue Nachricht',
        'mark_unread' => 'Als ungelesen markieren',
        'send_message' => 'Nachricht senden',
        'delete_message' => 'Nachricht für dich löschen',
        'latest_conversations' => 'Neueste Unterhaltungen',
        'delete_conversation' => 'Unterhaltungen löschen',
        'show_details' => 'Einzelheiten anzeigen',
        'hide_details' => 'Einzelheiten ausblenden',
        'unread' => 'Ungelesen',
        'deleted' => 'Gelöscht',
        'report_message' => 'Nachricht melden',
        'add_reaction' => 'Reaktion hinzufügen',
        'today' => 'Heute',
        'reconnect' => 'Bitte verbinde dein Minecraft-Konto wieder, um zu chatten',
        'account_disconnected' => 'Dieser Nutzer hat sein verknüpftes Minecraft-Konto getrennt.',
        'saved_messages' => 'Gespeichert',
        'new_message_to_label' => 'An',
        'external-link-to' => 'Dieser Link bringt dich zu',
        'external-link-confirmation' => 'Bist du sicher, dass du dorthin gehen möchtest?',
        'external-link' => 'Externer Link',
        'reply' => 'Antworten'
    ],
    'server' => [
        'manage' => [
            'stats' => 'Statistiken'
        ]
    ],
    'report' => [
        'button' => 'Melden',
        'title' => 'Inhalt melden',
        'describe' => 'Beschreibe kurz, warum du diese Meldung machst',
        'select' => 'Grund auswählen',
        'submit' => 'Meldung senden',
        'reasons' => [
            'INAPPROPRIATE_CONTENT' => 'Unangemessener Inhalt',
            'SPAM' => 'Unerwünschte Werbung',
            'HARASSMENT' => 'Belästigung',
            'OTHER' => 'Sonstiges',
        ]
    ],
    'leaderboard' => [
        'title' => 'Rangliste',
        'description' => 'Sieh dir die SkinMC-Rangliste der Nutzer an.',
        'headline' => 'Top 10',
        'all-time-invites' => 'Einladungen aller Zeiten',
        'all-time-xp' => 'Gesamt XP',
        '30-day-xp' => '30 Tage XP'
    ],
];
