files:
  - source: /en/*.php
    translation: /%two_letters_code%/%original_file_name%
  - source: /vendor/eu-cookie-consent/en/*.php
    translation: /vendor/eu-cookie-consent/%two_letters_code%/%original_file_name%
