files:
  - source: /en/*.php
    translation: /%two_letters_code%/%original_file_name%
    languages_mapping:
      two_letters_code:
        sv: sv-SE
        es: es-ES
  - source: /vendor/eu-cookie-consent/en/*.php
    translation: /vendor/eu-cookie-consent/%two_letters_code%/%original_file_name%
    languages_mapping:
      two_letters_code:
        sv: sv-SE
        es: es-ES
