<?php

return [
    'login' => [
        'title' => 'Logg inn',
        'email' => 'Epost adresse',
        'password' => 'Passord',
        'button' => 'Logg inn',
        'editor_save_context' => "Log in to save your skin to the gallery. Your work won\\'t be lost.",
        'forgot' => 'Glemt passord?',
        'reset' => 'Reset',
        'register' => 'Har du ikke en konto ennå?',
        'signup' => 'Registrer deg',
        'google' => 'Fortsett med Google',
        'microsoft' => 'Continue with Microsoft',
        'facebook' => 'Fortsett med Facebook',
        'twitter' => 'Fortsett med Twitter',
        'divider' => 'or',
    ],
    'signup' => [
        'title' => 'Registrer deg',
        'existing' => 'Har du allerede en konto?',
        'button' => 'Agree and continue',
        'terms_by_selecting' => 'By selecting',
        'terms_agree_to' => ', I agree to SkinMC\'s',
        'terms_acknowledge' => 'and acknowledge the',
    ],
    'recover' => [
        'title' => 'Gjenopprett konto',
        'description' => 'Glemt passordet? Gjenopprett det ved å skrive inn din e-postadresse for å få det tilbake.',
        'button' => 'Send gjenopprettingse-post',
        'found' => 'Funnet ditt passord?',
    ],
    'logout' => [
        'title' => 'Log out',
        'description' => 'Are you sure you would like to log out of your SkinMC account?',
        'logout' => 'Log out',
        'cancel' => 'Cancel',
    ],
    'profile_qrcode' => [
        'title' => 'Scan QR code',
        'done' => 'Ferdig',
    ],
    'language' => [
        'title' => 'Språk',
        'description' => 'Velg språket ditt',
        'contribute' => 'Bidra',
        'contribute_add' => 'Legg til oversettelse',
        'updated' => 'Your language has been set',
    ],
    'copied' => 'Copied to clipboard!',
    'close' => 'Close',
    'feedback' => [
        'title' => 'Feedback',
        'type' => [
            'select' => 'Select feedback type',
            'label' => 'Feedback type',
            'comment' => 'Comments',
            'question' => 'Questions',
            'bug' => 'Bug report',
            'feature' => 'Feature request',
        ],
        'submit' => 'Submit',
        'nps' => 'On a scale from 0 to 10 how likely would you recommend SkinMC to a friend?',
        'success' => [
            'title' => 'Thank you!',
            'message' => 'Your message has been sent, expect a reply soon! For further questions, feel free join the Discord or submit another message.',
        ],
    ],
];
