<?php

return [
    'skins' => 'Stiler',
    'avatars' => 'Avatarer',
    'editor' => 'Redaktør',
    'heads' => 'Heads',
    'capes' => 'Kapper',
    'servers' => 'Servere',
    'achievement' => 'Prestasjon',
    'armor' => 'Armor stand',
    'banners' => 'Banners',
    'banner' => 'Banner Editor',
    'profile' => 'My profile',

    'generators' => 'Generators',

    // Navigation dropdowns
    'feed' => 'Feed',
    'discover' => 'Discover',
    'mods' => 'Mods',
    'shaders' => 'Shaders',
    'resource_packs' => 'Resource Packs',
    'modpacks' => 'Modpacks',
    'datapacks' => 'Data Packs',
    'plugins' => 'Plugins',

    'logout' => 'Logg ut',
    'register' => 'Registrer deg',
    'login' => 'Logg inn',
    'about' => 'Om',
    'contact' => 'Contact',
    'faqs' => 'OSS\'er',

    'minecraft_name' => 'Minecraft Navn',
    'minecraft_uuid' => 'Minecraft UUID',
    'what' => 'What',
    'recent_searches' => 'Nylige søk',
    'username' => 'Username',
    'uuid' => 'UUID',
    'search' => 'Søk',
    'search_placeholder' => 'Forsøk',
    'search_placeholder_uuid' => 'Enter UUID',
    'start_search' => 'Begynn å søke',
    'cancel_search' => 'Avbryt',
    'search_type' => 'Søk i typer',
    'search_type_all' => 'All results',
    'profiles' => 'Profiles',
    'view_skin' => 'Vis skinn',
    'edit_skin' => 'Rediger stil',
    'make_avatar' => 'Lag avatar',
    'find_heads' => 'Find player heads',
    'no_results_found' => 'No suggestions yet. Hit Enter to look it up.',

    'home' => 'Hjem',
    'help' => 'Hjelp',
    'tools' => 'Verktøy',
    'more-tools' => 'More tools',
    'skin_viewer' => 'Skin seer',
    'avatar_maker' => 'Profilbilde maker',
    'collections' => 'Samlinger',
    'popular_skins' => 'Populære skins',
    'cartoon_skins' => 'Tegneserie hud',
    'animal_skins' => 'Dyrehud',
    'community' => 'Fellesskap',
    'imprint' => 'Avtrykk',
    'cookies' => 'Informasjonskapsler',
    'terms' => 'Terms of Service',
    'privacy' => 'Privacy policy',
    'app' => 'App',
    'mod' => 'Mod',
    'totem' => 'Totems',
    'cube' => 'Cube',
    'new' => 'New',

    'feedback' => 'Feedback',
    'status' => 'Status',
    'recent_searches_placeholder' => 'As you start searching, your past searches will show here.',
    'recent_views_placeholder' => 'After visiting some profiles, your past visited ones will show here.',
    'moderate' => 'Moderate',
    'listings' => 'Listings',
    'add' => 'Add',

    // Autocomplete types
    'autocomplete' => [
        'profile' => 'Profile',
        'server' => 'Server',
        'project' => 'Project',
        'skin_tag' => 'Skin Tag',
        'server_category' => 'Server Category',
        'modrinth_category' => 'Project Category',
    ],

    'theme' => [
        'title' => 'Theme',
        'dark' => 'Dark',
        'light' => 'Light',
        'auto' => 'Auto',
    ],

    'language' => 'Language',
];
