<?php

return [
    'auth' => [
        'login' => [
            'title' => 'Welcome to SkinMC',
        ],
        'register' => [
            'title' => 'Sign up to SkinMC',
            'subtitle' => 'Get started and create your account for full access.'
        ]
    ],

    'home' => [
        'hero_slogan' => 'Ditt sted for Minecraft Skins.',
        'hero_cta' => 'Overraskelse meg',
        'hero_explore_cta' => 'Explore skins',
        'skin_viewer' => 'Tema Bruker',
        'skin_viewer_detail' => 'Bla gjennom :count stiler',
        'skin_editor' => 'Skin editor',
        'skin_editor_detail' => 'Design din egen hud',
        'avatar_maker' => 'Avatar generator',
        'avatar_maker_detail' => 'Generate your custom Minecraft avatar profile pictures.',
        'trending' => 'Populært',
        'minecraft_skin' => 'Minecraft skin',
        'favourite' => 'Favoritt',
        'collections' => 'Samlinger',
        'collections_detail' => 'Curated Minecraft Skins for hver anledning',
        'about_skinmc' => 'Om SkinMC',
        'about_find' => 'Finn skall',
        'about_find_detail' => 'Bruk SkinMC søket etter hvilken som helst Minecraft Brukernavn for å finne, vise og laste ned ditt neste nye skall.',
        'about_download' => 'Last ned eller rediger',
        'about_download_detail' => 'Funnet et skin du liker? Legg det til til favorittene dine, rediger eller last ned og gjør det til ditt eget.',
        'about_platform' => 'Kryssplattform',
        'about_platform_detail' => 'Vil du ta huden på farten? Skann QR-koden og lagre bildet på telefonen for Minecraft PE.',
        'meta' => [
            'title' => 'Minecraft Stilsett',
            'description' => 'Se og last ned Minecraft-skall, oppdag de beste skallene for markerte samlinger, sjekk brukernavnetilgjengelighet og historie så mye mer!',
        ],
        'recently_viewed' => 'Recently viewed',
        'explore_title' => 'Try something new',
        'explore' => 'Explore new ideas and tools',
        'servers_browse' => 'Browse servers',
        'servers' => 'Discover the best Minecraft Servers',
        'heads' => 'Minecraft heads',
        'head_description' => 'Browse the Minecraft heads database, or create new ones.',
        'achievement' => 'Achievement generator',
        'achievement_detail' => 'Create your own, custom and personalised achievements.',
        'continue' => 'Continue browsing'
    ],
    'profile' => [
        'verified' => 'Verified profile',
        'minecraft_profile' => 'Minecraft profil',
        'show_qr_code' => 'Show QR code',
        'favourite' => 'Favoritt',
        'user_title' => ':username Minecraft Skinn',
        'user_views' => 'Sett :views tid vist :views tid',
        'uuid' => 'UUID',
        'copy' => 'Kopier',
        'link' => 'Lenke',
        'skin_history' => 'Minecraft skin history (:skins)',
        'username_history' => 'Username history',
        'username_history_name' => 'Navn',
        'username_history_timestamp' => 'Endret kl.',
        'username_history_initial_name' => 'Første navn',
        'user_downloads' => ':downloads downloadnorden.org:downloads downloads',
        'download_skin' => 'Last ned skinet',
        'apply_skin' => 'Apply skin',
        'capes' => 'Capes',
        'claim_profile' => 'Er du :username? Krev profilen din for å bekrefte og tilpasse den!',
        'claimed' => 'Claimed profile',
        'meta_description' => 'View and download :username Minecraft Skin. See their UUID, name history, detailed stats, and more',
        'created_at' => 'Updated: :changed_at',
        'skins' => [
            'meta_title' => ':username Minecraft Skin History',
            'meta_description' => 'View :username Minecraft Skins history and previously used Skins. Use the history to browse through old or past used skins, backup and rollback or collect new skins.',
            'title' => 'Minecraft Skin history'
        ],
        'qr_code' => [
            'meta_title' => ':username\'s QR Code',
            'meta_description' => ':username Custom Minecraft Profile QR Code'
        ],
        'sub_nav' => [
            'skin' => 'Skin',
            'about' => 'About',
            'usernames' => 'Usernames',
            'head' => 'Head',
            'comments' => 'Comments'
        ],
        'cape' => 'Cape',
        'elytra' => 'Elytra',
        'nametag' => 'Name tag',
        'animation' => 'Animation',
        'rotation' => 'Rotation',
        'none' => 'None',
        'idle' => 'Idle',
        'walk' => 'Walk',
        'run' => 'Run',
        'fly' => 'Fly',
        'follow' => 'Follow',
        'following' => 'Following',
        'unfollow' => 'Unfollow',
        'followers' => 'Follower|Followers',
        'toast' => [
            'following' => 'You are now following :username!',
            'follow-self-error' => 'Sorry :username, you can\'t follow yourself.',
            'unfollowed' => 'You have unfollowed :username'
        ],
        'edit' => 'Edit profile',
        'joined' => 'Joined',
        'server-fav-list-empty' => 'Looks like :username hasn\'t got any favourite servers yet. Once :username has saved a server as their favourite, you can see it here.',
        'server-own-list-empty' => 'Looks like :username hasn\'t got any servers yet. Once :username has listed a server, you can see it here.',
        'capes-list-empty' => 'Looks like :username isn\'t wearing any capes yet. Once :username is wearing a cape, you can see it here.',
        'feed-own-list-empty' => 'Looks like you haven\'t posted anything to the feed yet! Once you post, you can see your posts here.',
        'feed-list-empty' => 'Hmm, it seems like :username hasn\'t posted anything to the feed yet. Once :username posts something you can see it here.',
        'following-own-list-empty' => 'Looks like you are not following anyone yet! Once you start to follow people, you can see them here.',
        'following-list-empty' => 'Hmm, it seems like :username is not following anyone. Once :username start following people you can see them here.',
        'followers-own-list-empty' => 'Once people start to follow your profile, they will show up here.',
        'followers-list-empty' => 'Hmm, it seems like :username is not being followed by anyone one. Be the first to follow :username. Once more people follow, you can see them here.',
        'render' => 'Renderer',
        '3d' => '3D render',
        '2d' => '2D render',
        'name-history-info' => 'Username History is going away. Mojang has removed support for accessing the name history API on September 13th 2022, resulting in an accurate name history not being available anymore. If you wish to hide your name history, claim your profile and go to settings to make it private.',
        'edit-skins' => 'Edit skin history',
        'hide-skin' => 'Hide skin',
        'show-skin' => 'Show skin',
        'edit-skin' => 'Edit skin',
        'servers' => [
            'title' => ':username\'s servers',
        ],
        'cape-list' => [
            'title' => ':username\'s capes',
        ]
    ],
    'skin' => [
        'meta' => [
            'title' => ':username Minecraft Skin',
            'description' => 'Minecraft Skin. Download and view the skin, and see which players are also wearing the same skin.',
            'tags' => ':username Minecraft Skin, :username Skin, Minecraft Skin, :username Custom Minecraft Skin, Download Skin, Players with the same skin',
        ],
        'title' => ':username Minecraft Skin',
        'head' => 'Head commands',
        'head_info' => 'To use with command blocks',
        'first_wearing' => 'First player seen wearing this skin:',
        'profiles' => ':profiles profile|:profiles profiles',
        'profiles_title' => ':profiles profile with this skin|:profiles profiles with this skin'
    ],
    'skins' => [
        'meta' => [
            'title' => 'Page :current — All Minecraft Skins',
            'description' => 'Browse through our :last pages list of :total custom Minecraft skins and download your favourite next skin!',
            'tags' => ':username Minecraft Skin, :username Skin, Minecraft Skin, :username Custom Minecraft Skin, Download Skin, Players with the same skin',
            'tags-title' => ':tag Minecraft Skins',
            'tags-description' => 'Browse through our :last pages list of :total :tag Minecraft skins and download your favourite :tag skin!',
            'tags-metatags' => ':tag Minecraft Skin, :tag Skin, Minecraft Skin, :tag Custom Minecraft Skin, Download :tag Skin, Minecraft :tag Skins',
        ],
        'title-skin-tags' => 'Tagged Minecraft Skins',
        'subtitle' => 'Page :current of :last from :total Minecraft Skins',
        'subtitle-skin-tags' => 'Page :current of :last from :total Tagged Minecraft Skins',
        'sort_by' => 'Sort by',
        'latest' => 'Latest skins',
        'most_profiles' => 'Most used skins',
        'profiles_today' => 'Most used today',
        'profiles_this_week' => 'Most used this week',
        'profiles_this_month' => 'Most used this month',
        'default' => 'Default sorting',
        'this_month' => 'Added this month',
        'this_week' => 'Added this week',
        'today' => 'Added today',
        'random' => 'Random',
        'similar' => 'Similar skins',
        'no_similar_skins' => 'No similar skins found yet.',
        'favorite' => ':count favourite|:count favourites',
    ],
    'skin-tags' => [
        'faq' => 'What are tags?',
        'about' => 'Tags are a way you to add relevant categories to skins. Adding tags allows you to discover more skins you like easily!',
        'guidelines' => [
            'good' => [
                'title' => 'General guidelines for good tags are:',
                'short' => 'Short',
                'descriptive' => 'Descriptive',
                'spelled' => 'Spelled correctly',
            ],
            'bad' => [
                'title' => 'Do not add tags such as:',
                'general' => 'Too general',
                'specific' =>  'Too specific',
                'too-many-tags' =>  'Should be three separate tags',
                'spelling' => 'Should be :example',
            ],
        ],
        'toast' => [
            'added' => 'Tag ”:tag” added for voting',
            'removed' => 'Tag ”:tag” has been removed',
            'upvote' => 'Upvoted ”:tag”',
            'downvote' => 'Downvoted ”:tag”'
        ],
        'vote' => [
            'up' => 'Upvote',
            'down' => 'Downvote',
            'remove' => 'Remove vote',
        ],
    ],
    'contact' => [
        'contact' => 'Contact',
        'email' => 'Please feel free to write us at <a href="mailto:support@skinmc.net">support@skinmc.net</a> for any questions you have.',
        'faq' => 'We kindly ask to first check out the <a href=":link">FAQ page</a> if your question is already answered there.',
        'other' => 'Other ways to connect',
        'other_discord' => 'Join the Discord server and connect with others, chat about games, share your favourite packs and get help from the community.',
        'other_twitter' => 'Follow on Twitter to see when a new update or feature is released, see the skin of the week and more.',
        'other_instagram' => 'Follow SkinMC on Instagram to browse and discover cool new featured Minecraft Skins and images.',
        'other_facebook' => 'Become a fan on Facebook and see all posts where you can comment and talk to others while exploring Minecraft content.'
    ],
    'about' => [
        'intro' => '<span>Din</span> <span>plattform</span> <span>for</span> <span>Minecraft</span> <span>Skall.</span>',
        'header_credit' => 'Illustrasjon "Epic Nether Battle" av',
        'info' => 'Hold oversikt over alt.',
        'info_explainer' => 'Vis en navnehistorie, se deres tidligere skall, legg dem til som en venn, nedlastingsskall og til og med skaffe detaljert statistikk.',
        'card_find_title' => 'Finn en minecrafter',
        'card_find_detail' => 'Kom i gang ved å søke etter spillernavn eller UUID av ditt valg.',
        'card_view_title' => 'Vis, lagre og rediger',
        'card_view_detail' => 'Funnet et skin du liker? Lagre det ved å laste ned eller bruke redigeringsprogrammet for å gjøre det selv.',
        'card_claim_title' => 'Bli bekreftet',
        'card_claim_detail' => 'Koble opp Minecraftkontoen din og få profilen din til å låse opp kule, nye funksjoner!',
        'card_customise_title' => 'Tilpass profilen din',
        'card_customise_detail' => 'Bekrefte spillere kan legge til sine sosiale medienker og gjøre sin profil egen profil.',
        'card_friends_title' => 'Legg til dine venner',
        'card_friends_detail' => 'Koble til vennene dine på SkinMC og vis vennelisten din på profilen.',
        'card_history_title' => 'Brukernavn & skallhistorikk',
        'card_history_detail' => 'Bruk det avanserte søket for å finne og se brukernavn/skin loggen til en spiller.',
        'founders' => 'The founders',
        'founders_cofounder' => 'Cofounder of SkinMC',
        'head_of_design' => 'Head of design',
        'head_of_code' => 'Head of code',
        'feedback' => 'Send us feedback',
        'faq' => 'Questions about Minecraft, Skins, and more? Read our FAQs with answers to most frequently asked questions.',
        'faq_link' => 'Visit FAQ center',
        'contact' => 'Do you want to reach out or have further questions? Contact us directly.',
        'contact_link' => 'Contact us',

    ],
    'faq' => [
        'title' => 'OSS\'er',
        'subtitle' => 'Ofte stilte spørsmål',
        'help' => 'Trenger du mer hjelp?',
        'discord' => 'Bli med på Discord-serveren for å chatte med andre Minecraft-spillere.',
        'contact' => 'Contact us',
        'q' => [
            'change_skin_t' => 'Hvordan endrer jeg Minecraft skallet?',
            'change_skin' => '
                <p>Slik endrer du utseendet ditt:</p>
                <ol>
                    <li>Besøk <a href="https://my.minecraft.net/en-us/login/">https://my. inecraft.net/en-us/login/</a> og logg inn med din Mojang-konto.</li><li>Når du er innlogget, velg <b>"Skinn"</b> på venstre meny.</li><li>Deretter, velg en modell du foretrekker og laster opp et skinn til ditt ønske.</li>
                </ol>',
            'change_username_t' => 'Hvordan endrer jeg mitt Minecraft brukernavn?',
            'change_username' => '
                <p>For å endre ditt brukernavn gjør følgende:</p>
                <ol>
                    <li>Besøk <a href="https://account.mojang.com/login" target="_blank" rel="nofollow">https://account. ojang.com/login</a> og logg inn med din Mojang-konto.</li>
                    <li>Finn din Minecraft Profilnavn og trykk på <b>"(Endre)"</b> knappen</li>
                    <li>På neste side Skriv inn ønsket nytt brukernavn.</li>
                    <li>Til slutt, bekreft endringene ved å skrive inn passordet ditt og trykke på "Endre navn".</li>
                </ol>',
            'dl_t' => 'Hvordan laster jeg ned noen Minecraft Skin?',
            'dl' => '
                <p>For å laste ned noe Minecraft Skin gjør du følgende:</p>
                <ol>
                    <li>Trykk på søkefeltet og skriv inn det brukernavnet til spilleren du vil laste ned skinet fra.</li>
                    <li>På profilsiden kan du forhåndsvise huden</li>
                    <li>Klikk på <strong>Last ned Skin</strong> under forhåndsvisningen</li>
                </ol>',
            'submit_q' => 'How do I submit a skin to a collection?',
            'submit_a' => '<p>Please fill out the following short form with the usernames and their category of which you would like to add to the collections. <a href="https://forms.gle/f4Jh5RpGfsHAZ5xE8" target="_blank">Collection submission form</a>',
            'mcpe_t' => 'Kan jeg bruke huden på Minecraft PE?',
            'mcpe' => '
                <p>Ja. Slik bruker du Skallet i Minecraft Pocket Edition følgende:</p>
                <ol>
                    <li>Åpne SkinMC. et på din smarttelefon og trykk på søkefeltet</li>
                    <li>Skriv inn brukernavnet til spillerens skinn som du ønsker å laste ned</li>
                    <li>Trykk på <strong>Last ned utseendet</strong> knappen under forhåndsvisningen </li>
                    <li>Åpne Minecraft PE og trykk på <strong>Profil</strong> på høyre side</li>
                    <li>Trykk på <strong>+</strong>, eller redigere tegnet og gå til fanen "klassiske utseende"</li>
                    <li>Trykk på "owned", deretter "importer", deretter "velg nytt skin"</li>
                </ol>',
            'change_times_t' => 'Hvor ofte kan jeg endre brukernavnet mitt?',
            'change_times' => '<p>Du kan endre ditt Minecraft Brukernavn <strong>én gang</strong> hver <strong>30 dager</strong>.</p>',
            'available_t' => 'Etter at jeg har forandret mitt brukernavn, når blir det tilgjengelig for andre for å få det?',
            'available' => '<p>Hvis du vil endre tilbake til ditt forrige brukernavn, kan du endre tilbake <strong>etter 30 dager.</strong> Alle andre må vente ytterligere <strong>7 dager</strong> (37 dager etter endring) før de kan kreve det gamle brukernavnet ditt. </p>',
            'username_history_t' => 'Kan du fjerne loggen min på brukernavnet mitt?',
            'username_history' => '
                <p>Siden brukernavnet historikk kommer fra Mojang, brukernavnet historikk kan ikke fjernes. Mojang har tidligere uttalt at de ønsker at tidligere kan ses på brukernavn1, og at de framskaffer en direkte metode for publikum for å få tilgang til denne informasjonen2.</p>
                <p class="font-14">1<a href="https://help.minecraft.net/hc/en-us/articles/360034636712-Minecraft-Usernames" target="_blank" rel="noreferrer">https://help. informasjonskraft. et/hc/nb-no/artikler/360034636712-Minecraft-Brukernavn</a></p>
                <p class="font-14 mb-0">2<a href="https://twitter.com/dinnerbone/status/554739042529849345" target="_blank" rel="noreferrer">https://twitter. om/dinnerbone/status/554739042529849345</a> (Tweet arkivert 2 år siden: <a href="http://archive.is/TeAyj" target="_blank" rel="noreferrer">http://archive. s/TeAyj</a>)
                </p>',
        ],
    ],
    'avatars' => [
        'start' => [
            'title' => 'Lag din egen Minecraft avatar',
            'subtitle' => 'Bruk Minecraft avatar generator for å lage en morsom avatar fra hvilket som helst skall!',
            'avatar_face' => 'Ansikt stil avatar',
            'avatar_bust' => 'Ruststil avatar',
            'avatar_cube' => 'Kube-stil avatar',
            'avatar_head3d' => 'Custom 3D head',
        ],
        'user' => [
            'title' => 'Velg skinn',
            'subtitle' => 'Skriv inn Minecraft-brukernavnet for avataren du ønsker å generere',
            'form_label' => 'Minecraft brukernavn',
            'form_submit' => 'Fortsett',
        ],
        'output' => [
            'title' => 'Forhåndsvisning og lagre',
            'subtitle' => 'Nyt å bruke din nye Minecraft avatar',
            'download_info' => 'Fornøyd med resultatet? Start med å bruke din nye avatar ved å laste den ned her',
            'download_button' => 'Last ned avatar',
            'avatar_style' => 'Avatar stil',
            'skin_username' => 'Skin brukernavn',
            'change' => 'Endre',
            'generate' => 'Generer',
            'avatar_colour' => 'Bakgrunnsfarge',
            'avatar_colour_palette' => 'Palette',
            'avatar_colour_basic' => 'Grunnleggende',
        ],
        'meta' => [
            'title' => 'Minecraft Avatar Generator',
            'description' => 'Minecraft Avatar Maker: opprett egendefinerte Minecraft-profilbilder ved å bruke Minecraft-skallet ditt',
        ],
    ],
    'totem' => [
        'title' => 'Custom Minecraft Totem',
        'subtitle' => 'Use the Minecraft Totem generator to create a custom resource pack with a Totem of Undying from any skin.',
        'download_info' => 'Happy with the preview? Choose your Minecraft version to save your custom resource pack:',
        'meta' => [
            'title' => 'Minecraft Custom Totem Generator',
            'description' => 'Custom Minecraft Totems: generate and create a custom Minecraft Resource Pack with a Totem of Undying using your or any other players Minecraft skin.',
        ],
        'type' => [
            'mini' => 'A mini version of your skin!',
            'full' => 'A full version of your skin!',
            'model3d' => 'A 3d model of your skin!',
            'add_designs' => 'Want to see more designs? Submit your design suggestion here:'
        ]
    ],
    'achievement' => [
        'header' => [
            'title' => 'Lag din egen Minecraft Prestasjon',
            'subtitle' => 'Bruk Minecraft Prestasjon Generator for å lage din egen prestasjon, og vis din utvikling i hva som helst du liker!',
        ],
        'generator' => [
            'yellow_text' => 'Gul tekst',
            'white_text' => 'Hvit tekst',
            'choose_icon' => 'Velg ikon',
            'face' => 'Minecraft-ansikt i stedet for ikon',
            'form_submit' => 'Nedlasting',
            'form_label' => 'Minecraft brukernavn',
            'download' => 'Nedlasting',
            'embed' => 'Integrer',
            'embed_copy' => 'Kopier',
        ],
        'meta' => [
            'title' => 'Minecraft Prestasjon Generator',
            'description' => 'Generer egendefinerte Minecraft-prestasjoner og -utviklere med skaperen av prestasjonen. Last ned bildet direkte, bruk det i forumsignaturer, innebygd med HTML eller BB-kode, og mer',
        ],
    ],
    'armor' => [
        'header' => [
            'title' => 'Minecraft Armor Stand Creator',
            'subtitle' => 'Generate and create your very own custom Minecraft Armor Stands. Create different poses, positions, place items, and much more.',
        ],
        'meta' => [
            'title' => 'Minecraft Armor Stand Creator',
            'description' => 'Easily generate and create custom Minecraft Armor Stands. The editor helps you make different poses, positions, place items, custom skins, and much more.',
        ],
    ],
    'banner' => [
        'editor' => [
            'header' => [
                'title' => 'Minecraft Banner Editor',
                'subtitle' => 'Design and create your very own custom Minecraft Banners. These can be used to decorate your world or also commonly seen used as <a href="https://optifine.net" target="_blank" rel="nofollow">Optifine</a> capes.',
            ],
            'meta' => [
                'title' => 'Minecraft Banner Creator',
                'description' => 'Create and design your very own custom Minecraft Banners designs with all the patterns and colors from the game! These can be used to decorate your world or be worn as an Optifine Cape using the Banner Cape. You can generate give codes for banners or shields.',
            ],
        ],
        'gallery' => [
            'header' => [
                'title' => 'Minecraft Banner Gallery',
                'subtitle' => 'Browse the gallery of :count custom designed Minecraft Banners. You can use a Banner as a cape to make your Minecraft skin more unique, or use a Banner as a flag to decorate your world.',
            ],
            'meta' => [
                'title' => 'Minecraft Banner Gallery',
                'description' => 'Browse the gallery of :count custom designed Minecraft Banners. You can use a Banner as a cape to make your Minecraft skin more unique, or use a Banner as a flag to decorate your world.',
            ],
        ],
    ],
    'search' => [
        'meta' => [
            'title' => 'Search results: :search',
        ],
        'title' => 'Søk i resultater',
        'results' => 'Page :current for :count result|Page :current of about :count results ',
        'time' => '(:time seconds)',
        'username_available' => 'Brukernavn tilgjengelig*',
        'username_unavailable' => 'Brukernavnet er ikke tilgjengelig',
        'username_status' => 'Status:',
        'username_status_available' => 'Tilgjengelig*',
        'username_status_unavailable' => 'Unavailable',
        'username_searches' => 'Søk',
        'username_searches_count' => ':count / dag',
        'username_available_disclaimer' => '*Med mindre navnet er midlertidig eller permanent utestengt av Mojang.',
        'no_results' => 'No profiles found. Try searching with UUID by changing the search type.',
        'no_results_tags' => 'No tagged skins found. Try searching for other tags such as "blue", "girl", "fox", etc...',
        'again' => 'Search again',
        'sorry' => 'Sssssssorry...',
        'view_profile' => 'View profile',
    ],
    'collection' => [
        'title' => 'Minecraft skallsamling',
        'subtitle' => 'Bla gjennom gjennom den kurerte samlingen av Minecraft-skinn.',
        'filters' => 'Filtre',
        'title_trending' => 'Populært',
        'title_all' => 'Alle Minecraft-skall',
        'skin_tags' => 'Tagged Skins',
        'filters_skin_type' => 'Type hud',
        'filter_skin_type_steve' => 'Steve type',
        'filter_skin_type_alex' => 'Alex type',
        'cancel' => 'Avbryt',
        'apply' => 'Bruk',
        'username_minecraft_skin' => ':username sitt Minecraftskinn',
        'user_downloads' => '<span class="fw-500">:downloads</span> download<span class="fw-500">:downloads</span> downloads',
    ],
    'favourites' => [
        'title' => 'Favoritter',
        'subtitle' => 'Vis og behandle utseender du har lagret senere i listen over favoritter',
        'sort' => 'Sort by',
        'toast' => [
            'added' => 'Added to your favourites list',
            'removed' => 'Removed from your favourites list'
        ],
        'skins' => [
            'button' => 'Skins',
            'empty_headline' => 'No favourite skins yet',
            'empty_subtitle' => 'You do not have any skins saved to your favourites list yet. Visit the server page and discover your next favourite!',
            'empty_browse' => 'Browse skins',
            'meta' => [
                'title' => 'My favourite skins',
                'description' => 'My favourite saved Minecraft skins',
            ],
        ],
        'servers' => [
            'button' => 'Servers',
            'empty_headline' => 'No favourite servers yet',
            'empty_subtitle' => 'You do not have any servers saved to your favourites list yet. Visit the server page and discover your next favourite!',
            'empty_browse' => 'Browse servers',
            'meta' => [
                'title' => 'My favourite servers',
                'description' => 'My favourite Minecraft servers',
             ],
        ],

    ],
    'cape' => [
        'editor' => [
            'title' => 'Minecraft cape editor',
            'subtitle' => 'Use the Minecraft cape editor to create your very own custom designed cape.',
            'meta' => [
                'title' => 'Minecraft Cape Editor',
                'description' => 'Use the Minecraft Cape Editor to create your very own custom designed cape.',
            ],
        ],
        'list' => [
            'title' => 'Minecraft capes',
            'subtitle' => 'Offisielle bildetekster på Minecraft',
            'meta' => [
                'title' => 'Liste over Minecraft Capes',
                'description' => 'Minecraft cape list: View all official Minecraft capes including Mojang, Minecon, Personal, Special and vanity capes',
            ],
        ],
        'detail' => [
            'title' => ':cape kappe',
            'info' => 'Cape information',
            'profile_list' => 'Profiler med denne kappe',
            'profiles' => ':profiles profile|:profiles profiles',
            'meta' => [
                'title' => 'Liste over Minecraft Capes',
                'description' => 'Minecraft cape liste: Vis alle offisielle Minecraft-kapper som Mojang, Minekon, Personell, Hastighets- og vanelighetsklokker',
            ],
        ],
        'list-custom' => [
            'title' => 'Custom Minecraft Capes',
            'description' => 'Browse and view custom capes which have been created and are used by SkinMC members.'
        ]
    ],
    'servers' => [
        'title' => 'Minecraft servere',
        'subtitle' => 'Bla gjennom og utforske minecraft servere',
        'all' => 'All servers',
        'manage_your_servers' => 'Manage your servers',
        'add_new_server' => 'Add new server',
        'filters' => [
            'trending' => 'Populært',
            'updated' => 'Oppdatert',
            'new' => 'Ny',
            'most_viewed' => 'Mest sett',
            'top_voted' => 'Beste stemte',
            'sorting' => 'Sorting',
            'sort_by_latest' => 'Sort by latest',
            'sort_by_oldest' => 'Sort by oldest',
            'categories' => 'Categories',
            'server_location' => 'Server location',
            'show_results' => 'Show results',
            'show_more' => 'Show more',
            'show_less' => 'Show less',
            'clear_filters' => 'Clear filters',
            'reviews' => 'Reviews',
            'sort_by_highest_rating' => 'Sort by highest rating',
            'sort_by_lowest_rating' => 'Sort by lowest rating',
            'bedrock_and_java_support' => 'Bedrock and Java support'
        ],
        'review-count' => ':count Review|:count Reviews',
        'meta' => [
            'title' => 'Minecraft serverliste',
            'description' => 'Bla gjennom og utforske Minecraftserverlisten for å finne den beste Minecraft-serveren! Filtrer de siste, mest populære og mye mer',
        ],
        'reviews' => [
            'meta' => [
                'title' => 'Write a review',
            ],
            'editing' => 'You\'re editing your review from :date. Would you like to delete your review instead?',
            'welcome' => 'Hi :username. How was your overall experience with :servername?',
            'subtitle' => 'Leave an overall score of your past experience with the server.',
            'scale' => [
                'great' => 'Great',
                'good' => 'Good',
                'okay' => 'Okay',
                'meh' => 'Meh',
                'bad' => 'Bad',
            ],
            'rate-experience' => 'Next, rate your experience in these areas',
            'overall' => 'Overall',
            'server-team' => 'Server team',
            'community' => 'Community',
            'experience' => 'Experience',
            'availablility' => 'Uptime and availability',
            'shop' => 'Shop',
            'write-review-title' => 'Write a review',
            'write-review-subtitle' => 'Leave a few notes, you can highlight what you enjoyed, what made your experience special, or offer a few suggestions.',
            'write-review-helper' => 'Write a server review to share your experience with new players, and help the server owners with feedback.',
            'write-review-tips' => 'Here are some tips',
            'submit-title' => 'Ready to submit your review?',
            'submit-subtitle' => 'Almost done!',
            'submit-review' => 'Submit my review',
            'back' => 'Back',
            'continue' => 'Continue',
            'delete-title' => 'Are you sure you would like to delete your review?',
            'tos-checkbox-part-1' => 'By submitting this form you accept SkinMC\'s Terms of Service, Privacy Policy, and Community Guidelines. You also confirm that all of the information is accurate, and follows the',
            'tos-checkbox-part-2' => 'review guidelines.',
            'tos-checkbox-part-3' => 'Your review will be published after submission, but can be subject to review.'
        ],
        'slots' => 'Slots',
        'empty-helper' => 'You can try to do another search or',
        'empty' => 'Hmm it\'s still empty here.',
        'verified' => 'Verified',
        'review_translate_show_original' => 'Show original',
        'review_translate' => 'Oversett vurdering',
        'description_translate' => 'Translate description',
        'create' => [
            'welcome' => 'Welcome',
            'basics' => 'Basics',
            'categories' => 'Categories',
            'social_links' => 'Social links',
            'trailer_video' => 'Trailer video',
            'images' => 'Images',
            'images_description' => 'You can upload photos afterwards, to showcase what your server offers.',
            'submit' => 'Submit',
            'lets_get_your_server_added' => 'Let\'s get your server added.',
            'basics-subtitle' => 'Let people know what your server is about.',
            'description' => 'Description',
            'description_tips' => 'Here are some tips',
            'description_hint' => 'Write a good description for your server to attract new players.',
            'categories-subtitle' => 'Choose some categories for your server',
            'missing-category' => 'Missing a category?',
            'social_links_description' => 'Where can players connect with your server on social media?',
            'trailer_video_description' => 'Showcase your server with a YouTube video.',
            'trailer_video_hint' => 'Paste the video URL or ID:',
            'ready_to_submit_your_server' => 'Ready to submit your server?',
            'review-hint' => 'After submission the team will carefully review your server listing application. Then upon decision, your server will be published, or changes requested before going live.',
            'terms' => [
                'part-1' => 'By submitting this form you are authorised to accept SkinMC\'s Terms of Service, Privacy Policy, and Community Guidelines. You also confirm that all of the information above is accurate, you have properly followed the',
                'part-2' => 'server requirements for setup',
                'part-3' => ', and that the Minecraft server is owned and managed by the entity you are representing.'
            ],
            'submit-application' => 'Submit application',
            'video-id-helper' => [
                'part-1' => 'The video ID is the string of numbers and letters after',
                'part-2' => 'For example if your video url is',
                'part-3' => ', then your video ID would be'
            ],
            'welcome_description' => 'In this step, we\'ll get started on adding your server. Tell us a bit about it, write a description, and in the next step you can upload some images.'
        ],
        'copy_server_ip' => 'Copy server IP',
        'all_minecraft_servers' => 'All Minecraft Servers',
        'promo' => [
            'title' => 'Do you host a Minecraft Server?',
            'ready_to_list_your_server' => 'Ready to list your Server?',
            'everything_you_need' => 'Everything you need to grow your server',
            'list_your_server' => 'List your server',
            'list_your_server_description' => 'Create a listing for your server, add photos, social media and more.',
            'find_players' => 'Find players',
            'find_players_description' => 'Find and reach new players to join your server and grow your community.',
            'get_reviews' => 'Get reviews',
            'get_reviews_description' => 'Ask your community to review your server, and reward them in game.',
            'why_list_on_skinmc' => 'Why you should list your Server on SkinMC',
            'others' => 'Others',
            'quality_check_and_confirmation' => 'Quality check and confirmation',
            'quality_check_description' => 'Our team reviews every server to ensure quality.',
            'verified_players' => 'Reviews from verified Minecraft players',
            'verified_players_description' => 'Collect authentic player reviews from legitimate accounts with Votifier integration.',
            'international' => 'International',
            'international_description' => 'With translation features your listing is available to more players.',
            'server_listing_page' => 'Powerful Server listing page',
            'server_listing_page_description' => 'Add photos, description texts, youtube videos, and highlight why players should join your server.',
            'social_connections' => 'Social media connections',
            'social_connections_description' => 'Connect your Servers social accounts and show new players where they can find you.',
            'verified_badge' => 'Verification badge',
            'verified_badge_description' => 'Authentic servers can apply for a verification badge.',
            'owner_profile' => 'Owner profile',
            'owner_profile_description' => 'Add a personal touch, by completing your custom profile.',
            'categories' => 'Categories',
            'categories_description' => 'Different categories to make it easier to find your server.',
            'vote' => 'Vote',
            'vote_description' => 'Ask users to vote for your server.',
            'fair_listings' => 'Fair listings',
            'fair_listings_description' => 'Server listings can not be artificially boosted in results on SkinMC.',
            'support' => '24h support',
            'support_description' => 'Do you need help or have questions? You can always reach out and receive a fast reply.',
            'custom_features' => 'Custom features',
            'custom_features_description' => 'Missing a feature for your server? Open a ticket, and we\'ll implement it.',
            'faq' => [
                'title' => 'Answers to your questions',
                'suited-question' => 'Is my Minecraft Server suited for SkinMC?',
                'suited-answer' => 'Minecraft Players on SkinMC love to discover new experiences, content and engage with communities. On the platform you\'ll find a large variety of different, unique, fun Minecraft servers. From a large network to even a small survival server, it can make someones day!',
                'get-started-question' => 'How do I get started?',
                'get-started-answer' => 'Adding your Minecraft Server to the SkinMC Server List is very easy! You will first need to create an account, if you haven\'t already, and then follow the setup guide to get your server listed. Add a few photos and a nice description, and your server will be published in no time!',
                'players-question' => 'How can I get more players on my Minecraft Server?',
                'players-answer' => 'Building a community is the most crucial part of a long lasting Minecraft Server. Use the Minecraft Server List on SkinMC to find a new audience and continue to build your community. Ask your players to recommend your Server, or share your listing on social media platforms. Collecting good reviews can also play an important role to a great Server listing presence that attracts new players.',
                'more-question' => 'I have more questions. Where can I get help?',
                'more-answer' => 'You can reach out to SkinMC at any time, 24 hours, by using either the help button, the help desk, or by joining the Discord server.'
            ],
            'ready_to_list_description' => 'Add your Minecraft Server to the SkinMC Server List in just a few minutes. If you need any help, you can reach out around the clock and receive answers quickly.'
        ],
        'manage' => [
            'index' => [
                'welcome' => 'Welcome back, :username',
                'your_servers' => 'Your servers',
                'reviews_today' => 'Reviews today',
                'no_reviews_today' => 'No reviews today',
                'no_reviews_text' => 'Your servers haven\'t received any reviews today. Why not ask your players to leave one?',
                'tips' => [
                    'title' => 'Tips',
                    'description-title' => 'Write a good server description',
                    'description-body' => 'Helpful tips and advice to write a great server description.',
                    'images-title' => 'Adding server images',
                    'images-body' => 'Make your server listing stand out with great images.'
                ]
            ],
            'listings' => [
                'title' => 'Your Minecraft servers (:count)'
            ],
            'insights' => [
                'title' => 'Insights'
            ],
            'edit_server' => 'Edit server',
            'listing' => 'Listing',
            'to_do' => 'To do',
            'last_update' => 'Last update',
            'add_more_photos_to_publish' => 'Add more photos to publish',
            'looks_empty_here' => 'Looks empty here.',
            'get_started_by_adding_a_new_server' => 'Get started by adding a new server?'
        ],
        'status' => [
            'approved' => 'Approved',
            'pending_approval' => 'Pending approval',
            'published' => 'Published',
            'in_review' => 'In review'
        ]
    ],
    'editor' => [
        'import' => [
            'title' => 'Import Skin',
            'import_by_username' => 'Import by username',
            'import_button' => 'Import',
            'drag' => 'Drag and drop a skin here, or click',
            'click' => 'Select image'
        ],
        'draw' => 'Draw',
        'eyedropper' => 'Eyedropper',
        'fill' => 'Fill',
        'move' => 'Move',
        'decrease_brightness' => 'Decrease brightness',
        'increase_brightness' => 'Increase brightness',
        'erase' => 'Erase',
        'undo' => 'Step back (CTRL+Z)',
        'redo' => 'Step forward (CTRL+Y)',
        'default_view' => 'Default view',
        'zoom_in' => 'Zoom in (CTRL +)',
        'zoom_out' => 'Zoom out (CTRL -)',
        'saved' => 'Sist lagret akkurat nå',
        'saving' => 'Automatisk lagring...',
        'save_error' => 'En feil oppstod',
        'new_skin' => 'New skin',
        'previous_skins' => 'Previous skins',
        'backed_up_title' => 'Automatically saved skins',
        'backed_up_info' => 'Temporarily backed up to your local storage.',
        'backed_up_empty_title' => 'It\'s empty here',
        'backed_up_empty_info' => 'Once you start editing skins you\'ll see your 32 last edited skins here.',
        'backed_up_skins_count' => 'of 32 skin backups used',
        'backed_up_skins_count_info' => 'You can back up to up 32 skins. Once you reach 32 skins an older skin will be replaced with a new one.',
        'layers' => 'Lag',
        'body' => [
            'title' => 'Innhold',
            'overlay' => 'Overlay',
            'head' => 'Hode',
            'torso' => 'Overkropp',
            'l_arm' => 'Venstre arm',
            'r_arm' => 'Høyre arm',
            'l_leg' => 'Venstre bein',
            'r_leg' => 'Høyre bein',
        ],
        'model' => 'Modell',
        'steve' => 'Steve',
        'alex' => 'Åpen',
        'stance' => [
            'title' => 'Posisjon',
            'default' => 'Standard',
            'walk' => 'Gå',
            'run' => 'Kjør',
            'hug' => 'T-poser',
            'fly' => 'Flue',
        ],
        'fullscreen' => 'Fullscreen',
        'fullscreen_exit' => 'Exit fullscreen',
        'grid' => 'Rutenett',
        'show_grid' => 'Vis rutenett',
        'download' => [
            'title' => 'Lagre og last ned',
            'subtitle' => 'SkinMC konto',
            'description' => 'Ønsker du å lage en gratis SkinMC konto for å spare skinn og framtidens til skyen?',
            'start_description' => 'Start nedlasting direkte uten å lagre i skyen',
            'start' => 'Last ned skinet',
        ],
        'help' => [
            'title' => 'Minecraft Skin Editor',
            'about' => 'Create and edit your custom Minecraft Skin easily with the SkinMC Editor. You can choose between Steve and Alex models, import skins from a file or username, and create your very own Minecraft Skin.',
            'draw' => 'Draw using the pen tool. Select a colour from the swatch to use with it.',
            'eyedropper' => 'Use the eyedropper to select a colour from your skin and add it to your current palette.',
            'fill' => 'Fill entire areas of your skin using the fill tool. Select a colour before using fill.',
            'move' => 'Pan and move around the skin editor canvas with the move tool.',
            'decrease_brightness' => 'Decrease the brightness of the currently active colour.',
            'increase_brightness' => 'Increase the brightness of the currently active colour.',
            'erase' => 'Erase pixels drawn on the secondary overlay layer.',
        ],
    ],
    'account' => [
        'level' => 'Level',
        'level_history' => 'Level history',
        'xp' => 'XP',
        'my_xp' => 'My XP',
        'xp_to_next_level' => ':xp XP to next level',
        'xp_info' => 'What are XP?',
        'xp_info_tooltip' => 'XP is earned for various activities such as adding tags to skins, inviting friends, commenting, and much more. With each XP earned you can level up and unlock cool things!',
        'settings' => [
            'title' => 'Konto',
            'show_profile' => 'Gå til profil',
            'friends' => 'Venner',
            'friends_detail' => 'Hold deg tilkoblet ved å bruke vennelisten din på SkinMC.',
            'security' => 'Sikkerhet',
            'security_detail' => 'Oppdater ditt passord og ta vare på kontoen din',
            'social' => 'Sosiale medier kontoer',
            'social_detail' => 'Tilpass profilen din ved å legge til dine sosiale medier',
            'link' => 'Koble til Minecraft-konto',
            'link_detail' => 'Koble til Minecraft-kontoen din og få profilen din.',
            'logout' => 'Vil du logge ut av SkinMC-kontoen din?',
            'automatic_backups' => 'Automatic skin backups',
            'automatic_backups_info' => 'As a SkinMC plus member your skins are backed up daily.',
        ],
        'capes' => [
            'title' => 'SkinMC Minecraft Cape',
            'description' => 'Wear any cape you wish in-game with SkinMC Capes for free.',
            'drop' => 'Drag and drop a cape here',
            'drop-hint' => 'Dimensions 64x32px',
            'select' => 'Select image',
            'upload-cape' => 'Upload & use cape',
            'save-and-use' => 'Save & use',
            'uploaded-cape' => 'Uploaded cape',
            'no-cape' => 'No cape',
            'remove-cape' => 'Remove cape',
            'download' => 'Download the SkinMC Mod to see your and other players capes in-game.',
            'learn-more' => 'Learn more',
            'link-account' => 'Please link your Minecraft account to upload a cape.',
            'updated' => 'Your cape has been updated!',
            'removed' => 'Your cape has been removed.',
            'active' => 'Your cape is activated!'
        ],
        'favourite' => 'Favourite',
        'remove_favourite' => 'Remove favourite',
        'added_to_favourites' => 'Added to favourites',
        'removed_from_favourites' => 'Removed from favourites',
        'welcome' => 'Nice to see you!',
        'view-profile' => 'View my profile',
        'security' => [
            'title' => 'Sikkerhet',
            'email' => 'Epost adresse',
            'email-title' => 'Update your email address.',
            'save' => 'Lagre',
            'password' => 'Passord',
            'password-title' => 'Change your password at any time.',
            'social-provider' => 'To update your account information, such as your password, please visit your login provider:',
            'social-provider-email' => 'Your associated email address with your login provider',
            'social-provider-connected' => 'Currently connected login providers',
            'current-password' => 'Current password',
            'forgot' => 'Forgot password?',
            'edit' => 'Rediger',
            'delete' => 'Delete my account',
            'account-deletion' => 'Delete your SkinMC account.',
            'delete-info' => 'Please confirm to continue',
            'delete-confirmation' => 'Deleting your account is irreversible. All your personal information and content such as posts, favourites, uploaded capes, customisations, etc. will be deleted and can not be recovered.',
            'delete-confirmation-info' => 'Enter your password to continue',
            'yes-confirm-delete' => 'Yes, confirm delete',
            'account-successfully-deleted' => 'Your account and data has been successfully deleted.'
        ],
        'social' => [
            'title' => 'Sosiale kontoer',
            'edit' => 'Rediger',
            'save' => 'Lagre',
            'link-account' => 'Link your Minecraft account to SkinMC to display your social links on your profile.',
            'finish-setup' => 'Finish setup',
            'connect-account' => 'Connect your accounts',
            'connect-description' => 'Choose which accounts you wish to connect and unlock special SkinMC integrations.',
            'empty' => 'No accounts added',
            'empty-description' => 'Your social media accounts will show up here and on your public profile. Once added they will add more personalisation to your page as well as enable integrations.',
            'connect' => 'Connect',
            'username' => 'username',
            'spotify' => 'Add your Spotify username to show your Spotify information on your profile.',
            'discord' => 'Enter your Discord username and number to display your Discord information on your SkinMC profile.',
            'youtube' => 'Add your YouTube channel to SkinMC which will display your YouTube channel on your profile.',
            'youtube-format' => 'Use the following format depending on your channel link:',
            'twitter' => 'Enter your Twitter username to display it on your profile.',
            'twitch' => 'Enter your Twitch username to display your Twitch channel on your profile.',
            'reddit' => 'Enter your Reddit username to display your Reddit profile on your profile.',
            'github' => 'Enter your GitHub username to display your GitHub profile on your profile.',
            'telegram' => 'Enter your Telegram username to display your Telegram link on your profile.',
            'tiktok' => 'Enter your TikTok username to display your TikTok profile on your profile.',
            'snapchat' => 'Enter your Snapchat username to display your Snapchat profile on your profile.',
            'instagram' => 'Enter your Instagram username to display your Instagram profile on your profile.',
            'facebook' => 'Enter your Facebook username to display your Facebook profile on your profile.',
            'includes_skinmc_plus_benefits' => 'Includes SkinMC plus benefits',
        ],
        'recover' => [
            'title' => 'Gjenopprett din konto',
            'subtitle' => 'Vennligst skriv inn det nye passordet ditt og bekreft det for å fullføre gjenopprettingen av kontoen.',
            'new_password' => 'Nytt passord',
            'repeat_new_password' => 'Gjenta nytt passord',
            'submit' => 'Gjenopprett konto',
        ],
        'customise' => [
            'title' => 'Customise your profile',
            'description' => 'Add your social media, choose an emoji, set your location and more',
            'information' => 'Information',
            'preview' => 'Preview',
            'location' => [
                'title' => 'Location',
                'description' => 'Choose which location you would like to add to your profile.',
            ],
            'biography' => [
                'title' => 'About me',
                'description' => 'Write a bio for your profile.',
            ],
            'status' => 'Status',
            'status-toggle' => 'Show my online status',
            'emoji' => 'Emoji',
            'name-history-toggle' => 'Make username history private',
            'name-history-info' => 'Your Minecraft username history is currently',
            'name-history-toggle-on' => 'private',
            'name-history-toggle-off' => 'public',
            'theme' => 'Profile theme',
            'theme-primary' => 'Primary',
            'theme-secondary' => 'Secondary',
        ],
        'link' => [
            'manage' => 'Manage linked Minecraft account',
            'description' => 'See and manage your linked Minecraft account',
            'title' => 'Linked Minecraft account',
            'current' => 'Currently linked Minecraft account.',
            'status' => 'You now have full access to all SkinMC features!',
            'linked' => 'Linked',
            'disconnect' => 'Disconnect',
            'disconnect-title' => 'Disconnect Minecraft account',
            'disconnect-info' => 'Are you sure you would like to disconnect your Minecraft account?',
            'disconnect-features' => 'You will lose access to commenting, customisation and other features which require a linked Minecraft account. To use these again you will be required to link a Minecraft account.',
            'disconnect-following' => 'Disconnecting your Minecraft account will permanently remove all your followed profiles.',
            'disconnect-posts' => 'Your created feed posts and liked will be deleted.',
            'can-not-undo' => 'This can\'t be undone.',
            'are-you-sure' => 'Are you sure?',
            'confirm' => 'Yes, confirm disconnect',
            'cancel' => 'No, cancel',
            'success' => 'Your account was successfully disconnected!'
        ],
        'finish-setup' => [
            'title' => 'Finish account setup',
            'description' => 'Finish setting up your account, and get full access to all features by linking your Minecraft account to SkinMC.',
            'link' => 'Link Minecraft account',
            'get-started' => 'Get started',
            'skip' => 'Skip',
            'claim' => 'Claim your profile',
            'customise' => 'Customise your page',
            'social' => 'Add social links',
            'comment' => 'Access to comment system',
            'direct_message' => 'Send direct messages',
            'feed' => 'Post status updates to the feed',
            'follow' => 'Follow your friends',
            'badge' => 'Badge displayed on your profile',
            'cape' => 'Custom Minecraft cape',
            'backup' => 'Automatic skin backup',
            'more' => 'And more...'
        ],
        'skins' => [
            'title' => 'Manage skins',
            'toggle' => 'Skin visibility toggled',
        ],
        'invite' => [
            'title' => 'My invites',
            'headline' => 'Invite your friends',
            'info' => 'Create an invite code to share with your friend. Once they accept it, you\'ll both earn some extra XP!',
            'description' => 'Create an invite for your friends and you\'ll both earn some extra XP.',
            'generate' => 'Create invite code',
            'empty' => 'You haven\'t created any invites yet.',
            'code' => 'Code',
            'expiry' => 'Each code works once.',
            'status' => [
                'title' => 'Status',
                'pending' => 'Pending',
                'accepted' => 'Accepted'
            ],
            'add_invite' => [
                'button' => 'Have an invite?',
                'title' => 'Add an invite code',
                'redeem' => 'Redeem invite',
            ],
            'share' => 'Send your friend an invite link'
        ],
        'emoji' => [
            'title' => 'SkinMC Emoji',
            'introducing' => 'Introducing',
            'info' => 'Customise your profile with emoji. Unlock more as you level up.',
            'unlocked_at' => 'Unlocked at level :level',
            'unlocks_at' => 'Reach level :level to unlock',
            'turn_off' => 'Show emoji'
        ]
    ],
    'notifications' => [
        'title' => 'Notifications',
        'view_all' => 'View all',
        'view_all_notifications' => 'View all notifications',
        'image' => 'Notification photo',
        'archived' => 'Archived',
        'inbox' => 'Inbox',
        'empty' => [
            'title' => 'You\'re up to date!',
            'text' => 'New notifications will show up here.',
            'text-archived' => 'Archived notifications will show up here.',
        ],
        'action' => [
            'archive' => 'Move to archive',
            'unarchive' => 'Unarchive',
            'open' => 'Tap to open',
        ],
        'toast' => [
            'archive' => 'Notification moved to archive',
            'unarchive' => 'Notification moved to inbox',
            'undo' => 'Undo',
        ]
    ],
    'error' => [
        'offline' => [
            'title' => 'No internet',
            'subtitle' => 'Your internet was disconnected. Please check your connection and reload the page to try again.',
            'try_again' => 'Try again'
        ],
        '404' => [
            'title' => '404 — Page not found.',
            'subtitle' => 'Hm, it looks like nothing was found at this location. Maybe try going back, or start a new search?',
            'try_again' => 'Back home'
        ],
    ],
    'heads' => [
        'list' => [
            'meta' => [
                'title' => 'Minecraft heads database',
                'description' => 'Explore the database of Minecraft heads to decorate your world with, or generate your own give command. View official heads, player heads and custom heads that feature textures which never change.'
            ],
            'header' => [
                'title' => 'Minecraft heads',
                'subtitle' => 'Explore our database of Minecraft heads to decorate your world, or generate your own give command. Player heads show the current skin worn by a user, and can change as the user updates their skin. Custom heads are linked to the Mojang skin file and never change. Custom heads must be summoned using a command block as the command is very long.',
            ],
            'count' => [
                'heads' => ':heads head|:heads heads',
            ],
            'customheads' => [
                'title' => 'Custom heads',
                'description' => 'Custom heads use the direct path to the texture file on the Mojang servers. Hence textures will never be deleted and the heads never change.',
                'version' => 'Minecraft 1.8 or later',
            ],
            'playerheads' => [
                'title' => 'Player heads',
                'description' => 'Player heads use the current skin texture of a Minecraft player. As they are username based, when the player changes their name or skin, the head changes.',
                'version' => 'All Minecraft versions',
            ]
        ],
    ],
    'mod' => [
        'title' => 'SkinMC Mod: Free custom capes',
        'headline' => 'Introducing the SkinMC Mod for more customisation',
        'description' => 'Giving back to the Minecraft community, with a free mod which enables players more customisation with custom capes, available and visible for anyone using the mod.',
        'download' => 'Download now',
        'download-title' => 'Download the mod',
        'requires' => 'Requires',
        'select-version' => 'Choose your Minecraft version',
        'get-started' => 'Getting started is simple',
        'step-1' => '1. Get the mod',
        'step-1-detail' => 'Install Fabric, then download the mod for your game version and install it by putting the jar in your mods folder.',
        'step-2' => '2. Link your account',
        'step-2-detail' => 'If you haven\'t already, sign up/in and connect your Minecraft account to SkinMC.',
        'step-3' => '3. Upload your cape',
        'step-3-detail' => 'Go to your account and upload your custom cape. It will be visible in-game.',
        'all-versions' => 'All versions',
        'latest' => 'Latest',
        'logged-in' => 'Upload your cape',
        'mirror' => 'Mirror',
        'download-via' => 'Download via:',
        'curseforge' => 'CurseForge',
    ],
    'app' => [
        'title' => 'SkinMC Android App',
        'headline' => 'Say hello to the SkinMC Android App.',
        'play-store-attribution' => 'Google Play og Google Play-logoen er varemerker tilhørende Google LLC.',
        'features' => 'Convenient features for on the go',
        'feature-qr' => 'Built in QR-Code scanner',
        'feature-qr-detail' => 'Use the built in QR-Code scanner to easily get a skin from your Desktop to the app, or scan your friends custom profile QR-Code.',
        'feature-files' => 'Saves directly to files',
        'feature-files-detail' => 'With the usage of Android Files Manager, the app can conveniently save Skins, making it easier to apply in Bedrock Edition.',
        'feature-noads' => 'No ads',
        'feature-noads-detail' => 'A clean designed interface, without distractions. Enjoy an Ad-free experience without intrusive annoyances from web to app.',
        'feature-experience' => 'Experience',
        'feature-experience-detail' => 'Enjoy the full SkinMC experience anywhere, with added features. Customise your profile, add your bio, create a fun QR-Code and more!',
        'get-app-headline' => 'Get the SkinMC App',
        'get-app-detail' => 'Your very own Minecraft companion for your Android — available for free.'
    ],
    'random' => [
        'title' => 'Loading random Minecraft skin',
        'description' => 'Loading random Minecraft skin',
        'headline' => 'Please wait...',
        'redirect' => 'You will be automatically redirected. Page not loading?',
        'click-here' => 'Click here',
        'messages' => [
            '1' => 'Loading random Minecraft skin...',
            '2' => 'Digging down...',
            '3' => 'Creeper, aw man...',
            '4' => 'Searching through chests...',
            '5' => 'Did you know the coming skin is completely random?',
            '6' => 'Random skin incoming...',
            '7' => 'One more block...',
            '8' => 'Sorting inventory...',
            '9' => 'Crafting diamond pickaxe...',
            '10' => 'Looking for Herobrine...',
        ],
    ],
    'feed' => [
        'title' => 'Feed',
        'following' => 'Following',
        'sign-up' => 'Sign up or log in to join the conversation.',
        'link-account' => 'Link your Minecraft account to join the conversation.',
        'placeholder' => 'What is happening?',
        'audience' => 'Audience',
        'audience-title' => 'Who can see this?',
        'everyone' => 'Everyone',
        'everyone-info' => 'Anyone on or off SkinMC.',
        'followers' => 'Followers',
        'followers-info' => 'Signed in or members following me.',
        'private' => 'Only me',
        'private-info' => 'Private post only I can see.',
        'submit' => 'Post',
        'like' => 'Like',
        'comment' => 'Reply',
        'share' => 'Share',
        'remaining' => 'Remaining',
        'profile' => 'Posts by :username',
        'posts' => 'All posts',
        'my-posts' => 'My posts',
        'view-all' => 'View all posts',
        'post' => [
            'meta' => ':username on SkinMC: :text',
            'title' => 'Post',
            'created' => 'Status update posted!',
            'confirm-delete' => 'Are you sure you would like to delete this post? It can not be undone.',
            'delete' => 'Delete post',
            'deleted' => 'Your post was deleted.',
        ],
        'follow-suggestions' => 'Follow the team',
        'explore' => 'Explore',
        'hashtag' => 'Hashtag',
    ],
    'private' => [
        'title' => 'Private posts',
        'text' => 'This post is private.'
    ] ,
    'liked' => [
        'title' => 'Liked'
    ],
    'following' => [
        'title' => 'Following',
        'text' => 'Sign in to view this post.'
    ],
    'tags' => [
        'empty' => 'No tags to vote on yet',
        'empty-subtitle' => 'Be the first to add one',
    ],
    'inbox' => [
        'title' => 'Messages',
        'details' => 'Details',
        'message_user' => 'Message',
        'write_message' => 'Write a message',
        'empty' => [
            'no_message_selected' => 'No message selected',
            'open_or_start_conversation' => 'Open a conversation from the message list, or start a new one.',
            'no_messages' => 'No unread messages',
            'start_conversation' => 'Once you start a new conversation, your messages will be displayed here.',
            'conversation' => 'This is the beginning of your conversation with :username.',
            'users' => 'Unable to find any users that match the current query.'
        ],
        'typing' => ':username is typing...',
        'new_message' => 'New message',
        'mark_unread' => 'Mark unread',
        'send_message' => 'Send message',
        'delete_message' => 'Delete message for you',
        'latest_conversations' => 'Latest conversations',
        'delete_conversation' => 'Delete conversation',
        'show_details' => 'Show details',
        'hide_details' => 'Hide details',
        'unread' => 'Unread',
        'deleted' => 'Deleted',
        'report_message' => 'Report message',
        'add_reaction' => 'Add reaction',
        'today' => 'Today',
        'reconnect' => 'Please reconnect your Minecraft account to chat',
        'account_disconnected' => 'This user disconnected their linked Minecraft account.',
        'saved_messages' => 'Saved messages',
        'new_message_to_label' => 'To',
        'external-link-to' => 'This link will take you to',
        'external-link-confirmation' => 'Are you sure you want to go there?',
        'external-link' => 'External link',
        'reply' => 'Reply'
    ],
    'server' => [
        'manage' => [
            'stats' => 'Stats'
        ]
    ],
    'report' => [
        'button' => 'Report',
        'title' => 'Report content',
        'describe' => 'Briefly describe why you are reporting this',
        'select' => 'Select report reason',
        'submit' => 'Submit report',
        'reasons' => [
            'INAPPROPRIATE_CONTENT' => 'Inappropriate content',
            'SPAM' => 'Spam',
            'HARASSMENT' => 'Harassment',
            'OTHER' => 'Other',
        ]
    ],
    'leaderboard' => [
        'title' => 'Leaderboard',
        'description' => 'View the SkinMC leaderboard of users.',
        'headline' => 'Top 10',
        'all-time-invites' => 'All time invites',
        'all-time-xp' => 'All time XP',
        '30-day-xp' => '30 days XP'
    ],
];
