<?php

return [
    'skins' => 'Skórki',
    'avatars' => 'Awatary',
    'editor' => 'Edytor',
    'heads' => 'Głowy',
    'capes' => 'Pelerynki',
    'servers' => 'Serwery',
    'achievement' => 'Osiągnięcie',
    'armor' => 'Stojak na zbroję',
    'banners' => 'Banery',
    'banner' => 'Banner Editor',
    'profile' => 'Mój profil',

    'generators' => 'Generatory',

    // Navigation dropdowns
    'feed' => 'Feed',
    'discover' => 'Discover',
    'mods' => 'Mods',
    'shaders' => 'Shaders',
    'resource_packs' => 'Resource Packs',
    'modpacks' => 'Modpacks',
    'datapacks' => 'Data Packs',
    'plugins' => 'Plugins',

    'logout' => 'Wyloguj się',
    'register' => 'Zarejestruj',
    'login' => 'Zaloguj się',
    'about' => 'O programie',
    'contact' => 'Kontakt',
    'faqs' => 'Często zadawane pytania',

    'minecraft_name' => 'Nazwa Minecraft',
    'minecraft_uuid' => 'Identyfikator UUID Minecrafta',
    'what' => 'Co',
    'recent_searches' => 'Ostatnie wyszukiwania',
    'username' => 'Nazwa użytkownika',
    'uuid' => 'Identyfikator UUID',
    'search' => 'Szukaj',
    'search_placeholder' => 'Wypróbuj',
    'search_placeholder_uuid' => 'Wprowadź UUID',
    'start_search' => 'Rozpocznij wyszukiwanie',
    'cancel_search' => 'Anuluj',
    'search_type' => 'Typ wyszukiwania',
    'search_type_all' => 'Wszystkie wyniki',
    'profiles' => 'Profile',
    'view_skin' => 'Zobacz skórkę',
    'edit_skin' => 'Edytuj skórkę',
    'make_avatar' => 'Stwórz awatar',
    'find_heads' => 'Znajdź głowy gracza',
    'no_results_found' => 'No suggestions yet. Hit Enter to look it up.',

    'home' => 'Strona główna',
    'help' => 'Pomoc',
    'tools' => 'Narzędzia',
    'more-tools' => 'Więcej narzędzi',
    'skin_viewer' => 'Przeglądarka skinów',
    'avatar_maker' => 'Wytwórca awatarów',
    'collections' => 'Kolekcje',
    'popular_skins' => 'Popularne skórki',
    'cartoon_skins' => 'Skóry puszkowe',
    'animal_skins' => 'Skóry zwierzęce',
    'community' => 'Społeczność',
    'imprint' => 'Impressum',
    'cookies' => 'Pliki cookie',
    'terms' => 'Warunki korzystania',
    'privacy' => 'Polityka prywatności',
    'app' => 'Aplikacja',
    'mod' => 'Modyfikacja',
    'totem' => 'Totemy',
    'cube' => 'Cube',
    'new' => 'New',

    'feedback' => 'Sugestie',
    'status' => 'Status',
    'recent_searches_placeholder' => 'W miarę wyszukiwania, twoje wcześniejsze będą wyświetlane tutaj.',
    'recent_views_placeholder' => 'Po odwiedzeniu profili, twoje wcześniej odwiedzone profile będą wyświetlane tutaj.',
    'moderate' => 'Umiarkowany',
    'listings' => 'Oferty',
    'add' => 'Dodaj',

    // Autocomplete types
    'autocomplete' => [
        'profile' => 'Profile',
        'server' => 'Server',
        'project' => 'Project',
        'skin_tag' => 'Skin Tag',
        'server_category' => 'Server Category',
        'modrinth_category' => 'Project Category',
    ],

    'theme' => [
        'title' => 'Theme',
        'dark' => 'Ciemny',
        'light' => 'Jasny',
        'auto' => 'Auto',
    ],
];
