<?php

return [
    'auth' => [
        'login' => [
            'title' => 'Witaj na SkinMC',
        ],
        'register' => [
            'title' => 'Zarejestruj się do SkinMC',
            'subtitle' => 'Rozpocznij i utwórz swoje konto, aby uzyskać pełny dostęp.'
        ]
    ],

    'home' => [
        'hero_slogan' => 'Twoje miejsce dla Skórki Minecraft.',
        'hero_slogan_alt_1' => 'Everything Minecraft. One place.',
        'hero_slogan_alt_2' => 'Where Minecrafters meet.',
        'hero_cta' => 'Niespodzianka',
        'hero_explore_cta' => 'Przeglądaj skórki',
        'skin_viewer' => 'Przeglądarka skinów',
        'skin_viewer_detail' => 'Przeglądaj skiny :count',
        'skin_editor' => 'Edytor skinów',
        'skin_editor_detail' => 'Zaprojektuj swoją własną skórkę',
        'avatar_maker' => 'Generator awatarów',
        'avatar_maker_detail' => 'Generuj spersonalizowane profilowe zdjęcia awatarów Minecraft.',
        'trending' => 'Popularne',
        'minecraft_skin' => 'Skórka Minecraft',
        'favourite' => 'Ulubione',
        'collections' => 'Kolekcje',
        'collections_detail' => 'Przeklęte skórki Minecraft na każdą okazję',
        'about_skinmc' => 'O SkinMC',
        'about_find' => 'Znajdź dowolną skórkę',
        'about_find_detail' => 'Użyj wyszukiwania SkinMC dla dowolnej nazwy użytkownika Minecraft, aby znaleźć, wyświetlić i pobrać swój następny skin.',
        'about_download' => 'Pobierz lub edytuj',
        'about_download_detail' => 'Znalazłeś skórkę, którą lubisz? Dodaj ją do swoich ulubionych, edytuj lub pobierz i zrób ją własną.',
        'about_platform' => 'Platforma międzyplatformowa',
        'about_platform_detail' => 'Chcesz zabrać skórkę w podróży? Zeskanuj kod QR i zapisz obraz w telefonie dla Minecraft PE.',
        'meta' => [
            'title' => 'Przeglądarka skinów Minecraft',
            'description' => 'Obejrzyj i pobierz skórki Minecraft, odkryj najlepsze skórki w pekowanych kolekcjach, sprawdź dostępność i historię nazwy użytkownika i wiele więcej!',
        ],
        'recently_viewed' => 'Ostatnio oglądane',
        'explore_title' => 'Wypróbuj czegoś nowego',
        'explore' => 'Odkryj nowe pomysły i narzędzia',
        'servers_browse' => 'Przeglądaj serwery',
        'servers' => 'Odkryj najlepsze serwery Minecraft',
        'heads' => 'Głowy Minecraft',
        'head_description' => 'Przeglądaj bazę głów Minecraft\'a lub stwórz nowe.',
        'achievement' => 'Generator osiągnięć',
        'achievement_detail' => 'Stwórz własne, niestandardowe i spersonalizowane osiągnięcia.',
        'continue' => 'Kontynuuj przeglądanie'
    ],
    'profile' => [
        'verified' => 'Zweryfikowany profil',
        'minecraft_profile' => 'Profil Minecraft',
        'show_qr_code' => 'Pokaż kod QR',
        'favourite' => 'Ulubione',
        'user_title' => ':username Minecraft skin',
        'user_views' => 'Wyświetlono :view time|Wyświetlono :view times',
        'uuid' => 'UUUID',
        'copy' => 'Kopiuj',
        'link' => 'Połączyć',
        'skin_history' => 'Historia skórek Minecraft (:skins)',
        'username_history' => 'Historia nazw użytkownika',
        'username_history_name' => 'Nazwisko',
        'username_history_timestamp' => 'Zmieniono o',
        'username_history_initial_name' => 'Nazwa początkowa',
        'user_downloads' => ':downloads pobrań|:downloads pobrań',
        'download_skin' => 'Pobierz skórkę',
        'apply_skin' => 'Zastosuj skórkę',
        'capes' => 'Pelerynki',
        'claim_profile' => 'Czy jesteś :username? Odbierz swój profil, aby zweryfikować i dostosować go!',
        'claimed' => 'Zarezerwowany profil',
        'meta_description' => 'Przeglądaj i pobieraj skórkę Minecraft użytkownika :username. Zobacz ich UUID, historię nazw, szczegółowe statystyki i więcej',
        'created_at' => 'Zaktualizowano: :changed_at',
        'skins' => [
            'meta_title' => 'Historia skórki Minecraft :username',
            'meta_description' => 'Widok :username Historia skórek Minecraft i poprzednio używane skórki. Użyj historii, aby przeglądać stare lub poprzednio używane skórki, tworzyć kopie zapasowe i przywracać lub zbierać nowe skórki.',
            'title' => 'Historia Skórki Minecraft'
        ],
        'qr_code' => [
            'meta_title' => 'Kod QR :username',
            'meta_description' => ':username Niestandardowy kod QR profilu Minecraft'
        ],
        'sub_nav' => [
            'skin' => 'Skórka',
            'about' => 'O nas',
            'usernames' => 'Nazwy użytkowników',
            'head' => 'Głowa',
            'comments' => 'Komentarze'
        ],
        'cape' => 'Pelerynka',
        'elytra' => 'Pokrywy',
        'nametag' => 'Etykieta nazwy',
        'animation' => 'Animacja',
        'rotation' => 'Rotacja',
        'none' => 'Brak',
        'idle' => 'Bezczynność',
        'walk' => 'Chodzenie',
        'run' => 'Bieg',
        'fly' => 'Lot',
        'follow' => 'Obserwuj',
        'following' => 'Obserwujesz',
        'unfollow' => 'Przestań obserwować',
        'followers' => 'Obserwuje|Obserwujący',
        'toast' => [
            'following' => 'Śledzisz teraz :username!',
            'follow-self-error' => 'Przepraszamy :username, nie możesz śledzić samego siebie.',
            'unfollowed' => 'Przestałeś śledzić :username'
        ],
        'edit' => 'Edytuj profil',
        'joined' => 'Dołączył(a)',
        'role' => 'Role',
        'server-fav-list-empty' => 'Wygląda na to, że :username nie ma jeszcze żadnych ulubionych serwerów. Gdy :username zapisze serwer jako swój ulubiony, możesz go zobaczyć tutaj.',
        'server-own-list-empty' => 'Wygląda na to, że :username nie ma jeszcze żadnych serwerów. Gdy :username doda serwer, możesz go tutaj zobaczyć.',
        'capes-list-empty' => 'Wygląda na to, że :username nie nosi jeszcze żadnej peleryny. Gdy :username założy pelerynę, możesz ją zobaczyć tutaj.',
        'feed-own-list-empty' => 'Looks like you haven\'t posted anything to the feed yet! Once you post, you can see your posts here.',
        'feed-list-empty' => 'Hmm, it seems like :username hasn\'t posted anything to the feed yet. Once :username posts something you can see it here.',
        'following-own-list-empty' => 'Wygląda na to, że jeszcze nikogo nie obserwujesz! Gdy zaczniesz obserwować inne osoby, zobaczysz je tutaj.',
        'following-list-empty' => 'Hmm, wygląda na to, że :username nikogo nie obserwuje. Kiedy :username zacznie obserwować ludzi, będziesz mógł ich zobaczyć tutaj.',
        'followers-own-list-empty' => 'Gdy ludzie zaczną śledzić Twój profil, pojawią się tutaj.',
        'followers-list-empty' => 'Hmm, wygląda na to, że :username nie jest przez nikogo śledzony. Bądź pierwszym, który śledzi :username. Gdy więcej osób zacznie śledzić, będziesz mógł je zobaczyć tutaj.',
        'render' => 'Silnik renderujący',
        '3d' => 'Render 3D',
        '2d' => 'Render 2D',
        'name-history-info' => 'Historia nazwy użytkownika jest niedostępna. Mojang usunął obsługę dostępu do API historii nazw 13 września 2022 r., co spowodowało niedostępność dokładnej historii nazw. Jeśli chcesz ukryć historię nazw, stwórz swój profil i przejdź do ustawień, aby uczynić go prywatnym.',
        'edit-skins' => 'Edytuj historię skórki',
        'hide-skin' => 'Ukryj skórkę',
        'show-skin' => 'Pokaż skórkę',
        'edit-skin' => 'Edytuj skórkę',
        'servers' => [
            'title' => ':servery użytkownika',
        ],
        'cape-list' => [
            'title' => ':peleryny użytkownika',
        ]
    ],
    'skin' => [
        'meta' => [
            'title' => 'Skórka Minecraft :username',
            'description' => 'Skórka Minecraft. Pobierz i zobacz skórkę i sprawdź, którzy gracze również mają ten sam skin.',
            'tags' => ':username Minecraft Skin, :username Skin, Minecraft Skin, :username Custom Minecraft Skin, Download Skin, Players with the same skin',
        ],
        'title' => 'Skórka Minecraft :username',
        'head' => 'Polecenia na Główkę',
        'head_info' => 'Do użycia z blokami poleceń',
        'first_wearing' => 'Pierwszy gracz noszący tę skórkę:',
        'profiles' => ':profiles profile|:profiles profiles',
        'profiles_title' => ':profiles profile with this skin|:profiles profiles with this skin',
        'screenshot' => 'Zrzut ekranu',
    ],
    'skins' => [
        'meta' => [
            'title' => 'Strona :current - Wszystkie Skórki Minecraft',
            'description' => 'Browse through our :last pages list of :total custom Minecraft skins and download your favourite next skin!',
            'tags' => ':username Minecraft Skin, :username Skin, Minecraft Skin, :username Custom Minecraft Skin, Download Skin, Players with the same skin',
            'tags-title' => ':tag Skórki Minecraft',
            'tags-description' => 'Browse through our :last pages list of :total :tag Minecraft skins and download your favourite :tag skin!',
            'tags-metatags' => ':tag Minecraft Skin, :tag Skin, Minecraft Skin, :tag Custom Minecraft Skin, Download :tag Skin, Minecraft :tag Skins',
        ],
        'title-skin-tags' => 'Otagowane skórki Minecraft',
        'subtitle' => 'Page :current of :last from :total Minecraft Skins',
        'subtitle-skin-tags' => 'Page :current of :last from :total Tagged Minecraft Skins',
        'sort_by' => 'Sortuj według',
        'latest' => 'Najnowsze skórki',
        'most_profiles' => 'Najczęściej używane skórki',
        'profiles_today' => 'Najczęściej używane dzisiaj',
        'profiles_this_week' => 'Najczęściej używane w tym tygodniu',
        'profiles_this_month' => 'Najczęściej używane w tym miesiącu',
        'default' => 'Domyślnie sortowanie',
        'this_month' => 'Dodane w tym miesiącu',
        'this_week' => 'Dodane w tym tygodniu',
        'today' => 'Dodane dzisiaj',
        'random' => 'Losowe',
        'similar' => 'Podobne skórki',
        'no_similar_skins' => 'Nie znaleziono podobnych skórek',
        'favorite' => ':count ulubiony|:count ulubionych',
    ],
    'skin-tags' => [
        'faq' => 'Co to są tagi?',
        'about' => 'Tags are a way you to add relevant categories to skins. Adding tags allows you to discover more skins you like easily!',
        'guidelines' => [
            'good' => [
                'title' => 'Ogólne wytyczne dotyczące dobrych tagów są następujące:',
                'short' => 'Krótki',
                'descriptive' => 'Opisowy',
                'spelled' => 'Poprawnie napisany',
            ],
            'bad' => [
                'title' => 'Nie dodawaj tagów takich jak:',
                'general' => 'Zbyt ogólne',
                'specific' =>  'Zbyt specyficzne',
                'too-many-tags' =>  'Powinno być trzy oddzielne znaczniki',
                'spelling' => 'Powinno być :przykład',
            ],
        ],
        'toast' => [
            'added' => 'Tag ”:tag” added for voting',
            'removed' => 'Tag ”:tag” has been removed',
            'upvote' => 'Polubione ":tag"',
            'downvote' => 'Niepolubione na ":tag"'
        ],
        'vote' => [
            'up' => 'Głosuj za',
            'down' => 'Głosuj przeciw',
            'remove' => 'Usuń głos',
        ],
    ],
    'contact' => [
        'contact' => 'Kontakt',
        'email' => 'Proszę napisz do nas pod adresem <a href="mailto:support@skinmc.net">support@skinmc.net</a> dla wszelkich pytań.',
        'faq' => 'We kindly ask to first check out the <a href=":link">FAQ page</a> if your question is already answered there.',
        'other' => 'Inne sposoby połączenia',
        'other_discord' => 'Join the Discord server and connect with others, chat about games, share your favourite packs and get help from the community.',
        'other_twitter' => 'Follow on Twitter to see when a new update or feature is released, see the skin of the week and more.',
        'other_instagram' => 'Follow SkinMC on Instagram to browse and discover cool new featured Minecraft Skins and images.',
        'other_facebook' => 'Become a fan on Facebook and see all posts where you can comment and talk to others while exploring Minecraft content.'
    ],
    'about' => [
        'intro' => '<span>Twoja</span> <span>platforma</span> <span>dla</span> <span>Skórek</span> <span>Minecraft.</span>',
        'header_credit' => 'Ilustracja "Epicka Bitewna Nether" przez',
        'info' => 'Śledź wszystko.',
        'info_explainer' => 'Zobacz historię nazw graczy, zobacz poprzednie skórki, dodaj je jako znajomy, pobierz skórki, a nawet uzyskaj statystyki szczegółów.',
        'card_find_title' => 'Znajdź dowolnego rzemieślnika',
        'card_find_detail' => 'Zacznij od szukania wybranej przez Ciebie nazwy użytkownika lub UUID.',
        'card_view_title' => 'Przeglądaj, zapisz i edytuj',
        'card_view_detail' => 'Znalazłeś skórkę, którą chcesz? Zapisz ją, pobierając lub użyj edytora, aby zrobić ją własną.',
        'card_claim_title' => 'Zostań zweryfikowany',
        'card_claim_detail' => 'Połącz swoje konto Minecraft i odbierz swój profil, aby odblokować fajne nowe funkcje!',
        'card_customise_title' => 'Dostosuj swój profil',
        'card_customise_detail' => 'Zweryfikowani gracze mogą dodać swoje linki do mediów społecznościowych i uczynić swój profil własnym.',
        'card_friends_title' => 'Dodaj znajomych',
        'card_friends_detail' => 'Połącz się z przyjaciółmi na SkinMC i pokaż listę znajomych na profilu.',
        'card_history_title' => 'Nazwa użytkownika i historia skinów',
        'card_history_detail' => 'Użyj zaawansowanego wyszukiwania, aby znaleźć i zobaczyć nazwę użytkownika/historię użytkownika gracza.',
        'founders' => 'Założyciele',
        'founders_cofounder' => 'Współtwórca SkinMC',
        'head_of_design' => 'Head of design',
        'head_of_code' => 'Head of code',
        'feedback' => 'Wyślij nam opinię',
        'faq' => 'Questions about Minecraft, Skins, and more? Read our FAQs with answers to most frequently asked questions.',
        'faq_link' => 'Odwiedź centrum pytań',
        'contact' => 'Chcesz się z nami skontaktować lub masz dodatkowe pytania? Skontaktuj się z nami bezpośrednio.',
        'contact_link' => 'Skontaktuj się z nami',

    ],
    'faq' => [
        'title' => 'Często zadawane pytania',
        'subtitle' => 'Często zadawane pytania',
        'help' => 'Potrzebujesz więcej pomocy?',
        'discord' => 'Dołącz do serwera Discord, aby rozmawiać z innymi graczami Minecraft.',
        'contact' => 'Skontaktuj się z nami',
        'q' => [
            'change_skin_t' => 'Jak zmienić swoją skórkę Minecraft?',
            'change_skin' => '
                <p>Aby zmienić skórkę, wykonaj następujące czynności:</p>
                <ol>
                    <li>Odwiedź <a href="https://my.minecraft.net/en-us/login/">https://my. inecraft.net/en-us/login/</a> i zaloguj się na swoje konto Mojang.</li><li>Po zalogowaniu wybierz <b>"Skórka"</b> w lewym menu.</li><li>Następnie wybierz model, który wolisz i prześlij Skórkę swoich upodobań.</li>
                </ol>',
            'change_username_t' => 'Jak zmienić nazwę użytkownika Minecraft?',
            'change_username' => '
                <p>Aby zmienić nazwę użytkownika, wykonaj następujące czynności:</p>
                <ol>
                    <li>Odwiedź <a href="https://account.mojang.com/login" target="_blank" rel="nofollow">https://account. ojang.com/login</a> i zaloguj się na swoje konto Mojang.</li>
                    <li>Znajdź swoją nazwę profilu Minecraft i naciśnij <b>"(zmiana)"</b> przycisk</li>
                    <li>Na następnej stronie, wpisz żądaną nową nazwę użytkownika.</li>
                    <li>Wreszcie, potwierdź zmiany, wprowadzając hasło i naciśnij "Zmień nazwę".</li>
                </ol>',
            'dl_t' => 'Jak pobrać kogoś ze Skórki Minecraft?',
            'dl' => '
                <p>Aby pobrać wszystkich Minecraft Skin wykonaj następujące czynności:</p>
                <ol>
                    <li>Naciśnij pasek wyszukiwania i wpisz nazwę użytkownika gracza, z którego chcesz pobrać skórkę.</li>
                    <li>Na stronie profilu możesz zobaczyć podgląd skórki</li>
                    <li>Kliknij na przycisk <strong>Pobierz skórkę</strong> pod podglądem</li>
                </ol>',
            'submit_q' => 'Jak dodać skórkę do kolekcji?',
            'submit_a' => '<p>Please fill out the following short form with the usernames and their category of which you would like to add to the collections. <a href="https://forms.gle/f4Jh5RpGfsHAZ5xE8" target="_blank">Collection submission form</a>',
            'mcpe_t' => 'Czy mogę użyć Skórki na Minecraft PE?',
            'mcpe' => '
                <p>Tak. Aby użyć Skórki w Minecraft Pocket Edition, wykonaj następujące czynności:</p>
                <ol>
                    <li>Otwórz SkinMC. utwórz swój smartfon i dotknij paska wyszukiwania</li>
                    <li>Wprowadź nazwę użytkownika skórki gracza, którą chcesz pobrać</li>
                    <li>Dotknij przycisku <strong>Pobierz Skórkę</strong> pod podglądem </li>
                    <li>Otwórz Minecraft PE i dotknij <strong>Profil</strong> po prawej stronie</li>
                    <li>Dotknij <strong>+</strong>lub edytuj znak i przejdź do zakładki "klasyczne skórki"</li>
                    <li>Dotknij "własne", następnie "import", następnie "wybierz nową skórkę"</li>
                </ol>',
            'change_times_t' => 'Jak często mogę zmienić nazwę użytkownika?',
            'change_times' => '<p>Możesz zmienić swoją nazwę użytkownika Minecraft <strong>raz</strong> co <strong>30 dni</strong>.</p>',
            'available_t' => 'Po zmianie nazwy użytkownika, kiedy staje się dostępna dla innych, aby go odebrać?',
            'available' => '<p>Jeśli chcesz zmienić poprzednią nazwę użytkownika, możesz zmienić <strong>po 30 dniach.</strong> Każdy inny musi poczekać dodatkowo <strong>7 dni</strong> (37 dni po zmianach) zanim będzie mógł odebrać Twoją starą nazwę użytkownika. </p>',
            'username_history_t' => 'Czy potrafisz usunąć historię mojej nazwy użytkownika?',
            'username_history' => '
                <p>Ponieważ dane historii nazwy użytkownika pochodzą z Mojang, nie można usunąć historii użytkownika. Mojang oświadczył wcześniej, że ich zamiarem było widzenie poprzednich nazw użytkowników1, oraz że stanowią one bezpośrednią metodę dostępu społeczeństwa do tych informacji2.</p>
                <p class="font-14">1<a href="https://help.minecraft.net/hc/en-us/articles/360034636712-Minecraft-Usernames" target="_blank" rel="noreferrer">https://help. rzemiosło. et/hc/en-us/articles/360034636712-Minecraft-Usernames</a></p>
                <p class="font-14 mb-0">2<a href="https://twitter.com/dinnerbone/status/554739042529849345" target="_blank" rel="noreferrer">https://twitter. om/dinnerbone/status/554739042529849345</a> (Tweet zarchiwizowany 2 lata temu: <a href="http://archive.is/TeAyj" target="_blank" rel="noreferrer">http://archive. s/TeAyj</a>)
                </p>',
        ],
    ],
    'avatars' => [
        'start' => [
            'title' => 'Stwórz swój własny awatar Minecraft',
            'subtitle' => 'Użyj generatora awatarów Minecraft, aby stworzyć zabawny awatar z dowolnej skóry!',
            'avatar_face' => 'Awatar stylu twarzy',
            'avatar_bust' => 'Awatar stylu pyłu',
            'avatar_cube' => 'Awatar stylu kostki',
            'avatar_head3d' => 'Niestandardowa głowa 3D',
        ],
        'user' => [
            'title' => 'Wybierz skórkę',
            'subtitle' => 'Wprowadź nazwę użytkownika Minecraft dla awatara, który chcesz wygenerować',
            'form_label' => 'Nazwa użytkownika Minecraft',
            'form_submit' => 'Kontynuuj',
        ],
        'output' => [
            'title' => 'Podgląd i zapisz',
            'subtitle' => 'Ciesz się swoim nowym awatarem Minecraft',
            'download_info' => 'Podoba Ci się wynik? Zacznij używać swojego nowego awatara, pobierając go tutaj',
            'download_button' => 'Pobierz awatar',
            'avatar_style' => 'Styl awatara',
            'skin_username' => 'Nazwa użytkownika skórki',
            'change' => 'Zmiana',
            'generate' => 'Wygeneruj',
            'avatar_colour' => 'Kolor tła',
            'avatar_colour_palette' => 'Paleta',
            'avatar_colour_basic' => 'Podstawowe',
        ],
        'meta' => [
            'title' => 'Generator awatarów Minecraft',
            'description' => 'Minecraft Avatar Maker: stwórz własne zdjęcia profilowe Minecraft za pomocą skórki Minecraft',
        ],
    ],
    'totem' => [
        'title' => 'Niestandardowy totem Minecraft',
        'subtitle' => 'Use the Minecraft Totem generator to create a custom resource pack with a Totem of Undying from any skin.',
        'download_info' => 'Happy with the preview? Choose your Minecraft version to save your custom resource pack:',
        'meta' => [
            'title' => 'Minecraft Custom Totem Generator',
            'description' => 'Custom Minecraft Totems: generate and create a custom Minecraft Resource Pack with a Totem of Undying using your or any other players Minecraft skin.',
        ],
        'type' => [
            'mini' => 'Mini wersja Twojej skórki!',
            'full' => 'Pełna wersja Twojej skórki!',
            'model3d' => 'Model 3D Twojej skórki!',
            'add_designs' => 'Chcesz zobaczyć więcej projektów? Prześlij swoją propozycję tutaj:'
        ]
    ],
    'achievement' => [
        'header' => [
            'title' => 'Stwórz własne osiągnięcia Minecraft',
            'subtitle' => 'Użyj Generatora Osiągnięć Minecraft, aby stworzyć swoje własne osiągnięcia i użyć pokazuj swoje postępy w każdym co Ci się podoba!',
        ],
        'generator' => [
            'yellow_text' => 'Żółty tekst',
            'white_text' => 'Biały tekst',
            'choose_icon' => 'Wybierz ikonę',
            'face' => 'Płaszczyzna Minecraft zamiast ikony',
            'form_submit' => 'Pobierz',
            'form_label' => 'Nazwa użytkownika Minecraft',
            'download' => 'Pobierz',
            'embed' => 'Osadzony',
            'embed_copy' => 'Kopiuj',
        ],
        'meta' => [
            'title' => 'Generator osiągnięć Minecraft',
            'description' => 'Wygeneruj własne osiągnięcia i awansy z Minecraft. Pobierz obrazek bezpośrednio, użyj go w podpisach forum, osadzonych w kodzie HTML lub BB i więcej',
        ],
    ],
    'armor' => [
        'header' => [
            'title' => 'Kreator stojaków na zbroję Minecraft',
            'subtitle' => 'Generate and create your very own custom Minecraft Armor Stands. Create different poses, positions, place items, and much more.',
        ],
        'meta' => [
            'title' => 'Kreator stojaków na zbroję Minecraft',
            'description' => 'Easily generate and create custom Minecraft Armor Stands. The editor helps you make different poses, positions, place items, custom skins, and much more.',
        ],
    ],
    'banner' => [
        'editor' => [
            'header' => [
                'title' => 'Edytor sztandarów Minecraft',
                'subtitle' => 'Design and create your very own custom Minecraft Banners. These can be used to decorate your world or also commonly seen used as <a href="https://optifine.net" target="_blank" rel="nofollow">Optifine</a> capes.',
            ],
            'meta' => [
                'title' => 'Kreator sztandarów Minecraft',
                'description' => 'Create and design your very own custom Minecraft Banners designs with all the patterns and colors from the game! These can be used to decorate your world or be worn as an Optifine Cape using the Banner Cape. You can generate give codes for banners or shields.',
            ],
        ],
        'gallery' => [
            'header' => [
                'title' => 'Kreator sztandarów Minecraft',
                'subtitle' => 'Browse the gallery of :count custom designed Minecraft Banners. You can use a Banner as a cape to make your Minecraft skin more unique, or use a Banner as a flag to decorate your world.',
            ],
            'meta' => [
                'title' => 'Galeria sztandarów Minecraft',
                'description' => 'Browse the gallery of :count custom designed Minecraft Banners. You can use a Banner as a cape to make your Minecraft skin more unique, or use a Banner as a flag to decorate your world.',
            ],
        ],
    ],
    'search' => [
        'meta' => [
            'title' => 'Wyniki wyszukiwania: :szukaj',
        ],
        'title' => 'Wyniki wyszukiwania',
        'results' => 'Page :current for :count result|Page :current of about :count results ',
        'time' => '(:time sekund)',
        'username_available' => 'Nazwa użytkownika dostępna*',
        'username_unavailable' => 'Nazwa użytkownika jest niedostępna',
        'username_status' => 'Status',
        'username_status_available' => 'Dostępne*',
        'username_status_unavailable' => 'Niedostępny',
        'username_searches' => 'Wyszukiwania',
        'username_searches_count' => ':count / dzień',
        'username_available_disclaimer' => '*O ile nazwa nie jest tymczasowo lub trwale zbanowana przez Mojang.',
        'no_results' => 'Nie znaleziono profili. Spróbuj wyszukać poprzez UUID, zmieniając typ wyszukiwania.',
        'no_results_tags' => 'No tagged skins found. Try searching for other tags such as "blue", "girl", "fox", etc...',
        'again' => 'Szukaj ponownie',
        'sorry' => 'Przeeepraszamy...',
        'view_profile' => 'Zobacz profil',
    ],
    'collection' => [
        'title' => 'Kolekcja skinów Minecraft',
        'subtitle' => 'Przeglądaj naszą zakleszczoną kolekcję skinów Minecraft.',
        'filters' => 'Filtry',
        'title_trending' => 'Popularne',
        'title_all' => 'Wszystkie skórki Minecraft',
        'skin_tags' => 'Oznaczone skórki',
        'filters_skin_type' => 'Typ skóry',
        'filter_skin_type_steve' => 'Typ Steve',
        'filter_skin_type_alex' => 'Typ Alex',
        'cancel' => 'Anuluj',
        'apply' => 'Zastosuj',
        'username_minecraft_skin' => 'Skórka użytkownika :username',
        'user_downloads' => '<span class="fw-500">:downloads</span> download|<span class="fw-500">:downloads</span> downloads',
    ],
    'favourites' => [
        'title' => 'Ulubione',
        'subtitle' => 'Zobacz i zarządzaj skinami, które zapisałeś później na liście ulubionych',
        'sort' => 'Sortuj według',
        'toast' => [
            'added' => 'Dodano do listy ulubionych',
            'removed' => 'Usunięto z listy ulubionych'
        ],
        'skins' => [
            'button' => 'Skórki',
            'empty_headline' => 'Brak ulubionych skórek',
            'empty_subtitle' => 'Nie masz jeszcze żadnych skórek zapisanych na liście ulubionych. Odwiedź stronę serwera i odkryj następną ulubioną!',
            'empty_browse' => 'Przeglądaj skórki',
            'meta' => [
                'title' => 'Moje ulubione skórki',
                'description' => 'Moje ulubione skórki Minecrafta',
            ],
        ],
        'servers' => [
            'button' => 'Serwery',
            'empty_headline' => 'Nie ma jeszcze ulubionych serwerów',
            'empty_subtitle' => 'Nie masz jeszcze żadnych serwerów zapisanych na liście ulubionych. Odwiedź stronę serwera i odkryj następną ulubioną!',
            'empty_browse' => 'Przeglądaj serwery',
            'meta' => [
                'title' => 'Moje ulubione serwery',
                'description' => 'Moje ulubione serwery Minecraft',
             ],
        ],

    ],
    'cape' => [
        'editor' => [
            'title' => 'Edytor pelerynek Minecraft',
            'subtitle' => 'Użyj edytora peleryn Minecraft, aby stworzyć swoją własną, niestandardową, zaprojektowaną pelerynę.',
            'meta' => [
                'title' => 'Edytor pelerynek Minecraft',
                'description' => 'Użyj edytora peleryn Minecraft, aby stworzyć swoją własną, niestandardową, zaprojektowaną pelerynę.',
            ],
        ],
        'list' => [
            'title' => 'Pelerynki Minecraft',
            'subtitle' => 'Oficjalne pelerynki gry Minecraft. Pelerynki są przedmiotami pamiątkowymi i są noszone jako dodatek do skórki gracza. Mogą również zmienić wygląd po założeniu elytry.',
            'meta' => [
                'title' => 'Lista pelerynek Minecraft',
                'description' => 'Lista peleryn Minecrafta: Zobacz wszystkie oficjalne pelerny Minecrafta w tym Mojang, Minecon, Osobiste, Specjalne i próżne',
            ],
        ],
        'detail' => [
            'title' => 'Pelerynka :cape',
            'info' => 'Informacje o pelerynie',
            'profile_list' => 'Profile z tą peleryną',
            'profiles' => ':profiles profile|:profiles profiles',
            'meta' => [
                'title' => 'Lista kapturków Minecraft',
                'description' => 'Lista ucieczki Minecrafta: Zobacz wszystkie oficjalne jaskinie Minecrafta w tym Mojang, Minecon, Osobiste, Specjalne i próżne',
            ],
        ],
        'list-custom' => [
            'title' => 'Niestandardowe peleryny Minecraft',
            'description' => 'Przeglądaj niestandardowe peleryny, które zostały stworzone i są używane przez członków SkinMC.'
        ]
    ],
    'servers' => [
        'title' => 'Serwery Minecraft',
        'subtitle' => 'Przeglądaj i przeglądaj serwery minecraft',
        'all' => 'Wszystkie serwery',
        'manage_your_servers' => 'Zarządzaj swoimi serwerami',
        'add_new_server' => 'Dodaj nowy serwer',
        'filters' => [
            'trending' => 'Popularne',
            'updated' => 'Zaktualizowano',
            'new' => 'Nowy',
            'most_viewed' => 'Najczęściej oglądane',
            'top_voted' => 'Najlepszy głos',
            'sorting' => 'Sortowanie',
            'sort_by_latest' => 'Sortuj według najnowszych',
            'sort_by_oldest' => 'Sortuj według najstarszych',
            'categories' => 'Kategorie',
            'server_location' => 'Lokalizacja serwera',
            'show_results' => 'Pokaż wyniki',
            'show_more' => 'Pokaż więcej',
            'show_less' => 'Pokaż mniej',
            'clear_filters' => 'Wyczyść filtry',
            'reviews' => 'Opinie',
            'sort_by_highest_rating' => 'Sortuj według najwyższej oceny',
            'sort_by_lowest_rating' => 'Sortuj według najniższej oceny',
            'bedrock_and_java_support' => 'Wsparcie dla Bedrock i Java'
        ],
        'review-count' => ':count Opinia|:count Opinie',
        'meta' => [
            'title' => 'Lista serwerów Minecraft',
            'description' => 'Przeglądaj i odkrywaj listę serwerów Minecraft, aby znaleźć najlepszy serwer Minecrafta! Filtruj według najnowszych, najpopularniejszych i wielu innych',
        ],
        'reviews' => [
            'meta' => [
                'title' => 'Napisz opinię',
            ],
            'editing' => 'Edytujesz swoją opinię od :date. Czy chcesz usunąć swoją recenzję?',
            'welcome' => 'Witaj :username. Jak masz ogólne doświadczenie z :servername?',
            'subtitle' => 'Pozostaw ogólny wynik swojego doświadczenia z serwerem.',
            'scale' => [
                'great' => 'Świetne',
                'good' => 'Dobrze',
                'okay' => 'Okej',
                'meh' => 'e, tam...',
                'bad' => 'Źle',
            ],
            'rate-experience' => 'Następnie oceń swoje doświadczenia w tych obszarach',
            'overall' => 'Ogólnie',
            'server-team' => 'Zespół serwera',
            'community' => 'Społeczność',
            'experience' => 'Doświadczenie',
            'availablility' => 'Czas działania i dostępność',
            'shop' => 'Sklep',
            'write-review-title' => 'Napisz opinię',
            'write-review-subtitle' => 'Pozostaw kilka notatek, możesz podkreślić co Ci się podobało, co uczyniło Twoje doświadczenie specjalnym lub zaproponować kilka sugestii.',
            'write-review-helper' => 'Write a server review to share your experience with new players, and help the server owners with feedback.',
            'write-review-tips' => 'Oto kilka porad',
            'submit-title' => 'Gotowy na przesłanie opinii?',
            'submit-subtitle' => 'Prawie gotowe!',
            'submit-review' => 'Prześlij moją opinię',
            'back' => 'Wstecz',
            'continue' => 'Kontynuuj',
            'delete-title' => 'Jesteś pewien, że chcesz usunąć swoją opinię?',
            'tos-checkbox-part-1' => 'By submitting this form you accept SkinMC\'s Terms of Service, Privacy Policy, and Community Guidelines. You also confirm that all of the information is accurate, and follows the',
            'tos-checkbox-part-2' => 'review guidelines.',
            'tos-checkbox-part-3' => 'Your review will be published after submission, but can be subject to review.'
        ],
        'slots' => 'Miejsca',
        'empty-helper' => 'You can try to do another search or',
        'empty' => 'Hmm it\'s still empty here.',
        'verified' => 'Zweryfikowany',
        'review_translate_show_original' => 'Pokaż oryginał',
        'review_translate' => 'Ocena tłumaczenia',
        'description_translate' => 'Tłumacz opis',
        'create' => [
            'welcome' => 'Witaj',
            'basics' => 'Podstawy',
            'categories' => 'Kategorie',
            'social_links' => 'Linki społecznościowe',
            'trailer_video' => 'Zwiastun wideo',
            'images' => 'Obrazy',
            'images_description' => 'You can upload photos afterwards, to showcase what your server offers.',
            'submit' => 'Prześlij',
            'lets_get_your_server_added' => 'Dodajmy Twój serwer.',
            'basics-subtitle' => 'Daj ludziom znać, o czym jest Twój serwer.',
            'description' => 'Opis',
            'description_tips' => 'Oto kilka porad',
            'description_hint' => 'Napisz dobry opis swojego serwera, aby przyciągnąć nowych graczy.',
            'categories-subtitle' => 'Wybierz kategorie dla swojego serwera',
            'missing-category' => 'Brakuje kategorii?',
            'social_links_description' => 'Where can players connect with your server on social media?',
            'trailer_video_description' => 'Showcase your server with a YouTube video.',
            'trailer_video_hint' => 'Wklej adres URL lub identyfikator wideo:',
            'ready_to_submit_your_server' => 'Gotowy do przesłania swojego serwera?',
            'review-hint' => 'After submission the team will carefully review your server listing application. Then upon decision, your server will be published, or changes requested before going live.',
            'terms' => [
                'part-1' => 'By submitting this form you are authorised to accept SkinMC\'s Terms of Service, Privacy Policy, and Community Guidelines. You also confirm that all of the information above is accurate, you have properly followed the',
                'part-2' => 'server requirements for setup',
                'part-3' => ', and that the Minecraft server is owned and managed by the entity you are representing.'
            ],
            'submit-application' => 'Submit application',
            'video-id-helper' => [
                'part-1' => 'The video ID is the string of numbers and letters after',
                'part-2' => 'For example if your video url is',
                'part-3' => ', then your video ID would be'
            ],
            'welcome_description' => 'W tym kroku zaczniemy dodawać twój serwer. Opowiedz nam trochę o nim, napisz opis, a w następnym kroku możesz przesłać jakieś zdjęcia.'
        ],
        'copy_server_ip' => 'Kopiuj IP serwera',
        'all_minecraft_servers' => 'Wszystkie serwery Minecraft',
        'promo' => [
            'title' => 'Czy prowadzisz serwer Minecraft?',
            'ready_to_list_your_server' => 'Ready to list your Server?',
            'everything_you_need' => 'Everything you need to grow your server',
            'list_your_server' => 'List your server',
            'list_your_server_description' => 'Create a listing for your server, add photos, social media and more.',
            'find_players' => 'Znajdź graczy',
            'find_players_description' => 'Find and reach new players to join your server and grow your community.',
            'get_reviews' => 'Uzyskaj recenzje',
            'get_reviews_description' => 'Ask your community to review your server, and reward them in game.',
            'why_list_on_skinmc' => 'Why you should list your Server on SkinMC',
            'others' => 'Inne',
            'quality_check_and_confirmation' => 'Quality check and confirmation',
            'quality_check_description' => 'Our team reviews every server to ensure quality.',
            'verified_players' => 'Reviews from verified Minecraft players',
            'verified_players_description' => 'Collect authentic player reviews from legitimate accounts with Votifier integration.',
            'international' => 'International',
            'international_description' => 'With translation features your listing is available to more players.',
            'server_listing_page' => 'Powerful Server listing page',
            'server_listing_page_description' => 'Add photos, description texts, youtube videos, and highlight why players should join your server.',
            'social_connections' => 'Social media connections',
            'social_connections_description' => 'Connect your Servers social accounts and show new players where they can find you.',
            'verified_badge' => 'Verification badge',
            'verified_badge_description' => 'Authentic servers can apply for a verification badge.',
            'owner_profile' => 'Owner profile',
            'owner_profile_description' => 'Add a personal touch, by completing your custom profile.',
            'categories' => 'Categories',
            'categories_description' => 'Different categories to make it easier to find your server.',
            'vote' => 'Vote',
            'vote_description' => 'Ask users to vote for your server.',
            'fair_listings' => 'Fair listings',
            'fair_listings_description' => 'Server listings can not be artificially boosted in results on SkinMC.',
            'support' => '24h support',
            'support_description' => 'Do you need help or have questions? You can always reach out and receive a fast reply.',
            'custom_features' => 'Custom features',
            'custom_features_description' => 'Missing a feature for your server? Open a ticket, and we\'ll implement it.',
            'faq' => [
                'title' => 'Answers to your questions',
                'suited-question' => 'Is my Minecraft Server suited for SkinMC?',
                'suited-answer' => 'Minecraft Players on SkinMC love to discover new experiences, content and engage with communities. On the platform you\'ll find a large variety of different, unique, fun Minecraft servers. From a large network to even a small survival server, it can make someones day!',
                'get-started-question' => 'How do I get started?',
                'get-started-answer' => 'Adding your Minecraft Server to the SkinMC Server List is very easy! You will first need to create an account, if you haven\'t already, and then follow the setup guide to get your server listed. Add a few photos and a nice description, and your server will be published in no time!',
                'players-question' => 'How can I get more players on my Minecraft Server?',
                'players-answer' => 'Building a community is the most crucial part of a long lasting Minecraft Server. Use the Minecraft Server List on SkinMC to find a new audience and continue to build your community. Ask your players to recommend your Server, or share your listing on social media platforms. Collecting good reviews can also play an important role to a great Server listing presence that attracts new players.',
                'more-question' => 'I have more questions. Where can I get help?',
                'more-answer' => 'You can reach out to SkinMC at any time, 24 hours, by using either the help button, the help desk, or by joining the Discord server.'
            ],
            'ready_to_list_description' => 'Add your Minecraft Server to the SkinMC Server List in just a few minutes. If you need any help, you can reach out around the clock and receive answers quickly.'
        ],
        'manage' => [
            'index' => [
                'welcome' => 'Welcome back, :username',
                'your_servers' => 'Twoje serwery',
                'reviews_today' => 'Reviews today',
                'no_reviews_today' => 'No reviews today',
                'no_reviews_text' => 'Your servers haven\'t received any reviews today. Why not ask your players to leave one?',
                'tips' => [
                    'title' => 'Wskazówki',
                    'description-title' => 'Write a good server description',
                    'description-body' => 'Helpful tips and advice to write a great server description.',
                    'images-title' => 'Adding server images',
                    'images-body' => 'Make your server listing stand out with great images.'
                ]
            ],
            'listings' => [
                'title' => 'Your Minecraft servers (:count)'
            ],
            'insights' => [
                'title' => 'Insights'
            ],
            'edit_server' => 'Edytuj serwer',
            'listing' => 'Listing',
            'to_do' => 'To do',
            'last_update' => 'Ostatnia aktualizacja',
            'add_more_photos_to_publish' => 'Add more photos to publish',
            'looks_empty_here' => 'Looks empty here.',
            'get_started_by_adding_a_new_server' => 'Get started by adding a new server?'
        ],
        'status' => [
            'approved' => 'Zatwierdzono',
            'pending_approval' => 'Oczekuje na zatwierdzenie',
            'published' => 'Opublikowano',
            'in_review' => 'W trakcie weryfikacji'
        ]
    ],
    'editor' => [
        'import' => [
            'title' => 'Importuj skórkę',
            'import_by_username' => 'Import by username',
            'import_button' => 'Importuj',
            'drag' => 'Drag and drop a skin here, or click',
            'click' => 'Select image'
        ],
        'download' => [
            'error' => [
                'no-data' => 'No skin data was provided. Please try again.',
                'invalid-format' => 'The skin data format is invalid. Please try again.',
                'invalid-data' => 'The skin data is corrupted. Please try again.',
                'generic' => 'Something went wrong while downloading your skin. Please try again.',
            ],
        ],
        'draw' => 'Rysuj',
        'eyedropper' => 'Eyedropper',
        'fill' => 'Wypełnij',
        'move' => 'Move',
        'decrease_brightness' => 'Decrease brightness',
        'increase_brightness' => 'Increase brightness',
        'erase' => 'Gumka',
        'undo' => 'Krok wstecz (CTRL+Z)',
        'redo' => 'Krok naprzód (CTRL+Y)',
        'default_view' => 'Widok domyślny',
        'zoom_in' => 'Powiększenie (CTRL +)',
        'zoom_out' => 'Pomniejszenie (CTRL -)',
        'saved' => 'Ostatnio zapisane przed chwilą',
        'saving' => 'Automatyczne zapisywanie...',
        'save_error' => 'Wystąpił błąd',
        'new_skin' => 'Nowa skórka',
        'previous_skins' => 'Poprzednia skórka',
        'backed_up_title' => 'Automatically saved skins',
        'backed_up_info' => 'Temporarily backed up to your local storage.',
        'backed_up_empty_title' => 'It\'s empty here',
        'backed_up_empty_info' => 'Once you start editing skins you\'ll see your 32 last edited skins here.',
        'backed_up_skins_count' => 'of 32 skin backups used',
        'backed_up_skins_count_info' => 'You can back up to up 32 skins. Once you reach 32 skins an older skin will be replaced with a new one.',
        'layers' => 'Warstwa',
        'body' => [
            'title' => 'Ciało',
            'overlay' => 'Overlay',
            'head' => 'Głowa',
            'torso' => 'Tułów',
            'l_arm' => 'Lewe ramię',
            'r_arm' => 'Prawe ramię',
            'l_leg' => 'Lewa noga',
            'r_leg' => 'Prawa noga',
        ],
        'model' => 'Wzór',
        'steve' => 'Steve',
        'alex' => 'Alex',
        'stance' => [
            'title' => 'Położenie',
            'default' => 'Domyślne',
            'walk' => 'Chodzenie',
            'run' => 'Bieg',
            'hug' => 'T-pose',
            'fly' => 'Lot',
        ],
        'fullscreen' => 'Fullscreen',
        'fullscreen_exit' => 'Exit fullscreen',
        'grid' => 'Siatka',
        'show_grid' => 'Pokaż siatkę',
        'download' => [
            'title' => 'Zapisz i Pobierz',
            'subtitle' => 'Konto SkinMC',
            'description' => 'Czy chcesz utworzyć darmowe konto SkinMC, aby zapisać skórkę i przyszłe w chmurze?',
            'start_description' => 'Rozpocznij pobieranie bezpośrednio bez zapisywania do chmury',
            'start' => 'Pobierz skórkę',
        ],
        'help' => [
            'title' => 'Minecraft Skin Editor',
            'about' => 'Create and edit your custom Minecraft Skin easily with the SkinMC Editor. You can choose between Steve and Alex models, import skins from a file or username, and create your very own Minecraft Skin.',
            'draw' => 'Draw using the pen tool. Select a colour from the swatch to use with it.',
            'eyedropper' => 'Use the eyedropper to select a colour from your skin and add it to your current palette.',
            'fill' => 'Fill entire areas of your skin using the fill tool. Select a colour before using fill.',
            'move' => 'Pan and move around the skin editor canvas with the move tool.',
            'decrease_brightness' => 'Decrease the brightness of the currently active colour.',
            'increase_brightness' => 'Increase the brightness of the currently active colour.',
            'erase' => 'Erase pixels drawn on the secondary overlay layer.',
        ],
    ],
    'account' => [
        'level' => 'Level',
        'level_history' => 'Level history',
        'xp' => 'XP',
        'my_xp' => 'My XP',
        'xp_to_next_level' => ':xp XP to next level',
        'xp_info' => 'What are XP?',
        'xp_info_tooltip' => 'XP is earned for various activities such as adding tags to skins, inviting friends, commenting, and much more. With each XP earned you can level up and unlock cool things!',
        'settings' => [
            'title' => 'Konto',
            'show_profile' => 'Przejdź do profilu',
            'friends' => 'Znajomi',
            'friends_detail' => 'Pozostań połączony, korzystając z listy znajomych na SkinMC.',
            'security' => 'Bezpieczeństwo',
            'security_detail' => 'Zaktualizuj hasło logowania i upewnij się, że Twoje konto jest bezpieczne',
            'social' => 'Konta mediów społecznościowych',
            'social_detail' => 'Dostosuj swój profil dodając swoje media społecznościowe',
            'link' => 'Połącz konto Minecraft',
            'link_detail' => 'Połącz swoje konto Minecraft i włącz swój profil.',
            'logout' => 'Czy chcesz wylogować się ze swojego konta SkinMC?',
            'automatic_backups' => 'Automatic skin backups',
            'automatic_backups_info' => 'As a SkinMC plus member your skins are backed up daily.',
        ],
        'capes' => [
            'title' => 'Peleryna Minecraft SkinMC',
            'description' => 'Wear any cape you wish in-game with SkinMC Capes for free.',
            'drop' => 'Przeciągnij i upuść peleryne tutaj',
            'drop-hint' => 'Wymiary 64x32px',
            'select' => 'Wybierz obraz',
            'upload-cape' => 'Prześlij i użyj peleryny',
            'save-and-use' => 'Zapisz i użyj',
            'uploaded-cape' => 'Przesłana peleryna',
            'no-cape' => 'Brak peleryny',
            'remove-cape' => 'Usuń pelerynę',
            'download' => 'Download the SkinMC Mod to see your and other players capes in-game.',
            'learn-more' => 'Dowiedz się więcej',
            'link-account' => 'Please link your Minecraft account to upload a cape.',
            'updated' => 'Twoja peleryna została zaktualizowana!',
            'removed' => 'Twoja peleryna została usunięta.',
            'active' => 'Twoja peleryna jest aktywowana!'
        ],
        'favourite' => 'Ulubione',
        'remove_favourite' => 'Usuń z ulubionych',
        'added_to_favourites' => 'Added to favourites',
        'removed_from_favourites' => 'Removed from favourites',
        'welcome' => 'Nice to see you!',
        'view-profile' => 'Zobacz profil',
        'security' => [
            'title' => 'Bezpieczeństwo',
            'email' => 'Adres e-mail',
            'email-title' => 'Update your email address.',
            'save' => 'Zapisz',
            'password' => 'Hasło',
            'password-title' => 'Change your password at any time.',
            'social-provider' => 'To update your account information, such as your password, please visit your login provider:',
            'social-provider-email' => 'Your associated email address with your login provider',
            'social-provider-connected' => 'Currently connected login providers',
            'current-password' => 'Aktualne hasło',
            'forgot' => 'Zapomniałeś hasła?',
            'edit' => 'Edytuj',
            'delete' => 'Usuń moje konto',
            'account-deletion' => 'Delete your SkinMC account.',
            'delete-info' => 'Please confirm to continue',
            'delete-confirmation' => 'Deleting your account is irreversible. All your personal information and content such as posts, favourites, uploaded capes, customisations, etc. will be deleted and can not be recovered.',
            'delete-confirmation-info' => 'Enter your password to continue',
            'yes-confirm-delete' => 'Tak, potwierdź usunięcie',
            'account-successfully-deleted' => 'Your account and data has been successfully deleted.'
        ],
        'social' => [
            'title' => 'Konta społecznościowe',
            'edit' => 'Edytuj',
            'save' => 'Zapisz',
            'link-account' => 'Link your Minecraft account to SkinMC to display your social links on your profile.',
            'finish-setup' => 'Finish setup',
            'connect-account' => 'Connect your accounts',
            'connect-description' => 'Choose which accounts you wish to connect and unlock special SkinMC integrations.',
            'empty' => 'No accounts added',
            'empty-description' => 'Your social media accounts will show up here and on your public profile. Once added they will add more personalisation to your page as well as enable integrations.',
            'connect' => 'Połącz',
            'username' => 'username',
            'spotify' => 'Add your Spotify username to show your Spotify information on your profile.',
            'discord' => 'Enter your Discord username and number to display your Discord information on your SkinMC profile.',
            'youtube' => 'Add your YouTube channel to SkinMC which will display your YouTube channel on your profile.',
            'youtube-format' => 'Use the following format depending on your channel link:',
            'twitter' => 'Enter your X (formerly Twitter) username to display it on your profile.',
            'bluesky' => 'Enter your Bluesky handle e.g. username.bsky.social to display your Bluesky profile on your profile.',
            'twitch' => 'Enter your Twitch username to display your Twitch channel on your profile.',
            'reddit' => 'Enter your Reddit username to display your Reddit profile on your profile.',
            'github' => 'Enter your GitHub username to display your GitHub profile on your profile.',
            'telegram' => 'Enter your Telegram username to display your Telegram link on your profile.',
            'tiktok' => 'Enter your TikTok username to display your TikTok profile on your profile.',
            'snapchat' => 'Enter your Snapchat username to display your Snapchat profile on your profile.',
            'instagram' => 'Enter your Instagram username to display your Instagram profile on your profile.',
            'facebook' => 'Enter your Facebook username to display your Facebook profile on your profile.',
            'includes_skinmc_plus_benefits' => 'Includes SkinMC plus benefits',
        ],
        'recover' => [
            'title' => 'Odzyskaj swoje konto',
            'subtitle' => 'Wprowadź nowe hasło i potwierdź aby zakończyć odzyskiwanie konta.',
            'new_password' => 'Nowe hasło',
            'repeat_new_password' => 'Powtórz nowe hasło',
            'submit' => 'Odzyskaj konto',
        ],
        'customise' => [
            'title' => 'Dostosuj swój profil',
            'description' => 'Add your social media, choose an emoji, set your location and more',
            'information' => 'Informacje',
            'preview' => 'Podgląd',
            'location' => [
                'title' => 'Lokalizacja',
                'description' => 'Choose which location you would like to add to your profile.',
            ],
            'biography' => [
                'title' => 'O mnie',
                'description' => 'Napisz bio dla swojego profilu.',
            ],
            'status' => 'Status',
            'status-toggle' => 'Pokaż mój status online',
            'emoji' => 'Emoji',
            'name-history-toggle' => 'Make username history private',
            'name-history-info' => 'Your Minecraft username history is currently',
            'name-history-toggle-on' => 'private',
            'name-history-toggle-off' => 'public',
            'theme' => 'Motyw profilu',
            'theme-primary' => 'Primary',
            'theme-secondary' => 'Secondary',
            'appearance' => 'Appearance',
        ],
        'link' => [
            'manage' => 'Zarządzaj połączonym kontem Minecraft',
            'description' => 'Zobacz i zarządzaj swoim połączonym kontem Minecraft',
            'title' => 'Linked Minecraft account',
            'current' => 'Currently linked Minecraft account.',
            'status' => 'You now have full access to all SkinMC features!',
            'linked' => 'Połączone',
            'disconnect' => 'Rozłącz',
            'disconnect-title' => 'Odłącz konto Minecraft',
            'disconnect-info' => 'Are you sure you would like to disconnect your Minecraft account?',
            'disconnect-features' => 'You will lose access to commenting, customisation and other features which require a linked Minecraft account. To use these again you will be required to link a Minecraft account.',
            'disconnect-following' => 'Disconnecting your Minecraft account will permanently remove all your followed profiles.',
            'disconnect-posts' => 'Your created feed posts and liked will be deleted.',
            'can-not-undo' => 'This can\'t be undone.',
            'are-you-sure' => 'Czy jesteś pewien?',
            'confirm' => 'Tak, potwierdź odłączenie',
            'cancel' => 'Nie, anuluj',
            'success' => 'Your account was successfully disconnected!'
        ],
        'finish-setup' => [
            'title' => 'Finish account setup',
            'description' => 'Finish setting up your account, and get full access to all features by linking your Minecraft account to SkinMC.',
            'link' => 'Połącz konto Minecraft',
            'get-started' => 'Rozpocznij',
            'skip' => 'Pomiń',
            'claim' => 'Claim your profile',
            'customise' => 'Customise your page',
            'social' => 'Dodaj linki społecznościowe',
            'comment' => 'Access to comment system',
            'direct_message' => 'Send direct messages',
            'feed' => 'Post status updates to the feed',
            'follow' => 'Follow your friends',
            'badge' => 'Badge displayed on your profile',
            'cape' => 'Własna peleryna Minecraft',
            'backup' => 'Automatic skin backup',
            'more' => 'I więcej...'
        ],
        'skins' => [
            'title' => 'Zarządzaj skórkami',
            'toggle' => 'Widoczność skórki przełączona',
        ],
        'invite' => [
            'title' => 'Moje zaproszenia',
            'headline' => 'Zaproś znajomych',
            'info' => 'Create an invite code to share with your friend. Once they accept it, you\'ll both earn some extra XP!',
            'description' => 'Create an invite for your friends and you\'ll both earn some extra XP.',
            'generate' => 'Utwórz kod zaproszenia',
            'empty' => 'You haven\'t created any invites yet.',
            'code' => 'Kod',
            'expiry' => 'Each code works once.',
            'status' => [
                'title' => 'Status',
                'pending' => 'Oczekujące',
                'accepted' => 'Zaakceptowano'
            ],
            'add_invite' => [
                'button' => 'Masz zaproszenie?',
                'title' => 'Dodaj kod zaproszenia',
                'redeem' => 'Zrealizuj zaproszenie',
            ],
            'share' => 'Wyślij znajomemu link z zaproszeniem'
        ],
        'emoji' => [
            'title' => 'SkinMC Emoji',
            'introducing' => 'Introducing',
            'info' => 'Customise your profile with emoji. Unlock more as you level up.',
            'unlocked_at' => 'Unlocked at level :level',
            'unlocks_at' => 'Reach level :level to unlock',
            'turn_off' => 'Show emoji'
        ]
    ],
    'notifications' => [
        'title' => 'Powiadomienia',
        'view_all' => 'Zobacz wszystkie',
        'view_all_notifications' => 'Zobacz wszystkie powiadomienia',
        'image' => 'Notification photo',
        'archived' => 'Zarchiwizowane',
        'inbox' => 'Wiadomości',
        'empty' => [
            'title' => 'You\'re up to date!',
            'text' => 'New notifications will show up here.',
            'text-archived' => 'Archived notifications will show up here.',
        ],
        'action' => [
            'archive' => 'Move to archive',
            'unarchive' => 'Unarchive',
            'open' => 'Tap to open',
        ],
        'toast' => [
            'archive' => 'Powiadomienie przeniesione do archiwum',
            'unarchive' => 'Powiadomienie przeniesione do skrzynki odbiorczej',
            'undo' => 'Cofnij',
        ]
    ],
    'error' => [
        'offline' => [
            'title' => 'Brak internetu',
            'subtitle' => 'Twój internet został rozłączony. Sprawdź swoje połączenie i odśwież stronę, aby spróbować ponownie.',
            'try_again' => 'Try again'
        ],
        '404' => [
            'title' => '404 — Page not found.',
            'subtitle' => 'Hm, it looks like nothing was found at this location. Maybe try going back, or start a new search?',
            'try_again' => 'Back home'
        ],
    ],
    'heads' => [
        'list' => [
            'meta' => [
                'title' => 'Minecraft heads database',
                'description' => 'Explore the database of Minecraft heads to decorate your world with, or generate your own give command. View official heads, player heads and custom heads that feature textures which never change.'
            ],
            'header' => [
                'title' => 'Głowy Minecraft',
                'subtitle' => 'Explore our database of Minecraft heads to decorate your world, or generate your own give command. Player heads show the current skin worn by a user, and can change as the user updates their skin. Custom heads are linked to the Mojang skin file and never change. Custom heads must be summoned using a command block as the command is very long.',
            ],
            'count' => [
                'heads' => ':heads head|:heads heads',
            ],
            'customheads' => [
                'title' => 'Custom heads',
                'description' => 'Custom heads use the direct path to the texture file on the Mojang servers. Hence textures will never be deleted and the heads never change.',
                'version' => 'Minecraft 1.8 or later',
            ],
            'playerheads' => [
                'title' => 'Player heads',
                'description' => 'Player heads use the current skin texture of a Minecraft player. As they are username based, when the player changes their name or skin, the head changes.',
                'version' => 'All Minecraft versions',
            ]
        ],
    ],
    'mod' => [
        'title' => 'SkinMC Mod: Darmowe niestandardowe peleryny',
        'headline' => 'Introducing the SkinMC Mod for more customisation',
        'description' => 'Giving back to the Minecraft community, with a free mod which enables players more customisation with custom capes, available and visible for anyone using the mod.',
        'download' => 'Pobierz teraz',
        'download-title' => 'Pobierz modyfikację',
        'requires' => 'Wymaga',
        'select-version' => 'Wybierz swoją wersję Minecraft',
        'get-started' => 'Rozpoczęcie jest proste',
        'step-1' => '1. Zdobądź modyfikację',
        'step-1-detail' => 'Zainstaluj Fabric, a następnie pobierz mod dla swojej wersji gry i zainstaluj go poprzez umieszczenie jar w folderze mods.',
        'step-2' => '2. Połącz swoje konto',
        'step-2-detail' => 'Jeśli jeszcze tego nie zrobiłeś, zarejestruj się i podłącz swoje konto Minecraft z SkinMC.',
        'step-3' => '3. Prześlij swoją pelerynę',
        'step-3-detail' => 'Przejdź do swojego konta i prześlij swoją własną pelerynę. Będzie ona widoczna w grze.',
        'all-versions' => 'Wszystkie wersje',
        'latest' => 'Najnowsze',
        'logged-in' => 'Prześlij swoją pelerynę',
        'mirror' => 'Mirror',
        'download-via' => 'Pobierz przez:',
        'curseforge' => 'CurseForge',
    ],
    'app' => [
        'title' => 'Aplikacja SkinMC na Androida',
        'headline' => 'Przywitaj się z aplikacją SkinMC na Androida.',
        'play-store-attribution' => 'Google Play i logo Google Play są znakami towarowymi firmy Google LLC.',
        'features' => 'Convenient features for on the go',
        'feature-qr' => 'Built in QR-Code scanner',
        'feature-qr-detail' => 'Use the built in QR-Code scanner to easily get a skin from your Desktop to the app, or scan your friends custom profile QR-Code.',
        'feature-files' => 'Saves directly to files',
        'feature-files-detail' => 'With the usage of Android Files Manager, the app can conveniently save Skins, making it easier to apply in Bedrock Edition.',
        'feature-noads' => 'Brak reklam',
        'feature-noads-detail' => 'A clean designed interface, without distractions. Enjoy an Ad-free experience without intrusive annoyances from web to app.',
        'feature-experience' => 'Doświadczenie',
        'feature-experience-detail' => 'Enjoy the full SkinMC experience anywhere, with added features. Customise your profile, add your bio, create a fun QR-Code and more!',
        'get-app-headline' => 'Pobierz aplikację SkinMC',
        'get-app-detail' => 'Your very own Minecraft companion for your Android — available for free.'
    ],
    'random' => [
        'title' => 'Ładowanie losowej skórki Minecraft',
        'description' => 'Ładowanie losowej skórki Minecraft',
        'headline' => 'Proszę czekać...',
        'redirect' => 'You will be automatically redirected. Page not loading?',
        'click-here' => 'Kliknij tutaj',
        'messages' => [
            '1' => 'Ładowanie losowej skórki Minecraft...',
            '2' => 'Kopanie w dół...',
            '3' => 'Creeper, aw man...',
            '4' => 'Searching through chests...',
            '5' => 'Did you know the coming skin is completely random?',
            '6' => 'Random skin incoming...',
            '7' => 'Jeszcze jeden blok...',
            '8' => 'Sortowanie ekwipunku...',
            '9' => 'Crafting diamond pickaxe...',
            '10' => 'Szukam Herobrine...',
        ],
    ],
    'feed' => [
        'title' => 'Strumień',
        'following' => 'Obserwujesz',
        'sign-up' => 'Sign up or log in to join the conversation.',
        'link-account' => 'Link your Minecraft account to join the conversation.',
        'placeholder' => 'What is happening?',
        'audience' => 'Audience',
        'audience-title' => 'Kto może to zobaczyć?',
        'everyone' => 'Wszyscy',
        'everyone-info' => 'Anyone on or off SkinMC.',
        'followers' => 'Obserwujący',
        'followers-info' => 'Signed in or members following me.',
        'private' => 'Tylko ja',
        'private-info' => 'Private post only I can see.',
        'submit' => 'Wyślij',
        'like' => 'Polub',
        'comment' => 'Odpowiedz',
        'share' => 'Udostępnij',
        'remaining' => 'Remaining',
        'profile' => 'Posts by :username',
        'posts' => 'Wszystkie posty',
        'my-posts' => 'Moje posty',
        'view-all' => 'Zobacz wszystkie posty',
        'post' => [
            'meta' => ':username on SkinMC: :text',
            'title' => 'Post',
            'created' => 'Status update posted!',
            'confirm-delete' => 'Are you sure you would like to delete this post? It can not be undone.',
            'delete' => 'Usuń post',
            'deleted' => 'Twój post został usunięty.',
        ],
        'repost' => [
            'button' => 'Repost',
            'quote_button' => 'Quote',
            'title' => 'Repost this post',
            'quote_title' => 'Quote post',
            'quote_label' => 'Add a comment (optional)',
            'quote_placeholder' => 'Add your thoughts...',
            'reposted' => 'reposted',
            'success' => 'Reposted!',
            'removed' => 'Repost removed.',
            'already_reposted' => 'You have already reposted this.',
            'undo' => 'Undo repost',
            'original_deleted' => 'The original post has been deleted.',
            'deleted_post' => 'This post has been deleted',
        ],
        'poll' => [
            'title' => 'Poll',
            'create' => 'Create a poll',
            'option' => 'Option',
            'add_option' => 'Add option',
            'duration' => 'Duration',
            'duration_1' => '1 day',
            'duration_3' => '3 days',
            'duration_7' => '7 days',
            'votes' => '{0} votes|{1} vote|[2,*] votes',
            'ended' => 'Poll ended',
            'ends_in' => 'Ends :time',
            'login_required' => 'Sign in to vote',
        ],
        'gif' => [
            'title' => 'GIF',
            'search_placeholder' => 'Search KLIPY for GIFs...',
            'no_results' => 'No GIFs found',
            'powered_by' => 'Powered by',
            'categories' => 'Categories',
            'trending' => 'Trending',
        ],
        'media' => 'Media',
        'follow-suggestions' => 'Obserwuj zespół',
        'explore' => 'Odkrywaj',
        'hashtag' => 'Hashtag',
        'stories' => [
            'archive' => [
                'title' => 'Story Archive',
                'subtitle' => 'Your archived stories are only visible to you',
                'empty' => 'No archived stories yet',
                'empty-description' => 'Stories you post will appear here after 24 hours.',
                'action' => 'Archive',
                'archived' => 'Story moved to archive.',
                'already-archived' => 'Story is already archived.',
            ],
        ],
    ],
    'private' => [
        'title' => 'Prywatne posty',
        'text' => 'Ten post jest prywatny.'
    ] ,
    'liked' => [
        'title' => 'Polubione'
    ],
    'following' => [
        'title' => 'Following',
        'text' => 'Zaloguj się, aby zobaczyć ten post.'
    ],
    'tags' => [
        'empty' => 'No tags to vote on yet',
        'empty-subtitle' => 'Be the first to add one',
    ],
    'inbox' => [
        'title' => 'Wiadomości',
        'details' => 'Szczegóły',
        'message_user' => 'Wiadomość',
        'write_message' => 'Napisz wiadomość',
        'empty' => [
            'no_message_selected' => 'Nie wybrano wiadomości',
            'open_or_start_conversation' => 'Open a conversation from the message list, or start a new one.',
            'no_messages' => 'Brak nieprzeczytanych wiadomości',
            'start_conversation' => 'Once you start a new conversation, your messages will be displayed here.',
            'conversation' => 'This is the beginning of your conversation with :username.',
            'users' => 'Unable to find any users that match the current query.'
        ],
        'typing' => ':username is typing...',
        'new_message' => 'Nowa wiadomość',
        'mark_unread' => 'Oznacz jako nieprzeczytane',
        'send_message' => 'Wyślij wiadomość',
        'delete_message' => 'Delete message for you',
        'latest_conversations' => 'Ostatnie konwersacje',
        'delete_conversation' => 'Usuń konwersację',
        'show_details' => 'Pokaż szczegóły',
        'hide_details' => 'Ukryj szczegóły',
        'unread' => 'Nieprzeczytane',
        'deleted' => 'Usunięte',
        'report_message' => 'Zgłoś wiadomość',
        'add_reaction' => 'Dodaj reakcję',
        'today' => 'Dzisiaj',
        'reconnect' => 'Please reconnect your Minecraft account to chat',
        'account_disconnected' => 'This user disconnected their linked Minecraft account.',
        'saved_messages' => 'Zapisane wiadomości',
        'new_message_to_label' => 'Do',
        'external-link-to' => 'Ten link zabierze Cię do',
        'external-link-confirmation' => 'Czy na pewno chcesz tam iść?',
        'external-link' => 'Link zewnętrzny',
        'reply' => 'Reply'
    ],
    'server' => [
        'manage' => [
            'stats' => 'Statystyki'
        ]
    ],
    'report' => [
        'button' => 'Report',
        'title' => 'Report content',
        'describe' => 'Briefly describe why you are reporting this',
        'select' => 'Select report reason',
        'submit' => 'Submit report',
        'reasons' => [
            'INAPPROPRIATE_CONTENT' => 'Inappropriate content',
            'SPAM' => 'Spam',
            'HARASSMENT' => 'Harassment',
            'OTHER' => 'Other',
        ]
    ],
    'leaderboard' => [
        'title' => 'Leaderboard',
        'description' => 'View the SkinMC leaderboard of users.',
        'headline' => 'Top 10',
        'all-time-invites' => 'All time invites',
        'all-time-xp' => 'All time XP',
        '30-day-xp' => '30 days XP'
    ],
];
