<?php

return [
    'skins' => 'Ulkoasut',
    'avatars' => 'Hahmot',
    'editor' => 'Muokkain',
    'heads' => 'Heads',
    'capes' => 'Merkit',
    'servers' => 'Palvelimet',
    'achievement' => 'Saavutus',
    'armor' => 'Armor stand',
    'banners' => 'Banners',
    'profile' => 'My profile',

    'generators' => 'Generators',

    'logout' => 'Kirjaudu ulos',
    'register' => 'Rekisteröidy nyt',
    'login' => 'Kirjaudu sisään',
    'about' => 'Tietoja',
    'contact' => 'Contact',
    'faqs' => 'UKK',

    'minecraft_name' => 'Minecraftin Nimi',
    'minecraft_uuid' => 'Minecraft UUID',
    'what' => 'What',
    'recent_searches' => 'Viimeisimmät haut',
    'username' => 'Username',
    'uuid' => 'UUID',
    'search' => 'Etsi',
    'search_placeholder' => 'Kokeile',
    'search_placeholder_uuid' => 'Enter UUID',
    'start_search' => 'Aloita haku',
    'cancel_search' => 'Peruuta',
    'search_type' => 'Etsi tyyppi',
    'search_type_all' => 'All results',
    'profiles' => 'Profiles',
    'view_skin' => 'Näytä ulkoasu',
    'edit_skin' => 'Muokkaa ulkoasua',
    'make_avatar' => 'Tee profiilikuva',
    'find_heads' => 'Find player heads',

    'home' => 'Koti',
    'help' => 'Ohje',
    'tools' => 'Työkalut',
    'more-tools' => 'More tools',
    'skin_viewer' => 'Ulkoasun katselin',
    'avatar_maker' => 'Hahmon valmistaja',
    'collections' => 'Kokoelmat',
    'popular_skins' => 'Suositut nahat',
    'cartoon_skins' => 'Sarjakuvan nahat',
    'animal_skins' => 'Eläinten nahat',
    'community' => 'Yhteisö',
    'imprint' => 'Jälki',
    'cookies' => 'Evästeet',
    'terms' => 'Terms of Service',
    'privacy' => 'Privacy policy',
    'app' => 'App',
    'mod' => 'Mod',
    'totem' => 'Totems',

    'feedback' => 'Feedback',
    'status' => 'Status',
    'recent_searches_placeholder' => 'As you start searching, your past searches will show here.',
    'recent_views_placeholder' => 'After visiting some profiles, your past visited ones will show here.',
    'moderate' => 'Moderate',
    'listings' => 'Listings',
    'add' => 'Add',

    'theme' => [
        'dark' => 'Dark',
        'light' => 'Light',
        'auto' => 'Automatic'
    ],
];
