<?php

return [
    'skins' => 'Skinit',
    'avatars' => 'Profiilikuvat',
    'editor' => 'Muokkaaja',
    'heads' => 'Päät',
    'capes' => 'Viitat',
    'servers' => 'Palvelimet',
    'achievement' => 'Saavutus',
    'armor' => 'Haarniskateline',
    'banners' => 'Bannerit',
    'banner' => 'Banner Editor',
    'profile' => 'Profiilini',

    'generators' => 'Generaattorit',

    // Navigation dropdowns
    'feed' => 'Feed',
    'discover' => 'Discover',
    'mods' => 'Mods',
    'shaders' => 'Shaders',
    'resource_packs' => 'Resource Packs',
    'modpacks' => 'Modpacks',
    'datapacks' => 'Data Packs',
    'plugins' => 'Plugins',

    'logout' => 'Kirjaudu ulos',
    'register' => 'Rekisteröidy nyt',
    'login' => 'Kirjaudu sisään',
    'about' => 'Tietoja',
    'contact' => 'Yhteystiedot',
    'faqs' => 'UKK',

    'minecraft_name' => 'Minecraftin Nimi',
    'minecraft_uuid' => 'Minecraft UUID',
    'what' => 'Mitä',
    'recent_searches' => 'Viimeisimmät haut',
    'username' => 'Käyttäjänimi',
    'uuid' => 'UUID',
    'search' => 'Etsi',
    'search_placeholder' => 'Kokeile',
    'search_placeholder_uuid' => 'Syötä UUID',
    'start_search' => 'Aloita haku',
    'cancel_search' => 'Peruuta',
    'search_type' => 'Etsi tyyppi',
    'search_type_all' => 'Kaikki tulokset',
    'profiles' => 'Profiilit',
    'view_skin' => 'Näytä ulkoasu',
    'edit_skin' => 'Muokkaa ulkoasua',
    'make_avatar' => 'Tee profiilikuva',
    'find_heads' => 'Etsi pelaajan päät',
    'no_results_found' => 'No suggestions yet. Hit Enter to look it up.',

    'home' => 'Koti',
    'help' => 'Ohje',
    'tools' => 'Työkalut',
    'more-tools' => 'Lisää työkaluja',
    'skin_viewer' => 'Skinin katselu',
    'avatar_maker' => 'Profiilikuva luoja',
    'collections' => 'Kokoelmat',
    'popular_skins' => 'Suositut nahat',
    'cartoon_skins' => 'Sarjakuvan nahat',
    'animal_skins' => 'Eläinten nahat',
    'community' => 'Yhteisö',
    'imprint' => 'Jälki',
    'cookies' => 'Evästeet',
    'terms' => 'Käyttöehdot',
    'privacy' => 'Tietosuojakäytäntö',
    'app' => 'Sovellus',
    'mod' => 'Modi',
    'totem' => 'Toteemit',
    'cube' => 'Cube',
    'new' => 'New',

    'feedback' => 'Palaute',
    'status' => 'Tila',
    'recent_searches_placeholder' => 'Kun aloitat haun, aiemmat haut näkyvät tässä.',
    'recent_views_placeholder' => 'Joillakin profiileilla vierailtuasi, aiemmin vieraillut profiilit näkyvät tässä.',
    'moderate' => 'Kohtalainen',
    'listings' => 'Listaukset',
    'add' => 'Lisää',

    // Autocomplete types
    'autocomplete' => [
        'profile' => 'Profile',
        'server' => 'Server',
        'project' => 'Project',
        'skin_tag' => 'Skin Tag',
        'server_category' => 'Server Category',
        'modrinth_category' => 'Project Category',
    ],

    'theme' => [
        'title' => 'Theme',
        'dark' => 'Tumma',
        'light' => 'Vaalea',
        'auto' => 'Auto',
    ],
];
