<?php

return [
    'auth' => [
        'login' => [
            'title' => 'Tervetuloa SkinMC:iin',
        ],
        'register' => [
            'title' => 'Rekisteröidy SkinMC:hen',
            'subtitle' => 'Aloita ja luo tilisi täydelle pääsylle.'
        ]
    ],

    'home' => [
        'hero_slogan' => 'Paikkasi Minecraft Skinsille.',
        'hero_cta' => 'Yllätä minut',
        'hero_explore_cta' => 'Tutki skinejä',
        'skin_viewer' => 'Ulkoasun Katselin',
        'skin_viewer_detail' => 'Selaa :count skins',
        'skin_editor' => 'Ulkoasun editori',
        'skin_editor_detail' => 'Suunnittele oma ihosi',
        'avatar_maker' => 'Profiilikuva generaattori',
        'avatar_maker_detail' => 'Luo mukautetut Minecraft profiilikuvat',
        'trending' => 'Nousussa',
        'minecraft_skin' => 'Minecraftin iho',
        'favourite' => 'Suosikki',
        'collections' => 'Kokoelmat',
        'collections_detail' => 'Kuratoidut Minecraftin ihot joka kerta',
        'about_skinmc' => 'Tietoja SkinMC:stä',
        'about_find' => 'Etsi mikä tahansa iho',
        'about_find_detail' => 'Käytä SkinMC Etsi mitä tahansa Minecraftin käyttäjänimeä löytääksesi, katsoaksesi ja ladataksesi seuraavan uuden ulkoasun.',
        'about_download' => 'Lataa tai muokkaa',
        'about_download_detail' => 'Löysitkö haluamasi ihon? Lisää se suosikkeihisi, muokkaa tai lataa ja tee se omaksi.',
        'about_platform' => 'Ristimäinen alustaa',
        'about_platform_detail' => 'Haluatko ottaa ulkoasun päähän? Skannaa QR-koodi ja tallenna kuva puhelimeen Minecraft PE -laitteelle.',
        'meta' => [
            'title' => 'Minecraft Ulkoasu',
            'description' => 'Katsele ja lataa Minecraftin ihot, löydä parhaat ihot kuratoiduissa kokoelmissa, tarkista käyttäjätunnuksen saatavuus ja historia ja paljon muuta!',
        ],
        'recently_viewed' => 'Viimeksi katsottu',
        'explore_title' => 'Kokeile jotain uutta',
        'explore' => 'Tutustu uusiin ideoihin ja työkaluihin',
        'servers_browse' => 'Selaa palvelimia',
        'servers' => 'Löydä parhaat Minecraft palvelimet',
        'heads' => 'Minecraftin päät',
        'head_description' => 'Selaa Minecraftin päätietokantaa tai luo uusia.',
        'achievement' => 'Saavutus generaattori',
        'achievement_detail' => 'Luo omia, mukautettuja ja yksilöllisiä saavutuksia.',
        'continue' => 'Jatka selaamista'
    ],
    'profile' => [
        'verified' => 'Vahvistettu profiili',
        'minecraft_profile' => 'Minecraftin profiili',
        'show_qr_code' => 'Näytä QR-koodi',
        'favourite' => 'Suosikki',
        'user_title' => ':username Minecraft Skini',
        'user_views' => 'Katsottu :views aika Katsottu :views times',
        'uuid' => 'UUID',
        'copy' => 'Kopioi',
        'link' => 'Linkki',
        'skin_history' => 'Minecraftin skini historia (:skins)',
        'username_history' => 'Käyttäjänimi historia',
        'username_history_name' => 'Nimi',
        'username_history_timestamp' => 'Muutettu klo',
        'username_history_initial_name' => 'Alkuperäinen nimi',
        'user_downloads' => ':downloads download :downloads downloads',
        'download_skin' => 'Lataa oletus',
        'apply_skin' => 'Käytä skiniä',
        'capes' => 'Viitat',
        'claim_profile' => 'Oletko :username? Lunasta profiilisi tarkistaaksesi ja muokkaa sitä!',
        'claimed' => 'Lunastettu profiili',
        'meta_description' => 'Katso ja lataa :username Minecraft Skini. Katso heidän UUID, nimihistoria, yksityiskohtaiset tilastot, ja muuta',
        'created_at' => 'Päivitetty: :changed_at',
        'skins' => [
            'meta_title' => ':username Minecraft Skini Historia',
            'meta_description' => 'Katso :username Minecraft Skinit historia ja aiemmin käytetyt Skinit. Käytä historiaa selatakseen vanhoja tai aiemmin käytettyjä skinejä, varmuuskopioi ja palauta tai kerää uusia skinejä.',
            'title' => 'Minecraftin Skini historia'
        ],
        'qr_code' => [
            'meta_title' => ':username:n QR-koodi',
            'meta_description' => ':username Mukautettu Minecraft Profiili QR-koodi'
        ],
        'sub_nav' => [
            'skin' => 'Skini',
            'about' => 'Tietoja',
            'usernames' => 'Käyttäjänimet',
            'head' => 'Pää',
            'comments' => 'Kommentit'
        ],
        'cape' => 'Viitta',
        'elytra' => 'Liitosiivet',
        'nametag' => 'Nimi tunniste',
        'animation' => 'Animaatio',
        'rotation' => 'Kierto',
        'none' => 'Ei mitään',
        'idle' => 'Toimeton',
        'walk' => 'Kävele',
        'run' => 'Juokse',
        'fly' => 'Lennä',
        'follow' => 'Seuraa',
        'following' => 'Seuratut',
        'unfollow' => 'Lopeta seuraaminen',
        'followers' => 'Seuraaja|Seuraajat',
        'toast' => [
            'following' => 'Seuraat nyt :username!',
            'follow-self-error' => 'Anteeksi :username, et voi seurata itseäsi.',
            'unfollowed' => 'Olet lopettanut :username seuraamisen'
        ],
        'edit' => 'Muokkaa profiilia',
        'joined' => 'Liittyi',
        'server-fav-list-empty' => 'Näyttää siltä, että :username ei saanut ole vielä yhtään suosikkipalvelinta. Kun :username on tallentanut palvelimen suosikikseen, voit nähdä sen täällä.',
        'server-own-list-empty' => 'Näyttää siltä, että :username ei ole saanut vielä yhtään palvelinta. Kun :username on listannut palvelimen, näet sen täällä.',
        'capes-list-empty' => 'Näyttää siltä, että :username ei ole vielä pukeutunut mihinkään viittaan. Kun :username on pukeutunut viittaan, näet sen täältä.',
        'feed-own-list-empty' => 'Näyttää siltä, että et ole vielä julkaissut mitään syötteeseen! Kun olet julkaissut, voit nähdä julkaisujasi täällä.',
        'feed-list-empty' => 'Hmm, näyttää siltä, että :username ei ole julkaissut vielä mitään syötteeseen. Kun :username julkaisee jotain, voit nähdä sen täällä.',
        'following-own-list-empty' => 'Näyttää siltä, että et seuraa ketään vielä! Kun alat seurata ihmisiä, voit nähdä ne täällä.',
        'following-list-empty' => 'Hmm, näyttää siltä, että :username ei seuraa ketään. Kun :username alkaa seurata ihmisiä, voit nähdä ne täällä.',
        'followers-own-list-empty' => 'Kun ihmiset alkavat seurata profiiliasi, he näkyvät täällä.',
        'followers-list-empty' => 'Hmm, näyttää siltä, että :username ei seuraa ketään. Ole ensimmäinen, joka seuraa :username. Kun enemmän ihmisiä seuraa, voit nähdä ne täällä.',
        'render' => 'Renderöijä',
        '3d' => '3D renderöinti',
        '2d' => '2D renderöinti',
        'name-history-info' => 'Käyttäjänimi Historia on menossa pois. Mojang on poistanut tuen nimihistorian API:n käyttämiselle 13. syyskuuta 2022, minkä seurauksena tarkkaa nimihistoriaa ei ole enää saatavilla. Jos haluat piilottaa nimihistoriasi, lunasta profiilisi ja siirry asetuksiin tehdäksesi siitä yksityisen.',
        'edit-skins' => 'Muokkaa skini historiaa',
        'hide-skin' => 'Piilota skini',
        'show-skin' => 'Näytä skini',
        'edit-skin' => 'Muokkaa skiniä',
        'servers' => [
            'title' => ':username:n palvelimet',
        ],
        'cape-list' => [
            'title' => ':username:n viitat',
        ]
    ],
    'skin' => [
        'meta' => [
            'title' => ':username Minecraft Skini',
            'description' => 'Minecraft Skini. Lataa ja katsele skiniä ja näe millä pelaajilla on myös sama skini.',
            'tags' => ':username Minecraft Skini, :username Skini, Minecraft Skini, :username Mukautettu Minecraft Skini, Lataa Skini, Pelaajat, joilla on sama skini',
        ],
        'title' => ':username Minecraft Skini',
        'head' => 'Pää komennot',
        'head_info' => 'Käytetään komentolohkojen kanssa',
        'first_wearing' => 'Ensimmäinen pelaaja, joka on nähty tällä skinillä:',
        'profiles' => ':profilit profiili|:profilit profilit',
        'profiles_title' => ':profiilit profiili tällä skinillä|:profiilit profiilit tällä skinillä',
        'screenshot' => 'Kuvankaappaus',
    ],
    'skins' => [
        'meta' => [
            'title' => 'Sivu :current — Kaikki Minecraft Skinit',
            'description' => 'Selaa :last sivun listaa, jossa on yhteensä :total mukautettua Minecraft skiniä, ja lataa seuraava suosikkiskinisi!',
            'tags' => ':username Minecraft Skini, :username Skini, Minecraft Skini, :username Mukautettu Minecraft Skini, Lataa Skini, Pelaajat, joilla on sama skini',
            'tags-title' => ':tag Minecraft Skinit',
            'tags-description' => 'Selaa :last sivumme listaa, jossa on yhteensä :total :tag Minecraft skiniä, ja lataa seuraava :tag skini!',
            'tags-metatags' => ':tag Minecraft Skini, :tag Skini, Minecraft Skini, :tag Mukautettu Minecraft Skini, Lataa :tag Skini, Minecraft :tag Skinit',
        ],
        'title-skin-tags' => 'Tagatut Minecraft Skinit',
        'subtitle' => 'Sivu :current / :last :total Minecraft Skineistä',
        'subtitle-skin-tags' => 'Sivu :current / :last :total tagatuista Minecraft Skineistä',
        'sort_by' => 'Lajittelujärjestys',
        'latest' => 'Viimeisimmät skinit',
        'most_profiles' => 'Eniten käytetyt skinit',
        'profiles_today' => 'Eniten käytetty tänään',
        'profiles_this_week' => 'Eniten käytetty tällä viikolla',
        'profiles_this_month' => 'Eniten käytetty tässä kuussa',
        'default' => 'Oletusjärjestys',
        'this_month' => 'Lisätty tässä kuussa',
        'this_week' => 'Lisätty tällä viikolla',
        'today' => 'Lisätty tänään',
        'random' => 'Satunnainen',
        'similar' => 'Samankaltaiset skinit',
        'no_similar_skins' => 'Samankaltaisia skinejä ei löytynyt vielä.',
        'favorite' => ':count suosikki:count suosikit',
    ],
    'skin-tags' => [
        'faq' => 'Mitä tagit ovat?',
        'about' => 'Tunnisteet ovat tapa lisätä merkityksellisiä kategorioita skineille. Lisäämällä tunnisteita voit löytää lisää skiniä pidät helposti!',
        'guidelines' => [
            'good' => [
                'title' => 'Yleiset ohjeet hyvistä tunnisteista ovat:',
                'short' => 'Lyhyt',
                'descriptive' => 'Kuvaileva',
                'spelled' => 'Oikein kirjoitettu',
            ],
            'bad' => [
                'title' => 'Älä lisää tunnisteita, kuten:',
                'general' => 'Liian yleinen',
                'specific' =>  'Liian tarkka',
                'too-many-tags' =>  'Pitäisi olla kolme erillistä tagia',
                'spelling' => 'Pitäisi olla :example',
            ],
        ],
        'toast' => [
            'added' => 'Tunniste ”:tag” lisätty äänestykseen',
            'removed' => 'Tunniste ”:tag” on poistettu',
            'upvote' => 'Ylä-ääni ”:tag”',
            'downvote' => 'Alaääni ”:tag”'
        ],
        'vote' => [
            'up' => 'Ylä-ääni',
            'down' => 'Alaääni',
            'remove' => 'Poista ääni',
        ],
    ],
    'contact' => [
        'contact' => 'Yhteystiedot',
        'email' => 'Voit vapaasti kirjoittaa meille osoitteeseen <a href="mailto:support@skinmc.net">support@skinmc.net</a> mistä tahansa kysymyksestä mitä sinulla on.',
        'faq' => 'Pyydämme ystävällisesti ensin tarkistaa <a href=":link">UKK sivu</a> jos kysymykseesi on jo vastattu siellä.',
        'other' => 'Muita tapoja ottaa yhteyttä',
        'other_discord' => 'Liity Discord palvelimeen ja ota yhteys muihin, juttele peleistä, jaa suosikkipaketit ja saa apua yhteisöltä.',
        'other_twitter' => 'Seuraa Twitterissä nähdäksesi milloin uusi päivitys tai ominaisuus on julkaistu, katso viikon skini ja paljon muuta.',
        'other_instagram' => 'Seuraa SkinMC:tä Instagramissa selataksesi ja löytääksesi uusia hienoja Minecraftin Skinejä ja kuvia.',
        'other_facebook' => 'Ryhdy faniksi Facebookissa ja näe kaikki julkaisut, joihin voit kommentoida ja puhua muiden kanssa tutkiessasi Minecraftin sisältöä.'
    ],
    'about' => [
        'intro' => '<span>Sinun</span> <span>alustasi</span> <span></span> <span>Minecraft</span> <span>olemusta.</span>',
        'header_credit' => 'Kuva "Epic Nether Battle" by',
        'info' => 'Pidä kirjaa kaikesta.',
        'info_explainer' => 'Katso pelaajien nimi historia, katso heidän edellinen ulkoasu, lisää ne ystävänä, lataa ulkoasuja, ja jopa saada tiedot tilastot.',
        'card_find_title' => 'Etsi mikä tahansa minecrafter',
        'card_find_detail' => 'Aloita etsimällä valitsemaasi pelaajien käyttäjänimeä tai UUID:tä.',
        'card_view_title' => 'Katso, tallenna ja muokkaa',
        'card_view_detail' => 'Löysitkö ihon, josta pidät? Tallenna se lataamalla tai käyttämällä editoria tehdäksesi siitä oman.',
        'card_claim_title' => 'Vahvista vahvistus',
        'card_claim_detail' => 'Linkitä Minecraft-tilisi ja vaadi profiilisi avataksesi uusia viileitä ominaisuuksia!',
        'card_customise_title' => 'Muokkaa profiiliasi',
        'card_customise_detail' => 'Vahvistetut pelaajat voivat lisätä sosiaalisen median linkkinsä ja tehdä profiilinsa omaksi.',
        'card_friends_title' => 'Lisää ystäväsi',
        'card_friends_detail' => 'Hanki yhteys ystäviesi kanssa SkinMC:ssä ja näytä kaverilistasi profiilissa.',
        'card_history_title' => 'Käyttäjänimi ja ulkoasun historia',
        'card_history_detail' => 'Käytä lisähakua löytääksesi pelaajan käyttäjätunnuksen tai ulkoasun historian ja nähdäksesi sen.',
        'founders' => 'Perustajat',
        'founders_cofounder' => 'SkinMC:n toinen perustaja',
        'head_of_design' => 'Pääsuunnittelija',
        'head_of_code' => 'Pääkoodaaja',
        'feedback' => 'Lähetä meille palautetta',
        'faq' => 'Kysymyksiä Minecraftista, Skinsistä ja muusta? Lue usein kysytyt kysymykset ja vastaukset yleisimpiin kysymyksiin.',
        'faq_link' => 'Vieraile UKK keskuksessa',
        'contact' => 'Haluatko ottaa yhteyttä tai onko sinulla lisäkysymyksiä? Ota meihin suoraan yhteyttä.',
        'contact_link' => 'Ota meihin yhteyttä',

    ],
    'faq' => [
        'title' => 'UKK',
        'subtitle' => 'Usein kysytyt kysymykset',
        'help' => 'Tarvitsetko lisää apua?',
        'discord' => 'Liity Discord-palvelimeen keskustellaksesi muiden Minecraft-pelaajien kanssa.',
        'contact' => 'Ota meihin yhteyttä',
        'q' => [
            'change_skin_t' => 'Miten voin muuttaa Minecraft Skini?',
            'change_skin' => '
                <p>Muuttaaksesi Skin tee seuraavasti:</p>
                <ol>
                    <li>Vieraile osoitteessa <a href="https://my.minecraft.net/en-us/login/">https://my. inecraft.net/en-us/login/</a> ja kirjaudu sisään Mojang-tililläsi.</li><li>Kun olet kirjautunut sisään, valitse <b>"Skin"</b> vasemmasta valikosta.</li><li>Valitse sitten haluamasi malli ja lataa mielesi Ulkoasu</li>
                </ol>',
            'change_username_t' => 'Miten vaihdan Minecraftin käyttäjänimeni?',
            'change_username' => '
                <p>Muuttaaksesi käyttäjänimeäsi tee seuraavat:</p>
                <ol>
                    <li>Vieraile osoitteessa <a href="https://account.mojang.com/login" target="_blank" rel="nofollow">https://account. ojang.com/login</a> ja kirjaudu sisään Mojang-tililläsi.</li>
                    <li>Etsi Minecraft-profiilisi nimi ja paina <b>"(Kakku)"</b> painiketta</li>
                    <li>Seuraavalla sivulla syötä haluamasi uusi käyttäjätunnus.</li>
                    <li>Lopuksi vahvista muutokset kirjoittamalla salasanasi ja painamalla "Muuta nimi".</li>
                </ol>',
            'dl_t' => 'Miten voin ladata jonkun Minecraft Skin?',
            'dl' => '
                <p>Jos haluat ladata jonkun Minecraft Skin tehdä seuraavasti:</p>
                <ol>
                    <li>Paina hakupalkkia ja kirjoita pelaajan käyttäjätunnus, josta haluat ladata ulkoasun.</li>
                    <li>Profiilisivulla voit esikatsella ulkoasua</li>
                    <li>Klikkaa <strong>Lataa Ulkoasu</strong> -painiketta esikatselun alla</li>
                </ol>',
            'submit_q' => 'Miten voin lähettää skinin kokoelmaan?',
            'submit_a' => '<p>Ole hyvä ja täytä seuraava lyhyt lomake käyttäjätunnuksilla ja niiden luokalla, jonka haluat lisätä kokoelmiin. <a href="https://forms.gle/f4Jh5RpGfsHAZ5xE8" target="_blank">Kokoelman lähetyslomake</a>',
            'mcpe_t' => 'Voinko käyttää ihoa Minecraft PE:ssä?',
            'mcpe' => '
                <p>Kyllä. Jos haluat käyttää Skiniä Minecraft Pocket Editionissa, tee seuraavasti:</p>
                <ol>
                    <li>Avaa SkinMC. et älypuhelimessasi ja napauta hakupalkkia</li>
                    <li>Syötä pelaajan ulkoasun käyttäjänimi jonka haluat ladata</li>
                    <li>Napauta <strong>Lataa Ulkoasu</strong> -painiketta esikatselun alla </li>
                    <li>Avaa Minecraft PE ja napauta <strong>Profiili</strong> oikealla puolella</li>
                    <li>Napauta <strong>+</strong>, tai muokkaa hahmoa ja siirry "klassisen oletuksen välilehteen"</li>
                    <li>Napauta "omistettu", sitten "import", sitten "valitse uusi nahka"</li>
                </ol>',
            'change_times_t' => 'Kuinka usein voin vaihtaa käyttäjänimeäni?',
            'change_times' => '<p>Voit muuttaa Minecraftin käyttäjänimeä <strong>kerran</strong> joka <strong>30 päivä</strong>.</p>',
            'available_t' => 'Kun olen muuttanut käyttäjänimeni, milloin se tulee saataville muiden vaatia sitä?',
            'available' => '<p>Jos haluat muuttaa takaisin edelliseen käyttäjänimeesi, voit muuttaa <strong>30 päivän kuluttua.</strong> Kaikkien muiden on odotettava <strong>7 päivää</strong> (37 päivää vaihtamisen jälkeen), ennen kuin he voivat lunastaa vanhan käyttäjätunnuksesi. </p>',
            'username_history_t' => 'Voitko poistaa käyttäjätunnukseni historiasta?',
            'username_history' => '
                <p>Koska käyttäjätunnuksen historia on peräisin Mojangista, käyttäjätunnuksen historiaa ei voi poistaa. Mojang on aiemmin todennut, että heidän tarkoituksenaan oli, että aiemmat käyttäjätunnukset ovat nähtävissä1, ja että ne tarjoavat suoran menetelmän yleisön käyttää näitä tietoja2.</p>
                <p class="font-14">1<a href="https://help.minecraft.net/hc/en-us/articles/360034636712-Minecraft-Usernames" target="_blank" rel="noreferrer">https://help inecraft. et/hc/en-us/articles/360034636712-Minecraft-Usernames</a></p>
                <p class="font-14 mb-0">2<a href="https://twitter.com/dinnerbone/status/554739042529849345" target="_blank" rel="noreferrer">https://twitter. om/dinnerbone/status/554739042529849345</a> (Tweet archived 2 years ago: <a href="http://archive.is/TeAyj" target="_blank" rel="noreferrer">http://archive. s/TeAyj</a>)
                </p>',
        ],
    ],
    'avatars' => [
        'start' => [
            'title' => 'Luo oma Minecraft-avatar',
            'subtitle' => 'Käytä Minecraft avatar generaattori luoda hauska avatar mistä tahansa olemuksesta!',
            'avatar_face' => 'Kasvotyylinen profiilikuva',
            'avatar_bust' => 'Pommun tyylinen profiilikuva',
            'avatar_cube' => 'Kuution tyyli profiilikuva',
            'avatar_head3d' => 'Mukautettu 3D pää',
        ],
        'user' => [
            'title' => 'Valitse ulkoasu',
            'subtitle' => 'Syötä Minecraftin käyttäjätunnus avatarille, jonka haluat luoda',
            'form_label' => 'Minecraftin käyttäjätunnus',
            'form_submit' => 'Jatka',
        ],
        'output' => [
            'title' => 'Esikatsele ja tallenna',
            'subtitle' => 'Nauti uuden Minecraftin käyttämisestä',
            'download_info' => 'Onnellinen tuloksella? Aloita uuden hahmon käyttö lataamalla se tänne',
            'download_button' => 'Lataa profiilikuva',
            'avatar_style' => 'Profiilikuvan tyyli',
            'skin_username' => 'Ulkoasun käyttäjänimi',
            'change' => 'Muuta',
            'generate' => 'Luo',
            'avatar_colour' => 'Taustan väri',
            'avatar_colour_palette' => 'Paletti',
            'avatar_colour_basic' => 'Perus',
        ],
        'meta' => [
            'title' => 'Minecraft Avatar Generaattori',
            'description' => 'Minecraft Avatar Maker: luo mukautettuja Minecraft-profiilikuvia käyttäen Minecraftin ihoa',
        ],
    ],
    'totem' => [
        'title' => 'Mukautettu Minecraft Toteemi',
        'subtitle' => 'Käytä Minecraft Totemi generaattoria luodakseen mukautetun resurssipaketin, jossa on Kuolematon Totemi tahansa skinistä.',
        'download_info' => 'Oletko tyytyväinen esikatseluun? Valitse Minecraft-versiosi tallentaaksesi mukautetun resurssipaketin:',
        'meta' => [
            'title' => 'Minecraft Mukautettu Totemi Generaattori',
            'description' => 'Mukautetut Minecraft Totemit: generoi ja luo mukautettu Minecraft Resurssipaketti, jossa Kuolematon Totemi käyttää sinun tai muiden pelaajien Minecraft skiniä.',
        ],
        'type' => [
            'mini' => 'Mini versio skinistäsi!',
            'full' => 'Täysi versio skinistäsi!',
            'model3d' => '3d malli skinistäsi!',
            'add_designs' => 'Haluatko nähdä lisää malleja? Lähetä sinun suunnitteluehdotus täältä:'
        ]
    ],
    'achievement' => [
        'header' => [
            'title' => 'Luo oma Minecraft-saavutuksesi',
            'subtitle' => 'Käytä Minecraft Achievement Generator luoda oman mukautetun saavutuksen ja käyttää näyttää edistysaskeleita kaikessa, mitä haluat!',
        ],
        'generator' => [
            'yellow_text' => 'Keltainen teksti',
            'white_text' => 'Valkoinen teksti',
            'choose_icon' => 'Valitse kuvake',
            'face' => 'Minecraft kasvot kuvakkeen sijaan',
            'form_submit' => 'Lataa',
            'form_label' => 'Minecraftin käyttäjätunnus',
            'download' => 'Lataa',
            'embed' => 'Upota',
            'embed_copy' => 'Kopioi',
        ],
        'meta' => [
            'title' => 'Minecraft Saavutus Generaattori',
            'description' => 'Luo mukautettuja Minecraft-saavutuksia ja -parannuksia Achievement luojalla. Lataa kuva suoraan, käytä sitä foorumi allekirjoituksia, upotettu HTML tai BB koodi, ja paljon muuta',
        ],
    ],
    'armor' => [
        'header' => [
            'title' => 'Minecraft Haarniskajalustan Luoja',
            'subtitle' => 'Generoi ja luo oma mukautettu Minecraft haarniskajalusta. Luo erilaisia asentoja, sijoituksia, aseta esineitä ja paljon muuta.',
        ],
        'meta' => [
            'title' => 'Minecraft Haarniskajalustan Luoja',
            'description' => 'Generoi ja luo helposti mukautettuja Minecraft haarniskajalustoja. Muokkaaja auttaa sinua tekemään erilaisia asentoja, sijoituksia, asettaa kohteita, muokata skinejä ja paljon muuta.',
        ],
    ],
    'banner' => [
        'editor' => [
            'header' => [
                'title' => 'Minecraft Bannerin Muokkaaja',
                'subtitle' => 'Suunnittele ja luo omat Minecraft bannerit. Näitä voidaan käyttää koristamaan maailmasi tai käytetään yleisesti myös <a href="https://optifine.net" target="_blank" rel="nofollow">Optifine</a> viittana.',
            ],
            'meta' => [
                'title' => 'Minecraft Bannerin Muokkaaja',
                'description' => 'Luo ja suunnittele ikioma Minecraft-bannerisi, jossa on kaikki pelin kuviot ja värit! Niitä voidaan käyttää maailmasi koristeluun tai käyttää Optifine-viittana Banneriviitan avulla. Voit luoda antamiskoodeja bannereille tai kilville.',
            ],
        ],
        'gallery' => [
            'header' => [
                'title' => 'Minecraft Banneri Galleria',
                'subtitle' => 'Selaa galleriaa :count mukautettuja Minecraft bannereita. Voit käyttää Banneria viitana, joka tekee Minecraftin skinistäsi ainutlaatuisemman, tai käytä Banneria lippuna koristamaan maailmaasi.',
            ],
            'meta' => [
                'title' => 'Minecraft Banneri Galleria',
                'description' => 'Selaa galleriaa :count mukautettuja Minecraft bannereita. Voit käyttää Banneria viitana, joka tekee Minecraftin skinistäsi ainutlaatuisemman, tai käytä Banneria lippuna koristamaan maailmaasi.',
            ],
        ],
    ],
    'search' => [
        'meta' => [
            'title' => 'Hakutulokset: :search',
        ],
        'title' => 'Haun tulokset',
        'results' => 'Sivu :current :count tulos:|Sivu :current :count tulokset ',
        'time' => '(:time sekuntia)',
        'username_available' => 'Käyttäjätunnus saatavilla',
        'username_unavailable' => 'Käyttäjätunnus ei ole käytettävissä',
        'username_status' => 'Tila',
        'username_status_available' => 'Saatavuus',
        'username_status_unavailable' => 'Ei saatavilla',
        'username_searches' => 'Haut',
        'username_searches_count' => ':count / päivä',
        'username_available_disclaimer' => '*Ellei Mojang ole väliaikaisesti tai pysyvästi kieltänyt nimeä.',
        'no_results' => 'Profiileja ei löytynyt. Kokeile hakua UUID:llä muuttamalla hakutyyppiä.',
        'no_results_tags' => 'Tagattuja skinejä ei löytynyt. Kokeile hakea muilla tunnisteilla kuten \'sininen\', \'tyttö\', \'kettu\' jne...',
        'again' => 'Hae uudelleen',
        'sorry' => 'Aaaaanteeksi...',
        'view_profile' => 'Näytä profiili',
    ],
    'collection' => [
        'title' => 'Minecraftin ihonkeräys',
        'subtitle' => 'Selaa Minecraftin nahkojen kuratoidun kokoelman läpi.',
        'filters' => 'Suodattimet',
        'title_trending' => 'Nousussa',
        'title_all' => 'Kaikki Minecraft Olemukset',
        'skin_tags' => 'Tagattuja skinejä',
        'filters_skin_type' => 'Ulkoasun tyyppi',
        'filter_skin_type_steve' => 'Steven tyyppi',
        'filter_skin_type_alex' => 'Alex tyyppi',
        'cancel' => 'Peruuta',
        'apply' => 'Käytä',
        'username_minecraft_skin' => ':usernamen Minecraft iho',
        'user_downloads' => '<span class="fw-500">:downloads</span> download<span class="fw-500">:downloads</span> downloads',
    ],
    'favourites' => [
        'title' => 'Suosikit',
        'subtitle' => 'Tarkastele ja hallitse leikkejä, jotka olet tallentanut myöhemmin suosikkilistassa',
        'sort' => 'Lajittelujärjestys',
        'toast' => [
            'added' => 'Lisätty suosikkilistaasi',
            'removed' => 'Poistettu suosikkilistastasi'
        ],
        'skins' => [
            'button' => 'Skinit',
            'empty_headline' => 'Ei vielä suosikkiskinejä',
            'empty_subtitle' => 'Sinulla ei ole vielä yhtään skiniä tallennettu suosikkilistaasi. Käy palvelinsivulla ja löydä seuraava suosikkisi!',
            'empty_browse' => 'Selaa skinejä',
            'meta' => [
                'title' => 'Minun suosikkiskinit',
                'description' => 'Minun suosikiksi tallennetut Minecraft skinit',
            ],
        ],
        'servers' => [
            'button' => 'Palvelimet',
            'empty_headline' => 'Ei vielä suosikkipalvelimia',
            'empty_subtitle' => 'Sinulla ei ole vielä yhtään palvelinta tallennettu suosikkilistaasi. Käy palvelinsivulla ja löydä seuraava suosikkisi!',
            'empty_browse' => 'Selaa palvelimia',
            'meta' => [
                'title' => 'Minun suosikkipalvelimet',
                'description' => 'Minun suosikkini Minecraft palvelimet',
             ],
        ],

    ],
    'cape' => [
        'editor' => [
            'title' => 'Minecraft viitta muokkaaja',
            'subtitle' => 'Käytä Minecraft viitta muokkaajaa luodaksesi oman mukautetun viitan.',
            'meta' => [
                'title' => 'Minecraft Viitta Muokkaaja',
                'description' => 'Käytä Minecraft Viitta Muokkaajaa luodaksesi oman mukautetun viitan.',
            ],
        ],
        'list' => [
            'title' => 'Minecraft viitat',
            'subtitle' => 'Minecraftin viralliset viitat',
            'meta' => [
                'title' => 'Minecraft Capes -lista',
                'description' => 'Minecraft viittalista: Näytä kaikki viralliset Minecraft-viitat, kuten Mojang, Minecon, Persoonalliset, Spesiaali ja vanity viitat',
            ],
        ],
        'detail' => [
            'title' => ':cape Viitta',
            'info' => 'Viitan tiedot',
            'profile_list' => 'Profiilit, joilla on tämä teksti',
            'profiles' => ':profilit profiili|:profilit profilit',
            'meta' => [
                'title' => 'Minecraft Capes -lista',
                'description' => 'Minecraft cape lista: Näytä kaikki viralliset Minecraft viitat kuten Mojang, Minecon, Personal, Speical ja vanity viitat',
            ],
        ],
        'list-custom' => [
            'title' => 'Mukautettu Minecraft Viitat',
            'description' => 'Selaa ja katso mukautettuja viitat, jotka on luotu ja joita SkinMC jäsenet käyttävät.'
        ]
    ],
    'servers' => [
        'title' => 'Minecraft palvelimet',
        'subtitle' => 'Selaa ja tutki minecraft-palvelimia',
        'all' => 'Kaikki palvelimet',
        'manage_your_servers' => 'Hallinnoi palvelimiasi',
        'add_new_server' => 'Lisää uusi palvelin',
        'filters' => [
            'trending' => 'Nousussa',
            'updated' => 'Päivitetty',
            'new' => 'Uusi',
            'most_viewed' => 'Useimmin katsottu',
            'top_voted' => 'Top äänesti',
            'sorting' => 'Lajitellaan',
            'sort_by_latest' => 'Lajittele viimeisimmän mukaan',
            'sort_by_oldest' => 'Lajittele vanhimman mukaan',
            'categories' => 'Luokat',
            'server_location' => 'Palvelimen sijainti',
            'show_results' => 'Näytä tulokset',
            'show_more' => 'Näytä lisää',
            'show_less' => 'Näytä vähemmän',
            'clear_filters' => 'Tyhjennä suodattimet',
            'reviews' => 'Arvostelut',
            'sort_by_highest_rating' => 'Lajittele korkeimman arvosanan mukaan',
            'sort_by_lowest_rating' => 'Lajittele alimman arvosanan mukaan',
            'bedrock_and_java_support' => 'Bedrock ja Java tuki'
        ],
        'review-count' => ':count Arvostelu|:count Arvostelua',
        'meta' => [
            'title' => 'Minecraft Palvelinluettelo',
            'description' => 'Selaa ja tutki Minecraft-palvelinten listaa löytääksesi parhaan Minecraft-palvelin! Suodata viimeisin, suosituin ja paljon muuta',
        ],
        'reviews' => [
            'meta' => [
                'title' => 'Kirjoita arvostelu',
            ],
            'editing' => 'Muokkaat arvosteluasi :date. Haluatko poistaa arvostelun sen sijaan?',
            'welcome' => 'Hei :username. Kuinka oli kokonaiskokemuksesi :servername?',
            'subtitle' => 'Jätä kokonaispistemäärä aiemmasta kokemuksestasi palvelimen kanssa.',
            'scale' => [
                'great' => 'Loistava',
                'good' => 'Hyvä',
                'okay' => 'Okei',
                'meh' => 'Meh',
                'bad' => 'Huono',
            ],
            'rate-experience' => 'Arvioi seuraavaksi kokemuksesi näillä alueilla',
            'overall' => 'Yleinen',
            'server-team' => 'Palvelimen tiimi',
            'community' => 'Yhteisö',
            'experience' => 'Kokemus',
            'availablility' => 'Käyttöaika ja saatavuus',
            'shop' => 'Kauppa',
            'write-review-title' => 'Kirjoita arvostelu',
            'write-review-subtitle' => 'Jätä muutamia muistiinpanoja, voit korostaa mistä nautit, mikä teki kokemuksestasi erityisen, tai tarjota muutamia ehdotuksia.',
            'write-review-helper' => 'Kirjoita palvelimen arvostelu jakaaksesi kokemuksesi uusien pelaajien kanssa ja auta palvelimen omistajia palautteen kera.',
            'write-review-tips' => 'Tässä on muutamia vinkkejä',
            'submit-title' => 'Oletko valmis lähettämään arvostelusi?',
            'submit-subtitle' => 'Melkein valmista!',
            'submit-review' => 'Lähetä arvosteluni',
            'back' => 'Takaisin',
            'continue' => 'Jatka',
            'delete-title' => 'Oletko varma, että haluat poistaa arvostelusi?',
            'tos-checkbox-part-1' => 'Lähettämällä tämän lomakkeen hyväksyt SkinMC:n käyttöehdot, tietosuojakäytännön ja yhteisön ohjeet. Vahvistat myös, että kaikki tiedot ovat paikkansapitäviä ja noudattavat',
            'tos-checkbox-part-2' => 'arvosteluohjeita.',
            'tos-checkbox-part-3' => 'Arvostelusi julkaistaan lähettämisen jälkeen, mutta se voidaan tarkistaa.'
        ],
        'slots' => 'Paikat',
        'empty-helper' => 'Voit yrittää tehdä toisen haun tai',
        'empty' => 'Hmm täällä on vielä tyhjää.',
        'verified' => 'Vahvistettu',
        'review_translate_show_original' => 'Näytä alkuperäinen',
        'review_translate' => 'Käännä arvostelu',
        'description_translate' => 'Käännä kuvaus',
        'create' => [
            'welcome' => 'Tervetuloa',
            'basics' => 'Perusasiat',
            'categories' => 'Luokat',
            'social_links' => 'Sosiaaliset linkit',
            'trailer_video' => 'Traileri video',
            'images' => 'Kuvat',
            'images_description' => 'Voit ladata kuvia jälkikäteen, jotta voit esitellä mitä palvelin tarjoaa.',
            'submit' => 'Lähetä',
            'lets_get_your_server_added' => 'Lisätään palvelimesi.',
            'basics-subtitle' => 'Kerro ihmisille, mistä palvelimellasi on kyse.',
            'description' => 'Kuvaus',
            'description_tips' => 'Tässä on muutamia vinkkejä',
            'description_hint' => 'Kirjoita hyvä kuvaus palvelimellesi houkutellaksesi uusia pelaajia.',
            'categories-subtitle' => 'Valitse joitakin kategorioita palvelimellesi',
            'missing-category' => 'Puuttuva kategoria?',
            'social_links_description' => 'Missä pelaajat voivat olla yhteydessä palvelimeesi sosiaalisessa mediassa?',
            'trailer_video_description' => 'Esittele palvelimesi YouTube-videolla.',
            'trailer_video_hint' => 'Liitä videon URL-osoite tai ID:',
            'ready_to_submit_your_server' => 'Oletko valmis lähettämään palvelimesi?',
            'review-hint' => 'Lähettämisen jälkeen tiimi tarkistaa huolellisesti palvelimen listaushakemuksen. Sitten kun päätös, palvelin julkaistaan, tai muutoksia pyydetään ennen julkiseksi menoa.',
            'terms' => [
                'part-1' => 'Tämän lomakkeen lähettämällä sinä hyväksyt SkinMC:n käyttöehdot, yksityisyydensuojan ja yhteisön ohjeet. Vahvistat myös, että kaikki edellä mainitut tiedot ovat paikkaansapitäviä, olet seurannut asianmukaisesti',
                'part-2' => 'palvelimen asennusta koskevia vaatimuksia',
                'part-3' => 'ja että Minecraft-palvelimen omistaa ja sitä hallinnoi edustamasi taho.'
            ],
            'submit-application' => 'Lähetä hakemus',
            'video-id-helper' => [
                'part-1' => 'Videon ID on merkkijono numeroiden ja kirjainten jälkeen',
                'part-2' => 'Esimerkiksi, jos videon url on',
                'part-3' => ', sitten videon ID olisi'
            ],
            'welcome_description' => 'Tässä vaiheessa lähdemme aloittamaan palvelimen lisäämisen. Kerro meille hieman siitä, kirjoita kuvaus, ja seuraavassa vaiheessa voit ladata joitakin kuvia.'
        ],
        'copy_server_ip' => 'Kopioi palvelin IP',
        'all_minecraft_servers' => 'Kaikki Minecraft Palvelimet',
        'promo' => [
            'title' => 'Ylläpidätkö Minecraft-palvelinta?',
            'ready_to_list_your_server' => 'Oletko valmis listaamaan palvelimesi?',
            'everything_you_need' => 'Kaikki mitä tarvitset palvelimesi kasvattamiseen',
            'list_your_server' => 'Listaa palvelimesi',
            'list_your_server_description' => 'Luo listaus palvelimellesi, lisää kuvia, sosiaalista mediaa ja paljon muuta.',
            'find_players' => 'Etsi pelaajia',
            'find_players_description' => 'Etsi ja tavoita uusia pelaajia liittymään palvelimellesi ja kasvattamaan yhteisöäsi.',
            'get_reviews' => 'Hanki arvosteluja',
            'get_reviews_description' => 'Pyydä yhteisöäsi arvostelemaan palvelimesi ja palkitse heidät pelissä.',
            'why_list_on_skinmc' => 'Miksi sinun pitäisi listata palvelimesi SkinMC:ssä',
            'others' => 'Others',
            'quality_check_and_confirmation' => 'Quality check and confirmation',
            'quality_check_description' => 'Our team reviews every server to ensure quality.',
            'verified_players' => 'Reviews from verified Minecraft players',
            'verified_players_description' => 'Collect authentic player reviews from legitimate accounts with Votifier integration.',
            'international' => 'International',
            'international_description' => 'With translation features your listing is available to more players.',
            'server_listing_page' => 'Powerful Server listing page',
            'server_listing_page_description' => 'Add photos, description texts, youtube videos, and highlight why players should join your server.',
            'social_connections' => 'Social media connections',
            'social_connections_description' => 'Connect your Servers social accounts and show new players where they can find you.',
            'verified_badge' => 'Verification badge',
            'verified_badge_description' => 'Authentic servers can apply for a verification badge.',
            'owner_profile' => 'Owner profile',
            'owner_profile_description' => 'Add a personal touch, by completing your custom profile.',
            'categories' => 'Categories',
            'categories_description' => 'Different categories to make it easier to find your server.',
            'vote' => 'Vote',
            'vote_description' => 'Ask users to vote for your server.',
            'fair_listings' => 'Fair listings',
            'fair_listings_description' => 'Server listings can not be artificially boosted in results on SkinMC.',
            'support' => '24h support',
            'support_description' => 'Do you need help or have questions? You can always reach out and receive a fast reply.',
            'custom_features' => 'Mukautetut ominaisuudet',
            'custom_features_description' => 'Puuttuuko palvelimeltasi jokin ominaisuus? Avaa lippu, niin me toteutamme sen.',
            'faq' => [
                'title' => 'Vastauksia kysymyksiisi',
                'suited-question' => 'Onko Minecraft Palvelimeni SkinMC:lle sopiva?',
                'suited-answer' => 'Minecraft Pelaajat SkinMC:ssä rakastavat löytää uusia kokemuksia, sisältöä ja sitoutua yhteisöihin. Alustalla löydät laajan valikoiman erilaisia, ainutlaatuisia, hauskoja Minecraftin palvelimia. Suuresta verkosta jopa pieneen selviytymispalvelimeen, se voi parantaa jonkun päivän!',
                'get-started-question' => 'Miten pääsen alkuun?',
                'get-started-answer' => 'Lisäämällä Minecraft Palvelimesi SkinMC Palvelin Listaan on erittäin helppoa! Sinun täytyy ensin luoda tili, jos et ole jo tehnyt, ja sitten seuraa asennusohjeita saadaksesi palvelimen listatuksi. Lisää muutama kuva ja mukava kuvaus, ja palvelin julkaistaan ilman aikaa!',
                'players-question' => 'Miten voin saada enemmän pelaajia Minecraft Palvelimelleni?',
                'players-answer' => 'Yhteisön rakentaminen on pitkän kestävän Minecraft Palvelimen tärkein osa. Käytä Minecraftin Palvelin Listaa SkinMC:ssä löytääksesi uuden yleisön ja jatkaaksesi yhteisösi rakentamista. Pyydä pelaajia suosittelemaan palvelintasi tai jakamaan listasi sosiaalisen median alustoille. Hyvien arvostelujen keräämisellä voi myös olla tärkeä rooli, kun halutaan saada hyvä Palvelin listaus, joka houkuttelee uusia pelaajia.',
                'more-question' => 'Minulla on enemmän kysymyksiä. Mistä voin saada apua?',
                'more-answer' => 'Voit ottaa yhteyttä SkinMC:hen milloin tahansa, 24 tuntia vuorokaudessa, joko käyttämällä apupainiketta, neuvontapalvelua tai liittymällä Discord palvelimeen.'
            ],
            'ready_to_list_description' => 'Lisää Minecraft Palvelimesi SkinMC Palvelin Listaan vain muutamassa minuutissa. Jos tarvitset apua, voit ottaa yhteyttä ympäri vuorokauden ja saada vastauksia nopeasti.'
        ],
        'manage' => [
            'index' => [
                'welcome' => 'Tervetuloa takaisin, :username',
                'your_servers' => 'Sinun palvelimesi',
                'reviews_today' => 'Arvostelut tänään',
                'no_reviews_today' => 'Ei arvosteluja tänään',
                'no_reviews_text' => 'Palvelimesi ei ole saanut tänään yhtään arvostelua. Miksi et pyydä pelaajiasi lähettämään yhtä?',
                'tips' => [
                    'title' => 'Vinkkejä',
                    'description-title' => 'Kirjoita hyvä palvelimen kuvaus',
                    'description-body' => 'Hyödyllisiä vinkkejä ja neuvoja kirjoittaa hyvä palvelimen kuvaus.',
                    'images-title' => 'Lisätään palvelimen kuvia',
                    'images-body' => 'Make your server listing stand out with great images.'
                ]
            ],
            'listings' => [
                'title' => 'Your Minecraft servers (:count)'
            ],
            'insights' => [
                'title' => 'Insights'
            ],
            'edit_server' => 'Edit server',
            'listing' => 'Listing',
            'to_do' => 'To do',
            'last_update' => 'Last update',
            'add_more_photos_to_publish' => 'Add more photos to publish',
            'looks_empty_here' => 'Looks empty here.',
            'get_started_by_adding_a_new_server' => 'Get started by adding a new server?'
        ],
        'status' => [
            'approved' => 'Approved',
            'pending_approval' => 'Pending approval',
            'published' => 'Published',
            'in_review' => 'In review'
        ]
    ],
    'editor' => [
        'import' => [
            'title' => 'Import Skin',
            'import_by_username' => 'Import by username',
            'import_button' => 'Import',
            'drag' => 'Drag and drop a skin here, or click',
            'click' => 'Select image'
        ],
        'download' => [
            'error' => [
                'no-data' => 'No skin data was provided. Please try again.',
                'invalid-format' => 'The skin data format is invalid. Please try again.',
                'invalid-data' => 'The skin data is corrupted. Please try again.',
                'generic' => 'Something went wrong while downloading your skin. Please try again.',
            ],
        ],
        'draw' => 'Draw',
        'eyedropper' => 'Eyedropper',
        'fill' => 'Fill',
        'move' => 'Move',
        'decrease_brightness' => 'Vähennä kirkkautta',
        'increase_brightness' => 'Lisää kirkkautta',
        'erase' => 'Pyyhi',
        'undo' => 'Astu taaksepäin (CTRL+Z)',
        'redo' => 'Astu eteenpäin (CTRL+Y)',
        'default_view' => 'Oletusnäkymä',
        'zoom_in' => 'Suurenna (CTRL +)',
        'zoom_out' => 'Pienennä (CTRL -)',
        'saved' => 'Viimeksi tallennettu juuri nyt',
        'saving' => 'Tallennetaan automaattisesti...',
        'save_error' => 'Tapahtui virhe',
        'new_skin' => 'Uusi skini',
        'previous_skins' => 'Edelliset skinit',
        'backed_up_title' => 'Automaattisesti tallennetut skinit',
        'backed_up_info' => 'Tilapäisesti varmuuskopioitu paikalliseen tallennustilaan.',
        'backed_up_empty_title' => 'Täällä on tyhjää',
        'backed_up_empty_info' => 'Kun aloitat skinin muokkauksen, näet 32 viimeksi muokattua skiniä täällä.',
        'backed_up_skins_count' => '32 käytetyn skinin varmuuskopiot',
        'backed_up_skins_count_info' => 'Voit varmuuskopioida jopa 32 skiniä. Kun saavutat 32 skiniä, vanhempi iho korvataan uudella skinillä.',
        'layers' => 'Kerrokset',
        'body' => [
            'title' => 'Runko',
            'overlay' => 'Overlay',
            'head' => 'Pää',
            'torso' => 'Torso',
            'l_arm' => 'Vasen käsi',
            'r_arm' => 'Oikea käsi',
            'l_leg' => 'Vasen jalka',
            'r_leg' => 'Oikea jalka',
        ],
        'model' => 'Malli',
        'steve' => 'Steve',
        'alex' => 'Alex',
        'stance' => [
            'title' => 'Sijainti',
            'default' => 'Oletus',
            'walk' => 'Kävele',
            'run' => 'Suorita',
            'hug' => 'T-iske',
            'fly' => 'Lento',
        ],
        'fullscreen' => 'Fullscreen',
        'fullscreen_exit' => 'Exit fullscreen',
        'grid' => 'Ruudukko',
        'show_grid' => 'Näytä ruudukko',
        'download' => [
            'title' => 'Tallenna & Lataa',
            'subtitle' => 'Skinmc Tili',
            'description' => 'Haluatko luoda ilmaisen SkinMC-tilin, jonka avulla voit tallentaa ihosi ja tulevaisuudennäkymät pilveen?',
            'start_description' => 'Aloita lataus suoraan tallentamatta pilveen',
            'start' => 'Lataa oletus',
        ],
        'help' => [
            'title' => 'Minecraft Skin Editor',
            'about' => 'Create and edit your custom Minecraft Skin easily with the SkinMC Editor. You can choose between Steve and Alex models, import skins from a file or username, and create your very own Minecraft Skin.',
            'draw' => 'Draw using the pen tool. Select a colour from the swatch to use with it.',
            'eyedropper' => 'Use the eyedropper to select a colour from your skin and add it to your current palette.',
            'fill' => 'Fill entire areas of your skin using the fill tool. Select a colour before using fill.',
            'move' => 'Pan and move around the skin editor canvas with the move tool.',
            'decrease_brightness' => 'Decrease the brightness of the currently active colour.',
            'increase_brightness' => 'Increase the brightness of the currently active colour.',
            'erase' => 'Erase pixels drawn on the secondary overlay layer.',
        ],
    ],
    'account' => [
        'level' => 'Level',
        'level_history' => 'Level history',
        'xp' => 'XP',
        'my_xp' => 'My XP',
        'xp_to_next_level' => ':xp XP to next level',
        'xp_info' => 'What are XP?',
        'xp_info_tooltip' => 'XP is earned for various activities such as adding tags to skins, inviting friends, commenting, and much more. With each XP earned you can level up and unlock cool things!',
        'settings' => [
            'title' => 'Tili',
            'show_profile' => 'Siirry profiiliin',
            'friends' => 'Ystävät',
            'friends_detail' => 'Pysy yhteydessä käyttämällä ystäväsi listaa SkinMC.',
            'security' => 'Turvallisuus',
            'security_detail' => 'Päivitä kirjautumissalasanasi ja säilytä tilisi turvassa',
            'social' => 'Sosiaalisen median tilit',
            'social_detail' => 'Muokkaa profiiliasi lisäämällä sosiaalisen median',
            'link' => 'Yhdistä Minecraft-tili',
            'link_detail' => 'Linkitä Minecraft-tilisi ja tallenna profiilisi.',
            'logout' => 'Haluatko kirjautua ulos SkinMC tililtäsi?',
            'automatic_backups' => 'Automatic skin backups',
            'automatic_backups_info' => 'As a SkinMC plus member your skins are backed up daily.',
        ],
        'capes' => [
            'title' => 'SkinMC Minecraft Cape',
            'description' => 'Wear any cape you wish in-game with SkinMC Capes for free.',
            'drop' => 'Drag and drop a cape here',
            'drop-hint' => 'Dimensions 64x32px',
            'select' => 'Select image',
            'upload-cape' => 'Upload & use cape',
            'save-and-use' => 'Save & use',
            'uploaded-cape' => 'Uploaded cape',
            'no-cape' => 'No cape',
            'remove-cape' => 'Remove cape',
            'download' => 'Download the SkinMC Mod to see your and other players capes in-game.',
            'learn-more' => 'Learn more',
            'link-account' => 'Please link your Minecraft account to upload a cape.',
            'updated' => 'Your cape has been updated!',
            'removed' => 'Your cape has been removed.',
            'active' => 'Your cape is activated!'
        ],
        'favourite' => 'Favourite',
        'remove_favourite' => 'Remove favourite',
        'added_to_favourites' => 'Added to favourites',
        'removed_from_favourites' => 'Removed from favourites',
        'welcome' => 'Nice to see you!',
        'view-profile' => 'View my profile',
        'security' => [
            'title' => 'Turvallisuus',
            'email' => 'Sähköposti osoite',
            'email-title' => 'Update your email address.',
            'save' => 'Tallenna',
            'password' => 'Salasana',
            'password-title' => 'Change your password at any time.',
            'social-provider' => 'To update your account information, such as your password, please visit your login provider:',
            'social-provider-email' => 'Your associated email address with your login provider',
            'social-provider-connected' => 'Currently connected login providers',
            'current-password' => 'Current password',
            'forgot' => 'Forgot password?',
            'edit' => 'Muokkaa',
            'delete' => 'Delete my account',
            'account-deletion' => 'Delete your SkinMC account.',
            'delete-info' => 'Please confirm to continue',
            'delete-confirmation' => 'Deleting your account is irreversible. All your personal information and content such as posts, favourites, uploaded capes, customisations, etc. will be deleted and can not be recovered.',
            'delete-confirmation-info' => 'Enter your password to continue',
            'yes-confirm-delete' => 'Yes, confirm delete',
            'account-successfully-deleted' => 'Your account and data has been successfully deleted.'
        ],
        'social' => [
            'title' => 'Sosiaaliset tilit',
            'edit' => 'Muokkaa',
            'save' => 'Tallenna',
            'link-account' => 'Link your Minecraft account to SkinMC to display your social links on your profile.',
            'finish-setup' => 'Finish setup',
            'connect-account' => 'Connect your accounts',
            'connect-description' => 'Choose which accounts you wish to connect and unlock special SkinMC integrations.',
            'empty' => 'No accounts added',
            'empty-description' => 'Your social media accounts will show up here and on your public profile. Once added they will add more personalisation to your page as well as enable integrations.',
            'connect' => 'Connect',
            'username' => 'username',
            'spotify' => 'Add your Spotify username to show your Spotify information on your profile.',
            'discord' => 'Enter your Discord username and number to display your Discord information on your SkinMC profile.',
            'youtube' => 'Add your YouTube channel to SkinMC which will display your YouTube channel on your profile.',
            'youtube-format' => 'Use the following format depending on your channel link:',
            'twitter' => 'Enter your X (formerly Twitter) username to display it on your profile.',
            'bluesky' => 'Enter your Bluesky handle e.g. username.bsky.social to display your Bluesky profile on your profile.',
            'twitch' => 'Enter your Twitch username to display your Twitch channel on your profile.',
            'reddit' => 'Enter your Reddit username to display your Reddit profile on your profile.',
            'github' => 'Enter your GitHub username to display your GitHub profile on your profile.',
            'telegram' => 'Enter your Telegram username to display your Telegram link on your profile.',
            'tiktok' => 'Enter your TikTok username to display your TikTok profile on your profile.',
            'snapchat' => 'Enter your Snapchat username to display your Snapchat profile on your profile.',
            'instagram' => 'Enter your Instagram username to display your Instagram profile on your profile.',
            'facebook' => 'Enter your Facebook username to display your Facebook profile on your profile.',
            'includes_skinmc_plus_benefits' => 'Includes SkinMC plus benefits',
        ],
        'recover' => [
            'title' => 'Palauta tilisi',
            'subtitle' => 'Syötä uusi salasana ja vahvista se viimeistelläksesi tilin palautuksen.',
            'new_password' => 'Uusi salasana',
            'repeat_new_password' => 'Toista uusi salasana',
            'submit' => 'Palauta tili',
        ],
        'customise' => [
            'title' => 'Customise your profile',
            'description' => 'Add your social media, choose an emoji, set your location and more',
            'information' => 'Information',
            'preview' => 'Preview',
            'location' => [
                'title' => 'Location',
                'description' => 'Choose which location you would like to add to your profile.',
            ],
            'biography' => [
                'title' => 'About me',
                'description' => 'Write a bio for your profile.',
            ],
            'status' => 'Status',
            'status-toggle' => 'Show my online status',
            'emoji' => 'Emoji',
            'name-history-toggle' => 'Make username history private',
            'name-history-info' => 'Your Minecraft username history is currently',
            'name-history-toggle-on' => 'private',
            'name-history-toggle-off' => 'public',
            'theme' => 'Profile theme',
            'theme-primary' => 'Primary',
            'theme-secondary' => 'Secondary',
            'appearance' => 'Appearance',
        ],
        'link' => [
            'manage' => 'Manage linked Minecraft account',
            'description' => 'See and manage your linked Minecraft account',
            'title' => 'Linked Minecraft account',
            'current' => 'Currently linked Minecraft account.',
            'status' => 'You now have full access to all SkinMC features!',
            'linked' => 'Linked',
            'disconnect' => 'Disconnect',
            'disconnect-title' => 'Disconnect Minecraft account',
            'disconnect-info' => 'Are you sure you would like to disconnect your Minecraft account?',
            'disconnect-features' => 'You will lose access to commenting, customisation and other features which require a linked Minecraft account. To use these again you will be required to link a Minecraft account.',
            'disconnect-following' => 'Disconnecting your Minecraft account will permanently remove all your followed profiles.',
            'disconnect-posts' => 'Your created feed posts and liked will be deleted.',
            'can-not-undo' => 'This can\'t be undone.',
            'are-you-sure' => 'Are you sure?',
            'confirm' => 'Yes, confirm disconnect',
            'cancel' => 'No, cancel',
            'success' => 'Your account was successfully disconnected!'
        ],
        'finish-setup' => [
            'title' => 'Finish account setup',
            'description' => 'Finish setting up your account, and get full access to all features by linking your Minecraft account to SkinMC.',
            'link' => 'Link Minecraft account',
            'get-started' => 'Get started',
            'skip' => 'Skip',
            'claim' => 'Claim your profile',
            'customise' => 'Customise your page',
            'social' => 'Add social links',
            'comment' => 'Access to comment system',
            'direct_message' => 'Send direct messages',
            'feed' => 'Post status updates to the feed',
            'follow' => 'Follow your friends',
            'badge' => 'Badge displayed on your profile',
            'cape' => 'Custom Minecraft cape',
            'backup' => 'Automatic skin backup',
            'more' => 'And more...'
        ],
        'skins' => [
            'title' => 'Manage skins',
            'toggle' => 'Skin visibility toggled',
        ],
        'invite' => [
            'title' => 'My invites',
            'headline' => 'Invite your friends',
            'info' => 'Create an invite code to share with your friend. Once they accept it, you\'ll both earn some extra XP!',
            'description' => 'Create an invite for your friends and you\'ll both earn some extra XP.',
            'generate' => 'Create invite code',
            'empty' => 'You haven\'t created any invites yet.',
            'code' => 'Code',
            'expiry' => 'Each code works once.',
            'status' => [
                'title' => 'Status',
                'pending' => 'Pending',
                'accepted' => 'Accepted'
            ],
            'add_invite' => [
                'button' => 'Have an invite?',
                'title' => 'Add an invite code',
                'redeem' => 'Redeem invite',
            ],
            'share' => 'Send your friend an invite link'
        ],
        'emoji' => [
            'title' => 'SkinMC Emoji',
            'introducing' => 'Introducing',
            'info' => 'Customise your profile with emoji. Unlock more as you level up.',
            'unlocked_at' => 'Unlocked at level :level',
            'unlocks_at' => 'Reach level :level to unlock',
            'turn_off' => 'Show emoji'
        ]
    ],
    'notifications' => [
        'title' => 'Notifications',
        'view_all' => 'View all',
        'view_all_notifications' => 'View all notifications',
        'image' => 'Notification photo',
        'archived' => 'Archived',
        'inbox' => 'Inbox',
        'empty' => [
            'title' => 'You\'re up to date!',
            'text' => 'New notifications will show up here.',
            'text-archived' => 'Archived notifications will show up here.',
        ],
        'action' => [
            'archive' => 'Move to archive',
            'unarchive' => 'Unarchive',
            'open' => 'Tap to open',
        ],
        'toast' => [
            'archive' => 'Notification moved to archive',
            'unarchive' => 'Notification moved to inbox',
            'undo' => 'Undo',
        ]
    ],
    'error' => [
        'offline' => [
            'title' => 'No internet',
            'subtitle' => 'Your internet was disconnected. Please check your connection and reload the page to try again.',
            'try_again' => 'Try again'
        ],
        '404' => [
            'title' => '404 — Page not found.',
            'subtitle' => 'Hm, it looks like nothing was found at this location. Maybe try going back, or start a new search?',
            'try_again' => 'Back home'
        ],
    ],
    'heads' => [
        'list' => [
            'meta' => [
                'title' => 'Minecraft heads database',
                'description' => 'Explore the database of Minecraft heads to decorate your world with, or generate your own give command. View official heads, player heads and custom heads that feature textures which never change.'
            ],
            'header' => [
                'title' => 'Minecraft heads',
                'subtitle' => 'Explore our database of Minecraft heads to decorate your world, or generate your own give command. Player heads show the current skin worn by a user, and can change as the user updates their skin. Custom heads are linked to the Mojang skin file and never change. Custom heads must be summoned using a command block as the command is very long.',
            ],
            'count' => [
                'heads' => ':heads head|:heads heads',
            ],
            'customheads' => [
                'title' => 'Custom heads',
                'description' => 'Custom heads use the direct path to the texture file on the Mojang servers. Hence textures will never be deleted and the heads never change.',
                'version' => 'Minecraft 1.8 or later',
            ],
            'playerheads' => [
                'title' => 'Player heads',
                'description' => 'Player heads use the current skin texture of a Minecraft player. As they are username based, when the player changes their name or skin, the head changes.',
                'version' => 'All Minecraft versions',
            ]
        ],
    ],
    'mod' => [
        'title' => 'SkinMC Mod: Free custom capes',
        'headline' => 'Introducing the SkinMC Mod for more customisation',
        'description' => 'Giving back to the Minecraft community, with a free mod which enables players more customisation with custom capes, available and visible for anyone using the mod.',
        'download' => 'Download now',
        'download-title' => 'Download the mod',
        'requires' => 'Requires',
        'select-version' => 'Choose your Minecraft version',
        'get-started' => 'Getting started is simple',
        'step-1' => '1. Get the mod',
        'step-1-detail' => 'Install Fabric, then download the mod for your game version and install it by putting the jar in your mods folder.',
        'step-2' => '2. Link your account',
        'step-2-detail' => 'If you haven\'t already, sign up/in and connect your Minecraft account to SkinMC.',
        'step-3' => '3. Upload your cape',
        'step-3-detail' => 'Go to your account and upload your custom cape. It will be visible in-game.',
        'all-versions' => 'All versions',
        'latest' => 'Latest',
        'logged-in' => 'Upload your cape',
        'mirror' => 'Mirror',
        'download-via' => 'Download via:',
        'curseforge' => 'CurseForge',
    ],
    'app' => [
        'title' => 'SkinMC Android App',
        'headline' => 'Say hello to the SkinMC Android App.',
        'play-store-attribution' => 'Google Play ja Google Play -logo ovat Google LLC: n tavaramerkkejä.',
        'features' => 'Convenient features for on the go',
        'feature-qr' => 'Built in QR-Code scanner',
        'feature-qr-detail' => 'Use the built in QR-Code scanner to easily get a skin from your Desktop to the app, or scan your friends custom profile QR-Code.',
        'feature-files' => 'Saves directly to files',
        'feature-files-detail' => 'With the usage of Android Files Manager, the app can conveniently save Skins, making it easier to apply in Bedrock Edition.',
        'feature-noads' => 'No ads',
        'feature-noads-detail' => 'A clean designed interface, without distractions. Enjoy an Ad-free experience without intrusive annoyances from web to app.',
        'feature-experience' => 'Experience',
        'feature-experience-detail' => 'Enjoy the full SkinMC experience anywhere, with added features. Customise your profile, add your bio, create a fun QR-Code and more!',
        'get-app-headline' => 'Get the SkinMC App',
        'get-app-detail' => 'Your very own Minecraft companion for your Android — available for free.'
    ],
    'random' => [
        'title' => 'Loading random Minecraft skin',
        'description' => 'Loading random Minecraft skin',
        'headline' => 'Please wait...',
        'redirect' => 'You will be automatically redirected. Page not loading?',
        'click-here' => 'Click here',
        'messages' => [
            '1' => 'Loading random Minecraft skin...',
            '2' => 'Digging down...',
            '3' => 'Creeper, aw man...',
            '4' => 'Searching through chests...',
            '5' => 'Did you know the coming skin is completely random?',
            '6' => 'Random skin incoming...',
            '7' => 'One more block...',
            '8' => 'Sorting inventory...',
            '9' => 'Crafting diamond pickaxe...',
            '10' => 'Looking for Herobrine...',
        ],
    ],
    'feed' => [
        'title' => 'Feed',
        'following' => 'Following',
        'sign-up' => 'Sign up or log in to join the conversation.',
        'link-account' => 'Link your Minecraft account to join the conversation.',
        'placeholder' => 'What is happening?',
        'audience' => 'Audience',
        'audience-title' => 'Who can see this?',
        'everyone' => 'Everyone',
        'everyone-info' => 'Anyone on or off SkinMC.',
        'followers' => 'Followers',
        'followers-info' => 'Signed in or members following me.',
        'private' => 'Only me',
        'private-info' => 'Private post only I can see.',
        'submit' => 'Post',
        'like' => 'Like',
        'comment' => 'Reply',
        'share' => 'Share',
        'remaining' => 'Remaining',
        'profile' => 'Posts by :username',
        'posts' => 'All posts',
        'my-posts' => 'My posts',
        'view-all' => 'View all posts',
        'post' => [
            'meta' => ':username on SkinMC: :text',
            'title' => 'Post',
            'created' => 'Status update posted!',
            'confirm-delete' => 'Are you sure you would like to delete this post? It can not be undone.',
            'delete' => 'Delete post',
            'deleted' => 'Your post was deleted.',
        ],
        'follow-suggestions' => 'Follow the team',
        'explore' => 'Explore',
        'hashtag' => 'Hashtag',
    ],
    'private' => [
        'title' => 'Private posts',
        'text' => 'This post is private.'
    ] ,
    'liked' => [
        'title' => 'Liked'
    ],
    'following' => [
        'title' => 'Following',
        'text' => 'Sign in to view this post.'
    ],
    'tags' => [
        'empty' => 'No tags to vote on yet',
        'empty-subtitle' => 'Be the first to add one',
    ],
    'inbox' => [
        'title' => 'Messages',
        'details' => 'Details',
        'message_user' => 'Message',
        'write_message' => 'Write a message',
        'empty' => [
            'no_message_selected' => 'No message selected',
            'open_or_start_conversation' => 'Open a conversation from the message list, or start a new one.',
            'no_messages' => 'No unread messages',
            'start_conversation' => 'Once you start a new conversation, your messages will be displayed here.',
            'conversation' => 'This is the beginning of your conversation with :username.',
            'users' => 'Unable to find any users that match the current query.'
        ],
        'typing' => ':username is typing...',
        'new_message' => 'New message',
        'mark_unread' => 'Mark unread',
        'send_message' => 'Send message',
        'delete_message' => 'Delete message for you',
        'latest_conversations' => 'Latest conversations',
        'delete_conversation' => 'Delete conversation',
        'show_details' => 'Show details',
        'hide_details' => 'Hide details',
        'unread' => 'Unread',
        'deleted' => 'Deleted',
        'report_message' => 'Report message',
        'add_reaction' => 'Add reaction',
        'today' => 'Today',
        'reconnect' => 'Please reconnect your Minecraft account to chat',
        'account_disconnected' => 'This user disconnected their linked Minecraft account.',
        'saved_messages' => 'Saved messages',
        'new_message_to_label' => 'To',
        'external-link-to' => 'This link will take you to',
        'external-link-confirmation' => 'Are you sure you want to go there?',
        'external-link' => 'External link',
        'reply' => 'Reply'
    ],
    'server' => [
        'manage' => [
            'stats' => 'Stats'
        ]
    ],
    'report' => [
        'button' => 'Report',
        'title' => 'Report content',
        'describe' => 'Briefly describe why you are reporting this',
        'select' => 'Select report reason',
        'submit' => 'Submit report',
        'reasons' => [
            'INAPPROPRIATE_CONTENT' => 'Inappropriate content',
            'SPAM' => 'Spam',
            'HARASSMENT' => 'Harassment',
            'OTHER' => 'Other',
        ]
    ],
    'leaderboard' => [
        'title' => 'Leaderboard',
        'description' => 'View the SkinMC leaderboard of users.',
        'headline' => 'Top 10',
        'all-time-invites' => 'All time invites',
        'all-time-xp' => 'All time XP',
        '30-day-xp' => '30 days XP'
    ],
];
