<?php

return [
    'auth' => [
        'login' => [
            'title' => 'Tervetuloa SkinMC:iin',
        ],
        'register' => [
            'title' => 'Rekisteröidy SkinMC:hen',
            'subtitle' => 'Aloita ja luo tilisi täydelle pääsylle.'
        ]
    ],

    'home' => [
        'hero_slogan' => 'Paikkasi Minecraft Skinsille.',
        'hero_slogan_alt_1' => 'Everything Minecraft. One place.',
        'hero_slogan_alt_2' => 'Where Minecrafters meet.',
        'hero_cta' => 'Yllätä minut',
        'hero_explore_cta' => 'Tutki skinejä',
        'skin_viewer' => 'Ulkoasun Katselin',
        'skin_viewer_detail' => 'Selaa :count skins',
        'skin_editor' => 'Ulkoasun editori',
        'skin_editor_detail' => 'Suunnittele oma ihosi',
        'avatar_maker' => 'Profiilikuva generaattori',
        'avatar_maker_detail' => 'Luo mukautetut Minecraft profiilikuvat',
        'trending' => 'Nousussa',
        'minecraft_skin' => 'Minecraft iho',
        'favourite' => 'Suosikki',
        'collections' => 'Kokoelmat',
        'collections_detail' => 'Kuratoidut Minecraftin ihot joka kerta',
        'about_skinmc' => 'Tietoja SkinMC:stä',
        'about_find' => 'Etsi mikä tahansa iho',
        'about_find_detail' => 'Käytä SkinMC Etsi mitä tahansa Minecraftin käyttäjänimeä löytääksesi, katsoaksesi ja ladataksesi seuraavan uuden ulkoasun.',
        'about_download' => 'Lataa tai muokkaa',
        'about_download_detail' => 'Löysitkö haluamasi ihon? Lisää se suosikkeihisi, muokkaa tai lataa ja tee se omaksi.',
        'about_platform' => 'Ristimäinen alustaa',
        'about_platform_detail' => 'Haluatko ottaa ulkoasun päähän? Skannaa QR-koodi ja tallenna kuva puhelimeen Minecraft PE -laitteelle.',
        'meta' => [
            'title' => 'Minecraft Ulkoasu',
            'description' => 'Katsele ja lataa Minecraftin ihot, löydä parhaat ihot kuratoiduissa kokoelmissa, tarkista käyttäjätunnuksen saatavuus ja historia ja paljon muuta!',
        ],
        'recently_viewed' => 'Viimeksi katsottu',
        'explore_title' => 'Kokeile jotain uutta',
        'explore' => 'Tutustu uusiin ideoihin ja työkaluihin',
        'servers_browse' => 'Selaa palvelimia',
        'servers' => 'Löydä parhaat Minecraft palvelimet',
        'heads' => 'Minecraft päät',
        'head_description' => 'Selaa Minecraftin päätietokantaa tai luo uusia.',
        'achievement' => 'Saavutus generaattori',
        'achievement_detail' => 'Luo omia, mukautettuja ja yksilöllisiä saavutuksia.',
        'continue' => 'Jatka selaamista'
    ],
    'profile' => [
        'verified' => 'Vahvistettu profiili',
        'minecraft_profile' => 'Minecraft profiili',
        'show_qr_code' => 'Näytä QR-koodi',
        'favourite' => 'Suosikki',
        'user_title' => ':username Minecraft Skini',
        'user_views' => 'Katsottu :views aika Katsottu :views times',
        'uuid' => 'UUID',
        'copy' => 'Kopioi',
        'link' => 'Linkki',
        'skin_history' => 'Minecraft skini historia (:skins)',
        'username_history' => 'Käyttäjänimi historia',
        'username_history_name' => 'Nimi',
        'username_history_timestamp' => 'Muutettu klo',
        'username_history_initial_name' => 'Alkuperäinen nimi',
        'user_downloads' => ':downloads download :downloads downloads',
        'download_skin' => 'Lataa oletus',
        'apply_skin' => 'Käytä skiniä',
        'capes' => 'Viitat',
        'claim_profile' => 'Oletko :username? Lunasta profiilisi tarkistaaksesi ja muokkaa sitä!',
        'claimed' => 'Lunastettu profiili',
        'meta_description' => 'Katso ja lataa :username Minecraft Skini. Katso heidän UUID, nimihistoria, yksityiskohtaiset tilastot, ja muuta',
        'created_at' => 'Päivitetty: :changed_at',
        'skins' => [
            'meta_title' => ':username Minecraft Skini Historia',
            'meta_description' => 'Katso :username Minecraft Skinit historia ja aiemmin käytetyt Skinit. Käytä historiaa selatakseen vanhoja tai aiemmin käytettyjä skinejä, varmuuskopioi ja palauta tai kerää uusia skinejä.',
            'title' => 'Minecraft Skini historia'
        ],
        'qr_code' => [
            'meta_title' => ':username:n QR-koodi',
            'meta_description' => ':username Mukautettu Minecraft Profiili QR-koodi'
        ],
        'sub_nav' => [
            'skin' => 'Skini',
            'about' => 'Tietoja',
            'usernames' => 'Käyttäjänimet',
            'head' => 'Pää',
            'comments' => 'Kommentit'
        ],
        'cape' => 'Viitta',
        'elytra' => 'Liitosiivet',
        'nametag' => 'Nimi tunniste',
        'animation' => 'Animaatio',
        'rotation' => 'Kierto',
        'none' => 'Ei mitään',
        'idle' => 'Toimeton',
        'walk' => 'Kävele',
        'run' => 'Juokse',
        'fly' => 'Lennä',
        'follow' => 'Seuraa',
        'following' => 'Seurataan',
        'unfollow' => 'Lopeta seuraaminen',
        'followers' => 'Seuraaja|Seuraajat',
        'toast' => [
            'following' => 'Seuraat nyt :username!',
            'follow-self-error' => 'Anteeksi :username, et voi seurata itseäsi.',
            'unfollowed' => 'Olet lopettanut :username seuraamisen'
        ],
        'edit' => 'Muokkaa profiilia',
        'joined' => 'Liittyi',
        'role' => 'Role',
        'server-fav-list-empty' => 'Näyttää siltä, että :username ei saanut ole vielä yhtään suosikkipalvelinta. Kun :username on tallentanut palvelimen suosikikseen, voit nähdä sen täällä.',
        'server-own-list-empty' => 'Näyttää siltä, että :username ei ole saanut vielä yhtään palvelinta. Kun :username on listannut palvelimen, näet sen täällä.',
        'capes-list-empty' => 'Näyttää siltä, että :username ei ole vielä pukeutunut mihinkään viittaan. Kun :username on pukeutunut viittaan, näet sen täältä.',
        'feed-own-list-empty' => 'Näyttää siltä, että et ole vielä julkaissut mitään syötteeseen! Kun olet julkaissut, voit nähdä julkaisujasi täällä.',
        'feed-list-empty' => 'Hmm, näyttää siltä, että :username ei ole julkaissut vielä mitään syötteeseen. Kun :username julkaisee jotain, voit nähdä sen täällä.',
        'following-own-list-empty' => 'Näyttää siltä, että et seuraa ketään vielä! Kun alat seurata ihmisiä, voit nähdä ne täällä.',
        'following-list-empty' => 'Hmm, näyttää siltä, että :username ei seuraa ketään. Kun :username alkaa seurata ihmisiä, voit nähdä ne täällä.',
        'followers-own-list-empty' => 'Kun ihmiset alkavat seurata profiiliasi, he näkyvät täällä.',
        'followers-list-empty' => 'Hmm, näyttää siltä, että :username ei seuraa ketään. Ole ensimmäinen, joka seuraa :username. Kun enemmän ihmisiä seuraa, voit nähdä ne täällä.',
        'render' => 'Renderöijä',
        '3d' => '3D renderöinti',
        '2d' => '2D renderöinti',
        'name-history-info' => 'Käyttäjänimi Historia on menossa pois. Mojang on poistanut tuen nimihistorian API:n käyttämiselle 13. syyskuuta 2022, minkä seurauksena tarkkaa nimihistoriaa ei ole enää saatavilla. Jos haluat piilottaa nimihistoriasi, lunasta profiilisi ja siirry asetuksiin tehdäksesi siitä yksityisen.',
        'edit-skins' => 'Muokkaa skini historiaa',
        'hide-skin' => 'Piilota skini',
        'show-skin' => 'Näytä skini',
        'edit-skin' => 'Muokkaa skiniä',
        'servers' => [
            'title' => ':username:n palvelimet',
        ],
        'cape-list' => [
            'title' => ':username:n viitat',
        ]
    ],
    'skin' => [
        'meta' => [
            'title' => ':username Minecraft Skini',
            'description' => 'Minecraft Skini. Lataa ja katsele skiniä ja näe millä pelaajilla on myös sama skini.',
            'tags' => ':username Minecraft Skini, :username Skini, Minecraft Skini, :username Mukautettu Minecraft Skini, Lataa Skini, Pelaajat, joilla on sama skini',
        ],
        'title' => ':username Minecraft Skini',
        'head' => 'Pää komennot',
        'head_info' => 'Käytetään komentolohkojen kanssa',
        'first_wearing' => 'Ensimmäinen pelaaja, joka on nähty tällä skinillä:',
        'profiles' => ':profilit profiili|:profilit profilit',
        'profiles_title' => ':profiilit profiili tällä skinillä|:profiilit profiilit tällä skinillä',
        'screenshot' => 'Kuvankaappaus',
    ],
    'skins' => [
        'meta' => [
            'title' => 'Sivu :current — Kaikki Minecraft Skinit',
            'description' => 'Selaa :last sivun listaa, jossa on yhteensä :total mukautettua Minecraft skiniä, ja lataa seuraava suosikkiskinisi!',
            'tags' => ':username Minecraft Skini, :username Skini, Minecraft Skini, :username Mukautettu Minecraft Skini, Lataa Skini, Pelaajat, joilla on sama skini',
            'tags-title' => ':tag Minecraft Skinit',
            'tags-description' => 'Selaa :last sivumme listaa, jossa on yhteensä :total :tag Minecraft skiniä, ja lataa seuraava :tag skini!',
            'tags-metatags' => ':tag Minecraft Skini, :tag Skini, Minecraft Skini, :tag Mukautettu Minecraft Skini, Lataa :tag Skini, Minecraft :tag Skinit',
        ],
        'title-skin-tags' => 'Tagatut Minecraft Skinit',
        'subtitle' => 'Sivu :current / :last :total Minecraft Skineistä',
        'subtitle-skin-tags' => 'Sivu :current / :last :total tagatuista Minecraft Skineistä',
        'sort_by' => 'Lajittelujärjestys',
        'latest' => 'Viimeisimmät skinit',
        'most_profiles' => 'Eniten käytetyt skinit',
        'profiles_today' => 'Eniten käytetty tänään',
        'profiles_this_week' => 'Eniten käytetty tällä viikolla',
        'profiles_this_month' => 'Eniten käytetty tässä kuussa',
        'default' => 'Oletusjärjestys',
        'this_month' => 'Lisätty tässä kuussa',
        'this_week' => 'Lisätty tällä viikolla',
        'today' => 'Lisätty tänään',
        'random' => 'Satunnainen',
        'similar' => 'Samankaltaiset skinit',
        'no_similar_skins' => 'Samankaltaisia skinejä ei löytynyt vielä.',
        'favorite' => ':count suosikki:count suosikit',
    ],
    'skin-tags' => [
        'faq' => 'Mitä tagit ovat?',
        'about' => 'Tunnisteet ovat tapa lisätä merkityksellisiä kategorioita skineille. Lisäämällä tunnisteita voit löytää lisää skiniä pidät helposti!',
        'guidelines' => [
            'good' => [
                'title' => 'Yleiset ohjeet hyvistä tunnisteista ovat:',
                'short' => 'Lyhyt',
                'descriptive' => 'Kuvaileva',
                'spelled' => 'Oikein kirjoitettu',
            ],
            'bad' => [
                'title' => 'Älä lisää tunnisteita, kuten:',
                'general' => 'Liian yleinen',
                'specific' =>  'Liian tarkka',
                'too-many-tags' =>  'Pitäisi olla kolme erillistä tagia',
                'spelling' => 'Pitäisi olla :example',
            ],
        ],
        'toast' => [
            'added' => 'Tunniste ”:tag” lisätty äänestykseen',
            'removed' => 'Tunniste ”:tag” on poistettu',
            'upvote' => 'Ylä-ääni ”:tag”',
            'downvote' => 'Alaääni ”:tag”'
        ],
        'vote' => [
            'up' => 'Ylä-ääni',
            'down' => 'Alaääni',
            'remove' => 'Poista ääni',
        ],
    ],
    'contact' => [
        'contact' => 'Yhteystiedot',
        'email' => 'Voit vapaasti kirjoittaa meille osoitteeseen <a href="mailto:support@skinmc.net">support@skinmc.net</a> mistä tahansa kysymyksestä mitä sinulla on.',
        'faq' => 'Pyydämme ystävällisesti ensin tarkistaa <a href=":link">UKK sivu</a> jos kysymykseesi on jo vastattu siellä.',
        'other' => 'Muita tapoja ottaa yhteyttä',
        'other_discord' => 'Liity Discord palvelimeen ja ota yhteys muihin, juttele peleistä, jaa suosikkipaketit ja saa apua yhteisöltä.',
        'other_twitter' => 'Seuraa Twitterissä nähdäksesi milloin uusi päivitys tai ominaisuus on julkaistu, katso viikon skini ja paljon muuta.',
        'other_instagram' => 'Seuraa SkinMC:tä Instagramissa selataksesi ja löytääksesi uusia hienoja Minecraft Skinejä ja kuvia.',
        'other_facebook' => 'Ryhdy faniksi Facebookissa ja näe kaikki julkaisut, joihin voit kommentoida ja puhua muiden kanssa tutkiessasi Minecraftin sisältöä.'
    ],
    'about' => [
        'intro' => '<span>Sinun</span> <span>alustasi</span> <span></span> <span>Minecraft</span> <span>olemusta.</span>',
        'header_credit' => 'Kuva "Epic Nether Battle" by',
        'info' => 'Pidä kirjaa kaikesta.',
        'info_explainer' => 'Katso pelaajien nimi historia, katso heidän edellinen ulkoasu, lisää ne ystävänä, lataa ulkoasuja, ja jopa saada tiedot tilastot.',
        'card_find_title' => 'Etsi mikä tahansa minecrafter',
        'card_find_detail' => 'Aloita etsimällä valitsemaasi pelaajien käyttäjänimeä tai UUID:tä.',
        'card_view_title' => 'Katso, tallenna ja muokkaa',
        'card_view_detail' => 'Löysitkö ihon, josta pidät? Tallenna se lataamalla tai käyttämällä editoria tehdäksesi siitä oman.',
        'card_claim_title' => 'Vahvista vahvistus',
        'card_claim_detail' => 'Linkitä Minecraft-tilisi ja vaadi profiilisi avataksesi uusia viileitä ominaisuuksia!',
        'card_customise_title' => 'Muokkaa profiiliasi',
        'card_customise_detail' => 'Vahvistetut pelaajat voivat lisätä sosiaalisen median linkkinsä ja tehdä profiilinsa omaksi.',
        'card_friends_title' => 'Lisää ystäväsi',
        'card_friends_detail' => 'Hanki yhteys ystäviesi kanssa SkinMC:ssä ja näytä kaverilistasi profiilissa.',
        'card_history_title' => 'Käyttäjänimi ja ulkoasun historia',
        'card_history_detail' => 'Käytä lisähakua löytääksesi pelaajan käyttäjätunnuksen tai ulkoasun historian ja nähdäksesi sen.',
        'founders' => 'Perustajat',
        'founders_cofounder' => 'SkinMC:n toinen perustaja',
        'head_of_design' => 'Pääsuunnittelija',
        'head_of_code' => 'Pääkoodaaja',
        'feedback' => 'Lähetä meille palautetta',
        'faq' => 'Kysymyksiä Minecraftista, Skinsistä ja muusta? Lue usein kysytyt kysymykset ja vastaukset yleisimpiin kysymyksiin.',
        'faq_link' => 'Vieraile UKK keskuksessa',
        'contact' => 'Haluatko ottaa yhteyttä tai onko sinulla lisäkysymyksiä? Ota meihin suoraan yhteyttä.',
        'contact_link' => 'Ota meihin yhteyttä',

    ],
    'faq' => [
        'title' => 'UKK',
        'subtitle' => 'Usein kysytyt kysymykset',
        'help' => 'Tarvitsetko lisää apua?',
        'discord' => 'Liity Discord-palvelimeen keskustellaksesi muiden Minecraft-pelaajien kanssa.',
        'contact' => 'Ota meihin yhteyttä',
        'q' => [
            'change_skin_t' => 'Miten voin muuttaa Minecraft Skini?',
            'change_skin' => '
                <p>Muuttaaksesi Skin tee seuraavasti:</p>
                <ol>
                    <li>Vieraile osoitteessa <a href="https://my.minecraft.net/en-us/login/">https://my. inecraft.net/en-us/login/</a> ja kirjaudu sisään Mojang-tililläsi.</li><li>Kun olet kirjautunut sisään, valitse <b>"Skin"</b> vasemmasta valikosta.</li><li>Valitse sitten haluamasi malli ja lataa mielesi Ulkoasu</li>
                </ol>',
            'change_username_t' => 'Miten vaihdan Minecraftin käyttäjänimeni?',
            'change_username' => '
                <p>Muuttaaksesi käyttäjänimeäsi tee seuraavat:</p>
                <ol>
                    <li>Vieraile osoitteessa <a href="https://account.mojang.com/login" target="_blank" rel="nofollow">https://account. ojang.com/login</a> ja kirjaudu sisään Mojang-tililläsi.</li>
                    <li>Etsi Minecraft-profiilisi nimi ja paina <b>"(Kakku)"</b> painiketta</li>
                    <li>Seuraavalla sivulla syötä haluamasi uusi käyttäjätunnus.</li>
                    <li>Lopuksi vahvista muutokset kirjoittamalla salasanasi ja painamalla "Muuta nimi".</li>
                </ol>',
            'dl_t' => 'Miten voin ladata jonkun Minecraft Skin?',
            'dl' => '
                <p>Jos haluat ladata jonkun Minecraft Skin tehdä seuraavasti:</p>
                <ol>
                    <li>Paina hakupalkkia ja kirjoita pelaajan käyttäjätunnus, josta haluat ladata ulkoasun.</li>
                    <li>Profiilisivulla voit esikatsella ulkoasua</li>
                    <li>Klikkaa <strong>Lataa Ulkoasu</strong> -painiketta esikatselun alla</li>
                </ol>',
            'submit_q' => 'Miten voin lähettää skinin kokoelmaan?',
            'submit_a' => '<p>Ole hyvä ja täytä seuraava lyhyt lomake käyttäjätunnuksilla ja niiden luokalla, jonka haluat lisätä kokoelmiin. <a href="https://forms.gle/f4Jh5RpGfsHAZ5xE8" target="_blank">Kokoelman lähetyslomake</a>',
            'mcpe_t' => 'Voinko käyttää ihoa Minecraft PE:ssä?',
            'mcpe' => '
                <p>Kyllä. Jos haluat käyttää Skiniä Minecraft Pocket Editionissa, tee seuraavasti:</p>
                <ol>
                    <li>Avaa SkinMC. et älypuhelimessasi ja napauta hakupalkkia</li>
                    <li>Syötä pelaajan ulkoasun käyttäjänimi jonka haluat ladata</li>
                    <li>Napauta <strong>Lataa Ulkoasu</strong> -painiketta esikatselun alla </li>
                    <li>Avaa Minecraft PE ja napauta <strong>Profiili</strong> oikealla puolella</li>
                    <li>Napauta <strong>+</strong>, tai muokkaa hahmoa ja siirry "klassisen oletuksen välilehteen"</li>
                    <li>Napauta "omistettu", sitten "import", sitten "valitse uusi nahka"</li>
                </ol>',
            'change_times_t' => 'Kuinka usein voin vaihtaa käyttäjänimeäni?',
            'change_times' => '<p>Voit muuttaa Minecraftin käyttäjänimeä <strong>kerran</strong> joka <strong>30 päivä</strong>.</p>',
            'available_t' => 'Kun olen muuttanut käyttäjänimeni, milloin se tulee saataville muiden vaatia sitä?',
            'available' => '<p>Jos haluat muuttaa takaisin edelliseen käyttäjänimeesi, voit muuttaa <strong>30 päivän kuluttua.</strong> Kaikkien muiden on odotettava <strong>7 päivää</strong> (37 päivää vaihtamisen jälkeen), ennen kuin he voivat lunastaa vanhan käyttäjätunnuksesi. </p>',
            'username_history_t' => 'Voitko poistaa käyttäjätunnukseni historiasta?',
            'username_history' => '
                <p>Koska käyttäjätunnuksen historia on peräisin Mojangista, käyttäjätunnuksen historiaa ei voi poistaa. Mojang on aiemmin todennut, että heidän tarkoituksenaan oli, että aiemmat käyttäjätunnukset ovat nähtävissä1, ja että ne tarjoavat suoran menetelmän yleisön käyttää näitä tietoja2.</p>
                <p class="font-14">1<a href="https://help.minecraft.net/hc/en-us/articles/360034636712-Minecraft-Usernames" target="_blank" rel="noreferrer">https://help inecraft. et/hc/en-us/articles/360034636712-Minecraft-Usernames</a></p>
                <p class="font-14 mb-0">2<a href="https://twitter.com/dinnerbone/status/554739042529849345" target="_blank" rel="noreferrer">https://twitter. om/dinnerbone/status/554739042529849345</a> (Tweet archived 2 years ago: <a href="http://archive.is/TeAyj" target="_blank" rel="noreferrer">http://archive. s/TeAyj</a>)
                </p>',
        ],
    ],
    'avatars' => [
        'start' => [
            'title' => 'Luo oma Minecraft-avatar',
            'subtitle' => 'Käytä Minecraft avatar generaattori luoda hauska avatar mistä tahansa olemuksesta!',
            'avatar_face' => 'Kasvotyylinen profiilikuva',
            'avatar_bust' => 'Pommun tyylinen profiilikuva',
            'avatar_cube' => 'Kuution tyyli profiilikuva',
            'avatar_head3d' => 'Mukautettu 3D pää',
        ],
        'user' => [
            'title' => 'Valitse ulkoasu',
            'subtitle' => 'Syötä Minecraftin käyttäjätunnus avatarille, jonka haluat luoda',
            'form_label' => 'Minecraftin käyttäjätunnus',
            'form_submit' => 'Jatka',
        ],
        'output' => [
            'title' => 'Esikatsele ja tallenna',
            'subtitle' => 'Nauti uuden Minecraftin käyttämisestä',
            'download_info' => 'Onnellinen tuloksella? Aloita uuden hahmon käyttö lataamalla se tänne',
            'download_button' => 'Lataa profiilikuva',
            'avatar_style' => 'Profiilikuvan tyyli',
            'skin_username' => 'Ulkoasun käyttäjänimi',
            'change' => 'Muuta',
            'generate' => 'Luo',
            'avatar_colour' => 'Taustan väri',
            'avatar_colour_palette' => 'Paletti',
            'avatar_colour_basic' => 'Perus',
        ],
        'meta' => [
            'title' => 'Minecraft Avatar Generaattori',
            'description' => 'Minecraft Avatar Maker: luo mukautettuja Minecraft-profiilikuvia käyttäen Minecraftin ihoa',
        ],
    ],
    'totem' => [
        'title' => 'Mukautettu Minecraft Toteemi',
        'subtitle' => 'Käytä Minecraft Totemi generaattoria luodakseen mukautetun resurssipaketin, jossa on Kuolematon Totemi tahansa skinistä.',
        'download_info' => 'Oletko tyytyväinen esikatseluun? Valitse Minecraft-versiosi tallentaaksesi mukautetun resurssipaketin:',
        'meta' => [
            'title' => 'Minecraft Mukautettu Totemi Generaattori',
            'description' => 'Mukautetut Minecraft Totemit: generoi ja luo mukautettu Minecraft Resurssipaketti, jossa Kuolematon Totemi käyttää sinun tai muiden pelaajien Minecraft skiniä.',
        ],
        'type' => [
            'mini' => 'Mini versio skinistäsi!',
            'full' => 'Täysi versio skinistäsi!',
            'model3d' => '3d malli skinistäsi!',
            'add_designs' => 'Haluatko nähdä lisää malleja? Lähetä sinun suunnitteluehdotus täältä:'
        ]
    ],
    'achievement' => [
        'header' => [
            'title' => 'Luo oma Minecraft-saavutuksesi',
            'subtitle' => 'Käytä Minecraft Achievement Generator luoda oman mukautetun saavutuksen ja käyttää näyttää edistysaskeleita kaikessa, mitä haluat!',
        ],
        'generator' => [
            'yellow_text' => 'Keltainen teksti',
            'white_text' => 'Valkoinen teksti',
            'choose_icon' => 'Valitse kuvake',
            'face' => 'Minecraft kasvot kuvakkeen sijaan',
            'form_submit' => 'Lataa',
            'form_label' => 'Minecraftin käyttäjätunnus',
            'download' => 'Lataa',
            'embed' => 'Upota',
            'embed_copy' => 'Kopioi',
        ],
        'meta' => [
            'title' => 'Minecraft Saavutus Generaattori',
            'description' => 'Luo mukautettuja Minecraft-saavutuksia ja -parannuksia Achievement luojalla. Lataa kuva suoraan, käytä sitä foorumi allekirjoituksia, upotettu HTML tai BB koodi, ja paljon muuta',
        ],
    ],
    'armor' => [
        'header' => [
            'title' => 'Minecraft Haarniskajalustan Luoja',
            'subtitle' => 'Generoi ja luo oma mukautettu Minecraft haarniskajalusta. Luo erilaisia asentoja, sijoituksia, aseta esineitä ja paljon muuta.',
        ],
        'meta' => [
            'title' => 'Minecraft Haarniskajalustan Luoja',
            'description' => 'Generoi ja luo helposti mukautettuja Minecraft haarniskajalustoja. Muokkaaja auttaa sinua tekemään erilaisia asentoja, sijoituksia, asettaa kohteita, muokata skinejä ja paljon muuta.',
        ],
    ],
    'banner' => [
        'editor' => [
            'header' => [
                'title' => 'Minecraft Bannerin Muokkaaja',
                'subtitle' => 'Suunnittele ja luo omat Minecraft bannerit. Näitä voidaan käyttää koristamaan maailmasi tai käytetään yleisesti myös <a href="https://optifine.net" target="_blank" rel="nofollow">Optifine</a> viittana.',
            ],
            'meta' => [
                'title' => 'Minecraft Bannerin Muokkaaja',
                'description' => 'Luo ja suunnittele ikioma Minecraft-bannerisi, jossa on kaikki pelin kuviot ja värit! Niitä voidaan käyttää maailmasi koristeluun tai käyttää Optifine-viittana Banneriviitan avulla. Voit luoda antamiskoodeja bannereille tai kilville.',
            ],
        ],
        'gallery' => [
            'header' => [
                'title' => 'Minecraft Banneri Galleria',
                'subtitle' => 'Selaa galleriaa :count mukautettuja Minecraft bannereita. Voit käyttää Banneria viitana, joka tekee Minecraftin skinistäsi ainutlaatuisemman, tai käytä Banneria lippuna koristamaan maailmaasi.',
            ],
            'meta' => [
                'title' => 'Minecraft Banneri Galleria',
                'description' => 'Selaa galleriaa :count mukautettuja Minecraft bannereita. Voit käyttää Banneria viitana, joka tekee Minecraftin skinistäsi ainutlaatuisemman, tai käytä Banneria lippuna koristamaan maailmaasi.',
            ],
        ],
    ],
    'search' => [
        'meta' => [
            'title' => 'Hakutulokset: :search',
        ],
        'title' => 'Haun tulokset',
        'results' => 'Sivu :current :count tulos:|Sivu :current :count tulokset ',
        'time' => '(:time sekuntia)',
        'username_available' => 'Käyttäjätunnus saatavilla',
        'username_unavailable' => 'Käyttäjätunnus ei ole käytettävissä',
        'username_status' => 'Tila',
        'username_status_available' => 'Saatavuus',
        'username_status_unavailable' => 'Ei saatavilla',
        'username_searches' => 'Haut',
        'username_searches_count' => ':count / päivä',
        'username_available_disclaimer' => '*Ellei Mojang ole väliaikaisesti tai pysyvästi kieltänyt nimeä.',
        'no_results' => 'Profiileja ei löytynyt. Kokeile hakua UUID:llä muuttamalla hakutyyppiä.',
        'no_results_tags' => 'Tagattuja skinejä ei löytynyt. Kokeile hakea muilla tunnisteilla kuten \'sininen\', \'tyttö\', \'kettu\' jne...',
        'again' => 'Hae uudelleen',
        'sorry' => 'Aaaaanteeksi...',
        'view_profile' => 'Näytä profiili',
    ],
    'collection' => [
        'title' => 'Minecraftin ihonkeräys',
        'subtitle' => 'Selaa Minecraftin nahkojen kuratoidun kokoelman läpi.',
        'filters' => 'Suodattimet',
        'title_trending' => 'Nousussa',
        'title_all' => 'Kaikki Minecraft Olemukset',
        'skin_tags' => 'Tagattuja skinejä',
        'filters_skin_type' => 'Ulkoasun tyyppi',
        'filter_skin_type_steve' => 'Steven tyyppi',
        'filter_skin_type_alex' => 'Alex tyyppi',
        'cancel' => 'Peruuta',
        'apply' => 'Käytä',
        'username_minecraft_skin' => ':usernamen Minecraft iho',
        'user_downloads' => '<span class="fw-500">:downloads</span> download<span class="fw-500">:downloads</span> downloads',
    ],
    'favourites' => [
        'title' => 'Suosikit',
        'subtitle' => 'Tarkastele ja hallitse leikkejä, jotka olet tallentanut myöhemmin suosikkilistassa',
        'sort' => 'Lajittelujärjestys',
        'toast' => [
            'added' => 'Lisätty suosikkilistaasi',
            'removed' => 'Poistettu suosikkilistastasi'
        ],
        'skins' => [
            'button' => 'Skinit',
            'empty_headline' => 'Ei vielä suosikkiskinejä',
            'empty_subtitle' => 'Sinulla ei ole vielä yhtään skiniä tallennettu suosikkilistaasi. Käy palvelinsivulla ja löydä seuraava suosikkisi!',
            'empty_browse' => 'Selaa skinejä',
            'meta' => [
                'title' => 'Minun suosikkiskinit',
                'description' => 'Minun suosikiksi tallennetut Minecraft skinit',
            ],
        ],
        'servers' => [
            'button' => 'Palvelimet',
            'empty_headline' => 'Ei vielä suosikkipalvelimia',
            'empty_subtitle' => 'Sinulla ei ole vielä yhtään palvelinta tallennettu suosikkilistaasi. Käy palvelinsivulla ja löydä seuraava suosikkisi!',
            'empty_browse' => 'Selaa palvelimia',
            'meta' => [
                'title' => 'Minun suosikkipalvelimet',
                'description' => 'Minun suosikkini Minecraft palvelimet',
             ],
        ],

    ],
    'cape' => [
        'editor' => [
            'title' => 'Minecraft viitta muokkaaja',
            'subtitle' => 'Käytä Minecraft viitta muokkaajaa luodaksesi oman mukautetun viitan.',
            'meta' => [
                'title' => 'Minecraft Viitta Muokkaaja',
                'description' => 'Käytä Minecraft Viitta Muokkaajaa luodaksesi oman mukautetun viitan.',
            ],
        ],
        'list' => [
            'title' => 'Minecraft viitat',
            'subtitle' => 'Minecraftin viralliset viitat',
            'meta' => [
                'title' => 'Minecraft Capes -lista',
                'description' => 'Minecraft viittalista: Näytä kaikki viralliset Minecraft-viitat, kuten Mojang, Minecon, Persoonalliset, Spesiaali ja vanity viitat',
            ],
        ],
        'detail' => [
            'title' => ':cape Viitta',
            'info' => 'Viitan tiedot',
            'profile_list' => 'Profiilit, joilla on tämä teksti',
            'profiles' => ':profilit profiili|:profilit profilit',
            'meta' => [
                'title' => 'Minecraft Capes -lista',
                'description' => 'Minecraft cape lista: Näytä kaikki viralliset Minecraft viitat kuten Mojang, Minecon, Personal, Speical ja vanity viitat',
            ],
        ],
        'list-custom' => [
            'title' => 'Mukautettu Minecraft Viitat',
            'description' => 'Selaa ja katso mukautettuja viitat, jotka on luotu ja joita SkinMC jäsenet käyttävät.'
        ]
    ],
    'servers' => [
        'title' => 'Minecraft palvelimet',
        'subtitle' => 'Selaa ja tutki minecraft-palvelimia',
        'all' => 'Kaikki palvelimet',
        'manage_your_servers' => 'Hallinnoi palvelimiasi',
        'add_new_server' => 'Lisää uusi palvelin',
        'filters' => [
            'trending' => 'Nousussa',
            'updated' => 'Päivitetty',
            'new' => 'Uusi',
            'most_viewed' => 'Useimmin katsottu',
            'top_voted' => 'Top äänesti',
            'sorting' => 'Lajitellaan',
            'sort_by_latest' => 'Lajittele viimeisimmän mukaan',
            'sort_by_oldest' => 'Lajittele vanhimman mukaan',
            'categories' => 'Luokat',
            'server_location' => 'Palvelimen sijainti',
            'show_results' => 'Näytä tulokset',
            'show_more' => 'Näytä lisää',
            'show_less' => 'Näytä vähemmän',
            'clear_filters' => 'Tyhjennä suodattimet',
            'reviews' => 'Arvostelut',
            'sort_by_highest_rating' => 'Lajittele korkeimman arvosanan mukaan',
            'sort_by_lowest_rating' => 'Lajittele alimman arvosanan mukaan',
            'bedrock_and_java_support' => 'Bedrock ja Java tuki'
        ],
        'review-count' => ':count Arvostelu|:count Arvostelua',
        'meta' => [
            'title' => 'Minecraft Palvelinluettelo',
            'description' => 'Selaa ja tutki Minecraft-palvelinten listaa löytääksesi parhaan Minecraft-palvelin! Suodata viimeisin, suosituin ja paljon muuta',
        ],
        'reviews' => [
            'meta' => [
                'title' => 'Kirjoita arvostelu',
            ],
            'editing' => 'Muokkaat arvosteluasi :date. Haluatko poistaa arvostelun sen sijaan?',
            'welcome' => 'Hei :username. Kuinka oli kokonaiskokemuksesi :servername?',
            'subtitle' => 'Jätä kokonaispistemäärä aiemmasta kokemuksestasi palvelimen kanssa.',
            'scale' => [
                'great' => 'Loistava',
                'good' => 'Hyvä',
                'okay' => 'Okei',
                'meh' => 'Meh',
                'bad' => 'Huono',
            ],
            'rate-experience' => 'Arvioi seuraavaksi kokemuksesi näillä alueilla',
            'overall' => 'Yleinen',
            'server-team' => 'Palvelimen tiimi',
            'community' => 'Yhteisö',
            'experience' => 'Kokemus',
            'availablility' => 'Käyttöaika ja saatavuus',
            'shop' => 'Kauppa',
            'write-review-title' => 'Kirjoita arvostelu',
            'write-review-subtitle' => 'Jätä muutamia muistiinpanoja, voit korostaa mistä nautit, mikä teki kokemuksestasi erityisen, tai tarjota muutamia ehdotuksia.',
            'write-review-helper' => 'Kirjoita palvelimen arvostelu jakaaksesi kokemuksesi uusien pelaajien kanssa ja auta palvelimen omistajia palautteen kera.',
            'write-review-tips' => 'Tässä on muutamia vinkkejä',
            'submit-title' => 'Oletko valmis lähettämään arvostelusi?',
            'submit-subtitle' => 'Melkein valmista!',
            'submit-review' => 'Lähetä arvosteluni',
            'back' => 'Takaisin',
            'continue' => 'Jatka',
            'delete-title' => 'Oletko varma, että haluat poistaa arvostelusi?',
            'tos-checkbox-part-1' => 'Lähettämällä tämän lomakkeen hyväksyt SkinMC:n käyttöehdot, tietosuojakäytännön ja yhteisön ohjeet. Vahvistat myös, että kaikki tiedot ovat paikkansapitäviä ja noudattavat',
            'tos-checkbox-part-2' => 'arvosteluohjeita.',
            'tos-checkbox-part-3' => 'Arvostelusi julkaistaan lähettämisen jälkeen, mutta se voidaan tarkistaa.'
        ],
        'slots' => 'Paikat',
        'empty-helper' => 'Voit yrittää tehdä toisen haun tai',
        'empty' => 'Hmm täällä on vielä tyhjää.',
        'verified' => 'Vahvistettu',
        'review_translate_show_original' => 'Näytä alkuperäinen',
        'review_translate' => 'Käännä arvostelu',
        'description_translate' => 'Käännä kuvaus',
        'create' => [
            'welcome' => 'Tervetuloa',
            'basics' => 'Perusasiat',
            'categories' => 'Luokat',
            'social_links' => 'Sosiaaliset linkit',
            'trailer_video' => 'Traileri video',
            'images' => 'Kuvat',
            'images_description' => 'Voit ladata kuvia jälkikäteen, jotta voit esitellä mitä palvelin tarjoaa.',
            'submit' => 'Lähetä',
            'lets_get_your_server_added' => 'Lisätään palvelimesi.',
            'basics-subtitle' => 'Kerro ihmisille, mistä palvelimellasi on kyse.',
            'description' => 'Kuvaus',
            'description_tips' => 'Tässä on muutamia vinkkejä',
            'description_hint' => 'Kirjoita hyvä kuvaus palvelimellesi houkutellaksesi uusia pelaajia.',
            'categories-subtitle' => 'Valitse joitakin kategorioita palvelimellesi',
            'missing-category' => 'Puuttuva kategoria?',
            'social_links_description' => 'Missä pelaajat voivat olla yhteydessä palvelimeesi sosiaalisessa mediassa?',
            'trailer_video_description' => 'Esittele palvelimesi YouTube-videolla.',
            'trailer_video_hint' => 'Liitä videon URL-osoite tai ID:',
            'ready_to_submit_your_server' => 'Oletko valmis lähettämään palvelimesi?',
            'review-hint' => 'Lähettämisen jälkeen tiimi tarkistaa huolellisesti palvelimen listaushakemuksen. Sitten kun päätös, palvelin julkaistaan, tai muutoksia pyydetään ennen julkiseksi menoa.',
            'terms' => [
                'part-1' => 'Tämän lomakkeen lähettämällä sinä hyväksyt SkinMC:n käyttöehdot, yksityisyydensuojan ja yhteisön ohjeet. Vahvistat myös, että kaikki edellä mainitut tiedot ovat paikkaansapitäviä, olet seurannut asianmukaisesti',
                'part-2' => 'palvelimen asennusta koskevia vaatimuksia',
                'part-3' => 'ja että Minecraft-palvelimen omistaa ja sitä hallinnoi edustamasi taho.'
            ],
            'submit-application' => 'Lähetä hakemus',
            'video-id-helper' => [
                'part-1' => 'Videon ID on merkkijono numeroiden ja kirjainten jälkeen',
                'part-2' => 'Esimerkiksi, jos videon url on',
                'part-3' => ', sitten videon ID olisi'
            ],
            'welcome_description' => 'Tässä vaiheessa lähdemme aloittamaan palvelimen lisäämisen. Kerro meille hieman siitä, kirjoita kuvaus, ja seuraavassa vaiheessa voit ladata joitakin kuvia.'
        ],
        'copy_server_ip' => 'Kopioi palvelin IP',
        'all_minecraft_servers' => 'Kaikki Minecraft Palvelimet',
        'promo' => [
            'title' => 'Ylläpidätkö Minecraft-palvelinta?',
            'ready_to_list_your_server' => 'Oletko valmis listaamaan palvelimesi?',
            'everything_you_need' => 'Kaikki mitä tarvitset palvelimesi kasvattamiseen',
            'list_your_server' => 'Listaa palvelimesi',
            'list_your_server_description' => 'Luo listaus palvelimellesi, lisää kuvia, sosiaalista mediaa ja paljon muuta.',
            'find_players' => 'Etsi pelaajia',
            'find_players_description' => 'Etsi ja tavoita uusia pelaajia liittymään palvelimellesi ja kasvattamaan yhteisöäsi.',
            'get_reviews' => 'Hanki arvosteluja',
            'get_reviews_description' => 'Pyydä yhteisöäsi arvostelemaan palvelimesi ja palkitse heidät pelissä.',
            'why_list_on_skinmc' => 'Miksi sinun pitäisi listata palvelimesi SkinMC:ssä',
            'others' => 'Muut',
            'quality_check_and_confirmation' => 'Laadun tarkistus ja vahvistus',
            'quality_check_description' => 'Tiimimme arvioi jokaisen palvelimen laadun takaamiseksi.',
            'verified_players' => 'Arvostelut vahvistetuista Minecraft-pelaajista',
            'verified_players_description' => 'Kerää aitoja pelaajien arvosteluja laillisilta tileiltä Votifier integraatiolla.',
            'international' => 'Kansainvälinen',
            'international_description' => 'Käännösominaisuuksilla listauksesi on saatavilla useammalle pelaajalle.',
            'server_listing_page' => 'Tehokas Palvelin listaus sivu',
            'server_listing_page_description' => 'Lisää kuvia, kuvaustekstejä, youtube videoita, ja korosta, miksi pelaajien pitäisi liittyä palvelimellesi.',
            'social_connections' => 'Sosiaalisen median yhteydet',
            'social_connections_description' => 'Yhdistä palvelimet sosiaalitilejä ja näytä uusille pelaajille, mistä he voivat löytää sinut.',
            'verified_badge' => 'Vahvistusmerkki',
            'verified_badge_description' => 'Aidot palvelimet voivat hakea vahvistusmerkkiä.',
            'owner_profile' => 'Omistajan profiili',
            'owner_profile_description' => 'Lisää henkilökohtainen kosketus, täyttämällä oman mukautetun profiilin.',
            'categories' => 'Luokat',
            'categories_description' => 'Eri luokkia, jotta palvelimesi löytäminen olisi helpompaa.',
            'vote' => 'Äänestä',
            'vote_description' => 'Pyydä käyttäjiä äänestämään palvelintasi.',
            'fair_listings' => 'Oikeudenmukaiset listaukset',
            'fair_listings_description' => 'Palvelin listauksia ei voida keinotekoisesti tehostaa SkinMC:n tuloksissa.',
            'support' => '24 tunnin tuki',
            'support_description' => 'Tarvitset apua tai sinulla on kysyttävää? Voit aina ottaa yhteyttä ja saada nopean vastauksen.',
            'custom_features' => 'Mukautetut ominaisuudet',
            'custom_features_description' => 'Puuttuuko palvelimeltasi jokin ominaisuus? Avaa lippu, niin me toteutamme sen.',
            'faq' => [
                'title' => 'Vastauksia kysymyksiisi',
                'suited-question' => 'Onko Minecraft Palvelimeni SkinMC:lle sopiva?',
                'suited-answer' => 'Minecraft Pelaajat SkinMC:ssä rakastavat löytää uusia kokemuksia, sisältöä ja sitoutua yhteisöihin. Alustalla löydät laajan valikoiman erilaisia, ainutlaatuisia, hauskoja Minecraftin palvelimia. Suuresta verkosta jopa pieneen selviytymispalvelimeen, se voi parantaa jonkun päivän!',
                'get-started-question' => 'Miten pääsen alkuun?',
                'get-started-answer' => 'Lisäämällä Minecraft Palvelimesi SkinMC Palvelin Listaan on erittäin helppoa! Sinun täytyy ensin luoda tili, jos et ole jo tehnyt, ja sitten seuraa asennusohjeita saadaksesi palvelimen listatuksi. Lisää muutama kuva ja mukava kuvaus, ja palvelin julkaistaan ilman aikaa!',
                'players-question' => 'Miten voin saada enemmän pelaajia Minecraft Palvelimelleni?',
                'players-answer' => 'Yhteisön rakentaminen on pitkän kestävän Minecraft Palvelimen tärkein osa. Käytä Minecraftin Palvelin Listaa SkinMC:ssä löytääksesi uuden yleisön ja jatkaaksesi yhteisösi rakentamista. Pyydä pelaajia suosittelemaan palvelintasi tai jakamaan listasi sosiaalisen median alustoille. Hyvien arvostelujen keräämisellä voi myös olla tärkeä rooli, kun halutaan saada hyvä Palvelin listaus, joka houkuttelee uusia pelaajia.',
                'more-question' => 'Minulla on enemmän kysymyksiä. Mistä voin saada apua?',
                'more-answer' => 'Voit ottaa yhteyttä SkinMC:hen milloin tahansa, 24 tuntia vuorokaudessa, joko käyttämällä apupainiketta, neuvontapalvelua tai liittymällä Discord palvelimeen.'
            ],
            'ready_to_list_description' => 'Lisää Minecraft Palvelimesi SkinMC Palvelin Listaan vain muutamassa minuutissa. Jos tarvitset apua, voit ottaa yhteyttä ympäri vuorokauden ja saada vastauksia nopeasti.'
        ],
        'manage' => [
            'index' => [
                'welcome' => 'Tervetuloa takaisin, :username',
                'your_servers' => 'Sinun palvelimesi',
                'reviews_today' => 'Arvostelut tänään',
                'no_reviews_today' => 'Ei arvosteluja tänään',
                'no_reviews_text' => 'Palvelimesi ei ole saanut tänään yhtään arvostelua. Miksi et pyydä pelaajiasi lähettämään yhtä?',
                'tips' => [
                    'title' => 'Vinkkejä',
                    'description-title' => 'Kirjoita hyvä palvelimen kuvaus',
                    'description-body' => 'Hyödyllisiä vinkkejä ja neuvoja kirjoittaa hyvä palvelimen kuvaus.',
                    'images-title' => 'Lisätään palvelimen kuvia',
                    'images-body' => 'Tee palvelin listauksestasi erottuva suurien kuvien avulla.'
                ]
            ],
            'listings' => [
                'title' => 'Minecraft palvelimesi (:count)'
            ],
            'insights' => [
                'title' => 'Näkymät'
            ],
            'edit_server' => 'Muokkaa palvelinta',
            'listing' => 'Listaus',
            'to_do' => 'Muistilista',
            'last_update' => 'Viimeisin päivitys',
            'add_more_photos_to_publish' => 'Lisää kuvia julkaistavaksi',
            'looks_empty_here' => 'Näyttää tyhjältä täällä.',
            'get_started_by_adding_a_new_server' => 'Aloita lisäämällä uusi palvelin?'
        ],
        'status' => [
            'approved' => 'Hyväksytty',
            'pending_approval' => 'Odottaa hyväksyntää',
            'published' => 'Julkaistu',
            'in_review' => 'Tarkastettavana'
        ]
    ],
    'editor' => [
        'import' => [
            'title' => 'Tuo Skini',
            'import_by_username' => 'Tuo käyttäjänimellä',
            'import_button' => 'Tuo',
            'drag' => 'Vedä ja pudota skini tähän, tai klikkaa',
            'click' => 'Valitse kuva'
        ],
        'download' => [
            'error' => [
                'no-data' => 'Skinin tietoja ei annettu. Ole hyvä ja yritä uudelleen.',
                'invalid-format' => 'Skinin tietojen muoto on virheellinen. Ole hyvä ja yritä uudelleen.',
                'invalid-data' => 'Skinin tiedot ovat vioittuneet. Ole hyvä ja yritä uudelleen.',
                'generic' => 'Jokin meni pieleen skiniä ladattaessa. Ole hyvä ja yritä uudelleen.',
            ],
        ],
        'draw' => 'Piirrä',
        'eyedropper' => 'Pipetti',
        'fill' => 'Täytä',
        'move' => 'Siirrä',
        'decrease_brightness' => 'Vähennä kirkkautta',
        'increase_brightness' => 'Lisää kirkkautta',
        'erase' => 'Pyyhi',
        'undo' => 'Astu taaksepäin (CTRL+Z)',
        'redo' => 'Astu eteenpäin (CTRL+Y)',
        'default_view' => 'Oletusnäkymä',
        'zoom_in' => 'Suurenna (CTRL +)',
        'zoom_out' => 'Pienennä (CTRL -)',
        'saved' => 'Viimeksi tallennettu juuri nyt',
        'saving' => 'Tallennetaan automaattisesti...',
        'save_error' => 'Tapahtui virhe',
        'new_skin' => 'Uusi skini',
        'previous_skins' => 'Edelliset skinit',
        'backed_up_title' => 'Automaattisesti tallennetut skinit',
        'backed_up_info' => 'Tilapäisesti varmuuskopioitu paikalliseen tallennustilaan.',
        'backed_up_empty_title' => 'Täällä on tyhjää',
        'backed_up_empty_info' => 'Kun aloitat skinin muokkauksen, näet 32 viimeksi muokattua skiniä täällä.',
        'backed_up_skins_count' => '32 käytetyn skinin varmuuskopiot',
        'backed_up_skins_count_info' => 'Voit varmuuskopioida jopa 32 skiniä. Kun saavutat 32 skiniä, vanhempi iho korvataan uudella skinillä.',
        'layers' => 'Kerrokset',
        'body' => [
            'title' => 'Runko',
            'overlay' => 'Päällikerros',
            'head' => 'Pää',
            'torso' => 'Yläruumis',
            'l_arm' => 'Vasen käsi',
            'r_arm' => 'Oikea käsi',
            'l_leg' => 'Vasen jalka',
            'r_leg' => 'Oikea jalka',
        ],
        'model' => 'Malli',
        'steve' => 'Steve',
        'alex' => 'Alex',
        'stance' => [
            'title' => 'Sijainti',
            'default' => 'Oletus',
            'walk' => 'Kävele',
            'run' => 'Suorita',
            'hug' => 'T-iske',
            'fly' => 'Lento',
        ],
        'fullscreen' => 'Koko näyttö',
        'fullscreen_exit' => 'Poistu kokoruudusta',
        'grid' => 'Ruudukko',
        'show_grid' => 'Näytä ruudukko',
        'download' => [
            'title' => 'Tallenna & Lataa',
            'subtitle' => 'Skinmc Tili',
            'description' => 'Haluatko luoda ilmaisen SkinMC-tilin, jonka avulla voit tallentaa ihosi ja tulevaisuudennäkymät pilveen?',
            'start_description' => 'Aloita lataus suoraan tallentamatta pilveen',
            'start' => 'Lataa oletus',
        ],
        'help' => [
            'title' => 'Minecraft Skini Muokkaaja',
            'about' => 'Luo ja muokkaa mukautettua Minecraft skiniä helposti SkinMC-editorilla. Voit valita Steven ja Alexin malleista, tuoda skinejä tiedostosta tai käyttäjätunnuksesta ja luoda oman Minecraft Skinin.',
            'draw' => 'Piirrä kynätyökalulla. Valitse värivalikoimasta väri, jota haluat käyttää sen kanssa.',
            'eyedropper' => 'Valitse pipetillä väri skinistäsi ja lisää se nykyiseen palettiisi.',
            'fill' => 'Täytä koko skinialue täyttötyökalulla. Valitse väri ennen kuin käytät täyttöä.',
            'move' => 'Siirrä ja liiku skinieditorin kankaalla siirtotyökalulla.',
            'decrease_brightness' => 'Vähennä tällä hetkellä aktiivisen värin kirkkautta.',
            'increase_brightness' => 'Lisää tällä hetkellä aktiivisen värin kirkkautta.',
            'erase' => 'Pyyhi toissijaisen päällikerroksen piirtämät pikselit.',
            'minimap' => 'Minimap',
            'minimap_info' => 'The minimap can show you the skin texture in a flat view while in 3D mode. In 2D mode the minimap switches to a 3D preview of your skin. You can zoom in and out.',
            'autosave' => 'Autosave',
            'autosave_info' => 'The autosave feature saves your skin automatically every 30 seconds. You can access the autosaved skins in the editor by pressing the folder icon, and choosing "Previous skins".',
            '2d_editor' => '2D and 3D editor',
            '2d_editor_info' => 'Toggle between editing your Minecraft skin in 2D or 3D mode.',
        ],
    ],
    'account' => [
        'level' => 'Taso',
        'level_history' => 'Taso historia',
        'xp' => 'XP',
        'my_xp' => 'Minun XP',
        'xp_to_next_level' => ':xp XP seuraavalle tasolle',
        'xp_info' => 'Mitä ovat XP?',
        'xp_info_tooltip' => 'XP:tä on ansaittu erilaisilla toiminnoilla, kuten lisäämällä tageja skineille, kutsumalla ystäviä, kommentoimalla ja paljon muuta. Jokaisella ansaitulla XP:llä voit tasoittaa ylös ja avata siistejä juttuja!',
        'settings' => [
            'title' => 'Tili',
            'show_profile' => 'Siirry profiiliin',
            'friends' => 'Ystävät',
            'friends_detail' => 'Pysy yhteydessä käyttämällä ystäväsi listaa SkinMC.',
            'security' => 'Turvallisuus',
            'security_detail' => 'Päivitä kirjautumissalasanasi ja säilytä tilisi turvassa',
            'social' => 'Sosiaalisen median tilit',
            'social_detail' => 'Muokkaa profiiliasi lisäämällä sosiaalisen median',
            'link' => 'Yhdistä Minecraft-tili',
            'link_detail' => 'Linkitä Minecraft-tilisi ja tallenna profiilisi.',
            'logout' => 'Haluatko kirjautua ulos SkinMC tililtäsi?',
            'automatic_backups' => 'Automaattiset skinin varmuuskopiot',
            'automatic_backups_info' => 'SkinMC plus jäsenenä sinun skinisi varmuuskopioidaan päivittäin.',
        ],
        'capes' => [
            'title' => 'SkinMC Minecraft Viitta',
            'description' => 'Voit käyttää mitä tahansa haluamaasi viittaa pelissä SkinMC Capes avulla ilmaiseksi.',
            'drop' => 'Vedä ja pudota viitta tähän',
            'drop-hint' => 'Mitat 64x32px',
            'select' => 'Valitse kuva',
            'upload-cape' => 'Lataa & käytä viittaa',
            'save-and-use' => 'Tallenna & käytä',
            'uploaded-cape' => 'Ladattu viitta',
            'no-cape' => 'Ei viittaa',
            'remove-cape' => 'Poista viitta',
            'download' => 'Lataa SkinMC Modi nähdäksesi sinun ja muiden pelaajien viitat pelissä.',
            'learn-more' => 'Lue lisää',
            'link-account' => 'Ole hyvä ja linkitä Minecraft-tilisi ladataksesi viitan.',
            'updated' => 'Viittasi on päivitetty!',
            'removed' => 'Viittasi on poistettu.',
            'active' => 'Viittasi on aktivoitu!'
        ],
        'favourite' => 'Suosikki',
        'remove_favourite' => 'Poista suosikki',
        'added_to_favourites' => 'Lisätty suosikkeihin',
        'removed_from_favourites' => 'Poista suosikeista',
        'welcome' => 'Mukava nähdä sinua!',
        'view-profile' => 'Näytä profiilini',
        'security' => [
            'title' => 'Turvallisuus',
            'email' => 'Sähköposti osoite',
            'email-title' => 'Päivitä sähköpostiosoitteesi.',
            'save' => 'Tallenna',
            'password' => 'Salasana',
            'password-title' => 'Vaihda salasanasi milloin tahansa.',
            'social-provider' => 'Jotta voit päivittää tilitietosi, kuten salasanasi, ole hyvä ja vieraile kirjautumispalveluntarjoajasi:',
            'social-provider-email' => 'Yhdistetty sähköpostiosoitteesi kirjautumispalveluntarjoajasi kanssa',
            'social-provider-connected' => 'Tällä hetkellä yhdistetyt kirjautumispalveluntarjoajat',
            'current-password' => 'Nykyinen salasana',
            'forgot' => 'Unohditko salasanasi?',
            'edit' => 'Muokkaa',
            'delete' => 'Poista tilini',
            'account-deletion' => 'Poista SkinMC tilisi.',
            'delete-info' => 'Ole hyvä ja vahvista jatkaaksesi',
            'delete-confirmation' => 'Tilisi poistaminen on peruuttamatonta. Kaikki henkilökohtaiset tietosi ja sisältösi, kuten viestit, suosikit, ladatut viitat, mukautukset jne. poistetaan, eikä niitä voi palauttaa.',
            'delete-confirmation-info' => 'Anna salasanasi jatkaaksesi',
            'yes-confirm-delete' => 'Kyllä, vahvista poisto',
            'account-successfully-deleted' => 'Tilisi ja tietosi ovat poistettu onnistuneesti.'
        ],
        'social' => [
            'title' => 'Sosiaaliset tilit',
            'edit' => 'Muokkaa',
            'save' => 'Tallenna',
            'link-account' => 'Linkitä Minecraft-tilisi SkinMC:hen näyttääksesi sosiaaliset linkkisi profiilissasi.',
            'finish-setup' => 'Viimeistele määritys',
            'connect-account' => 'Yhdistä tilisi',
            'connect-description' => 'Valitse mitkä tilit haluat yhdistää ja avata erityisiä SkinMC integraatioita.',
            'empty' => 'Ei lisättyjä tilejä',
            'empty-description' => 'Sosiaalisen median tilisi näkyvät täällä ja julkisessa profiilissasi. Kun ne on lisätty, ne lisäävät sivusi personointia ja mahdollistavat integraatiot.',
            'connect' => 'Yhdistä',
            'username' => 'käyttäjänimi',
            'spotify' => 'Lisää Spotify-käyttäjänimesi näyttääksesi Spotifyn tiedot profiilissasi.',
            'discord' => 'Lisää Discord-käyttäjänimesi näyttääksesi Discordin tiedot SkinMC profiilissasi.',
            'youtube' => 'Lisää YouTube-kanavasi SkinMC:hen, joka näyttää YouTube-kanavasi profiilissasi.',
            'youtube-format' => 'Käytä seuraavaa muotoa riippuen kanavan linkistä:',
            'twitter' => 'Syötä X (entinen Twitter) käyttäjänimesi näyttääksesi sen profiilissasi.',
            'bluesky' => 'Anna Bluesky-tunnuksesi esim. username.bsky.social näyttääksesi Bluesky-profiilisi profiilissasi.',
            'twitch' => 'Anna Twitch-käyttäjänimesi, jotta voit näyttää Twitch-kanavasi profiilissasi.',
            'reddit' => 'Anna Reddit-käyttäjänimesi, jotta voit näyttää Reddit profiilisi profiilissasi.',
            'github' => 'Anna GitHub-käyttäjänimesi, jotta voit näyttää GitHub profiilisi profiilissasi.',
            'telegram' => 'Anna Telegram-käyttäjänimesi, jotta voit näyttää Telegram profiilisi profiilissasi.',
            'tiktok' => 'Anna TikTok-käyttäjänimesi, jotta voit näyttää TikTok profiilisi profiilissasi.',
            'snapchat' => 'Anna Snapchat-käyttäjänimesi, jotta voit näyttää Snapchat profiilisi profiilissasi.',
            'instagram' => 'Anna Instagram-käyttäjänimesi, jotta voit näyttää Instagram profiilisi profiilissasi.',
            'facebook' => 'Anna Facebook-käyttäjänimesi, jotta voit näyttää Facebook profiilisi profiilissasi.',
            'includes_skinmc_plus_benefits' => 'Sisältää SkinMC plus hyödyt',
        ],
        'recover' => [
            'title' => 'Palauta tilisi',
            'subtitle' => 'Syötä uusi salasana ja vahvista se viimeistelläksesi tilin palautuksen.',
            'new_password' => 'Uusi salasana',
            'repeat_new_password' => 'Toista uusi salasana',
            'submit' => 'Palauta tili',
        ],
        'customise' => [
            'title' => 'Mukauta profiiliasi',
            'description' => 'Lisää sosiaalinen mediasi, valitse emoji, määritä sijaintisi ja muuta',
            'information' => 'Tietoja',
            'preview' => 'Esikatselu',
            'location' => [
                'title' => 'Sijainti',
                'description' => 'Valitse minkä sijainnin, sinä haluat lisätä profiiliisi.',
            ],
            'biography' => [
                'title' => 'Tietoja minusta',
                'description' => 'Kirjoita bio profiilillesi.',
            ],
            'status' => 'Tila',
            'status-toggle' => 'Näytä minun online tila',
            'emoji' => 'Emoji',
            'name-history-toggle' => 'Tee käyttäjätunnuksen historiasta yksityinen',
            'name-history-info' => 'Minecraftin käyttäjätnimesi on tällä hetkellä',
            'name-history-toggle-on' => 'yksityinen',
            'name-history-toggle-off' => 'julkinen',
            'theme' => 'Profiilin teema',
            'theme-primary' => 'Ensisijainen',
            'theme-secondary' => 'Toissijainen',
            'appearance' => 'Ulkonäkö',
        ],
        'link' => [
            'manage' => 'Hallitse linkitettyä Minecraft-tiliä',
            'description' => 'Katso ja hallinnoi linkitettyä Minecraft-tiliäsi',
            'title' => 'Yhdistetty Minecraft-tili',
            'current' => 'Tällä hetkellä linkitetty Minecraft-tili.',
            'status' => 'Sinulla on nyt täysi pääsy kaikkiin SkinMC ominaisuuksiin!',
            'linked' => 'Linkitetty',
            'disconnect' => 'Katkaise yhteys',
            'disconnect-title' => 'Katkaise Minecraft-tilin yhteys',
            'disconnect-info' => 'Oletko varma, että haluat katkaista yhteyden Minecraft-tiliisi?',
            'disconnect-features' => 'Menetät pääsyn kommentointiin, mukauttamiseen ja muihin ominaisuuksiin, jotka vaativat linkitetyn Minecraft-tilin. Jotta voit käyttää näitä uudelleen, sinun täytyy linkittää Minecraft-tili.',
            'disconnect-following' => 'Minecraft-tilisi katkaiseminen poistaa pysyvästi kaikki seuraavat profiilit.',
            'disconnect-posts' => 'Luomasi syöte julkaisut ja tykkäykset poistetaan.',
            'can-not-undo' => 'Tätä ei voi peruuttaa.',
            'are-you-sure' => 'Oletko varma?',
            'confirm' => 'Kyllä, vahvista yhteyden katkaisu',
            'cancel' => 'Ei, peruuta',
            'success' => 'Tilisi katkaistiin onnistuneesti!'
        ],
        'finish-setup' => [
            'title' => 'Viimeistele tilin määritys',
            'description' => 'Viimeistele tilin määritys ja saat täyden pääsyn kaikkiin ominaisuuksiin linkittämällä Minecraft-tilisi SkinMC:hen.',
            'link' => 'Yhdistä Minecraft-tili',
            'get-started' => 'Aloita',
            'skip' => 'Ohita',
            'claim' => 'Lunasta profiilisi',
            'customise' => 'Mukauta sivuasi',
            'social' => 'Lisää sosiaalisia linkkejä',
            'comment' => 'Pääsy kommenttijärjestelmään',
            'direct_message' => 'Lähetä suoria viestejä',
            'feed' => 'Julkaise tilapäivitykset syötteeseen',
            'follow' => 'Seuraa ystäviäsi',
            'badge' => 'Profiilissasi näkyvä merkki',
            'cape' => 'Mukautettu Minecraft Viitta',
            'backup' => 'Automaattinen skinin varmuuskopio',
            'more' => 'Ja muuta...'
        ],
        'skins' => [
            'title' => 'Hallinnoi skinejä',
            'toggle' => 'Skinin näkyvyys kytketty',
        ],
        'invite' => [
            'title' => 'Minun kutsut',
            'headline' => 'Kutsu ystäviäsi',
            'info' => 'Luo ystäväsi kanssa jaettava kutsukoodi. Kun he hyväksyvät sen, molemmat ansaitsevat ylimääräistä XP:tä!',
            'description' => 'Luo kutsu ystävillesi ja ansaitte molemmat ylimääräistä XP:tä.',
            'generate' => 'Luo kutsukoodi',
            'empty' => 'Et ole vielä luonut yhtään kutsua.',
            'code' => 'Koodi',
            'expiry' => 'Jokainen koodi toimii kerran.',
            'status' => [
                'title' => 'Tila',
                'pending' => 'Odottaa',
                'accepted' => 'Hyväksytty'
            ],
            'add_invite' => [
                'button' => 'Onko sinulla kutsu?',
                'title' => 'Lisää kutsukoodi',
                'redeem' => 'Lunasta kutsu',
            ],
            'share' => 'Lähetä ystävällesi kutsulinkki'
        ],
        'emoji' => [
            'title' => 'SkinMC Emoji',
            'introducing' => 'Esittelyssä',
            'info' => 'Mukauta profiiliasi emojien avulla. Avaa lisää, kun nouset tasolle.',
            'unlocked_at' => 'Avattu tasolla :level',
            'unlocks_at' => 'Saavuta taso :level avataksesi',
            'turn_off' => 'Näytä emoji'
        ]
    ],
    'notifications' => [
        'title' => 'Ilmoitukset',
        'view_all' => 'Näytä kaikki',
        'view_all_notifications' => 'Näytä kaikki ilmoitukset',
        'image' => 'Ilmoituksen kuva',
        'archived' => 'Arkistoitu',
        'inbox' => 'Saapuneet',
        'empty' => [
            'title' => 'Olet ajan tasalla!',
            'text' => 'Uudet ilmoitukset näkyvät täällä.',
            'text-archived' => 'Arkistoidut ilmoitukset näkyvät täällä.',
        ],
        'action' => [
            'archive' => 'Siirrä arkistoon',
            'unarchive' => 'Palauta arkistosta',
            'open' => 'Avaa napauttamalla',
        ],
        'toast' => [
            'archive' => 'Ilmoitus siirretty arkistoon',
            'unarchive' => 'Ilmoitus siirretty saapuneisiin',
            'undo' => 'Kumoa',
        ]
    ],
    'error' => [
        'offline' => [
            'title' => 'Ei internetyhteyttä',
            'subtitle' => 'Yhteytesi katkesi. Tarkista yhteytesi ja lataa sivu uudelleen yrittääksesi uudelleen.',
            'try_again' => 'Yritä uudelleen'
        ],
        '404' => [
            'title' => '404 — Sivua ei löytynyt.',
            'subtitle' => 'Hm, näyttää siltä, että tässä paikassa ei löytynyt mitään. Ehkä yritä palata tai aloita uusi haku?',
            'try_again' => 'Takaisin etusivulle'
        ],
    ],
    'heads' => [
        'list' => [
            'meta' => [
                'title' => 'Minecraft päät tietokanta',
                'description' => 'Tutki Minecraft päättietokantaa koristellaksesi maailmasi tai luodaksesi oman komennon. Näytä viralliset päät, pelaajien päät ja mukautetut päät, joissa on tekstuurit jotka eivät koskaan muutu.'
            ],
            'header' => [
                'title' => 'Minecraft päät',
                'subtitle' => 'Tutki Minecraft päätietokantaamme koristellaksesi maailmasi tai luodaksesi oman antamis komennon. Pelaajan päät näyttävät käyttäjän käyttämän skinin ja voivat muuttua, kun käyttäjä päivittää skininsä. Mukautetut päät on linkitetty Mojangin skini tiedostoon eivätkä koskaan muutu. Mukautetut päät on kutsuttava komentokuution avulla, koska komento on hyvin pitkä.',
            ],
            'count' => [
                'heads' => ':päät pää|:päät päät',
            ],
            'customheads' => [
                'title' => 'Mukautetut päät',
                'description' => 'Mukautetut päät käyttävät suoraa polkua tekstuuritiedostoon Mojang-palvelimella. Siksi tekstuuria ei koskaan poisteta eikä päät koskaan muutu.',
                'version' => 'Minecraft 1.8 tai uudempi',
            ],
            'playerheads' => [
                'title' => 'Pelaajan päät',
                'description' => 'Pelaajan päät käyttävät Minecraft-pelaajan nykyistä skini koostumusta. Koska ne ovat käyttäjätunnuksen perustaa, kun pelaaja muuttaa nimeään tai skiniä, pää muuttuu.',
                'version' => 'Kaikki Minecraft versiot',
            ]
        ],
    ],
    'mod' => [
        'title' => 'SkinMC Modi: Ilmaiset mukautetut viitat',
        'headline' => 'Esittelyssä SkinMC Modi lisää enemmän mukauttamista',
        'description' => 'Antamalla takaisin Minecraft-yhteisölle ilmaisella modilla, joka antaa pelaajille mahdollisuuden mukauttaa peliä enemmän mukautetuilla viitoilla, jotka ovat kaikkien modia käyttävien saatavilla ja näkyvillä.',
        'download' => 'Lataa nyt',
        'download-title' => 'Lataa modi',
        'requires' => 'Vaatii',
        'select-version' => 'Valitse Minecraft versio',
        'get-started' => 'Aloittaminen on yksinkertaista',
        'step-1' => '1. Hanki modi',
        'step-1-detail' => 'Asenna Fabric, sitten lataa modi sinun pelin versioon ja asenna se laittamalla jar modit kansioon.',
        'step-2' => '2. Linkitä tilisi',
        'step-2-detail' => 'Jos et ole vielä rekisteröidy/kirjautunut sisään ja yhdistä Minecraft-tilisi SkinMC:hen.',
        'step-3' => '3. Lataa viittasi',
        'step-3-detail' => 'Mene tilillesi ja lataa mukautettu viitta. Se näkyy pelissä.',
        'all-versions' => 'Kaikki versiot',
        'latest' => 'Viimeisin',
        'logged-in' => 'Lataa viittasi',
        'mirror' => 'Peili',
        'download-via' => 'Lataa:',
        'curseforge' => 'CurseForge',
    ],
    'app' => [
        'title' => 'SkinMC Android-sovellus',
        'headline' => 'Sano hei SkinMC Android sovellukselle.',
        'play-store-attribution' => 'Google Play ja Google Play -logo ovat Google LLC: n tavaramerkkejä.',
        'features' => 'Kätevät ominaisuudet tien päällä',
        'feature-qr' => 'Sisäänrakennettu QR-koodinlukija',
        'feature-qr-detail' => 'Käytä rakennettua QR-koodinlukijaa helposti saadaksesi skinin työpöydältä sovellukseen, tai skannaa ystäväsi mukautetun profiilin QR-koodi.',
        'feature-files' => 'Tallentaa suoraan tiedostoihin',
        'feature-files-detail' => 'Android-tiedostojen hallinnan avulla sovellus voi kätevästi tallentaa skinit, mikä helpottaa hakemista Bedrock Editionissa.',
        'feature-noads' => 'Ei mainoksia',
        'feature-noads-detail' => 'Puhdas suunniteltu käyttöliittymä ilman häiriötekijöitä. Nauti mainoksettomasta kokemuksesta ilman häiritseviä häiriöitä verkosta sovellukseen.',
        'feature-experience' => 'Kokemus',
        'feature-experience-detail' => 'Nauti täydestä SkinMC-kokemuksesta missä tahansa, jossa on lisäominaisuuksia. Mukauta profiiliasi, lisää sinun bio, luo hauska QR-koodi ja paljon muuta!',
        'get-app-headline' => 'Hanki SkinMC sovellus',
        'get-app-detail' => 'Oma Minecraft kumppanisi Androidille — saatavilla ilmaiseksi.'
    ],
    'random' => [
        'title' => 'Ladataan satunnaista Minecraftin skiniä',
        'description' => 'Ladataan satunnaista Minecraftin skiniä',
        'headline' => 'Odota hetki...',
        'redirect' => 'Sinut ohjataan automaattisesti. Sivu ei lataudu?',
        'click-here' => 'Napsauta tästä',
        'messages' => [
            '1' => 'Ladataan satunnaista Minecraftin skiniä...',
            '2' => 'Kaivetaan alas...',
            '3' => 'Creeper, aw man...',
            '4' => 'Etsitään arkkujen läpi...',
            '5' => 'Tiesitkö, että tuleva skini on täysin satunnainen?',
            '6' => 'Satunnainen skini tulossa...',
            '7' => 'Vielä yksi kuutio...',
            '8' => 'Lajitellaan varastoa...',
            '9' => 'Valmistetaan timanttikirves...',
            '10' => 'Etsitään Herobrinea...',
        ],
    ],
    'feed' => [
        'title' => 'Syöte',
        'following' => 'Seurataan',
        'sign-up' => 'Rekisteröidy tai kirjaudu sisään liittyäksesi keskusteluun.',
        'link-account' => 'Yhdistä Minecraft-tilisi liittyäksesi keskusteluun.',
        'placeholder' => 'Mitä tapahtuu?',
        'audience' => 'Yleisö',
        'audience-title' => 'Kuka voi nähdä tämän?',
        'everyone' => 'Kaikki',
        'everyone-info' => 'Kuka tahansa SkinMC:n tai sen ulkopuolella.',
        'followers' => 'Seuraajat',
        'followers-info' => 'Sisään kirjautunut tai jäsenet, jotka seuraa minua.',
        'private' => 'Vain minä',
        'private-info' => 'Yksityinen julkaisu, vain minä näen.',
        'submit' => 'Julkaise',
        'like' => 'Tykkää',
        'comment' => 'Vastaa',
        'share' => 'Jaa',
        'remaining' => 'Jäljellä',
        'profile' => ':username julkaisut',
        'posts' => 'Kaikki julkaisut',
        'my-posts' => 'Minun julkaisut',
        'view-all' => 'Näytä kaikki julkaisut',
        'post' => [
            'meta' => ':username SkinMC:ssä: :text',
            'title' => 'Julkaise',
            'created' => 'Tilapäivitys julkaistu!',
            'confirm-delete' => 'Oletko varma, että haluat poistaa tämän julkaisun? Sitä ei voi perua.',
            'delete' => 'Poista julkaisu',
            'deleted' => 'Julkaisusi poistettiin.',
        ],
        'repost' => [
            'button' => 'Repost',
            'quote_button' => 'Quote',
            'title' => 'Repost this post',
            'quote_title' => 'Quote post',
            'quote_label' => 'Add a comment (optional)',
            'quote_placeholder' => 'Add your thoughts...',
            'reposted' => 'reposted',
            'success' => 'Reposted!',
            'removed' => 'Repost removed.',
            'already_reposted' => 'You have already reposted this.',
            'undo' => 'Undo repost',
            'original_deleted' => 'The original post has been deleted.',
            'deleted_post' => 'This post has been deleted',
        ],
        'poll' => [
            'title' => 'Poll',
            'create' => 'Create a poll',
            'option' => 'Option',
            'add_option' => 'Add option',
            'duration' => 'Duration',
            'duration_1' => '1 day',
            'duration_3' => '3 days',
            'duration_7' => '7 days',
            'votes' => '{0} votes|{1} vote|[2,*] votes',
            'ended' => 'Poll ended',
            'ends_in' => 'Ends :time',
            'login_required' => 'Sign in to vote',
        ],
        'gif' => [
            'title' => 'GIF',
            'search_placeholder' => 'Search KLIPY for GIFs...',
            'no_results' => 'No GIFs found',
            'powered_by' => 'Powered by',
            'categories' => 'Categories',
            'trending' => 'Trending',
        ],
        'media' => 'Media',
        'follow-suggestions' => 'Seuraa tiimiä',
        'explore' => 'Selaa',
        'hashtag' => 'Aihetunniste',
        'no_users' => 'No users found.',
        'stories' => [
            'archive' => [
                'title' => 'Story Archive',
                'subtitle' => 'Your archived stories are only visible to you',
                'empty' => 'No archived stories yet',
                'empty-description' => 'Stories you post will appear here after 24 hours.',
                'action' => 'Archive',
                'archived' => 'Story moved to archive.',
                'already-archived' => 'Story is already archived.',
            ],
        ],
    ],
    'private' => [
        'title' => 'Yksityiset julkaisut',
        'text' => 'Tämä julkaisu on yksityinen.'
    ] ,
    'liked' => [
        'title' => 'Tykätty'
    ],
    'following' => [
        'title' => 'Seuratut',
        'text' => 'Kirjaudu sisään nähdäksesi tämän julkaisun.'
    ],
    'tags' => [
        'empty' => 'Ei vielä äänestettäviä tunnisteita',
        'empty-subtitle' => 'Ole ensimmäinen, joka lisää yhden',
    ],
    'inbox' => [
        'title' => 'Viestit',
        'details' => 'Tiedot',
        'message_user' => 'Viesti',
        'write_message' => 'Kirjoita viesti',
        'empty' => [
            'no_message_selected' => 'Viestiä ei ole valittu',
            'open_or_start_conversation' => 'Avaa keskustelu viestilistasta tai aloita uusi keskustelu.',
            'no_messages' => 'Ei lukemattomia viestejä',
            'start_conversation' => 'Kun aloitat uuden keskustelun, sinun viestit näytetään täällä.',
            'conversation' => 'Tämä on keskustelusi alku :username kanssa.',
            'users' => 'Ei löydy käyttäjiä, jotka vastaavat nykyistä hakua.'
        ],
        'typing' => ':username kirjoittaa...',
        'new_message' => 'Uusi viesti',
        'mark_unread' => 'Merkitse lukemattomaksi',
        'send_message' => 'Lähetä viesti',
        'delete_message' => 'Poista viesti sinulta',
        'latest_conversations' => 'Viimeisimmät keskustelut',
        'delete_conversation' => 'Poista keskustelu',
        'show_details' => 'Näytä tiedot',
        'hide_details' => 'Piilota tiedot',
        'unread' => 'Lukematon',
        'deleted' => 'Poistettu',
        'report_message' => 'Ilmianna viesti',
        'add_reaction' => 'Lisää reaktio',
        'today' => 'Tänään',
        'reconnect' => 'Yhdistä Minecraft-tilisi uudelleen, jotta voit keskustella',
        'account_disconnected' => 'Tämä käyttäjä katkaisi linkitetyn Minecraft-tilinsä.',
        'saved_messages' => 'Tallennetut viestit',
        'new_message_to_label' => 'Vastaanottaja',
        'external-link-to' => 'Tämä linkki vie sinut kohteeseen',
        'external-link-confirmation' => 'Oletko varma, että haluat mennä sinne?',
        'external-link' => 'Ulkoinen linkki',
        'reply' => 'Vastaa'
    ],
    'server' => [
        'manage' => [
            'stats' => 'Tilastot'
        ]
    ],
    'report' => [
        'button' => 'Ilmianna',
        'title' => 'Ilmianna sisältö',
        'describe' => 'Kuvailkaa lyhyesti, miksi raportoitte tästä',
        'select' => 'Valitse ilmiannon syy',
        'submit' => 'Lähetä ilmianto',
        'reasons' => [
            'INAPPROPRIATE_CONTENT' => 'Epäasiallinen sisältö',
            'SPAM' => 'Roskaposti',
            'HARASSMENT' => 'Häirintä',
            'OTHER' => 'Muu',
        ]
    ],
    'leaderboard' => [
        'title' => 'Tulostaulukko',
        'description' => 'Katso SkinMC:n käyttäjien tulostaulukkoa.',
        'headline' => 'Top 10',
        'all-time-invites' => 'Kaikkien aikojen kutsut',
        'all-time-xp' => 'Kaikkien aikojen XP',
        '30-day-xp' => '30 päivän XP'
    ],
];
