<?php

return [
    'login' => [
        'title' => 'Bejelentkezés',
        'email' => 'Email-cím',
        'password' => 'Jelszó',
        'button' => 'Bejelentkezés',
        'editor_save_context' => "Log in to save your skin to the gallery. Your work won\\'t be lost.",
        'forgot' => 'Elfelejtetted a jelszavad?',
        'reset' => 'Visszaállítás',
        'register' => 'Még nincs fiókod?',
        'signup' => 'Regisztráció',
        'google' => 'Folytatás Google-lel',
        'microsoft' => 'Tovább Microsofttal',
        'facebook' => 'Folytatás Facebook-kal',
        'twitter' => 'Folytatás Twitter-rel',
        'divider' => 'vagy',
    ],
    'signup' => [
        'title' => 'Regisztráció',
        'existing' => 'Már van fiókod?',
        'button' => 'Elfogadás és folytatás',
        'terms_by_selecting' => 'A kiválasztással',
        'terms_agree_to' => ', elfogadom a SkinMC',
        'terms_acknowledge' => 'és megértem a',
    ],
    'recover' => [
        'title' => 'Fiók helyreállítása',
        'description' => 'Elfelejtetted a jelszavad? Add meg az email-címedet és segítünk visszaszerezni!',
        'button' => 'Jelszóhelyreállító email elküldése',
        'found' => 'Megtaláltad a jelszavad?',
    ],
    'logout' => [
        'title' => 'Kijelentkezés',
        'description' => 'Biztosan ki szeretnél jelentkezni a SkinMC fiókodból?',
        'logout' => 'Kijelentkezés',
        'cancel' => 'Mégse',
    ],
    'profile_qrcode' => [
        'title' => 'QR kód beolvasása',
        'done' => 'Kész',
    ],
    'language' => [
        'title' => 'Nyelv',
        'description' => 'Válassz nyelvet',
        'contribute' => 'Hozzájárulás',
        'contribute_add' => 'Új fordítás',
        'updated' => 'Nyelv kiválasztva',
    ],
    'copied' => 'Vágólapra másolva',
    'close' => 'Bezárás',
    'feedback' => [
        'title' => 'Visszajelzés',
        'type' => [
            'select' => 'Milyen kategóriában szeretnél visszajelzést küldeni?',
            'label' => 'Visszajelzés kategóriája',
            'comment' => 'Hozzászólások',
            'question' => 'Kérdések',
            'bug' => 'Hibajelentés',
            'feature' => 'Új funkció kérelmezése',
        ],
        'submit' => 'Küldés',
        'nps' => 'Egy 0-tól 10-ig terjedő skálán mekkora a valószínűsége, hogy ajánlanád a SkinMC-t a barátaidnak?',
        'success' => [
            'title' => 'Köszönjük!',
            'message' => 'Fogadtuk az üzenetedet és hamarosan válaszolunk! Ha további kérdéseid lennének, nyugodtan csatlakozz a Discord-szerverhez vagy küldj el egy újabb üzenetet.',
        ],
    ],
];
