<?php

return [
    'skins' => 'Kinézetek',
    'avatars' => 'Profilképkészítő',
    'editor' => 'Kinézetszerkesztő',
    'heads' => 'Fejek',
    'capes' => 'Köpenyek',
    'servers' => 'Szerverek',
    'achievement' => 'Teljesítménykészítő',
    'armor' => 'Páncélállvány-szerkesztő',
    'banners' => 'Zászlók',
    'banner' => 'Banner Editor',
    'profile' => 'Saját profil',

    'generators' => 'Generators',

    // Navigation dropdowns
    'feed' => 'Feed',
    'discover' => 'Discover',
    'mods' => 'Mods',
    'shaders' => 'Shaders',
    'resource_packs' => 'Resource Packs',

    'logout' => 'Kijelentkezés',
    'register' => 'Regisztráció',
    'login' => 'Bejelentkezés',
    'about' => 'Névjegy',
    'contact' => 'Kapcsolat',
    'faqs' => 'GY.I.K.',

    'minecraft_name' => 'Minecraft-felhasználónév',
    'minecraft_uuid' => 'Minecraft-UUID',
    'what' => 'Keresés',
    'recent_searches' => 'Keresési előzmények',
    'username' => 'Felhasználónév',
    'uuid' => 'UUID',
    'search' => 'Keresés',
    'search_placeholder' => 'Keresési javaslat:',
    'search_placeholder_uuid' => 'Add meg a felhasználó UUID-jét!',
    'start_search' => 'Keresés indítása',
    'cancel_search' => 'Mégse',
    'search_type' => 'Szűrők',
    'search_type_all' => 'Összes találat',
    'profiles' => 'Fiókok',
    'view_skin' => 'Kinézet megtekintése',
    'edit_skin' => 'Kinézet szerkesztése',
    'make_avatar' => 'Beállítás profilképként',
    'find_heads' => 'Játékosfejek keresése',

    'home' => 'Kezdőlap',
    'help' => 'Súgó',
    'tools' => 'Eszközök',
    'more-tools' => 'További eszközök',
    'skin_viewer' => 'Kinézetvizsgáló',
    'avatar_maker' => 'Profilképszerkesztő',
    'collections' => 'Gyűjtemények',
    'popular_skins' => 'Felkapott kinézetek',
    'cartoon_skins' => 'Rajzfilmes kinézetek',
    'animal_skins' => 'Állatos kinézetek',
    'community' => 'Közösség',
    'imprint' => 'Impresszum',
    'cookies' => 'Sütik',
    'terms' => 'Terms of Service',
    'privacy' => 'Privacy policy',
    'app' => 'Alkalmazás',
    'mod' => 'Mod',
    'totem' => 'Totemkészítő',
    'cube' => 'Cube',
    'new' => 'New',

    'feedback' => 'Visszajelzés',
    'status' => 'Állapot',
    'recent_searches_placeholder' => 'A keresési előzményeid itt fognak megjelenni.',
    'recent_views_placeholder' => 'Az általad korábban megtekintett profilok itt fognak megjelenni.',
    'moderate' => 'Moderáció',
    'listings' => 'Adatbázis',
    'add' => 'Új',

    'theme' => [
        'title' => 'Theme',
        'dark' => 'Dark',
        'light' => 'Light',
        'auto' => 'Auto'
    ],
];
