<?php

return [
    'auth' => [
        'login' => [
            'title' => 'Isten hozott a SkinMC-n!',
        ],
        'register' => [
            'title' => 'SkinMC-regisztráció',
            'subtitle' => 'Regisztrálj a teljes hozzáféréshez.'
        ]
    ],

    'home' => [
        'hero_slogan' => 'A Minecraft-kinézetek tárháza.',
        'hero_slogan_alt_1' => 'Everything Minecraft. One place.',
        'hero_slogan_alt_2' => 'Where Minecrafters meet.',
        'hero_cta' => 'Jó napom van',
        'hero_explore_cta' => 'Felfedezés',
        'skin_viewer' => 'Kinézetvizsgáló',
        'skin_viewer_detail' => ':count kinézet a tárházban',
        'skin_editor' => 'Kinézetszerkesztő',
        'skin_editor_detail' => 'Tervezd meg a saját kinézetedet',
        'avatar_maker' => 'Profilképszerkesztő',
        'avatar_maker_detail' => 'Készíts saját Minecraftos profilképeket!',
        'trending' => 'Felkapott',
        'minecraft_skin' => 'Minecraft-kinézet',
        'favourite' => 'Kedvencnek jelölés',
        'collections' => 'Gyűjtemények',
        'collections_detail' => 'Kézzel válogatott Minecraft-kinézetek bármilyen alkalomra',
        'about_skinmc' => 'A SkinMC névjegye',
        'about_find' => 'Tekintsd meg bárki kinézetét',
        'about_find_detail' => 'A SkinMC-n rákereshetsz bárkire és letöltheted a legújabb kinézetedet.',
        'about_download' => 'Letöltés és szerkesztés',
        'about_download_detail' => 'Megtetszett egy kinézet? Jelöld be kedvencnek, szerkeszd, vagy töltsd le és használd magad!',
        'about_platform' => 'Platformfüggetlen',
        'about_platform_detail' => 'Magaddal vinnél egy kinézetet? Olvasd be a QR kódját és elmentheted a telefonodra, a mobilos kiadással való használathoz.',
        'meta' => [
            'title' => 'Minecraftkinézet-vizsgáló',
            'description' => 'Minecraft-kinézetek megtekintése és letöltése, a legjobb kinézetek felfedezése kézzel válogatott gyűjteményekből, felhasználónév-elérhetőség ellenőrzése, előzmények megtekintése, és sok más!',
        ],
        'recently_viewed' => 'Előzmények',
        'explore_title' => 'Újdonságok',
        'explore' => 'Új ötletek és eszközök',
        'servers_browse' => 'Szerverek böngészése',
        'servers' => 'Fedezd fel a legjobb Minecraft-szervereket!',
        'heads' => 'Minecraft-fejek',
        'head_description' => 'Böngészd a Mincecraftfej-adatbázist vagy készíts újat!',
        'achievement' => 'Teljesítményszerkesztő',
        'achievement_detail' => 'Készíts egyedi teljesítményeket!',
        'continue' => 'Böngészés folytatása'
    ],
    'profile' => [
        'verified' => 'Igazolt fiók',
        'minecraft_profile' => 'Minecraft-fiók',
        'show_qr_code' => 'QR kód mutatása',
        'favourite' => 'Kedvencnek jelölés',
        'user_title' => ':username Minecraft-kinézete',
        'user_views' => ':views megtekintés',
        'uuid' => 'UUID',
        'copy' => 'Másolás',
        'link' => 'Hivatkozás',
        'skin_history' => 'Kinézetelőzmények (:skins elem)',
        'username_history' => 'Felhasználónévelőzmények',
        'username_history_name' => 'Felhasználónév',
        'username_history_timestamp' => 'Legutóbbi módosítás',
        'username_history_initial_name' => '(Eredeti név)',
        'user_downloads' => ':downloads letöltés',
        'download_skin' => 'Kinézet letöltése',
        'apply_skin' => 'Kinézet használata',
        'capes' => 'Köpenyek',
        'claim_profile' => 'Te vagy :username? Igazold a tulajdonjogod és személyre szabhatod!',
        'claimed' => 'Igazolt fiók',
        'meta_description' => ':username Minecraft-kinézetének megtekintése vagy letöltése. UUID, felhasználónévelőzmények, részletes statisztikák és további adatok.',
        'created_at' => 'Legutóbb frissítve: :changed_at',
        'skins' => [
            'meta_title' => ':username Minecraftkinézet-előzményei',
            'meta_description' => ':username Minecraftkinézet-előzményeinek megtekintése. Itt láthatod :username előzőleg használt kinézeteit és le is töltheted azokat.',
            'title' => 'Kinézetelőzmények'
        ],
        'qr_code' => [
            'meta_title' => ':username QR kódja',
            'meta_description' => 'A :username Minecaft-fiókjához tartozó egyedi QR kód'
        ],
        'sub_nav' => [
            'skin' => 'Kinézet',
            'about' => 'Névjegy',
            'usernames' => 'Felhasználónevek',
            'head' => 'Fej',
            'comments' => 'Hozzászólások'
        ],
        'cape' => 'Köpeny',
        'elytra' => 'Kitinszárny',
        'nametag' => 'Név',
        'animation' => 'Animáció',
        'rotation' => 'Forgás',
        'none' => 'Egyik sem',
        'idle' => 'Tétlen',
        'walk' => 'Séta',
        'run' => 'Futás',
        'fly' => 'Repülés',
        'follow' => 'Követés',
        'following' => 'követett',
        'unfollow' => 'Követés megszüntetése',
        'followers' => 'követő',
        'toast' => [
            'following' => 'Mostantól követed :username-t!',
            'follow-self-error' => 'Sajnáljuk, :username, de nem követheted önmagad.',
            'unfollowed' => 'Mostantól már nem követed :username-t.'
        ],
        'edit' => 'Profil szerkesztése',
        'joined' => 'Csatlakozott',
        'role' => 'Role',
        'server-fav-list-empty' => 'Looks like :username hasn\'t got any favourite servers yet. Once :username has saved a server as their favourite, you can see it here.',
        'server-own-list-empty' => 'Looks like :username hasn\'t got any servers yet. Once :username has listed a server, you can see it here.',
        'capes-list-empty' => 'Looks like :username isn\'t wearing any capes yet. Once :username is wearing a cape, you can see it here.',
        'feed-own-list-empty' => 'Looks like you haven\'t posted anything to the feed yet! Once you post, you can see your posts here.',
        'feed-list-empty' => 'Hmm, it seems like :username hasn\'t posted anything to the feed yet. Once :username posts something you can see it here.',
        'following-own-list-empty' => 'Úgy tűnik, hogy még senkit sem követsz. A követett emberek itt fognak megjelenni.',
        'following-list-empty' => 'Úgy tűnik, hogy :username még senkit sem követ. Az általa követett emberek itt fognak megjelenni.',
        'followers-own-list-empty' => 'A Téged követő emberek itt fognak megjelenni.',
        'followers-list-empty' => 'Hmm… úgy tűnik, hogy :username-t nem követi senki. Légy Te az első! A(z) :username-t követő emberek itt fognak megjelenni.',
        'render' => 'Megjelenítő',
        '3d' => 'Térhatású',
        '2d' => 'Lapos',
        'name-history-info' => 'A felhasználónévelőzmények hamarosan elbúcsúznak. 2022. szeptember 13-án a Mojang megszüntette a korábbi felhasználónevek elérhetőségét az API-ban, ezért már nincs róluk elérhető pontos adatbázis. Ha nem szeretnéd, hogy nyilvánosak legyenek az előzményeid, igazold a fiókod tulajdonjogát és tedd priváttá.',
        'edit-skins' => 'Kinézetelőzmények szerkesztése',
        'hide-skin' => 'Kinézet elrejtése',
        'show-skin' => 'Kinézet mutatása',
        'edit-skin' => 'Edit skin',
        'servers' => [
            'title' => ':username\'s servers',
        ],
        'cape-list' => [
            'title' => ':username\'s capes',
        ]
    ],
    'skin' => [
        'meta' => [
            'title' => ':username Minecraft-kinézete',
            'description' => 'Minecraft-kinézet megtekintése, letöltése és nyomon követése.',
            'tags' => ':username Minecraft-kinézete, :username kinézete, Minecraft-kinézet, :username egyedi Minecraft-kinézete, kinézet letöltése, játékosok akik ezt a kinézetet használják',
        ],
        'title' => ':username Minecraft-kinézete',
        'head' => 'Fejparancsok',
        'head_info' => 'Parancsblokkokkal való használathoz',
        'first_wearing' => 'Az első játékos, aki ezt a kinézetet használta:',
        'profiles' => ':profiles fiók',
        'profiles_title' => ':profiles fiók használja ezt a kinézetet',
        'screenshot' => 'Screenshot',
    ],
    'skins' => [
        'meta' => [
            'title' => ':current. oldal – Minden Minecraft-kinézet',
            'description' => 'Böngészd át a(z) :last-oldalas listánkat, ami mind a(z) :total egyedi Minecraft kinézetet tartalmazza, és szerezd be a következő kinézetedet!',
            'tags' => ':username Minecraft-kinézete, :username kinézete, Minecraft-kinézet, :username egyedi Minecraft-kinézete, kinézet letöltése, játékosok akik ezt a kinézetet használják',
            'tags-title' => 'A(z) :tag-címkével rendelkező Minecraft-kinézetek',
            'tags-description' => 'Böngészd át a(z) :last-oldalas listánkat, ami mind a(z) :total :tag-címkével rendelkező Minecraft kinézetet tartalmazza, és szerezd be a kedvenc kinézetedet!',
            'tags-metatags' => ':tag-címkével rendelkező Minecraft-kinézetek, Minecraft-kinézetek, :tag-címkével rendelkező egyedi Minecraft-kinézetek, :tag-címkével rendelkező kinézetek letöltése',
        ],
        'title-skin-tags' => 'Címkével rendelkező Minecraft-kinézetek',
        'subtitle' => ':last / :current. oldal – Összesen :total Minecraft-kinézet',
        'subtitle-skin-tags' => ':last / :current. oldal – Összesen :total címkével rendelkező Minecraft-kinézet',
        'sort_by' => 'Rendezés',
        'latest' => 'A legújabb elöl',
        'most_profiles' => 'A leghasználtabb elöl',
        'profiles_today' => 'A mai napon leghasználtabb elöl',
        'profiles_this_week' => 'Az ezen a héten leghasználtabb elöl',
        'profiles_this_month' => 'Az ebben a hónapban leghasználtabb elöl',
        'default' => 'Alapértelmezett',
        'this_month' => 'Ebben a hónapban',
        'this_week' => 'Ezen a héten',
        'today' => 'A mai napon',
        'random' => 'Véletlenszerű',
        'similar' => 'Hasonló kinézetek',
        'no_similar_skins' => 'Még nem találtunk hasonló kinézeteket.',
        'favorite' => ':count kedvenc',
    ],
    'skin-tags' => [
        'faq' => 'Súgó a címkékről',
        'about' => 'Címkék használatával lehet kinézeteket kategóriákba rendezni. Helyesen megadott címkék segítéségével gyorsabban megtalálhatod a Neked megfelelő kinézeteket.',
        'guidelines' => [
            'good' => [
                'title' => 'Egy jó címke…',
                'short' => '…rövid',
                'descriptive' => '…leíró',
                'spelled' => '…helyesen írt',
            ],
            'bad' => [
                'title' => 'Ilyen címkét ne hozz létre:',
                'general' => 'Túl általános',
                'specific' =>  'Túl pontos',
                'too-many-tags' =>  'Ez három különböző címke legyen',
                'spelling' => 'A helyes írásmód: :example',
            ],
        ],
        'toast' => [
            'added' => 'A(z) „:tag”-címkét szavazásra bocsátottad.',
            'removed' => '„:tag”-címke eltávolítva.',
            'upvote' => 'Pozitívan értékelted a(z) „:tag”-címkét.',
            'downvote' => 'Negatívan értékelted a(z) „:tag”-címkét.'
        ],
        'vote' => [
            'up' => 'Tetszik',
            'down' => 'Nem tetszik',
            'remove' => 'Szavazat visszavonása',
        ],
    ],
    'contact' => [
        'contact' => 'Kapcsolat',
        'email' => 'Ha kérdésed van, nyugodtan fordulj hozzánk a <a href="mailto:support@skinmc.net">support@skinmc.net</a> email-címen.',
        'faq' => 'Kérjük, látogasd meg a <a href=":link">GY.I.K.-et</a> és ellenőrizd, hogy valaki már megválaszolta-e a kérdésedet.',
        'other' => 'További kapcsolatfelvételi lehetőségek',
        'other_discord' => 'Csatlakozz a Discord-szerverhez, ha barátkozni szeretnél, játékokról beszélgetni, megosztani a kedvenc gyűjteményeidet, vagy segítséget kérnél!',
        'other_twitter' => 'A Twitter-profilunkon értesülhetsz az új frissítésekről és funkciókról, illetve megtekintheted a hét kinézetét.',
        'other_instagram' => 'Az Instagram-oldalunkon megtekintheted a király új Minecraft-kinézeteket és képeket.',
        'other_facebook' => 'A Facebook-oldalunkon hozzászólhatsz a bejegyzéseinkhez és másokkal beszélgethetsz, miközben Minecraftos tartalmakat nézegetsz.'
    ],
    'about' => [
        'intro' => '<span>A</span> <span>Minecraft-kinézetek</span> <span>tárháza.</span>',
        'header_credit' => 'Az „Epic Nether Battle”-illusztráció készítője:',
        'info' => 'Kövess nyomon mindent!',
        'info_explainer' => 'Megtekintheted egy játékos felhasználónév- és kinézetelőzményeit, barátnak jelölheted őt, letöltheted a kinézeteit és még részletes statisztikákat is láthatsz róla.',
        'card_find_title' => 'Tekintsd meg bármelyik Minecraft-játékos profilját!',
        'card_find_detail' => 'A kezdéshez keress rá egy játékos felhasználónevére vagy UUID-jére!',
        'card_view_title' => 'Nézelődj, ments és szerkessz!',
        'card_view_detail' => 'Megtetszett egy kinézet? Töltsd le, vagy készíts sajátot a szerkesztővel!',
        'card_claim_title' => 'Igazold magad!',
        'card_claim_detail' => 'A Minecraft-fiókod összekapcsolásával igazolhatod a profilod tulajdonjogát, és ezzel különleges funkciók válnak elérhetővé a számodra.',
        'card_customise_title' => 'Szabd személyre a profilod!',
        'card_customise_detail' => 'Az igazolt játékosok önmagukra formálhatják a profiljukat és még a más közösségi oldalakon található profiljaikra is hivatkozhatnak.',
        'card_friends_title' => 'Jelöld be a barátaid!',
        'card_friends_detail' => 'Ha kapcsolatba lépsz a SkinMC-s barátaiddal, ők is megjelennek a profilodon.',
        'card_history_title' => 'Felhasználónév- és kinézetelőzmények',
        'card_history_detail' => 'A fejlett keresőmotor segítségével megtalálhatod bármelyik játékos korábbi neveit és kinézeteit.',
        'founders' => 'Az alapítók',
        'founders_cofounder' => 'A SkinMC társalapítója',
        'head_of_design' => 'Fő tervező',
        'head_of_code' => 'Fő programozó',
        'feedback' => 'Visszajelzés',
        'faq' => 'Kérdésed van a Minecrafttal, a kinézetekkel, vagy mással kapcsolatban? Olvasd el a GY.I.K.-et és megtudod a válaszokat a leggyakoribb kérdésekre!',
        'faq_link' => 'GY.I.K.',
        'contact' => 'Fel akarod venni velünk a kapcsolatot, vagy további kérdéseid vannak? Csak írj!',
        'contact_link' => 'Kapcsolat',

    ],
    'faq' => [
        'title' => 'GY.I.K.',
        'subtitle' => 'Gyakran ismételt kérdések',
        'help' => 'További segítségre van szükséged?',
        'discord' => 'Csatlakozz a Discord-szerverünkhöz, ahol más Minecraft-játékosokkal is beszélgethetsz!',
        'contact' => 'Kapcsolat',
        'q' => [
            'change_skin_t' => 'Hogyan változtathatom meg a Minecraft-kinézetemet?',
            'change_skin' => '
                <p>A kinézeted megváltoztatásához az alábbi lépéseket kell követned:</p>
                <ol>
                    <li>Látogasd meg a <a href="https://my.minecraft.net/en-us/login/">https://my.minecraft.net/en-us/login/</a>-honlapot és jelentkezz be a Mojang-fiókoddal!</li><li>Bejelentkezés után kattints bal oldalt a <b>„Skin”</b>-menüpontra!</li><li>Végezetül válaszd ki a kívánt karaktermodellt és töltsd fel a használni kívánt kinézetet!</li>
                </ol>',
            'change_username_t' => 'Hogyan változtathatom meg a Minecraft-felhasználónevemet?',
            'change_username' => '
                <p>A felhasználóneved megváltoztatásához az alábbi lépéseket kell követned:</p>
                <ol>
                    <li>Látogasd meg a <a href="https://my.minecraft.net/en-us/login/">https://my.minecraft.net/en-us/login/</a>-honlapot és jelentkezz be a Mojang-fiókoddal!</li>
                    <li>Keresd meg a felhasználónevedet, majd kattints a <b>„(Change)”</b>-gombra!</li>
                    <li>A következő oldalon add meg a használni kívánt felhasználónevet!</li>
                    <li>Végezetül alkalmazd a változtatásokat a jelszavad újbóli megadásával és a „Change name”-gombra való kattintással!</li>
                </ol>',
            'dl_t' => 'Hogyan tölthetem le valaki más Minecraft-kinézetét?',
            'dl' => '
                <p>Ha le szeretnéd tölteni valaki más kinézetét, az alábbi lépéseket kell követned:</p>
                <ol>
                    <li>Kattints a keresőmezőbe az oldal tetején és gépeld be annak a személynek a felhasználónevét, akinek a kinézetét használni szeretnéd!</li>
                    <li>Letöltés előtt még a profilján megtekintheted a kinézetét.</li>
                    <li>Kattints az előnézet alatt a <strong>Kinézet letöltése</strong>-gombra és elindul a letöltés!</li>
                </ol>',
            'submit_q' => 'Gyűjteménybe hogyan nevezhetek ki egy kinézetet?',
            'submit_a' => '<p>Töltsd ki az alábbi rövid űrlapot és add meg a kinézetet viselő személy felhasználónevét és, hogy melyik gyűjteménybe szeretnéd nevezni!<a href="https://forms.gle/f4Jh5RpGfsHAZ5xE8" target="_blank">Gyűjteménybe nevező űrlap</a>',
            'mcpe_t' => 'Tölthetek le úgy kinézetet, hogy azt a Minecraft mobiltelefonos kiadásában használjam?',
            'mcpe' => '
                <p>Igen; a mobiltelefonos kiadásban az alábbi módon használhatsz kinézeteket:</p>
                <ol>
                    <li>Nyisd meg a SkinMC.net-honlapot az okostelefonodon és koppints a keresőmezőre!</li>
                    <li>Gépeld be annak a személynek a felhasználónevét, akinek a kinézetét használni szeretnéd!</li>
                    <li>Koppints rá az előnézet alatt található <strong>Kinézet letöltése</strong>-gombra!</li>
                    <li>Nyisd meg a Minecraftot és koppints a jobb oldalon található <strong>„Öltöző”</strong>-gombra!</li>
                    <li>Kattints a bal oldalon található <strong>„+”</strong>-gombra, vagy középen a <strong>„Karakter szerkesztése”</strong>-gombra és bal oldalt válts a <strong>„Klasszikus felületek”</strong>-fülre!</li>
                    <li>A <strong>„Saját felületek”</strong> alatt koppints rá az üres felületre, majd a jobb oldalon megjelenő <strong>„Új felület kiválasztása”</strong>-gombra és nyisd meg az imént letöltött képet!</li>
                </ol>',
            'change_times_t' => 'Milyen gyakran változtathatom meg a felhasználónevemet?',
            'change_times' => '<p>A Minecraft-felhasználónevedet <strong>30 naponta egyszer</strong> változtathatod meg.</p>',
            'available_t' => 'Ha megváltoztatom a felhasználónevemet, mennyi idő után foglalhatja le valaki a régi nevemet?',
            'available' => '<p>Ha vissza akarod szerezni a régi felhasználónevedet, azt csak a <strong>30 nap lejárta után</strong> teheted meg. A 30 nap utáni <strong>7 napos</strong> időszakban még nem foglalható le a neved mások által (tehát módosítás után összesen 37 napod van visszaszerezni a régi neved).</p>',
            'username_history_t' => 'Lennétek szívesek eltávolítani a felhasználónévelőzményeimet?',
            'username_history' => '
                <p>Mivel a korábbi felhasználóneveket tartalmazó adatbázist nem mi tartjuk fenn, hanem a Mojang, ezért az előzményeket nem tudjuk eltávolítani. A Mojang korábban jelezte, hogy szándékosan elérhetően akarják tartani ezt az információt¹ és, hogy a nyilvánosságnak közvetlen elérést szeretnének biztosítani hozzá².</p>
                <p class="font-14">¹<a href="https://help.minecraft.net/hc/en-us/articles/360034636712-Minecraft-Usernames" target="_blank" rel="noreferrer">https://help.minecraft.net/hc/en-us/articles/360034636712-Minecraft-Usernames</a> (angol nyelven)</p>
                <p class="font-14 mb-0">²<a href="https://twitter.com/dinnerbone/status/554739042529849345" target="_blank" rel="noreferrer">https://twitter.com/dinnerbone/status/554739042529849345</a> (angol nyelven) (Tárolt változat 2018-ból: <a href="http://archive.is/TeAyj" target="_blank" rel="noreferrer">http://archive.is/TeAyj</a>)
                </p>',
        ],
    ],
    'avatars' => [
        'start' => [
            'title' => 'Hozz létre egyedi profilképeket!',
            'subtitle' => 'A profilképszerkesztővel személyre szabott profilképeket készíthetsz bármelyik Minecraft-kinézetből.',
            'avatar_face' => 'Lapos arc',
            'avatar_bust' => 'Lapos mellszobor',
            'avatar_cube' => 'Térhatású kocka',
            'avatar_head3d' => 'Forgatható térhatású kocka',
        ],
        'user' => [
            'title' => 'Kinézet kiválasztása',
            'subtitle' => 'Gépeld be annak a Minecraft-játékosnak a felhasználónevét, akiről profilképet szeretnél készíteni!',
            'form_label' => 'Minecraft-felhasználónév',
            'form_submit' => 'Tovább',
        ],
        'output' => [
            'title' => 'Előnézet és mentés',
            'subtitle' => 'Használd egészséggel!',
            'download_info' => 'Elégedett vagy? Töltsd le a kész profilképet az alábbi gombbal és máris használhatod!',
            'download_button' => 'Profilkép letöltése',
            'avatar_style' => 'Profilkép stílusa',
            'skin_username' => 'Kinézet tulajdonosa',
            'change' => 'Módosítás',
            'generate' => 'OK',
            'avatar_colour' => 'Háttérszín',
            'avatar_colour_palette' => 'Színpaletta',
            'avatar_colour_basic' => 'Alapértelmezett',
        ],
        'meta' => [
            'title' => 'Minecraftprofilkép-szerkesztő',
            'description' => 'Minecraftprofilkép-szerkesztő: Hozz létre egyedi profilképeket a Minecraft-kinézeted használatával!',
        ],
    ],
    'totem' => [
        'title' => 'Egyedi Minecraft-totem',
        'subtitle' => 'A totemszerkesztővel egyedi forráscsomagot hozhatsz létre, melyben az életmentés toteme az általad megadott kinézetre hasonlít.',
        'download_info' => 'Elégedett vagy? Válaszd ki az alábbi legördülő listáról az általad használt Minecraft-verziót, majd kattints a „Letöltés” gombra!',
        'meta' => [
            'title' => 'Egyedi Minecrafttotem-szerkesztő',
            'description' => 'Egyedi Minecraft-totemek: A totemszerkesztővel egyedi forráscsomagot hozhatsz létre, melyben az életmentés toteme az általad megadott kinézetre hasonlít.',
        ],
        'type' => [
            'mini' => 'A kinézeted pici változata',
            'full' => 'A kinézeted teljes változata',
            'model3d' => 'A kinézeted térhatású modellje',
            'add_designs' => 'Több lehetőségre vágysz? Ha javaslatod van, ide beküldheted:'
        ]
    ],
    'achievement' => [
        'header' => [
            'title' => 'Hozz létre egyedi teljesítményeket!',
            'subtitle' => 'A Minecraftteljesítmény-szerkesztővel egyedi előrelépéseket készíthetsz, amiket bármiben felhasználhatsz.',
        ],
        'generator' => [
            'yellow_text' => 'Cím',
            'white_text' => 'Tartalom',
            'choose_icon' => 'Ikon',
            'face' => 'Ikon helyett Minecraft-fej',
            'form_submit' => 'Letöltés',
            'form_label' => 'Minecraft-felhasználónév',
            'download' => 'Letöltés',
            'embed' => 'Beágyazás',
            'embed_copy' => 'Másolás',
        ],
        'meta' => [
            'title' => 'Minecraftteljesítmény-szerkesztő',
            'description' => 'A teljesítményszerkesztővel egyedi teljesítményeket és előrelépéseket hozhatsz létre. A kész képet aztán letöltheted, beágyazhatod HTML vagy BB kóddal, és még fórumaláírásokban is használhatod.',
        ],
    ],
    'armor' => [
        'header' => [
            'title' => 'Minecraftpáncélállvány-szerkesztő',
            'subtitle' => 'A páncélállvány-szerkesztő segítségével a játékban használható páncélállványokat rakhatsz össze. Kiválaszthatod a testtartásást, az elhelyezkedését és még sok mást.',
        ],
        'meta' => [
            'title' => 'Minecraftpáncélállvány-szerkesztő',
            'description' => 'A páncélállvány-szerkesztő segítségével a játékban használható páncélállványokat rakhatsz össze. Kiválaszthatod a testtartásást, az elhelyezkedését és még sok mást.',
        ],
    ],
    'banner' => [
        'editor' => [
            'header' => [
                'title' => 'Minecraftzászló-szerkesztő',
                'subtitle' => 'Tervezd meg a saját Minecraft-zászlódat! Ezeket díszként vagy <a href="https://optifine.net" target="_blank" rel="nofollow">Optifine</a>-köpenyként is használhatod.',
            ],
            'meta' => [
                'title' => 'Minecraftzászló-szerkesztő',
                'description' => 'Készítsd el a saját Minecraft-zászlódat a játékban használható lehetőségekkel! Ezekkel a zászlókkal kidíszítheted a világodat vagy beállíthatod őket Optifine-köpenyként. A minták zászlókon vagy pajzsokon való felhasználásához /give-parancsokat is kérhetsz.',
            ],
        ],
        'gallery' => [
            'header' => [
                'title' => 'Zászlóböngésző',
                'subtitle' => 'Böngészd át a(z) :count zászlónkat, amikkel feldíszítheted a világodat, vagy még egyedibbé varázsolhatod a kinézetedet!',
            ],
            'meta' => [
                'title' => 'Zászlóböngésző',
                'description' => 'Böngészd át a(z) :count zászlónkat, amikkel feldíszítheted a világodat, vagy még egyedibbé varázsolhatod a kinézetedet!',
            ],
        ],
    ],
    'search' => [
        'meta' => [
            'title' => ':search találat',
        ],
        'title' => 'SkinMC-keresés',
        'results' => ':current. oldal – Nagyjából :count találat',
        'time' => '(:time másodperc)',
        'username_available' => 'Ez a felhasználónév elérhető*',
        'username_unavailable' => 'Ez a felhasználónév foglalt',
        'username_status' => 'Állapot',
        'username_status_available' => 'Elérhető*',
        'username_status_unavailable' => 'Foglalt',
        'username_searches' => 'Keresések száma',
        'username_searches_count' => 'Naponta :count',
        'username_available_disclaimer' => '*Kivéve, ha a felhasználónév átmenetileg vagy véglegesen le lett tiltva a Mojang által.',
        'no_results' => 'Nincs találat. Próbálj keresni UUID alapján vagy állítsd át a szűrőt.',
        'no_results_tags' => 'Nincs találat. Próbálj más címkékre keresni és kereséskor az angol nyelvet használd. Pl.: „blue”, „girl”, „fox”, stb.',
        'again' => 'Keresés újból',
        'sorry' => 'Ssssssszajnáljuk…',
        'view_profile' => 'Profil megtekintése',
    ],
    'collection' => [
        'title' => 'Minecraftkinézet-gyűjtemény',
        'subtitle' => 'Böngészd át a kézzel válogatott Minecraftkinézet-gyűjteményeinket!',
        'filters' => 'Szűrők',
        'title_trending' => 'Felkapott',
        'title_all' => 'Minden Minecraft-kinézet',
        'skin_tags' => 'Címkével rendelkező kinézetek',
        'filters_skin_type' => 'Kinézet típusa',
        'filter_skin_type_steve' => 'Steve',
        'filter_skin_type_alex' => 'Alex',
        'cancel' => 'Mégse',
        'apply' => 'Alkalmaz',
        'username_minecraft_skin' => ':username Minecraft-kinézete',
        'user_downloads' => '<span class="fw-500">:downloads</span> letöltés',
    ],
    'favourites' => [
        'title' => 'Kedvencek',
        'subtitle' => 'A kedvencnek jelölt kinézetek kezelése',
        'sort' => 'Rendezés',
        'toast' => [
            'added' => 'Kedvencnek jelölve.',
            'removed' => 'Eltávolítva a kedvencek közül.'
        ],
        'skins' => [
            'button' => 'Kinézetek',
            'empty_headline' => 'Nincsenek kedvencek',
            'empty_subtitle' => 'Még egy kinézetet sem jelöltél kedvencnek. Látogasd meg a kinézetböngészőt és találd meg a legújabb kedvencedet!',
            'empty_browse' => 'Kinézetek böngészése',
            'meta' => [
                'title' => 'Kedvenc kinézetek',
                'description' => 'Az általad kedvencnek jelölt kinézetek.',
            ],
        ],
        'servers' => [
            'button' => 'Szerverek',
            'empty_headline' => 'Nincsenek kedvencek',
            'empty_subtitle' => 'Még egy szervert sem jelöltél kedvencnek. Látogasd meg a szerverböngészőt és találd meg a legújabb kedvencedet!',
            'empty_browse' => 'Szerverek böngészése',
            'meta' => [
                'title' => 'Kedvenc szerverek',
                'description' => 'Saját kedvenc Minecraft-szerverek',
             ],
        ],

    ],
    'cape' => [
        'editor' => [
            'title' => 'Minecraftköpeny-szerkesztő',
            'subtitle' => 'A köpenyszerkesztővel létrehozhatsz egy egyedi Minecraft-köpenyt.',
            'meta' => [
                'title' => 'Minecraftköpeny-szerkesztő',
                'description' => 'A köpenyszerkesztővel létrehozhatsz egy egyedi Minecraft-köpenyt.',
            ],
        ],
        'list' => [
            'title' => 'Minecraft-köpenyek',
            'subtitle' => 'A Minecraftban elérhető hivatalos köpenyek listája. Minden köpeny díszítő célt szolgál és az alap kinézetet egészíti ki. Ha a köpenyt viselő játékos kitinszárnyat vesz fel, a köpenye is megváltozik.',
            'meta' => [
                'title' => 'Minecraft-köpenyek listája',
                'description' => 'Minecraft-köpenyek listája: Itt megtekintheted az összes hivatalosan elérhető Minecraft-köpenyt, köztük a Mojang által viselt-, a Mineconokon kiosztott-, a személyes- és a különleges köpenyeket is.',
            ],
        ],
        'detail' => [
            'title' => ':cape-köpeny',
            'info' => 'Információ',
            'profile_list' => 'A köpenyt viselő felhasználók',
            'profiles' => ':profiles fiók',
            'meta' => [
                'title' => '„:cape” Minecraft-köpeny',
                'description' => 'A(z) „:cape” Minecraft-köpeny és az azt használó felhasználók megtekintése.',
            ],
        ],
        'list-custom' => [
            'title' => 'Egyedi Minecraft-köpenyek',
            'description' => 'A SkinMC-felhasználók által készített és használt egyedi köpenyek böngészése és megtekintése.'
        ]
    ],
    'servers' => [
        'title' => 'Minecraft-szerverek',
        'subtitle' => 'Minecraft szerverek böngészése és felfedezése',
        'all' => 'Minden szerver',
        'manage_your_servers' => 'Szerverek kezelése',
        'add_new_server' => 'Új szerver',
        'filters' => [
            'trending' => 'Felkapott',
            'updated' => 'Legutóbb frissítve',
            'new' => 'Új',
            'most_viewed' => 'Legnézettebb',
            'top_voted' => 'Legjobban értékelt',
            'sorting' => 'Rendezés',
            'sort_by_latest' => 'A legújabb elöl',
            'sort_by_oldest' => 'A legrégebbi elöl',
            'categories' => 'Kategóriák',
            'server_location' => 'Szerver elhelyezkedése',
            'show_results' => 'Alkalmaz',
            'show_more' => 'Továbbiak megjelenítése',
            'show_less' => 'Kevesebb megjelenítése',
            'clear_filters' => 'Szűrők törlése',
            'reviews' => 'Értékelések',
            'sort_by_highest_rating' => 'A legjobb elöl',
            'sort_by_lowest_rating' => 'A legrosszabb elöl',
            'bedrock_and_java_support' => 'Bedrock- és Java-támogatás'
        ],
        'review-count' => ':count értékelés',
        'meta' => [
            'title' => 'Minecraft-szerverek listája',
            'description' => 'Böngészd át a Minecraftszerver-listát és találd meg a legjobb Minecraft-szervert! Szűrők segítségével gyorsan megtalálhatod a legújabbakat, a legnépszerűbbeket, stb.',
        ],
        'reviews' => [
            'meta' => [
                'title' => 'Értékelés',
            ],
            'editing' => 'Jelenleg a(z) :date napon közzétett értékelésedet szerkeszted. Szeretnéd törölni az értékelést?',
            'welcome' => ':username! Milyen volt a tapasztalatod a(z) „:servername”-szerveren?',
            'subtitle' => 'Értékeld az általános élményedet!',
            'scale' => [
                'great' => 'Nagyon jó',
                'good' => 'Jó',
                'okay' => 'Elmegy',
                'meh' => 'Rossz',
                'bad' => 'Nagyon rossz',
            ],
            'rate-experience' => 'Kérjük, az alábbi kategóriákban is értékeld a szervert!',
            'overall' => 'Átfogó értékelés',
            'server-team' => 'A szerver személyzete',
            'community' => 'Közösség',
            'experience' => 'Élmény',
            'availablility' => 'Üzemidő és elérhetőség',
            'shop' => 'Bolt',
            'write-review-title' => 'Vélemény',
            'write-review-subtitle' => 'Foglald össze, hogy mi tetszett a szerveren és mi teszi azt egyedivé, vagy tedd fel a javaslataidat!',
            'write-review-helper' => 'Értékeld szövegesen a szervert és oszd meg az élményedet más játékosokkal, vagy javasolj változtatásokat a szerver tulajdonosainak!',
            'write-review-tips' => 'Néhány tipp:',
            'submit-title' => 'Készen állsz az értékelés beküldésére?',
            'submit-subtitle' => 'Már majdnem kész!',
            'submit-review' => 'Értékelés küldése',
            'back' => 'Vissza',
            'continue' => 'Tovább',
            'delete-title' => 'Biztosan törölni szeretnéd az értékelésedet?',
            'tos-checkbox-part-1' => 'Az űrlap kitöltésével beleegyezel a SkinMC szolgáltatási feltételeibe, adatvédelmi- és közösségi irányelveibe. Továbbá megerősíted, hogy a megadott információ pontos és megfelel az',
            'tos-checkbox-part-2' => 'értékelési irányelveknek.',
            'tos-checkbox-part-3' => 'Az értékelésed rögtön közzétételre kerül, de lehetséges, hogy később felülvizsgáljuk.'
        ],
        'slots' => 'Helyek száma',
        'empty-helper' => 'Próbálj új keresést indítani vagy…',
        'empty' => 'Hmm… Nincs itt semmi.',
        'verified' => 'Ellenőrzött',
        'review_translate_show_original' => 'Eredeti megjelenítése',
        'review_translate' => 'Értékelés lefordítása',
        'description_translate' => 'Leírás lefordítása',
        'create' => [
            'welcome' => 'Köszöntő',
            'basics' => 'Alapadatok',
            'categories' => 'Kategóriák',
            'social_links' => 'Közösség',
            'trailer_video' => 'Előzetes',
            'images' => 'Képek',
            'images_description' => 'Később feltölthetsz képeket, hogy bemutathasd, mit kínál a szervered.',
            'submit' => 'Közzététel',
            'lets_get_your_server_added' => 'Adjuk hozzá a szerveredet az adatbázishoz!',
            'basics-subtitle' => 'Meséld el, hogy miről szól a szervered!',
            'description' => 'Leírás',
            'description_tips' => 'Néhány ötlet',
            'description_hint' => 'Írj egy érdekes leírást, ami bevonzza a játékosokat!',
            'categories-subtitle' => 'Add meg, mely kategóriákba illik bele a szervered!',
            'missing-category' => 'Hiányzó kategória',
            'social_links_description' => 'Milyen közösségi oldalakon van jelen a szervered?',
            'trailer_video_description' => 'Mutasd be a szerveredet egy YouTube-videó beágyazásával!',
            'trailer_video_hint' => 'A videó hivatkozása vagy azonosítója:',
            'ready_to_submit_your_server' => 'Készen állsz a beküldésre?',
            'review-hint' => 'Beküldés után a csapatunk alaposan átvizsgálja a szerverhozzáadási kérelmedet. Bírálás után a szervered azonnal felkerül a listára vagy, ha változtatásokat kérünk, visszaküldjük Neked.',
            'terms' => [
                'part-1' => 'Az űrlap beküldésével beleegyezel a SkinMC szolgáltatási feltételeibe, adatvédelmi- és közösségi irányelveibe. Továbbá megerősíted, hogy a megadott információ pontos és megfelel a',
                'part-2' => 'szerverhozzáadási követelményeknek',
                'part-3' => 'és, hogy a Minecraft-szerver, melynek a listázását kérelmezed, a Te tulajdonodban áll, vagy a tulajdonos megbízásából cselekszel.'
            ],
            'submit-application' => 'Kérelem beküldése',
            'video-id-helper' => [
                'part-1' => 'A videóazonosító az a betű- és számsor, ami a videó hivatkozásában az alábbi rész után következik:',
                'part-2' => 'Pl.: Ha a videó hivatkozása az alábbi:',
                'part-3' => ', akkor ebből a videóazonosító:'
            ],
            'welcome_description' => 'Kezdjük meg a szervered hozzáadását! Meséld el, hogy miről szól a szerver, majd tölts fel róla képeket.'
        ],
        'copy_server_ip' => 'Szerver IP-címének másolása',
        'all_minecraft_servers' => 'Minden Minecraft-szerver',
        'promo' => [
            'title' => 'Van saját Minecraft-szervered?',
            'ready_to_list_your_server' => 'Készen állsz a szervered beküldésre?',
            'everything_you_need' => 'Tudnivalók egy szerver népszerűsítéséhez',
            'list_your_server' => 'Listázd a szervered!',
            'list_your_server_description' => 'Add hozzá a szerveredet az adatbázisunkhoz és mutasd be másoknak képekkel, közösségi hivatkozásokkal és másokkal!',
            'find_players' => 'Játékosok toborzása',
            'find_players_description' => 'Találj új játékosokat és terjeszd ki a közösségedet!',
            'get_reviews' => 'Véleménygyűjtés',
            'get_reviews_description' => 'Kérdd meg a játékosaidat, hogy írjanak véleményt a szerveredről és jutalmazd meg őket a játékban!',
            'why_list_on_skinmc' => 'Okok, amiért megéri a SkinMC-n listázni a szerveredet',
            'others' => 'Egyebek',
            'quality_check_and_confirmation' => 'Minőség-ellenőrzés és vizsgálat',
            'quality_check_description' => 'A csapatunk minden szervert átvizsgál.',
            'verified_players' => 'Értékelések valódi Minecraft-játékosoktól',
            'verified_players_description' => 'A Votifier-integrációnak köszönhetően hiteles értékeléseket kaphatsz valódi felhasználóktól.',
            'international' => 'Nemzetközi',
            'international_description' => 'A gépifordítói-funkciónak köszönhetően a szervered oldala még több felhasználó számára elérhető.',
            'server_listing_page' => 'Sokoldalú szerveroldal',
            'server_listing_page_description' => 'A szerveroldalon megjelenetnek fényképek, leírások és videók, és kiemelheted a lehetséges játékosok számára, hogy miért csatlakozzanak.',
            'social_connections' => 'Közösségi oldalak',
            'social_connections_description' => 'A szervered közösségi oldalaira is hivatkozhatsz, az új játékosok számára.',
            'verified_badge' => 'Hitelesítő jelvény',
            'verified_badge_description' => 'A hiteles szerverek jelvényt is kérelmezhetnek.',
            'owner_profile' => 'Tulajdonosi profilok',
            'owner_profile_description' => 'A saját profiloldalad személyre szabásával személyesebbé teheted azt.',
            'categories' => 'Kategóriák',
            'categories_description' => 'A különböző kategóriáknak köszönhetően mások könnyebben megtalálhatják a szervered.',
            'vote' => 'Szavazás',
            'vote_description' => 'Megkérhetsz más felhasználókat, hogy szavazzanak a szerveredre.',
            'fair_listings' => 'Igazságosság',
            'fair_listings_description' => 'A szerverek megjelenési sorrendjén nem lehet mesterségesen változtatni.',
            'support' => '24 órás támogatás',
            'support_description' => 'Kérdésed van vagy segítségre van szükséged? Bármikor felveheted velünk a kapcsolatot és gyorsan válaszolunk, éjjel-nappal.',
            'custom_features' => 'Egyedi funkciók',
            'custom_features_description' => 'Hiányolsz egy funkciót? Hozz létre egy támogatási jegyet és intézkedünk!',
            'faq' => [
                'title' => 'Kérdezz-felelek',
                'suited-question' => 'A SkinMC-re való a Minecraft-szerverem?',
                'suited-answer' => 'A SkinMC-t meglátogató Minecraft-játékosok imádnak új élményeket, tartalmakat és közösségeket felfedezni. Ezen a platformon rengeteg új és egyedi szervert fedezhetsz fel. Itt bármit felfedezhetsz a nagyobb közösségektől a kisebb túlélő szerverekig.',
                'get-started-question' => 'Mivel kezdjem?',
                'get-started-answer' => 'A szervered listázása nagyon egyszerű a SkinMC-n! Először is, regisztrálj egy fiókot ha még nem tetted volna meg, majd kövesd a szerverhozzáadási varázsló lépéseit! Csak írj leírást és csatolj néhány fényképet, és a szervered seperc alatt listázva lesz!',
                'players-question' => 'Hogyan csalogathatok több játékost a Minecraft-szerveremre?',
                'players-answer' => 'Egy erős Minecraft-szerver kulcsa a közösségépítés. A SkinMC szerverböngészője segítségével könnyen találhatsz új közönséget, amiből közösséget építhetsz. Kérd meg a játékosaidat, hogy ajánlják másoknak a szerveredet és osszák meg közösségi oldalakon. Kedvező értékelések is nagy szerepet játszhatnak a szerver népszerűsítésében.',
                'more-question' => 'Egyéb kérdésem van. Hol kaphatok segítséget?',
                'more-answer' => 'A SkinMC-t éjjel-nappal felkeresheted a Súgó-gombbal és az ügyfélszolgálaton, vagy a Discord-szerveren.'
            ],
            'ready_to_list_description' => 'A Minecraft-szerveredet néhány perc alatt hozzáadhatod a SkinMC adatbázisához. Ha segítségre van szükséged, éjjel-nappal elérhetsz minket.'
        ],
        'manage' => [
            'index' => [
                'welcome' => 'Üdv újra, :username!',
                'your_servers' => 'Saját szerverek',
                'reviews_today' => 'Mai értékelések',
                'no_reviews_today' => 'Nincs újdonság',
                'no_reviews_text' => 'A mai napon nem kaptál új értékeléseket. Kérd meg a játékosaidat, hogy értékeljék a szervered!',
                'tips' => [
                    'title' => 'Tippek',
                    'description-title' => 'Írj részletes leírást!',
                    'description-body' => 'A hasznos tippeknek és tanácsoknak jó helye van a leírásban.',
                    'images-title' => 'Csatolj képeket a szerverről!',
                    'images-body' => 'Jó képekkel feltűnőbb egy szerver.'
                ]
            ],
            'listings' => [
                'title' => 'Az általad birtokolt Minecraft-szerverek (:count db)'
            ],
            'insights' => [
                'title' => 'Kimutatások'
            ],
            'edit_server' => 'Szerkesztés',
            'listing' => 'Szerveroldal',
            'to_do' => 'Teendők',
            'last_update' => 'Utoljára frissítve',
            'add_more_photos_to_publish' => 'Csatolj fényképeket!',
            'looks_empty_here' => 'Nincs itt semmi.',
            'get_started_by_adding_a_new_server' => 'A kezdéshez add hozzá a szerveredet az adatbázishoz!'
        ],
        'status' => [
            'approved' => 'Jóváhagyott',
            'pending_approval' => 'Jóváhagyásra vár',
            'published' => 'Közzétett',
            'in_review' => 'Ellenőrzés alatt'
        ]
    ],
    'editor' => [
        'import' => [
            'title' => 'Kinézet importálása',
            'import_by_username' => 'Importálás felhasználónév alapján',
            'import_button' => 'Importálás',
            'drag' => 'Kattints, vagy húzz ide egy kinézetet',
            'click' => 'Kép kiválasztása'
        ],
        'download' => [
            'error' => [
                'no-data' => 'No skin data was provided. Please try again.',
                'invalid-format' => 'The skin data format is invalid. Please try again.',
                'invalid-data' => 'The skin data is corrupted. Please try again.',
                'generic' => 'Something went wrong while downloading your skin. Please try again.',
            ],
        ],
        'draw' => 'Draw',
        'eyedropper' => 'Eyedropper',
        'fill' => 'Fill',
        'move' => 'Move',
        'decrease_brightness' => 'Decrease brightness',
        'increase_brightness' => 'Increase brightness',
        'erase' => 'Erase',
        'undo' => 'Step back (CTRL+Z)',
        'redo' => 'Step forward (CTRL+Y)',
        'default_view' => 'Default view',
        'zoom_in' => 'Zoom in (CTRL +)',
        'zoom_out' => 'Zoom out (CTRL -)',
        'saved' => 'Legutóbbi frissítés: Most',
        'saving' => 'Automatikus mentés folyamatban…',
        'save_error' => 'Hiba történt',
        'new_skin' => 'New skin',
        'previous_skins' => 'Previous skins',
        'backed_up_title' => 'Automatically saved skins',
        'backed_up_info' => 'Temporarily backed up to your local storage.',
        'backed_up_empty_title' => 'It\'s empty here',
        'backed_up_empty_info' => 'Once you start editing skins you\'ll see your 32 last edited skins here.',
        'backed_up_skins_count' => 'of 32 skin backups used',
        'backed_up_skins_count_info' => 'You can back up to up 32 skins. Once you reach 32 skins an older skin will be replaced with a new one.',
        'layers' => 'Rétegek',
        'body' => [
            'title' => 'Alap',
            'overlay' => 'Felső',
            'head' => 'Fej',
            'torso' => 'Törzs',
            'l_arm' => 'Bal kar',
            'r_arm' => 'Jobb kar',
            'l_leg' => 'Bal láb',
            'r_leg' => 'Jobb láb',
        ],
        'model' => 'Típus',
        'steve' => 'Steve',
        'alex' => 'Alex',
        'stance' => [
            'title' => 'Testtartás',
            'default' => 'Alapértelmezett',
            'walk' => 'Séta',
            'run' => 'Futás',
            'hug' => 'T-póz',
            'fly' => 'Repülés',
        ],
        'fullscreen' => 'Fullscreen',
        'fullscreen_exit' => 'Exit fullscreen',
        'grid' => 'Rács',
        'show_grid' => 'Rács mutatása',
        'download' => [
            'title' => 'Mentés és letöltés',
            'subtitle' => 'SkinMC-fiók',
            'description' => 'Szeretnél létrehozni egy SkinMC-fiókot, hogy elmenthesd ezt és a jövőbeli kinézeteidet a felhőbe?',
            'start_description' => 'Közvetlen letöltés, a felhőbe mentés nélkül',
            'start' => 'Kinézet letöltése',
        ],
        'help' => [
            'title' => 'Minecraft Skin Editor',
            'about' => 'Create and edit your custom Minecraft Skin easily with the SkinMC Editor. You can choose between Steve and Alex models, import skins from a file or username, and create your very own Minecraft Skin.',
            'draw' => 'Draw using the pen tool. Select a colour from the swatch to use with it.',
            'eyedropper' => 'Use the eyedropper to select a colour from your skin and add it to your current palette.',
            'fill' => 'Fill entire areas of your skin using the fill tool. Select a colour before using fill.',
            'move' => 'Pan and move around the skin editor canvas with the move tool.',
            'decrease_brightness' => 'Decrease the brightness of the currently active colour.',
            'increase_brightness' => 'Increase the brightness of the currently active colour.',
            'erase' => 'Erase pixels drawn on the secondary overlay layer.',
        ],
    ],
    'account' => [
        'level' => 'Level',
        'level_history' => 'Level history',
        'xp' => 'XP',
        'my_xp' => 'My XP',
        'xp_to_next_level' => ':xp XP to next level',
        'xp_info' => 'What are XP?',
        'xp_info_tooltip' => 'XP is earned for various activities such as adding tags to skins, inviting friends, commenting, and much more. With each XP earned you can level up and unlock cool things!',
        'settings' => [
            'title' => 'Fiók',
            'show_profile' => 'Ugrás a profilhoz',
            'friends' => 'Barátok',
            'friends_detail' => 'Maradj kapcsolatban a SkinMC-s barátlista használatával!',
            'security' => 'Biztonság',
            'security_detail' => 'A fiókod biztonsága érdekében változtasd meg a jelszavad!',
            'social' => 'Közösségi fiókok',
            'social_detail' => 'Személyre szabhatod a profilodat a közösségi oldalaid hivatkozásával.',
            'link' => 'Minecraft-fiók összekapcsolása',
            'link_detail' => 'A Minecraft-fiókod összekapcsolásával igazolhatod a tulajdonjogod.',
            'logout' => 'Ki szeretnél jelentkezni a SkinMC-fiókodból?',
            'automatic_backups' => 'Automatic skin backups',
            'automatic_backups_info' => 'As a SkinMC plus member your skins are backed up daily.',
        ],
        'capes' => [
            'title' => 'SkinMC Minecraft-köpeny',
            'description' => 'Egy SkinMC-s köpeny használatával ingyenesen személyre szabhatod a viseletedet.',
            'drop' => 'Húzz ide egy köpenyt!',
            'drop-hint' => 'Felbontás: 64 × 32 képpont',
            'select' => 'Kép kiválasztása',
            'upload-cape' => 'Köpeny feltöltése és használata',
            'save-and-use' => 'Mentés és használat',
            'uploaded-cape' => 'Feltöltött köpeny',
            'no-cape' => 'Köpeny kikapcsolása',
            'remove-cape' => 'Köpeny eltávolítása',
            'download' => 'A SkinMC mod letöltésével láthatod a saját és mások egyéni köpenyeit a játékon belül.',
            'learn-more' => 'További információ',
            'link-account' => 'Köpeny feltöltéséhez össze kell kapcsolnod a Minecraft-fiókodat!',
            'updated' => 'Köpeny frissítve.',
            'removed' => 'Köpeny eltávolítva.',
            'active' => 'Köpeny bekapcsolva.'
        ],
        'favourite' => 'Kedvencnek jelölés',
        'remove_favourite' => 'Eltávolítás a kedvencek közül',
        'added_to_favourites' => 'Kedvencnek jelölve.',
        'removed_from_favourites' => 'Eltávolítva a kedvencek közül.',
        'welcome' => 'Isten hozott!',
        'view-profile' => 'Saját profil megtekintése',
        'security' => [
            'title' => 'Biztonság',
            'email' => 'Email-cím',
            'email-title' => 'Email-cím frissítése.',
            'save' => 'Mentés',
            'password' => 'Jelszó',
            'password-title' => 'A jelszavad bármikor megváltoztathatod.',
            'social-provider' => 'To update your account information, such as your password, please visit your login provider:',
            'social-provider-email' => 'Your associated email address with your login provider',
            'social-provider-connected' => 'Currently connected login providers',
            'current-password' => 'Jelenlegi jelszó',
            'forgot' => 'Elfelejtetted a jelszavad?',
            'edit' => 'Szerkesztés',
            'delete' => 'Fiók törlése',
            'account-deletion' => 'SkinMC-fiók törlése.',
            'delete-info' => 'A folytatáshoz megerősítés szükséges',
            'delete-confirmation' => 'A fiókod törlése végleges! Minden személyes adatod és az általad megosztott tartalmak, pl. a bejegyzéseid, kedvenceid, feltöltött köpenyeid, a személyre szabott profilod, stb. törölve lesz. Ez a folyamat visszavonhatatlan.',
            'delete-confirmation-info' => 'A folytatáshoz add meg a jelszavad!',
            'yes-confirm-delete' => 'Igen; fiók törlése',
            'account-successfully-deleted' => 'A fiókod és minden hozzá tartozó adat törlésre került.'
        ],
        'social' => [
            'title' => 'Közösségi oldalak',
            'edit' => 'Szerkesztés',
            'save' => 'Mentés',
            'link-account' => 'A közösségi oldalaid hivatkozásához először össze kell kapcsolnod a SkinMC-t a Minecraft-fiókoddal!',
            'finish-setup' => 'Befejezés',
            'connect-account' => 'Fiókok összekapcsolása',
            'connect-description' => 'Válaszd ki, hogy mely fiókokat szeretnél összekapcsolni a SkinMC-vel és használni a hozzájuk tartozó integrációkat!',
            'empty' => 'Nincsenek kapcsolatok',
            'empty-description' => 'A közösségi oldalaid itt és a nyilvános profilodon fognak megjelenni. Kapcsolódás után még egyedibbé tehetik az profilodat és használhatod a hozzájuk tartozó integrációkat.',
            'connect' => 'Összekapcsolás',
            'username' => 'felhasználónév',
            'spotify' => 'Ha szeretnél a profilodon Spotify-adatokat megjeleníteni, add meg a Spotify-felhasználónevedet!',
            'discord' => 'Ha szeretnél a profilodon Discord-adatokat megjeleníteni, add meg a Discord-felhasználónevedet és az utána lévő négy számot!',
            'youtube' => 'Ha szeretnéd a YouTube-csatornádat megjeleníteni a profilodon, add meg a csatornaazonosítót!',
            'youtube-format' => 'A csatorna hivatkozásának felépítésétől függően az alábbi formátumok valamelyikét kell megadnod:',
            'twitter' => 'Enter your X (formerly Twitter) username to display it on your profile.',
            'bluesky' => 'Enter your Bluesky handle e.g. username.bsky.social to display your Bluesky profile on your profile.',
            'twitch' => 'Ha szeretnél a profilodon Twitch-adatokat megjeleníteni, add meg a Twitch-felhasználónevedet!',
            'reddit' => 'Ha szeretnél a profilodon Reddit-adatokat megjeleníteni, add meg a Reddit-felhasználónevedet!',
            'github' => 'Ha szeretnél a profilodon GitHub-adatokat megjeleníteni, add meg a GitHub-felhasználónevedet!',
            'telegram' => 'Ha szeretnél a profilodon Telegram-adatokat megjeleníteni, add meg a Telegram-felhasználónevedet!',
            'tiktok' => 'Ha szeretnél a profilodon TikTok-adatokat megjeleníteni, add meg a TikTok-felhasználónevedet!',
            'snapchat' => 'Ha szeretnél a profilodon Snapchat-adatokat megjeleníteni, add meg a Snapchat-felhasználónevedet!',
            'instagram' => 'Ha szeretnél a profilodon Instagram-adatokat megjeleníteni, add meg a Instagram-felhasználónevedet!',
            'facebook' => 'Ha szeretnél a profilodon Facebook-adatokat megjeleníteni, add meg a Facebook-felhasználónevedet!',
            'includes_skinmc_plus_benefits' => 'Includes SkinMC plus benefits',
        ],
        'recover' => [
            'title' => 'Fiók helyreállítása',
            'subtitle' => 'A fiók helyreállításához adj meg egy új jelszót!',
            'new_password' => 'Új jelszó',
            'repeat_new_password' => 'Jelszó újra',
            'submit' => 'Fiók helyreállítása',
        ],
        'customise' => [
            'title' => 'Fiók testreszabása',
            'description' => 'Hivatkozz a közösségi oldalaidra, válassz ki egy emojit, add meg a tartózkodási helyedet, stb.',
            'information' => 'Adatok',
            'preview' => 'Előnézet',
            'location' => [
                'title' => 'Tartózkodási hely',
                'description' => 'Add meg a profilodon megjelenítendő helyet!',
            ],
            'biography' => [
                'title' => 'Magamról',
                'description' => 'Mesélj magadról!',
            ],
            'status' => 'Állapot',
            'status-toggle' => 'Elérhetőségi állapot mutatása',
            'emoji' => 'Emoji',
            'name-history-toggle' => 'Felhasználónévelőzmények titkosítása',
            'name-history-info' => 'A korábbi Minecraft-felhasználóneveid jelenleg',
            'name-history-toggle-on' => 'titkosak',
            'name-history-toggle-off' => 'nyilvánosak',
            'theme' => 'Profil témája',
            'theme-primary' => 'Alapszín',
            'theme-secondary' => 'Másodlagos szín',
            'appearance' => 'Appearance',
        ],
        'link' => [
            'manage' => 'Összekapcsolt Minecraft-fiók kezelése',
            'description' => 'A Minecraft-fiókod megtekintése és kezelése.',
            'title' => 'Összekapcsolt Minecraft-fiók',
            'current' => 'A jelenleg összekapcsolt Minecraft-fiók.',
            'status' => 'Hozzáférést nyertél az összes SkinMC-funkcióhoz!',
            'linked' => 'Összekapcsolva',
            'disconnect' => 'Szétválasztás',
            'disconnect-title' => 'Minecraft-fiók szétválasztása',
            'disconnect-info' => 'Biztosan szét szeretnéd választani a Minecraft- és SkinMC-fiókjaidat?',
            'disconnect-features' => 'A szétkapcsolás után nem leszel képes új hozzászólásokat írni, a profilod testreszabására, illetve az olyan további funkciók használatára, amelyek egy összekapcsolt Minecraft-fiókot igényelnek. Ahhoz, hogy ezeket újra használhasd, ismételten össze kell majd kapcsolnod a fiókjaidat.',
            'disconnect-following' => 'Ezen felül a követett felhasználók listája véglegesen ki lesz ürítve,',
            'disconnect-posts' => 'és a múltban létrehozott idővonalas bejegyzéseid és kedveléseid is törlésre kerülnek.',
            'can-not-undo' => 'Ezt nem lehet visszavonni.',
            'are-you-sure' => 'Biztos vagy benne?',
            'confirm' => 'Igen; szétkapcsolás',
            'cancel' => 'Mégse',
            'success' => 'A fiókjaidat sikeresen szétkapcsoltuk.'
        ],
        'finish-setup' => [
            'title' => 'Fiókbeállítások véglegesítése',
            'description' => 'Az összes SkinMC-funkció feloldásához össze kell kapcsolnod ezt a Minecraft-fiókoddal.',
            'link' => 'Minecraft-fiók összekapcsolása',
            'get-started' => 'Folytatás',
            'skip' => 'Kihagyás',
            'claim' => 'Fiók igazolása',
            'customise' => 'Profil testreszabása',
            'social' => 'Közösségi fiókok kapcsolása',
            'comment' => 'Hozzáférés a hozzászólás-rendszerhez',
            'direct_message' => 'Közvetlen üzenetek küldése',
            'feed' => 'Állapotfrissítések közzététele',
            'follow' => 'Barátok követése',
            'badge' => 'Hitelesítő jelvény',
            'cape' => 'Egyedi Minecraft-köpeny',
            'backup' => 'Automatic skin backup',
            'more' => 'És még sok más…'
        ],
        'skins' => [
            'title' => 'Kinézetek kezelése',
            'toggle' => 'Láthatóság kikapcsolva',
        ],
        'invite' => [
            'title' => 'My invites',
            'headline' => 'Invite your friends',
            'info' => 'Create an invite code to share with your friend. Once they accept it, you\'ll both earn some extra XP!',
            'description' => 'Create an invite for your friends and you\'ll both earn some extra XP.',
            'generate' => 'Create invite code',
            'empty' => 'You haven\'t created any invites yet.',
            'code' => 'Code',
            'expiry' => 'Each code works once.',
            'status' => [
                'title' => 'Status',
                'pending' => 'Pending',
                'accepted' => 'Accepted'
            ],
            'add_invite' => [
                'button' => 'Have an invite?',
                'title' => 'Add an invite code',
                'redeem' => 'Redeem invite',
            ],
            'share' => 'Send your friend an invite link'
        ],
        'emoji' => [
            'title' => 'SkinMC Emoji',
            'introducing' => 'Introducing',
            'info' => 'Customise your profile with emoji. Unlock more as you level up.',
            'unlocked_at' => 'Unlocked at level :level',
            'unlocks_at' => 'Reach level :level to unlock',
            'turn_off' => 'Show emoji'
        ]
    ],
    'notifications' => [
        'title' => 'Értesítések',
        'view_all' => 'Összes megtekintése',
        'view_all_notifications' => 'Összes értesítés',
        'image' => 'Értesítés képe',
        'archived' => 'Archivált',
        'inbox' => 'Bejövő üzenetek',
        'empty' => [
            'title' => 'Naprakész vagy!',
            'text' => 'A bejövő értesítések itt fognak megjelenni.',
            'text-archived' => 'Az archivált értesítések itt fognak megjelenni.',
        ],
        'action' => [
            'archive' => 'Archiválás',
            'unarchive' => 'Archiválás visszavonása',
            'open' => 'Megnyitás',
        ],
        'toast' => [
            'archive' => 'Értesítés archiválva.',
            'unarchive' => 'Értesítés visszaállítva.',
            'undo' => 'Visszavonás',
        ]
    ],
    'error' => [
        'offline' => [
            'title' => 'Nincs kapcsolat.',
            'subtitle' => 'Megszakadt a hálózati kapcsolat. Ellenőrizd a kapcsolatot, majd töltsd újra a lapot.',
            'try_again' => 'Újra'
        ],
        '404' => [
            'title' => '404 – Az oldal nem található.',
            'subtitle' => 'Hmm… Nincs itt semmi. Próbálj visszamenni vagy indíts új keresést!',
            'try_again' => 'Főoldal'
        ],
    ],
    'heads' => [
        'list' => [
            'meta' => [
                'title' => 'Minecraftfej-adatbázis',
                'description' => 'Böngészd át a Minecraftfej-adatbázist és találj fejeket, amelyekkel kidíszítheted a világodat, vagy generálj egy /give-parancsot! Itt megtekintheted a hivatalos fejeket, játékosok fejeit, és egyedi fejeket, melyek sosem változnak.'
            ],
            'header' => [
                'title' => 'Minecraft-fejek',
                'subtitle' => 'Böngészd át a Minecraftfej-adatbázist és találj fejeket, amelyekkel kidíszítheted a világodat, vagy generálj egy /give-parancsot! A játékosfejek az adott játékos mindenkori kinézetét mutatják. Az egyedi fejek a Mojang kinézetfájljához kapcsolódnak és sosem változnak meg. Az utóbbiakat csak parancsblokkal idézheted meg, mert a hozzájuk tartozó parancs nagyon hosszú.',
            ],
            'count' => [
                'heads' => ':heads fej',
            ],
            'customheads' => [
                'title' => 'Egyedi fejek',
                'description' => 'Az egyedi fejek közvetlen elérési utat használnak a Mojang szerverein található textúrafájlhoz, ezért a fejek sosem fognak megváltozni.',
                'version' => 'Minecraft 1.8 és későbbi verziók',
            ],
            'playerheads' => [
                'title' => 'Játékosfejek',
                'description' => 'A játékosfejek az adott játékos mindenkori kinézetét használják. Mivel felhasználónévalapúak, ezért minden kinézetváltással megváltoznak.',
                'version' => 'Az összes Minecraft-verzió',
            ]
        ],
    ],
    'mod' => [
        'title' => 'SkinMC mod: Ingyenes, egyedi köpenyek.',
        'headline' => 'Bemutatjuk a SkinMC modot, ami még több személyre szabást tesz lehetővé!',
        'description' => 'Ideje meghálálni a Minecraft-közösség szeretetét egy ingyenes moddal, ami lehetővé teszi az egyedi köpenyek használatát! Ezeket a köpenyeket bárki használhatja és láthatja, akinek telepítve van a mod.',
        'download' => 'Letöltés',
        'download-title' => 'Mod letöltése',
        'requires' => 'Alapkövetelmény:',
        'select-version' => 'Válaszd ki a Minecraft-verziód!',
        'get-started' => 'Vágjunk bele!',
        'step-1' => '1. Telepítsd a modot!',
        'step-1-detail' => 'Telepítsd a Fabricot, majd töltsd le a Minecraft-verziódhoz kapcsolódó SkinMC .jar-fájlt és helyezd a „mods” mappába!',
        'step-2' => '2. Kapcsold össze a fiókodat!',
        'step-2-detail' => 'Ha még nem tetted volna meg, regisztrálj és jelentkezz be, majd kapcsold össze a Minecraft-fiókodat a SkinMC-vel!',
        'step-3' => '3. Töltsd fel a köpenyedet!',
        'step-3-detail' => 'Nyisd meg a fiókbeállításokat és töltsd fel a használni kívánt egyedi köpenyt! Ezután a játékban rögtön láthatóvá válik.',
        'all-versions' => 'További verziók',
        'latest' => 'Legfrissebb',
        'logged-in' => 'Köpeny feltöltése',
        'mirror' => 'Tükör',
        'download-via' => 'Letöltés:',
        'curseforge' => 'CurseForge',
    ],
    'app' => [
        'title' => 'SkinMC Android-alkalmazás',
        'headline' => 'Bemutatjuk a SkinMC Android-alkalmazást',
        'play-store-attribution' => 'A Google Play és a Google Play logó a Google LLC védjegyei.',
        'features' => 'Hordozható funkciók',
        'feature-qr' => 'Beépített QR kód olvasó',
        'feature-qr-detail' => 'A beépített QR kód olvasóval könnyen megnyithatsz egy kinézetet a mobilalkalmazásban, vagy megnézheted a barátaid profilját.',
        'feature-files' => 'Közvetlen mentés',
        'feature-files-detail' => 'Az Android Fájlkezelő használatával az alkalmazás könnyen tud kinézeteket menteni, amiket rögtön használhatsz a játék telefonos kiadásában.',
        'feature-noads' => 'Hirdetések nélkül',
        'feature-noads-detail' => 'Letisztult felület, zavaró tényezők nélkül. A mobilalkalmazásban nincsenek hirdetések.',
        'feature-experience' => 'Funkcióteljesség',
        'feature-experience-detail' => 'A SkinMC-élmény mobilon sincs leegyszerűsítve. Szabd személyre a profilod, mesélj magadról, hozz létre QR kódokat és még sok más!',
        'get-app-headline' => 'A SkinMC-alkalmazás letöltése',
        'get-app-detail' => 'Tökéletes társ a Minecrafthoz Androidon – teljesen ingyen.'
    ],
    'random' => [
        'title' => 'Véletlenszerű Minecraft-kinézet betöltése…',
        'description' => 'Véletlenszerű Minecraft-kinézet betöltése…',
        'headline' => 'Egy pillanat…',
        'redirect' => 'Automatikusan át leszel irányítva. Nem tölt az oldal?',
        'click-here' => 'Kattints ide',
        'messages' => [
            '1' => 'Véletlenszerű Minecraft-kinézet betöltése…',
            '2' => 'Lefelé ásás…',
            '3' => '„Creeper? Aw, man…”',
            '4' => 'Ládák átkutatása…',
            '5' => 'Tudtad, hogy a kinézet, amit most fogsz látni, teljesen véletlenszerű?',
            '6' => 'Érkezik a véletlenszerű kinézet…',
            '7' => 'Még egy blokk…',
            '8' => 'Eszköztár rendezése…',
            '9' => 'Gyémántcsákány barkácsolása…',
            '10' => 'Herobrine keresése…',
        ],
    ],
    'feed' => [
        'title' => 'Hírfolyam',
        'following' => 'Követett',
        'sign-up' => 'A beszélgetésbe csatlakozáshoz regisztrálj vagy jelentkezz be!',
        'link-account' => 'A beszélgetésbe csatlakozáshoz kapcsold össze a Minecraft-fiókodat a SkinMC-vel!',
        'placeholder' => 'What is happening?',
        'audience' => 'Közönség',
        'audience-title' => 'Láthatóság',
        'everyone' => 'Mindenki',
        'everyone-info' => 'A SkinMC-n és azon kívül bárki.',
        'followers' => 'Követők',
        'followers-info' => 'Csak azok, akik be vannak jelentkezve és követnek téged.',
        'private' => 'Csak én',
        'private-info' => 'Privát bejegyzés, amit csak te láthatsz.',
        'submit' => 'Küldés',
        'like' => 'Kedvelés',
        'comment' => 'Hozzászólás',
        'share' => 'Megosztás',
        'remaining' => 'Hátralévő',
        'profile' => ':username bejegyzései',
        'posts' => 'Minden bejegyzés',
        'my-posts' => 'Saját bejegyzések',
        'view-all' => 'Összes bejegyzés megtekintése',
        'post' => [
            'meta' => ':username bejegyzése a SkinMC-n: :text',
            'title' => 'Bejegyzés',
            'created' => 'Állapotfrissítés közzétéve.',
            'confirm-delete' => 'Biztosan törölni akarod ezt a bejegyzést? Ezt nem lehet visszavonni!',
            'delete' => 'Törlés',
            'deleted' => 'Bejegyzés törölve.',
        ],
        'repost' => [
            'button' => 'Repost',
            'quote_button' => 'Quote',
            'title' => 'Repost this post',
            'quote_title' => 'Quote post',
            'quote_label' => 'Add a comment (optional)',
            'quote_placeholder' => 'Add your thoughts...',
            'reposted' => 'reposted',
            'success' => 'Reposted!',
            'removed' => 'Repost removed.',
            'already_reposted' => 'You have already reposted this.',
            'undo' => 'Undo repost',
            'original_deleted' => 'The original post has been deleted.',
            'deleted_post' => 'This post has been deleted',
        ],
        'poll' => [
            'title' => 'Poll',
            'create' => 'Create a poll',
            'option' => 'Option',
            'add_option' => 'Add option',
            'duration' => 'Duration',
            'duration_1' => '1 day',
            'duration_3' => '3 days',
            'duration_7' => '7 days',
            'votes' => '{0} votes|{1} vote|[2,*] votes',
            'ended' => 'Poll ended',
            'ends_in' => 'Ends :time',
            'login_required' => 'Sign in to vote',
        ],
        'gif' => [
            'title' => 'GIF',
            'search_placeholder' => 'Search KLIPY for GIFs...',
            'no_results' => 'No GIFs found',
            'powered_by' => 'Powered by',
            'categories' => 'Categories',
            'trending' => 'Trending',
        ],
        'media' => 'Media',
        'follow-suggestions' => 'Kövesd a csapatot!',
        'explore' => 'Felfedezés',
        'hashtag' => 'Címke',
        'stories' => [
            'archive' => [
                'title' => 'Story Archive',
                'subtitle' => 'Your archived stories are only visible to you',
                'empty' => 'No archived stories yet',
                'empty-description' => 'Stories you post will appear here after 24 hours.',
                'action' => 'Archive',
                'archived' => 'Story moved to archive.',
                'already-archived' => 'Story is already archived.',
            ],
        ],
    ],
    'private' => [
        'title' => 'Privát bejegyzések',
        'text' => 'Ez a bejegyzés privát.'
    ] ,
    'liked' => [
        'title' => 'Kedvelt'
    ],
    'following' => [
        'title' => 'Követett',
        'text' => 'A bejegyzés megtekintéséhez be kell jelentkezned!'
    ],
    'tags' => [
        'empty' => 'Még nincs mire szavazni.',
        'empty-subtitle' => 'Hozd létre az elsőt!',
    ],
    'inbox' => [
        'title' => 'Üzenetek',
        'details' => 'Részletek',
        'message_user' => 'Üzenet',
        'write_message' => 'Üzenet írása',
        'empty' => [
            'no_message_selected' => 'Nincs kiválasztott beszélgetés',
            'open_or_start_conversation' => 'Nyiss meg egy beszélgetést vagy hozz létre egy újat!',
            'no_messages' => 'Nincs olvasatlan üzenet.',
            'start_conversation' => 'Ha elkezdesz egy beszélgetést, itt fognak megjelenni az üzenetek.',
            'conversation' => 'Itt kezdődik a beszélgetésetek.',
            'users' => 'A keresési feltételeknek egy felhasználó sem felelt meg.'
        ],
        'typing' => ':username is typing...',
        'new_message' => 'Új üzenet',
        'mark_unread' => 'Megjelölés olvasatlaként',
        'send_message' => 'Üzenet küldése',
        'delete_message' => 'Üzenet törlése csak neked',
        'latest_conversations' => 'Legutóbbi beszélgetések',
        'delete_conversation' => 'Beszélgetés törlése',
        'show_details' => 'Részletek mutatása',
        'hide_details' => 'Részletek elrejtése',
        'unread' => 'Olvasatlan',
        'deleted' => 'Törölt',
        'report_message' => 'Üzenet jelentése',
        'add_reaction' => 'Add reaction',
        'today' => 'Ma',
        'reconnect' => 'A beszélgetéshez kapcsold össze a Minecraft-fiókodat a SkinMC-vel!',
        'account_disconnected' => 'Ez a felhasználó összekapcsolta a Minecraft-fiókját a SkinMC-vel.',
        'saved_messages' => 'Mentett üzenetek',
        'new_message_to_label' => 'Címzett',
        'external-link-to' => 'Ez a hivatkozás az alábbi oldalra fog átirányítani:',
        'external-link-confirmation' => 'Biztosan el akarod hagyni a SkinMC-t?',
        'external-link' => 'Külső hivatkozás',
        'reply' => 'Reply'
    ],
    'server' => [
        'manage' => [
            'stats' => 'Statisztikák'
        ]
    ],
    'report' => [
        'button' => 'Report',
        'title' => 'Report content',
        'describe' => 'Briefly describe why you are reporting this',
        'select' => 'Select report reason',
        'submit' => 'Submit report',
        'reasons' => [
            'INAPPROPRIATE_CONTENT' => 'Inappropriate content',
            'SPAM' => 'Spam',
            'HARASSMENT' => 'Harassment',
            'OTHER' => 'Other',
        ]
    ],
    'leaderboard' => [
        'title' => 'Leaderboard',
        'description' => 'View the SkinMC leaderboard of users.',
        'headline' => 'Top 10',
        'all-time-invites' => 'All time invites',
        'all-time-xp' => 'All time XP',
        '30-day-xp' => '30 days XP'
    ],
];
