<?php

return [
    'title' => 'Account bloccati',
    'description' => 'Gestisci gli account bloccati. Solo tu puoi vedere questa lista.',
    'empty_page' => 'Nessun account bloccato rimane su questa pagina.',
    'empty' => 'Non hai bloccato alcun account.',
    'block' => 'Blocca :username',
    'unblock' => 'Sblocca :username',
    'block_title' => 'Blocca :username?',
    'unblock_title' => 'Sblocca :username?',
    'confirm_block' => 'Blocca',
    'confirm_unblock' => 'Sblocca',
    'cancel' => 'Annulla',
    'block_description' => 'You won’t see each other’s posts or be able to message or follow each other. You’ll both be removed from each other’s followers. You can unblock them in settings.',
    'groups_description' => 'Nei gruppi condivisi, resterete membri ma non vedrete i rispettivi messaggi o riceverete notifiche gli uni dagli altri.',
    'public_description' => 'I post pubblici e i dati di Minecraft rimangono accessibili una volta disconnessi.',
    'blocked' => 'Account bloccato.',
    'unblocked' => 'Account unblocked. Following has not been restored.',
    'error' => 'La modifica non può essere salvata. Riprova.',
    'saving' => 'Salvataggio in corso…',
    'unavailable' => 'Questa interazione non è disponibile.',
    'content_unavailable' => 'Questo contenuto non è disponibile.',
    'profile_blocked' => 'Hai bloccato :username.',
    'profile_unavailable' => 'I contenuti social di questo account non sono disponibili.',
    'conversation_unavailable' => 'I messaggi non sono disponibili per questa conversazione. I messaggi precedenti sono ancora qui per il riferimento e la segnalazione.',
    'blocked_on' => 'Bloccato :date',
    'back_settings' => 'Torna alle impostazioni',
    'shared_group_notice' => 'Questo gruppo include un account con cui non puoi interagire. I loro messaggi e le notifiche saranno nascoste. L\'adesione al gruppo rimane visibile.',
];
