<?php

return [
    'moderation' => [
        'changes_required' => 'Changes required',
        'awaiting_review' => 'Awaiting review',
        'approval_required' => 'Approval required to publish',
        'offline' => 'Page offline',
        'offline_description' => 'Your page is offline following a moderation decision.',
        'changes_live' => 'Your submitted update needs changes. Your previously approved page is still public.',
        'restricted_description' => 'Changes saved in this link-page editor need approval before publication. You can still edit, save and preview your page. Profile details and linked creations continue to update from SkinMC.',
        'instructions' => 'What needs changing',
        'editing_hint' => 'Your draft, uploads and analytics are still here. Make the requested changes, or explain why you believe the decision was mistaken, then request a review.',
        'review_hint' => 'Save and preview your page, then request a review when you are ready to publish.',
        'pending_offline' => 'Your submitted page is waiting for our moderation team. It will stay offline until approved.',
        'pending_live' => 'Your update is waiting for our moderation team. Your previously approved page is still public.',
        'submitted' => 'Submitted',
        'your_explanation' => 'Your explanation',
        'newer_draft' => 'You have newer draft changes. These are private until you update your submission and it is approved.',
        'request_review' => 'Request review',
        'update_submission' => 'Update submission',
        'withdraw_review' => 'Withdraw review',
        'message_label' => 'What changed, or why should we reconsider?',
        'message_help' => 'Help our team understand your changes or your reason for asking us to reconsider. Use 10–2,000 characters.',
        'approval_consent' => 'We will save your current draft and submit this version for review. If approved, this submitted version will be published. Further edits in this editor stay private until you update the submission. Profile details and linked creations continue to update from SkinMC.',
        'submitting' => 'Submitting…',
        'keep_editing' => 'Keep editing',
        'withdraw_confirm' => 'This submission will no longer be reviewed. Your page will stay offline and your saved edits will remain.',
        'withdraw_live_confirm' => 'This submitted update will no longer be reviewed. Your approved page will stay public and your saved edits will remain.',
        'cancel' => 'Cancel',
        'message_required' => 'Tell us what changed or why you would like us to reconsider.',
        'message_short' => 'Please add a little more detail, using at least 10 characters.',
        'message_long' => 'Keep your explanation within 2,000 characters.',
        'publish_blocked' => 'Your page needs approval before it can be published. Save your changes and request a review.',
        'review_unavailable' => 'This page cannot be reviewed right now. Check that your Minecraft profile is still connected and your page content is available.',
        'stale_review' => 'This submission has changed or been withdrawn. Reload the page to review the latest version.',
        'not_required' => 'This page does not need a review. You can publish it from your editor.',
        'reasons' => [
            'spam' => 'Spam',
            'unsafe_links' => 'Unsafe links',
            'inappropriate_content' => 'Inappropriate content',
            'impersonation' => 'Impersonation',
            'copyright' => 'Copyright',
            'other' => 'Other',
        ],
        'notifications' => [
            'taken_offline' => ['title' => 'Your link page is offline', 'text' => ':message Open your editor to make changes or request a review. Public visibility can take up to one minute to update.'],
            'review_approved' => ['title' => 'Your link page was approved', 'text' => 'Your submitted version has been approved and published. Public visibility can take up to one minute to update. :message'],
            'changes_requested' => ['title' => 'Your link page needs changes', 'text' => ':message Open your editor to update your page and request another review.'],
            'restored' => ['title' => 'Your link page restriction was removed', 'text' => 'The moderation decision has been reversed. Your page is still private. Open your editor when you are ready to publish or request approval. :message'],
            'review_required' => ['title' => 'Approval required for your link pages', 'text' => 'Changes saved in your link-page editor now need approval before publication. You can continue editing and saving your drafts. Profile details and linked creations continue to update from SkinMC. :message'],
            'review_requirement_removed' => ['title' => 'You can publish your link pages again', 'text' => 'Your account no longer needs approval to publish changes from the link-page editor. Any page still marked as needing changes must be reviewed first. :message'],
        ],
    ],
    'report' => [
        'title' => 'Report link page',
        'description' => 'Tell us what is wrong with this page. Our moderation team will review your report.',
        'submitted' => 'Your report has been sent to our moderation team.',
        'back' => 'Back to link page',
    ],
    'title' => 'SkinMC.me', 'subtitle' => 'Your corner of Minecraft.', 'links' => 'Links',
    'explore_profile' => 'Explore :username’s page',
    'configure' => 'Your links', 'configure_hint' => 'Add your favourites. Make them yours.',
    'add_collection' => 'Add collection', 'collection_title' => 'Collection title',
    'collection_list' => 'List', 'collection_grid' => 'Grid', 'collection_carousel' => 'Carousel',
    'collection_untitled' => 'Untitled collection', 'collection_item' => 'item', 'collection_items' => 'items',
    'collection_hidden' => 'Hidden', 'collection_actions' => 'Collection actions',
    'hide_collection' => 'Hide collection', 'show_collection' => 'Show collection',
    'edit_title' => 'Edit title', 'edit_link' => 'Edit link', 'link_actions' => 'Link actions', 'link_collapse' => 'Collapse link',
    'hide_link' => 'Hide link', 'show_link' => 'Show link',
    'insert_here' => 'Add here', 'insert_link' => 'Link', 'insert_collection' => 'Collection', 'dismiss' => 'Dismiss',
    'collection_collapse' => 'Collapse collection', 'collection_expand' => 'Expand collection',
    'collection_remove' => 'Remove collection',
    'collection_remove_hint' => 'Links stay on your page. Only this collection and its selected creations are removed.',
    'collection_empty' => 'Drag links here, or add something below.',
    'collection_hidden_hint' => 'This collection and everything inside it are hidden.',
    'add_creations' => 'Add creations', 'creation_actions' => 'Creation actions', 'creation_unavailable' => 'Creation unavailable',
    'creation_unavailable_hint' => 'It may be private or no longer available. You can remove it from this collection.',
    'creations_description' => 'Choose which public creations to show in this collection.',
    'creations_categories' => 'Creation categories', 'creations_retry' => 'Try again',
    'creations_loading' => 'Loading creations', 'creations_selected' => 'selected',
    'creations_cancel' => 'Cancel', 'creations_done' => 'Done', 'close' => 'Close',
    'add_link' => 'Add new link', 'empty_links' => 'Add your first link to get started.',
    'link_title' => 'Link title', 'destination' => 'Destination URL', 'icon' => 'Icon', 'visible' => 'Visible',
    'remove' => 'Remove', 'up' => 'Move up', 'down' => 'Move down', 'reorder' => 'Drag to reorder',
    'layout' => 'Layout', 'thumbnail' => 'Thumbnail', 'compact' => 'Compact', 'featured' => 'Featured',
    'compact_hint' => 'A simple, direct link.', 'featured_hint' => 'Make your link stand out with a large card.',
    'example_link' => 'My link', 'thumbnail_hint' => 'JPEG, PNG or WebP, up to 5 MiB. A wide image (1200 × 375) works well for Featured.',
    'upload_image' => 'Upload image', 'change_image' => 'Change image', 'uploading' => 'Uploading…',
    'remove_image' => 'Remove image', 'socials' => 'Social icons',
    'socials_hint' => 'A few more places to find you.', 'add_social' => 'Add social icon', 'empty_socials' => 'No social icons yet.',
    'platform' => 'Platform', 'status' => 'Status', 'status_title' => 'What’s happening?',
    'status_hint' => 'A little update, right above your avatar.', 'status_label' => 'Status message',
    'status_publish_hint' => 'Plain text and emoji, up to 80 characters.',
    'clear' => 'Clear', 'design' => 'Design', 'design_title' => 'Design your page',
    'design_hint' => 'Choose your theme, wallpaper, buttons and colours.', 'theme' => 'Theme',
    'wallpaper' => 'Wallpaper', 'wallpaper_hint' => 'JPEG, PNG or WebP, up to 5 MiB and 20 megapixels.',
    'buttons' => 'Buttons', 'button_style' => 'Button style', 'button_shape' => 'Button shape',
    'text' => 'Text', 'font' => 'Font', 'colors' => 'Colours', 'stickers' => 'Stickers',
    'sticker' => 'Sticker', 'your_stickers' => 'Your stickers', 'add_sticker' => 'Add sticker', 'done' => 'Done',
    'turn_left' => 'Turn left', 'turn_right' => 'Turn right', 'move_to' => 'Move to',
    'position_top' => 'Top', 'position_middle' => 'Middle', 'position_bottom' => 'Bottom',
    'decorate' => 'Decorate', 'sticker_hint' => 'Tap a sticker to edit it. Drag it on the preview to move it.',
    'sticker_search' => 'Find a sticker', 'search' => 'Search', 'trending' => 'Trending', 'more_stickers' => 'More stickers',
    'sticker_unavailable' => 'This sticker can’t be previewed right now.',
    'sticker_empty' => 'No stickers found. Try another search.', 'previous' => 'Previous', 'next' => 'Next',
    'anchor' => 'Anchor', 'profile' => 'Profile', 'footer' => 'Footer', 'x' => 'Horizontal position', 'y' => 'Vertical position',
    'size' => 'Size', 'rotation' => 'Rotation', 'z_index' => 'Layer', 'save' => 'Save changes',
    'publish' => 'Publish changes', 'unpublish' => 'Unpublish', 'draft' => 'Private draft',
    'published' => 'Published',
    'publication_toggle' => 'Publish page', 'publication_on_hint' => 'Your page is public. Save changes to update it.',
    'publication_off_hint' => 'Your page is private. Turn this on to publish it.',
    'pending_publication' => 'Saved changes are waiting to go live.', 'all_saved' => 'All changes saved',
    'custom' => 'Custom', 'image' => 'Image', 'fill' => 'Fill',
    'sticker_loading' => 'Loading stickers…', 'sticker_limit' => 'You’ve added 12 stickers. Remove one to add another.', 'unpublished_changes' => 'Unsaved changes', 'saving' => 'Saving…',
    'read_only' => 'You need an active Minecraft profile without restrictions to edit your page. Your saved page and analytics are still here.',
    'no_profile' => 'Connect a Minecraft profile to create your page.', 'profile_settings' => 'Edit profile information',
    'synced' => 'Your name, biography, avatar and badges stay in sync with your SkinMC profile.',
    'preview' => 'Live preview', 'copy' => 'Copy address', 'preview_wait' => 'Loading your SkinMC.me preview…',
    'preview_pending' => 'Add a title and URL to each visible link to update the preview.',
    'preview_size' => 'Preview width', 'mobile' => 'Mobile', 'desktop' => 'Desktop',
    'preview_unavailable' => 'The preview couldn’t load. Your edits are still here.', 'retry_preview' => 'Retry preview',
    'reload' => 'Reload saved draft',
    'conflict' => 'This page was updated somewhere else. Your edits are still here. Reload the saved draft before trying again.',
    'retained' => 'Your saved pages', 'new_page' => 'Current profile', 'analytics' => 'Analytics',
    'edit_page' => 'Edit page', 'insights' => 'Insights', 'editor_tabs' => 'Page editor', 'preview_tab' => 'Preview',
    'analytics_overview' => 'Overview', 'analytics_range' => 'Time period',
    'analytics_loading' => 'Loading the last :days days…',
    'analytics_page_views' => 'Page views', 'analytics_link_clicks' => 'Link clicks',
    'analytics_chart_title' => 'Daily page views and link clicks',
    'analytics_chart_summary' => 'Page views: :views. Link clicks: :clicks. :range. Exact daily counts are available below.',
    'analytics_explore_chart' => 'Explore daily activity', 'analytics_chart_help' => 'Use the left and right arrow keys to explore each day. Home and End move to the first and last day.',
    'analytics_day_summary' => 'Views: :views · Clicks: :clicks',
    'analytics_daily' => 'Daily breakdown', 'analytics_no_activity' => 'No activity yet',
    'analytics_top_links' => 'Top links', 'analytics_top_links_hint' => 'Links and social icons, ordered by clicks.',
    'analytics_no_clicks' => 'Your most-clicked links will appear here.',
    'analytics_show_all' => 'Show all links', 'analytics_show_less' => 'Show fewer',
    'analytics_hint' => 'Totals are approximate, not unique visitors. Blocked requests aren’t counted and some bot traffic may be included.',
    'days' => ':days days', 'views' => 'Total views', 'clicks' => 'Total clicks', 'date' => 'Date (UTC)',
    'link_click' => 'click', 'link_clicks' => 'clicks',
    'item' => 'Link or social icon', 'removed_link' => 'Removed link', 'analytics_empty' => 'Your totals will appear after your page receives visits.',
    'themes' => ['clean' => 'Clean', 'midnight' => 'Midnight', 'grass' => 'Grass', 'amethyst' => 'Amethyst'],
    'fonts' => ['system' => 'System', 'satoshi' => 'Satoshi', 'minecraft' => 'Minecraft'],
    'styles' => ['outline' => 'Outline', 'filled' => 'Filled'],
    'shapes' => ['pill' => 'Pill', 'rounded' => 'Rounded', 'square' => 'Square'],
    'color_labels' => ['background' => 'Background', 'surface' => 'Surface', 'text' => 'Text', 'muted' => 'Secondary text',
        'button' => 'Button', 'button_text' => 'Button text', 'border' => 'Border', 'accent' => 'Accent'],
    'validation' => [
        'invalid' => 'Check your page settings and try again.',
        'collection_link' => 'Choose a link that isn’t already in another collection.',
        'collection_source' => 'A creation can appear only once in each collection.',
        'collection_limit' => 'Choose up to :max creations on this page.',
        'content_order' => 'Something went wrong with the page order. Please try again.',
        'creation_unavailable' => 'This creation is no longer available. Choose another public creation.',
        'creation_category' => 'Choose an available creation category.',
        'creation_page' => 'Choose a valid page of creations.',
        'length' => 'Use at most :max characters. Some emoji count as two.', 'boolean' => 'Choose on or off.',
        'integer' => 'Enter a whole number.', 'number' => 'Enter a valid number.', 'url' => 'Enter a valid URL without spaces or login details.',
        'duplicate' => 'Something was duplicated. Please try again.', 'anchor' => 'Choose an existing link, profile or footer.',
        'static' => 'Animated stickers need a static preview image.', 'area' => 'Use an image with no more than 20 megapixels.',
        'image' => 'Upload a valid JPEG, PNG or WebP image.', 'asset' => 'Choose an image uploaded for this page.',
        'storage' => 'Image uploads are unavailable right now. Please try again later.',
        'selection' => 'Please select this sticker again from KLIPY. We couldn’t verify it.',
        'selection_expired' => 'This sticker selection expired. Search for it and select it again.',
    ],
    'js' => [
        'collection_untitled' => 'Untitled collection',
        'collection_added' => 'Collection added.',
        'collection_removed' => 'Collection removed. Your links are still here.',
        'content_moved' => 'Position updated.',
        'creation_removed' => 'Creation removed from this collection.',
        'creations_updated' => 'Collection updated.',
        'link_added' => 'Link added.',
        'saved' => 'Saved! Your page is private.', 'published' => 'Published! Your page will update within one minute.',
        'unpublished' => 'Unpublished! Your page will be hidden within one minute.',
        'draft_saved' => 'Draft saved. Request a review when you are ready.',
        'review_draft_saved' => 'Draft saved. Update your submission to include these changes.',
        'review_requested' => 'Your page has been submitted for review.',
        'review_updated' => 'Your updated page has been submitted for review.',
        'review_withdrawn' => 'Review withdrawn. Your saved edits are still here.',
        'review_message_invalid' => 'Tell us what changed or why we should reconsider, using 10–2,000 characters.',
        'failed' => 'Something went wrong. Your edits are still here. Try again.',
        'conflict' => 'This page was updated somewhere else. Your edits are still here. Reload the saved draft before trying again.',
        'copied' => 'Address copied!', 'copy_failed' => 'Couldn’t copy the address. You can copy it above.',
        'image_uploaded' => 'Image added. Save when you’re ready.',
        'analytics_failed' => 'Insights couldn’t load. Please try again.',
    ],
];
