<?php

return [
    'skins' => 'Skin',
    'avatars' => 'Avatar',
    'editor' => 'Editor',
    'heads' => 'Teste',
    'capes' => 'Mantelli',
    'servers' => 'Server',
    'achievement' => 'Achievement',
    'armor' => 'Supporto per armature',
    'banners' => 'Stendardi',
    'profile' => 'Profilo personale',

    'generators' => 'Generatori',

    'logout' => 'Disconnettiti',
    'register' => 'Registrati',
    'login' => 'Accedi',
    'about' => 'Informazioni',
    'contact' => 'Contattaci',
    'faqs' => 'Domande frequenti',

    'minecraft_name' => 'Nome Minecraft',
    'minecraft_uuid' => 'UUID di Minecraft',
    'what' => 'Cosa',
    'recent_searches' => 'Ricerche recenti',
    'username' => 'Nome Utente',
    'uuid' => 'UUID',
    'search' => 'Cerca',
    'search_placeholder' => 'Prova',
    'search_placeholder_uuid' => 'Inserisci UUID',
    'start_search' => 'Inizia la ricerca',
    'cancel_search' => 'Annulla',
    'search_type' => 'Tipo di ricerca',
    'search_type_all' => 'Tutti i risultati',
    'profiles' => 'Profili',
    'view_skin' => 'Visualizza skin',
    'edit_skin' => 'Modifica skin',
    'make_avatar' => 'Crea avatar',
    'find_heads' => 'Trova teste del giocatore',

    'home' => 'Schermata Home',
    'help' => 'Aiuto',
    'tools' => 'Strumenti',
    'more-tools' => 'Altri strumenti',
    'skin_viewer' => 'Visualizzatore skin',
    'avatar_maker' => 'Creatore Avatar',
    'collections' => 'Collezioni',
    'popular_skins' => 'Skin popolari',
    'cartoon_skins' => 'Skin da cartone animato',
    'animal_skins' => 'Skin di animali',
    'community' => 'Comunità',
    'imprint' => 'Note legali',
    'cookies' => 'Cookie',
    'terms' => 'Termini di servizio',
    'privacy' => 'Politica sulla riservatezza',
    'app' => 'App',
    'mod' => 'Mod',
    'totem' => 'Totem',

    'feedback' => 'Suggerimento',
    'status' => 'Stato',
    'recent_searches_placeholder' => 'Quando inizi la ricerca, le tue ricerche passate appariranno qui.',
    'recent_views_placeholder' => 'Dopo aver visitato alcuni profili, quelli visitati in passato verranno mostrati qui.',
    'moderate' => 'Modera',
    'listings' => 'Inserzioni',
    'add' => 'Aggiungi',

    'theme' => [
        'dark' => 'Scuro',
        'light' => 'Chiaro',
        'auto' => 'Automatico'
    ],
];
