<?php

return [
    'auth' => [
        'login' => [
            'title' => 'Benvenuto su SkinMC',
        ],
        'register' => [
            'title' => 'Registrati su SkinMC',
            'subtitle' => 'Inizia e crea il tuo account per l\'accesso completo.',
        ],
    ],

    'home' => [
        'hero_slogan' => 'Il tuo posto per le skin di Minecraft.',
        'hero_slogan_alt_1' => 'Tutto Minecraft. Un posto.',
        'hero_slogan_alt_2' => 'Dove i Minecrafters si incontrano.',
        'hero_cta' => 'Sorprendimi',
        'hero_explore_cta' => 'Esplora le skin',
        'skin_viewer' => 'Visualizzatore Skin',
        'skin_viewer_detail' => 'Sfoglia le :count skin',
        'skin_editor' => 'Editor di skin',
        'skin_editor_detail' => 'Progetta la tua skin',
        'avatar_maker' => 'Generatore di avatar',
        'avatar_maker_detail' => 'Genera le immagini personalizzate del tuo avatar di Minecraft per il tuo profilo.',
        'trending' => 'Di tendenza',
        'minecraft_skin' => 'Skin di Minecraft',
        'favourite' => 'Preferito',
        'collections' => 'Collezioni',
        'collections_detail' => 'Skin di Minecraft adatte per ogni occasione',
        'about_skinmc' => 'Informazioni su SkinMC',
        'about_find' => 'Trova qualsiasi skin',
        'about_find_detail' => 'Usa la ricerca SkinMC per qualsiasi nome utente di Minecraft per trovare, visualizzare e scaricare la tua prossima skin.',
        'about_download' => 'Scarica o modifica',
        'about_download_detail' => 'Hai trovato una skin che ti piace? Aggiungila ai tuoi preferiti, modificala o scaricala e rendila tua.',
        'about_platform' => 'Cross platform',
        'about_platform_detail' => 'Vuoi prendere la skin al volo? Scansiona il codice QR e salva l\'immagine sul tuo telefono per Minecraft PE.',
        'meta' => [
            'title' => 'Visualizzatore di Skin Minecraft',
            'description' => 'Visualizza e scarica le skin di Minecraft, scopri le migliori skin nelle collezioni curate, controlla la disponibilità del nome utente e la storia e molto altro ancora!',
        ],
        'recently_viewed' => 'Visti di recente',
        'explore_title' => 'Prova qualcosa di nuovo',
        'explore' => 'Esplora nuove idee e strumenti',
        'servers_browse' => 'Cerca server',
        'servers' => 'Scopri i migliori server Minecraft',
        'heads' => 'Teste di Minecraft',
        'head_description' => 'Sfoglia il database delle teste, o creane di nuove.',
        'achievement' => 'Generatore di achievement',
        'achievement_detail' => 'Crea i tuoi achievements personalizzati.',
        'continue' => 'Contina a sfogliare',
    ],
    'profile' => [
        'verified' => 'Profilo verificato',
        'minecraft_profile' => 'Profilo di Minecraft',
        'show_qr_code' => 'Mostra il QR code',
        'favourite' => 'Preferito',
        'user_title' => ':username Skin Minecraft',
        'user_views' => 'Visualizzato :views volta|Visualizzato :views volte',
        'uuid' => 'UUID',
        'copy' => 'Copia',
        'link' => 'Link',
        'skin_history' => 'Cronologia delle Skin Minecraft (:skins)',
        'username_history' => 'Cronologia degli username',
        'username_history_name' => 'Nome',
        'username_history_timestamp' => 'Cambiato il',
        'username_history_initial_name' => 'Nome iniziale',
        'user_downloads' => ':download download|:download download',
        'download_skin' => 'Scarica skin',
        'apply_skin' => 'Applica la skin',
        'capes' => 'Mantelli',
        'claim_profile' => 'Sei :username? Richiedi il tuo profilo per verificarlo e personalizzarlo!',
        'claimed' => 'Profilo recamato',
        'meta_description' => 'Visualizza e scarica :username Minecraft Skin. Vedi la loro UUID, cronologia dei nomi, statistiche dettagliate e altro ancora',
        'created_at' => 'Aggiornato il: :changed_at',
        'skins' => [
            'meta_title' => ':username Cronologia Skin Minecraft',
            'meta_description' => 'Visualizza la cronologia skin Minecraft di :username e le skin precedentemente utilizzate. Utilizza la cronologia per sfogliare skin vecchie o precedentemente usate, eseguire backup e ripristinare o raccogliere nuove skin.',
            'title' => 'Cronologia delle Skin di Minecraft 
',
        ],
        'qr_code' => [
            'meta_title' => 'Codice QR di :username',
            'meta_description' => ':username Profilo Personalizzato Minecraft Codice QR',
        ],
        'sub_nav' => [
            'skin' => 'Skin',
            'about' => 'Informazioni',
            'usernames' => 'Nome utenti',
            'head' => 'Testa',
            'comments' => 'Commenti',
        ],
        'cape' => 'Mantello',
        'elytra' => 'Elytra',
        'nametag' => 'Name tag',
        'animation' => 'Animazione',
        'rotation' => 'Rotazione',
        'none' => 'Nessuno',
        'idle' => 'Inattivo',
        'walk' => 'Camminare',
        'run' => 'Correre',
        'fly' => 'Volare',
        'follow' => 'Segue',
        'following' => 'Following',
        'unfollow' => 'Non seguire più',
        'followers' => 'Follower|Followers',
        'toast' => [
            'following' => 'Ora segui :username!',
            'follow-self-error' => 'Spiacenti :username, non puoi seguirti da solo.',
            'unfollowed' => 'Non segui più :username',
        ],
        'edit' => 'Modifica il profilo',
        'joined' => 'Unito',
        'role' => 'Ruolo',
        'server-fav-list-empty' => 'Sembra che :username non abbia server preferiti al momento. Una volta che :username avrà salvato un server come preferito, lo potrai vedere qui.',
        'server-own-list-empty' => 'Sembra che :username non abbia ancora alcun server. Una volta che :username avrà elencato un server, lo potrai vedere qui.',
        'capes-list-empty' => 'Sembra che :username non indossi ancora nessun mantello. Una volta che :username indosserà un mantello, lo potrai vedere qui.',
        'feed-own-list-empty' => 'Sembra che tu non abbia ancora pubblicato niente nel feed! Una volta che pubblicherai, potrai vedere il tuo post qui.',
        'feed-list-empty' => 'Hmm, sembra che :username non abbia ancora pubblicato nulla nel feed. Una volta che :username pubblicherà qualcosa la potrai vedere qui.',
        'following-own-list-empty' => 'Sembra che tu non stia ancora seguendo nessuno! Una volta che inizi a seguire le persone, puoi vederle qui.',
        'following-list-empty' => 'Hmm, sembra che :username non stia seguendo nessuno. Una volta :username inizierà a seguire le persone, le potrai vedere qui.',
        'followers-own-list-empty' => 'Una volta che le persone iniziano a seguire il tuo profilo, appariranno qui.',
        'followers-list-empty' => 'Hmm, sembra che :username non sia seguito da nessuno. Sii il primo a seguire :username. Una volta che più persone lo seguono, potrai vederle qui.',
        'render' => 'Modalità di rendering',
        '3d' => 'Rendering 3D',
        '2d' => 'render 2D',
        'name-history-info' => 'Cronologia nomi utente sta scomparendo. Mojang ha rimosso il supporto per accedere all\'API della cronologia dei nomi il 13 settembre 2022, con conseguente accurata cronologia dei nomi non è più disponibile. Se si desidera nascondere la cronologia dei nomi, rivendicare il tuo profilo e andare alle impostazioni per renderlo privato.',
        'edit-skins' => 'Modifica cronologia di skin',
        'hide-skin' => 'Nascondi skin',
        'show-skin' => 'Mostra skin',
        'edit-skin' => 'Modifica skin',
        'servers' => [
            'title' => 'i server di :username',
        ],
        'cape-list' => [
            'title' => 'i mantelli di :username',
        ],
    ],
    'skin' => [
        'meta' => [
            'title' => ':username Skin Minecraft',
            'description' => 'Minecraft Skin. Scarica e visualizza la skin, e vedi quali giocatori indossano anche la stessa skin.',
            'tags' => ':username Minecraft Skin, :username Skin, Minecraft Skin, :username Skin di Minecraft Personalizzata, Scarica Skin, Giocatori con la stessa skin',
        ],
        'title' => ':username Skin Minecraft',
        'head' => 'Comandi di testa',
        'head_info' => 'Da usare con blocchi di comando',
        'first_wearing' => 'Primo giocatore visto indossare questa skin:',
        'profiles' => ':profili profilo|:profili profili',
        'profiles_title' => ':profiles profilo con questa skin|:profiles profili con questa skin',
        'screenshot' => 'Cattura schermata',
    ],
    'skins' => [
        'meta' => [
            'title' => 'Pagina :current — Tutte Le Skin Di Minecraft',
            'description' => 'Sfoglia la nostra lista :last page di :total custom Minecraft skin e scarica la tua skin preferita!',
            'tags' => ':username Minecraft Skin, :username Skin, Minecraft Skin, :username Skin di Minecraft Personalizzata, Scarica Skin, Giocatori con la stessa skin',
            'tags-title' => ':tag Skin di Minecraft',
            'tags-description' => 'Sfoglia la nostra lista :last pages di :total :tag skin di Minecraft e scarica la tua :tag preferita!',
            'tags-metatags' => ':tag Skin di Minecraft, :tag Skin, Skin di Minecraft, :tag Skin personalizzata Minecraft, Scarica :tag Skin, Minecraft :tag Skins',
        ],
        'title-skin-tags' => 'Skin di Minecraft etichettate',
        'subtitle' => 'Pagina :current di :last per :total Minecraft Skin',
        'subtitle-skin-tags' => 'Pagina :current di :last per :total skin di Minecraft etichettate',
        'sort_by' => 'Ordinato per',
        'latest' => 'Ultime skin',
        'most_profiles' => 'Skin più usate',
        'profiles_today' => 'Le più usate oggi',
        'profiles_this_week' => 'Più usate questa settimana',
        'profiles_this_month' => 'Più usate questo mese',
        'default' => 'Ordinamento predefinito',
        'this_month' => 'Aggiunta questo mese',
        'this_week' => 'Aggiunta questa settimana',
        'today' => 'Aggiunta oggi',
        'random' => 'Casuale',
        'similar' => 'Skin simili',
        'no_similar_skins' => 'Nessuna skin simile trovata.',
        'favorite' => ':count preferito|:count preferiti',
    ],
    'skin-tags' => [
        'faq' => 'Cosa sono i tag?',
        'about' => 'I tag sono un modo per aggiungere categorie rilevanti alle skin. L\'aggiunta di tag ti permette di scoprire più skin che ti piacciono facilmente!',
        'guidelines' => [
            'good' => [
                'title' => 'Le linee guida generali per ottimi tag sono:',
                'short' => 'Corto',
                'descriptive' => 'Descrittivo',
                'spelled' => 'Ortografia corretta',
            ],
            'bad' => [
                'title' => 'Non aggiungere tag come:',
                'general' => 'Troppo generico',
                'specific' => 'Troppo specifico',
                'too-many-tags' => 'Dovrebbero essere tre tag separati',
                'spelling' => 'Dovrebbe essere :example',
            ],
        ],
        'toast' => [
            'added' => 'Il tag ”:tag” aggiunto per la votazione',
            'removed' => 'Il tag ”:tag” è stato rimosso',
            'upvote' => 'Hai votato positivamente per ":tag"',
            'downvote' => 'Hai votato negativamente per ":tag"',
        ],
        'vote' => [
            'up' => 'Voto positivo',
            'down' => 'Voto negativo',
            'remove' => 'Rimuovi voto',
        ],
    ],
    'contact' => [
        'contact' => 'Contatta',
        'email' => 'Non esitate a scriverci a <a href="mailto:support@skinmc.net">support@skinmc.net</a> per tutte le domande che hai.',
        'faq' => 'Chiediamo gentilmente di consultare prima la pagina <a href=":link">FAQ</a> se la tua domanda è già stata risolta.',
        'other' => 'Più modi per conneterti',
        'other_discord' => 'Unisciti al server Discord e connettiti con altri, chiacchiera su giochi, condividi i tuoi pacchetti preferiti e ottieni aiuto dalla comunità.',
        'other_twitter' => 'Segui su Twitter per vedere quando viene rilasciato un nuovo aggiornamento o una nuova funzionalità, vedi le skin della settimana e altro ancora.',
        'other_instagram' => 'Segui SkinMC su Instagram per sfogliare e scoprire nuove e interessanti Skin Minecraft e immagini.',
        'other_facebook' => 'Diventa un fan su Facebook e vedi tutti i post in cui è possibile commentare e parlare con altri durante l\'esplorazione dei contenuti di Minecraft.',
    ],
    'about' => [
        'intro' => '<span>La tua</span> <span>piattaforma</span> <span>per</span> <span>Minecraft</span> <span>Skins.</span>',
        'header_credit' => 'Illustrazione "Epica Nether Battle" da',
        'info' => 'Tieni traccia di tutto.',
        'info_explainer' => 'Visualizza la cronologia dei nomi di un giocatore, vedi le loro skin precedenti, aggiungili come amico, scarica skin e anche ottieni statistiche dei dettagli.',
        'card_find_title' => 'Trova qualsiasi minecrafter',
        'card_find_detail' => 'Inizia cercando qualsiasi nome utente del giocatore o UUID di tua scelta.',
        'card_view_title' => 'Visualizza, salva e modifica',
        'card_view_detail' => 'Trovato un skin che ti piace? Salvala scaricandola o utilizza l\'editor per renderla tua.',
        'card_claim_title' => 'Ottieni la verifica',
        'card_claim_detail' => 'Collega il tuo account Minecraft e rivendica il tuo profilo per sbloccare nuove funzionalità!',
        'card_customise_title' => 'Personalizza il tuo profilo',
        'card_customise_detail' => 'I giocatori verificati possono aggiungere i loro link ai social media e rendere il loro profilo proprio.',
        'card_friends_title' => 'Aggiungi i tuoi amici',
        'card_friends_detail' => 'Connettiti con i tuoi amici su SkinMC e mostra la lista dei tuoi amici sul profilo.',
        'card_history_title' => 'Nome utente e cronologia skin',
        'card_history_detail' => 'Usa la ricerca avanzata per trovare e vedere la cronologia username/skin di un giocatore.',
        'founders' => 'I fondatori',
        'founders_cofounder' => 'Cofounder di SkinMC',
        'head_of_design' => 'Responsabile del design',
        'head_of_code' => 'Capo del codice',
        'feedback' => 'Inviaci un feedback',
        'faq' => 'Domande su Minecraft, Skins e altro ancora? Leggi la nostra pagina FAQ con tutte le risposte alle domande più frequenti/',
        'faq_link' => 'Visita la pagina FAQ',
        'contact' => 'Volete contattarci o avete altre domande? Contattateci direttamente.',
        'contact_link' => 'Contattaci',

    ],
    'faq' => [
        'title' => 'FAQ',
        'subtitle' => 'Domande frequenti',
        'help' => 'Hai bisogno di aiuto?',
        'discord' => 'Unisciti al server Discord per chattare con altri giocatori di Minecraft.',
        'contact' => 'Contattaci',
        'q' => [
            'change_skin_t' => 'Come faccio a cambiare la mia skin di Minecraft?',
            'change_skin' => '
                <p>Per cambiare la tua Skin fai quanto segue:</p>
                <ol>
                    <li>Visita <a href="https://minecraft.net/it-it/login/">https://minecraft.net/it-it/login/</a> e accedi con il tuo account Microsoft.</li><li>Una volta effettuato l\'accesso, seleziona <b>"Skin"</b> sul menu a sinistra.</li><li>Poi, scegli un modello che preferisci e carica una Skin di tuo gradimento.</li>
                </ol>',
            'change_username_t' => 'Come faccio a cambiare il mio nome utente di Minecraft?',
            'change_username' => '
                <p>Per cambiare il tuo nome utente fai quanto segue:</p>
                <ol>
                    <li>Visita <a href="https://minecraft.net/it-it/login" target="_blank" rel="nofollow">https://minecraft.net/it-it/login</a> e accedi con il tuo account Microsoft.</li>
                    <li>Trova il tuo nome del profilo di Minecraft e premi il pulsante <b>"(Cambiare)"</b></li>
                    <li>Nella pagina successiva, inserisci il nuovo nome utente desiderato.</li>
                    <li>Infine, confermare le modifiche inserendo la password e premendo "Cambia nome".</li>
                </ol>',
            'dl_t' => 'Come faccio a scaricare la skin Minecraft di qualcuno?',
            'dl' => '
                <p>Per scaricare la skin Minecraft di chiunque effettua le seguenti operazioni:</p>
                <ol>
                    <li>Premi sulla barra di ricerca e inserisci il nome utente del giocatore da cui vuoi scaricare la skin.</li>
                    <li>Nella pagina del profilo puoi vedere in anteprima la skin</li>
                    <li>Clicca sul pulsante <strong>Scarica Skin</strong> sotto l\'anteprima</li>
                </ol>',
            'submit_q' => 'Come si invia una skin a una collezione?
',
            'submit_a' => '<pSi prega di compilare il seguente breve modulo con i nomi utente e la categoria di appartenenza che si desidera aggiungere alle collezioni. <a href="https://forms.gle/f4Jh5RpGfsHAZ5xE8" target="_blank">Modulo di presentazione della collezione</a>',
            'mcpe_t' => 'Posso usare la Skin su Minecraft PE?',
            'mcpe' => '
                <p>Sì. Per utilizzare la Skin in Minecraft Pocket Edition procedere come segue:</p>
                <ol>
                    <li>Apri SkinMC.net sul tuo cellulare e clicca sulla barra di ricerca</li>
                    <li>Inserisci il nome utente che possiede la skin che vorresti scaricare</li>
                    <li>Clicca il pulsante <strong>Download Skin</strong> sotto l\'anteprima </li>
                    <li>Apri Minecraft PE e clicca su <strong>Profilo</strong> nella zona a destra</li>
                    <li>Clicca sul <strong>+</strong>, o modifica il carattere e vai alla "scheda skin classiche"</li>
                    <li>Tocca "possedute", poi "importare", poi "scegli una nuova skin"</li>
                </ol>',
            'change_times_t' => 'Quanto spesso posso cambiare il mio nome utente?',
            'change_times' => '<p>Puoi cambiare il tuo nome utente di Minecraft <strong>una volta</strong> ogni <strong>30 giorni</strong>.</p>',
            'available_t' => 'Dopo aver cambiato il mio nome utente, quando diventa disponibile per gli altri per rivendicarlo?',
            'available' => '<p>Se vuoi tornare al tuo nome utente precedente, puoi tornare indietro <strong>dopo 30 giorni.</strong> Tutti gli altri devono aspettare un ulteriore <strong>7 giorni</strong> (37 giorni dopo il cambiamento) prima che possano reclamare il tuo vecchio nome utente. </p>',
            'username_history_t' => 'Riesci a rimuovere la cronologia dei miei username, per favore?',
            'username_history' => '
                <p>Poiché i dati della cronologia dei nomi utente provengono da Mojang, la cronologia del nome utente non può essere rimossa. Mojang ha precedentemente dichiarato che la loro intenzione era che i nomi utente precedenti possono essere visti, e forniscono al pubblico un metodo diretto per accedere a tali informazioni².</p>
                                <p class="font-14 mb-0">2<a href="https://twitter.com/dinnerbone/status/554739042529849345" target="_blank" rel="noreferrer">https://twitter. om/dinnerbone/status/554739042529849345</a> (Tweet archived 2 years fa: <a href="http://archive.is/TeAyj" target="_blank" rel="noreferrer">http://archive. s/TeAyj</a>)
                </p>',
        ],
    ],
    'avatars' => [
        'start' => [
            'title' => 'Crea il tuo avatar di Minecraft',
            'subtitle' => 'Usa il generatore avatar di Minecraft per creare un divertente avatar da qualsiasi skin!',
            'avatar_face' => 'Stile avatar: Volto',
            'avatar_bust' => 'Stile avatar: Busto',
            'avatar_cube' => 'Stile avatar: Cubo',
            'avatar_head3d' => 'Testa 3D personalizzata',
        ],
        'user' => [
            'title' => 'Scegli skin',
            'subtitle' => 'Inserisci il nome utente di Minecraft per l\'avatar che vuoi generare',
            'form_label' => 'Nome utente di Minecraft',
            'form_submit' => 'Continua',
        ],
        'output' => [
            'title' => 'Anteprima e salvataggio',
            'subtitle' => 'Goditi usando il tuo nuovo avatar di Minecraft',
            'download_info' => 'Felice con il risultato? Inizia a usare il tuo nuovo avatar scaricandolo qui',
            'download_button' => 'Scarica avatar',
            'avatar_style' => 'Stile avatar',
            'skin_username' => 'Nome utente skin',
            'change' => 'Cambia',
            'generate' => 'Genera',
            'avatar_colour' => 'Colore di sfondo',
            'avatar_colour_palette' => 'Palette',
            'avatar_colour_basic' => 'Base',
        ],
        'meta' => [
            'title' => 'Generatore Avatar Di Minecraft',
            'description' => 'Minecraft Avatar Maker: crea immagini personalizzate del profilo Minecraft utilizzando la tua skin di Minecraft',
        ],
    ],
    'totem' => [
        'title' => 'Totem Minecraft Personalizzato',
        'subtitle' => 'Usa il generatore di Totem per Minecraft per creare un pacchetto di risorse personalizzato con un Totem dell\'Immortalità da qualsiasi skin.',
        'download_info' => 'Felice con l\'anteprima? Scegli la tua versione di Minecraft per salvare il tuo pacchetto di risorse personalizzato:',
        'meta' => [
            'title' => 'Generatore Di Totem Personalizzato per Minecraft',
            'description' => 'Totem di Minecraft personalizzati: genera e crea un pacchetto di risorse di Minecraft personalizzato con un Totem dell\'Immortalità usando la tua o la skin di qualsiasi altro giocatore di Minecraft.',
        ],
        'type' => [
            'mini' => 'Una mini versione della tua skin!',
            'full' => 'Una versione completa della tua skin!',
            'model3d' => 'Un modello 3d della tua skin!',
            'add_designs' => 'Vuoi vedere più design? Invia il tuo suggerimento di design qui:',
        ],
    ],
    'achievement' => [
        'header' => [
            'title' => 'Crea il tuo achievement di Minecraft',
            'subtitle' => 'Usa il Generatore di Successi di Minecraft per creare il tuo risultato personalizzato e utilizzare mostrare i tuoi achievements in qualsiasi cosa ti piace!',
        ],
        'generator' => [
            'yellow_text' => 'Testo giallo',
            'white_text' => 'Testo bianco',
            'choose_icon' => 'Scegli icona',
            'face' => 'Volto su Minecraft invece dell\'icona',
            'form_submit' => 'Scarica',
            'form_label' => 'Nome utente di Minecraft',
            'download' => 'Scarica',
            'embed' => 'Incorpora',
            'embed_copy' => 'Copia',
        ],
        'meta' => [
            'title' => 'Generatore Di Achievement Minecraft',
            'description' => 'Genera achievement e progressi personalizzati di Minecraft con il creatore di Achievement. Scarica l\'immagine direttamente, usala nelle firme del forum, incorporata con codice HTML o BB e altro',
        ],
    ],
    'armor' => [
        'header' => [
            'title' => 'Creatore di supporti per armatura di Minecraft',
            'subtitle' => 'Genera e crea i tuoi supporti per armatura di Minecraft personalizzati. Crea pose, posizioni, posiziona oggetti diversi e molto altro.',
        ],
        'meta' => [
            'title' => 'Creatore di supporti per armatura di Minecraft',
            'description' => 'Genera e crea facilmente supporti per armatura di Minecraft personalizzati. L\'editor ti aiuta a creare pose, posizioni, posiziona oggetti, skin personalizzate e molto altro.',
        ],
    ],
    'banner' => [
        'editor' => [
            'header' => [
                'title' => 'Editor Stendardi di Minecraft',
                'subtitle' => 'Progetta e crea i tuoi stendardi di Minecraft personalizzati. Possono essere utilizzati per decorare il tuo mondo o anche essere utilizzati come mantelli <a href="https://optifine.net" target="_blank" rel="nofollow">Optifine</a>.',
            ],
            'meta' => [
                'title' => 'Creatore Stendardi di Minecraft',
                'description' => 'Crea e progetta i tuoi stili di stendardi di Minecraft personalizzati con tutti i modelli e colori del gioco! Possono essere utilizzati per decorare il tuo mondo o essere indossati come un Mantello Optifine utilizzando lo Stendardo Mantello. È possibile generare codici per stendardi o scudi.',
            ],
        ],
        'gallery' => [
            'header' => [
                'title' => 'Galleria di Stendardi di Minecraft',
                'subtitle' => 'Sfoglia la galleria di :count Stendardi di Minecraft su misura. Puoi usare uno Stendardo come mantello per rendere la tua skin di Minecraft più unica, o usa uno Stendardo come bandiera per decorare il tuo mondo.',
            ],
            'meta' => [
                'title' => 'Galleria di Stendardi di Minecraft',
                'description' => 'Sfoglia la galleria di :count Stendardi di Minecraft su misura. Puoi usare uno Stendardo come mantello per rendere la tua skin di Minecraft più unica, o usa uno Stendardo come bandiera per decorare il tuo mondo.',
            ],
        ],
    ],
    'search' => [
        'meta' => [
            'title' => 'Risultati di ricerca: :search',
        ],
        'title' => 'Risultati della ricerca',
        'results' => 'Pagina :current per :count risultato|Pagina :current di circa :count risultati ',
        'time' => '(:tempo secondi)',
        'username_available' => 'Nome utente disponibile*',
        'username_unavailable' => 'Nome utente non disponibile',
        'username_status' => 'Stato',
        'username_status_available' => 'Disponibile*',
        'username_status_unavailable' => 'Non disponibile',
        'username_searches' => 'Ricerche',
        'username_searches_count' => ':count / giorno',
        'username_available_disclaimer' => '*A meno che il nome non sia temporaneamente o permanentemente vietato da Mojang.',
        'no_results' => 'Nessun profilo trovato. Prova a cercare con l\'UUID cambiando il tipo di ricerca.',
        'no_results_tags' => 'Nessuna skin registrata trovata. Prova a cercare altri tag come "blue", "girl", "fox", ecc...',
        'again' => 'Cerca di nuovo',
        'sorry' => 'Sssssssscusa...',
        'view_profile' => 'Visualizza profilo',
    ],
    'collection' => [
        'title' => 'Collezione skin di Minecraft',
        'subtitle' => 'Sfoglia la nostra collezione curata di skin Minecraft.',
        'filters' => 'Filtri',
        'title_trending' => 'Tendenze',
        'title_all' => 'Tutte Le Skin Di Minecraft',
        'skin_tags' => 'Skin registrate',
        'filters_skin_type' => 'Tipo di skin',
        'filter_skin_type_steve' => 'Tipo di steve',
        'filter_skin_type_alex' => 'Tipo di Alex',
        'cancel' => 'Annulla',
        'apply' => 'Applica',
        'username_minecraft_skin' => 'skin Minecraft di :username',
        'user_downloads' => '<span class="fw-500">:downloads</span> download|<span class="fw-500">:downloads</span> download',
    ],
    'favourites' => [
        'title' => 'Preferiti',
        'subtitle' => 'Visualizza e gestisci le skin che hai salvato in seguito nella tua lista dei preferiti',
        'sort' => 'Ordina per',
        'toast' => [
            'added' => 'Aggiunto alla tua lista preferiti',
            'removed' => 'Rimosso dalla tua lista preferiti',
        ],
        'skins' => [
            'button' => 'Skin',
            'empty_headline' => 'Ancora nessuna skin preferita',
            'empty_subtitle' => 'Non hai ancora nessuna skin salvata nella tua lista preferiti. Visita la pagina del server e scopri la tua prossima preferita!',
            'empty_browse' => 'Sfoglia le skin',
            'meta' => [
                'title' => 'Le mie Skin preferite',
                'description' => 'Skin preferite di Minecraft salvate ',
            ],
        ],
        'servers' => [
            'button' => 'Server',
            'empty_headline' => 'Ancora nessun server preferito',
            'empty_subtitle' => 'Non hai ancora nessuna skin salvata nella tua lista preferiti. Visita la pagina del server e scopri la tua prossima preferita!',
            'empty_browse' => 'Sfoglia server',
            'meta' => [
                'title' => 'Server preferiti',
                'description' => 'Server Minecraft preferiti',
            ],
        ],

    ],
    'cape' => [
        'editor' => [
            'title' => 'Editor Mantelli di Minecraft',
            'subtitle' => 'Usa l\'editor di Mantelli di Minecraft per creare il tuo mantello personalizzato.',
            'meta' => [
                'title' => 'Editor Mantelli di Minecraft',
                'description' => 'Usa l\'editor di Mantelli di Minecraft per creare il tuo mantello personalizzato.',
            ],
        ],
        'list' => [
            'title' => 'Mantelli di Minecraft',
            'subtitle' => 'Mantelli ufficiali di Minecraft. I mantelli sono oggetti commemorativi e vengono indossati come aggiunta alla skin del giocatore. Possono anche cambiare l\'aspetto quando viene indossato un elytra.',
            'meta' => [
                'title' => 'Lista Mantelli di Minecraft',
                'description' => 'Lista di Mantelli di Minecraft: Vedi tutti i mantelli ufficiali di Minecraft tra cui Mojang, Minecon, Personali, Speciali e sciccosi.',
            ],
        ],
        'detail' => [
            'title' => 'Mantello :cape',
            'info' => 'Informazioni sul mantello',
            'profile_list' => 'Profili con questo mantello',
            'profiles' => ':profili profilo|:profili profili',
            'meta' => [
                'title' => 'Mantello di Minecraft :cape',
                'description' => 'Scopri il Mantello Minecraft :cape e guarda i giocatori che lo indossano!',
            ],
        ],
        'list-custom' => [
            'title' => 'Mantelli di Minecraft personalizzati',
            'description' => 'Sfoglia e visualizza i mantelli personalizzati che sono stati creati e utilizzati dai membri di SkinMC.',
        ],
    ],
    'servers' => [
        'title' => 'Server di Minecraft',
        'subtitle' => 'Cerca ed esplora i server di minecraft',
        'all' => 'Tutti i server',
        'manage_your_servers' => 'Gestisci i tuoi server',
        'add_new_server' => 'Aggiungi un nuovo server',
        'filters' => [
            'trending' => 'Tendenze',
            'updated' => 'Aggiornato',
            'new' => 'Nuovo',
            'most_viewed' => 'Più visti',
            'top_voted' => 'Piu votati',
            'sorting' => 'Ordina',
            'sort_by_latest' => 'Ordina per ultimo',
            'sort_by_oldest' => 'Ordina dal più vecchio',
            'categories' => 'Categorie',
            'server_location' => 'Posizione del server',
            'show_results' => 'Visualizza i risultati',
            'show_more' => 'Mostra di più',
            'show_less' => 'Mostra di meno',
            'clear_filters' => 'Cancella i filtri',
            'reviews' => 'Recensioni',
            'sort_by_highest_rating' => 'Ordina per voto più alto',
            'sort_by_lowest_rating' => 'Ordina per voto più basso',
            'bedrock_and_java_support' => 'Supporto Bedrock e Java',
        ],
        'review-count' => ':count Recensione|:count Recensioni',
        'meta' => [
            'title' => 'Lista Server Minecraft',
            'description' => 'Sfoglia ed esplora l\'elenco dei server di Minecraft per trovare il miglior server di Minecraft! Filtra per l\'ultimo, più popolare e molto altro',
        ],
        'reviews' => [
            'meta' => [
                'title' => 'Scrivi una recensione',
            ],
            'editing' => 'Stai modificando la tua recensione da :date. Vuoi eliminare la tua recensione?',
            'welcome' => 'Ciao :username. Come è stata la tua esperienza complessiva con :servername?',
            'subtitle' => 'Lascia un punteggio complessivo della tua esperienza passata col server.',
            'scale' => [
                'great' => 'Ottimo',
                'good' => 'Buono',
                'okay' => 'Ok',
                'meh' => 'Così così',
                'bad' => 'Brutto',
            ],
            'rate-experience' => 'Successivamente, valuta la tua esperienza in queste sezioni',
            'overall' => 'Complessivo',
            'server-team' => 'Squadra del server',
            'community' => 'Comunità',
            'experience' => 'Esperienza',
            'availablility' => 'Orari e disponibilità',
            'shop' => 'Negozio',
            'write-review-title' => 'Scrivi una recensione',
            'write-review-subtitle' => 'Lascia qualche appunto, puoi evidenziare ciò che ti è piaciuto, ciò che ha reso speciale la tua esperienza, od offrire alcuni suggerimenti.',
            'write-review-helper' => 'Scrivi una recensione del server per condividere la tua esperienza con nuovi giocatori e aiutare i proprietari del server con dei suggerimenti.',
            'write-review-tips' => 'Ecco alcuni consigli',
            'submit-title' => 'Pronto per inviare la tua recensione?',
            'submit-subtitle' => 'Quasi finito!',
            'submit-review' => 'Invia la mia recensione',
            'back' => 'Indietro',
            'continue' => 'Continua',
            'delete-title' => 'Sei sicuro di voler eliminare la tua recensione?',
            'tos-checkbox-part-1' => 'Inviando questo modulo accetti i Termini di Servizio, l\'Informativa sulla Privacy e le Linee Guida della Community di SkinMC. Confermi anche che tutte le informazioni sono esatte, e seguono i',
            'tos-checkbox-part-2' => 'le linee guida.',
            'tos-checkbox-part-3' => 'La tua recensione sarà pubblicata dopo l\'invio, ma può essere soggetta a revisione.',
        ],
        'slots' => 'Slot',
        'empty-helper' => 'Puoi provare a fare un\'altra ricerca o',
        'empty' => 'Mhh sembra non esserci ancora nulla qui.',
        'verified' => 'Verificato',
        'review_translate_show_original' => 'Mostra originale',
        'review_translate' => 'Traduci la recensione',
        'description_translate' => 'Traduci descrizione',
        'create' => [
            'welcome' => 'Benvenuto/a',
            'basics' => 'Nozioni di base',
            'categories' => 'Categorie',
            'social_links' => 'Link social',
            'trailer_video' => 'Video Trailer',
            'images' => 'Immagini',
            'images_description' => 'Puoi caricare le foto in seguito, per mostrare ciò che il tuo server offre.',
            'submit' => 'Invia',
            'lets_get_your_server_added' => 'Aggiungiamo il tuo server.',
            'basics-subtitle' => 'Fai sapere alle persone di cosa tratta il tuo server.',
            'description' => 'Descrizione',
            'description_tips' => 'Ecco alcuni suggerimenti',
            'description_hint' => 'Scrivi una buona descrizione per il tuo server per attirare nuovi giocatori.',
            'categories-subtitle' => 'Scegli alcune categorie per il tuo server',
            'missing-category' => 'Manca una categoria?',
            'social_links_description' => 'Dove possono i giocatori connettersi al server sui social media?',
            'trailer_video_description' => 'Mostra il tuo server con un video di YouTube.',
            'trailer_video_hint' => 'Incolla l\'URL o l\'ID del video:',
            'ready_to_submit_your_server' => 'Pronto per creare il server?',
            'review-hint' => 'Dopo l\'invio esamineremo attentamente la tua richiesta di elenco del server. Successivamente, il tuo server sarà pubblicato, o ti richiederemo delle modifiche per consentirlo.',
            'terms' => [
                'part-1' => 'Inviando questo modulo accetti i Termini di Servizio, l\'Informativa sulla Privacy e le Linee Guida della Community di SkinMC. Confermi anche che tutte le informazioni sono esatte, e hai correttamente seguito i',
                'part-2' => 'requisiti del server per la configurazione',
                'part-3' => ', e che il server di Minecraft è posseduto e gestito dall\'entità che stai rappresentando.',
            ],
            'submit-application' => 'Invia domanda',
            'video-id-helper' => [
                'part-1' => 'L\'ID video è la stringa di numeri e lettere dopo',
                'part-2' => 'Ad esempio se il tuo Url video è',
                'part-3' => ', quindi il tuo ID video sarebbe',
            ],
            'welcome_description' => 'In questo passaggio, inizieremo ad aggiungere il tuo server. Parlarcene un po\', scrivi una descrizione, e nella fase successiva potrai caricare alcune immagini.',
        ],
        'copy_server_ip' => 'Copia l\'IP del server',
        'all_minecraft_servers' => 'Tutti i Server Minecraft',
        'promo' => [
            'title' => 'Ospiti un server di Minecraft?',
            'ready_to_list_your_server' => 'Pronto a far apparire il tuo Server nella lista?',
            'everything_you_need' => 'Tutto ciò che ti serve per far crescere il tuo server',
            'list_your_server' => 'Immetti il tuo server nella lista',
            'list_your_server_description' => 'Crea una lista per il tuo server, aggiungi foto, social media e altro ancora.',
            'find_players' => 'Trova giocatori',
            'find_players_description' => 'Trova nuovi giocatori che si uniscano al tuo server per far crescere la tua comunità.',
            'get_reviews' => 'Ottieni recensioni',
            'get_reviews_description' => 'Chiedi alla tua comunità di valutare il tuo server e ricompensali nel gioco.',
            'why_list_on_skinmc' => 'Perché dovresti listare il tuo server su SkinMC',
            'others' => 'Altri',
            'quality_check_and_confirmation' => 'Controllo qualità e conferma',
            'quality_check_description' => 'La nostra squadra esamina ogni server per garantirne la qualità.',
            'verified_players' => 'Recensioni da giocatori di Minecraft verificati',
            'verified_players_description' => 'Raccogli le recensioni dei giocatori da account legittimi con integrazione Votifer.',
            'international' => 'Internazionale',
            'international_description' => 'Con le funzioni di traduzione il tuo annuncio è disponibile per un\'ampia fascia di giocatori.',
            'server_listing_page' => 'Lista server migliori',
            'server_listing_page_description' => 'Aggiungi foto, descrizione, video su youtube e metti in primo piano il perché i giocatori dovrebbero unirsi al tuo server.',
            'social_connections' => 'Collegamenti ai social media',
            'social_connections_description' => 'Collega i tuoi account social ai server e mostra ai nuovi giocatori dove possono trovarti.',
            'verified_badge' => 'Badge di verifica',
            'verified_badge_description' => 'I server autentici possono richiedere un badge di verifica.',
            'owner_profile' => 'Profilo del proprietario',
            'owner_profile_description' => 'Aggiungi un tocco personale, completando il tuo profilo personalizzato.',
            'categories' => 'Categorie',
            'categories_description' => 'Categorie diverse per facilitare la ricerca del tuo server.',
            'vote' => 'Vota',
            'vote_description' => 'Chiedi agli utenti di votare per il tuo server.',
            'fair_listings' => 'Inserzioni eque',
            'fair_listings_description' => 'Le inserzioni dei server non possono essere potenziate artificialmente nei risultati su SkinMC.',
            'support' => 'Supporto 24h',
            'support_description' => 'Hai bisogno di aiuto o hai domande? Puoi sempre contattarci e ricevere una risposta in tempi brevi.',
            'custom_features' => 'Funzionalità personalizzate',
            'custom_features_description' => 'Manca una funzionalità per il tuo server? Apri una richiesta, e la implementeremo.',
            'faq' => [
                'title' => 'Risposte alle tue domande',
                'suited-question' => 'Il mio server di Minecraft è adatto per SkinMC?',
                'suited-answer' => 'I giocatori di Minecraft su SkinMC amano scoprire nuove esperienze, contenuti e interagire con le comunità. Sulla piattaforma troverete una grande varietà di diversi server di Minecraft, unici e divertenti. Da un grande impero a un piccolo server in sopravvivenza, troverai quello che fa al caso tuo!',
                'get-started-question' => 'Come posso iniziare?',
                'get-started-answer' => 'Aggiungere il tuo server Minecraft all\'elenco dei server SkinMC è molto facile! Dovrai prima creare un account, se non lo hai già fatto, e poi seguire la guida di configurazione per poter aggiungere il tuo server. Aggiungi alcune foto e una bella descrizione, e il tuo server sarà pubblicato in pochissimo tempo!',
                'players-question' => 'Come posso ottenere più giocatori sul mio server Minecraft?',
                'players-answer' => 'Costruire una comunità è la parte più cruciale di un server Minecraft di lunga durata. Usa la lista dei server di Minecraft su SkinMC per trovare un nuovo pubblico e continuare a sviluppare la tua comunità. Chiedi ai tuoi giocatori di consigliare il tuo Server, o di condividere il tuo annuncio su piattaforme di social media. Raccogliere buone recensioni può anche svolgere un ruolo decisivo, garantendoti una grande presenza di nell\'elenco dei Server e attirando nuovi giocatori.',
                'more-question' => 'Ho altre domande. Dove posso ottenere aiuto?',
                'more-answer' => 'È possibile contattare SkinMC in qualsiasi momento, 24/24, utilizzando il pulsante di aiuto, la pagina di assistenza o entrando nel nostro server Discord.',
            ],
            'ready_to_list_description' => 'Aggiungi il tuo server di Minecraft all\'elenco dei server SkinMC in pochi minuti. Se hai bisogno di aiuto, è possibile contattarci 24 ore su 24 e ricevere risposte il prima possibile.',
        ],
        'manage' => [
            'index' => [
                'welcome' => 'Bentornato, :username',
                'your_servers' => 'I tuoi server',
                'reviews_today' => 'Recensioni oggi',
                'no_reviews_today' => 'Nessuna recensione oggi',
                'no_reviews_text' => 'I tuoi server non hanno ricevuto alcuna recensione oggi. Perché non chiedi ai tuoi utenti di lasciarne una?',
                'tips' => [
                    'title' => 'Suggerimenti',
                    'description-title' => 'Scrivi una buona descrizione del server',
                    'description-body' => 'Consigli utili e spunti per scrivere un\'ammirabile descrizione del server.',
                    'images-title' => 'Aggiunta d\'immagini del server',
                    'images-body' => 'Fai spiccare il tuo elenco server con magnifiche immagini.',
                ],
            ],
            'listings' => [
                'title' => 'I tuoi server di Minecraft (:count)',
            ],
            'insights' => [
                'title' => 'Dettagli',
            ],
            'edit_server' => 'Modifica server',
            'listing' => 'Elenchi',
            'to_do' => 'Da fare',
            'last_update' => 'Ultimo aggiornamento',
            'add_more_photos_to_publish' => 'Aggiungi altre foto per pubblicare',
            'looks_empty_here' => 'Sembra che non ci sia nulla qui.',
            'get_started_by_adding_a_new_server' => 'Iniziare con l\'aggiunta di un nuovo server?',
        ],
        'status' => [
            'approved' => 'Approvato',
            'pending_approval' => 'In attesa di approvazione',
            'published' => 'Pubblicato',
            'in_review' => 'In revisione',
        ],
    ],
    'editor' => [
        'import' => [
            'title' => 'Importa Skin',
            'import_by_username' => 'Importa per nome utente',
            'import_button' => 'Importa',
            'drag' => 'Trascina e rilascia qui un tema, o fai clic',
            'click' => 'Seleziona un\'immagine',
        ],
        'download' => [
            'error' => [
                'no-data' => 'Non è stato provveduto nessun dato per la skin. Per favore riprova.',
                'invalid-format' => 'Il formato dati della skin non è valido. Per favore riprova.',
                'invalid-data' => 'I dati della skin sono corrotti. Per favore riprova.',
                'generic' => 'Qualcosa è andato storto durante il download della tua skin. Per favore riprova.',
            ],
        ],
        'draw' => 'Disegno',
        'eyedropper' => 'Contagocce',
        'fill' => 'Riempi',
        'move' => 'Muovi',
        'decrease_brightness' => 'Riduci luminosità',
        'increase_brightness' => 'Aumenta luminosità',
        'erase' => 'Cancella',
        'undo' => 'Torna indietro (CTRL+Z)',
        'redo' => 'Vai avanti (CTRL+Y)',
        'default_view' => 'Vista predefinita',
        'zoom_in' => 'Aumenta lo zoom (CTRL +)',
        'zoom_out' => 'Riduci lo zoom (CTRL -)',
        'saved' => 'Ultimo salvataggio appena salvato',
        'saving' => 'Salvataggio automatico...',
        'save_error' => 'Si è verificato un errore',
        'new_skin' => 'Nuova skin',
        'previous_skins' => 'Skin precedenti',
        'backed_up_title' => 'Skin salvate automaticamente',
        'backed_up_info' => 'Salvataggio temporaneo nella memoria locale.',
        'backed_up_empty_title' => 'Sembra che non ci sia nulla qui',
        'backed_up_empty_info' => 'Una volta che inizierai a modificare le skin vedrai qui le tue 32 ultime skin modificate.',
        'backed_up_skins_count' => 'di 32 backup di skin utilizzati',
        'backed_up_skins_count_info' => 'È possibile eseguire il backup fino a 32 skin. Una volta raggiunto questo limite una skin più vecchia verrà sostituita con una nuova.',
        'layers' => 'Livelli',
        'body' => [
            'title' => 'Corpo',
            'overlay' => 'Copertura',
            'head' => 'Testa',
            'torso' => 'Busto',
            'l_arm' => 'Braccio sinistro',
            'r_arm' => 'Braccio destro',
            'l_leg' => 'Gamma sinistra',
            'r_leg' => 'gamba destra',
        ],
        'model' => 'Modello',
        'steve' => 'Steve',
        'alex' => 'Alex',
        'stance' => [
            'title' => 'Posizione',
            'default' => 'Predefinito',
            'walk' => 'Camminare',
            'run' => 'Correre',
            'hug' => 'T-pose',
            'fly' => 'Volare',
        ],
        'fullscreen' => 'Schermo intero',
        'fullscreen_exit' => 'Esci da schermo intero',
        'grid' => 'Griglia',
        'show_grid' => 'Mostra griglia',
        'download' => [
            'title' => 'Salva E Scarica',
            'subtitle' => 'Account SkinMC',
            'description' => 'Vuoi creare un account SkinMC gratuito per salvare la tua pelle e quelli futuri sulla nuvola?',
            'start_description' => 'Avvia il download direttamente senza salvare sul cloud',
            'start' => 'Scarica skin',
        ],
        'help' => [
            'title' => 'Editor skin di Minecraft',
            'about' => 'Crea e modifica facilmente la tua skin di Minecraft personalizzata con l\'Editor SkinMC. Puoi scegliere tra i modelli Steve e Alex, importare skin da un file o un nome utente e creare la tua skin.',
            'draw' => 'Disegna con lo strumento penna. Seleziona un colore dalla tavolozza per usarlo.',
            'eyedropper' => 'Usa il contagocce per selezionare un colore dalla skin e aggiungerlo alla tavolozza attuale.',
            'fill' => 'Riempi intere aree della skin usando lo strumento di riempimento. Seleziona un colore prima di usarlo.',
            'move' => 'Trascina e muoviti intorno alla tela dell\'editor di skin con lo strumento di movimento.',
            'decrease_brightness' => 'Diminuisce la luminosità del colore attualmente attivo.',
            'increase_brightness' => 'Aumenta la luminosità del colore attualmente attivo.',
            'erase' => 'Cancella i pixel disegnati sul livello secondario di sovrapposizione.',
            'minimap' => 'Minimappa',
            'minimap_info' => 'La minimappa può mostrare la texture della skin in una vista piatta mentre è in modalità 3D. In modalità 2D la minimappa passa a un\'anteprima 3D della tua skin. Puoi ingrandire e rimpicciolire.',
            'autosave' => 'Salvataggio automatico',
            'autosave_info' => 'La funzione di salvataggio automatico salva automaticamente la tua skin ogni 30 secondi. È possibile accedere alle skin salvate nell\'editor premendo l\'icona della cartella, e scegliendo "Skin precedenti".',
            '2d_editor' => 'Editor 2D e 3D',
            '2d_editor_info' => 'Cambia la modifica della tua skin Minecraft in modalità 2D o 3D.',
        ],
    ],
    'account' => [
        'level' => 'Livello',
        'level_history' => 'Cronologia livello',
        'xp' => 'XP',
        'my_xp' => 'I miei XP',
        'xp_to_next_level' => ':xp XP al livello successivo',
        'xp_info' => 'Che cosa sono gli XP?',
        'xp_info_tooltip' => 'Gli XP si guadagnano con varie attività, come l\'aggiunta di tag alle skin, invitando amici, scrivendo commenti e altro. Con ogni XP guadagnato puoi salire di livello e sbloccare cose interessanti!',
        'settings' => [
            'title' => 'Account',
            'show_profile' => 'Vai al profilo',
            'friends' => 'Amici',
            'friends_detail' => 'Rimani connesso utilizzando la tua lista di amici su SkinMC.',
            'security' => 'Sicurezza',
            'security_detail' => 'Aggiorna la password di accesso e mantieni il tuo account al sicuro',
            'social' => 'Account social media',
            'social_detail' => 'Personalizza il tuo profilo aggiungendo i tuoi social media',
            'link' => 'Collega account Minecraft',
            'link_detail' => 'Collega il tuo account Minecraft e rivendica il tuo profilo.',
            'logout' => 'Vuoi uscire dal tuo account SkinMC?',
            'automatic_backups' => 'Backup automatico della skin',
            'automatic_backups_info' => 'Come membro SkinMC plus le tue skin vengono salvate ogni giorno.',
        ],
        'capes' => [
            'title' => 'Mantello SkinMC',
            'description' => 'Indossa qualsiasi mantello che desideri nel gioco con SkinMC Capes gratis.',
            'drop' => 'Trascina qui un mantello',
            'drop-hint' => 'Dimensioni 64x32px',
            'select' => 'Seleziona un\'immagine',
            'upload-cape' => 'Carica & usa il mantello',
            'save-and-use' => 'Salva & usa',
            'uploaded-cape' => 'Mantello caricato',
            'no-cape' => 'Nessun Mantello',
            'remove-cape' => 'Rimuovi mantello',
            'download' => 'Scarica SkinMC Mod per vedere il tuo e mantelli di altri giocatori in gioco.',
            'learn-more' => 'Scopri di più',
            'link-account' => 'Collega il tuo account Minecraft per caricare un mantello.',
            'updated' => 'Il tuo mantello è stato aggiornato!',
            'removed' => 'Il tuo mantello è stato rimosso.',
            'active' => 'Il mantello è attivato!',
        ],
        'favourite' => 'Preferito',
        'remove_favourite' => 'Rimuovi dai Preferiti',
        'added_to_favourites' => 'Aggiunto ai Preferiti',
        'removed_from_favourites' => 'Rimosso dai preferiti',
        'welcome' => 'Piacere di vederti!',
        'view-profile' => 'Visualizza il mio profilo',
        'security' => [
            'title' => 'Sicurezza',
            'email' => 'Indirizzo email',
            'email-title' => 'Aggiorna il tuo indirizzo email.',
            'save' => 'Salva',
            'password' => 'Password',
            'password-title' => 'Cambia la tua password in qualsiasi momento.',
            'social-provider' => 'Per aggiornare le informazioni del tuo account, come la tua password, visita il tuo fornitore di accesso:',
            'social-provider-email' => 'Il tuo indirizzo di posta associato al tuo fornitore di accesso',
            'social-provider-connected' => 'Fornitori di accessi attualmente connessi',
            'current-password' => 'Password attuale',
            'forgot' => 'Hai dimenticato la password?',
            'edit' => 'Modifica',
            'delete' => 'Elimina il mio account',
            'account-deletion' => 'Elimina il tuo account SkinMC.',
            'delete-info' => 'Per favore conferma per continuare',
            'delete-confirmation' => 'Eliminare il tuo account è irreversibile. Tutte le tue informazioni personali e contenuti come post, preferiti, mantelli caricati, personalizzazioni, ecc. saranno eliminati e non potranno essere recuperati.',
            'delete-confirmation-info' => 'Inserisci la password per continuare',
            'delete-confirmation-info-social' => 'Type "delete" to confirm account deletion',
            'type-delete' => 'Type "delete" to confirm',
            'type-delete-label' => 'Type "delete" to confirm',
            'yes-confirm-delete' => 'Sì, conferma l\'eliminazione',
            'account-successfully-deleted' => 'Il tuo account e i tuoi dati sono stati eliminati con successo.',
        ],
        'social' => [
            'title' => 'Account Social',
            'edit' => 'Modifica',
            'save' => 'Salva',
            'link-account' => 'Collega il tuo account Minecraft a SkinMC per visualizzare i tuoi link sociali sul tuo profilo.',
            'finish-setup' => 'Termina la configurazione',
            'connect-account' => 'Collega i tuoi account',
            'connect-description' => 'Scegli quali account vuoi collegare e sbloccare le integrazioni SkinMC speciali.',
            'empty' => 'Nessun account aggiunto',
            'empty-description' => 'I tuoi account di social media verranno visualizzati qui e sul tuo profilo pubblico. Una volta aggiunti aggiungeranno più personalizzazione alla tua pagina e abiliteranno le integrazioni.',
            'connect' => 'Connettiti',
            'username' => 'nome utente',
            'spotify' => 'Aggiungi il tuo nome utente Spotify per mostrare le tue informazioni sul tuo profilo.',
            'discord' => 'Inserisci il tuo nome utente e numero Discord per visualizzare le informazioni Discord sul tuo profilo SkinMC.',
            'youtube' => 'Aggiungi il tuo canale YouTube a SkinMC che mostrerà il tuo canale YouTube sul tuo profilo.',
            'youtube-format' => 'Utilizzare il seguente formato a seconda del link del canale:',
            'twitter' => 'Inserisci il tuo nome utente X (ex Twitter) per visualizzarlo sul tuo profilo.',
            'bluesky' => 'Inserisci il tuo nome utente Bluesky per esempio username.bsky.social per visualizzare il tuo profilo Bluesky sul tuo profilo.',
            'twitch' => 'Inserisci il tuo nome utente Twitch per visualizzare il tuo canale Twitch sul tuo profilo.',
            'reddit' => 'Inserisci il tuo nome utente Reddit per visualizzare il tuo profilo Reddit sul tuo profilo.',
            'github' => 'Inserisci il tuo nome utente Github per visualizzare il tuo profilo Github sul tuo profilo.',
            'telegram' => 'Inserisci il tuo nome utente Telegram per visualizzare il tuo link Telegram sul tuo profilo.',
            'tiktok' => 'Inserisci il tuo nome utente di TikTok per visualizzare il tuo profilo TikTok sul tuo profilo.',
            'snapchat' => 'Inserisci il tuo nome utente Snapchat per visualizzare il tuo profilo Snapchat sul tuo profilo.',
            'instagram' => 'Inserisci il tuo nome utente Instagram per visualizzare il tuo profilo Instagram sul tuo profilo.',
            'facebook' => 'Inserisci il tuo nome utente di Facebook per visualizzare il tuo profilo Facebook sul tuo profilo.',
            'includes_skinmc_plus_benefits' => 'Include i vantaggi di SkinMC plus',
        ],
        'recover' => [
            'title' => 'Recupera il tuo account',
            'subtitle' => 'Inserisci la tua nuova password e confermarla per completare il recupero del tuo account.',
            'new_password' => 'Nuova password',
            'repeat_new_password' => 'Ripeti la nuova password',
            'submit' => 'Recupera account',
        ],
        'customise' => [
            'title' => 'Personalizza il tuo profilo',
            'description' => 'Aggiungi i tuoi social media, scegli un\'emoji, imposta la tua posizione e altro',
            'information' => 'Informazioni',
            'preview' => 'Anteprima',
            'location' => [
                'title' => 'Posizione',
                'description' => 'Scegli quale posizione vuoi aggiungere al tuo profilo.',
            ],
            'biography' => [
                'title' => 'Chi sono',
                'description' => 'Scrivi una bio per il tuo profilo.',
            ],
            'status' => 'Stato',
            'status-toggle' => 'Mostra il mio stato online',
            'emoji' => 'Emoji',
            'name-history-toggle' => 'Rendi la cronologia utente privata',
            'name-history-info' => 'La tua cronologia dei nomi utente di Minecraft è attualmente',
            'name-history-toggle-on' => 'privata',
            'name-history-toggle-off' => 'pubblica',
            'theme' => 'Tema del profilo',
            'theme-primary' => 'Primario',
            'theme-secondary' => 'Secondario',
            'appearance' => 'Aspetto',
        ],
        'link' => [
            'manage' => 'Gestisci account di Minecraft collegato',
            'description' => 'Vedi e gestisci il tuo account di Minecraft collegato',
            'title' => 'Account di Minecraft collegato',
            'current' => 'Account Minecraft attualmente collegato.',
            'status' => 'Ora hai pieno accesso a tutte le funzionalità di SkinMC!',
            'linked' => 'Collegato',
            'disconnect' => 'Disconnetti',
            'disconnect-title' => 'Disconnetti account Minecraft',
            'disconnect-info' => 'Sei sicuro di voler uscire dal tuo account SkinMC?',
            'disconnect-features' => 'Perderai l\'accesso ai commenti, alla personalizzazione e ad altre funzionalità che richiedono un account di Minecraft collegato. Per utilizzarli di nuovo sarà necessario collegare un account Minecraft.',
            'disconnect-following' => 'Scollegare il tuo account Minecraft rimuoverà permanentemente tutti i profili che segui.',
            'disconnect-posts' => 'I tuoi post feed creati e piaciuti verranno eliminati.',
            'can-not-undo' => 'L\'operazione non può essere annullata.',
            'are-you-sure' => 'Sei sicuro?',
            'confirm' => 'Sì, conferma la disconnessione',
            'cancel' => 'No, annulla',
            'success' => 'Il tuo account è stato disconnesso con successo!',
        ],
        'finish-setup' => [
            'title' => 'Termina configurazione account',
            'description' => 'Termina la configurazione del tuo account e ottieni l\'accesso completo a tutte le funzionalità collegando il tuo account Minecraft a SkinMC.',
            'link' => 'Collega account Minecraft',
            'get-started' => 'Inizia',
            'skip' => 'Salta',
            'claim' => 'Reclama questo profilo',
            'customise' => 'Personalizza la tua pagina',
            'social' => 'Aggiungi link social',
            'comment' => 'Accesso ai commenti',
            'direct_message' => 'Invia messaggi diretti',
            'feed' => 'Pubblica gli aggiornamenti di stato sul feed',
            'follow' => 'Segui i tuoi amici',
            'badge' => 'Badge mostrato sul tuo profilo',
            'cape' => 'Mantelli di Minecraft personalizzati',
            'backup' => 'Backup automatico della skin',
            'more' => 'E altro...',
        ],
        'skins' => [
            'title' => 'Gestisci skin',
            'toggle' => 'La visibilità della skin è stata modificata',
        ],
        'invite' => [
            'title' => 'I miei inviti',
            'headline' => 'Invita i tuoi amici',
            'info' => 'Crea un codice invito da condividere con il tuo amico. Se lo accetterà, entrambi otterrete qualche XP extra!',
            'description' => 'Crea un invito per i tuoi amici e guadagnerete entrambi alcuni XP extra.',
            'generate' => 'Crea codice invito',
            'empty' => 'Non hai ancora creato alcun invito.',
            'code' => 'Codice',
            'expiry' => 'Ogni codice funziona solo una volta.',
            'status' => [
                'title' => 'Stato',
                'pending' => 'In attesa',
                'accepted' => 'Accettato',
            ],
            'add_invite' => [
                'button' => 'Hai un invito?',
                'title' => 'Aggiungi un codice invito',
                'redeem' => 'Riscatta invito',
            ],
            'share' => 'Invia al tuo amico un link invito',
        ],
        'emoji' => [
            'title' => 'Emoji di SkinMC',
            'introducing' => 'Introduzione',
            'info' => 'Personalizza il tuo profilo con le emoji. Sbloccane di nuove mentre sali di livello.',
            'unlocked_at' => 'Sbloccato al livello :level',
            'unlocks_at' => 'Raggiungi il livello :level per sbloccare',
            'turn_off' => 'Mostra emoji',
        ],
    ],
    'notifications' => [
        'title' => 'Notifiche',
        'view_all' => 'Mostra tutto',
        'view_all_notifications' => 'Mostra tutte le notifiche',
        'image' => 'Foto notifica',
        'archived' => 'Archiviate',
        'inbox' => 'Messaggi in arrivo',
        'empty' => [
            'title' => 'È tutto aggiornato!',
            'text' => 'Le nuove notifiche verranno visualizzate qui.',
            'text-archived' => 'Le notifiche archiviate verranno visualizzate qui.',
        ],
        'action' => [
            'archive' => 'Sposta nell\'archivio',
            'unarchive' => 'De-archivia',
            'open' => 'Tocca per aprire',
        ],
        'toast' => [
            'archive' => 'Notifica spostata nell\'archivio',
            'unarchive' => 'Notifica spostata nei messaggi in arrivo',
            'undo' => 'Annulla',
        ],
    ],
    'error' => [
        'offline' => [
            'title' => 'Nessuna connessione',
            'subtitle' => 'La connessione Internet è stata interrotta. Controllare la connessione e ricaricare la pagina per riprovare.',
            'try_again' => 'Riprova',
        ],
        '404' => [
            'title' => '404 Pagina non Trovata',
            'subtitle' => 'Hm, sembra che non sia stato trovato nulla in questa posizione. Forse si può provare a tornare indietro o iniziare una nuova ricerca?
',
            'try_again' => 'Torna alla pagina iniziale',
        ],
    ],
    'heads' => [
        'list' => [
            'meta' => [
                'title' => 'Database delle teste Minecraft',
                'description' => 'Esplora il database delle teste Minecraft con cui decorare il tuo mondo o generare il tuo comando personalizzato. Visualizza le teste ufficiali, le teste dei giocatori e le teste personalizzate con texture che non cambiano mai.',
            ],
            'header' => [
                'title' => 'Teste Minecraft',
                'subtitle' => 'Esplorate il nostro database di teste di Minecraft per decorare il vostro mondo o per generare il vostro comando. Le teste dei giocatori mostrano la skin correntemente indossata da un utente e possono cambiare quando l\'utente aggiorna la propria skin. Le teste personalizzate sono collegate al file della skin di Mojang e non cambiano mai. Le teste personalizzate devono essere evocate utilizzando un blocco di comando, poiché il comando è molto lungo.
',
            ],
            'count' => [
                'heads' => ':heads testa|:heads teste',
            ],
            'customheads' => [
                'title' => 'Teste personalizzata',
                'description' => 'Le teste personalizzate utilizzano il percorso diretto del file di texture sui server Mojang. Pertanto le texture non verranno mai eliminate e le teste non cambieranno mai.',
                'version' => 'Minecraft 1.8 o successivo
',
            ],
            'playerheads' => [
                'title' => 'Teste dei Giocatori',
                'description' => 'Le teste dei giocatori utilizzano la texture della pelle corrente di un giocatore di Minecraft. Essendo basate sul nome utente, quando il giocatore cambia nome o skin, la testa cambia.',
                'version' => 'Tutte le versioni di Minecraft',
            ],
        ],
    ],
    'mod' => [
        'title' => 'SkinMC Mod: mantelli personalizzati gratis',
        'headline' => 'Introduzione della mod SkinMC per una maggiore personalizzazione',
        'description' => 'Ritornando alla comunità di Minecraft, con una mod gratuita che consente ai giocatori di personalizzare maggiormente con i mantelli personalizzati, disponibile e visibile per chiunque utilizzi il mod.',
        'download' => 'Scarica ora',
        'download-title' => 'Scarica la mod',
        'requires' => 'Richiesto',
        'select-version' => 'Scegli la tua versione di Minecraft',
        'get-started' => 'Iniziare è semplice',
        'step-1' => '1. Ottieni la mod',
        'step-1-detail' => 'Installa Fabric, quindi scarica la mod per la tua versione del gioco e installala mettendo il file jar nella cartella delle mod.',
        'step-2' => '2. Collega il tuo account',
        'step-2-detail' => 'Se non lo hai già, iscriviti e collega il tuo account Minecraft a SkinMC.',
        'step-3' => '3. Carica il tuo mantello',
        'step-3-detail' => 'Vai al tuo account e carica il tuo mantello personalizzato. Sarà visibile in gioco.',
        'all-versions' => 'Tutte le versioni',
        'latest' => 'Recenti',
        'logged-in' => 'Carica il tuo mantello',
        'mirror' => 'Ruota',
        'download-via' => 'Scarica tramite:',
        'curseforge' => 'CurseForge',
    ],
    'app' => [
        'title' => 'SkinMC App per Android',
        'headline' => 'Saluta la SkinMC App per Android.',
        'play-store-attribution' => 'Google Play e il logo di Google Play sono marchi di Google LLC.',
        'features' => 'Caratteristiche comode per il viaggio',
        'feature-qr' => 'Scanner di codici QR integrato',
        'feature-qr-detail' => 'Usa lo scanner di codici QR incorporato per ottenere facilmente una skin dal tuo computer all\'app o scansiona il codice QR del tuo profilo personalizzato.',
        'feature-files' => 'Salva direttamente nei file',
        'feature-files-detail' => 'Con l\'utilizzo di Android File Manager, l\'applicazione può comodamente salvare le Skin, rendendole più facile da applicare nella Bedrock Edition.',
        'feature-noads' => 'Nessuna pubblicità',
        'feature-noads-detail' => 'Un\'interfaccia pulita, senza distrazioni. Goditi un\'esperienza senza pubblicità senza fastidi intrusivi dal web all\'app.',
        'feature-experience' => 'Esperienza',
        'feature-experience-detail' => 'Goditi l\'esperienza completa di SkinMC ovunque, con funzionalità aggiuntive. Personalizza il tuo profilo, aggiungi il tuo bio, crea un divertente codice QR e altro ancora!',
        'get-app-headline' => 'Scarica l\'app SkinMC',
        'get-app-detail' => 'Il tuo compagno per Minecraft proprio per il tuo Android — disponibile gratuitamente.',
    ],
    'random' => [
        'title' => 'Caricamento della skin di Minecraft casuale',
        'description' => 'Caricamento della skin di Minecraft casuale',
        'headline' => 'Attendi...',
        'redirect' => 'Verrai reindirizzato automaticamente. Pagina non caricata?',
        'click-here' => 'Clicca qui',
        'messages' => [
            '1' => 'Caricamento della skin di Minecraft casuale...',
            '2' => 'Scavando...',
            '3' => 'Creeper, aw man...',
            '4' => 'Ricerca nelle casse...',
            '5' => 'Sapevi che la skin in arrivo è completamente casuale?',
            '6' => 'Skin casuale in arrivo...',
            '7' => 'Ancora un blocco...',
            '8' => 'Ordinamento dell\'inventario...',
            '9' => 'Craftando un piccone di diamante...',
            '10' => 'Cercando Herobrine...',
        ],
    ],
    'feed' => [
        'title' => 'Feed',
        'following' => 'Seguiti',
        'sign-up' => 'Registrati o accedi per partecipare alla conversazione.',
        'link-account' => 'Collega il tuo account di Minecraft per partecipare alla conversazione.',
        'placeholder' => 'Che cosa sta succedendo?',
        'audience' => 'Pubblico',
        'audience-title' => 'Chi può vedere questo?',
        'everyone' => 'Chiunque',
        'everyone-info' => 'Chiunque dentro o fuori SkinMC.',
        'followers' => 'Followers',
        'followers-info' => 'Accesso effettuato o membri che mi seguono.',
        'private' => 'Solo io',
        'private-info' => 'Post privato che posso vedere solo io.',
        'submit' => 'Post',
        'like' => 'Mi piace',
        'comment' => 'Rispondi',
        'share' => 'Condividi',
        'remaining' => 'Rimanenti',
        'profile' => 'Pubblicato da :username',
        'posts' => 'Tutti i post',
        'my-posts' => 'I miei Post',
        'view-all' => 'Vedi tutti i post',
        'post' => [
            'meta' => ':username su SkinMC: :text',
            'title' => 'Post',
            'created' => 'Aggiornamento dello stato pubblicato!',
            'confirm-delete' => 'Sei sicuro di voler eliminare questo post? L\'operazione non può essere annullata.',
            'delete' => 'Cancella Post',
            'deleted' => 'Il tuo post è stato cancellato.',
        ],
        'repost' => [
            'button' => 'Ripubblica',
            'quote_button' => 'Cita',
            'title' => 'Ripubblica questo post',
            'quote_title' => 'Cita post',
            'quote_label' => 'Aggiungi un commento (opzionale)',
            'quote_placeholder' => 'Condividi la tua opinione...',
            'reposted' => 'ripubblicato',
            'success' => 'Ripubblicato!',
            'removed' => 'Repost rimosso.',
            'already_reposted' => 'Hai già ripubblicato questo.',
            'undo' => 'Annulla il repost',
            'original_deleted' => 'Il post originale è stato eliminato.',
            'deleted_post' => 'Questo post è stato eliminato',
        ],
        'hashtags' => [
            'title' => 'Trending',
            'trending-now' => 'Trending now',
            'post' => 'post',
            'posts' => 'posts',
            'hashtag' => 'Hashtag',
            'hashtags' => 'Hashtags',
            'no-results' => 'No hashtags found',
        ],
        'search' => [
            'title' => 'Search',
            'placeholder' => 'Search posts, hashtags...',
            'no-results' => 'No results found',
            'posts' => 'Posts',
            'no-hashtags-found' => 'No hashtags found matching ":query"',
            'no-results-found' => 'No results found for ":query"',
        ],
        'poll' => [
            'title' => 'Sondaggio',
            'create' => 'Crea un sondaggio',
            'option' => 'Opzione',
            'add_option' => 'Aggiungi opzione',
            'duration' => 'Durata',
            'duration_1' => '1 giorno',
            'duration_3' => '3 giorni',
            'duration_7' => '7 giorni',
            'votes' => '{0} voti|{1} voto|[2,*] voti',
            'ended' => 'Sondaggio terminato',
            'ends_in' => 'Termina :time',
            'login_required' => 'Accedi per votare',
        ],
        'gif' => [
            'title' => 'GIF',
            'search_placeholder' => 'Cerca GIF in KLIPY...',
            'no_results' => 'Nessuna GIF trovata',
            'powered_by' => 'Offerto da',
            'categories' => 'Categorie',
            'trending' => 'Di tendenza',
        ],
        'media' => 'Media',
        'follow-suggestions' => 'Segui il team',
        'explore' => 'Esplora',
        'hashtag' => 'Hashtag',
        'no_users' => 'No users found.',
        'stories' => [
            'archive' => [
                'title' => 'Archivio Delle Storie',
                'subtitle' => 'Le tue storie archiviate sono visibili solo a te',
                'empty' => 'Ancora nessuna storia è stata archiviata',
                'empty-description' => 'Le storie che pubblicherai appariranno qui dopo 24 ore.',
                'action' => 'Archivia',
                'archived' => 'Storia spostata nell\'archivio.',
                'already-archived' => 'La storia è già archiviata.',
            ],
        ],
    ],
    'private' => [
        'title' => 'Post privati',
        'text' => 'Questo post è privato.',
    ],
    'liked' => [
        'title' => 'Mi piace',
    ],
    'following' => [
        'title' => 'Seguiti',
        'text' => 'Accedi per visualizzare questo post.',
    ],
    'tags' => [
        'empty' => 'Ancora nessun tag su cui votare',
        'empty-subtitle' => 'Sii il primo ad aggiungerne uno',
    ],
    'inbox' => [
        'title' => 'Messaggi',
        'details' => 'Dettagli',
        'message_user' => 'Messaggio',
        'write_message' => 'Scrivi un messaggio',
        'empty' => [
            'no_message_selected' => 'Nessun messaggio selezionato',
            'open_or_start_conversation' => 'Apri una conversazione dall\'elenco dei messaggi o avviane una nuova.',
            'no_messages' => 'Nessun messaggio da leggere',
            'start_conversation' => 'Una volta avviata una nuova conversazione, i messaggi verranno visualizzati qui.',
            'conversation' => 'Questo è l\'inizio della tua conversazione con :username.',
            'users' => 'Impossibile trovare utenti che corrispondono alla query corrente.',
        ],
        'typing' => ':username sta scrivendo...',
        'new_message' => 'Nuovo messaggio',
        'mark_unread' => 'Segna come non letto',
        'send_message' => 'Invia messaggio',
        'delete_message' => 'Elimina il messaggio per te',
        'latest_conversations' => 'Ultime conversazioni',
        'delete_conversation' => 'Elimina conversazione',
        'show_details' => 'Mostra dettagli',
        'hide_details' => 'Nascondi dettagli',
        'unread' => 'Non letti',
        'deleted' => 'Cancellato',
        'report_message' => 'Segnala messaggio',
        'add_reaction' => 'Aggiungi reazione',
        'today' => 'Oggi',
        'reconnect' => 'Riconnetti nuovamente il tuo account Minecraft per chattare',
        'account_disconnected' => 'Questo utente ha disconnesso l\'account di Minecraft collegato.',
        'saved_messages' => 'Messaggi salvati',
        'new_message_to_label' => 'A',
        'external-link-to' => 'Questo link ti porterà a',
        'external-link-confirmation' => 'Sei sicuro di voler continuare?',
        'external-link' => 'Link esterno',
        'reply' => 'Rispondi',
    ],
    'server' => [
        'manage' => [
            'stats' => 'Statistiche',
        ],
    ],
    'report' => [
        'button' => 'Segnala',
        'title' => 'Contenuto segnalato',
        'describe' => 'Descrivi brevemente perché stai segnalando il contenuto',
        'select' => 'Seleziona il motivo della segnalazione',
        'submit' => 'Invia segnalazione',
        'reasons' => [
            'INAPPROPRIATE_CONTENT' => 'Contenuto inappropriato',
            'SPAM' => 'Posta indesiderata',
            'HARASSMENT' => 'Molestia',
            'OTHER' => 'Altro',
        ],
    ],
    'leaderboard' => [
        'title' => 'Classifica',
        'description' => 'Visualizza la classifica SkinMC degli utenti.',
        'headline' => 'Primi 10',
        'all-time-invites' => 'Tutti gli inviti',
        'all-time-xp' => 'Tutti gli XP',
        '30-day-xp' => 'XP degli ultimi 30 giorni',
    ],
];
