<?php

return [
    'pronouns' => 'Pronomi',
    'pronouns_help' => 'Facoltativo. Fai sapere alle persone come riferirti.',
    'pronouns_placeholder' => 'es: lei, lui/lui, loro/a',
    'title' => 'Stato',
    'add' => 'Cosa sta succedendo?',
    'edit' => 'Modifica lo stato',
    'view' => 'Visualizza lo stato',
    'placeholder' => "Che c'è di nuovo?",
    'message' => 'Messaggio di stato',
    'emoji' => 'Scegli un\'emoji',
    'remove_emoji' => 'Rimuovi emoji',
    'clear_after' => 'Svuota dopo',
    'hour' => '1 ora',
    'day' => '1 giorno',
    'week' => '1 settimana',
    'forever' => 'Fino a quando non lo cancello',
    'expires' => 'Cancella :time',
    'save' => 'Salva stato',
    'saving' => 'Salvataggio in corso…',
    'saved' => 'Stato salvato',
    'cleared' => 'Stato cancellato',
    'clear' => 'Cancella lo stato',
    'close' => 'Chiudi lo stato',
    'react' => 'Reagisci allo stato',
    'reacted' => 'Reazione inviata',
    'reply' => 'Rispondi allo stato',
    'reply_placeholder' => 'Rispondi…',
    'sending' => 'Invio in corso…',
    'replied' => 'Risposta inviata',
    'chat_reaction' => 'Reagito a uno stato',
    'chat_reply' => 'Risposto a uno stato',
    'chat_preview' => 'Stato: :message',
    'sign_in' => 'Accedi per reagire o iniziare una conversazione',
    'restricted' => 'Le interazioni di stato non sono disponibili in base alle impostazioni di messaggistica.',
    'error' => 'Impossibile aggiornare lo stato. Si prega di riprovare.',
    'send_error' => 'Impossibile inviare la tua risposta. Per favore riprova.',
    'rate_limited' => 'Attendere un momento prima d\'inviare un\'altra risposta.',
    'unavailable' => 'Questo stato è cambiato o scaduto.',
    'invalid_emoji' => 'Per favore scegli una singola emoji.',
    'picker_error' => 'Impossibile caricare le emoji. Per favore riprova.',
];
