<?php

return [
    'skins' => 'Скини',
    'avatars' => 'Аватари',
    'editor' => 'Редактор',
    'heads' => 'Голови',
    'capes' => 'Плащі',
    'servers' => 'Сервери',
    'achievement' => 'Досягнення',
    'armor' => 'Стійка для броні',
    'banners' => 'Стяги',
    'banner' => 'Banner Editor',
    'profile' => 'Мій профіль',

    'generators' => 'Генератори',

    // Navigation dropdowns
    'feed' => 'Feed',
    'discover' => 'Discover',
    'mods' => 'Mods',
    'shaders' => 'Shaders',
    'resource_packs' => 'Resource Packs',

    'logout' => 'Вийти',
    'register' => 'Зареєструватися',
    'login' => 'Увійти',
    'about' => 'Про SkinMC',
    'contact' => 'Звʼязатися',
    'faqs' => 'Поширені запитання',

    'minecraft_name' => 'Імʼя Minecraft',
    'minecraft_uuid' => 'Minecraft UUID',
    'what' => 'Пошук',
    'recent_searches' => 'Нещодавні запити',
    'username' => 'Імʼя користувача',
    'uuid' => 'UUID',
    'search' => 'Пошук',
    'search_placeholder' => 'Спробуйте',
    'search_placeholder_uuid' => 'Введіть UUID',
    'start_search' => 'Почати пошук',
    'cancel_search' => 'Скасувати',
    'search_type' => 'Тип пошуку',
    'search_type_all' => 'Усі результати',
    'profiles' => 'Профілі',
    'view_skin' => 'Поглянути скин',
    'edit_skin' => 'Редагувати скин',
    'make_avatar' => 'Створити аватар',
    'find_heads' => 'Знайти голови гравців',

    'home' => 'Головна',
    'help' => 'Допомога',
    'tools' => 'Інструменти',
    'more-tools' => 'Більше інструментів',
    'skin_viewer' => 'Переглядач скинів',
    'avatar_maker' => 'Генератор аватарів',
    'collections' => 'Колекції',
    'popular_skins' => 'Популярні скини',
    'cartoon_skins' => 'Мультяшні скіни',
    'animal_skins' => 'Скини тварин',
    'community' => 'Спільнота',
    'imprint' => 'Вихідні дані',
    'cookies' => 'Файли Cookie',
    'terms' => 'Умови користування',
    'privacy' => 'Політика конфіденційності',
    'app' => 'Додаток',
    'mod' => 'Мод',
    'totem' => 'Тотеми',
    'cube' => 'Cube',
    'new' => 'New',

    'feedback' => 'Зворотний звʼязок',
    'status' => 'Статус',
    'recent_searches_placeholder' => 'Коли ви починаєте пошук, ваші минулі пошуки відображатимуться тут.',
    'recent_views_placeholder' => 'Після відвідування деяких профілів тут відображатимуться ті, які ви відвідали раніше.',
    'moderate' => 'Модерувати',
    'listings' => 'Списки',
    'add' => 'Додати',

    'theme' => [
        'title' => 'Theme',
        'dark' => 'Темна',
        'light' => 'Світла',
        'auto' => 'Auto'
    ],
];
