<?php

return [
    'skins' => 'Pieles',
    'avatars' => 'Avatares',
    'editor' => 'Editor',
    'capes' => 'Capas',
    'servers' => 'Servidores',
    'achievement' => 'Logro',

    'logout' => 'Cerrar sesión',
    'register' => 'Regístrate',
    'login' => 'Iniciar sesión',
    'about' => 'Acerca de',
    'faqs' => 'FAQs',

    'minecraft_name' => 'Nombre de Minecraft',
    'recent_searches' => 'búsquedas recientes',
    'search' => 'Buscar',
    'search_placeholder' => 'Prueba',
    'start_search' => 'Empezar a buscar',
    'cancel_search' => 'Cancelar',
    'search_type' => 'Tipo de búsqueda',
    'view_skin' => 'Ver skin',
    'edit_skin' => 'Editar skin',
    'make_avatar' => 'Hacer avatar',

    'home' => 'Inicio',
    'help' => 'Ayuda',
    'tools' => 'Herramientas',
    'skin_viewer' => 'Visor de aspecto',
    'avatar_maker' => 'Fabricante de avatar',
    'collections' => 'Colecciones',
    'popular_skins' => 'Pieles populares',
    'cartoon_skins' => 'Pieles de dibujos animados',
    'animal_skins' => 'Pieles animales',
    'community' => 'Comunidad',
    'imprint' => 'Aviso',
    'cookies' => 'Cookies',
    'terms' => 'Términos',
];
