<?php

return [
    'skins' => 'Aspectos',
    'skins_profile' => 'Aspectos de perfiles',
    'skins_profile_subtitle' => 'Diseños de perfiles de Minecraft',
    'creations' => 'Creaciones',
    'creations_subtitle' => 'Aspectos compartidos por la comunidad',
    'skin_upload_subtitle' => 'Añade tu creación',
    'skin_tags' => 'Etiquetas',
    'avatars' => 'Avatares',
    'editor' => 'Editor',
    'heads' => 'Cabezas',
    'capes' => 'Capas',
    'servers' => 'Servidores',
    'achievement' => 'Logros',
    'armor' => 'Soporte para armadura',
    'banners' => 'Estandartes',
    'banner' => 'Editor de Estandartes',
    'banner_gallery' => 'Galería de Estandartes',
    'profile' => 'Mi perfil',
    'wallpapers' => 'Fondos de pantalla',

    'generators' => 'Generadores',

    // Navigation dropdowns
    'feed' => 'Inicio',
    'discover' => 'Descubrir',
    'mods' => 'Mods',
    'shaders' => 'Shaders',
    'resource_packs' => 'Paquete de recursos',
    'modpacks' => 'Modpacks',
    'datapacks' => 'Datapacks',
    'plugins' => 'Plugins',

    'logout' => 'Cerrar sesión',
    'register' => 'Registrarse',
    'login' => 'Iniciar sesión',
    'about' => 'Acerca de',
    'contact' => 'Contacto',
    'faqs' => 'FAQ\'s',

    'minecraft_name' => 'Nombre de Minecraft',
    'minecraft_uuid' => 'UUID de Minecraft',
    'what' => 'Qué',
    'recent_searches' => 'Búsquedas recientes',
    'username' => 'Nombre de usuario',
    'uuid' => 'UUID',
    'search' => 'Búsqueda',
    'search_placeholder' => 'Probar',
    'search_placeholder_uuid' => 'Introducir UUID',
    'start_search' => 'Comenzar búsqueda',
    'cancel_search' => 'Cancelar',
    'search_type' => 'Tipo de búsqueda',
    'search_type_all' => 'Todos los resultados',
    'profiles' => 'Perfiles',
    'view_skin' => 'Ver aspecto',
    'edit_skin' => 'Editar aspecto',
    'make_avatar' => 'Crear avatar',
    'find_heads' => 'Buscar cabezas de jugador',
    'no_results_found' => 'Aún no hay sugerencias. Pulsa Enter para buscarlo.',

    'home' => 'Inicio',
    'help' => 'Ayuda',
    'tools' => 'Herramientas',
    'more-tools' => 'Más herramientas',
    'skin_viewer' => 'Visor de aspectos',
    'avatar_maker' => 'Creador de Avatares',
    'collections' => 'Colecciones',
    'popular_skins' => 'Aspectos Populares',
    'cartoon_skins' => 'Aspectos de caricatura',
    'animal_skins' => 'Aspectos de animales',
    'community' => 'Comunidad',
    'imprint' => 'Imprimir',
    'cookies' => 'Cookies',
    'terms' => 'Términos de servicio',
    'privacy' => 'Política de privacidad',
    'app' => 'Aplicación',
    'mod' => 'Mod',
    'totem' => 'Totems',
    'cube' => 'Cubo',
    'new' => 'Nuevo',

    'boards' => 'Tablones',
    'boards_subtitle' => 'Tus colecciones guardadas',

    'feedback' => 'Opiniones',
    'status' => 'Estado',
    'recent_searches_placeholder' => 'A medida que empieces a buscar, tus búsquedas pasadas se mostrarán aquí.',
    'recent_views_placeholder' => 'Después de visitar algunos perfiles, los que has visitado te mostrarán aquí.',
    'moderate' => 'Moderar',
    'listings' => 'Listados',
    'add' => 'Añadir',

    // Autocomplete types
    'autocomplete' => [
        'profile' => 'Perfil',
        'server' => 'Servidor',
        'project' => 'Proyecto',
        'skin_tag' => 'Etiqueta de aspecto',
        'server_category' => 'Categoría del servidor',
        'modrinth_category' => 'Categoría del proyecto',
    ],

    'theme' => [
        'title' => 'Tema',
        'dark' => 'Oscuro',
        'light' => 'Claro',
        'auto' => 'Automático',
    ],

    'language' => 'Idioma',
];
