<?php

return [
    'skins' => 'Aspectos',
    'avatars' => 'Avatares',
    'editor' => 'Editor',
    'heads' => 'Cabezas',
    'capes' => 'Capas',
    'servers' => 'Servidores',
    'achievement' => 'Logros',
    'armor' => 'Soporte para armadura',
    'banners' => 'Estandartes',
    'banner' => 'Banner Editor',
    'profile' => 'Mi perfil',

    'generators' => 'Generadores',

    // Navigation dropdowns
    'feed' => 'Feed',
    'discover' => 'Discover',
    'mods' => 'Mods',
    'shaders' => 'Shaders',
    'resource_packs' => 'Resource Packs',
    'modpacks' => 'Modpacks',
    'datapacks' => 'Data Packs',
    'plugins' => 'Plugins',

    'logout' => 'Cerrar sesión',
    'register' => 'Registrarse',
    'login' => 'Iniciar sesión',
    'about' => 'Acerca de',
    'contact' => 'Contacto',
    'faqs' => 'FAQ\'s',

    'minecraft_name' => 'Nombre de Minecraft',
    'minecraft_uuid' => 'UUID de Minecraft',
    'what' => 'Qué',
    'recent_searches' => 'Búsquedas recientes',
    'username' => 'Nombre de usuario',
    'uuid' => 'UUID',
    'search' => 'Búsqueda',
    'search_placeholder' => 'Probar',
    'search_placeholder_uuid' => 'Introducir UUID',
    'start_search' => 'Comenzar búsqueda',
    'cancel_search' => 'Cancelar',
    'search_type' => 'Tipo de búsqueda',
    'search_type_all' => 'Todos los resultados',
    'profiles' => 'Perfiles',
    'view_skin' => 'Ver aspecto',
    'edit_skin' => 'Editar aspecto',
    'make_avatar' => 'Crear avatar',
    'find_heads' => 'Buscar cabezas de jugador',
    'no_results_found' => 'No suggestions yet. Hit Enter to look it up.',

    'home' => 'Inicio',
    'help' => 'Ayuda',
    'tools' => 'Herramientas',
    'more-tools' => 'Más herramientas',
    'skin_viewer' => 'Visor de aspectos',
    'avatar_maker' => 'Creador de Avatares',
    'collections' => 'Colecciones',
    'popular_skins' => 'Aspectos Populares',
    'cartoon_skins' => 'Aspectos de caricatura',
    'animal_skins' => 'Aspectos de animales',
    'community' => 'Comunidad',
    'imprint' => 'Imprimir',
    'cookies' => 'Cookies',
    'terms' => 'Términos de servicio',
    'privacy' => 'Política de privacidad',
    'app' => 'Aplicación',
    'mod' => 'Mod',
    'totem' => 'Totems',
    'cube' => 'Cube',
    'new' => 'New',

    'feedback' => 'Opiniones',
    'status' => 'Estado',
    'recent_searches_placeholder' => 'A medida que empieces a buscar, tus búsquedas pasadas se mostrarán aquí.',
    'recent_views_placeholder' => 'Después de visitar algunos perfiles, los que has visitado te mostrarán aquí.',
    'moderate' => 'Moderar',
    'listings' => 'Listados',
    'add' => 'Añadir',

    'theme' => [
        'title' => 'Theme',
        'dark' => 'Oscuro',
        'light' => 'Claro',
        'auto' => 'Auto',
    ],
];
