<?php

return [
    'skins' => 'Skins',
    'avatars' => 'Avatars',
    'editor' => 'Editor',
    'heads' => 'Hoofden',
    'capes' => 'Capes',
    'servers' => 'Servers',
    'achievement' => 'Prestatie',
    'armor' => 'Harnashouder',
    'banners' => 'Banieren',
    'profile' => 'Mijn profiel',

    'generators' => 'Generators',

    'logout' => 'Uitloggen',
    'register' => 'Registreren',
    'login' => 'Inloggen',
    'about' => 'Over',
    'contact' => 'Contact',
    'faqs' => 'Veelgestelde vragen',

    'minecraft_name' => 'Minecraft Naam',
    'minecraft_uuid' => 'Minecraft UUID',
    'what' => 'Wat',
    'recent_searches' => 'Recente zoekopdrachten',
    'username' => 'Gebruikersnaam',
    'uuid' => 'UUID',
    'search' => 'Zoeken',
    'search_placeholder' => 'Probeer',
    'search_placeholder_uuid' => 'Voer UUID in',
    'start_search' => 'Begin met zoeken',
    'cancel_search' => 'Annuleren',
    'search_type' => 'Zoektype',
    'search_type_all' => 'Alle resultaten',
    'profiles' => 'Profielen',
    'view_skin' => 'Bekijk skin',
    'edit_skin' => 'Bewerk skin',
    'make_avatar' => 'Maak een avatar',
    'find_heads' => 'Vind speler hoofden',

    'home' => 'Start',
    'help' => 'Help',
    'tools' => 'Hulpprogramma\'s',
    'more-tools' => 'Meer hulpprogramma\'s',
    'skin_viewer' => 'Skin bekijker',
    'avatar_maker' => 'Avatar maker',
    'collections' => 'Collecties',
    'popular_skins' => 'Populaire skins',
    'cartoon_skins' => 'Tekenfilm skins',
    'animal_skins' => 'Dieren skins',
    'community' => 'Community',
    'imprint' => 'Impressum',
    'cookies' => 'Cookies',
    'terms' => 'Gebruiksvoorwaarden',
    'privacy' => 'Privacybeleid',
    'app' => 'App',
    'mod' => 'Mod',
    'totem' => 'Totems',

    'feedback' => 'Feedback',
    'status' => 'Status',
    'recent_searches_placeholder' => 'Naarmate je begint met zoeken, worden de vorige zoekopdrachten hier getoond.',
    'recent_views_placeholder' => 'Na een aantal profielen te hebben bezocht, worden hier de bezochte profielen getoond.',
    'moderate' => 'Modereren',
    'listings' => 'Listings',
    'add' => 'Toevoegen',

    'theme' => [
        'dark' => 'Donker',
        'light' => 'Licht',
        'auto' => 'Automatisch'
    ],
];
