<?php

return [
    'skins' => 'Skins',
    'skins_profile' => 'Profiel skins',
    'skins_profile_subtitle' => 'Skins van Minecraft profielen',
    'creations' => 'Creaties',
    'creations_subtitle' => 'Skins gedeeld door de community',
    'skin_upload_subtitle' => 'Voeg je creatie toe',
    'skin_tags' => 'Gelabeld',
    'avatars' => 'Avatars',
    'editor' => 'Editor',
    'heads' => 'Hoofden',
    'capes' => 'Capes',
    'servers' => 'Servers',
    'achievement' => 'Prestatie',
    'armor' => 'Harnashouder',
    'banners' => 'Banieren',
    'banner' => 'Banier Editor',
    'banner_gallery' => 'Banier Galerij',
    'profile' => 'Mijn profiel',
    'wallpapers' => 'Achtergronden',

    'generators' => 'Generatoren',

    // Navigation dropdowns
    'feed' => 'Feed',
    'discover' => 'Ontdek',
    'mods' => 'Mods',
    'shaders' => 'Shaders',
    'resource_packs' => 'Resource Packs',
    'modpacks' => 'Modpacks',
    'datapacks' => 'Data Packs',
    'plugins' => 'Plugins',

    'logout' => 'Uitloggen',
    'register' => 'Registreren',
    'login' => 'Inloggen',
    'about' => 'Over',
    'contact' => 'Contact',
    'faqs' => 'Veelgestelde vragen',

    'minecraft_name' => 'Minecraft Naam',
    'minecraft_uuid' => 'Minecraft UUID',
    'what' => 'Wat',
    'recent_searches' => 'Recente zoekopdrachten',
    'username' => 'Gebruikersnaam',
    'uuid' => 'UUID',
    'search' => 'Zoek',
    'search_placeholder' => 'Probeer',
    'search_placeholder_uuid' => 'Voer UUID in',
    'start_search' => 'Begin met zoeken',
    'cancel_search' => 'Annuleren',
    'search_type' => 'Zoektype',
    'search_type_all' => 'Alle resultaten',
    'profiles' => 'Profielen',
    'view_skin' => 'Bekijk skin',
    'edit_skin' => 'Bewerk skin',
    'make_avatar' => 'Maak een avatar',
    'find_heads' => 'Vindt speler hoofden',
    'no_results_found' => 'Nog geen suggesties, Druk Enter om het te bekijken',

    'home' => 'Home',
    'help' => 'Help',
    'tools' => 'Hulpprogramma\'s',
    'more-tools' => 'Meer hulpprogramma\'s',
    'skin_viewer' => 'Skin bekijker',
    'avatar_maker' => 'Avatar maker',
    'collections' => 'Collecties',
    'popular_skins' => 'Populaire skins',
    'cartoon_skins' => 'Tekenfilm skins',
    'animal_skins' => 'Dieren skins',
    'community' => 'Community',
    'imprint' => 'Impressum',
    'cookies' => 'Cookies',
    'terms' => 'Gebruiksvoorwaarden',
    'privacy' => 'Privacybeleid',
    'app' => 'App',
    'mod' => 'Mod',
    'totem' => 'Totems',
    'cube' => 'Kubus',
    'new' => 'Nieuw',

    'boards' => 'Boards',
    'boards_subtitle' => 'Je opgeslagen collecties',

    'feedback' => 'Feedback',
    'status' => 'Status',
    'recent_searches_placeholder' => 'Vorige zoekopdrachten hier getoond.',
    'recent_views_placeholder' => 'Na een aantal profielen te hebben bezocht, worden hier de bezochte profielen getoond.',
    'moderate' => 'Modereren',
    'listings' => 'Listings',
    'add' => 'Toevoegen',

    // Autocomplete types
    'autocomplete' => [
        'profile' => 'Profiel',
        'server' => 'Server',
        'project' => 'Project',
        'skin_tag' => 'Skin Tag',
        'server_category' => 'Server Categorie',
        'modrinth_category' => 'Project Categorie',
    ],

    'theme' => [
        'title' => 'Thema',
        'dark' => 'Donker',
        'light' => 'Licht',
        'auto' => 'Auto',
    ],

    'language' => 'Taal',
];
