<?php

return [
    'auth' => [
        'login' => [
            'title' => 'Welkom bij SkinMC',
        ],
        'register' => [
            'title' => 'Registreer bij SkinMC',
            'subtitle' => 'Aan de slag en maak uw account aan voor volledige toegang.'
        ]
    ],

    'home' => [
        'hero_slogan' => 'Jouw plek voor Minecraft skins.',
        'hero_slogan_alt_1' => 'Everything Minecraft. One place.',
        'hero_slogan_alt_2' => 'Where Minecrafters meet.',
        'hero_cta' => 'Verras me',
        'hero_explore_cta' => 'Verken skins',
        'skin_viewer' => 'Skin bekijker',
        'skin_viewer_detail' => 'Bekijk :count skins',
        'skin_editor' => 'Skin bewerker',
        'skin_editor_detail' => 'Ontwerp je eigen skin',
        'avatar_maker' => 'Avatar generator',
        'avatar_maker_detail' => 'Genereer je aangepaste Minecraft-avatar profielafbeeldingen.',
        'trending' => 'Populair',
        'minecraft_skin' => 'Minecraft skin',
        'favourite' => 'Favoriet',
        'collections' => 'Collecties',
        'collections_detail' => 'Geordende Minecraft skins voor elke gelegenheid',
        'about_skinmc' => 'Over SkinMC',
        'about_find' => 'Vind elke skin',
        'about_find_detail' => 'Gebruik de SkinMC voor elke Minecraft-gebruikersnaam om je volgende nieuwe skin te vinden, te bekijken en te downloaden.',
        'about_download' => 'Downloaden of bewerken',
        'about_download_detail' => 'Heb je een skin gevonden die je leuk vindt? Voeg deze toe aan je favorieten, bewerk of download hem en maak het je eigen skin.',
        'about_platform' => 'Cross-platform',
        'about_platform_detail' => 'Wil je de skin onderweg nemen? Scan de QR-code en sla de afbeelding op je telefoon op voor Minecraft PE.',
        'meta' => [
            'title' => 'Minecraft Skin Bekijker',
            'description' => 'Bekijk en download Minecraft skins, ontdek de beste skins in geordende collecties, controleer de beschikbaarheid van de gebruikersnaam en geschiedenis en nog veel meer!',
        ],
        'recently_viewed' => 'Onlangs bekeken',
        'explore_title' => 'Probeer iets nieuws',
        'explore' => 'Ontdek nieuwe ideeën en hulpprogramma\'s',
        'servers_browse' => 'Blader door servers',
        'servers' => 'Ontdek de beste Minecraft servers',
        'heads' => 'Minecraft Hoofden',
        'head_description' => 'Blader door de Minecraft hoofden database, of maak een nieuw hoofd.',
        'achievement' => 'Prestatie generator',
        'achievement_detail' => 'Creëer je eigen, aangepaste en gepersonaliseerde prestaties.',
        'continue' => 'Doorgaan met browsen'
    ],
    'profile' => [
        'verified' => 'Geverifieerd profiel',
        'minecraft_profile' => 'Minecraft profiel',
        'show_qr_code' => 'QR-code weergeven',
        'favourite' => 'Favoriet',
        'user_title' => ':username\'s Minecraft Skin',
        'user_views' => ':views keer bekeken|:views keer bekeken',
        'uuid' => 'UUID',
        'copy' => 'Kopieer',
        'link' => 'Koppeling',
        'skin_history' => 'Minecraft skin geschiedenis (:skins)',
        'username_history' => 'Gebruikersnaam geschiedenis',
        'username_history_name' => 'Naam',
        'username_history_timestamp' => 'Gewijzigd op',
        'username_history_initial_name' => 'Oorspronkelijk naam',
        'user_downloads' => ':downloads download|:downloads downloads',
        'download_skin' => 'Download skin',
        'apply_skin' => 'Skin toepassen',
        'capes' => 'Capes',
        'claim_profile' => 'Ben jij :username? Claim je profiel om het te verifiëren en aan te passen!',
        'claimed' => 'Geclaimd profiel',
        'meta_description' => 'Bekijk en download :username\'s Minecraft Skin. Zie hun UUID, naam geschiedenis, gedetailleerde statistieken en meer',
        'created_at' => 'Bijgewerkt: :changed_at',
        'skins' => [
            'meta_title' => ':username\'s Minecraft Skin Geschiedenis',
            'meta_description' => 'Bekijk :username\'s Minecraft Skins geschiedenis en eerder gebruikte Skins. Gebruik de geschiedenis om door oude of vroeger gebruikte skins te bladeren, backup en terug te zetten of nieuwe skins te verzamelen.',
            'title' => 'Minecraft Skin geschiedenis'
        ],
        'qr_code' => [
            'meta_title' => ':username\'s QR-code',
            'meta_description' => ':username\'s Aangepaste Minecraft Profiel QR-code'
        ],
        'sub_nav' => [
            'skin' => 'Skin',
            'about' => 'Over',
            'usernames' => 'Gebruikersnamen',
            'head' => 'Hoofd',
            'comments' => 'Reacties'
        ],
        'cape' => 'Cape',
        'elytra' => 'Elytra',
        'nametag' => 'Naamkaart',
        'animation' => 'Animatie',
        'rotation' => 'Rotatie',
        'none' => 'Geen',
        'idle' => 'Idle',
        'walk' => 'Loop',
        'run' => 'Ren',
        'fly' => 'Vlieg',
        'follow' => 'Volg',
        'following' => 'Volgend',
        'unfollow' => 'Niet meer volgen',
        'followers' => 'Volger|Volgers',
        'toast' => [
            'following' => 'Je volgt nu :username!',
            'follow-self-error' => 'Sorry :username, je kunt jezelf niet volgen.',
            'unfollowed' => 'Je volgt :username niet meer'
        ],
        'edit' => 'Profiel bewerken',
        'joined' => 'Lid geworden',
        'role' => 'Role',
        'server-fav-list-empty' => 'Looks like :username hasn\'t got any favourite servers yet. Once :username has saved a server as their favourite, you can see it here.',
        'server-own-list-empty' => 'Looks like :username hasn\'t got any servers yet. Once :username has listed a server, you can see it here.',
        'capes-list-empty' => 'Looks like :username isn\'t wearing any capes yet. Once :username is wearing a cape, you can see it here.',
        'feed-own-list-empty' => 'Looks like you haven\'t posted anything to the feed yet! Once you post, you can see your posts here.',
        'feed-list-empty' => 'Hmm, it seems like :username hasn\'t posted anything to the feed yet. Once :username posts something you can see it here.',
        'following-own-list-empty' => 'Het lijkt erop dat je nog niemand volgt! Zodra je mensen begint te volgen, kun je ze hier zien.',
        'following-list-empty' => 'Hmm, het lijkt erop dat :username niemand volgt. Wanneer :username mensen begint te volgen kun je ze hier zien.',
        'followers-own-list-empty' => 'Wanneer mensen jouw profiel beginnen te volgen, worden ze hier getoond.',
        'followers-list-empty' => 'Hmm, het lijkt erop dat :username door niemand wordt gevolgd. Volg als eerste :username. Zodra er meer mensen volgen, kun je ze hier zien.',
        'render' => 'Renderer',
        '3d' => '3D render',
        '2d' => '2D render',
        'name-history-info' => 'Gebruikersnaam geschiedenis verdwijnt. Mojang heeft de toegang tot de naamgeschiedenis API op 13 september 2022 verwijderd, wat betekent dat een nauwkeurige naamgeschiedenis niet meer beschikbaar is. Als je jouw naamgeschiedenis wilt verbergen, claim dan je profiel en ga naar instellingen om het privé te maken.',
        'edit-skins' => 'Bewerk skin geschiedenis',
        'hide-skin' => 'Verberg skin',
        'show-skin' => 'Toon skin',
        'edit-skin' => 'Bewerk skin',
        'servers' => [
            'title' => ':username\'s servers',
        ],
        'cape-list' => [
            'title' => ':username\'s capes',
        ]
    ],
    'skin' => [
        'meta' => [
            'title' => ':username\'s Minecraft Skin',
            'description' => 'Minecraft skin. Download en bekijk de skin, en kijk welke spelers ook dezelfde skin dragen.',
            'tags' => ':username\'s Minecraft Skin, :username\'s Skin, Minecraft Skin, :username\'s aangepaste Minecraft Skin, Download Skin, Spelers met dezelfde Skin',
        ],
        'title' => ':username\'s Minecraft Skin',
        'head' => 'Hoofd commando\'s',
        'head_info' => 'Te gebruiken met opdrachtblokken',
        'first_wearing' => 'Eerste speler met deze skin gezien:',
        'profiles' => ':profiles profiel|:profiles profielen',
        'profiles_title' => ':profiles profiel met deze skin|:profiles profielen met deze skin',
        'screenshot' => 'Schermafbeelding',
    ],
    'skins' => [
        'meta' => [
            'title' => 'Pagina :current - Alle Minecraft skins',
            'description' => 'Blader door onze :last pagina\'s lijst van :total aangepaste Minecraft skins en download je favoriete volgende skin!',
            'tags' => ':username\'s Minecraft Skin, :username\'s Skin, Minecraft Skin, :username\'s aangepaste Minecraft Skin, Download Skin, Spelers met dezelfde Skin',
            'tags-title' => ':tag Minecraft Skins',
            'tags-description' => 'Browse through our :last pages list of :total :tag Minecraft skins and download your favourite :tag skin!',
            'tags-metatags' => ':tag Minecraft Skin, :tag Skin, Minecraft Skin, :tag Custom Minecraft Skin, Download :tag Skin, Minecraft :tag Skins',
        ],
        'title-skin-tags' => 'Tagged Minecraft Skins',
        'subtitle' => 'Pagina :current van :last van de :total Minecraft skins',
        'subtitle-skin-tags' => 'Page :current of :last from :total Tagged Minecraft Skins',
        'sort_by' => 'Sorteer op',
        'latest' => 'Recente skins',
        'most_profiles' => 'Meest gebruikte skins',
        'profiles_today' => 'Meest gebruikt vandaag',
        'profiles_this_week' => 'Meest gebruikt deze week',
        'profiles_this_month' => 'Meest gebruikt deze maand',
        'default' => 'Standaard sortering',
        'this_month' => 'Deze maand toegevoegd',
        'this_week' => 'Toegevoegd deze week',
        'today' => 'Vandaag toegevoegd',
        'random' => 'Willekeurig',
        'similar' => 'Vergelijkbare skins',
        'no_similar_skins' => 'Nog geen vergelijkbare skins gevonden.',
        'favorite' => ':count favourite|:count favourites',
    ],
    'skin-tags' => [
        'faq' => 'Wat zijn tags?',
        'about' => 'Tags are a way you to add relevant categories to skins. Adding tags allows you to discover more skins you like easily!',
        'guidelines' => [
            'good' => [
                'title' => 'General guidelines for good tags are:',
                'short' => 'Kort',
                'descriptive' => 'Beschrijvend',
                'spelled' => 'Goed gespeld',
            ],
            'bad' => [
                'title' => 'Voeg geen tags toe zoals:',
                'general' => 'Te algemeen',
                'specific' =>  'Te specifiek',
                'too-many-tags' =>  'Should be three separate tags',
                'spelling' => 'Should be :example',
            ],
        ],
        'toast' => [
            'added' => 'Tag ”:tag” added for voting',
            'removed' => 'Tag ”:tag” has been removed',
            'upvote' => 'Upvoted ”:tag”',
            'downvote' => 'Downvoted ”:tag”'
        ],
        'vote' => [
            'up' => 'Upvote',
            'down' => 'Downvote',
            'remove' => 'Remove vote',
        ],
    ],
    'contact' => [
        'contact' => 'Contact',
        'email' => 'Aarzel niet om ons te schrijven naar <a href="mailto:support@skinmc.net">support@skinmc.net</a> voor vragen die je hebt.',
        'faq' => 'We vragen u vriendelijk om eerst de <a href=":link">FAQ pagina</a> te bekijken om te zien of uw vraag daar al beantwoord is.',
        'other' => 'Andere manieren om te verbinden',
        'other_discord' => 'Word lid van de Discord server en maak verbinding met anderen, chat over spellen, deel je favoriete pakketten en krijg hulp van de gemeenschap.',
        'other_twitter' => 'Volg op Twitter om te zien wanneer een nieuwe update of functie wordt uitgebracht, bekijk de skin van de week en meer.',
        'other_instagram' => 'Volg SkinMC op Instagram om coole nieuwe Minecraft skins en afbeeldingen te ontdekken.',
        'other_facebook' => 'Word een fan op Facebook en zie alle berichten waar je kan reageren en met anderen kan praten terwijl je Minecraft-content verkent.'
    ],
    'about' => [
        'intro' => '<span>Jouw</span> <span>platform</span> <span>voor</span> <span>Minecraft</span> <span>Skins.</span>',
        'header_credit' => 'Illustratie "Epische Nether Gevecht" door',
        'info' => 'Houd alles in de gaten.',
        'info_explainer' => 'Bekijk de geschiedenis van de naam van een speler, bekijk hun eerdere skins, voeg ze toe als vriend, download skins en krijg zelfs detailstatistieken.',
        'card_find_title' => 'Vind elke minecrafter',
        'card_find_detail' => 'Ga aan de slag door te zoeken naar een spelers gebruikersnaam of UUID naar jouw keuze.',
        'card_view_title' => 'Bekijk, opslaan & bewerken',
        'card_view_detail' => 'Een skin gevonden die je leuk vindt? Sla deze op door het downloaden of door de editor te gebruiken om het zelf te maken.',
        'card_claim_title' => 'Wordt geverifieerd',
        'card_claim_detail' => 'Koppel je Minecraft-account en claim je profiel om coole nieuwe functies te ontgrendelen!',
        'card_customise_title' => 'Pas uw profiel aan',
        'card_customise_detail' => 'Geverifieerde spelers kunnen hun social media links toevoegen en hun profiel eigen maken.',
        'card_friends_title' => 'Voeg uw vrienden toe',
        'card_friends_detail' => 'Maak verbinding met je vrienden op SkinMC en toon je vriendenlijst op het profiel.',
        'card_history_title' => 'Gebruikersnaam & skingeschiedenis',
        'card_history_detail' => 'Gebruik de geavanceerde zoekopdracht om de gebruikersnaam/skin geschiedenis van een speler te vinden.',
        'founders' => 'De oprichters',
        'founders_cofounder' => 'Cofounder van SkinMC',
        'head_of_design' => 'Manager van het design',
        'head_of_code' => 'Manager van de code',
        'feedback' => 'Stuur ons feedback',
        'faq' => 'Vragen over Minecraft, Skins, en meer? Lees onze FAQs met antwoorden op de meeste gestelde vragen.',
        'faq_link' => 'Bezoek FAQ-centrum',
        'contact' => 'Wil je contact opnemen of heb je meer vragen? Neem direct contact met ons op.',
        'contact_link' => 'Neem contact met ons op',

    ],
    'faq' => [
        'title' => 'FAQs',
        'subtitle' => 'Veelgestelde vragen',
        'help' => 'Meer hulp nodig?',
        'discord' => 'Word lid van de Discord server om met andere Minecraft spelers te chatten.',
        'contact' => 'Neem contact met ons op',
        'q' => [
            'change_skin_t' => 'Hoe verander ik mijn Minecraft Skin?',
            'change_skin' => '
                <p>Om je Skin te veranderen, doet u het volgende:</p>
                <ol>
                    <li>Bezoek <a href="https://my.minecraft.net/nl-nl/login/">https://my.minecraft.net/nl-nl/login/</a> en meld u aan met uw Mojang account.</li><li>Eenmaal aangemeld, selecteer <b>"Skin"</b> in het linkermenu.</li><li>Kies dan een model dat je verkiest en upload een Skin van je eigen aard.</li>
                </ol>',
            'change_username_t' => 'Hoe wijzig ik mijn Minecraft gebruikersnaam?',
            'change_username' => '
                <p>Om uw gebruikersnaam te wijzigen, doet u het volgende:</p>
                <ol>
                    <li>Bezoek <a href="https://account.mojang.com/login" target="_blank" rel="nofollow">https://account.mojang.com/login</a> en log in met uw Mojang account.</li>
                    <li>Vind je Minecraft profielnaam en druk op <b>"(Change)"</b> knop</li>
                    <li>Op de volgende pagina, voer je gewenste nieuwe gebruikersnaam in.</li>
                    <li>Uiteindelijk, Bevestig de wijzigingen door uw wachtwoord in te voeren en op "Change name." te drukken.</li>
                </ol>',
            'dl_t' => 'Hoe download ik iemands Minecraft Skin?',
            'dl' => '
                <p>Om een Minecraft skin te downloaden doe je het volgende:</p>
                <ol>
                    <li>Druk op de zoekbalk en voer de gebruikersnaam in van de speler waarvan je de skin wilt downloaden.</li>
                    <li>Op de profielpagina kunt u de skin bekijken</li>
                    <li>Klik op de <strong>Download Skin</strong> knop onder de voorvertoning</li>
                </ol>',
            'submit_q' => 'Hoe kan ik een skin indienen bij een collectie?',
            'submit_a' => '<p>Vul het volgende formulier in met de gebruikersnamen en de categorie waarvan je de collecties wilt toevoegen. <a href="https://forms.gle/f4Jh5RpGfsHAZ5xE8" target="_blank">Inzending formulier</a>',
            'mcpe_t' => 'Kan ik de skin gebruiken bij Minecraft PE?',
            'mcpe' => '
<p>Ja. Om Skins te gebruiken in Minecraft Pocket Edition doe je het volgende:</p>
                <ol>
                    <li>Open SkinMC.net op je mobiel en klik op de zoekbalk.</li>
                    <li>Voer de gebruikersnaam in van de speler waarvan je de skin wilt downloaden.</li>
                    <li>Klik op de <strong>Download Skin</strong> knop onder de voorvertoning</li>
                    <li>Open Minecraft PE en klik op <strong>Profiel</strong> aan de rechterkant</li>
                    <li>Klik op de <strong>+</strong> of bewerk karakter en ga naar de "classic skins tab"</li>
                    <li>Klik op "owned", daarna op "import" en kies dan "choose new skin"</li>
                </ol>',
            'change_times_t' => 'Hoe vaak kan ik mijn gebruikersnaam wijzigen?',
            'change_times' => '<p>Je kunt je Minecraft Gebruikersnaam één <strong>keer</strong> per <strong>30 dagen</strong> veranderen.</p>',
            'available_t' => 'Wanneer kan mijn gebruikersnaam na het veranderen ervan voor anderen beschikbaar zijn om het op te eisen?',
            'available' => '<p>Als u naar uw vorige gebruikersnaam wilt gaan, kunt u deze <strong>na 30 dagen</strong> terugzetten. Alle anderen moeten <strong>7 dagen</strong> extra wachten (37 dagen na verandering) voordat ze je oude gebruikersnaam kunnen opeisen. </p>',
            'username_history_t' => 'Kunt u mijn gebruikersnaam geschiedenis alsjeblieft verwijderen?',
            'username_history' => '
                <p>Omdat de gebruikersnaam geschiedenis data van Mojang is, de gebruikersnaam geschiedenis kan niet worden verwijderd. Mojang heeft eerder gezegd dat het de bedoeling was dat eerdere gebruikersnamen kunnen worden gezien¹: en dat ze voor het publiek een rechtstreekse methode bieden om toegang te krijgen tot deze informatie².</p>
                <p class="font-14">¹<a href="https://help.minecraft.net/hc/en-us/articles/360034636712-Minecraft-Usernames" target="_blank" rel="noreferrer">https://help.minecraft.net/hc/nl-nl/articles/360034636712-Minecraft-Usernames</a></p>
                <p class="font-14 mb-0">²<a href="https://twitter.com/dinnerbone/status/554739042529849345" target="_blank" rel="noreferrer">https://twitter.com/dinnerbone/status/554739042529849345</a> (Tweet gearchiveerd 2 jaar geleden: <a href="http://archive.is/TeAyj" target="_blank" rel="noreferrer">http://archive.is/TeAyj</a>)
                </p>',
        ],
    ],
    'avatars' => [
        'start' => [
            'title' => 'Maak je eigen Minecraft avatar',
            'subtitle' => 'Gebruik de Minecraft avatar generator om een leuke avatar van elke skin te maken!',
            'avatar_face' => 'Gezicht stijl avatar',
            'avatar_bust' => 'Borst stijl avatar',
            'avatar_cube' => 'Kubus stijlavatar',
            'avatar_head3d' => 'Aangepast 3D hoofd',
        ],
        'user' => [
            'title' => 'Kies skin',
            'subtitle' => 'Voer de Minecraft gebruikersnaam in voor de avatar die u wilt genereren',
            'form_label' => 'Minecraft gebruikersnaam',
            'form_submit' => 'Doorgaan',
        ],
        'output' => [
            'title' => 'Voorbeeldweergave en opslaan',
            'subtitle' => 'Veel plezier met je nieuwe Minecraft avatar',
            'download_info' => 'Gelukkig met het resultaat? Begin met het gebruiken van je nieuwe avatar door het hier te downloaden',
            'download_button' => 'Download avatar',
            'avatar_style' => 'Avatar stijl',
            'skin_username' => 'Skin gebruikersnaam',
            'change' => 'Verander',
            'generate' => 'Genereer',
            'avatar_colour' => 'Achtergrondkleur',
            'avatar_colour_palette' => 'Kleur palet',
            'avatar_colour_basic' => 'Basis',
        ],
        'meta' => [
            'title' => 'Minecraft Avatar Generator',
            'description' => 'Minecraft Avatar Maker: maak aangepaste Minecraft-profielfoto\'s met je Minecraft skin',
        ],
    ],
    'totem' => [
        'title' => 'Aangepaste Minecraft Totem',
        'subtitle' => 'Gebruik de Minecraft Totem generator om een aangepast bronpakket te maken met een Totem of Undying van elke skin.',
        'download_info' => 'Blij met het voorbeeld? Kies je Minecraft-versie om je aangepaste bronpakket op te slaan:',
        'meta' => [
            'title' => 'Minecraft Aangepaste Totem Generator',
            'description' => 'Custom Minecraft Totems: generate and create a custom Minecraft Resource Pack with a Totem of Undying using your or any other players Minecraft skin.',
        ],
        'type' => [
            'mini' => 'Een mini-versie van je skin!',
            'full' => 'Een volledige versie van je skin!',
            'model3d' => 'Een 3D-model van je skin!',
            'add_designs' => 'Want to see more designs? Submit your design suggestion here:'
        ]
    ],
    'achievement' => [
        'header' => [
            'title' => 'Maak je eigen Minecraft Prestatie',
            'subtitle' => 'Gebruik de Minecraft Prestatiegenerator om je eigen aangepaste prestatie te maken en gebruik je vooruitgang bij alles wat je wilt!',
        ],
        'generator' => [
            'yellow_text' => 'Gele tekst',
            'white_text' => 'Witte tekst',
            'choose_icon' => 'Kies pictogram',
            'face' => 'Minecraft gezicht in plaats van pictogram',
            'form_submit' => 'Download',
            'form_label' => 'Minecraft gebruikersnaam',
            'download' => 'Download',
            'embed' => 'Insluiten',
            'embed_copy' => 'Kopieer',
        ],
        'meta' => [
            'title' => 'Minecraft Prestatie Generator',
            'description' => 'Genereer aangepaste Minecraft Prestaties en Prestaties met de Prestatie Maker. Download de afbeelding direct, gebruik het in forum handtekeningen, insluiten met HTML of BB code en meer',
        ],
    ],
    'armor' => [
        'header' => [
            'title' => 'Minecraft Harnashouder Maker',
            'subtitle' => 'Genereer en maak je eigen aangepaste Minecraft Harnashouders. Maak verschillende poses, posities, plaats items en nog veel meer.',
        ],
        'meta' => [
            'title' => 'Minecraft Harnashouder Maker',
            'description' => 'Gemakkelijk genereren en maken van aangepaste Minecraft Harnashouders. De editor helpt je om verschillende poses, posities, items plaatsen, aangepaste skins en nog veel meer te maken.',
        ],
    ],
    'banner' => [
        'editor' => [
            'header' => [
                'title' => 'Minecraft Banner Editor',
                'subtitle' => 'Ontwerp en maak je eigen Minecraft Banners. Deze kunnen gebruikt worden om je wereld te versieren of ook vaak gebruikt worden als <a href="https://optifine.net" target="_blank" rel="nofollow">Optimfine</a> capes.',
            ],
            'meta' => [
                'title' => 'Minecraft Banner Maker',
                'description' => 'Maak en ontwerp jouw eigen Minecraft Banners ontwerpen met alle patronen en kleuren van het spel! Deze kunnen gebruikt worden om uw wereld te versieren of gedragen worden als een Optifine Cape met behulp van de Banier Cape. U kunt codes voor banieren of schilden genereren.',
            ],
        ],
        'gallery' => [
            'header' => [
                'title' => 'Minecraft Banner Gallerij',
                'subtitle' => 'Blader door de galerij van :count aangepaste ontworpen Minecraft Banners. U kunt een Banier als cape gebruiken om uw Minecraft skin uniek te maken, of gebruik een Banier als een vlag om je wereld te decoreren.',
            ],
            'meta' => [
                'title' => 'Minecraft Banner Gallerij',
                'description' => 'Blader door de galerij van :count aangepaste ontworpen Minecraft Banieren. U kunt een Banier als cape gebruiken om uw Minecraft skin uniek te maken, of gebruik een Banier als een vlag om je wereld te decoreren.',
            ],
        ],
    ],
    'search' => [
        'meta' => [
            'title' => 'Zoekresultaten: :search',
        ],
        'title' => 'Zoekresultaten',
        'results' => 'Pagina :current voor :count resultaat|Pagina :current van ongeveer :count resultaaten ',
        'time' => '(:time seconden)',
        'username_available' => 'Gebruikersnaam beschikbaar*',
        'username_unavailable' => 'Gebruikersnaam is niet beschikbaar',
        'username_status' => 'Status',
        'username_status_available' => 'Beschikbaar*',
        'username_status_unavailable' => 'Onbeschikbaar',
        'username_searches' => 'Zoekopdrachten',
        'username_searches_count' => ':count / dag',
        'username_available_disclaimer' => '*Tenzij de naam tijdelijk of permanent is verbannen door Mojang.',
        'no_results' => 'Geen profielen gevonden. Probeer te zoeken met UUID door het zoektype te wijzigen.',
        'no_results_tags' => 'No tagged skins found. Try searching for other tags such as "blue", "girl", "fox", etc...',
        'again' => 'Opnieuw zoeken',
        'sorry' => 'Sssssssorry...',
        'view_profile' => 'Profiel bekijken',
    ],
    'collection' => [
        'title' => 'Minecraft skin collectie',
        'subtitle' => 'Blader door onze geordende collectie van Minecraft skins.',
        'filters' => 'Filters',
        'title_trending' => 'Populair',
        'title_all' => 'Alle Minecraft Skins',
        'skin_tags' => 'Gelabelde skins',
        'filters_skin_type' => 'Soort skin',
        'filter_skin_type_steve' => 'Steve soort',
        'filter_skin_type_alex' => 'Alex soort',
        'cancel' => 'Annuleer',
        'apply' => 'Toepassen',
        'username_minecraft_skin' => ':username\'s Minecraft skin',
        'user_downloads' => '<span class="fw-500">:downloads</span> download|<span class="fw-500">:downloads</span> downloads',
    ],
    'favourites' => [
        'title' => 'Favorieten',
        'subtitle' => 'Bekijk en beheer skins en servers die je hebt opgeslagen voor later in je favorietenlijst',
        'sort' => 'Sorteer op',
        'toast' => [
            'added' => 'Added to your favourites list',
            'removed' => 'Removed from your favourites list'
        ],
        'skins' => [
            'button' => 'Skins',
            'empty_headline' => 'Nog geen favoriete skins',
            'empty_subtitle' => 'Je hebt nog geen skins opgeslagen in je favorietenlijst. Bezoek de serverpagina en ontdek je volgende favorieten!',
            'empty_browse' => 'Blader door skins',
            'meta' => [
                'title' => 'Mijn favoriete skins',
                'description' => 'Mijn favoriete opgeslagen Minecraft skins',
            ],
        ],
        'servers' => [
            'button' => 'Servers',
            'empty_headline' => 'Nog geen favoriete servers',
            'empty_subtitle' => 'Je hebt nog geen servers opgeslagen in je favorietenlijst. Bezoek de serverpagina en ontdek je volgende favorieten!',
            'empty_browse' => 'Blader door servers',
            'meta' => [
                'title' => 'Mijn favoriete servers',
                'description' => 'Mijn favoriete Minecraft servers',
             ],
        ],

    ],
    'cape' => [
        'editor' => [
            'title' => 'Minecraft cape bewerker',
            'subtitle' => 'Use the Minecraft cape editor to create your very own custom designed cape.',
            'meta' => [
                'title' => 'Minecraft Cape Bewerker',
                'description' => 'Use the Minecraft Cape Editor to create your very own custom designed cape.',
            ],
        ],
        'list' => [
            'title' => 'Minecraft capes',
            'subtitle' => 'Officiële capes van Minecraft zijn herdenkingsvoorwerpen en worden gedragen als aanvulling op de spelers skin. Ze kunnen ook het uiterlijk veranderen als een elytra wordt gedragen.',
            'meta' => [
                'title' => 'Minecraft Capes Lijst',
                'description' => 'Minecraft cape lijst: Bekijk alle officiële Minecraft capes met inbegrip van Mojang, Minecon, Persoonlijke, Speciale en gepersonaliseerde capes',
            ],
        ],
        'detail' => [
            'title' => ':cape Cape',
            'info' => 'Cape informatie',
            'profile_list' => 'Profielen met deze cape',
            'profiles' => ':profiles profiel|:profiles profielen',
            'meta' => [
                'title' => ':cape Minecraft Cape',
                'description' => 'Bekijk de :cape Minecraft Cape en zie spelers die het dragen!',
            ],
        ],
        'list-custom' => [
            'title' => 'Custom Minecraft Capes',
            'description' => 'Browse and view custom capes which have been created and are used by SkinMC members.'
        ]
    ],
    'servers' => [
        'title' => 'Minecraft servers',
        'subtitle' => 'Blader en ontdek minecraft servers',
        'all' => 'Alle servers',
        'manage_your_servers' => 'Beheer jouw servers',
        'add_new_server' => 'Nieuwe server toevoegen',
        'filters' => [
            'trending' => 'Populair',
            'updated' => 'Bijgewerkt',
            'new' => 'Nieuw',
            'most_viewed' => 'Meest bekeken',
            'top_voted' => 'Top gestemd',
            'sorting' => 'Sortering',
            'sort_by_latest' => 'Sorteer op nieuwste',
            'sort_by_oldest' => 'Sorteer op oudste',
            'categories' => 'Categorieën',
            'server_location' => 'Server locatie',
            'show_results' => 'Toon resultaten',
            'show_more' => 'Toon meer',
            'show_less' => 'Toon minder',
            'clear_filters' => 'Verwijder filters',
            'reviews' => 'Beoordelingen',
            'sort_by_highest_rating' => 'Sorteer op de hoogste beoordeling',
            'sort_by_lowest_rating' => 'Sorteer op de laagste beoordeling',
            'bedrock_and_java_support' => 'Bedrock en Java ondersteuning'
        ],
        'review-count' => ':count Beoordeling|:count Beoordelingen',
        'meta' => [
            'title' => 'Minecraft Server Lijst',
            'description' => 'Blader en verken de Minecraft Servers lijst om de beste Minecraft server te vinden! Filter op de laatste, meest populaire en nog veel meer',
        ],
        'reviews' => [
            'meta' => [
                'title' => 'Schrijf een beoordeling',
            ],
            'editing' => 'You\'re editing your review from :date. Would you like to delete your review instead?',
            'welcome' => 'Hallo :username. Hoe was je algehele ervaring met :servername?',
            'subtitle' => 'Leave an overall score of your past experience with the server.',
            'scale' => [
                'great' => 'Fantastisch',
                'good' => 'Goed',
                'okay' => 'Oké',
                'meh' => 'Matig',
                'bad' => 'Slecht',
            ],
            'rate-experience' => 'Next, rate your experience in these areas',
            'overall' => 'Overall',
            'server-team' => 'Server team',
            'community' => 'Community',
            'experience' => 'Ervaring',
            'availablility' => 'Uptime en beschikbaarheid',
            'shop' => 'Shop',
            'write-review-title' => 'Schrijf een beoordeling',
            'write-review-subtitle' => 'Leave a few notes, you can highlight what you enjoyed, what made your experience special, or offer a few suggestions.',
            'write-review-helper' => 'Write a server review to share your experience with new players, and help the server owners with feedback.',
            'write-review-tips' => 'Hier zijn enkele tips',
            'submit-title' => 'Klaar om je beoorderling te verzenden?',
            'submit-subtitle' => 'Bijna klaar!',
            'submit-review' => 'Verzend mijn review',
            'back' => 'Terug',
            'continue' => 'Ga verder',
            'delete-title' => 'Are you sure you would like to delete your review?',
            'tos-checkbox-part-1' => 'By submitting this form you accept SkinMC\'s Terms of Service, Privacy Policy, and Community Guidelines. You also confirm that all of the information is accurate, and follows the',
            'tos-checkbox-part-2' => 'review guidelines.',
            'tos-checkbox-part-3' => 'Your review will be published after submission, but can be subject to review.'
        ],
        'slots' => 'Slots',
        'empty-helper' => 'You can try to do another search or',
        'empty' => 'Hmm it\'s still empty here.',
        'verified' => 'Geverifieerd',
        'review_translate_show_original' => 'Show original',
        'review_translate' => 'Vertaal recensie',
        'description_translate' => 'Vertaal omschrijving',
        'create' => [
            'welcome' => 'Welkom',
            'basics' => 'Basics',
            'categories' => 'Categorieën',
            'social_links' => 'Sociale links',
            'trailer_video' => 'Trailer video',
            'images' => 'Afbeeldingen',
            'images_description' => 'You can upload photos afterwards, to showcase what your server offers.',
            'submit' => 'Indienen',
            'lets_get_your_server_added' => 'Let\'s get your server added.',
            'basics-subtitle' => 'Let people know what your server is about.',
            'description' => 'Omschrijving',
            'description_tips' => 'Hier zijn enkele tips',
            'description_hint' => 'Write a good description for your server to attract new players.',
            'categories-subtitle' => 'Choose some categories for your server',
            'missing-category' => 'Missing a category?',
            'social_links_description' => 'Where can players connect with your server on social media?',
            'trailer_video_description' => 'Showcase your server with a YouTube video.',
            'trailer_video_hint' => 'Paste the video URL or ID:',
            'ready_to_submit_your_server' => 'Ready to submit your server?',
            'review-hint' => 'After submission the team will carefully review your server listing application. Then upon decision, your server will be published, or changes requested before going live.',
            'terms' => [
                'part-1' => 'By submitting this form you are authorised to accept SkinMC\'s Terms of Service, Privacy Policy, and Community Guidelines. You also confirm that all of the information above is accurate, you have properly followed the',
                'part-2' => 'server requirements for setup',
                'part-3' => ', and that the Minecraft server is owned and managed by the entity you are representing.'
            ],
            'submit-application' => 'Aanvraag verzenden',
            'video-id-helper' => [
                'part-1' => 'The video ID is the string of numbers and letters after',
                'part-2' => 'For example if your video url is',
                'part-3' => ', then your video ID would be'
            ],
            'welcome_description' => 'In this step, we\'ll get started on adding your server. Tell us a bit about it, write a description, and in the next step you can upload some images.'
        ],
        'copy_server_ip' => 'Kopieer server IP',
        'all_minecraft_servers' => 'Alle Minecraft Servers',
        'promo' => [
            'title' => 'Host jij een Minecraft Server?',
            'ready_to_list_your_server' => 'Klaar om jouw server te vermelden?',
            'everything_you_need' => 'Everything you need to grow your server',
            'list_your_server' => 'List your server',
            'list_your_server_description' => 'Create a listing for your server, add photos, social media and more.',
            'find_players' => 'Find players',
            'find_players_description' => 'Find and reach new players to join your server and grow your community.',
            'get_reviews' => 'Get reviews',
            'get_reviews_description' => 'Ask your community to review your server, and reward them in game.',
            'why_list_on_skinmc' => 'Why you should list your Server on SkinMC',
            'others' => 'Others',
            'quality_check_and_confirmation' => 'Quality check and confirmation',
            'quality_check_description' => 'Our team reviews every server to ensure quality.',
            'verified_players' => 'Reviews from verified Minecraft players',
            'verified_players_description' => 'Collect authentic player reviews from legitimate accounts with Votifier integration.',
            'international' => 'International',
            'international_description' => 'With translation features your listing is available to more players.',
            'server_listing_page' => 'Powerful Server listing page',
            'server_listing_page_description' => 'Add photos, description texts, youtube videos, and highlight why players should join your server.',
            'social_connections' => 'Social media connections',
            'social_connections_description' => 'Connect your Servers social accounts and show new players where they can find you.',
            'verified_badge' => 'Verification badge',
            'verified_badge_description' => 'Authentic servers can apply for a verification badge.',
            'owner_profile' => 'Owner profile',
            'owner_profile_description' => 'Add a personal touch, by completing your custom profile.',
            'categories' => 'Categorieën',
            'categories_description' => 'Different categories to make it easier to find your server.',
            'vote' => 'Vote',
            'vote_description' => 'Ask users to vote for your server.',
            'fair_listings' => 'Fair listings',
            'fair_listings_description' => 'Server listings can not be artificially boosted in results on SkinMC.',
            'support' => '24 uur ondersteuning',
            'support_description' => 'Do you need help or have questions? You can always reach out and receive a fast reply.',
            'custom_features' => 'Custom features',
            'custom_features_description' => 'Missing a feature for your server? Open a ticket, and we\'ll implement it.',
            'faq' => [
                'title' => 'Answers to your questions',
                'suited-question' => 'Is my Minecraft Server suited for SkinMC?',
                'suited-answer' => 'Minecraft Players on SkinMC love to discover new experiences, content and engage with communities. On the platform you\'ll find a large variety of different, unique, fun Minecraft servers. From a large network to even a small survival server, it can make someones day!',
                'get-started-question' => 'How do I get started?',
                'get-started-answer' => 'Adding your Minecraft Server to the SkinMC Server List is very easy! You will first need to create an account, if you haven\'t already, and then follow the setup guide to get your server listed. Add a few photos and a nice description, and your server will be published in no time!',
                'players-question' => 'How can I get more players on my Minecraft Server?',
                'players-answer' => 'Building a community is the most crucial part of a long lasting Minecraft Server. Use the Minecraft Server List on SkinMC to find a new audience and continue to build your community. Ask your players to recommend your Server, or share your listing on social media platforms. Collecting good reviews can also play an important role to a great Server listing presence that attracts new players.',
                'more-question' => 'I have more questions. Where can I get help?',
                'more-answer' => 'You can reach out to SkinMC at any time, 24 hours, by using either the help button, the help desk, or by joining the Discord server.'
            ],
            'ready_to_list_description' => 'Add your Minecraft Server to the SkinMC Server List in just a few minutes. If you need any help, you can reach out around the clock and receive answers quickly.'
        ],
        'manage' => [
            'index' => [
                'welcome' => 'Welkom terug, :username',
                'your_servers' => 'Jouw servers',
                'reviews_today' => 'Reviews today',
                'no_reviews_today' => 'No reviews today',
                'no_reviews_text' => 'Your servers haven\'t received any reviews today. Why not ask your players to leave one?',
                'tips' => [
                    'title' => 'Tips',
                    'description-title' => 'Write a good server description',
                    'description-body' => 'Helpful tips and advice to write a great server description.',
                    'images-title' => 'Adding server images',
                    'images-body' => 'Make your server listing stand out with great images.'
                ]
            ],
            'listings' => [
                'title' => 'Your Minecraft servers (:count)'
            ],
            'insights' => [
                'title' => 'Insights'
            ],
            'edit_server' => 'Bewerk server',
            'listing' => 'Listing',
            'to_do' => 'To do',
            'last_update' => 'Last update',
            'add_more_photos_to_publish' => 'Add more photos to publish',
            'looks_empty_here' => 'Looks empty here.',
            'get_started_by_adding_a_new_server' => 'Get started by adding a new server?'
        ],
        'status' => [
            'approved' => 'Goedgekeurd',
            'pending_approval' => 'Wachten op goedkeuring',
            'published' => 'Gepubliceerd',
            'in_review' => 'In beoordeling'
        ]
    ],
    'editor' => [
        'import' => [
            'title' => 'Skin importeren',
            'import_by_username' => 'Importeer via gebruikersnaam',
            'import_button' => 'Importeer',
            'drag' => 'Sleep een skin naar hier of klik',
            'click' => 'Afbeeldingen selecteren'
        ],
        'download' => [
            'error' => [
                'no-data' => 'No skin data was provided. Please try again.',
                'invalid-format' => 'The skin data format is invalid. Please try again.',
                'invalid-data' => 'The skin data is corrupted. Please try again.',
                'generic' => 'Something went wrong while downloading your skin. Please try again.',
            ],
        ],
        'draw' => 'Teken',
        'eyedropper' => 'Eyedropper',
        'fill' => 'Fill',
        'move' => 'Move',
        'decrease_brightness' => 'Decrease brightness',
        'increase_brightness' => 'Increase brightness',
        'erase' => 'Erase',
        'undo' => 'Step back (CTRL+Z)',
        'redo' => 'Step forward (CTRL+Y)',
        'default_view' => 'Default view',
        'zoom_in' => 'Zoom in (CTRL +)',
        'zoom_out' => 'Zoom out (CTRL -)',
        'saved' => 'Laatst opgeslagen zojuist',
        'saving' => 'Automatisch opslaan...',
        'save_error' => 'Er is een fout opgetreden',
        'new_skin' => 'New skin',
        'previous_skins' => 'Previous skins',
        'backed_up_title' => 'Automatically saved skins',
        'backed_up_info' => 'Temporarily backed up to your local storage.',
        'backed_up_empty_title' => 'It\'s empty here',
        'backed_up_empty_info' => 'Once you start editing skins you\'ll see your 32 last edited skins here.',
        'backed_up_skins_count' => 'of 32 skin backups used',
        'backed_up_skins_count_info' => 'You can back up to up 32 skins. Once you reach 32 skins an older skin will be replaced with a new one.',
        'layers' => 'Lagen',
        'body' => [
            'title' => 'Lichaam',
            'overlay' => 'Overlay',
            'head' => 'Hoofd',
            'torso' => 'Romp',
            'l_arm' => 'Linkerarm',
            'r_arm' => 'Rechterarm',
            'l_leg' => 'Linkerbeen',
            'r_leg' => 'Rechterbeen',
        ],
        'model' => 'Model',
        'steve' => 'Steve',
        'alex' => 'Alex',
        'stance' => [
            'title' => 'Positie',
            'default' => 'Standaard',
            'walk' => 'Loop',
            'run' => 'Ren',
            'hug' => 'T-pose',
            'fly' => 'Vlieg',
        ],
        'fullscreen' => 'Fullscreen',
        'fullscreen_exit' => 'Exit fullscreen',
        'grid' => 'Raster',
        'show_grid' => 'Raster weergeven',
        'download' => [
            'title' => 'Opslaan & Downloaden',
            'subtitle' => 'SkinMC Account',
            'description' => 'Wil je een gratis SkinMC-account maken om je skin en toekomstige skins in de cloud op te slaan?',
            'start_description' => 'Start de download direct zonder op te slaan in de cloud',
            'start' => 'Download skin',
        ],
        'help' => [
            'title' => 'Minecraft Skin Bewerker',
            'about' => 'Create and edit your custom Minecraft Skin easily with the SkinMC Editor. You can choose between Steve and Alex models, import skins from a file or username, and create your very own Minecraft Skin.',
            'draw' => 'Draw using the pen tool. Select a colour from the swatch to use with it.',
            'eyedropper' => 'Use the eyedropper to select a colour from your skin and add it to your current palette.',
            'fill' => 'Fill entire areas of your skin using the fill tool. Select a colour before using fill.',
            'move' => 'Pan and move around the skin editor canvas with the move tool.',
            'decrease_brightness' => 'Decrease the brightness of the currently active colour.',
            'increase_brightness' => 'Increase the brightness of the currently active colour.',
            'erase' => 'Erase pixels drawn on the secondary overlay layer.',
        ],
    ],
    'account' => [
        'level' => 'Level',
        'level_history' => 'Level geschiedenis',
        'xp' => 'XP',
        'my_xp' => 'Mijn XP',
        'xp_to_next_level' => ':xp XP voor het volgende level',
        'xp_info' => 'Wat is XP?',
        'xp_info_tooltip' => 'XP is earned for various activities such as adding tags to skins, inviting friends, commenting, and much more. With each XP earned you can level up and unlock cool things!',
        'settings' => [
            'title' => 'Account',
            'show_profile' => 'Ga naar profiel',
            'friends' => 'Vrienden',
            'friends_detail' => 'Blijf verbonden door gebruik te maken van je vriendenlijst op SkinMC.',
            'security' => 'Beveiliging',
            'security_detail' => 'Werk uw inlogwachtwoord bij en houd uw account veilig',
            'social' => 'Sociale media accounts',
            'social_detail' => 'Pas je profiel aan door je sociale media toe te voegen',
            'link' => 'Minecraft account koppelen',
            'link_detail' => 'Koppel je Minecraft-account en claim je profiel.',
            'logout' => 'Wil je je uitloggen uit je SkinMC account?',
            'automatic_backups' => 'Automatic skin backups',
            'automatic_backups_info' => 'Als SkinMC plus lid worden jouw skins elke dag geback-upt.',
        ],
        'capes' => [
            'title' => 'SkinMC Minecraft Cape',
            'description' => 'Draag elke cape die je wilt in-game gratis met SkinMC Capes.',
            'drop' => 'Sleep een cape hierheen',
            'drop-hint' => 'Afmetingen 64x32px',
            'select' => 'Selecteer afbeelding',
            'upload-cape' => 'Upload & gebruik cape',
            'save-and-use' => 'Opslaan & gebruiken',
            'uploaded-cape' => 'Geüploade cape',
            'no-cape' => 'Geen cape',
            'remove-cape' => 'Verwijder cape',
            'download' => 'Download de SkinMC Mod om je eigen cape en die van andere spelers te zien in-game.',
            'learn-more' => 'Lees meer',
            'link-account' => 'Koppel je Minecraft-account om een cape te uploaden.',
            'updated' => 'Jouw cape is bijgewerkt!',
            'removed' => 'Jouw cape is verwijdered.',
            'active' => 'Jouw cape is geactiveerd!'
        ],
        'favourite' => 'Favoriet',
        'remove_favourite' => 'Verwijder favoriet',
        'added_to_favourites' => 'Aan favorieten toegevoegd',
        'removed_from_favourites' => 'Removed from favourites',
        'welcome' => 'Leuk je te zien!',
        'view-profile' => 'Mijn profiel bekijken',
        'security' => [
            'title' => 'Beveiliging',
            'email' => 'E-mailadres',
            'email-title' => 'Werk uw e-mailadres bij.',
            'save' => 'Opslaan',
            'password' => 'Wachtwoord',
            'password-title' => 'Wijzig uw wachtwoord op elk gewenst moment.',
            'social-provider' => 'To update your account information, such as your password, please visit your login provider:',
            'social-provider-email' => 'Your associated email address with your login provider',
            'social-provider-connected' => 'Currently connected login providers',
            'current-password' => 'Huidig wachtwoord',
            'forgot' => 'Wachtwoord vergeten?',
            'edit' => 'Bewerken',
            'delete' => 'Verwijder mijn account',
            'account-deletion' => 'Verwijder je SkinMC account.',
            'delete-info' => 'Please confirm to continue',
            'delete-confirmation' => 'Deleting your account is irreversible. All your personal information and content such as posts, favourites, uploaded capes, customisations, etc. will be deleted and can not be recovered.',
            'delete-confirmation-info' => 'Enter your password to continue',
            'yes-confirm-delete' => 'Yes, confirm delete',
            'account-successfully-deleted' => 'Your account and data has been successfully deleted.'
        ],
        'social' => [
            'title' => 'Sociale accounts',
            'edit' => 'Bewerken',
            'save' => 'Opslaan',
            'link-account' => 'Link your Minecraft account to SkinMC to display your social links on your profile.',
            'finish-setup' => 'Finish setup',
            'connect-account' => 'Koppel uw accounts',
            'connect-description' => 'Choose which accounts you wish to connect and unlock special SkinMC integrations.',
            'empty' => 'Geen accounts toegevoegd',
            'empty-description' => 'Your social media accounts will show up here and on your public profile. Once added they will add more personalisation to your page as well as enable integrations.',
            'connect' => 'Koppel',
            'username' => 'gebruikersnaam',
            'spotify' => 'Add your Spotify username to show your Spotify information on your profile.',
            'discord' => 'Enter your Discord username and number to display your Discord information on your SkinMC profile.',
            'youtube' => 'Add your YouTube channel to SkinMC which will display your YouTube channel on your profile.',
            'youtube-format' => 'Use the following format depending on your channel link:',
            'twitter' => 'Enter your X (formerly Twitter) username to display it on your profile.',
            'bluesky' => 'Enter your Bluesky handle e.g. username.bsky.social to display your Bluesky profile on your profile.',
            'twitch' => 'Enter your Twitch username to display your Twitch channel on your profile.',
            'reddit' => 'Enter your Reddit username to display your Reddit profile on your profile.',
            'github' => 'Enter your GitHub username to display your GitHub profile on your profile.',
            'telegram' => 'Enter your Telegram username to display your Telegram link on your profile.',
            'tiktok' => 'Enter your TikTok username to display your TikTok profile on your profile.',
            'snapchat' => 'Enter your Snapchat username to display your Snapchat profile on your profile.',
            'instagram' => 'Enter your Instagram username to display your Instagram profile on your profile.',
            'facebook' => 'Enter your Facebook username to display your Facebook profile on your profile.',
            'includes_skinmc_plus_benefits' => 'Includes SkinMC plus benefits',
        ],
        'recover' => [
            'title' => 'Herstel je account',
            'subtitle' => 'Voer uw nieuwe wachtwoord in en bevestig het om het herstellen van uw account te voltooien.',
            'new_password' => 'Nieuw wachtwoord',
            'repeat_new_password' => 'Herhaal nieuw wachtwoord',
            'submit' => 'Account herstellen',
        ],
        'customise' => [
            'title' => 'Pas uw profiel aan',
            'description' => 'Add your social media, choose an emoji, set your location and more',
            'information' => 'Informatie',
            'preview' => 'Voorbeeld',
            'location' => [
                'title' => 'Locatie',
                'description' => 'Choose which location you would like to add to your profile.',
            ],
            'biography' => [
                'title' => 'Over jezelf',
                'description' => 'Schrijf een biografie voor je profiel.',
            ],
            'status' => 'Status',
            'status-toggle' => 'Toon mijn online status',
            'emoji' => 'Emoji',
            'name-history-toggle' => 'Make username history private',
            'name-history-info' => 'Your Minecraft username history is currently',
            'name-history-toggle-on' => 'privé',
            'name-history-toggle-off' => 'publiek',
            'theme' => 'Profiel thema',
            'theme-primary' => 'Primair',
            'theme-secondary' => 'Secundair',
            'appearance' => 'Appearance',
        ],
        'link' => [
            'manage' => 'Manage linked Minecraft account',
            'description' => 'See and manage your linked Minecraft account',
            'title' => 'Gekoppeld Minecraft account',
            'current' => 'Momenteel gekoppelde Minecraft account.',
            'status' => 'You now have full access to all SkinMC features!',
            'linked' => 'Gekoppeld',
            'disconnect' => 'Ontkoppelen',
            'disconnect-title' => 'Minecraft account ontkoppelen',
            'disconnect-info' => 'Are you sure you would like to disconnect your Minecraft account?',
            'disconnect-features' => 'You will lose access to commenting, customisation and other features which require a linked Minecraft account. To use these again you will be required to link a Minecraft account.',
            'disconnect-following' => 'Disconnecting your Minecraft account will permanently remove all your followed profiles.',
            'disconnect-posts' => 'Your created feed posts and liked will be deleted.',
            'can-not-undo' => 'This can\'t be undone.',
            'are-you-sure' => 'Weet je het zeker?',
            'confirm' => 'Yes, confirm disconnect',
            'cancel' => 'Nee, annuleer',
            'success' => 'Your account was successfully disconnected!'
        ],
        'finish-setup' => [
            'title' => 'Finish account setup',
            'description' => 'Finish setting up your account, and get full access to all features by linking your Minecraft account to SkinMC.',
            'link' => 'Minecraft account koppelen',
            'get-started' => 'Aan de slag',
            'skip' => 'Overslaan',
            'claim' => 'Claim je profiel',
            'customise' => 'Pas uw pagina aan',
            'social' => 'Sociale links toevoegen',
            'comment' => 'Toegang tot opmerkingen systeem',
            'direct_message' => 'Verstuur directe berichten',
            'feed' => 'Post status updates to the feed',
            'follow' => 'Follow your friends',
            'badge' => 'Badge weergeven op jouw profiel',
            'cape' => 'Aangepaste Minecraft cape',
            'backup' => 'Automatic skin backup',
            'more' => 'En meer...'
        ],
        'skins' => [
            'title' => 'Manage skins',
            'toggle' => 'Skin visibility toggled',
        ],
        'invite' => [
            'title' => 'My invites',
            'headline' => 'Invite your friends',
            'info' => 'Create an invite code to share with your friend. Once they accept it, you\'ll both earn some extra XP!',
            'description' => 'Create an invite for your friends and you\'ll both earn some extra XP.',
            'generate' => 'Create invite code',
            'empty' => 'You haven\'t created any invites yet.',
            'code' => 'Code',
            'expiry' => 'Elke code werkt één keer.',
            'status' => [
                'title' => 'Status',
                'pending' => 'In afwachting',
                'accepted' => 'Geaccepteerd'
            ],
            'add_invite' => [
                'button' => 'Heb je een uitnodiging?',
                'title' => 'Voeg een uitnodigingscode toe',
                'redeem' => 'Uitnodiging inwisselen',
            ],
            'share' => 'Stuur je vriend een uitnodigingslink'
        ],
        'emoji' => [
            'title' => 'SkinMC Emoji',
            'introducing' => 'Introducing',
            'info' => 'Customise your profile with emoji. Unlock more as you level up.',
            'unlocked_at' => 'Unlocked at level :level',
            'unlocks_at' => 'Reach level :level to unlock',
            'turn_off' => 'Show emoji'
        ]
    ],
    'notifications' => [
        'title' => 'Notificaties',
        'view_all' => 'Bekijk alles',
        'view_all_notifications' => 'View all notifications',
        'image' => 'Notification photo',
        'archived' => 'Gearchiveerd',
        'inbox' => 'Inbox',
        'empty' => [
            'title' => 'You\'re up to date!',
            'text' => 'New notifications will show up here.',
            'text-archived' => 'Archived notifications will show up here.',
        ],
        'action' => [
            'archive' => 'Move to archive',
            'unarchive' => 'Unarchive',
            'open' => 'Tap to open',
        ],
        'toast' => [
            'archive' => 'Notification moved to archive',
            'unarchive' => 'Notification moved to inbox',
            'undo' => 'Undo',
        ]
    ],
    'error' => [
        'offline' => [
            'title' => 'Geen Internet',
            'subtitle' => 'Uw internetverbinding is verbroken. Controleer uw verbinding en laad de pagina opnieuw om het opnieuw te proberen.',
            'try_again' => 'Probeer het opnieuw'
        ],
        '404' => [
            'title' => '404 – Pagina niet gevonden.',
            'subtitle' => 'Hm, het lijkt erop dat er op deze locatie niets is gevonden. Probeer terug te gaan of probeer een nieuwe zoekopdracht?',
            'try_again' => 'Terug naar home'
        ],
    ],
    'heads' => [
        'list' => [
            'meta' => [
                'title' => 'Minecraft hoofden database',
                'description' => 'Verken de database van Minecraft hoofden om je wereld mee te versieren, of genereer je eigen gave commando. Bekijk officiële hoofden, speler hoofden en aangepaste hoofden die texturen gebruiken die nooit veranderen.'
            ],
            'header' => [
                'title' => 'Minecraft Hoofden',
                'subtitle' => 'Ontdek onze database van Minecraft-hoofden om je wereld te versieren, of genereer je eigen commando. Speler geeft de huidige skin van een gebruiker weer en kan veranderen als de gebruiker zijn skin bijwerkt. Aangepaste hoofden zijn gekoppeld aan het Mojang skin bestand en worden nooit veranderd. Aangepaste hoofden moeten worden opgeroepen met behulp van een opdrachtblok omdat het commando erg lang is.',
            ],
            'count' => [
                'heads' => ':heads hoofd|:heads hoofden',
            ],
            'customheads' => [
                'title' => 'Aangepaste hoofden',
                'description' => 'Aangepaste hoofden gebruiken het directe pad naar het texturebestand op de Mojang servers. Vandaar dat texturen nooit zullen worden verwijderd en de hoofden zullen nooit veranderen.',
                'version' => 'Minecraft 1.8 of hoger',
            ],
            'playerheads' => [
                'title' => 'Speler hoofden',
                'description' => 'Speler hoofden gebruiken de huidige skin textuur van een Minecraft-speler. Omdat ze een gebruikersnaam zijn, verandert het hoofd als de speler zijn naam of skin verandert.',
                'version' => 'Alle Minecraft-versies',
            ]
        ],
    ],
    'mod' => [
        'title' => 'SkinMC Mod: Gratis aangepaste capes',
        'headline' => 'Introducering van de SkinMC Mod voor meer aanpassingen',
        'description' => 'Giving back to the Minecraft community, with a free mod which enables players more customisation with custom capes, available and visible for anyone using the mod.',
        'download' => 'Download nu',
        'download-title' => 'Download de mod',
        'requires' => 'Vereisten',
        'select-version' => 'Kies jouw Minecraft versie',
        'get-started' => 'Er mee beginnen is eenvoudig',
        'step-1' => '1. Download de mod',
        'step-1-detail' => 'Installeer Fabric, download daarna de mod voor je game versie en installeer het door de mod in je mods map te plaatsen.',
        'step-2' => '2. Koppel jouw account',
        'step-2-detail' => 'Als je je nog niet hebt aangemeld, meld je dan aan en verbind je Minecraft-account met SkinMC.',
        'step-3' => '3. Upload jouw cape',
        'step-3-detail' => 'Ga naar uw account en upload uw aangepaste cape. Het zal zichtbaar zijn in het spel.',
        'all-versions' => 'Alle versies',
        'latest' => 'Nieuwste',
        'logged-in' => 'Upload jouw cape',
        'mirror' => 'Mirror',
        'download-via' => 'Download via:',
        'curseforge' => 'CurseForge',
    ],
    'app' => [
        'title' => 'SkinMC Android App',
        'headline' => 'Say hello to the SkinMC Android App.',
        'play-store-attribution' => 'Google Play en het Google Play-logo zijn handelsmerken van Google LLC.',
        'features' => 'Convenient features for on the go',
        'feature-qr' => 'Built in QR-Code scanner',
        'feature-qr-detail' => 'Use the built in QR-Code scanner to easily get a skin from your Desktop to the app, or scan your friends custom profile QR-Code.',
        'feature-files' => 'Saves directly to files',
        'feature-files-detail' => 'With the usage of Android Files Manager, the app can conveniently save Skins, making it easier to apply in Bedrock Edition.',
        'feature-noads' => 'Geen advertenties',
        'feature-noads-detail' => 'A clean designed interface, without distractions. Enjoy an Ad-free experience without intrusive annoyances from web to app.',
        'feature-experience' => 'Experience',
        'feature-experience-detail' => 'Enjoy the full SkinMC experience anywhere, with added features. Customise your profile, add your bio, create a fun QR-Code and more!',
        'get-app-headline' => 'Download de SkinMC App',
        'get-app-detail' => 'Your very own Minecraft companion for your Android — available for free.'
    ],
    'random' => [
        'title' => 'Loading random Minecraft skin',
        'description' => 'Loading random Minecraft skin',
        'headline' => 'Even geduld...',
        'redirect' => 'You will be automatically redirected. Page not loading?',
        'click-here' => 'Klik hier',
        'messages' => [
            '1' => 'Willekeurige Minecraft skin laden...',
            '2' => 'Omlaag graven...',
            '3' => 'Creeper, aw man...',
            '4' => 'Zoeken door kisten...',
            '5' => 'Wist je dat de aankomende skin volledig willekeurig is?',
            '6' => 'Willekeurige skin aankomend...',
            '7' => 'Nog één blok...',
            '8' => 'Inventaris sorteren...',
            '9' => 'Diamanten pikhouweel maken...',
            '10' => 'Zoeken naar Herobrine...',
        ],
    ],
    'feed' => [
        'title' => 'Feed',
        'following' => 'Following',
        'sign-up' => 'Sign up or log in to join the conversation.',
        'link-account' => 'Link your Minecraft account to join the conversation.',
        'placeholder' => 'What is happening?',
        'audience' => 'Audience',
        'audience-title' => 'Wie kan dit zien?',
        'everyone' => 'Iedereen',
        'everyone-info' => 'Iedereen binnen of buiten SkinMC.',
        'followers' => 'Volgers',
        'followers-info' => 'Ingelogde leden of leden die mij volgen.',
        'private' => 'Alleen ik',
        'private-info' => 'Privé berichten die alleen ik kan zien.',
        'submit' => 'Post',
        'like' => 'Like',
        'comment' => 'Reply',
        'share' => 'Share',
        'remaining' => 'Remaining',
        'profile' => 'Posts by :username',
        'posts' => 'All posts',
        'my-posts' => 'My posts',
        'view-all' => 'View all posts',
        'post' => [
            'meta' => ':username on SkinMC: :text',
            'title' => 'Post',
            'created' => 'Status update posted!',
            'confirm-delete' => 'Are you sure you would like to delete this post? It can not be undone.',
            'delete' => 'Delete post',
            'deleted' => 'Your post was deleted.',
        ],
        'follow-suggestions' => 'Follow the team',
        'explore' => 'Explore',
        'hashtag' => 'Hashtag',
        'stories' => [
            'archive' => [
                'title' => 'Story Archive',
                'subtitle' => 'Your archived stories are only visible to you',
                'empty' => 'No archived stories yet',
                'empty-description' => 'Stories you post will appear here after 24 hours.',
                'action' => 'Archive',
                'archived' => 'Story moved to archive.',
                'already-archived' => 'Story is already archived.',
            ],
        ],
    ],
    'private' => [
        'title' => 'Private posts',
        'text' => 'This post is private.'
    ] ,
    'liked' => [
        'title' => 'Liked'
    ],
    'following' => [
        'title' => 'Following',
        'text' => 'Sign in to view this post.'
    ],
    'tags' => [
        'empty' => 'No tags to vote on yet',
        'empty-subtitle' => 'Be the first to add one',
    ],
    'inbox' => [
        'title' => 'Berichten',
        'details' => 'Details',
        'message_user' => 'Bericht',
        'write_message' => 'Schrijf een bericht',
        'empty' => [
            'no_message_selected' => 'Geen bericht geselecteerd',
            'open_or_start_conversation' => 'Open een gesprek vanuit de berichtenlijst of begin een nieuwe.',
            'no_messages' => 'Geen ongelezen berichten',
            'start_conversation' => 'Zodra je een nieuw gesprek start, worden je berichten hier getoond.',
            'conversation' => 'This is the beginning of your conversation with :username.',
            'users' => 'Unable to find any users that match the current query.'
        ],
        'typing' => ':username is typing...',
        'new_message' => 'Nieuw bericht',
        'mark_unread' => 'Mark unread',
        'send_message' => 'Verstuur bericht',
        'delete_message' => 'Bericht voor jou verwijderen',
        'latest_conversations' => 'Latest conversations',
        'delete_conversation' => 'Delete conversation',
        'show_details' => 'Show details',
        'hide_details' => 'Hide details',
        'unread' => 'Ongelezen',
        'deleted' => 'Verwijderd',
        'report_message' => 'Rapporteer bericht',
        'add_reaction' => 'Add reaction',
        'today' => 'Vandaag',
        'reconnect' => 'Please reconnect your Minecraft account to chat',
        'account_disconnected' => 'This user disconnected their linked Minecraft account.',
        'saved_messages' => 'Opgeslagen berichten',
        'new_message_to_label' => 'Naar',
        'external-link-to' => 'Deze link brengt je naar',
        'external-link-confirmation' => 'Weet je zeker dat je daarheen wilt gaan?',
        'external-link' => 'Externe link',
        'reply' => 'Reply'
    ],
    'server' => [
        'manage' => [
            'stats' => 'Statistieken'
        ]
    ],
    'report' => [
        'button' => 'Melden',
        'title' => 'Inhoud melden',
        'describe' => 'Beschrijf kort waarom je dit meldt',
        'select' => 'Selecteer meldings reden',
        'submit' => 'Verzend melding',
        'reasons' => [
            'INAPPROPRIATE_CONTENT' => 'Ongepaste inhoud',
            'SPAM' => 'Spam',
            'HARASSMENT' => 'Intimidatie',
            'OTHER' => 'Andere',
        ]
    ],
    'leaderboard' => [
        'title' => 'Leaderboard',
        'description' => 'View the SkinMC leaderboard of users.',
        'headline' => 'Top 10',
        'all-time-invites' => 'All time invites',
        'all-time-xp' => 'XP aller tijden',
        '30-day-xp' => '30 dagen XP'
    ],
];
