<?php

return [
    'skins' => '스킨',
    'avatars' => '아바타',
    'editor' => '편집기',
    'heads' => '머리',
    'capes' => '망토',
    'servers' => '서버',
    'achievement' => '도전과제',
    'armor' => '갑옷 거치대',
    'banners' => '배너',
    'banner' => 'Banner Editor',
    'profile' => '내 프로필',

    'generators' => '생성기',

    // Navigation dropdowns
    'feed' => 'Feed',
    'discover' => 'Discover',
    'mods' => 'Mods',
    'shaders' => 'Shaders',
    'resource_packs' => 'Resource Packs',
    'modpacks' => 'Modpacks',
    'datapacks' => 'Data Packs',
    'plugins' => 'Plugins',

    'logout' => '로그아웃',
    'register' => '가입',
    'login' => '로그인',
    'about' => '소개',
    'contact' => '문의',
    'faqs' => '자주 묻는 질문',

    'minecraft_name' => 'Minecraft 이름',
    'minecraft_uuid' => 'Minecraft UUID',
    'what' => '내용',
    'recent_searches' => '최근 검색어',
    'username' => '사용자 이름',
    'uuid' => 'UUID',
    'search' => '검색',
    'search_placeholder' => '추천:',
    'search_placeholder_uuid' => 'UUID 입력',
    'start_search' => '검색을 시작해 보세요',
    'cancel_search' => '닫기',
    'search_type' => '검색 유형',
    'search_type_all' => '모든 결과',
    'profiles' => '프로필',
    'view_skin' => '스킨 보기',
    'edit_skin' => '스킨 편집',
    'make_avatar' => '아바타 만들기',
    'find_heads' => '플레이어 머리 찾기',

    'home' => '홈',
    'help' => '도움말',
    'tools' => '도구',
    'more-tools' => '다른 도구',
    'skin_viewer' => '스킨 뷰어',
    'avatar_maker' => '아바타 만들기',
    'collections' => '모음집',
    'popular_skins' => '인기 스킨',
    'cartoon_skins' => '만화 스킨',
    'animal_skins' => '동물 스킨',
    'community' => '커뮤니티',
    'imprint' => '판권',
    'cookies' => '쿠키',
    'terms' => '이용 약관',
    'privacy' => '개인정보처리방침',
    'app' => '앱',
    'mod' => '모드',
    'totem' => '토템',
    'cube' => 'Cube',
    'new' => 'New',

    'feedback' => '의견 보내기',
    'status' => '상태',
    'recent_searches_placeholder' => '검색을 시작하면, 과거 검색 결과가 여기에 표시돼요.',
    'recent_views_placeholder' => '일부 프로필을 방문하면, 과거 방문했던 프로필이 여기에 표시돼요.',
    'moderate' => '관리',
    'listings' => '목록',
    'add' => '추가',

    'theme' => [
        'title' => 'Theme',
        'dark' => '어둡게',
        'light' => '밝게',
        'auto' => 'Auto'
    ],
];
