<?php

return [
    'auth' => [
        'login' => [
            'title' => 'SkinMC에 오신 걸 환영해요',
        ],
        'register' => [
            'title' => 'SkinMC에 가입하기',
            'subtitle' => '모든 기능을 사용하려면 계정을 생성하고 시작하세요.',
        ],
    ],

    'home' => [
        'hero_slogan' => 'Minecraft 스킨을 찾는 나만의 공간',
        'hero_slogan_alt_1' => 'Everything Minecraft. One place.',
        'hero_slogan_alt_2' => 'Where Minecrafters meet.',
        'hero_cta' => '아무거나 볼래요!',
        'hero_explore_cta' => '스킨 둘러보기',
        'skin_viewer' => '스킨 뷰어',
        'skin_viewer_detail' => '스킨 :count개 둘러보기',
        'skin_editor' => '스킨 편집기',
        'skin_editor_detail' => '나만의 스킨을 설계해 보세요',
        'avatar_maker' => '아바타 생성기',
        'avatar_maker_detail' => '나만의 맞춤 Minecraft 아바타 프로필 사진을 생성해 보세요.',
        'trending' => '인기 급상승',
        'minecraft_skin' => 'Minecraft 스킨',
        'favourite' => '즐겨찾기',
        'collections' => '모음집',
        'collections_detail' => '모든 경우를 위해 엄선된 Minecraft 스킨',
        'creations_title' => 'Skin creations',
        'creations_description' => 'Browse and upload custom Minecraft skin creations.',
        'creations_new_updated' => 'New & updated',
        'about_skinmc' => 'SkinMC 소개',
        'about_find' => '아무 스킨 찾기',
        'about_find_detail' => '특정 Minecraft 사용자 이름을 찾기 위해, 내 다음 새로운 스킨을 사기 위해 SkinMC 검색 기능을 사용해요.',
        'about_download' => '다운로드 또는 수정',
        'about_download_detail' => '원하는 스킨을 찾으셨나요? 즐겨찾기에 추가하고, 수정 또는 다운로드하여 나만의 것으로 만드세요.',
        'about_platform' => '플랫폼 전환하기',
        'about_platform_detail' => '이동 중에 스킨을 착용하고 싶으신가요? QR 코드를 스캔해서 기기에 Minecraft 포켓에디션용 사진을 저장하세요.',
        'meta' => [
            'title' => 'Minecraft 스킨 뷰어',
            'description' => 'Minecraft 스킨을 보고 다운로드하고, 엄선된 컬렉션에서 최고의 스킨을 찾고, 사용자 이름 사용 가능 여부와 기록을 확인하는 등 다양한 활동을 즐겨보세요!',
        ],
        'recently_viewed' => '최근 조회',
        'explore_title' => '새로운 걸 시도해 보세요',
        'explore' => '새 아이디어와 도구를 확인해 보세요',
        'servers_browse' => '서버 둘러보기',
        'servers' => '최고의 Minecraft 서버를 발견해 보세요',
        'servers_new_upcoming' => 'New & upcoming servers',
        'servers_new_upcoming_browse' => 'Find fresh servers with smaller communities that are currently online.',
        'servers_upcoming_players' => 'players',
        'servers_upcoming_badge' => 'New',
        'heads' => 'Minecraft 머리',
        'head_description' => 'Minecraft 머리 데이터베이스를 둘러보거나, 새로운 걸 생성해 보세요.',
        'achievement' => '도전과제 생성기',
        'achievement_detail' => '나만의 개인적인 맞춤 도전과제를 생성해 보세요.',
        'continue' => '계속 둘러보기',
        'totem' => 'Minecraft Totem Generator',
        'totem_description' => 'Create a custom Minecraft resource pack with a Totem of Undying from any skin.',
        'banner' => 'Minecraft Banner Generator',
        'banner_description' => 'Generate and preview custom Minecraft banners and patterns.',
        'capes' => 'Minecraft Capes',
        'capes_description' => 'Browse the largest collection of Minecraft capes, or create your own.',
        'feature_drop_bubble_title' => 'SkinMC Creator Update',
        'feature_drop_bubble_cta' => "What's new?",
        'feature_drop_modal' => [
            'hero' => [
                'title' => 'SkinMC Creator Update',
                'subtitle' => 'More tools. More control. More ways to share.',
                'description' => 'Built for creators, collectors and server communities.',
                'cta' => 'Explore what\'s new',
            ],

            'upload_creations' => [
                'title' => 'Publish your work.',
                'description' => 'Upload custom skin creations directly to SkinMC.',
                'line_1' => 'Add details, credits and choose visibility.',
                'line_2' => 'Save as draft, unlisted, or publish publicly.',
            ],

            'custom_heads' => [
                'title' => 'A new heads gallery.',
                'description' => 'Upload and explore custom Minecraft heads.',
                'line_1' => 'Perfect for builders.',
                'line_2' => 'Perfect for server creators.',
            ],

            'feed_upgrade' => [
                'title' => 'Share more. Share better.',
                'description' => 'Post up to four images in the feed.',
                'line_1' => 'Share your favourite skins, creations or servers.',
                'line_2' => 'Directly from where you discover them.',
            ],

            'editor_upgrade' => [
                'title' => 'The most powerful SkinMC editor yet.',
                'description' => 'New creative tools for more control and cleaner detailing.',
                'line_1' => 'Circle, triangle and square brushes.',
                'line_2' => 'Size and softness slider.',
                'line_3' => 'Noise texture brush.',
                'line_4' => 'Improved fill tool.',
            ],

            'preview_mode' => [
                'title' => 'Floating preview.',
                'description' => 'A minimap for your skin, always in view.',
                'line_1' => 'Live updates while you paint.',
                'line_2' => 'Add reference images.',
                'line_3' => '2D, 3D, or side-by-side.',
                'line_4' => 'Position it anywhere.',
            ],

            'server_ranking' => [
                'title' => 'Improved ranking and voting.',
                'description' => 'A fairer system with better visibility for quality servers.',
            ],

            'avatar_generator_upgrade' => [
                'title' => 'Real-time 3D avatars.',
                'description' => 'A faster, more powerful avatar generator.',
                'line_1' => 'Full 3D and bust avatars.',
                'line_2' => 'Optional name tags.',
                'line_3' => 'Live preview.',
                'line_4' => 'High-resolution rendering.',
            ],

            'closing' => [
                'title' => 'SkinMC is evolving.',
                'description' => 'Create. Curate. Share.',
                'cta' => 'Start creating',
            ],
        ],
    ],
    'profile' => [
        'verified' => '인증된 프로필',
        'minecraft_profile' => 'Minecraft 프로필',
        'show_qr_code' => 'QR 코드 표시',
        'favourite' => '즐겨찾기',
        'user_title' => ':username님의 Minecraft 스킨',
        'user_views' => '조회수 :views회',
        'uuid' => 'UUID',
        'copy' => '복사',
        'link' => '링크',
        'skin_history' => 'Minecraft 스킨 기록 (:skins)',
        'username_history' => '사용자 이름 기록',
        'username_history_name' => '이름',
        'username_history_timestamp' => '변경된 날짜',
        'username_history_initial_name' => '최초 이름',
        'user_downloads' => '다운로드 :downloads회',
        'download_skin' => '스킨 다운로드',
        'apply_skin' => '스킨 적용',
        'capes' => '망토',
        'claim_profile' => ':username님이신가요? 프로필을 등록하고 꾸며보세요!',
        'claimed' => '프로필 등록 완료',
        'meta_description' => ':username님의 Minecraft 스킨을 보고 다운로드해요. UUID, 이름 기록, 세부 통계 등이 있어요',
        'created_at' => '변경된 날짜: :changed_at',
        'skins' => [
            'meta_title' => ':username님의 Minecraft 스킨 기록',
            'meta_description' => ':username님의 Minecraft 스킨 기록과 이전에 사용했던 스킨을 봐요. 이 기록을 이용해서 과거에 사용했던 스킨을 살펴보고, 백업하거나 다시 되돌리거나 새 스킨을 수집해 보세요.',
            'title' => 'Minecraft 스킨 기록',
        ],
        'qr_code' => [
            'meta_title' => ':username님의 QR 코드',
            'meta_description' => ':username님의 맞춤 Minecraft 프로필 QR 코드',
        ],
        'sub_nav' => [
            'skin' => '스킨',
            'about' => '내 소개',
            'usernames' => '사용자 이름',
            'head' => '머리',
            'comments' => '댓글',
        ],
        'cape' => '망토',
        'elytra' => '겉날개',
        'nametag' => '이름표',
        'animation' => '애니메이션',
        'rotation' => '회전',
        'none' => '없음',
        'idle' => '정적 상태',
        'walk' => '걷는 상태',
        'run' => '뛰는 상태',
        'fly' => '나는 상태',
        'follow' => '팔로우',
        'following' => '팔로우 중',
        'unfollow' => '팔로우 취소',
        'followers' => '팔로워',
        'toast' => [
            'following' => ':username님을 팔로우 중이에요!',
            'follow-self-error' => ':username님 죄송하지만, 자기 자신을 팔로우할 수 없어요.',
            'unfollowed' => ':username님의 팔로우를 취소했어요',
        ],
        'edit' => '프로필 편집',
        'joined' => '가입 시기:',
        'role' => 'Role',
        'server-fav-list-empty' => '아직 :username님이 아무 서버도 즐겨찾기 하지 않은거 같아요. :username님이 서버를 즐겨찾기에 저장하면, 여기에서 확인할 수 있어요.',
        'server-own-list-empty' => '아직 :username님이 아무 서버도 추가하지 않은거 같아요. :username님이 서버를 추가하면, 여기에서 확인할 수 있어요.',
        'capes-list-empty' => ':username님이 아직 아무 망토도 장착하지 않은 것 같아요. :username님이 망토를 장착하면, 여기에서 확인할 수 있어요.',
        'feed-own-list-empty' => '아직 아무 게시물도 게시하지 않은 것 같아요. 게시물을 게시하면 여기에서 확인할 수 있어요.',
        'feed-list-empty' => '흠, :username님이 아직 아무 게시물도 게시하지 않은 것 같아요. :username님이 게시물을 게시하면 여기에서 확인할 수 있어요.',
        'following-own-list-empty' => '아직 아무도 팔로우하지 않은 것 같아요! 누군가를 팔로우하기 시작하면, 여기에서 확인할 수 있어요.',
        'following-list-empty' => '흠, :username님이 아무도 팔로우하지 않은 것 같아요. :username님이 누군가를 팔로우하기 시작하면 여기서 확인할 수 있어요.',
        'followers-own-list-empty' => '누군가 나를 팔로우하기 시작하면, 여기에 표시돼요.',
        'followers-list-empty' => '흠, :username님을 팔로우하는 분이 없는 것 같아요. :username님을 팔로우하는 첫 번째 분이 되어보세요. 더 많은 분이 팔로우하기 시작하면, 여기서 확인할 수 있어요.',
        'render' => '렌더',
        '3d' => '3D 렌더',
        '2d' => '2D 렌더',
        'name-history-info' => '사용자 이름 기록이 사라지고 있어요. Mojang은 9월 13일 이후 이름 기록 API를 접근하지 못하도록 지원을 중단했어요. 따라서 이제 정확한 이름 기록을 사용할 수 없게 됐어요. 내 이름 기록을 숨기고 싶다면, 내 프로필을 등록하고 설정에서 비공개로 만드세요.',
        'edit-skins' => '스킨 기록 편집',
        'hide-skin' => '스킨 숨기기',
        'show-skin' => '스킨 표시',
        'edit-skin' => '스킨 편집',
        'servers' => [
            'title' => ':username님의 서버',
        ],
        'cape-list' => [
            'title' => ':username님의 망토',
        ],
    ],
    'skin' => [
        'meta' => [
            'title' => ':username님의 Minecraft 스킨',
            'description' => 'Minecraft 스킨. 스킨을 다운로드하고 보고, 동일한 스킨을 착용 중인 플레이어를 확인해요.',
            'tags' => ':username님의 Minecraft 스킨, :username 스킨, Minecraft 스킨, :username님의 맞춤 Minecraft 스킨, 스킨 다운로드, 동일한 스킨이 있는 플레이어',
        ],
        'title' => ':username님의 Minecraft 스킨',
        'head' => '머리 명령어',
        'head_info' => '명령 블록과 함께 사용하세요',
        'first_wearing' => '이 스킨을 처음 착용한 플레이어:',
        'profiles' => '프로필 :profiles개',
        'profiles_title' => '이 스킨을 착용 중인 프로필 :profiles개',
        'screenshot' => '스크린샷',
    ],
    'skins' => [
        'meta' => [
            'title' => ':current페이지 - 모든 Minecraft 스킨',
            'description' => ':last 페이지에 있는 :total개의 Minecraft 스킨 목록을 둘러보고, 가장 마음에 드는 스킨을 다운로드하세요!',
            'tags' => ':username님의 Minecraft 스킨, :username 스킨, Minecraft 스킨, :username님의 맞춤 Minecraft 스킨, 스킨 다운로드, 동일한 스킨이 있는 플레이어',
            'tags-title' => ':tag의 Minecraft 스킨',
            'tags-description' => 'Browse through our :last pages list of :total :tag Minecraft skins and download your favourite :tag skin!',
            'tags-metatags' => ':tag Minecraft 스킨, :tag 스킨, Minecraft 스킨 :tag 맞춤 Minecraft 스킨, 다운로드 :tag 스킨, Minecraft :tag 스킨',
        ],
        'title-skin-tags' => '태그된 Minecraft 스킨',
        'subtitle' => ':last 중 :current페이지 - 총 스킨 :total개',
        'subtitle-skin-tags' => ':last 중 :current페이지 - 총 태그된 스킨 :total개',
        'sort_by' => '정렬 기준',
        'latest' => '최신 스킨',
        'most_profiles' => '많이 사용한 스킨',
        'profiles_today' => '오늘 많이 사용한 스킨',
        'profiles_this_week' => '이번 주에 많이 사용한 스킨',
        'profiles_this_month' => '이번 달에 많이 사용한 스킨',
        'default' => '기본 정렬',
        'this_month' => '이번 달에 추가된 스킨',
        'this_week' => '이번 주에 추가된 스킨',
        'today' => '오늘 추가된 스킨',
        'random' => '무작위 스킨',
        'similar' => '유사한 스킨',
        'no_similar_skins' => '유사한 스킨을 찾지 못했어요.',
        'favorite' => '즐겨찾기 :count개',
    ],
    'skin-tags' => [
        'faq' => '태그가 무엇인가요?',
        'about' => '태그는 스킨과 관련된 카테고리를 추가하는 방법이에요. 태그를 추가하면 좋아하는 스킨을 쉽게 발견하도록 해 줘요!',
        'guidelines' => [
            'good' => [
                'title' => '좋은 태그의 일반적인 지침:',
                'short' => '짧게',
                'descriptive' => '묘사적이게',
                'spelled' => '철자를 정확하게',
            ],
            'bad' => [
                'title' => '다음과 같은 태그는 추가하지 마세요:',
                'general' => '너무 일반적임',
                'specific' => '너무 구체적임',
                'too-many-tags' => '3개의 분리된 태그여야 함',
                'spelling' => ':example이어야 함',
            ],
        ],
        'toast' => [
            'added' => '":tag" 태그가 투표에 추가됐어요',
            'removed' => '":tag:" 태그가 삭제됐어요',
            'upvote' => '":tag" 태그를 추천했어요',
            'downvote' => '":tag" 태그를 비추천했어요',
        ],
        'vote' => [
            'up' => '추천',
            'down' => '비추천',
            'remove' => '투표 제거',
        ],
    ],
    'contact' => [
        'contact' => '문의',
        'email' => '생각 중인 질문을 <a href="mailto:support@skinmc.net">support@skinmc.net</a>로 자유롭게 작성해서 저희에게 알려주세요.',
        'faq' => '그 전에 생각 중인 질문이 <a href=":link">FAQ 페이지</a>에 먼저 있는지 확인하시는 걸 권장드려요.',
        'other' => '연락할 수 있는 다른 방법',
        'other_discord' => 'Discord 서버에 참가해서 다른 분과 연결하고, 게임 관련 대화를 하고, 내 최애 팩을 공유하고, 커뮤니티 지원을 받아보세요.',
        'other_twitter' => 'Twitter에서 팔로우해서 언제 새 업데이트나 기능이 출시되는지 확인하고, 이번 주의 스킨을 확인해 보세요.',
        'other_instagram' => 'Instagram에서 SkinMC를 팔로우해서 멋지고 특색있는 Minecraft 스킨과 사진을 살펴보고 발견해 보세요.',
        'other_bluesky' => 'Follow SkinMC on Bluesky to see when a new update or feature is released, see the skin of the week and more.',
    ],
    'about' => [
        'intro' => '<span>Minecraft</span> <span>스킨</span><span>을 위한</span> <span>나만의</span> <span>플랫폼</span>',
        'header_credit' => '삽화 "Epic Nether Battle" 제작자:',
        'info' => '모든 걸 파악하세요.',
        'info_explainer' => '플레이어의 이름 기록, 이전에 사용했던 스킨을 보고, 친구로 추가하거나, 스킨을 다운로드하거나 세부 통계를 확인해 보세요.',
        'card_find_title' => '아무 Minecraft 플레이어나 찾기',
        'card_find_detail' => '내 결정에 따라 플레이어의 사용자 이름이나 UUID으로 아무 플레이어나 검색을 시작해 보세요.',
        'card_view_title' => '보고, 저장하고, 편집하기',
        'card_view_detail' => '내가 좋아하는 스킨을 찾았나요? 다운로드해서 저장하거나 나만의 스킨으로 만드려면 편집기를 사용해 보세요.',
        'card_claim_title' => '등록하기',
        'card_claim_detail' => '내 MInecraft 계정을 연동해서 내 프로필을 등록하고 새 기능을 잠금 해제해 보세요!',
        'card_customise_title' => '내 프로필을 맞춤 설정하기',
        'card_customise_detail' => '등록된 플레이어는 소셜 미디어 링크를 추가하고 프로필을 마음대로 꾸밀 수 있어요.',
        'card_friends_title' => '친구 추가하기',
        'card_friends_detail' => 'SkinMC에 내 친구와 연결해서 프로필에 친구 목록을 표시해 보세요.',
        'card_history_title' => '사용자 이름 및 스킨 기록',
        'card_history_detail' => '고급 검색을 사용해 플레이어의 사용자 이름/스킨 기록을 찾고 확인해 보세요.',
        'founders' => '창업자',
        'founders_cofounder' => 'SkinMC의 공동 창업자',
        'head_of_design' => '디자인 담당',
        'head_of_code' => '코드 담당',
        'feedback' => '저희에게 피드백을 보내주세요',
        'faq' => 'Minecraft, 스킨 등에 대한 질문이 있으신가요? 자주 묻는 질문의 대답은 FAQ를 읽어보세요.',
        'faq_link' => 'FAQ 센터 방문',
        'contact' => '연락하고 싶으시거나 다른 질문이 있으신가요? 직접 문의해 주세요.',
        'contact_link' => '문의하기',

    ],
    'faq' => [
        'title' => 'FAQ',
        'subtitle' => '자주 묻는 질문',
        'help' => '도움이 더 필요하신가요?',
        'discord' => 'Discord 서버에 참가해서 다른 Minecraft 플레이어와 대화해 보세요.',
        'contact' => '문의하기',
        'q' => [
            'change_skin_t' => '제 Minecraft 스킨을 어떻게 변경하나요?',
            'change_skin' => '                <p>스킨 변경을 위해 아래 절차를 따르세요:</p>
                <ol>
                    <li>https://my.minecraft.net/en-us/login/<a href="https://my.minecraft.net/en-us/login/">를 방문하세요. </a> Mojang 계정으로 로그인 하세요.</li><li>로그인 후 <b>왼쪽 메뉴에 있는</b> "스킨"을 선택하세요.</li><li>그 다음, choose a Model you prefer and upload a the Skin of your liking.</li>
                </ol>',
            'change_username_t' => '제 Minecraft 사용자 이름을 어떻게 변경하나요?',
            'change_username' => '                <p>사용자 이름 변경을 위해 아래 절차를 따르세요:</p>
                <ol>
                    <li>https://account.mojang.com/login<a href="https://account.mojang.com/login" target="_blank" rel="nofollow">를 방문하세요</a> Mojang 계정으로 로그인 하세요..</li>
                    <li>내 Minecraft 프로필 사용자 이름을 찾고 <b>"(변경)"</b> 버튼을 누르세요.</li>
                    <li>다음 페이지에서, 원하는 새로운 사용자 이름을 입력하세요..</li>
                    <li>마지막으로 "사용자 이름 변경"을 누르고 비밀번호를 입력해서 사용자 이름 변경을 완료하세요.</li>
                </ol>',
            'dl_t' => '다른 분의 Minecraft 스킨을 어떻게 다운로드하나요?',
            'dl' => '                <p>누군가의 Minecraft 스킨을 다운로드 하려면 아래 절차를 따르세요:</p>
                <ol>
                    <li>겁색창을 열고 스킨을 다운로드 할 플레이어의 사용자 이름을 입력하세요.</li>
                    <li>프로필 페이지에서 스킨을 미리볼 수 있습니다.</li>
                    <li>미리보기 버튼 아래에 있는<strong>다운로드 스킨</strong>을 누르세요</li>
                </ol>',
            'submit_q' => '스킨을 모음집으로 어떻게 제출할 수 있나요?',
            'submit_a' => '<p>Please fill out the following short form with the usernames and their category of which you would like to add to the collections. <a href="https://forms.gle/f4Jh5RpGfsHAZ5xE8" target="_blank">Collection submission form</a>',
            'mcpe_t' => 'Minecraft 포켓 에디션에서 스킨을 사용할 수 있나요?',
            'mcpe' => '
                <p>Yes. To use the Skin in Minecraft Pocket Edition do the following:</p>
                <ol>
                    <li>Open SkinMC.net on your smartphone and tap the search bar</li>
                    <li>Enter the username of the player\'s skin you would like to download</li>
                    <li>Tap the <strong>Download Skin</strong> button under the preview </li>
                    <li>Open Minecraft PE and tap on <strong>Profile</strong> on the right side</li>
                    <li>Tap on the <strong>+</strong>, or edit character and go to the "classic skins tab"</li>
                    <li>Tap on "owned", then "import", then "choose new skin"</li>
                </ol>',
            'change_times_t' => '제 사용자 이름을 얼마나 자주 변경할 수 있나요?',
            'change_times' => '<p>Minecraft 사용자 이름은 <strong>30일에</strong> 한 번 <strong>변경할 수 있습니다</strong>.</p>',
            'available_t' => '제 닉네임을 변경한 후 다른 사람들에게 언제부터 변경사항이 적용되나요?',
            'available' => '<p>이전 사용자명으로 되돌아가려면, <strong>30일 후</strong>부터 가능해요. 다른 사람이 내 이전 사용자명을 가져가려면 <strong>7일</strong>(변경 후 37일)을 더 기다려야 해요.</p>',
            'username_history_t' => '제 사용자 이름 기록을 지워주실 수 있나요?',
            'username_history' => '
                <p>As the username history data comes from Mojang, the username history can not be removed. Mojang has previously stated that their intention was that previous usernames can be seen¹, and that they provide a direct method for the public to access this information².</p>
                <p class="font-14">¹<a href="https://help.minecraft.net/hc/en-us/articles/360034636712-Minecraft-Usernames" target="_blank" rel="noreferrer">https://help.minecraft.net/hc/en-us/articles/360034636712-Minecraft-Usernames</a></p>
                <p class="font-14 mb-0">²<a href="https://twitter.com/dinnerbone/status/554739042529849345" target="_blank" rel="noreferrer">https://twitter.com/dinnerbone/status/554739042529849345</a> (Tweet archived 2 years ago: <a href="http://archive.is/TeAyj" target="_blank" rel="noreferrer">http://archive.is/TeAyj</a>)
                </p>',
        ],
    ],
    'avatars' => [
        'start' => [
            'title' => '나만의 Minecraft 아바타를 생성해 보세요',
            'subtitle' => 'Minecraft 아바타 생성기를 사용해서 어떠한 스킨이든지 재밌는 아바타를 생성해 보세요!',
            'avatar_face' => '얼굴형 아바타',
            'avatar_bust' => '상반신형 아바타',
            'avatar_cube' => '큐브형 아바타',
            'avatar_head3d' => '3D headshot',
            'avatar_bust3d' => '3D bust',
        ],
        'user' => [
            'title' => '스킨을 고르세요',
            'subtitle' => '내가 생성하고 싶은 아바타의 Minecraft 사용자 이름을 입력하세요.',
            'form_label' => 'Minecraft 사용자 이름',
            'form_submit' => '계속',
        ],
        'output' => [
            'title' => '미리보기 및 저장',
            'subtitle' => '새 Minecraft 아바타 사용을 즐기세요',
            'download_info' => '결과에 만족하시나요? 여기에서 다운로드해서 나만의 새 아바타 사용을 시작해 보세요',
            'download_button' => '아바타 다운로드',
            'avatar_style' => '아바타 스타일',
            'skin_username' => '스킨 사용자 이름',
            'change' => '변경',
            'generate' => '생성',
            'avatar_colour' => '배경 색상',
            'avatar_colour_palette' => '팔레트',
            'avatar_colour_basic' => '기본',
            'show_nametag' => 'Show nametag',
            'loading_3d' => 'Loading 3D viewer…',
        ],
        'meta' => [
            'title' => 'Minecraft 아바타 생성기',
            'description' => 'Minecraft 아바타 만들기: Minecraft 스킨으로 맞춤 Minecraft 프로필 사진을 생성하세요',
        ],
    ],
    'totem' => [
        'title' => '맞춤 Minecraft 토템',
        'subtitle' => 'Minecraft 토템 생성기를 사용해서 어떠한 스킨이든지 불사의 토템이 있는 사용자 지정 리소스팩을 만들어 보세요.',
        'download_info' => '미리 보기에 만족하시나요? Minecraft 버전을 고르고 사용자 지정 리소스 팩에 저장해 보세요:',
        'download_failed' => 'Could not load skin image. Check the username or try uploading an image.',
        'base64_size' => 'The image must be less than 256KB.',
        'meta' => [
            'title' => 'Minecraft 맞춤 토템 생성기',
            'description' => 'Custom Minecraft Totems: generate and create a custom Minecraft Resource Pack with a Totem of Undying using your or any other players Minecraft skin.',
        ],
        'type' => [
            'mini' => '스킨의 미니 버전이에요!',
            'full' => '스킨의 전체 버전이에요!',
            'model3d' => '스킨의 3D 모델 버전이에요!',
            'add_designs' => '더 많은 디자인을 보고 싶으신가요? 디자인 제안을 여기에 남겨주세요:',
        ],
    ],
    'achievement' => [
        'header' => [
            'title' => '나만의 Minecraft 도전과제를 생성해 보세요',
            'subtitle' => 'Minecraft 도전과제 생성기를 사용해서 맞춤 도전과제를 생성하고 좋아하는 아무 도전과제나 보여줘 보세요!',
        ],
        'generator' => [
            'yellow_text' => '노란색 문자',
            'white_text' => '하얀색 문자',
            'choose_icon' => '아이콘을 고르세요',
            'face' => '아이콘 대신 Minecraft 얼굴',
            'form_submit' => '다운로드',
            'form_label' => 'Minecraft 사용자 이름',
            'download' => '다운로드',
            'embed' => '임베드',
            'embed_copy' => '복사',
        ],
        'meta' => [
            'title' => 'Minecraft 도전과제 생성기',
            'description' => 'Generate custom Minecraft Achievements and Advancements with the Achievement creator. Download the image directly, use it in forum signatures, embed with HTML or BB code, and more',
        ],
    ],
    'armor' => [
        'header' => [
            'title' => 'Minecraft 갑옷 거치대 생성기',
            'subtitle' => '나만의 Minecraft 갑옷 거치대를 생성해 보세요. 각기 다른 포즈, 위치, 아이템 배치 등을 만들어보세요.',
        ],
        'meta' => [
            'title' => 'Minecraft 갑옷 거치대 생성기',
            'description' => 'Easily generate and create custom Minecraft Armor Stands. The editor helps you make different poses, positions, place items, custom skins, and much more.',
        ],
    ],
    'banner' => [
        'editor' => [
            'header' => [
                'title' => 'Minecraft 배너 편집기',
                'subtitle' => 'Design and create your very own custom Minecraft Banners. These can be used to decorate your world or also commonly seen used as <a href="https://optifine.net" target="_blank" rel="nofollow">Optifine</a> capes.',
            ],
            'meta' => [
                'title' => 'Minecraft 배너 생성기',
                'description' => 'Create and design your very own custom Minecraft Banners designs with all the patterns and colors from the game! These can be used to decorate your world or be worn as an Optifine Cape using the Banner Cape. You can generate give codes for banners or shields.',
            ],
            'toolbar' => [
                'title' => 'Banner Editor',
                'randomise' => 'Randomise',
                'clear_layers' => 'Clear layers',
                'help' => 'Help',
                'save_banner' => 'Save banner',
                'submit_to_gallery' => 'Add to gallery',
                'reset_from_url' => 'Load from link',
                'minecraft_version' => 'Minecraft version',
                'texture_type' => 'Texture type',
                'banner' => 'Banner',
                'shield' => 'Shield',
                'version_1_21' => '1.21+',
                'version_1_16' => '1.16 - 1.20',
                'version_1_13' => '1.13 - 1.15',
                'version_1_8' => '1.8 - 1.12',
            ],
            'tools' => [
                'share_link' => 'Share link',
                'share_link_placeholder' => 'Share link',
                'generate_codes' => 'Generate codes',
                'target_selector' => 'Target selector',
                'command_give' => 'Give',
                'command_setblock' => 'Setblock',
                'command_replaceitem_shield' => 'Shield',
                'code_placeholder' => 'Pick a command to generate code',
                'import_code' => 'Import code',
                'background_grass' => 'Grass background',
            ],
            'modal' => [
                'save_banners' => 'Saved banners',
                'share_saved_gallery' => 'Share saved gallery',
                'share_saved_gallery_placeholder' => 'Share saved gallery',
                'export_to_chest' => 'Export to chest',
                'delete_all' => 'Delete all',
            ],
        ],
        'gallery' => [
            'header' => [
                'title' => 'Minecraft 배너 갤러리',
                'subtitle' => 'Browse the gallery of :count custom designed Minecraft banners and patterns. Use it as a shield or cape to make your Minecraft skin more unique, or as a flag to decorate your world.',
            ],
            'meta' => [
                'title' => 'Minecraft 배너 갤러리',
                'description' => 'Browse the gallery of :count custom designed Minecraft Banners. You can use a Banner Design and Pattern as a Shield or cape to make your Minecraft skin more unique, or use it as a flag to decorate your world.',
            ],
            'add_design' => 'Add design',
            'sort' => 'Sort:',
            'sort_trending' => 'Trending',
            'sort_best' => 'Best of',
            'sort_newest' => 'Newest',
            'sort_oldest' => 'Oldest',
            'sort_favorites' => 'Most favourites',
            'sort_views' => 'Most views',
            'sort_last_week' => 'Last week',
            'sort_last_30d' => 'Last 30 days',
            'clear_filters' => 'Clear filters',
            'no_banners' => 'No banners yet',
            'no_banners_message' => 'No designs yet. Be the first to share one.',
            'create_banner' => 'Create a banner',
        ],
        'publish' => [
            'title' => 'Publish banner',
            'publish_button' => 'Publish',
            'title_label' => 'Title',
            'description_label' => 'Description',
            'tags_label' => 'Tags',
            'tags_max_reached' => 'Maximum 5 tags reached',
            'tags_add_placeholder' => 'Add a tag',
            'tags_help' => 'Press enter, tab, or comma to add a tag.',
            'tags_max_error' => 'You can add a maximum of 5 tags.',
            'generate_banner_error' => 'Create a design first.',
            'invalid_code_format' => 'Invalid banner code format.',
            'invalid_base_color' => 'Invalid base colour. Must be between 0 and 15.',
            'invalid_patterns_format' => 'Invalid patterns format.',
            'invalid_pattern_structure' => 'Invalid pattern structure.',
            'invalid_pattern_unknown' => 'Unknown pattern.',
            'invalid_pattern_color' => 'Invalid pattern colour. Must be between 0 and 15.',
        ],
        'edit' => [
            'title' => 'Edit banner',
            'title_label' => 'Title',
            'description_label' => 'Description',
            'tags_label' => 'Tags',
            'tags_max_reached' => 'Maximum 5 tags reached',
            'tags_add_placeholder' => 'Add a tag',
            'tags_help' => 'Press enter, tab, or comma to add a tag.',
            'tags_max_error' => 'You can add a maximum of 5 tags.',
            'save_changes' => 'Save changes',
            'cancel' => 'Cancel',
            'edit_details' => 'Edit banner details',
            'delete' => 'Delete banner',
            'delete_confirm' => 'Delete this banner? This cannot be undone.',
        ],
        'show' => [
            'edit_design' => 'Edit design',
            'banner_give_command' => 'Banner give command',
            'setblock_command' => 'Setblock command',
            'shield_give_command' => 'Shield give command',
            'views_count' => ':count view|:count views',
            'favourites_count' => ':count favourite|:count favourites',
            'favourite_label' => 'favourite',
            'favourites_label' => 'favourites',
            'similar_banners' => 'Similar banners',
        ],
        'already_exists' => 'This banner is already in the gallery.',
    ],
    'skin_creations' => [
        'search_tab' => 'Creations',
        'gallery' => [
            'title' => 'Skin Creations',
            'description' => 'Browse :count custom Minecraft skin creations.',
            'header' => [
                'title' => 'Skin Creations',
                'subtitle' => ':count creation|:count creations',
            ],
            'tab_creations' => 'Creations',
            'upload' => 'Upload skin',
            'downloadable_only' => 'Downloadable only',
            'sort_trending' => 'Trending',
            'sort_best' => 'Best',
            'sort_newest' => 'Newest',
            'sort_oldest' => 'Oldest',
            'sort_favorites' => 'Most favourites',
            'sort_views' => 'Most views',
            'sort_last_week' => 'Last week',
            'sort_last_30d' => 'Last 30 days',
            'sort_recently_updated' => 'Recently updated',
            'empty_title' => 'No creations yet',
            'empty_message' => 'Be the first to share a skin creation.',
            'clear_filters' => 'Clear',
        ],
        'upload' => [
            'title' => 'Upload skin creation',
            'description' => 'Upload a Minecraft skin to the gallery.',
            'heading' => 'Upload skin',
            'subtitle' => 'Drag and drop a PNG or choose a file. Add a title, description, and tags.',
            'drop_here' => 'Drop here',
            'drag_or_click' => 'Drag and drop a skin or click to choose',
            'format_hint' => 'PNG · 64×32 or 64×64',
            'choose_file' => 'Choose file',
            'title_label' => 'Title',
            'title_placeholder' => 'e.g. Mystical Warrior Skin',
            'description_label' => 'Description',
            'description_placeholder' => 'Tell others about your skin creation...',
            'tags_label' => 'Tags',
            'tags_placeholder' => 'e.g. fantasy, knight, blue',
            'tags_hint' => 'Up to 12 tags, comma-separated.',
            'downloadable' => 'Allow download',
            'downloadable_hint' => 'Allow other users to directly download your creation.',
            'visibility_label' => 'Visibility',
            'more_options' => 'More options',
            'credit_label' => 'Credit',
            'credit_placeholder' => 'Optional credit or attribution',
            'alt_text_label' => 'Alt text',
            'alt_text_subtitle' => 'This helps people using screen readers understand what your skin is about.',
            'alt_text_placeholder' => 'Describe what your skin looks like (optional)',
            'submit' => 'Publish',
            'cancel' => 'Cancel',
            'edit_in_editor' => 'Edit skin',
            'please_upload_skin' => 'Please upload a skin first.',
            'remixable' => 'Allow remixing',
            'remixable_hint' => 'Allow other users to remix your creation.',
        ],
        'edit' => [
            'title' => 'Edit skin creation',
            'description' => 'Edit your skin creation.',
            'heading' => 'Edit creation',
            'subtitle' => 'Update title, description, tags, or re-upload the skin.',
            'submit' => 'Save changes',
        ],
        'show' => [
            'download' => 'Download',
            'download_button' => 'Download skin',
            'open_in_editor' => 'Open in editor',
            'edit' => 'Edit details',
            'delete' => 'Delete',
            'delete_confirm' => 'Delete this creation? This cannot be undone.',
            'similar' => 'Similar creations',
            'created_at_ago' => 'Created :time',
            'updated_at_ago' => 'Updated :time',
            'created_and_updated' => 'Created :created · Updated :updated',
            'version_number' => 'Version :number',
            'version_history' => 'Version history',
            'iterations' => 'Iterations',
            'before_after' => 'Before & after',
            'previous' => 'Previous',
            'current' => 'Current',
            'tagged' => 'Tagged',
            'tagged_alt' => 'Tagged',
            'no_tags' => 'No tags',
            'stats' => 'Stats',
            'no_stats' => 'No stats',
        ],
        'validation' => [
            'invalid_skin_format' => 'Invalid skin format. Minecraft skins must be 64×32 or 64×64 PNG.',
            'tags_max_error' => 'You can add a maximum of 12 tags.',
        ],
        'deleted' => 'Creation deleted.',
        'download_disabled' => 'This creation is not available for download.',
        'editor' => [
            'save_to_gallery' => 'Save to gallery',
            'save_new_version' => 'Save new version',
            'save_updated_skin_version' => 'Save updated skin version',
            'save_as_new_creation' => 'Save as new creation',
            'published_successfully' => 'Your skin has been published successfully!',
            'saved_new_version' => 'New version saved.',
            'previous_skin_available' => 'A previously edited skin was found. Would you like to restore it?',
            'restore_skin' => 'Restore',
            'skin_loaded' => 'Skin loaded successfully',
            'preparing_upload' => 'Preparing your upload…',
            'bridge_fail_missing' => 'Your skin is still safe in the editor. Try saving to gallery again.',
            'bridge_fail_invalid' => 'Your skin is still safe in the editor. We couldn\'t use the saved copy — please try saving to gallery again.',
            'bridge_fail_server' => 'Your skin is still safe in the editor. Something went wrong — please try saving to gallery again.',
            'pending_replaced' => 'Your previous pending upload was replaced with your latest skin.',
            'claim_step' => 'Step 1 of 2',
            'claim_title' => 'Link your Minecraft account',
            'claim_description' => 'To publish skins to the gallery, link your Minecraft account first. This is a quick, one-time setup.',
            'claim_skin_safe' => 'Your skin is saved and will be ready to publish right after linking.',
            'claim_button' => 'Link Minecraft Account',
            'claim_reassurance' => 'Your skin is safe — you\'ll continue to publishing after linking.',
            'claim_posting' => 'Saving your skin…',
            'claim_fail' => 'Something went wrong — your skin is safe in the editor. Please try again.',
        ],
        'visibility' => [
            'public' => 'Public',
            'unlisted' => 'Unlisted',
            'draft' => 'Draft',
        ],
    ],
    'search' => [
        'meta' => [
            'title' => '검색 결과: :search',
        ],
        'what_are_you_searching_for' => 'What are you searching for?',
        'title' => '검색 결과',
        'results' => 'Page :current for :count result|Page :current of about :count results ',
        'results_count' => ':count result|:count results',
        'time' => '(:time초)',
        'username_available' => '사용자 이름 사용 가능*',
        'username_unavailable' => '사용자 이름 사용 불가',
        'username_status' => '상태',
        'username_status_available' => '사용 가능*',
        'username_status_unavailable' => '사용 불가',
        'username_searches' => '검색 수',
        'username_searches_count' => ':count/일',
        'username_available_disclaimer' => '*Mojang이 이 프로필 이름을 일시적 또는 영구적으로 차단하지 않은 경우',
        'no_results' => '어떠한 프로필도 찾지 못했어요. 검색 유형을 UUID로 바꿔 다시 검색해 보세요.',
        'no_results_tags' => '태그된 스킨을 찾지 못했어요. "blue", "girl", "fox" 등의 다른 태그로 검색해 보세요...',
        'again' => '다시 검색하기',
        'sorry' => '으아아아...',
        'view_profile' => '프로필 보기',
        'view_all' => 'View all',
        'filters' => 'Filters',
        'more_results' => 'more results',
        'more_results_fallback' => 'more results',
        'close' => 'Close',
        'clear_filters' => 'Clear all',
        'profiles' => 'Profiles',
        'verified_only' => 'Verified only',
        'verification' => 'Verification',
        'all' => 'All',
        'verified' => 'Verified',
        'not_verified' => 'Not verified',
        'country' => 'Country',
        'country_placeholder' => 'e.g. US, UK',
        'no_types_found' => 'No project types found for this search',
        'no_categories_found' => 'No categories found for this search',
        'featured' => 'Featured',
        'yes' => 'Yes',
        'no' => 'No',
        'skins' => 'Skins',
        'tags' => 'Tags',
        'no_tags_found' => 'No tags found for this search',
        'min_profiles' => 'Min profiles using',
        'try_different' => 'Try a different search term',
        'skins_no_results' => 'No skins found',
        'empty_state' => [
            'title' => 'No matches this time',
            'message' => "We didn't find any results for this search. Try adjusting your keywords or browsing instead.",
        ],
    ],
    'collection' => [
        'title' => 'Minecraft 스킨 모음집',
        'subtitle' => 'Minecraft 스킨의 짜깁기된 모음집을 통해 살펴보세요.',
        'filters' => '필터',
        'title_trending' => '인기 급상승',
        'title_all' => '모든 Minecraft 스킨',
        'skin_tags' => '태그된 스킨',
        'filters_skin_type' => '스킨 유형',
        'filter_skin_type_steve' => '스티브 유형',
        'filter_skin_type_alex' => '알렉스 유형',
        'cancel' => '취소',
        'apply' => '적용',
        'username_minecraft_skin' => ':username님의 Minecraft 스킨',
        'user_downloads' => '다운로드 <span class="fw-500">:downloads</span>회',
    ],
    'favourites' => [
        'title' => '즐겨찾기',
        'subtitle' => 'View and manage skins, heads, servers and banners you saved for later in your favourites list',
        'sort' => '정렬 기준',
        'toast' => [
            'added' => '즐겨찾기 목록에 추가했어요',
            'removed' => '즐겨찾기 목록에서 제거했어요',
            'login_required' => 'Sign in to add to favourites',
        ],
        'skins' => [
            'button' => '스킨',
            'empty_headline' => 'No skins saved yet.',
            'empty_subtitle' => 'Skins you save will appear here.',
            'empty_browse' => '스킨 둘러보기',
            'meta' => [
                'title' => '내가 즐겨찾기한 스킨',
                'description' => '내가 즐겨찾기에 저장한 Minecraft 스킨',
            ],
        ],
        'heads' => [
            'button' => 'Heads',
            'empty_headline' => 'No heads saved yet.',
            'empty_subtitle' => 'Heads you save will appear here.',
            'empty_browse' => 'Browse heads',
            'meta' => [
                'title' => 'My favourite heads',
                'description' => 'My favourite custom Minecraft heads',
            ],
        ],
        'creations' => [
            'heading' => 'Skin creations',
            'empty_headline' => 'No favourite skin creations yet',
        ],
        'servers' => [
            'button' => '서버',
            'empty_headline' => 'No servers saved yet.',
            'empty_subtitle' => 'Save servers you want to revisit later.',
            'empty_browse' => '서버 둘러보기',
            'meta' => [
                'title' => '내가 즐겨찾기한 서버',
                'description' => '내가 즐겨찾기한 Minecraft 서버',
            ],
        ],
        'banners' => [
            'button' => 'Banners',
            'empty_headline' => 'No banners saved yet.',
            'empty_subtitle' => 'Banners you save will be shown here.',
            'empty_browse' => 'Browse banners',
            'meta' => [
                'title' => 'My favourite banners',
                'description' => 'My favourite Minecraft banners',
            ],
        ],
    ],
    'cape' => [
        'editor' => [
            'title' => 'Minecraft 망토 편집기',
            'subtitle' => 'Minecraft 망투 편집기를 이용하여 나만의 맞춤 제작된 망토를 만들어보세요.',
            'meta' => [
                'title' => 'Minecraft 망토 편집기',
                'description' => 'Minecraft 망투 편집기를 이용하여 나만의 맞춤 제작된 망토를 만들어보세요.',
            ],
        ],
        'list' => [
            'title' => 'Minecraft 망토',
            'subtitle' => 'Minecraft의 공식 망토예요. 망토는 기념품이고 플레이어 스킨과 함께 착용돼요. 겉날개를 착용했을 때의 모습을 변경할 수도 있어요.',
            'meta' => [
                'title' => 'Minecraft 망토 목록',
                'description' => 'Minecraft cape list: View all official Minecraft capes including Mojang, Minecon, Personal, Special and vanity capes',
            ],
        ],
        'detail' => [
            'title' => ':cape 망토',
            'info' => '망토 정보',
            'profile_list' => '이 망토를 착용 중인 프로필',
            'profiles' => '프로필 :profiles개',
            'meta' => [
                'title' => ':cape Minecraft 망토',
                'description' => 'Check out the :cape Minecraft Cape and see players wearing it!',
            ],
        ],
        'list-custom' => [
            'title' => '맞춤 Minecraft 망토',
            'description' => 'SkinMC 멤버들이 만들고 사용 중인 커스텀 망토를 둘러보세요.',
        ],
    ],
    'servers' => [
        'title' => 'Minecraft 서버',
        'subtitle' => 'Minecraft 서버를 살펴보고 탐험해 보세요',
        'all' => '모든 서버',
        'manage_your_servers' => '내 서버 관리하기',
        'add_new_server' => '새 서버 추가',
        'filters' => [
            'trending' => '인기 급상승',
            'updated' => '업데이트됨',
            'new' => '신규',
            'most_viewed' => '최다 조회',
            'top_voted' => '상위 투표',
            'sorting' => '정렬',
            'sort_by_latest' => '최신순으로 정렬',
            'sort_by_oldest' => '오래된 순으로 정렬',
            'categories' => '분류',
            'server_location' => '서버 위치',
            'show_results' => '결과 보기',
            'show_more' => '더 보기',
            'show_less' => '덜 보기',
            'clear_filters' => '필터 초기화',
            'reviews' => '평가',
            'sort_by_highest_rating' => '높은 평점순으로 정렬',
            'sort_by_lowest_rating' => '낮은 평점순으로 정렬',
            'bedrock_and_java_support' => 'Bedrock 및 Java 지원',
            'sort_by' => 'Sort:',
            'sort_ranking' => 'Best',
            'sort_newest' => 'Newest',
            'sort_new_upcoming' => 'New & upcoming',
            'sort_most_players' => 'Most players',
            'sort_top_rated' => 'Top rated',
            'sort_most_votes' => 'Most votes',
        ],
        'review-count' => ':count 후기 ',
        'meta' => [
            'title' => 'Minecraft 서버 목록',
            'description' => '최고의 Minecraft 서버를 찾기 위해 Minecraft 서버 목록을 살펴보고 탐험해 보세요!
최신순, 최다 인기순 등으로 필터하세요',
        ],
        'reviews' => [
            'meta' => [
                'title' => '후기 작성하기',
            ],
            'editing' => 'You\'re editing your review from :date. Would you like to delete your review instead?',
            'welcome' => ':username님 안녕하세요. :servername 서버의 전반적인 경험은 어떠셨나요?',
            'subtitle' => 'Leave an overall score of your past experience with the server.',
            'scale' => [
                'great' => '매우 좋음',
                'good' => '좋음',
                'okay' => '괜찮음',
                'meh' => '그저그럼',
                'bad' => '별로임',
            ],
            'rate-experience' => '다음으로, 이곳에서의 경험을 평가해 주세요.',
            'overall' => '전반적인',
            'server-team' => '서버 팀',
            'community' => '커뮤니티',
            'experience' => '경험',
            'availablility' => 'Uptime and availability',
            'shop' => '상점',
            'write-review-title' => '후기 작성하기',
            'write-review-subtitle' => '노트를 조금 남겨보세요. 무엇을 즐겼는지 강조하고, 무엇이 경험을 특별하게 만들었는지, 아니라면 약간의 제안을 제공해주세요.',
            'write-review-helper' => '서버 리뷰를 작성해 새로운 플레이어와 당신의 경험을 공유하고, 피드백을 남겨 서버 소유자를 도와주세요.',
            'write-review-tips' => '여기 일부 팁들이 있어요',
            'submit-title' => '리뷰를 제출할 준비가 되었나요?',
            'submit-subtitle' => '거의 다 됐어요!',
            'submit-review' => '내 후기 등록하기',
            'back' => '돌아가기',
            'continue' => '계속',
            'delete-title' => '정말로 이 리뷰를 삭제하시겠어요?',
            'tos-checkbox-part-1' => '이 양식을 제출함으로써 귀하는 SkinMC의 서비스 약관, 개인정보 보호정책 및 커뮤니티 가이드라인에 동의하게 돼요. 또한 귀하는 모든 정보가 정확하고 다음 사항을 준수함을 확인해요.',
            'tos-checkbox-part-2' => '가이드라인을 검토하세요.',
            'tos-checkbox-part-3' => '이 리뷰는 제출 이후에 공개되지만, 검토 대상이 될 수 있어요.',
            'cannot_review_own_server' => 'You cannot review your own server.',
        ],
        'slots' => '슬롯',
        'empty-helper' => 'You can try to do another search.',
        'empty' => '흠 여전히 비어 있네요.',
        'verified' => '인등된',
        'review_translate_show_original' => '원본 보기',
        'review_translate' => '후기 번역하기',
        'description_translate' => '설명 번역하기',
        'create' => [
            'welcome' => '환영',
            'basics' => '기본',
            'categories' => '카테고리',
            'social_links' => '소셜 링크',
            'trailer_video' => '트레일러 영상',
            'images' => '이미지',
            'images_description' => 'You can upload photos afterwards, to showcase what your server offers.',
            'submit' => '등록',
            'lets_get_your_server_added' => '서버를 등록해봅시다.',
            'basics-subtitle' => '서버가 어떤 곳인지 사람들이 알게 해주세요.',
            'description' => '설명',
            'description_tips' => '여기 일부 팁이 있어요',
            'description_hint' => '새로운 플레이어의 이목을 끌 만한 좋은 설명을 작성해주세요.',
            'categories-subtitle' => '내 서버를 위해 카테고리를 선택하세요',
            'missing-category' => '카테고리가 안 보이시나요?',
            'social_links_description' => '플레이어는 소셜 미디어 어디에서 당신의 서버에 접속할 수 있나요?',
            'trailer_video_description' => '유튜브 영상으로 서버를 선보이세요.',
            'trailer_video_hint' => '내 영상 URL 또는 ID를 붙여넣기:',
            'ready_to_submit_your_server' => '서버를 등록할 준비가 되었나요?',
            'review-hint' => '제출 이후 우리 팀은 귀하의 서버 찾기 대기 신청서를 검토할 거예요. 서버는 검토 이후에 공개되거나 공개 전 내용 변경을 요청드릴 거예요.',
            'terms' => [
                'part-1' => '이 양식을 제출함으로써 귀하는 SkinMC의 서비스 약관, 개인정보 보호정책 및 커뮤니티 가이드라인에 동의하는 것으로 간주돼요. 또한 귀하는 위의 모든 정보가 정확하며, 다음 사항을 올바르게 준수했음을 확인해요.',
                'part-2' => '설정을 위한 서버 요구사항',
                'part-3' => ', and that the Minecraft server is owned and managed by the entity you are representing.',
            ],
            'submit-application' => '지원서 등록하기',
            'video-id-helper' => [
                'part-1' => 'The video ID is the string of numbers and letters after',
                'part-2' => '예를 들어 영상 url이',
                'part-3' => ', 그 다음 영상 ID가 나와요',
            ],
            'welcome_description' => '이 단계에서는 서버 등록을 진행할 거예요. 이곳에 대해 조금 알려주세요. 설명을 작성해 주시면 다음 단계에서는 이미지를 업로드 할 수 있어요.',
        ],
        'votes' => [
            'vote' => 'Vote',
            'voted' => 'Voted',
            'success' => 'Your vote has been recorded!',
            'login_required' => 'Please log in to vote for this server.',
            'profile_required' => 'Link your Minecraft account to vote.',
            'server_ineligible' => 'This server is not currently eligible for voting.',
            'self_vote_blocked' => 'You cannot vote for your own server.',
            'cooldown' => 'You can only vote once every 24 hours.',
            'cooldown_tooltip' => 'You can vote again :time',
            'count' => ':count vote|:count votes',
        ],
        'copy_server_ip' => '서버 IP 복사하기',
        'all_minecraft_servers' => '모든 Minecraft 서버',
        'promo' => [
            'title' => 'Minecraft 서버를 호스트 하시나요?',
            'ready_to_list_your_server' => '서버를 등록할 준비가 되었나요?',
            'everything_you_need' => '서버를 키우기 위해 필요한 모든 것',
            'list_your_server' => '내 서버 등록하기',
            'list_your_server_description' => '사진과 소셜 미디어 등을 추가해 서버를 등록해보세요.',
            'find_players' => '플레이어 찾기',
            'find_players_description' => 'Find and reach new players to join your server and grow your community.',
            'get_reviews' => 'Get reviews',
            'get_reviews_description' => '서버의 리뷰를 남기게 만들고, 게임 안에서 보상을 얻을 수 있게 하세요.',
            'why_list_on_skinmc' => 'Why you should list your Server on SkinMC',
            'others' => '기타',
            'quality_check_and_confirmation' => '퀄리티 체크 및 확인',
            'quality_check_description' => 'Our team reviews every server to ensure quality.',
            'verified_players' => '인증된 마인크래프트 유저들의 리뷰',
            'verified_players_description' => 'Collect authentic player reviews from legitimate accounts with Votifier integration.',
            'international' => '국제',
            'international_description' => 'With translation features your listing is available to more players.',
            'server_listing_page' => '효과적인 서버 정렬 페이지',
            'server_listing_page_description' => '사진, 설명, 유튜브 영상을 추가하고 서버를 돋보여서 플레이어들이 그곳에 참여하게 만드세요.',
            'social_connections' => 'SNS 연결',
            'social_connections_description' => '내 서버의 SNS 계정을 연결하여 새로운 플레이어들이 서버를 탐색할 때 보여줘요.',
            'verified_badge' => '인증 배지',
            'verified_badge_description' => '공인된 서버는 인증 배지를 신청할 수 있어요.',
            'owner_profile' => '오너 프로필',
            'owner_profile_description' => 'Add a personal touch, by completing your custom profile.',
            'categories' => '카테고리',
            'categories_description' => '여러 분류로 서버를 찾기 쉬워요.',
            'vote' => '투표',
            'vote_description' => '유저들에게 내 서버에 투표를 요청해요.',
            'review' => 'Review',
            'review_description' => 'Ask users to review your server.',
            'fair_listings' => '공정한 등록',
            'fair_listings_description' => 'Server listings can not be artificially boosted in results on SkinMC.',
            'support' => '24시간 지원',
            'support_description' => '도움이 필요하거나 궁금한 점이 있으신가요? 언제든지 문의해서 빠른 답변을 받아보세요.',
            'custom_features' => '맞춤 기능',
            'custom_features_description' => '서버에 없는 기능이 있나요? 티켓을 열면, 저희가 구현해 드릴게요.',
            'faq' => [
                'title' => '내 질문에 답변해요',
                'suited-question' => '제 Minecraft 서버가 SkinMC에 적합한가요?',
                'suited-answer' => 'Minecraft Players on SkinMC love to discover new experiences, content and engage with communities. On the platform you\'ll find a large variety of different, unique, fun Minecraft servers. From a large network to even a small survival server, it can make someones day!',
                'get-started-question' => '어떻게 시작하나요?',
                'get-started-answer' => 'Adding your Minecraft Server to the SkinMC Server List is very easy! You will first need to create an account, if you haven\'t already, and then follow the setup guide to get your server listed. Add a few photos and a nice description, and your server will be published in no time!',
                'players-question' => '내 Minecraft 서버에 더 많은 플레이어를 모으려면 어떻게 해야 하나요?',
                'players-answer' => 'Building a community is the most crucial part of a long lasting Minecraft Server. Use the Minecraft Server List on SkinMC to find a new audience and continue to build your community. Ask your players to recommend your Server, or share your listing on social media platforms. Collecting good reviews can also play an important role to a great Server listing presence that attracts new players.',
                'more-question' => '질문이 더 있어요. 도움은 어디서 받을 수 있나요?',
                'more-answer' => 'You can reach out to SkinMC at any time, 24 hours, by using either the help button, the help desk, or by joining the Discord server.',
            ],
            'ready_to_list_description' => '단 몇 분 만에 당신의 Minecraft 서버를 SkinMC 서버 목록에 추가해 보세요. 도움이 필요하시다면 언제든 요청하고 빠른 답변을 얻어보세요.',
        ],
        'manage' => [
            'index' => [
                'welcome' => '다시 돌아온걸 환영해요, :username',
                'your_servers' => '내 서버',
                'reviews_today' => '오늘의 후기',
                'no_reviews_today' => '오늘은 후기가 없어요',
                'no_reviews_text' => '서버가 오늘 아무 리뷰도 받지 못했어요. 플레이어들에게 한번 요청해보는 건 어떨까요?',
                'tips' => [
                    'title' => '팁',
                    'description-title' => '좋은 서버 설명을 작성하세요',
                    'description-body' => '최고의 서버 설명을 작성하기 위해 도움이 되는 팁과 조언들이에요.',
                    'images-title' => '서버 이미지 추가하기',
                    'images-body' => 'Make your server listing stand out with great images.',
                ],
            ],
            'listings' => [
                'title' => '내 Minecraft 서버 (:count개)',
            ],
            'insights' => [
                'title' => '현황판',
                'metrics' => [
                    'servers' => 'Servers',
                    'live_count' => ':count live',
                    'votes_30d' => 'Votes (30 days)',
                    'all_time_count' => ':count all-time',
                    'favorites' => 'Favourites',
                    'reviews_count' => ':count reviews',
                    'average_rating' => 'Average rating',
                    'pending_draft_count' => ':pending pending, :draft draft',
                ],
                'trends' => [
                    'votes_title' => 'Vote trend',
                    'reviews_title' => 'Review trend',
                    'last_days' => 'Last :days days',
                    'vs_previous' => 'vs previous period',
                ],
                'opportunities' => [
                    'title' => 'Top opportunities',
                    'click_to_view' => 'Click an item to view affected servers.',
                    'missing_photos_draft' => 'Draft listings blocked by missing photos',
                    'no_votes_30d' => 'Live servers with no votes in 30 days',
                    'low_completeness' => 'Listings below 75% completeness',
                    'low_rating' => 'Servers below 3.5 rating (3+ reviews)',
                    'meta_missing_photos' => ':count/5 photos',
                    'meta_no_votes_30d' => '0 votes / 30d',
                    'meta_incomplete' => ':score%',
                    'meta_low_rating' => ':rating/5',
                    'none' => 'No servers in this category.',
                ],
                'review_breakdown' => [
                    'title' => 'Review category breakdown',
                    'empty' => 'No review data yet.',
                    'weakest' => 'Weakest category: :category',
                ],
                'top_lists' => [
                    'by_favorites' => 'Top by favourites',
                    'by_votes_30d' => 'Top by votes (30 days)',
                    'lowest_rated' => 'Lowest rated (3+ reviews)',
                    'empty' => 'No server data available.',
                    'empty_votes' => 'No vote data available.',
                    'empty_ratings' => 'Not enough review data yet.',
                ],
                'table' => [
                    'server' => 'Server',
                    'status' => 'Status',
                    'listing_score' => 'Listing score',
                    'avg_rating' => 'Avg',
                    'votes_30d' => 'Votes 30d',
                    'votes_all' => 'Votes',
                    'last_review' => 'Last review',
                    'live' => 'Live',
                    'pending' => 'Pending',
                    'draft' => 'Draft',
                    'empty_title' => 'No servers yet',
                    'empty_subtitle' => 'Add your first listing to see insights.',
                ],
                'activity' => [
                    'title' => 'Recent activity',
                    'review' => 'Review',
                    'vote' => 'Vote',
                    'vote_summary' => 'New vote received',
                    'view_review' => 'View review',
                    'by_user' => 'by :user',
                    'unknown_user' => 'Unknown',
                    'empty_title' => 'No activity yet',
                    'empty_subtitle' => 'Votes and reviews will appear here.',
                ],
            ],
            'edit_server' => '서버 수정하기',
            'listing' => '정렬하기',
            'to_do' => '할 것',
            'last_update' => '최근 갱신',
            'add_more_photos_to_publish' => '더 많은 사진을 추가하여 게시하세요',
            'looks_empty_here' => '비어 있는거 같아요.',
            'get_started_by_adding_a_new_server' => '새 서버를 추가하면서 시작하시겠어요?',
        ],
        'status' => [
            'approved' => '승인됨',
            'pending_approval' => '승인 대기 중',
            'published' => '게시됨',
            'draft' => 'Draft',
            'need_more_images' => 'Need :count more to publish',
            'ready_for_approval' => 'Ready for approval',
            'in_review' => '검토중',
        ],
    ],
    'editor' => [
        'import' => [
            'title' => '스킨 가져오기',
            'import_by_username' => '사용자 이름으로 가져오기',
            'import_button' => '가져오기',
            'drag' => '스킨을 여기에 끌어다 놓거나, 클릭하세요',
            'click' => '이미지 선택',
        ],
        'download' => [
            'error' => [
                'no-data' => 'No skin data was provided. Please try again.',
                'invalid-format' => 'The skin data format is invalid. Please try again.',
                'invalid-data' => 'The skin data is corrupted. Please try again.',
                'generic' => 'Something went wrong while downloading your skin. Please try again.',
            ],
        ],
        'draw' => '그리기',
        'eyedropper' => '스포이드',
        'fill' => '채우기',
        'move' => '움직이기',
        'decrease_brightness' => '밝기 낮추기',
        'increase_brightness' => '밝기 높이기',
        'erase' => '지우기',
        'undo' => '뒤로 가기 (CTRL+Z)',
        'redo' => '앞으로 가기 (CTRL+Y)',
        'default_view' => '기본 보기',
        'zoom_in' => '확대 (CTRL +)',
        'zoom_out' => '축소 (CTRL -)',
        'saved' => '방금 마지막 저장되었어요',
        'saving' => '자동 저장 중...',
        'save_error' => '오류가 발생했어요',
        'new_skin' => '신규 스킨',
        'automatically_saved_skins' => 'Automatically saved skins',
        'recovered_skins' => 'Recovered skins',
        'load' => 'Load',
        'delete' => 'Delete',
        'backed_up_title' => '자동으로 저장된 스킨',
        'backed_up_info' => '로컬 저장소에 임시로 백업했어요.',
        'backed_up_empty_title' => '비어 있네요',
        'backed_up_empty_info' => '스킨을 편집하기 시작한 이후 가장 최근 32개의 스킨이 여기에 뜰 거예요.',
        'recovered_empty_title' => 'No recovered skins',
        'recovered_empty_info' => 'Recovered skins will appear here when you navigate away or close the editor.',
        'backed_up_skins_count' => '/32개의 스킨 백업이 사용됨',
        'backed_up_skins_count_info' => '최대 스킨 32개까지 백업할 수 있어요. 스킨 32개에 도달하면 옛 스킨이 새 스킨으로 대체돼요.',
        'layers' => '레이어',
        'body' => [
            'title' => '몸',
            'overlay' => '오버레이',
            'head' => '머리',
            'torso' => '몸통',
            'l_arm' => '왼쪽 팔',
            'r_arm' => '오른쪽 팔',
            'l_leg' => '왼쪽 다리',
            'r_leg' => '오른쪽 다리',
        ],
        'model' => '모델',
        'steve' => '스티브',
        'alex' => '알렉스',
        'stance' => [
            'title' => '위치',
            'default' => '기본',
            'walk' => '걷는 상태',
            'run' => '뛰는 상태',
            'hug' => 'T자 자세',
            'fly' => '나는 상태',
        ],
        'fullscreen' => '전체화면 하기',
        'fullscreen_exit' => '전체화면',
        'grid' => '그리드',
        'show_grid' => '그리드 보기',
        'download' => [
            'title' => '저장 및 다운로드',
            'subtitle' => 'SkinMC 계정',
            'description' => '현재 내 스킨과 이후의 스킨을 클라우드에 저장하기 위해 SkinMC 계정을 생성하시겠어요?',
            'start_description' => '클라우드에 저장하지 않고 바로 다운로드를 시작하세요',
            'start' => '스킨 다운로드',
        ],
        'help' => [
            'title' => 'Minecraft 스킨 편집기',
            'about' => 'SkinMC 편집기를 사용하여 커스텀 Minecraft 스킨을 쉽게 만들고 편집해 보세요. 스티브와 알렉스 모델 중에 고르거나 파일 또는 사용자명으로 스킨을 첨부하고 자신만의 Minecraft 스킨을 만드세요.',
            'draw' => 'Draw using the pen tool. Select a colour from the swatch to use with it.',
            'eyedropper' => 'Use the eyedropper to select a colour from your skin and add it to your current palette.',
            'fill' => 'Fill entire areas of your skin using the fill tool. Select a colour before using fill.',
            'move' => 'Pan and move around the skin editor canvas with the move tool.',
            'decrease_brightness' => '현재 사용 중인 색상의 밝기를 낮춰요.',
            'increase_brightness' => '현재 사용 중인 색상의 밝기를 높여요.',
            'erase' => 'Erase pixels drawn on the secondary overlay layer.',
            'minimap' => 'Minimap',
            'minimap_info' => 'The minimap can show you the skin texture in a flat view while in 3D mode. In 2D mode the minimap switches to a 3D preview of your skin. You can zoom in and out.',
            'autosave' => 'Autosave',
            'autosave_info' => 'The autosave feature saves your skin automatically every 30 seconds. You can access the autosaved skins in the editor by pressing the folder icon, and choosing "Previous skins".',
            '2d_editor' => '2D and 3D editor',
            '2d_editor_info' => 'Toggle between editing your Minecraft skin in 2D or 3D mode.',
        ],
    ],
    'account' => [
        'level' => '레벨',
        'level_history' => '레벨 기록',
        'xp' => '경험치',
        'my_xp' => '내 경험치',
        'xp_to_next_level' => '다음 레벨까지 :xp 경험치',
        'xp_info' => '경험치란 무엇인가요?',
        'xp_info_tooltip' => '경험치는 스킨에 태그를 추가하고, 친구를 초대하고, 댓글을 작성하는 등 다양한 활동으로 받을 수 있어요. 경험치를 충분히 받으면 레벨 업할 수 있고 여러 것들을 잠금 해제할 수 있어요!',
        'table' => [
            'description' => 'Description',
            'points' => 'Points',
        ],
        'my_stuff' => [
            'title' => 'My stuff',
            'creations' => 'Creations',
            'collections' => 'Collections',
            'favourites' => 'Favourites',
            'skins' => 'Manage skins',
            'capes' => 'Capes',
            'banners' => 'Banners',
            'servers' => 'Servers',
        ],
        'settings' => [
            'title' => '계정',
            'show_profile' => '프로필로 이동',
            'friends' => '친구',
            'friends_detail' => 'SkinMc의 친구 목록을 사용해서 계속 연락해 보세요.',
            'security' => '보안',
            'security_detail' => '로그인 비밀번호를 변경하고 계정을 안전하게 유지하세요',
            'social' => '소셜 미디어 계정',
            'social_detail' => '소셜 미디어를 추가해서 프로필을 맞춤 설정하세요',
            'link' => 'Minecraft 계정 연동',
            'link_detail' => 'Minecraft 계정을 연동해서 프로필을 등록하세요.',
            'logout' => 'SkinMC 계정에서 로그아웃하고 싶으신가요?',
            'automatic_backups' => '자동 저장된 스킨 백업',
            'automatic_backups_info' => 'SkinMC 플러스 회원으로서 스킨이 매일 백업돼요.',
        ],
        'capes' => [
            'title' => 'SkinMC Minecraft 망토',
            'description' => '무료로 게임 내에서 원하는 SkinMC 망토를 착용하세요.',
            'drop' => '망토를 여기에 끌어서 놓으세요',
            'drop-hint' => '크기: 64x32px',
            'select' => '이미지 선택',
            'upload-cape' => '업로드 및 망토 사용',
            'save-and-use' => '저장 및 사용',
            'uploaded-cape' => '업로드된 망토',
            'no-cape' => '망토 없음',
            'remove-cape' => '망토 제거',
            'download' => 'SkinMC 모드를 다운로드해서 나와 다른 플레이어의 망토를 게임 내에서 확인해 보세요.',
            'learn-more' => '자세히 알아보기',
            'link-account' => '망토를 업로드하려면 Minecraft 계정과 연동하세요.',
            'updated' => '망토가 갱신됐어요!',
            'removed' => '망토가 제거됐어요.',
            'active' => '망토가 활성화됐어요!',
        ],
        'favourite' => '즐겨찾기',
        'remove_favourite' => '즐겨찾기에서 삭제',
        'added_to_favourites' => '즐겨찾기에 추가됨',
        'removed_from_favourites' => '즐겨찾기에서 삭제됨',
        'welcome' => '만나서 반가워요!',
        'view-profile' => '내 프로필 보기',
        'security' => [
            'title' => '보안',
            'email' => '이메일 주소',
            'email-title' => '이메일 주소를 변경하세요.',
            'save' => '저장',
            'password' => '비밀번호',
            'password-title' => '비밀번호를 언제든지 변경하세요.',
            'social-provider' => '비밀번호와 같은 계정 정보를 업데이트하려면, 로그인 제공자에 방문해 주세요:',
            'social-provider-email' => '내가 로그인 제공자에 연결한 이메일 주소',
            'social-provider-connected' => '현재 연결한 로그인 제공자',
            'current-password' => '현재 비밀번호',
            'forgot' => '비밀번호를 잊으셨나요?',
            'edit' => '편집',
            'delete' => '계정 삭제',
            'account-deletion' => 'SkinMC 계정을 삭제하세요.',
            'delete-info' => '계속하려면 확인해 주세요',
            'delete-confirmation' => '계정을 삭제하는 것은 되돌릴 수 없어요. 모든 개인 정보와 게시물, 즐겨찾기, 업로드한 망토, 꾸민 것 등이 삭제되며 다시 복원할 수 없어요.',
            'delete-confirmation-info' => '계속하려면 비밀번호를 입력하세요',
            'delete-confirmation-info-social' => 'Type "delete" to confirm account deletion',
            'type-delete' => 'Type "delete" to confirm',
            'type-delete-label' => 'Type "delete" to confirm',
            'yes-confirm-delete' => '네, 삭제를 확인했어요',
            'account-successfully-deleted' => '계정과 데이터가 삭제됐어요.',
        ],
        'social' => [
            'title' => '소셜 계정',
            'edit' => '편집',
            'save' => '저장',
            'link-account' => 'Minecraft 계정을 SkinMC와 연동해서 내 프로필에 소셜 미디어 링크를 표시해 보세요.',
            'finish-setup' => '설정 완료하기',
            'connect-account' => '계정 연동',
            'connect-description' => '연동하고 싶은 계정을 고르고 특별한 SkinMC 연동을 잠금 해제하세요.',
            'empty' => '추가된 계정 없음',
            'empty-description' => '소셜 미디어 계정이 여기와 공개 프로필에 보일 거예요. 계정이 추가되면 더 개인화된 페이지를 만들 수 있고 연동을 사용할 수 있어요.',
            'connect' => '다음과 연동:',
            'username' => '사용자 이름',
            'spotify' => 'Spotify 계정 이름을 입력하고 SkinMC 프로필에 Spotify 프로필 정보를 표시해 보세요.',
            'discord' => 'Discord 사용자명과 태그를 입력하고 SkinMC 프로필에 Discord 계정 정보를 표시해 보세요.',
            'youtube' => 'YouTube 채널 이름을 입력하고 SkinMC 프로필에 YouTube 채널 정보를 표시해 보세요.',
            'youtube-format' => '채널 링크에 따라 다음 형식을 사용하세요:',
            'twitter' => 'Enter your X (formerly Twitter) username to display it on your profile.',
            'bluesky' => 'Enter your Bluesky handle e.g. username.bsky.social to display your Bluesky profile on your profile.',
            'twitch' => 'Twitch 채널 이름을 입력하고 SkinMC 프로필에 Twitch 채널 정보를 표시해 보세요.',
            'reddit' => 'Reddit 계정 이름을 입력하고 SkinMC 프로필에 Reddit 프로필 정보를 표시해 보세요.',
            'github' => 'GitHub 계정 이름을 입력하고 SkinMC 프로필에 GitHub 프로필 정보를 표시해 보세요.',
            'telegram' => 'Telegram 계정 이름을 입력하고 SkinMC 프로필에 Telegram 링크를 표시해 보세요.',
            'tiktok' => 'TikTok 계정 이름을 입력하고 SkinMC 프로필에 TikTok 프로필 정보를 표시해 보세요.',
            'snapchat' => 'Snapchat 계정 이름을 입력하고 SkinMC 프로필에 Snapchat 프로필 정보를 표시해 보세요.',
            'instagram' => 'Instagram 계정 이름을 입력하고 SkinMC 프로필에 Instagram 프로필 정보를 표시해 보세요.',
            'facebook' => 'Facebook 계정 이름을 입력하고 SkinMC 프로필에 Facebook 프로필 정보를 표시해 보세요.',
            'includes_skinmc_plus_benefits' => 'SkinMC 플러스 혜택 포함',
        ],
        'recover' => [
            'title' => '계정 복구',
            'subtitle' => '계정 복구를 완료하기 위해 새 비밀번호를 입력하고 확인하세요.',
            'new_password' => '새 비밀번호',
            'repeat_new_password' => '새 비밀번호 재입력',
            'submit' => '계정 복구',
        ],
        'customise' => [
            'title' => '프로필 맞춤 설정',
            'description' => '소셜 미디어를 추가하고, 이모지를 고르고, 위치 등을 추가해 보세요.',
            'information' => '정보',
            'preview' => '미리 보기',
            'location' => [
                'title' => '위치',
                'description' => '내 프로필에 추가하고 싶은 위치를 선택하세요.',
            ],
            'biography' => [
                'title' => '내 소개',
                'description' => '프로필에 관한 소개를 작성해 보세요.',
            ],
            'status' => '상태',
            'status-toggle' => '내 온라인 상태 표시',
            'emoji' => '이모지',
            'name-history-toggle' => '사용자 이름 기록을 비공개로 만들기',
            'name-history-info' => 'Minecraft 사용자 이름 기록이 현재',
            'name-history-toggle-on' => '비공개예요',
            'name-history-toggle-off' => '공개예요',
            'theme' => '프로필 테마',
            'theme-primary' => '기본',
            'theme-secondary' => '보조',
            'appearance' => '외관',
        ],
        'link' => [
            'manage' => '연동된 Minecraft 계정 관리',
            'description' => '연동된 Minecraft 계정을 보고 관리하세요',
            'title' => '연동된 Minecraft 계정',
            'current' => 'Minecraft 계정과 연동됐어요.',
            'status' => '이제 모든 SkinMC 기능을 사용할 수 있어요!',
            'linked' => '연동됨',
            'disconnect' => '연동 해제',
            'disconnect-title' => 'Minecraft 계정 연동 해제',
            'disconnect-info' => 'Minecraft 계정 연동을 해제하시겠어요?',
            'disconnect-features' => '댓글 기능, 맞춤 설정 기능과 같은 Minecraft 계정 연동이 필요한 기능을 이용할 수 없게 돼요. 다시 이용하려면 Minecraft 계정을 연동해야 해요.',
            'disconnect-following' => 'Minecraft 계정과 연동을 해제하면 팔로우 중인 프로필이 모두 삭제돼요.',
            'disconnect-posts' => '생성한 피드 게시물과 좋아요가 삭제될 거예요.',
            'can-not-undo' => '이 작업은 되돌릴 수 없어요.',
            'are-you-sure' => '확실하신가요?',
            'confirm' => '네, 연동이 해제됨을 확인했어요',
            'cancel' => '아니요, 취소할게요',
            'success' => '계정과의 연동이 해제됐어요!',
        ],
        'finish-setup' => [
            'title' => '계정 설정 완료하기',
            'description' => '계정 설정을 완료하고, Minecraft 계정을 SkinMC에 연동해서 모든 기능을 이용해 보세요!',
            'link' => 'Minecraft 계정 연동하기',
            'get-started' => '시작하기',
            'skip' => '건너뛰기',
            'download_skin' => 'Download skin',
            'claim' => '프로필 소유권 등록',
            'pending_upload' => 'Link your Minecraft account to finish publishing your skin.',
            'customise' => '페이지 맞춤 설정',
            'social' => '소셜 링크 추가',
            'comment' => '댓글 기능 사용',
            'direct_message' => '다이렉트 메시지 전송',
            'feed' => '피드에 게시물 상태 업데이트',
            'follow' => '친구와 팔로우',
            'badge' => '내 프로필에 배지 표시',
            'cape' => '맞춤 Minecraft 망토 이용 가능',
            'backup' => '자동 스킨 백업',
            'more' => '등등...',
        ],
        'creations' => [
            'title' => 'Creations',
            'published' => 'Published',
            'private' => 'Private',
            'unlisted' => 'Unlisted',
            'drafts' => 'Drafts',
            'empty_title' => 'No creations yet',
            'empty_published' => 'You have no published creations. Upload a skin and set visibility to "Public" to show it here.',
            'empty_private' => 'You have no private (unlisted) creations.',
            'empty_unlisted' => 'You have no unlisted creations.',
            'empty_drafts' => 'You have no drafts. Save a creation as draft from the editor or upload page.',
            'empty_browse' => 'Browse gallery',
            'empty_upload' => 'Upload skin',
            'meta' => [
                'title' => 'My creations',
                'description' => 'View and manage your skin creations.',
            ],
        ],
        'banners' => [
            'title' => 'Banners',
            'published' => 'Published',
            'drafts' => 'Drafts',
            'empty_title' => 'No banners yet',
            'empty_published' => 'You have no published banners. Create a banner in the editor and publish it to show it here.',
            'empty_drafts' => 'You have no draft banners. Create a banner in the editor without publishing to save as draft.',
            'empty_browse' => 'Browse gallery',
            'empty_create' => 'Create banner',
            'meta' => [
                'title' => 'My banners',
                'description' => 'View and manage your Minecraft banners.',
            ],
        ],
        'skins' => [
            'title' => '스킨 관리',
            'subtitle' => 'Choose which skins appear on your profile. Your current Minecraft skin is always shown.',
            'toggle' => '스킨 공개상태가 전환되었어요',
            'section_currently_worn' => 'Currently worn in Minecraft',
            'section_profile_skins' => 'Skins on your profile',
            'active_badge' => 'Active in Minecraft',
            'active_synced_copy' => 'Synced from your Minecraft account.',
            'active_action_copy' => 'Always visible on your profile. To hide it, change your skin in Minecraft.',
            'open_minecraft_skin_settings' => 'Open Minecraft skin settings',
            'show_on_profile' => 'Show on profile',
            'show_on_profile_tooltip' => 'Controls visibility on your SkinMC profile.',
            'empty' => 'No skins in your history yet. Skins you wear in Minecraft will appear here.',
            'empty_other' => 'No other skins yet. Skins you have worn will appear here; you can show or hide them on your profile.',
            'empty_not_claimed_title' => 'Link your Minecraft account',
            'empty_not_claimed' => 'Connect your Minecraft account to see your skin history and choose which skins appear on your profile.',
        ],
        'invite' => [
            'title' => '내 초대',
            'headline' => '친구를 초대하세요',
            'info' => '친구와 공유할 초대 링크를 생성하세요. 친구가 수락하면, 친구와 나 모두 추가 경험치를 얻을 수 있어요!',
            'description' => '친구에게 초대장을 생성하면 친구와 나 모두 추가 경험치를 얻을 수 있어요.',
            'generate' => '초대 코드 생성',
            'empty' => '어떤 초대장도 생성하지 않았어요.',
            'code' => '코드',
            'expiry' => '각 코드는 한 번만 작동돼요.',
            'status' => [
                'title' => '상태',
                'pending' => '대기 중',
                'accepted' => '수락됨',
            ],
            'add_invite' => [
                'button' => '초대장이 있으신가요?',
                'title' => '초대 코드 추가',
                'redeem' => '초대 긁기',
            ],
            'share' => '초대 링크를 친구에게 전송하세요',
        ],
        'emoji' => [
            'title' => 'SkinMC 이모지',
            'introducing' => '소개하기',
            'info' => '이모지로 프로필을 꾸미세요. 레벨 업을 통해 더 많은 이모지를 사용하세요.',
            'unlocked_at' => ':level레벨에 잠금 해제',
            'unlocks_at' => ':level레벨에 도달해서 잠금 해제',
            'turn_off' => '이모지 보기',
        ],
    ],
    'notifications' => [
        'title' => '알림',
        'view_all' => '모두 보기',
        'view_all_notifications' => '모든 알림 보기',
        'image' => '알림 사진',
        'archived' => '보관함',
        'inbox' => '수신함',
        'settings' => [
            'title' => 'Notification settings',
            'open' => 'Open notification settings',
            'save' => 'Save',
            'saved' => 'Notification settings updated.',
            'server_owner_alerts' => [
                'title' => 'Server owner alerts',
                'description' => 'Receive reminders and listing insights to help keep your server visible and up to date.',
                'toggle' => 'Enable server owner alerts',
                'unavailable' => 'This alert preference is managed globally by the administrators.',
            ],
        ],
        'empty' => [
            'title' => '다 읽으셨어요!',
            'text' => '새 알림이 여기에 표시될 거예요.',
            'text-archived' => '보관된 알림이 여기에 표시될 거예요.',
        ],
        'action' => [
            'archive' => '보관함으로 이동하기',
            'unarchive' => '보관 해제하기',
            'open' => '탭해서 열기',
        ],
        'toast' => [
            'archive' => '알림을 보관함으로 이동했어요',
            'unarchive' => '알림을 수신함으로 이동했어요',
            'undo' => '되돌리기',
        ],
    ],
    'error' => [
        'offline' => [
            'title' => '인터넷 연결 없음',
            'subtitle' => '인터넷에 연결되지 않았어요. 연결을 확인하고 페이지를 다시 불러와서 다시 시도하세요.',
            'try_again' => '다시 시도하기',
        ],
        '404' => [
            'title' => '404 - 페이지를 찾지 못함.',
            'subtitle' => '흠, 이 위치에 아무것도 없는 것 같아요. 다시 돌아가거나, 새로 검색해보시는 건 어떠세요?',
            'try_again' => '홈으로 돌아가기',
        ],
    ],
    'heads' => [
        'list' => [
            'meta' => [
                'title' => 'Minecraft 머리 데이터베이스',
                'description' => 'Explore the database of Minecraft heads to decorate your world with, or generate your own give command. View official heads, player heads and custom heads that feature textures which never change.',
            ],
            'header' => [
                'title' => 'Minecraft 머리',
                'subtitle' => 'Explore our database of Minecraft heads to decorate your world, or generate your own give command. Player heads show the current skin worn by a user, and can change as the user updates their skin. Custom heads are linked to the Mojang skin file and never change. Custom heads must be summoned using a command block as the command is very long.',
            ],
            'count' => [
                'heads' => '머리 :heads개',
            ],
            'customheads' => [
                'title' => '사용자 지정 머리',
                'description' => '사용자 지정 머리는 Mojang 서버의 텍스처 파일에 직접적인 경로를 사용해요. 따라서 텍스처는 절대 삭제되지 않고 머리가 변하지 않아요.',
                'version' => 'Minecraft 1.8 이후',
            ],
            'playerheads' => [
                'title' => '플레이어 머리',
                'description' => '플레이어 머리는 Minecraft 플레이어의 현재 스킨 텍스처를 사용해요. 플레이어 머리는 사용자 이름을 기반으로 하기 때문에, 플레이어가 이름이나 스킨을 바꾸면, 머리가 바뀌어요.',
                'version' => '모든 Minecraft 버전',
            ],
        ],
    ],
    'mod' => [
        'title' => 'SkinMC 모드: 무료 커스텀 망토',
        'headline' => '더 많은 맞춤 설정이 있는 SkinMC 모드를 소개할게요',
        'description' => 'Giving back to the Minecraft community, with a free mod which enables players more customisation with custom capes, available and visible for anyone using the mod.',
        'download' => '지금 다운로드',
        'download-title' => '모드를 다운로드해 보세요',
        'requires' => '필수 항목:',
        'select-version' => 'Minecraft 버전을 고르세요',
        'get-started' => '시작하는 건 간단해요',
        'step-1' => '1. 모드를 다운로드하세요',
        'step-1-detail' => 'Fabric을 설치하고, 게임 버전에 맞는 모드를 다운로드하고 모드 폴더에 jar을 넣어 모드를 설치하세요.',
        'step-2' => '2. 내 계정과 연동하세요',
        'step-2-detail' => '아직 하지 않으셨다면, 로그인/가입 후 Minecraft 계정을 SkinMC와 연동하세요.',
        'step-3' => '3. 망토를 업로드하세요',
        'step-3-detail' => '내 계정으로 이동하고 맞춤 망토를 업로드하세요. 게임 내에서 보일 거예요.',
        'all-versions' => '모든 버전',
        'latest' => '최신',
        'logged-in' => '망토 업로드하기',
        'mirror' => '미러',
        'download-via' => '다음을 통해 다운로드:',
        'curseforge' => 'CurseForge',
    ],
    'app' => [
        'title' => 'SkinMC Android 앱',
        'headline' => 'SkinMC Android 앱을 만나보세요.',
        'play-store-attribution' => 'Google Play 및 Google Play 로고는 Google LLC의 상표입니다.',
        'features' => '이동 중에도 편리한 기능',
        'feature-qr' => '자체 제작된 QR 코드 스캐너',
        'feature-qr-detail' => 'Use the built in QR-Code scanner to easily get a skin from your Desktop to the app, or scan your friends custom profile QR-Code.',
        'feature-files' => '파일에 바로 저장하기',
        'feature-files-detail' => 'Android Files Manager를 이용하면 스킨을 간편하게 저장할 수 있고 Bedrock 에디션에 쉽게 적용할 수 있어요.',
        'feature-noads' => '광고 제거',
        'feature-noads-detail' => '복잡하지 않은 깔끔하게 디자인된 인터페이스. 웹에서 앱까지 성가신 광고 없는 경험을 즐기세요.',
        'feature-experience' => '경험하기',
        'feature-experience-detail' => 'Enjoy the full SkinMC experience anywhere, with added features. Customise your profile, add your bio, create a fun QR-Code and more!',
        'get-app-headline' => 'SkinMC 앱 받기',
        'get-app-detail' => 'Android를 위한 당신만의 Minecraft 동반자 — 무료로 사용 가능.',
    ],
    'random' => [
        'title' => '랜덤 Minecraft 스킨 불러오기',
        'description' => '랜덤 Minecraft 스킨 불러오기',
        'headline' => '잠시 기다려주세요...',
        'redirect' => '자동으로 리다이렉트될 거예요. 페이지가 불러와지지 않나요?',
        'click-here' => '여기를 누르세요',
        'messages' => [
            '1' => '무작위 Minecraft 스킨을 불러오는 중...',
            '2' => '땅굴 파는 중...',
            '3' => '이런, 또 크리퍼가 나타났어!',
            '4' => '상자를 샅샅이 찾는 중',
            '5' => '다음 스킨은 완전히 무작위라는 걸 아시나요?',
            '6' => '무작위 스킨 나오는 중...',
            '7' => '한 블록만 더...',
            '8' => '보관함 정렬 중...',
            '9' => '다이아몬드 곡괭이 제작 중...',
            '10' => '히로빈 찾는 중...',
        ],
    ],
    'feed' => [
        'title' => '피드',
        'following' => '팔로우 중',
        'sign-up' => '가입하거나 로그인해서 대화에 참여하세요.',
        'link-account' => 'Minecraft 계정을 연동해서 대화에 참여하세요.',
        'placeholder' => '무엇이 일어나고 있나요?',
        'audience' => '듣는 이',
        'audience-title' => '누가 이걸 볼 수 있나요?',
        'everyone' => '모두',
        'everyone-info' => 'SkinMC에 있는 누구나',
        'followers' => '팔로워',
        'followers-info' => '로그인했거나 나를 팔로우하는 사람만',
        'private' => '나만',
        'private-info' => '나 자신만 볼 수 있는 비공개 게시물',
        'submit' => '게시물',
        'like' => '좋아요',
        'comment' => '답장',
        'share' => '공유',
        'share_dialog' => [
            'title' => 'Share',
            'subtitle' => 'Share this page with friends',
            'native' => 'Share via device',
            'copy_link' => 'Copy link',
            'social' => 'Popular networks',
            'copied' => 'Link copied!',
            'native_failed' => 'Could not open the share menu.',
            'native_unsupported' => 'Native sharing is not available on this device.',
            'close' => 'Close',
            'networks' => [
                'x' => 'Share on X',
                'facebook' => 'Share on Facebook',
                'reddit' => 'Share on Reddit',
                'whatsapp' => 'Share on WhatsApp',
                'telegram' => 'Share on Telegram',
                'email' => 'Share by email',
                'bluesky' => 'Share on Bluesky',
                'pinterest' => 'Pin on Pinterest',
            ],
        ],
        'remaining' => '남아있는',
        'profile' => ':username님의 게시물',
        'posts' => '모든 게시물',
        'my-posts' => '내 게시물',
        'view-all' => '모든 게시물 보기',
        'post' => [
            'meta' => 'SkinMC:에 :username :text',
            'title' => '게시',
            'created' => '상태 갱신 계시됨!',
            'confirm-delete' => '게시물을 삭제하시겠어요? 삭제하면 되돌릴 수 없어요.',
            'delete' => '게시물 삭제하기',
            'deleted' => '게시물이 삭제되었어요.',
        ],
        'repost' => [
            'button' => 'Repost',
            'quote_button' => 'Quote',
            'title' => 'Repost this post',
            'quote_title' => 'Quote post',
            'quote_label' => 'Add a comment (optional)',
            'quote_placeholder' => 'Add your thoughts...',
            'reposted' => 'reposted',
            'success' => 'Reposted!',
            'removed' => 'Repost removed.',
            'already_reposted' => 'You have already reposted this.',
            'undo' => 'Undo repost',
            'original_deleted' => 'The original post has been deleted.',
            'deleted_post' => 'This post has been deleted',
        ],
        'hashtags' => [
            'title' => 'Trending',
            'trending-now' => 'Trending now',
            'post' => 'post',
            'posts' => 'posts',
            'posts-count' => ':count post|:count posts',
            'hashtag' => 'Hashtag',
            'hashtags' => 'Hashtags',
            'no-results' => 'No hashtags found',
        ],
        'search' => [
            'title' => 'Search',
            'placeholder' => 'Search posts, hashtags...',
            'no-results' => 'No results found',
            'posts' => 'Posts',
            'no-hashtags-found' => 'No hashtags found matching ":query"',
            'no-results-found' => 'No results found for ":query"',
        ],
        'poll' => [
            'title' => 'Poll',
            'create' => 'Create a poll',
            'option' => 'Option',
            'add_option' => 'Add option',
            'duration' => 'Duration',
            'duration_1' => '1 day',
            'duration_3' => '3 days',
            'duration_7' => '7 days',
            'votes' => '{0} votes|{1} vote|[2,*] votes',
            'ended' => 'Poll ended',
            'ends_in' => 'Ends :time',
            'login_required' => 'Sign in to vote',
        ],
        'gif' => [
            'title' => 'GIF',
            'search_placeholder' => 'Search KLIPY for GIFs...',
            'no_results' => 'No GIFs found',
            'powered_by' => 'Powered by',
            'categories' => 'Categories',
            'trending' => 'Trending',
        ],
        'embed' => [
            'title' => 'Embed',
            'attach' => 'Attach',
            'attached' => 'Attached',
            'share_to_feed' => 'Share to feed',
            'search_placeholder' => 'Search by name or username',
            'loading' => 'Searching attachments...',
            'relevant_for_you' => 'Relevant for you',
            'no_relevant' => 'No personal suggestions yet. Start typing to search.',
            'start_typing' => 'Start typing to search attachments.',
            'no_results' => 'No matching attachments yet. Try another search.',
            'invalid' => 'Could not find that attachment. Please select it again.',
            'unavailable' => 'Attachment unavailable',
            'too_many_attachments' => 'You can only attach one item per post.',
            'types' => [
                'skin' => 'Skin',
                'skin_creation' => 'Skin creation',
                'server' => 'Server',
                'banner' => 'Banner',
                'cape' => 'Cape',
            ],
            'cape_subtitle' => [
                'official' => 'Official cape',
                'optifine' => 'OptiFine cape',
                'custom' => 'Custom cape',
            ],
        ],
        'image_preview' => [
            'image_singular' => 'image',
            'image_plural' => 'images',
            'selected' => 'selected',
            'clear_all' => 'Clear all',
            'selected_image_preview' => 'Selected image preview',
            'texture_upload_hint' => 'This image appears to be a Minecraft skin or cape texture. Please upload it properly as a skin or cape first, then share it to the feed from there.',
            'skin_upload' => 'Skin Upload',
            'cape_upload' => 'Cape Upload',
            'compress_image' => 'Compress Image',
        ],
        'image_too_large' => 'Your image exceeds :size',
        'compress_first' => 'Compress the image first.',
        'media' => 'Media',
        'follow-suggestions' => '팀 팔로우하기',
        'explore' => '둘러보기',
        'hashtag' => '해시태그',
        'no_users' => 'No users found.',
        'stories' => [
            'archive' => [
                'title' => 'Story Archive',
                'subtitle' => 'Your archived stories are only visible to you',
                'empty' => 'No archived stories yet',
                'empty-description' => 'Stories you post will appear here after 24 hours.',
                'action' => 'Archive',
                'archived' => 'Story moved to archive.',
                'already-archived' => 'Story is already archived.',
            ],
        ],
    ],
    'private' => [
        'title' => '게시물을 비공개로 돌리기',
        'text' => '이 게시물은 비공개입니다.',
    ],
    'liked' => [
        'title' => '좋아요 누름',
    ],
    'following' => [
        'title' => '팔로잉',
        'text' => '로그인하여 게시물을 확인하세요.',
    ],
    'tags' => [
        'empty' => '투표할 태그가 아직 없어요',
        'empty-subtitle' => '가장 먼저 추가해 보세요',
    ],
    'inbox' => [
        'title' => '메시지',
        'details' => '설명',
        'message_user' => '메시지 보내기',
        'write_message' => '메시지 작성하기',
        'empty' => [
            'no_message_selected' => '메시지가 선택되지 않음',
            'open_or_start_conversation' => '메시지 목록에서 대화를 열거나, 새롭게 하나 시작해 보세요.',
            'no_messages' => '읽지 않은 메시지 없음',
            'start_conversation' => '신규 대화를 시작하면, 내 메시지가 여기에 표시돼요.',
            'conversation' => ':username님과 나눈 대화의 첫 부분이에요.',
            'users' => '현재 검색어와 일치하는 사용자를 찾지 못했어요.',
        ],
        'typing' => ':username님이 입력 중이에요...',
        'new_message' => '신규 메시지',
        'mark_unread' => '읽지 않음으로 표시',
        'send_message' => '메시지 전송',
        'delete_message' => '나를 위해 메시지 삭제하기',
        'latest_conversations' => '최근 대화',
        'delete_conversation' => '대화 삭제',
        'show_details' => '설명 펼쳐보기',
        'hide_details' => '설명 숨기기',
        'unread' => '읽지 않음',
        'deleted' => '삭제되었어요',
        'report_message' => '메시지 신고',
        'add_reaction' => '반응 추가',
        'today' => '오늘',
        'reconnect' => '채팅을 사용하려면 Minecraft 계정을 다시 연결하세요',
        'account_disconnected' => '해당 사용자는 Minecraft 계정 연동을 해제했어요.',
        'saved_messages' => '메시지 저장됨',
        'new_message_to_label' => '에게',
        'external-link-to' => '이 링크는 다음으로 연결돼요:',
        'external-link-confirmation' => '확실히 거기로 이동할까요?',
        'external-link' => '외부 링크',
        'reply' => '답장',
    ],
    'server' => [
        'manage' => [
            'stats' => '통계',
        ],
    ],
    'report' => [
        'button' => '신고',
        'title' => '콘텐츠 신고',
        'describe' => '이걸 신고하는 이유를 간략히 설명해 주세요',
        'select' => '신고 사유를 선택하세요',
        'submit' => '신고 제출',
        'reasons' => [
            'INAPPROPRIATE_CONTENT' => '부적절한 콘텐츠',
            'SPAM' => '스팸',
            'HARASSMENT' => '괴롭힘',
            'OTHER' => '그 외',
        ],
    ],
    'leaderboard' => [
        'title' => '순위표',
        'description' => 'SkinMc 유저 순위표를 봐요.',
        'headline' => '상위 10명',
        'all-time-invites' => '전체 초대',
        'all-time-xp' => '전체 경험치',
        '30-day-xp' => '30일 경험치',
    ],
    'boards' => [
        'title' => 'Boards',
        'meta_title' => 'My Boards',
        'meta_description' => 'Organize your saved Minecraft skins, creations, and banners into boards.',
        'all_pins' => 'All Pins',
        'save' => 'Save',
        'saved' => 'Saved',
        'save_to_board' => 'Save to board',
        'save_to_label' => 'Save to: :board',
        'saved_to_label' => 'Saved to :board',
        'choose_board' => 'Choose board',
        'search_boards' => 'Search',
        'no_boards' => 'No boards yet',
        'no_boards_match' => 'No boards found',
        'create_board' => 'Create board',
        'create' => 'Create',
        'cancel' => 'Cancel',
        'add' => 'Add',
        'create_placeholder' => 'Like "Medieval Builds" or "PvP Loadouts"',
        'field_name' => 'Name',
        'secret_label' => 'Secret',
        'secret_description' => 'So only you and collaborators can see it.',
        'keep_secret' => 'Keep this board secret',
        'add_collaborators' => 'Add collaborators (optional)',
        'collaborator_search_placeholder' => 'Search by name or email',
        'edit_board' => 'Edit board',
        'leave_board' => 'Leave board',
        'leave_board_confirm' => 'Leave this board? You will no longer be able to add pins to it.',
        'delete_board' => 'Delete board',
        'delete_confirm' => 'Are you sure you want to delete this board? All pins will be removed.',
        'empty_headline' => 'No pins yet',
        'empty_subtitle' => 'Start saving skins, creations, and banners to this board.',
        'empty_boards_headline' => 'No boards yet',
        'empty_boards_subtitle' => 'Save your first skin to automatically create a board.',
        'browse_skins' => 'Browse skins',
        'pins_count' => '{0} No pins|{1} 1 pin|[2,*] :count pins',
        'secret_badge' => 'Secret',
        'public_boards' => 'Boards',
        'collaborator_unknown_user' => 'Someone',
        'collaborating' => 'Collaborating',
        'your_boards' => 'Your boards',
        'boards_you_collaborate_on' => 'Boards you collaborate on',
        'empty_collaborating' => 'No boards you collaborate on yet.',
        'toast' => [
            'saved_to' => 'Saved to :board',
            'removed' => 'Pin removed',
            'created' => 'Board created',
            'updated' => 'Board updated',
            'deleted' => 'Board deleted',
            'collaborator_added' => 'Collaborator added',
            'collaborator_removed' => 'Collaborator removed',
            'left_board' => 'You left the board',
        ],
    ],
];
