<?php

return [
    'skins' => 'Skins',
    'avatars' => 'Avatares',
    'editor' => 'Editor',
    'heads' => 'Cabeças',
    'capes' => 'Capas',
    'servers' => 'Servidores',
    'achievement' => 'Conquistas',
    'armor' => 'Suporte de armadura',
    'banners' => 'Banners',
    'profile' => 'Meu perfil',

    'generators' => 'Geradores',

    'logout' => 'Sair',
    'register' => 'Criar conta',
    'login' => 'Entrar',
    'about' => 'Sobre',
    'contact' => 'Contato',
    'faqs' => 'Perguntas frequentes',

    'minecraft_name' => 'Nome no Minecraft',
    'minecraft_uuid' => 'UUID do Minecraft',
    'what' => 'Que',
    'recent_searches' => 'Buscas recentes',
    'username' => 'Nome de usuário',
    'uuid' => 'UUID',
    'search' => 'Buscar',
    'search_placeholder' => 'Tente',
    'search_placeholder_uuid' => 'Inserir UUID',
    'start_search' => 'Iniciar pesquisa',
    'cancel_search' => 'Cancelar',
    'search_type' => 'Tipo de busca',
    'search_type_all' => 'Todos os resultados',
    'profiles' => 'Perfis',
    'view_skin' => 'Ver skin',
    'edit_skin' => 'Editar tema',
    'make_avatar' => 'Criar avatar',
    'find_heads' => 'Buscar cabeça de jogadores',

    'home' => 'Início',
    'help' => 'Ajuda',
    'tools' => 'Ferramentas',
    'more-tools' => 'Mais ferramentas',
    'skin_viewer' => 'Visualizador de skins',
    'avatar_maker' => 'Criador de avatar',
    'collections' => 'Coleções',
    'popular_skins' => 'Skins em alta',
    'cartoon_skins' => 'Skins de animação',
    'animal_skins' => 'Skin de animais',
    'community' => 'Comunidade',
    'imprint' => 'Informações',
    'cookies' => 'Cookies',
    'terms' => 'Termos de serviço',
    'privacy' => 'Política de privacidade',
    'app' => 'Aplicativo',
    'mod' => 'Mod',
    'totem' => 'Totens',

    'feedback' => 'Feedback',
    'status' => 'Status',
    'recent_searches_placeholder' => 'Ao começar a buscar, suas buscas anteriores aparecerão aqui.',
    'recent_views_placeholder' => 'Após visitar alguns perfis, os visitados recentemente serão exibidos aqui.',
    'moderate' => 'Moderar',
    'listings' => 'Listagens',
    'add' => 'Adicionar',

    'theme' => [
        'dark' => 'Escuro',
        'light' => 'Claro',
        'auto' => 'Automático'
    ],
];
