<?php

return [
    'skins' => 'Skins',
    'avatars' => 'Foto de Perfil',
    'editor' => 'Editor Skin',
    'heads' => 'Cabeças',
    'capes' => 'Capas',
    'servers' => 'Servidores',
    'achievement' => 'Conquistas',
    'armor' => 'Suporte de Armaduras',
    'banners' => 'Banners',
    'profile' => 'Meu Perfil',

    'generators' => 'Generators',

    'logout' => 'Sair',
    'register' => 'Criar conta',
    'login' => 'Entrar',
    'about' => 'Sobre',
    'contact' => 'Contato',
    'faqs' => 'Perguntas frequentes',

    'minecraft_name' => 'Nome no Minecraft',
    'minecraft_uuid' => 'UUID do Minecraft',
    'what' => 'O quê',
    'recent_searches' => 'Pesquisas recentes',
    'username' => 'Nome de usuário',
    'uuid' => 'UUID',
    'search' => 'Pesquisar',
    'search_placeholder' => 'Tentar',
    'search_placeholder_uuid' => 'Informe o UUID',
    'start_search' => 'Iniciar busca',
    'cancel_search' => 'Cancelar',
    'search_type' => 'Tipo de pesquisa',
    'search_type_all' => 'Todos os resultados',
    'profiles' => 'Perfis',
    'view_skin' => 'Ver skin',
    'edit_skin' => 'Editar tema',
    'make_avatar' => 'Criar avatar',
    'find_heads' => 'Procurar cabeças',

    'home' => 'Início',
    'help' => 'Ajuda',
    'tools' => 'Ferramentas',
    'more-tools' => '+ Ferramentas',
    'skin_viewer' => 'Skins',
    'avatar_maker' => 'Criador de avatar',
    'collections' => 'Coleções',
    'popular_skins' => 'Skin populares',
    'cartoon_skins' => 'Cartoon skins',
    'animal_skins' => 'Skin de animais',
    'community' => 'Comunidade',
    'imprint' => 'Informações',
    'cookies' => 'Cookies',
    'terms' => 'Terms of Service',
    'privacy' => 'Privacy policy',
    'app' => 'App',
    'mod' => 'Mod',
    'totem' => 'Totems',

    'feedback' => 'Feedback',
    'status' => 'Status',
    'recent_searches_placeholder' => 'Ao começar a pesquisar, suas pesquisas anteriores aparecerão aqui.',
    'recent_views_placeholder' => 'Após visitar alguns perfis, os visitados recentemente serão exibidos aqui.',
    'moderate' => 'Moderar',
    'listings' => 'Listagens',
    'add' => 'Adicionar',

    'theme' => [
        'dark' => 'Dark',
        'light' => 'Light',
        'auto' => 'Automatic'
    ],
];
