<?php

return [
    'auth' => [
        'login' => [
            'title' => 'Bem-vindo ao SkinMC',
        ],
        'register' => [
            'title' => 'Registre-se no SkinMC',
            'subtitle' => 'Inicie e crie sua conta para ter acesso total.'
        ]
    ],

    'home' => [
        'hero_slogan' => 'Seu lugar para Skins de Minecraft.',
        'hero_slogan_alt_1' => 'Everything Minecraft. One place.',
        'hero_slogan_alt_2' => 'Where Minecrafters meet.',
        'hero_cta' => 'Surpreenda-me',
        'hero_explore_cta' => 'Explorar skins',
        'skin_viewer' => 'Skins',
        'skin_viewer_detail' => 'Navegar por :count skins',
        'skin_editor' => 'Editor de skin',
        'skin_editor_detail' => 'Crie sua própria skin',
        'avatar_maker' => 'Gerador de Avatar',
        'avatar_maker_detail' => 'Gere suas fotos de perfil de avatar do Minecraft.',
        'trending' => 'Em destaque',
        'minecraft_skin' => 'Skin do Minecraft',
        'favourite' => 'Favorito',
        'collections' => 'Coleções',
        'collections_detail' => 'Coleções de Skins para cada ocasião',
        'about_skinmc' => 'Sobre o SkinMC',
        'about_find' => 'Encontre uma skin',
        'about_find_detail' => 'Use o SkinMC para pesquisar qualquer usuário do Minecraft para encontrar, visualizar e baixar sua próxima skin.',
        'about_download' => 'Baixe ou edite',
        'about_download_detail' => 'Encontrou um skin que gostou? Adicione aos seus favoritos, edite ou baixe e torne-a sua.',
        'about_platform' => 'Multiplataforma',
        'about_platform_detail' => 'Quer levar sua skin a qualquer lugar? Leia o QR Code e salve no seu telefone para jogar no Minecraft PE.',
        'meta' => [
            'title' => 'Skins Minecraft',
            'description' => 'Veja e baixe as melhores skins de Minecraft, descubra as melhores coleções, verifique a disponibilidade de usuário, histórico e muito mais!',
        ],
        'recently_viewed' => 'Visto Recentemente',
        'explore_title' => 'Experimente algo novo',
        'explore' => 'Explore novas ideias e ferramentas',
        'servers_browse' => 'Explorar servidores',
        'servers' => 'Descubra os melhores servidores para Minecraft',
        'heads' => 'Cabeças do Minecraft',
        'head_description' => 'Encontre as melhores cabeças do Minecraft, ou cria suas próprias.',
        'achievement' => 'Gerador de conquistas',
        'achievement_detail' => 'Crie e personalize suas próprias conquistas.',
        'continue' => 'Continue navegando'
    ],
    'profile' => [
        'verified' => 'Perfil Verificado',
        'minecraft_profile' => 'Perfil do Minecraft',
        'show_qr_code' => 'Mostrar QR Code',
        'favourite' => 'Favorito',
        'user_title' => ':username Skin do Minecraft',
        'user_views' => 'Visto :views time| Visto :views times',
        'uuid' => 'UUID',
        'copy' => 'Copiar',
        'link' => 'Link',
        'skin_history' => 'Historico de skin do Minecraft (:skins)',
        'username_history' => 'Histórico de usuário',
        'username_history_name' => 'Nome',
        'username_history_timestamp' => 'Alterado em',
        'username_history_initial_name' => 'Nome inicial',
        'user_downloads' => ':downloads download|:downloads downloads',
        'download_skin' => 'Baixar skin',
        'apply_skin' => 'Aplicar skin',
        'capes' => 'Capas',
        'claim_profile' => 'Você é :username? Reivindicar seu perfil para verificar e personalizá-lo!',
        'claimed' => 'Perfil reivindicado',
        'meta_description' => 'Veja e baixe :username Minecraft Skin. Veja seu UUID, histórico de nomes, estatísticas detalhadas e muito mais',
        'created_at' => 'Atualizado: :changed_at',
        'skins' => [
            'meta_title' => ':username Histórico de Skin do Minecraft',
            'meta_description' => ':username Mostra o histórico de skins do Minecraft e skins já usadas. Use o histórico para salvar capas anteriores ou antigas como backups e reversão ou para coletar novas capas.',
            'title' => 'Histórico de Skin do Minecraft'
        ],
        'qr_code' => [
            'meta_title' => 'QR Code de :username',
            'meta_description' => ':username QR Code personalizado do perfil de Minecraft'
        ],
        'sub_nav' => [
            'skin' => 'Skin',
            'about' => 'Sobre',
            'usernames' => 'Nomes de usuários',
            'head' => 'Cabeça',
            'comments' => 'Comentários'
        ],
        'cape' => 'Capa',
        'elytra' => 'Élitro',
        'nametag' => 'Etiqueta',
        'animation' => 'Animação',
        'rotation' => 'Rotação',
        'none' => 'Nenhum',
        'idle' => 'Inativo',
        'walk' => 'Andar',
        'run' => 'Correr',
        'fly' => 'Voar',
        'follow' => 'Seguir',
        'following' => 'Seguindo',
        'unfollow' => 'Deixar de seguir',
        'followers' => 'Seguidor|Seguidores',
        'toast' => [
            'following' => 'Você seguiu :username!',
            'follow-self-error' => 'Desculpe :username, você não pode seguir você mesmo.',
            'unfollowed' => 'Você parou de seguir :username'
        ],
        'edit' => 'Editar perfil',
        'joined' => 'Conectado',
        'role' => 'Role',
        'server-fav-list-empty' => 'Parece que :username não tem servidores favoritos ainda. Quando :username favoritar um servidor, você verá-lo aqui.',
        'server-own-list-empty' => 'Parece que :username não listou um servidor ainda. Quando :username listar um servidor, você verá-lo aqui.',
        'capes-list-empty' => 'Parece que :username não está vestindo nenhuma capa. Quando :username vestir uma capa, você verá-lo aqui.',
        'feed-own-list-empty' => 'Parece que você ainda não postou nada no feed! Quando você postar, você poderá vê-los aqui.',
        'feed-list-empty' => 'Hmm, parece que :username ainda não postou nada no feed. Quando :username postar algo, você poderá vê-lo aqui.',
        'following-own-list-empty' => 'Parece que você ainda não está seguindo ninguém! Quando começar a seguir outras pessoas, você poderá vê-las aqui.',
        'following-list-empty' => 'Hmm, parece que :username não está seguindo ninguém. Quando :username começa a seguir alguém, você pode vê-las aqui.',
        'followers-own-list-empty' => 'Quando as pessoas começarem a seguir o seu perfil, elas aparecerão aqui.',
        'followers-list-empty' => 'Hmm, parece que :username não está sendo seguido por ninguém. Seja o primeiro a seguir :username.',
        'render' => 'Renderizador',
        '3d' => 'Renderização 3D',
        '2d' => 'Renderização 2D',
        'name-history-info' => 'A Mojang removeu o suporte para acessar a API do histórico de nomes no dia 13 de setembro de 2022. Se você deseja ocultar seu histórico de nomes, reivindique seu perfil e vá para configurações para torná-lo privado.',
        'edit-skins' => 'Editar histórico de skin',
        'hide-skin' => 'Ocultar skin',
        'show-skin' => 'Exibir skin',
        'edit-skin' => 'Editar skin',
        'servers' => [
            'title' => 'Servidores de :username',
        ],
        'cape-list' => [
            'title' => 'Mantos de :username',
        ]
    ],
    'skin' => [
        'meta' => [
            'title' => 'Skins de :username',
            'description' => 'Baixe e veja a pele e veja quais jogadores também estão usando a mesma pele.',
            'tags' => ':username Skin de Minecraft, :username Skin, Skin de Minecraft, :username Skin personalizada de Minecraft, Baixar skin, Jogadores com skins compartilhadas',
        ],
        'title' => ':username Skin de Minecraft',
        'head' => 'Comandos de cabeça',
        'head_info' => 'Para usar com blocos de comando',
        'first_wearing' => 'Primeiro jogador a usar esta skin:',
        'profiles' => ':profiles perfil|:profiles perfis',
        'profiles_title' => ':profiles perfil com esta skin|:profiles perfis com esta skin',
        'screenshot' => 'Fazer captura de tela',
    ],
    'skins' => [
        'meta' => [
            'title' => 'Página :current — Todas as Skins',
            'description' => 'Navegue através da nossa :last page lista de skins de Minecraft personalizadas :total e baixe sua próxima skina favorita!',
            'tags' => ':username Skin de Minecraft, :username Skin, Skin de Minecraft, :username Skin personalizada de Minecraft, Baixar skin, Jogadores com skins compartilhadas',
            'tags-title' => ':tag Minecraft Skins',
            'tags-description' => 'Navegue pela nossa :last page lista de :total :tag skins de Minecraft para baixar sua skin :tag favorita!',
            'tags-metatags' => ':tag Minecraft Skin, :tag Skin, Minecraft Skin, :tag Custom Minecraft Skin, Download :tag Skin, Minecraft :tag Skins',
        ],
        'title-skin-tags' => 'Tags Minecraft Skin',
        'subtitle' => 'Página :current de :last de :total Skins de Minecraft',
        'subtitle-skin-tags' => 'Página :current de :last de :total Tags Minecraft Skin',
        'sort_by' => 'Ordenar por',
        'latest' => 'Skin mais recente',
        'most_profiles' => 'Skins mais usadas',
        'profiles_today' => 'Mais usados hoje',
        'profiles_this_week' => 'Mais usados nesta semana',
        'profiles_this_month' => 'Mais usados este mês',
        'default' => 'Ordenar por padrão',
        'this_month' => 'Adicionado este mês',
        'this_week' => 'Adicionado esta semana',
        'today' => 'Adicionado hoje',
        'random' => 'Aleatório',
        'similar' => 'Skins semelhantes',
        'no_similar_skins' => 'Nenhuma skin semelhante foi encontrada ainda.',
        'favorite' => ':count favorito|:count favoritos',
    ],
    'skin-tags' => [
        'faq' => 'O que são tags?',
        'about' => 'Tags são uma forma de adicionar categorias relevantes a skins. Adicionar tags permite que você descubra mais skins de que gosta facilmente!',
        'guidelines' => [
            'good' => [
                'title' => 'As diretrizes gerais para boas tags são:',
                'short' => 'Curto',
                'descriptive' => 'Descritivo',
                'spelled' => 'Ortografia correta',
            ],
            'bad' => [
                'title' => 'Não adicione tags como:',
                'general' => 'Muito geral',
                'specific' =>  'Muito específico',
                'too-many-tags' =>  'Deve ser três tags separadas',
                'spelling' => 'Deve ser :example',
            ],
        ],
        'toast' => [
            'added' => 'Tag ":tag" adicionada para votação',
            'removed' => 'Tag ":tag" foi removida',
            'upvote' => 'Upvoted ":tag"',
            'downvote' => 'Downvoted ”:tag”'
        ],
        'vote' => [
            'up' => 'Upvote',
            'down' => 'Downvote',
            'remove' => 'Remover voto',
        ],
    ],
    'contact' => [
        'contact' => 'Contato',
        'email' => 'Sinta-se a vontade para nos escrever em <a href="mailto:support@skinmc.net">support@skinmc.net</a> para qualquer dúvida que você tenha.',
        'faq' => 'Você pode conferir aqui <a href=":link">página FAQ</a> se sua pergunta já foi respondida lá.',
        'other' => 'Outras maneiras de conectar',
        'other_discord' => 'Entre no servidor do Discord e se conecte com outras pessoas, converse sobre jogos, compartilhe seus pacotes favoritos e tenha ajuda da comunidade.',
        'other_twitter' => 'Siga no Twitter para ver quando uma nova atualização ou recurso for lançada, veja a skin da semana e muito mais.',
        'other_instagram' => 'Siga SkinMC no Instagram para navegar e descobrir novas skins e imagens em destaque do Minecraft.',
        'other_facebook' => 'Torne-se um fã no Facebook e veja todas as postagens onde você pode comentar e conversar com os outros enquanto explora o conteúdo do Minecraft.'
    ],
    'about' => [
        'intro' => '<span>Sua</span> <span>plataforma</span> <span>para</span> <span>Minecraft</span> <span>Skins.</span>',
        'header_credit' => 'Ilustração "Epic Nether Battle" por',
        'info' => 'Acompanhe tudo.',
        'info_explainer' => 'Veja o histórico de nomes dos jogadores, veja suas skins anteriores, adicione-as como um amigo, baixe skins, e até mesmo receba estatísticas detalhadas.',
        'card_find_title' => 'Encontre qualquer jogador de Minecraft',
        'card_find_detail' => 'Comece procurando por qualquer nome de jogador ou UUID de sua escolha.',
        'card_view_title' => 'Ver, salvar e editar',
        'card_view_detail' => 'Encontrou uma skin que você gostou? baixe ou use o editor para torná-la sua.',
        'card_claim_title' => 'Seja verificado',
        'card_claim_detail' => 'Conecte sua conta do Minecraft e reivindique seu perfil para desbloquear novos recursos!',
        'card_customise_title' => 'Personalize seu Perfil',
        'card_customise_detail' => 'Jogadores verificados podem adicionar links de mídia social e criar seu próprio perfil.',
        'card_friends_title' => 'Adicione seus amigos',
        'card_friends_detail' => 'Conecte-se com seus amigos no SkinMC e mostre sua lista de amigos no perfil.',
        'card_history_title' => 'Nome de usuário e histórico de skin',
        'card_history_detail' => 'Use a pesquisa avançada para encontrar e ver o histórico do nome de usuário/skin de um jogador.',
        'founders' => 'Os fundadores',
        'founders_cofounder' => 'Cofundador do SkinMC',
        'head_of_design' => 'Chefe de design',
        'head_of_code' => 'Chefe de códigos',
        'feedback' => 'Envie seu comentário',
        'faq' => 'Perguntas sobre Minecraft, Skins e muito mais? Leia nossas perguntas frequentes com respostas às perguntas mais frequentes.',
        'faq_link' => 'Visite o Centro FAQ',
        'contact' => 'Você quer entrar em contato conosco ou tem mais dúvidas? Contate-nos diretamente.',
        'contact_link' => 'Fale conosco',

    ],
    'faq' => [
        'title' => 'FAQs',
        'subtitle' => 'Perguntas frequentes',
        'help' => 'Precisa de mais ajuda?',
        'discord' => 'Entre no servidor do Discord para conversar com outros jogadores de Minecraft.',
        'contact' => 'Fale conosco',
        'q' => [
            'change_skin_t' => 'Como mudo minha Skin do Minecraft?',
            'change_skin' => '
                <p>Para mudar sua Skin siga esses passos: </p>
                <ol>
                    <li>Visite <a href="https://my.minecraft.net/en-us/login/">https://my.minecraft.net/en-us/login/</a> faça login com sua conta Mojang.</li><li>Depois de fazer login, selecione <b>"Skin"</b> no menu esquerdo.</li><li>Em seguida, escolha e carregue uma skin de sua preferência.</li>
                </ol>',
            'change_username_t' => 'Como mudar meu Nome de Usuário de Minecraft?',
            'change_username' => '
                <p>Para mudar seu nome de usuário faça o seguinte:</p>
                <ol>
                    <li>Visite <a href="https://account.mojang.com/login" target="_blank" rel="nofollow">https://account.mojang.com/login</a> faça login com sua conta Mojang.</li>
                    <li>Encontre o nome do seu perfil do Minecraft e pressione o botão <b>"(Mudar)"</b> button</li>
                    <li>Na próxima página, insira o novo nome de usuário desejado.</li>
                    <li>Por fim, confirme as alterações digitando sua senha e pressionando “Alterar nome”.</li>
                </ol>',
            'dl_t' => 'Como faço para baixar a Skin Minecraft de alguém?',
            'dl' => '
<p>Para baixar a Skin Minecraft de qualquer pessoa, faça o seguinte:</p>
                <ol>
                    <li>Pressione na barra de pesquisa e digite o nome de usuário do player do qual você deseja baixar o skin.</li>
                    <li>Na página de perfil você pode visualizar a skin</li>
                    <li>Clique no botão <strong>Baixar skin</strong> abaixo da visualização</li>
                </ol>',
            'submit_q' => 'Como faço para enviar uma skin para uma coleção?',
            'submit_a' => '<p>Por favor preencha o seguinte formulário com os nomes de usuário e suas categorias que você gostaria de adicionar às coleções. <a href="https://forms.gle/f4Jh5RpGfsHAZ5xE8" target="_blank">Formulário de envio de coleção</a>',
            'mcpe_t' => 'Posso usar a Skin no Minecraft PE?',
            'mcpe' => '
<p>Sim. Para usar a Skin no Minecraft Pocket Edition faça o seguinte:</p>
                <ol>
                    <li>Abra SkinMC.net no seu smartphone e toque na barra de pesquisa</li>
                    <li>Digite o nome de usuário da skin do jogador que você deseja baixar</li>
                    <li>Toque no botão <strong>Baixar skin</strong> abaixo da visualização </li>
                    <li>Abra o Minecraft PE e toque em <strong>Perfil</strong> no lado direito</li>
                    <li>Toque em <strong>+</strong> ou edite o personagem e vá para a "guia de skins clássicas"</li>
                    <li>Toque em "propriedade", depois em "importar" e em "escolher nova skin"</li>
                </ol>',
            'change_times_t' => 'Com que frequência eu posso mudar meu nome de usuário?',
            'change_times' => '<p>Você pode alterar seu nome de usuário do Minecraft <strong>uma vez</strong> a cada <strong>30 dias</strong>.</p>',
            'available_t' => 'Após alterar meu nome de usuário, quando ele ficará disponível para que outras pessoas possam reivindicá-lo?',
            'available' => '<p>Se quiser voltar ao seu nome de usuário anterior, você poderá alterá-lo novamente <strong>após 30 dias.</strong> Todos os outros precisarão esperar mais <strong>7 dias</strong> (37 dias após a alteração). antes que eles possam reivindicar seu nome de usuário antigo. </p>',
            'username_history_t' => 'Como excluir meu histórico de nome de usuário?',
            'username_history' => '
<p>Como os dados do histórico do nome de usuário vêm da Mojang, o histórico do nome de usuário não pode ser removido. A Mojang declarou anteriormente que sua intenção era que os nomes de usuário anteriores pudessem ser vistos¹ e que eles fornecessem um método direto para o público acessar essas informações².</p>
                <p class="font-14">¹<a href="https://help.minecraft.net/hc/en-us/articles/360034636712-Minecraft-Usernames" target="_blank" rel="noreferrer">https://help.minecraft.net/hc/en-us/articles/360034636712-Minecraft-Usernames</a></p>
                <p class="font-14 mb-0">²<a href="https://twitter.com/dinnerbone/status/554739042529849345" target="_blank" rel="noreferrer">https://twitter. com/dinnerbone/status/554739042529849345</a> (Tweet arquivado há 2 anos: <a href="http://archive.is/TeAyj" target="_blank" rel="noreferrer">http://archive.is/TeAyj</a>)
                </p>',
        ],
    ],
    'avatars' => [
        'start' => [
            'title' => 'Crie seu próprio avatar de Minecraft',
            'subtitle' => 'Use o gerador de avatar do Minecraft para criar um avatar divertido de qualquer skin!',
            'avatar_face' => 'Avatar - Estilo facial',
            'avatar_bust' => 'Avatar - Estilo Busto',
            'avatar_cube' => 'Avatar - Estilo Cubo',
            'avatar_head3d' => 'Cabeça 3D personalizada',
        ],
        'user' => [
            'title' => 'Escolher skin',
            'subtitle' => 'Digite o nome de usuário do Minecraft para o avatar que deseja gerar',
            'form_label' => 'Usuário do Minecraft',
            'form_submit' => 'Continuar',
        ],
        'output' => [
            'title' => 'Visualizar e salvar',
            'subtitle' => 'Aproveite usando seu novo avatar de Minecraft',
            'download_info' => 'Feliz com o resultado? Comece a usar sua nova skin fazendo o download aqui',
            'download_button' => 'Download Skin',
            'avatar_style' => 'Estilo de Skin',
            'skin_username' => 'Usuário da skin',
            'change' => 'Alterar',
            'generate' => 'Gerar',
            'avatar_colour' => 'Cor do plano de fundo',
            'avatar_colour_palette' => 'Paleta',
            'avatar_colour_basic' => 'Básico',
        ],
        'meta' => [
            'title' => 'Gerador Minecraft Avatar',
            'description' => 'Criador de Avatar do Minecraft: crie fotos de perfil personalizadas usando sua skin de Minecraft',
        ],
    ],
    'totem' => [
        'title' => 'Totem de Minecraft Personalizado',
        'subtitle' => 'Use o gerador de Totem do Minecraft para criar uma textura personalizada com um Totem de Imortalidade de qualquer skin.',
        'download_info' => 'Feliz com a prévia? Escolha sua versão do Minecraft para salvar seu pacote de recursos personalizado:',
        'meta' => [
            'title' => 'Gerador de Totem Personalizado do Minecraft',
            'description' => 'Totens personalizados: gere e crie um pacote personalizado para o Minecraft com um Totem da imortalidade usando sua ou qualquer outro skin para o Minecraft.',
        ],
        'type' => [
            'mini' => 'Uma mini versão da sua skin!',
            'full' => 'Uma versão completa da sua skin!',
            'model3d' => 'Um modelo 3D de sua skin!',
            'add_designs' => 'Quer ver mais designs? Envie sua sugestão de design aqui:'
        ]
    ],
    'achievement' => [
        'header' => [
            'title' => 'Crie sua própria Conquista do Minecraft',
            'subtitle' => 'Use o Gerador de Conquistas do Minecraft para criar sua própria conquista personalizada e usar para mostrar seus avanços em todo lugar que você quiser!',
        ],
        'generator' => [
            'yellow_text' => 'Texto amarelo',
            'white_text' => 'Texto branco',
            'choose_icon' => 'Escolha o ícone',
            'face' => 'Face de Minecraft em vez do ícone',
            'form_submit' => 'Download',
            'form_label' => 'Usuário do Minecraft',
            'download' => 'Download',
            'embed' => 'Embed',
            'embed_copy' => 'Copiar',
        ],
        'meta' => [
            'title' => 'Gerador de Conquistas do Minecraft',
            'description' => 'Gerar Conquistas personalizadas do Minecraft e avanços com o criador de conquistas. Baixar a imagem diretamente, use em assinaturas do fórum, incorpore HTML ou BB code, e muito mais',
        ],
    ],
    'armor' => [
        'header' => [
            'title' => 'Criador de Suporte de Armadura do Minecraft',
            'subtitle' => 'Gere e crie seus próprios Suportes de Armadura do Minecraft personalizados. Crie diferentes poses, posições, coloque itens e muito mais.',
        ],
        'meta' => [
            'title' => 'Criador de Suporte de Armadura do Minecraft',
            'description' => 'Gere e crie facilmente Suportes de Armadura do Minecraft personalizados. O editor te ajuda a criar diferentes poses, posições, colocar itens, skins personalizadas e muito mais.',
        ],
    ],
    'banner' => [
        'editor' => [
            'header' => [
                'title' => 'Editor de Estandarte do Minecraft',
                'subtitle' => 'Crie seus próprios Estandartes do Minecraft personalizados. Eles podem ser usados para decorar seu mundo ou também comumente vistos como capas do <a href="https://optifine.net" target="_blank" rel="nofollow">Optifine</a>.',
            ],
            'meta' => [
                'title' => 'Criador de Estandarte do Minecraft',
                'description' => 'Crie seus próprios Estandartes do Minecraft personalizados com todos os padrões e cores do jogo! Estes podem ser usados para decorar seu mundo ou ser usados como Capas do Optifine usando a Capa de Estandarte. Você pode gerar comandos de /give para estandartes ou escudos.',
            ],
        ],
        'gallery' => [
            'header' => [
                'title' => 'Galeria de Estandartes do Minecraft',
                'subtitle' => 'Navegue na galeria de :count Estandartes do Minecraft personalizados. Você pode usar o Estandarte como capa para tornar sua skin de Minecraft mais única, ou use um Estandarte como uma bandeira para decorar seu mundo.',
            ],
            'meta' => [
                'title' => 'Galeria de Estandartes do Minecraft',
                'description' => 'Navegue na galeria de :count Estandartes do Minecraft personalizados. Você pode usar o Estandarte como capa para tornar sua skin de Minecraft mais única, ou use um Estandarte como uma bandeira para decorar seu mundo.',
            ],
        ],
    ],
    'search' => [
        'meta' => [
            'title' => 'Resultados da pesquisa: :search',
        ],
        'title' => 'Resultados da pesquisa',
        'results' => 'Página :current para :count resultado|Página :current de :count resultados ',
        'time' => '(:time segundos)',
        'username_available' => 'Nome de usuário disponível*',
        'username_unavailable' => 'Nome de usuário não disponível',
        'username_status' => 'Estado',
        'username_status_available' => 'Disponível*',
        'username_status_unavailable' => 'Indisponível',
        'username_searches' => 'Pesquisas',
        'username_searches_count' => ':count / dia',
        'username_available_disclaimer' => '*A menos que o nome esteja temporariamente ou permanentemente banido pela Mojang.',
        'no_results' => 'Nenhum perfil encontrado. Tente pesquisar com UUID alterando o tipo de pesquisa.',
        'no_results_tags' => 'Nenhuma skin marcada foi encontrada. Tente pesquisar por outras tags como "blue", "girl", "fox", etc...',
        'again' => 'Buscar novamente',
        'sorry' => 'Desssssssculpe...',
        'view_profile' => 'Ver perfil',
    ],
    'collection' => [
        'title' => 'Coleção de skins do Minecraft',
        'subtitle' => 'Navegue através da nossa coleção de skins do Minecraft.',
        'filters' => 'Filtros',
        'title_trending' => 'Em destaque',
        'title_all' => 'Todas as skins de Minecraft',
        'skin_tags' => 'Skins Marcadas',
        'filters_skin_type' => 'Tipo de skin',
        'filter_skin_type_steve' => 'Tipo do Steve',
        'filter_skin_type_alex' => 'Tipo Alex',
        'cancel' => 'Cancelar',
        'apply' => 'Aplicar',
        'username_minecraft_skin' => 'Skin de :username',
        'user_downloads' => '<span class="fw-500">:downloads</span> download|<span class="fw-500">:downloads</span> downloads',
    ],
    'favourites' => [
        'title' => 'Favoritos',
        'subtitle' => 'Veja e gerencie skins e servidores que você salvou para mais tarde em sua lista de favoritos',
        'sort' => 'Ordenar por',
        'toast' => [
            'added' => 'Adicionado à sua lista de favoritos',
            'removed' => 'Removido da sua lista de favoritos'
        ],
        'skins' => [
            'button' => 'Skins',
            'empty_headline' => 'Sem skins favoritas ainda',
            'empty_subtitle' => 'Você ainda não tem skins salvas na sua lista de favoritos. Visite a página do servidor e descubra sua próxima favorita!',
            'empty_browse' => 'Procurar skins',
            'meta' => [
                'title' => 'Minhas skins favoritas',
                'description' => 'Minhas skins favoritas de Minecraft salvas',
            ],
        ],
        'servers' => [
            'button' => 'Servidores',
            'empty_headline' => 'Nenhum servidor favorito ainda',
            'empty_subtitle' => 'Você ainda não tem nenhum servidor salvo na sua lista de favoritos. Visite a página do servidor e descubra o seu próximo favorito!',
            'empty_browse' => 'Explorar servidores',
            'meta' => [
                'title' => 'My favourite servers',
                'description' => 'My favourite Minecraft servers',
             ],
        ],

    ],
    'cape' => [
        'editor' => [
            'title' => 'Minecraft cape editor',
            'subtitle' => 'Use the Minecraft cape editor to create your very own custom designed cape.',
            'meta' => [
                'title' => 'Minecraft Cape Editor',
                'description' => 'Use the Minecraft Cape Editor to create your very own custom designed cape.',
            ],
        ],
        'list' => [
            'title' => 'Minecraft capes',
            'subtitle' => 'Official capes of Minecraft. Capes are commemorative items and are worn as addition to the player skin. They can also change the appearance when an elytra is worn.',
            'meta' => [
                'title' => 'Minecraft Capes List',
                'description' => 'Minecraft cape list: View all official Minecraft capes including Mojang, Minecon, Personal, Special and vanity capes',
            ],
        ],
        'detail' => [
            'title' => ':cape Cape',
            'info' => 'Cape information',
            'profile_list' => 'Profiles with this cape',
            'profiles' => ':profiles profile|:profiles profiles',
            'meta' => [
                'title' => ':cape Minecraft Cape',
                'description' => 'Check out the :cape Minecraft Cape and see players wearing it!',
            ],
        ],
        'list-custom' => [
            'title' => 'Custom Minecraft Capes',
            'description' => 'Browse and view custom capes which have been created and are used by SkinMC members.'
        ]
    ],
    'servers' => [
        'title' => 'Minecraft servers',
        'subtitle' => 'Navegue e explore os Servidores de Minecraft',
        'all' => 'All servers',
        'manage_your_servers' => 'Manage your servers',
        'add_new_server' => 'Add new server',
        'filters' => [
            'trending' => 'Trending',
            'updated' => 'Updated',
            'new' => 'New',
            'most_viewed' => 'Most viewed',
            'top_voted' => 'Top voted',
            'sorting' => 'Sorting',
            'sort_by_latest' => 'Sort by latest',
            'sort_by_oldest' => 'Sort by oldest',
            'categories' => 'Categories',
            'server_location' => 'Server location',
            'show_results' => 'Show results',
            'show_more' => 'Show more',
            'show_less' => 'Show less',
            'clear_filters' => 'Clear filters',
            'reviews' => 'Reviews',
            'sort_by_highest_rating' => 'Sort by highest rating',
            'sort_by_lowest_rating' => 'Sort by lowest rating',
            'bedrock_and_java_support' => 'Bedrock and Java support'
        ],
        'review-count' => ':count Review|:count Reviews',
        'meta' => [
            'title' => 'Minecraft Server List',
            'description' => 'Navegue e explore a lista de Servidores de Minecraft para encontrar o melhor Servidor! Filtre pelos mais recentes, mais populares e muito mais',
        ],
        'reviews' => [
            'meta' => [
                'title' => 'Write a review',
            ],
            'editing' => 'You\'re editing your review from :date. Would you like to delete your review instead?',
            'welcome' => 'Hi :username. How was your overall experience with :servername?',
            'subtitle' => 'Leave an overall score of your past experience with the server.',
            'scale' => [
                'great' => 'Great',
                'good' => 'Good',
                'okay' => 'Okay',
                'meh' => 'Meh',
                'bad' => 'Bad',
            ],
            'rate-experience' => 'Next, rate your experience in these areas',
            'overall' => 'Overall',
            'server-team' => 'Server team',
            'community' => 'Community',
            'experience' => 'Experience',
            'availablility' => 'Uptime and availability',
            'shop' => 'Shop',
            'write-review-title' => 'Write a review',
            'write-review-subtitle' => 'Leave a few notes, you can highlight what you enjoyed, what made your experience special, or offer a few suggestions.',
            'write-review-helper' => 'Write a server review to share your experience with new players, and help the server owners with feedback.',
            'write-review-tips' => 'Here are some tips',
            'submit-title' => 'Ready to submit your review?',
            'submit-subtitle' => 'Almost done!',
            'submit-review' => 'Submit my review',
            'back' => 'Back',
            'continue' => 'Continue',
            'delete-title' => 'Are you sure you would like to delete your review?',
            'tos-checkbox-part-1' => 'By submitting this form you accept SkinMC\'s Terms of Service, Privacy Policy, and Community Guidelines. You also confirm that all of the information is accurate, and follows the',
            'tos-checkbox-part-2' => 'review guidelines.',
            'tos-checkbox-part-3' => 'Your review will be published after submission, but can be subject to review.'
        ],
        'slots' => 'Slots',
        'empty-helper' => 'You can try to do another search or',
        'empty' => 'Hmm it\'s still empty here.',
        'verified' => 'Verified',
        'review_translate_show_original' => 'Show original',
        'review_translate' => 'Translate review',
        'description_translate' => 'Translate description',
        'create' => [
            'welcome' => 'Welcome',
            'basics' => 'Basics',
            'categories' => 'Categories',
            'social_links' => 'Social links',
            'trailer_video' => 'Trailer video',
            'images' => 'Images',
            'images_description' => 'You can upload photos afterwards, to showcase what your server offers.',
            'submit' => 'Submit',
            'lets_get_your_server_added' => 'Let\'s get your server added.',
            'basics-subtitle' => 'Let people know what your server is about.',
            'description' => 'Description',
            'description_tips' => 'Here are some tips',
            'description_hint' => 'Write a good description for your server to attract new players.',
            'categories-subtitle' => 'Choose some categories for your server',
            'missing-category' => 'Missing a category?',
            'social_links_description' => 'Where can players connect with your server on social media?',
            'trailer_video_description' => 'Showcase your server with a YouTube video.',
            'trailer_video_hint' => 'Paste the video URL or ID:',
            'ready_to_submit_your_server' => 'Ready to submit your server?',
            'review-hint' => 'After submission the team will carefully review your server listing application. Then upon decision, your server will be published, or changes requested before going live.',
            'terms' => [
                'part-1' => 'By submitting this form you are authorised to accept SkinMC\'s Terms of Service, Privacy Policy, and Community Guidelines. You also confirm that all of the information above is accurate, you have properly followed the',
                'part-2' => 'server requirements for setup',
                'part-3' => ', and that the Minecraft server is owned and managed by the entity you are representing.'
            ],
            'submit-application' => 'Submit application',
            'video-id-helper' => [
                'part-1' => 'The video ID is the string of numbers and letters after',
                'part-2' => 'For example if your video url is',
                'part-3' => ', then your video ID would be'
            ],
            'welcome_description' => 'In this step, we\'ll get started on adding your server. Tell us a bit about it, write a description, and in the next step you can upload some images.'
        ],
        'copy_server_ip' => 'Copy server IP',
        'all_minecraft_servers' => 'All Minecraft Servers',
        'promo' => [
            'title' => 'Do you host a Minecraft Server?',
            'ready_to_list_your_server' => 'Ready to list your Server?',
            'everything_you_need' => 'Everything you need to grow your server',
            'list_your_server' => 'List your server',
            'list_your_server_description' => 'Create a listing for your server, add photos, social media and more.',
            'find_players' => 'Find players',
            'find_players_description' => 'Find and reach new players to join your server and grow your community.',
            'get_reviews' => 'Get reviews',
            'get_reviews_description' => 'Ask your community to review your server, and reward them in game.',
            'why_list_on_skinmc' => 'Why you should list your Server on SkinMC',
            'others' => 'Others',
            'quality_check_and_confirmation' => 'Quality check and confirmation',
            'quality_check_description' => 'Our team reviews every server to ensure quality.',
            'verified_players' => 'Reviews from verified Minecraft players',
            'verified_players_description' => 'Collect authentic player reviews from legitimate accounts with Votifier integration.',
            'international' => 'International',
            'international_description' => 'With translation features your listing is available to more players.',
            'server_listing_page' => 'Powerful Server listing page',
            'server_listing_page_description' => 'Add photos, description texts, youtube videos, and highlight why players should join your server.',
            'social_connections' => 'Social media connections',
            'social_connections_description' => 'Connect your Servers social accounts and show new players where they can find you.',
            'verified_badge' => 'Verification badge',
            'verified_badge_description' => 'Authentic servers can apply for a verification badge.',
            'owner_profile' => 'Owner profile',
            'owner_profile_description' => 'Add a personal touch, by completing your custom profile.',
            'categories' => 'Categories',
            'categories_description' => 'Different categories to make it easier to find your server.',
            'vote' => 'Vote',
            'vote_description' => 'Ask users to vote for your server.',
            'fair_listings' => 'Fair listings',
            'fair_listings_description' => 'Server listings can not be artificially boosted in results on SkinMC.',
            'support' => '24h support',
            'support_description' => 'Do you need help or have questions? You can always reach out and receive a fast reply.',
            'custom_features' => 'Custom features',
            'custom_features_description' => 'Missing a feature for your server? Open a ticket, and we\'ll implement it.',
            'faq' => [
                'title' => 'Answers to your questions',
                'suited-question' => 'Is my Minecraft Server suited for SkinMC?',
                'suited-answer' => 'Minecraft Players on SkinMC love to discover new experiences, content and engage with communities. On the platform you\'ll find a large variety of different, unique, fun Minecraft servers. From a large network to even a small survival server, it can make someones day!',
                'get-started-question' => 'How do I get started?',
                'get-started-answer' => 'Adding your Minecraft Server to the SkinMC Server List is very easy! You will first need to create an account, if you haven\'t already, and then follow the setup guide to get your server listed. Add a few photos and a nice description, and your server will be published in no time!',
                'players-question' => 'How can I get more players on my Minecraft Server?',
                'players-answer' => 'Building a community is the most crucial part of a long lasting Minecraft Server. Use the Minecraft Server List on SkinMC to find a new audience and continue to build your community. Ask your players to recommend your Server, or share your listing on social media platforms. Collecting good reviews can also play an important role to a great Server listing presence that attracts new players.',
                'more-question' => 'I have more questions. Where can I get help?',
                'more-answer' => 'You can reach out to SkinMC at any time, 24 hours, by using either the help button, the help desk, or by joining the Discord server.'
            ],
            'ready_to_list_description' => 'Add your Minecraft Server to the SkinMC Server List in just a few minutes. If you need any help, you can reach out around the clock and receive answers quickly.'
        ],
        'manage' => [
            'index' => [
                'welcome' => 'Welcome back, :username',
                'your_servers' => 'Your servers',
                'reviews_today' => 'Reviews today',
                'no_reviews_today' => 'No reviews today',
                'no_reviews_text' => 'Your servers haven\'t received any reviews today. Why not ask your players to leave one?',
                'tips' => [
                    'title' => 'Tips',
                    'description-title' => 'Write a good server description',
                    'description-body' => 'Helpful tips and advice to write a great server description.',
                    'images-title' => 'Adding server images',
                    'images-body' => 'Make your server listing stand out with great images.'
                ]
            ],
            'listings' => [
                'title' => 'Your Minecraft servers (:count)'
            ],
            'insights' => [
                'title' => 'Insights'
            ],
            'edit_server' => 'Edit server',
            'listing' => 'Listing',
            'to_do' => 'To do',
            'last_update' => 'Last update',
            'add_more_photos_to_publish' => 'Add more photos to publish',
            'looks_empty_here' => 'Looks empty here.',
            'get_started_by_adding_a_new_server' => 'Get started by adding a new server?'
        ],
        'status' => [
            'approved' => 'Approved',
            'pending_approval' => 'Pending approval',
            'published' => 'Published',
            'in_review' => 'In review'
        ]
    ],
    'editor' => [
        'import' => [
            'title' => 'Import Skin',
            'import_by_username' => 'Import by username',
            'import_button' => 'Import',
            'drag' => 'Drag and drop a skin here, or click',
            'click' => 'Select image'
        ],
        'download' => [
            'error' => [
                'no-data' => 'No skin data was provided. Please try again.',
                'invalid-format' => 'The skin data format is invalid. Please try again.',
                'invalid-data' => 'The skin data is corrupted. Please try again.',
                'generic' => 'Something went wrong while downloading your skin. Please try again.',
            ],
        ],
        'draw' => 'Draw',
        'eyedropper' => 'Eyedropper',
        'fill' => 'Fill',
        'move' => 'Move',
        'decrease_brightness' => 'Decrease brightness',
        'increase_brightness' => 'Increase brightness',
        'erase' => 'Erase',
        'undo' => 'Step back (CTRL+Z)',
        'redo' => 'Step forward (CTRL+Y)',
        'default_view' => 'Default view',
        'zoom_in' => 'Zoom in (CTRL +)',
        'zoom_out' => 'Zoom out (CTRL -)',
        'saved' => 'Last saved just now',
        'saving' => 'Auto saving...',
        'save_error' => 'An error occurred',
        'new_skin' => 'New skin',
        'previous_skins' => 'Previous skins',
        'backed_up_title' => 'Automatically saved skins',
        'backed_up_info' => 'Temporarily backed up to your local storage.',
        'backed_up_empty_title' => 'It\'s empty here',
        'backed_up_empty_info' => 'Once you start editing skins you\'ll see your 32 last edited skins here.',
        'backed_up_skins_count' => 'of 32 skin backups used',
        'backed_up_skins_count_info' => 'You can back up to up 32 skins. Once you reach 32 skins an older skin will be replaced with a new one.',
        'layers' => 'Layers',
        'body' => [
            'title' => 'Body',
            'overlay' => 'Overlay',
            'head' => 'Head',
            'torso' => 'Torso',
            'l_arm' => 'Left arm',
            'r_arm' => 'Right arm',
            'l_leg' => 'Left leg',
            'r_leg' => 'Right leg',
        ],
        'model' => 'Model',
        'steve' => 'Steve',
        'alex' => 'Alex',
        'stance' => [
            'title' => 'Position',
            'default' => 'Default',
            'walk' => 'Walk',
            'run' => 'Run',
            'hug' => 'T-pose',
            'fly' => 'Fly',
        ],
        'fullscreen' => 'Fullscreen',
        'fullscreen_exit' => 'Exit fullscreen',
        'grid' => 'Grid',
        'show_grid' => 'Show grid',
        'download' => [
            'title' => 'Save & Download',
            'subtitle' => 'SkinMC Account',
            'description' => 'Would you like to create a free SkinMC account to save your skin and future ones to the cloud?',
            'start_description' => 'Start download directly without saving to the cloud',
            'start' => 'Download skin',
        ],
        'help' => [
            'title' => 'Minecraft Skin Editor',
            'about' => 'Create and edit your custom Minecraft Skin easily with the SkinMC Editor. You can choose between Steve and Alex models, import skins from a file or username, and create your very own Minecraft Skin.',
            'draw' => 'Draw using the pen tool. Select a colour from the swatch to use with it.',
            'eyedropper' => 'Use the eyedropper to select a colour from your skin and add it to your current palette.',
            'fill' => 'Fill entire areas of your skin using the fill tool. Select a colour before using fill.',
            'move' => 'Pan and move around the skin editor canvas with the move tool.',
            'decrease_brightness' => 'Decrease the brightness of the currently active colour.',
            'increase_brightness' => 'Increase the brightness of the currently active colour.',
            'erase' => 'Erase pixels drawn on the secondary overlay layer.',
            'minimap' => 'Minimap',
            'minimap_info' => 'The minimap can show you the skin texture in a flat view while in 3D mode. In 2D mode the minimap switches to a 3D preview of your skin. You can zoom in and out.',
            'autosave' => 'Autosave',
            'autosave_info' => 'The autosave feature saves your skin automatically every 30 seconds. You can access the autosaved skins in the editor by pressing the folder icon, and choosing "Previous skins".',
            '2d_editor' => '2D and 3D editor',
            '2d_editor_info' => 'Toggle between editing your Minecraft skin in 2D or 3D mode.',
        ],
    ],
    'account' => [
        'level' => 'Level',
        'level_history' => 'Level history',
        'xp' => 'XP',
        'my_xp' => 'My XP',
        'xp_to_next_level' => ':xp XP to next level',
        'xp_info' => 'What are XP?',
        'xp_info_tooltip' => 'XP is earned for various activities such as adding tags to skins, inviting friends, commenting, and much more. With each XP earned you can level up and unlock cool things!',
        'settings' => [
            'title' => 'Account',
            'show_profile' => 'Go to profile',
            'friends' => 'Friends',
            'friends_detail' => 'Stay connected by using your friends list on SkinMC.',
            'security' => 'Security',
            'security_detail' => 'Update your login password and keep your account safe',
            'social' => 'Social media accounts',
            'social_detail' => 'Customise your profile by adding your social media',
            'link' => 'Link Minecraft account',
            'link_detail' => 'Link your Minecraft account and claim your profile.',
            'logout' => 'Do you want to log out from your SkinMC account?',
            'automatic_backups' => 'Automatic skin backups',
            'automatic_backups_info' => 'As a SkinMC plus member your skins are backed up daily.',
        ],
        'capes' => [
            'title' => 'SkinMC Minecraft Cape',
            'description' => 'Wear any cape you wish in-game with SkinMC Capes for free.',
            'drop' => 'Drag and drop a cape here',
            'drop-hint' => 'Dimensions 64x32px',
            'select' => 'Select image',
            'upload-cape' => 'Upload & use cape',
            'save-and-use' => 'Save & use',
            'uploaded-cape' => 'Uploaded cape',
            'no-cape' => 'No cape',
            'remove-cape' => 'Remove cape',
            'download' => 'Download the SkinMC Mod to see your and other players capes in-game.',
            'learn-more' => 'Learn more',
            'link-account' => 'Please link your Minecraft account to upload a cape.',
            'updated' => 'Your cape has been updated!',
            'removed' => 'Your cape has been removed.',
            'active' => 'Your cape is activated!'
        ],
        'favourite' => 'Favourite',
        'remove_favourite' => 'Remove favourite',
        'added_to_favourites' => 'Added to favourites',
        'removed_from_favourites' => 'Removed from favourites',
        'welcome' => 'Nice to see you!',
        'view-profile' => 'View my profile',
        'security' => [
            'title' => 'Security',
            'email' => 'Email address',
            'email-title' => 'Update your email address.',
            'save' => 'Save',
            'password' => 'Password',
            'password-title' => 'Change your password at any time.',
            'social-provider' => 'To update your account information, such as your password, please visit your login provider:',
            'social-provider-email' => 'Your associated email address with your login provider',
            'social-provider-connected' => 'Currently connected login providers',
            'current-password' => 'Current password',
            'forgot' => 'Forgot password?',
            'edit' => 'Edit',
            'delete' => 'Delete my account',
            'account-deletion' => 'Delete your SkinMC account.',
            'delete-info' => 'Please confirm to continue',
            'delete-confirmation' => 'Deleting your account is irreversible. All your personal information and content such as posts, favourites, uploaded capes, customisations, etc. will be deleted and can not be recovered.',
            'delete-confirmation-info' => 'Enter your password to continue',
            'yes-confirm-delete' => 'Yes, confirm delete',
            'account-successfully-deleted' => 'Your account and data has been successfully deleted.'
        ],
        'social' => [
            'title' => 'Social accounts',
            'edit' => 'Edit',
            'save' => 'Save',
            'link-account' => 'Link your Minecraft account to SkinMC to display your social links on your profile.',
            'finish-setup' => 'Finish setup',
            'connect-account' => 'Connect your accounts',
            'connect-description' => 'Choose which accounts you wish to connect and unlock special SkinMC integrations.',
            'empty' => 'No accounts added',
            'empty-description' => 'Your social media accounts will show up here and on your public profile. Once added they will add more personalisation to your page as well as enable integrations.',
            'connect' => 'Connect',
            'username' => 'username',
            'spotify' => 'Add your Spotify username to show your Spotify information on your profile.',
            'discord' => 'Enter your Discord username and number to display your Discord information on your SkinMC profile.',
            'youtube' => 'Add your YouTube channel to SkinMC which will display your YouTube channel on your profile.',
            'youtube-format' => 'Use the following format depending on your channel link:',
            'twitter' => 'Enter your X (formerly Twitter) username to display it on your profile.',
            'bluesky' => 'Enter your Bluesky handle e.g. username.bsky.social to display your Bluesky profile on your profile.',
            'twitch' => 'Enter your Twitch username to display your Twitch channel on your profile.',
            'reddit' => 'Enter your Reddit username to display your Reddit profile on your profile.',
            'github' => 'Enter your GitHub username to display your GitHub profile on your profile.',
            'telegram' => 'Enter your Telegram username to display your Telegram link on your profile.',
            'tiktok' => 'Enter your TikTok username to display your TikTok profile on your profile.',
            'snapchat' => 'Enter your Snapchat username to display your Snapchat profile on your profile.',
            'instagram' => 'Enter your Instagram username to display your Instagram profile on your profile.',
            'facebook' => 'Enter your Facebook username to display your Facebook profile on your profile.',
            'includes_skinmc_plus_benefits' => 'Includes SkinMC plus benefits',
        ],
        'recover' => [
            'title' => 'Recover your account',
            'subtitle' => 'Please enter your new password and confirm it to finish recovering your account.',
            'new_password' => 'New password',
            'repeat_new_password' => 'Repeat new password',
            'submit' => 'Recover account',
        ],
        'customise' => [
            'title' => 'Customise your profile',
            'description' => 'Add your social media, choose an emoji, set your location and more',
            'information' => 'Information',
            'preview' => 'Preview',
            'location' => [
                'title' => 'Location',
                'description' => 'Choose which location you would like to add to your profile.',
            ],
            'biography' => [
                'title' => 'About me',
                'description' => 'Write a bio for your profile.',
            ],
            'status' => 'Status',
            'status-toggle' => 'Show my online status',
            'emoji' => 'Emoji',
            'name-history-toggle' => 'Make username history private',
            'name-history-info' => 'Your Minecraft username history is currently',
            'name-history-toggle-on' => 'private',
            'name-history-toggle-off' => 'public',
            'theme' => 'Profile theme',
            'theme-primary' => 'Primary',
            'theme-secondary' => 'Secondary',
            'appearance' => 'Appearance',
        ],
        'link' => [
            'manage' => 'Manage linked Minecraft account',
            'description' => 'See and manage your linked Minecraft account',
            'title' => 'Linked Minecraft account',
            'current' => 'Currently linked Minecraft account.',
            'status' => 'You now have full access to all SkinMC features!',
            'linked' => 'Linked',
            'disconnect' => 'Disconnect',
            'disconnect-title' => 'Disconnect Minecraft account',
            'disconnect-info' => 'Are you sure you would like to disconnect your Minecraft account?',
            'disconnect-features' => 'You will lose access to commenting, customisation and other features which require a linked Minecraft account. To use these again you will be required to link a Minecraft account.',
            'disconnect-following' => 'Disconnecting your Minecraft account will permanently remove all your followed profiles.',
            'disconnect-posts' => 'Your created feed posts and liked will be deleted.',
            'can-not-undo' => 'This can\'t be undone.',
            'are-you-sure' => 'Are you sure?',
            'confirm' => 'Yes, confirm disconnect',
            'cancel' => 'No, cancel',
            'success' => 'Your account was successfully disconnected!'
        ],
        'finish-setup' => [
            'title' => 'Finish account setup',
            'description' => 'Finish setting up your account, and get full access to all features by linking your Minecraft account to SkinMC.',
            'link' => 'Link Minecraft account',
            'get-started' => 'Get started',
            'skip' => 'Skip',
            'claim' => 'Claim your profile',
            'customise' => 'Customise your page',
            'social' => 'Add social links',
            'comment' => 'Access to comment system',
            'direct_message' => 'Send direct messages',
            'feed' => 'Post status updates to the feed',
            'follow' => 'Follow your friends',
            'badge' => 'Badge displayed on your profile',
            'cape' => 'Custom Minecraft cape',
            'backup' => 'Automatic skin backup',
            'more' => 'And more...'
        ],
        'skins' => [
            'title' => 'Manage skins',
            'toggle' => 'Skin visibility toggled',
        ],
        'invite' => [
            'title' => 'My invites',
            'headline' => 'Invite your friends',
            'info' => 'Create an invite code to share with your friend. Once they accept it, you\'ll both earn some extra XP!',
            'description' => 'Create an invite for your friends and you\'ll both earn some extra XP.',
            'generate' => 'Create invite code',
            'empty' => 'You haven\'t created any invites yet.',
            'code' => 'Code',
            'expiry' => 'Each code works once.',
            'status' => [
                'title' => 'Status',
                'pending' => 'Pending',
                'accepted' => 'Accepted'
            ],
            'add_invite' => [
                'button' => 'Have an invite?',
                'title' => 'Add an invite code',
                'redeem' => 'Redeem invite',
            ],
            'share' => 'Send your friend an invite link'
        ],
        'emoji' => [
            'title' => 'SkinMC Emoji',
            'introducing' => 'Introducing',
            'info' => 'Customise your profile with emoji. Unlock more as you level up.',
            'unlocked_at' => 'Unlocked at level :level',
            'unlocks_at' => 'Reach level :level to unlock',
            'turn_off' => 'Show emoji'
        ]
    ],
    'notifications' => [
        'title' => 'Notifications',
        'view_all' => 'View all',
        'view_all_notifications' => 'View all notifications',
        'image' => 'Notification photo',
        'archived' => 'Archived',
        'inbox' => 'Inbox',
        'empty' => [
            'title' => 'You\'re up to date!',
            'text' => 'New notifications will show up here.',
            'text-archived' => 'Archived notifications will show up here.',
        ],
        'action' => [
            'archive' => 'Move to archive',
            'unarchive' => 'Unarchive',
            'open' => 'Tap to open',
        ],
        'toast' => [
            'archive' => 'Notification moved to archive',
            'unarchive' => 'Notification moved to inbox',
            'undo' => 'Undo',
        ]
    ],
    'error' => [
        'offline' => [
            'title' => 'No internet',
            'subtitle' => 'Your internet was disconnected. Please check your connection and reload the page to try again.',
            'try_again' => 'Try again'
        ],
        '404' => [
            'title' => '404 — Page not found.',
            'subtitle' => 'Hm, it looks like nothing was found at this location. Maybe try going back, or start a new search?',
            'try_again' => 'Back home'
        ],
    ],
    'heads' => [
        'list' => [
            'meta' => [
                'title' => 'Minecraft heads database',
                'description' => 'Explore the database of Minecraft heads to decorate your world with, or generate your own give command. View official heads, player heads and custom heads that feature textures which never change.'
            ],
            'header' => [
                'title' => 'Minecraft heads',
                'subtitle' => 'Explore our database of Minecraft heads to decorate your world, or generate your own give command. Player heads show the current skin worn by a user, and can change as the user updates their skin. Custom heads are linked to the Mojang skin file and never change. Custom heads must be summoned using a command block as the command is very long.',
            ],
            'count' => [
                'heads' => ':heads head|:heads heads',
            ],
            'customheads' => [
                'title' => 'Custom heads',
                'description' => 'Custom heads use the direct path to the texture file on the Mojang servers. Hence textures will never be deleted and the heads never change.',
                'version' => 'Minecraft 1.8 or later',
            ],
            'playerheads' => [
                'title' => 'Player heads',
                'description' => 'Player heads use the current skin texture of a Minecraft player. As they are username based, when the player changes their name or skin, the head changes.',
                'version' => 'All Minecraft versions',
            ]
        ],
    ],
    'mod' => [
        'title' => 'SkinMC Mod: Free custom capes',
        'headline' => 'Apresentando o mod SkinMC para uma maior personalização',
        'description' => 'Giving back to the Minecraft community, with a free mod which enables players more customisation with custom capes, available and visible for anyone using the mod.',
        'download' => 'Download now',
        'download-title' => 'Download the mod',
        'requires' => 'Requires',
        'select-version' => 'Choose your Minecraft version',
        'get-started' => 'Getting started is simple',
        'step-1' => '1. Get the mod',
        'step-1-detail' => 'Install Fabric, then download the mod for your game version and install it by putting the jar in your mods folder.',
        'step-2' => '2. Link your account',
        'step-2-detail' => 'If you haven\'t already, sign up/in and connect your Minecraft account to SkinMC.',
        'step-3' => '3. Upload your cape',
        'step-3-detail' => 'Go to your account and upload your custom cape. It will be visible in-game.',
        'all-versions' => 'All versions',
        'latest' => 'Latest',
        'logged-in' => 'Upload your cape',
        'mirror' => 'Mirror',
        'download-via' => 'Download via:',
        'curseforge' => 'CurseForge',
    ],
    'app' => [
        'title' => 'SkinMC Android App',
        'headline' => 'Diga Olá! para o App SkinMC para Android',
        'play-store-attribution' => 'Google Play and the Google Play logo are trademarks of Google LLC.',
        'features' => 'Convenient features for on the go',
        'feature-qr' => 'Built in QR-Code scanner',
        'feature-qr-detail' => 'Use the built in QR-Code scanner to easily get a skin from your Desktop to the app, or scan your friends custom profile QR-Code.',
        'feature-files' => 'Saves directly to files',
        'feature-files-detail' => 'With the usage of Android Files Manager, the app can conveniently save Skins, making it easier to apply in Bedrock Edition.',
        'feature-noads' => 'No ads',
        'feature-noads-detail' => 'A clean designed interface, without distractions. Enjoy an Ad-free experience without intrusive annoyances from web to app.',
        'feature-experience' => 'Experience',
        'feature-experience-detail' => 'Enjoy the full SkinMC experience anywhere, with added features. Customise your profile, add your bio, create a fun QR-Code and more!',
        'get-app-headline' => 'Get the SkinMC App',
        'get-app-detail' => 'Your very own Minecraft companion for your Android — available for free.'
    ],
    'random' => [
        'title' => 'Loading random Minecraft skin',
        'description' => 'Loading random Minecraft skin',
        'headline' => 'Please wait...',
        'redirect' => 'You will be automatically redirected. Page not loading?',
        'click-here' => 'Click here',
        'messages' => [
            '1' => 'Loading random Minecraft skin...',
            '2' => 'Digging down...',
            '3' => 'Creeper, aw man...',
            '4' => 'Searching through chests...',
            '5' => 'Did you know the coming skin is completely random?',
            '6' => 'Random skin incoming...',
            '7' => 'One more block...',
            '8' => 'Sorting inventory...',
            '9' => 'Crafting diamond pickaxe...',
            '10' => 'Looking for Herobrine...',
        ],
    ],
    'feed' => [
        'title' => 'Feed',
        'following' => 'Following',
        'sign-up' => 'Sign up or log in to join the conversation.',
        'link-account' => 'Link your Minecraft account to join the conversation.',
        'placeholder' => 'What is happening?',
        'audience' => 'Audience',
        'audience-title' => 'Who can see this?',
        'everyone' => 'Everyone',
        'everyone-info' => 'Anyone on or off SkinMC.',
        'followers' => 'Followers',
        'followers-info' => 'Signed in or members following me.',
        'private' => 'Only me',
        'private-info' => 'Private post only I can see.',
        'submit' => 'Post',
        'like' => 'Like',
        'comment' => 'Reply',
        'share' => 'Share',
        'remaining' => 'Remaining',
        'profile' => 'Posts by :username',
        'posts' => 'All posts',
        'my-posts' => 'My posts',
        'view-all' => 'View all posts',
        'post' => [
            'meta' => ':username on SkinMC: :text',
            'title' => 'Post',
            'created' => 'Status update posted!',
            'confirm-delete' => 'Are you sure you would like to delete this post? It can not be undone.',
            'delete' => 'Delete post',
            'deleted' => 'Your post was deleted.',
        ],
        'repost' => [
            'button' => 'Repost',
            'quote_button' => 'Quote',
            'title' => 'Repost this post',
            'quote_title' => 'Quote post',
            'quote_label' => 'Add a comment (optional)',
            'quote_placeholder' => 'Add your thoughts...',
            'reposted' => 'reposted',
            'success' => 'Reposted!',
            'removed' => 'Repost removed.',
            'already_reposted' => 'You have already reposted this.',
            'undo' => 'Undo repost',
            'original_deleted' => 'The original post has been deleted.',
            'deleted_post' => 'This post has been deleted',
        ],
        'poll' => [
            'title' => 'Poll',
            'create' => 'Create a poll',
            'option' => 'Option',
            'add_option' => 'Add option',
            'duration' => 'Duration',
            'duration_1' => '1 day',
            'duration_3' => '3 days',
            'duration_7' => '7 days',
            'votes' => '{0} votes|{1} vote|[2,*] votes',
            'ended' => 'Poll ended',
            'ends_in' => 'Ends :time',
            'login_required' => 'Sign in to vote',
        ],
        'gif' => [
            'title' => 'GIF',
            'search_placeholder' => 'Search KLIPY for GIFs...',
            'no_results' => 'No GIFs found',
            'powered_by' => 'Powered by',
            'categories' => 'Categories',
            'trending' => 'Trending',
        ],
        'media' => 'Media',
        'follow-suggestions' => 'Follow the team',
        'explore' => 'Explore',
        'hashtag' => 'Hashtag',
        'stories' => [
            'archive' => [
                'title' => 'Story Archive',
                'subtitle' => 'Your archived stories are only visible to you',
                'empty' => 'No archived stories yet',
                'empty-description' => 'Stories you post will appear here after 24 hours.',
                'action' => 'Archive',
                'archived' => 'Story moved to archive.',
                'already-archived' => 'Story is already archived.',
            ],
        ],
    ],
    'private' => [
        'title' => 'Private posts',
        'text' => 'This post is private.'
    ] ,
    'liked' => [
        'title' => 'Liked'
    ],
    'following' => [
        'title' => 'Following',
        'text' => 'Sign in to view this post.'
    ],
    'tags' => [
        'empty' => 'No tags to vote on yet',
        'empty-subtitle' => 'Be the first to add one',
    ],
    'inbox' => [
        'title' => 'Messages',
        'details' => 'Details',
        'message_user' => 'Message',
        'write_message' => 'Write a message',
        'empty' => [
            'no_message_selected' => 'No message selected',
            'open_or_start_conversation' => 'Open a conversation from the message list, or start a new one.',
            'no_messages' => 'No unread messages',
            'start_conversation' => 'Once you start a new conversation, your messages will be displayed here.',
            'conversation' => 'This is the beginning of your conversation with :username.',
            'users' => 'Unable to find any users that match the current query.'
        ],
        'typing' => ':username is typing...',
        'new_message' => 'New message',
        'mark_unread' => 'Mark unread',
        'send_message' => 'Send message',
        'delete_message' => 'Delete message for you',
        'latest_conversations' => 'Latest conversations',
        'delete_conversation' => 'Delete conversation',
        'show_details' => 'Show details',
        'hide_details' => 'Hide details',
        'unread' => 'Unread',
        'deleted' => 'Deleted',
        'report_message' => 'Report message',
        'add_reaction' => 'Add reaction',
        'today' => 'Today',
        'reconnect' => 'Please reconnect your Minecraft account to chat',
        'account_disconnected' => 'This user disconnected their linked Minecraft account.',
        'saved_messages' => 'Saved messages',
        'new_message_to_label' => 'To',
        'external-link-to' => 'This link will take you to',
        'external-link-confirmation' => 'Are you sure you want to go there?',
        'external-link' => 'External link',
        'reply' => 'Reply'
    ],
    'server' => [
        'manage' => [
            'stats' => 'Stats'
        ]
    ],
    'report' => [
        'button' => 'Report',
        'title' => 'Report content',
        'describe' => 'Briefly describe why you are reporting this',
        'select' => 'Select report reason',
        'submit' => 'Submit report',
        'reasons' => [
            'INAPPROPRIATE_CONTENT' => 'Inappropriate content',
            'SPAM' => 'Spam',
            'HARASSMENT' => 'Harassment',
            'OTHER' => 'Other',
        ]
    ],
    'leaderboard' => [
        'title' => 'Leaderboard',
        'description' => 'View the SkinMC leaderboard of users.',
        'headline' => 'Top 10',
        'all-time-invites' => 'All time invites',
        'all-time-xp' => 'All time XP',
        '30-day-xp' => '30 days XP'
    ],
];
