<?php

return [
    'login' => [
        'title' => 'ورود',
        'email' => 'آدرس ایمیل',
        'password' => 'کلمه عبور',
        'button' => 'ورود',
        'editor_save_context' => "Log in to save your skin to the gallery. Your work won\\'t be lost.",
        'forgot' => 'کلمه عبورتان را فراموش کردید؟',
        'reset' => 'بازنشانی',
        'register' => 'حساب کاربری ندارید؟',
        'signup' => 'ثبت‌نام کنید!',
        'google' => 'ادامه با گوگل',
        'microsoft' => 'Continue with Microsoft',
        'facebook' => 'ورود از طریق فیسبوک',
        'twitter' => 'ورود از طریق فیس بوک',
        'divider' => 'or',
    ],
    'signup' => [
        'title' => 'ثبت‌نام کنید!',
        'existing' => 'قبلا حساب باز کرده‌اید؟',
        'button' => 'Agree and continue',
        'terms_by_selecting' => 'By selecting',
        'terms_agree_to' => ', I agree to SkinMC\'s',
        'terms_acknowledge' => 'and acknowledge the',
    ],
    'recover' => [
        'title' => 'بازیابی حساب کاربری',
        'description' => 'رمز عبور خود را فراموش کرده اید؟ با وارد کردن آدرس ایمیل خود آن را بازیابی کنید تا آن را برگردانید.',
        'button' => 'ارسال ایمیل بازیابی',
        'found' => 'کلمه عبور خود را پیده کردید؟',
    ],
    'logout' => [
        'title' => 'خروج',
        'description' => 'آیا مطمئن هستید که می خواهید از حساب اسکین ام سی خود خارج شوید؟',
        'logout' => 'خروج',
        'cancel' => 'لفو',
    ],
    'profile_qrcode' => [
        'title' => 'اسکن کیو ار کد',
        'done' => 'انجام شد',
    ],
    'language' => [
        'title' => 'زبان',
        'description' => 'زبان خود را انتخاب کنید',
        'contribute' => 'مشارکت',
        'contribute_add' => 'اضافه کردن ترجمه جدید',
        'updated' => 'زبان شما ثبت شد',
    ],
    'copied' => 'به کلیپ برد کپی شد!',
    'close' => 'بستن',
    'feedback' => [
        'title' => 'بازخورد',
        'type' => [
            'select' => 'انتخاب نوع بازخورد',
            'label' => 'تایپ بازخورد',
            'comment' => 'نظرات',
            'question' => 'سوال ها',
            'bug' => 'گزارش اشکال',
            'feature' => 'درخواست قابلیت جدید',
        ],
        'submit' => 'ثبت',
        'nps' => 'در مقیاس 0 تا 10 چقدر احتمال دارد که اسکین ام سی را به یک دوست توصیه کنید؟',
        'success' => [
            'title' => 'از شما متشكريم!',
            'message' => 'پیام شما ارسال شده است، منتظر پاسخ به زودی باشید! برای سؤالات بیشتر، راحت به دیسکورد بپیوندید یا پیام دیگری ارسال کنید.',
        ],
    ],
];
