<?php

return [
    'common' => [
        'collection' => 'Collection',
        'collections' => 'Collections',
        'unknown_creator' => 'Minecraft creator',
        'items_count' => '{0} No items|{1} :count item|[2,*] :count items',
        'public_items_count' => '{0} No public items|{1} :count public item|[2,*] :count public items',
    ],
    'item_types' => [
        'skin' => 'Skin creation',
        'base' => 'Skin base',
        'cape' => 'Cape',
    ],
    'status' => [
        'public' => 'Public',
        'unlisted' => 'Unlisted',
        'draft' => 'Draft',
        'pending' => 'Pending review',
        'archived' => 'Archived',
        'banned' => 'Unavailable',
    ],
    'actions' => [
        'create' => 'Create collection',
        'edit' => 'Edit collection',
        'delete' => 'Delete collection',
        'remove' => 'Remove',
        'move_up' => 'Move up',
        'move_down' => 'Move down',
        'favorite' => 'Add collection to favourites',
        'unfavorite' => 'Remove collection from favourites',
        'share' => 'Share collection',
    ],
    'gallery' => [
        'meta_title' => 'Minecraft Creator Collections',
        'meta_description' => 'Explore :count collections of matching Minecraft skins, reusable bases, and capes.',
        'heading' => 'Creator collections',
        'subtitle' => 'Explore matching Minecraft skins, reusable bases, and capes organised by creators.',
        'sort' => 'Sort',
        'sort_menu_aria' => 'Sort creator collections',
        'sort_newest' => 'Newest',
        'sort_oldest' => 'Oldest',
        'sort_views' => 'Most viewed',
        'sort_items' => 'Most items',
        'empty_title' => 'No public collections yet',
        'empty_message' => 'Creator collections will appear here as soon as they contain a public item.',
        'empty_alt' => 'A collection of Minecraft creations',
    ],
    'create' => [
        'meta_title' => 'Create a Minecraft collection',
        'meta_description' => 'Organise your Minecraft skin creations, reusable bases, and custom capes.',
        'heading' => 'Create a collection',
        'subtitle' => 'Bring matching skins, bases, and capes together in an ordered series.',
    ],
    'edit' => [
        'meta_title' => 'Edit :title',
        'meta_description' => 'Update your Minecraft creator collection.',
        'heading' => 'Edit collection',
        'subtitle' => 'Update its details, members, and display order.',
        'delete_confirm' => 'Delete this collection? Its skins, bases, and capes will not be deleted.',
    ],
    'show' => [
        'meta_title' => ':title — Minecraft creator collection',
        'meta_title_fallback' => 'Minecraft creator collection',
        'meta_description_fallback' => 'A collection of matching Minecraft skins, bases, and capes.',
        'views' => ':count views',
        'empty_title' => 'No public items in this collection',
        'empty_owner_title' => 'This collection is empty',
        'empty_message' => 'Draft, unlisted, pending, and archived items stay hidden from visitors.',
        'empty_owner_message' => 'Edit the collection to add a skin creation, skin base, or custom cape.',
        'staged_notice' => 'Only you can see staged items. Visitors only see public and approved work.',
    ],
    'form' => [
        'title' => 'Title',
        'title_placeholder' => 'For example: Frostbound series',
        'description' => 'Description',
        'description_placeholder' => 'Tell visitors how the skins, bases, and capes belong together.',
        'selected_items' => 'Selected items',
        'selected_empty' => 'Choose at least one item when creating a collection.',
        'available_items' => 'Your creations',
        'search_items' => 'Search your creations',
        'search_placeholder' => 'Search by title or type',
        'no_matching_items' => 'No creations match these filters.',
        'library_empty' => 'Upload a skin creation or base to start your first collection. Your custom capes will appear here too.',
        'upload_creation' => 'Upload a creation',
        'clear_filters' => 'Clear filters',
        'load_more' => 'Show more creations',
        'sort_items' => 'Sort your creations',
        'sort_title' => 'Title A–Z',
        'results_count' => ':shown of :total creations',
        'selection_limit' => 'All :max spaces are filled. Remove an item before adding another.',
        'order_hint' => 'Use the arrows to arrange the collection. The first public items appear on its cover.',
        'item_added' => ':title added to the collection.',
        'item_removed' => ':title removed from the collection.',
        'item_moved' => ':title moved to position :position.',
        'saving' => 'Saving…',
        'picker_hint' => 'Draft and pending work can be staged, but visitors will only see public items.',
        'filter_all' => 'All',
        'filter_skin' => 'Skins',
        'filter_base' => 'Bases',
        'filter_cape' => 'Capes',
        'create_submit' => 'Create collection',
        'update_submit' => 'Save collection',
        'cancel' => 'Cancel',
    ],
    'flash' => [
        'created' => 'Collection created.',
        'updated' => 'Collection updated.',
        'deleted' => 'Collection deleted.',
        'item_added' => 'Item added to the collection.',
        'item_removed' => 'Item removed from the collection.',
        'memberships_updated' => 'Collections updated.',
        'reordered' => 'Collection order updated.',
    ],
    'validation' => [
        'min_items' => 'Select at least :min item.',
        'max_collections' => 'You can create up to :max collections.',
        'max_items' => 'A collection can contain up to :max items.',
        'invalid_selection' => 'One or more selected items are invalid or unavailable.',
        'invalid_collection_selection' => 'One or more selected collections are invalid.',
        'owner_only' => 'Collections can only contain work you created.',
    ],
    'picker' => [
        'open' => 'Add to collection',
        'heading' => 'Add to collections',
        'description' => 'Choose every collection this item should belong to.',
        'empty' => 'You have not created a collection yet.',
        'create_new' => 'Create a new collection',
        'create_and_add' => 'Create and add',
        'search_placeholder' => 'Search your collections',
        'no_matches' => 'No collections match your search.',
        'save' => 'Save collections',
        'cancel' => 'Cancel',
    ],
    'publish' => [
        'heading' => 'Add to collections',
        'description' => 'Include this item in existing collections or create a matching series as you publish.',
        'no_collections' => 'You do not have any collections yet.',
        'create_new_toggle' => 'Create a new collection for this item',
        'new_title' => 'New collection title',
        'new_description' => 'New collection description (optional)',
    ],
    'account' => [
        'meta_title' => 'Your creator collections',
        'meta_description' => 'Manage your collections of matching Minecraft skins, bases, and capes.',
        'heading' => 'Your collections',
        'subtitle' => 'Organise skin series and manage staged or public collection items.',
        'total_items' => '{0} No items|{1} :count total item|[2,*] :count total items',
        'public_items' => '{0} No public items|{1} :count public item|[2,*] :count public items',
        'empty_title' => 'You have not created a collection yet',
        'empty_message' => 'Group matching skin creations, reusable bases, and custom capes into a series.',
        'browse' => 'Browse collections',
    ],
];
