<?php

return [
    'skins' => 'Skins',
    'avatars' => 'Avatars',
    'editor' => 'Editeur',
    'heads' => 'Tête',
    'capes' => 'Captures',
    'servers' => 'Serveurs',
    'achievement' => 'Accomplissement',
    'armor' => 'Porte-armure',
    'banners' => 'Bannière',
    'banner' => 'Éditeur de bannière',
    'profile' => 'Mon profil',

    'generators' => 'Générateur',

    // Navigation dropdowns
    'feed' => 'Fil d\'actualités',
    'discover' => 'Découvrir',
    'mods' => 'Mods',
    'shaders' => 'Shaders',
    'resource_packs' => 'Packs de ressources',
    'modpacks' => 'Modpacks',
    'datapacks' => 'Datapacks',
    'plugins' => 'Plugins',

    'logout' => 'Déconnexion',
    'register' => 'S\'inscrire',
    'login' => 'Se connecter',
    'about' => 'À propos de',
    'contact' => 'Contact',
    'faqs' => 'Foire aux questions',

    'minecraft_name' => 'Nom de Minecraft',
    'minecraft_uuid' => 'Minecraft UUUID',
    'what' => 'Quoi',
    'recent_searches' => 'Recherches récentes',
    'username' => 'Pseudo',
    'uuid' => 'UUID',
    'search' => 'Chercher',
    'search_placeholder' => 'Essayer',
    'search_placeholder_uuid' => 'Saisir l\'UUID',
    'start_search' => 'Commencer la recherche',
    'cancel_search' => 'Abandonner',
    'search_type' => 'Type de recherche',
    'search_type_all' => 'Tous les résultats',
    'profiles' => 'Profils',
    'view_skin' => 'Voir le thème',
    'edit_skin' => 'Modifier le skin',
    'make_avatar' => 'Faire un avatar',
    'find_heads' => 'Trouver des têtes de joueur',

    'home' => 'Domicile',
    'help' => 'Aide',
    'tools' => 'Outils',
    'more-tools' => 'Plus d\'outils',
    'skin_viewer' => 'Visionneuse de thème',
    'avatar_maker' => 'Créateur d\'Avatar',
    'collections' => 'Collections',
    'popular_skins' => 'Skins populaires',
    'cartoon_skins' => 'Skins Cartoon',
    'animal_skins' => 'Peaux d\'animal',
    'community' => 'Communauté',
    'imprint' => 'Mentions légales',
    'cookies' => 'Cookies',
    'terms' => 'Conditions Générales d\'Utilisation',
    'privacy' => 'Politique de confidentialité',
    'app' => 'Appli',
    'mod' => 'Mod',
    'totem' => 'Totems',
    'cube' => 'Cube',
    'new' => 'Nouveau',

    'feedback' => 'Commentaires',
    'status' => 'Statut',
    'recent_searches_placeholder' => 'Voici les dernières recherches que vous avez effectuées.',
    'recent_views_placeholder' => 'Voici les profiles que vous avez regardés il y a pas longtemps.',
    'moderate' => 'Modéré',
    'listings' => 'Listes',
    'add' => 'Ajouter',

    'theme' => [
        'title' => 'Thème',
        'dark' => 'Sombre',
        'light' => 'Clair',
        'auto' => 'Auto'
    ],
];
