<?php

return [
    'auth' => [
        'login' => [
            'title' => 'Bienvenue sur SkinMC',
        ],
        'register' => [
            'title' => 'Inscrivez-vous à SkinMC',
            'subtitle' => 'Commencez à créer votre compte pour profiter de toutes les fonctionnalités.',
        ],
    ],

    'home' => [
        'hero_slogan' => 'Votre place pour les skins Minecraft.',
        'hero_slogan_alt_1' => 'Tout Minecraft. Un endroit.',
        'hero_slogan_alt_2' => 'Là où les Minecrafters se rencontrent.',
        'hero_cta' => 'Surprenez-moi',
        'hero_explore_cta' => 'Explorer les skins',
        'skin_viewer' => 'Visualiseur de skins',
        'skin_viewer_detail' => 'Voir :count skins',
        'skin_editor' => 'Éditeur de skins',
        'skin_editor_detail' => 'Concevez votre propre skin',
        'avatar_maker' => 'Générateur d\'avatar',
        'avatar_maker_detail' => 'Générez votre avatar Minecraft personnalisé.',
        'trending' => 'Tendance',
        'minecraft_skin' => 'Skin Minecraft',
        'favourite' => 'Favori',
        'collections' => 'Collections',
        'collections_detail' => 'Skins Minecraft organisés pour chaque occasion',
        'about_skinmc' => 'À propos de SkinMC',
        'about_find' => 'Trouver un skin',
        'about_find_detail' => 'Utilisez la recherche SkinMC pour trouver n\'importe quel pseudonyme Minecraft, afin de voir et télécharger votre prochain skin.',
        'about_download' => 'Télécharger ou modifier',
        'about_download_detail' => 'Vous avez trouvé un skin que vous appréciez ? Ajoutez-le à vos favoris, modifiez ou téléchargez-le afin d\'en faire le votre.',
        'about_platform' => 'Multi-plateforme',
        'about_platform_detail' => 'Voulez-vous prendre le skin ? Scannez le QR code et enregistrez l\'image sur votre téléphone pour Minecraft PE.',
        'meta' => [
            'title' => 'Visualiseur de skins Minecraft',
            'description' => 'Visualisez et téléchargez les skins Minecraft, découvrez les meilleurs skins dans les collections organisées, vérifiez la disponibilité d\'un pseudonyme, son historique, et bien plus encore !',
        ],
        'recently_viewed' => 'Récemment consulté',
        'explore_title' => 'Testez une nouveautée',
        'explore' => 'Explorez de nouvelles idées et outils',
        'servers_browse' => 'Voir les serveurs',
        'servers' => 'Découvrez les meilleurs serveurs Minecraft',
        'heads' => 'Têtes Minecraft',
        'head_description' => 'Parcourez les têtes de skins dans la base de donnée de Minecraft, ou créez en un.',
        'achievement' => 'Générateur de succès',
        'achievement_detail' => 'Créez vos propres succès personnalisés.',
        'continue' => 'Continuer la navigation',
        'totem' => 'Minecraft Totem Generator',
        'totem_description' => 'Create a custom Minecraft resource pack with a Totem of Undying from any skin.',
        'banner' => 'Minecraft Banner Generator',
        'banner_description' => 'Generate and preview custom Minecraft banners and patterns.',
        'capes' => 'Minecraft Capes',
        'capes_description' => 'Browse the largest collection of Minecraft capes, or create your own.',

    ],
    'profile' => [
        'verified' => 'Profil vérifié',
        'minecraft_profile' => 'Profil Minecraft',
        'show_qr_code' => 'Afficher le QR code',
        'favourite' => 'Favori',
        'user_title' => 'Skins Minecraft de :username',
        'user_views' => 'Vu :views fois|Vu :vues fois',
        'uuid' => 'UUID',
        'copy' => 'Copier',
        'link' => 'Lier',
        'skin_history' => 'Histoique des skins Minecraft (:skins)',
        'username_history' => 'Historique des pseudonymes',
        'username_history_name' => 'Pseudo',
        'username_history_timestamp' => 'Changé le',
        'username_history_initial_name' => 'Pseudo initial',
        'user_downloads' => ':downloads téléchargement|:downloads téléchargements',
        'download_skin' => 'Télécharger le skin',
        'apply_skin' => 'Appliquer le skin',
        'capes' => 'Capes',
        'claim_profile' => 'Êtes-vous :username ? Réclamez votre profil afin de le vérifier & de le personnaliser !',
        'claimed' => 'Profil réclamé',
        'meta_description' => 'Voir et télécharger le skin Minecraft de :username. Voir l\'UUID lié au pseudo, l\'historique de son nom, des statistiques détaillées, et plus',
        'created_at' => 'Mis à jour : :changed_at',
        'skins' => [
            'meta_title' => 'Historique des skins Minecraft de :username',
            'meta_description' => 'Regarde l\'historique des skins Minecraft précédemment utilisées par :username. Utilisez cet historique afin de parcourir les skins qui ont été utilisés par le passé, en avoir une sauvegarde et les récupérer.',
            'title' => 'Historique des skins Minecraft',
        ],
        'qr_code' => [
            'meta_title' => 'QR code de :username',
            'meta_description' => 'QR code personnalisé du profil Minecraft de :username',
        ],
        'sub_nav' => [
            'skin' => 'Skin',
            'about' => 'À propos',
            'usernames' => 'Pseudonymes',
            'head' => 'Tête',
            'comments' => 'Commentaires',
        ],
        'cape' => 'Cape',
        'elytra' => 'Élytres',
        'nametag' => 'Pseudonyme',
        'animation' => 'Animation',
        'rotation' => 'Rotation',
        'none' => 'Aucun',
        'idle' => 'Au repos',
        'walk' => 'Marche',
        'run' => 'Course',
        'fly' => 'Vol',
        'follow' => 'S\'abonner',
        'following' => 'Abonné',
        'unfollow' => 'Se désabonner',
        'followers' => 'Abonné|Abonnés',
        'toast' => [
            'following' => 'Vous vous êtes abonné à :username !',
            'follow-self-error' => 'Désolé :username, mais tu ne peux pas te suivre toi-même.',
            'unfollowed' => 'Vous vous êtes désabonné de :username',
        ],
        'edit' => 'Modifier votre profil',
        'joined' => 'Rejoint',
        'role' => 'Rôle',
        'server-fav-list-empty' => 'On dirait que :username n\'a pas encore de serveurs favoris. Une fois que :username auras enregistré un serveur comme favoris, vous pouvez le voir ici.',
        'server-own-list-empty' => 'On dirait que :username n\'a pas encore de serveurs favoris. Une fois que :username auras enregistré un serveur comme favoris, vous pouvez le voir ici.',
        'capes-list-empty' => 'On dirait que :username ne porte pas encore de capes. Une fois que :username porte une cape, vous pourrez le voir ici.',
        'feed-own-list-empty' => 'Il semble que vous n\'ayez rien posté sur le flux ! Une fois que vous auriez posté quelque chose, vous pouvez voir vos messages ici.',
        'feed-list-empty' => 'Hmm, il semble que :username n\'ait encore rien posté dans le flux. Une fois que :username postera quelque chose, vous pouvez le voir ici.',
        'following-own-list-empty' => 'Il paraît que vous ne suivez encore personne ! Une fois que vous suivrez des personnes, vous pourrez les voir ici.',
        'following-list-empty' => 'Hmm, il paraît que :username ne s\'est abonné à personne. Une fois qu\'il se sera abonné à quelqu\'un, vous pourrez voir ses abonnements ici.',
        'followers-own-list-empty' => 'les personnes qui s\'abonnent à vous seront affichés ici.',
        'followers-list-empty' => 'Hmm, il paraît que :username n\'est pas encore suivi. Soyez le premier à vous abonner à :username. Les abonnés de :username apparaîtrons ici, uen fois que quelqu\'un s\'y abonnera.',
        'render' => 'Moteur de rendu',
        '3d' => 'Rendu 3D',
        '2d' => 'Rendu 2D',
        'name-history-info' => 'L\'historique des pseudonymes disparaît. Majong a retiré l\'accès à l\'historique des noms via leur API le 13 septembre 2022, résultant à un historique des pseudos indisponible. Si vous voulez retirer la visibilité de vous anciens pseudonymes, merci de réclamer votre profil et d\'aller dans vos paramètres afin de les rendre privés.',
        'edit-skins' => 'Modifier l\'historique des skins',
        'hide-skin' => 'Masquer le skin',
        'show-skin' => 'Afficher le skin',
        'edit-skin' => 'Modifier le skin',
        'servers' => [
            'title' => 'Serveurs de :username',
        ],
        'cape-list' => [
            'title' => 'Capes de :username',
        ],
    ],
    'skin' => [
        'meta' => [
            'title' => 'Skin Minecraft de :username',
            'description' => 'Skin Minecraft. Téléchargez et visualisez le skin, et voyez quels joueurs portent également le même skin.',
            'tags' => ':username Skin Minecraft, :username Skin, Minecraft Skin, :username Skin Minecraft personnalisé, Télécharger Skin, Joueurs avec le même skin',
        ],
        'title' => 'Skin Minecraft de :username',
        'head' => 'Commandes pour obtenir la tête',
        'head_info' => 'À utiliser avec les blocs de commande',
        'first_wearing' => 'Premier joueur vu porter cette apparence :',
        'profiles' => 'Profile de :profiles|Profiles de :profiles',
        'profiles_title' => ':profile avec ce skin |:profiles avec ce skin',
        'screenshot' => 'Capture d\'écran',
    ],
    'skins' => [
        'meta' => [
            'title' => 'Page :current — Touts les Skins Minecraft',
            'description' => 'Parcourez notre liste :last pages de :total skins Minecraft personnalisés et téléchargez votre prochain skin préféré !',
            'tags' => ':username Skin Minecraft, :username Skin, Minecraft Skin, :username Skin Minecraft personnalisé, Télécharger le Skin, Joueurs avec le même skin',
            'tags-title' => ':tag Skins Minecraft',
            'tags-description' => 'Parcourez notre liste de :last pages de :total :tag skins Minecraft et téléchargez votre skin :tag préféré !',
            'tags-metatags' => ':tag Skin Minecraft, :tag Skin, Skin Minecraft, :tag Skin Minecraft personnalisé, Télécharger un skin :tag, Skin :tag Minecraft',
        ],
        'title-skin-tags' => 'Skins Minecraft taggés',
        'subtitle' => 'Page :current sur :last de :total Skins Minecraft',
        'subtitle-skin-tags' => 'Page :current sur :last de :total Skins Minecraft taggés',
        'sort_by' => 'Trier par',
        'latest' => 'Derniers skins',
        'most_profiles' => 'Skins les plus utilisés',
        'profiles_today' => 'Tendance d\'aujourd\'hui',
        'profiles_this_week' => 'Tendance de cette semaine',
        'profiles_this_month' => 'Tendance du mois',
        'default' => 'Tri par défaut',
        'this_month' => 'Ajoutés ce mois',
        'this_week' => 'Ajoutés cette semaine',
        'today' => 'Ajoutés aujourd\'hui',
        'random' => 'Aléatoire',
        'similar' => 'Skins similaires',
        'no_similar_skins' => 'Malheureusement, aucuns skins similaires ont été trouvés.',
        'favorite' => ':favoris:favoris',
    ],
    'skin-tags' => [
        'faq' => 'Que sont les tags ?',
        'about' => 'Les tags sont un moyen d\'ajouter vos catégories aux skins. Ajouter des tags vous permet de découvrir plus de skins que vous aimez facilement !',
        'guidelines' => [
            'good' => [
                'title' => 'Les directives générales pour les bonnes balises sont :',
                'short' => 'Court',
                'descriptive' => 'Description',
                'spelled' => 'Orthographe correcte',
            ],
            'bad' => [
                'title' => 'Ne pas ajouter de balises telles que:',
                'general' => 'Trop général',
                'specific' => 'Trop spécifique',
                'too-many-tags' => 'Doit être trois balises séparées',
                'spelling' => 'Doit être :example',
            ],
        ],
        'toast' => [
            'added' => 'Étiquette ”:tag” ajoutée pour le vote',
            'removed' => 'L\'étiquette ”:tag” a été supprimé',
            'upvote' => 'Voté pour ":tag"',
            'downvote' => 'Voté contre ”:tag”',
        ],
        'vote' => [
            'up' => 'Voter',
            'down' => 'Voter contre',
            'remove' => 'Retirer le vote',
        ],
    ],
    'contact' => [
        'contact' => 'Contact',
        'email' => 'N\'hésitez pas à nous écrire à <a href="mailto:support@skinmc.net">support@skinmc.net</a> pour toutes questions.',
        'faq' => 'Nous vous prions de bien vouloir d\'abord consulter la page <a href=":link">FAQ</a> si votre question y est déjà répondue.',
        'other' => 'Autres moyens de se connecter',
        'other_discord' => 'Rejoignez le serveur Discord et connectez-vous avec d\'autres joueurs, discutez à propos des jeux, partagez vos packs favoris et obtenez de l\'aide de la communauté.',
        'other_twitter' => 'Suivez-nous sur X (avant Twitter) pour voir quand une nouvelle mise à jour, une nouvelle fonctionnalité est publiée, même voir le skin de la semaine et encore plus.',
        'other_instagram' => 'Suivez SkinMC sur Instagram pour naviguer et découvrir de nouveaux skins et images Minecraft mis en avant.',
        'other_facebook' => 'Devenez fan sur Facebook et voyez tous les messages où vous pouvez commenter et parler à d\'autres tout en explorant le contenu de Minecraft.',
    ],
    'about' => [
        'intro' => '<span>Votre plateforme</span> <span></span> <span>pour</span> <span>skins Minecraft</span> <span>.</span>',
        'header_credit' => 'Illustration "Bataille du Nether Épique" par',
        'info' => 'Garder une trace de tout.',
        'info_explainer' => 'Voir l\'historique des noms des joueurs, voir leurs skins précédents, les ajouter en tant qu\'ami, télécharger des skins et même obtenir des statistiques détaillées.',
        'card_find_title' => 'Trouvez n\'importe quel minecrafter',
        'card_find_detail' => 'Commencez par rechercher un nom d\'utilisateur ou un UUID de votre choix.',
        'card_view_title' => 'Afficher, enregistrer et éditer',
        'card_view_detail' => 'Vous avez trouvé un skin que vous aimez ? Enregistrez-le en téléchargeant ou en utilisant l\'éditeur pour le faire vous-même.',
        'card_claim_title' => 'Obtenir une vérification',
        'card_claim_detail' => 'Liez votre compte Minecraft et revendiquez votre profil pour débloquer de nouvelles fonctionnalités !',
        'card_customise_title' => 'Personnalisez votre profil',
        'card_customise_detail' => 'Les joueurs vérifiés peuvent ajouter leurs liens vers les réseaux sociaux et faire leur propre profil.',
        'card_friends_title' => 'Ajoutez vos amis',
        'card_friends_detail' => 'Connectez-vous avec vos amis sur SkinMC et montrez votre liste d\'amis sur le profil.',
        'card_history_title' => 'Nom d\'utilisateur et historique du thème',
        'card_history_detail' => 'Utilisez la recherche avancée pour trouver et voir le nom d\'utilisateur/l\'historique du skin d\'un joueur.',
        'founders' => 'Les fondateurs',
        'founders_cofounder' => 'Co-fondateurs de SkinMC',
        'head_of_design' => 'Chef de design',
        'head_of_code' => 'Chef de code',
        'feedback' => 'Envoyez-nous votre avis',
        'faq' => 'Des questions sur Minecraft, des skins et plus encore ? Lisez notre FAQ avec les réponses aux questions les plus fréquemment posées.',
        'faq_link' => 'Visiter la FAQ',
        'contact' => 'Vous voulez nous contacter ou vous avez d\'autres questions ? Contactez-nous directement.',
        'contact_link' => 'Contactez-nous',

    ],
    'faq' => [
        'title' => 'Foire aux questions',
        'subtitle' => 'Foire aux questions',
        'help' => 'Besoin d\'aide supplémentaire?',
        'discord' => 'Rejoignez le serveur Discord pour discuter avec d\'autres joueurs Minecraft.',
        'contact' => 'Contactez-nous',
        'q' => [
            'change_skin_t' => 'Comment puis-je changer mon skin Minecraft ?',
            'change_skin' => '
                <p>Pour changer votre Skin faites ce qui suit :</p>
                <ol>
                    <li>Visitez <a href="https://my.minecraft.net/en-us/login/">https://my. inecraft.net/en-us/login/</a> et connectez-vous avec votre compte Mojang.</li><li>Une fois connecté, sélectionnez <b>"Skin"</b> dans le menu de gauche.</li><li>Ensuite, choisissez un modèle que vous préférez et téléchargez un skin de votre goût.</li>
                </ol>',
            'change_username_t' => 'Comment puis-je changer mon nom d\'utilisateur Minecraft ?',
            'change_username' => '
                <p>Pour modifier votre nom d\'utilisateur :</p>
                <ol>
                    <li>Visitez <a href="https://account.mojang.com/login" target="_blank" rel="nofollow">https://account. ojang.com/connectez-vous</a> et connectez-vous avec votre compte Mojang.</li>
                    <li>Trouvez votre nom de profil Minecraft et appuyez sur le <b>"(Change)"</b> bouton</li>
                    <li>Sur la page suivante, entrez le nouveau nom d\'utilisateur que vous souhaitez.</li>
                    <li>Enfin, confirmez les modifications en saisissant votre mot de passe et en appuyant sur "Changer de nom".</li>
                </ol>',
            'dl_t' => 'Comment télécharger le skin Minecraft de quelqu\'un ?',
            'dl' => '
                <p>Pour télécharger n\'importe qui Skin de Minecraft, faites ce qui suit :</p>
                <ol>
                    <li>Appuyez sur la barre de recherche et entrez le nom d\'utilisateur du joueur dont vous souhaitez télécharger le skin.</li>
                    <li>Sur la page de profil, vous pouvez prévisualiser le skin</li>
                    <li>Cliquez sur le <strong>Télécharger le Skin</strong> sous l\'aperçu</li>
                </ol>',
            'submit_q' => 'Comment puis-je soumettre un skin à une collection ?',
            'submit_a' => '<p>Merci de remplir le formulaire suivant avec la catégorie et le pseudonyme du joueur que vous voudriez ajouter à la collection. <a href="https://forms.gle/f4Jh5RpGfsHAZ5xE8" target="_blank">Formulaire de submition</a>',
            'mcpe_t' => 'Puis-je utiliser le Skin sur Minecraft PE ?',
            'mcpe' => '
                <p>Oui. Pour utiliser le Skin dans Minecraft Pocket Edition, faites ce qui suit :</p>
                <ol>
                    <li>Open SkinMC. sur votre smartphone et appuyez sur la barre de recherche</li>
                    <li>Entrez le nom d\'utilisateur de l\'apparence du joueur que vous souhaitez télécharger</li>
                    <li>Appuyez sur le bouton <strong>Télécharger Skin</strong> sous l\'aperçu </li>
                    <li>Ouvrez Minecraft PE et appuyez sur <strong>Profil</strong> sur le côté droit</li>
                    <li>Tapez sur le <strong>+</strong>, ou modifiez le caractère et allez dans l\'onglet "skins classiques"</li>
                    <li>Appuyez sur "propriété", puis "importer", puis "choisir une nouvelle peau"</li>
                </ol>',
            'change_times_t' => 'À quelle fréquence puis-je changer mon nom d\'utilisateur ?',
            'change_times' => '<p>Vous pouvez changer votre pseudo Minecraft <strong>une fois </strong> tous les <strong>30 jours</strong>.</p>',
            'available_t' => 'Après que j\'ai changé mon nom d\'utilisateur, quand est-il disponible pour les autres de le réclamer?',
            'available' => '<p>Si vous souhaitez revenir à votre nom d\'utilisateur précédent, vous pouvez revenir en arrière <strong>après 30 jours.</strong> Tout le monde a besoin d\'attendre un <strong>7 jours supplémentaires</strong> (37 jours après le changement) avant de pouvoir réclamer votre ancien nom d\'utilisateur. </p>',
            'username_history_t' => 'Pouvez-vous supprimer l\'historique de mon nom d\'utilisateur s\'il vous plaît ?',
            'username_history' => '
                <p>Comme les données de l\'historique du nom d\'utilisateur viennent de Mojang, l\'historique du nom d\'utilisateur ne peut pas être supprimé. Mojang a précédemment déclaré que leur intention était que les noms d\'utilisateur précédents puissent être vus1, et qu\'ils fournissent une méthode directe pour le public pour accéder à ces informations2.</p>
                <p class="font-14">1<a href="https://help.minecraft.net/hc/en-us/articles/360034636712-Minecraft-Usernames" target="_blank" rel="noreferrer">https://help. inecraft. et/hc/en-us/articles/360034636712-Minecraft-Usernames</a></p>
                <p class="font-14 mb-0">2<a href="https://twitter.com/dinnerbone/status/554739042529849345" target="_blank" rel="noreferrer">https://twitter. om/dinnerbone/status/554739042529849345</a> (Tweet archivé il y a 2 ans : <a href="http://archive.is/TeAyj" target="_blank" rel="noreferrer">http://archive. s/TeAyj</a>)
                </p>',
        ],
    ],
    'avatars' => [
        'start' => [
            'title' => 'Créez votre propre avatar Minecraft',
            'subtitle' => 'Utilisez le générateur d\'avatar Minecraft pour créer un avatar amusant à partir de n\'importe quel skin !',
            'avatar_face' => 'Avatar de style visage',
            'avatar_bust' => 'Avatar de style buste',
            'avatar_cube' => 'Avatar de style cube',
            'avatar_head3d' => 'Têtes 3D personnalisés',
        ],
        'user' => [
            'title' => 'Choisir un skin',
            'subtitle' => 'Entrez le nom d\'utilisateur Minecraft pour l\'avatar que vous souhaitez générer',
            'form_label' => 'Nom d\'utilisateur Minecraft',
            'form_submit' => 'Continuer',
        ],
        'output' => [
            'title' => 'Prévisualiser et enregistrer',
            'subtitle' => 'Profitez de votre nouvel avatar Minecraft',
            'download_info' => 'Heureux avec le résultat ? Commencez à utiliser votre nouvel avatar en le téléchargeant ici',
            'download_button' => 'Télécharger l\'avatar',
            'avatar_style' => 'Style de l\'avatar',
            'skin_username' => 'Nom d\'utilisateur du thème',
            'change' => 'Changement',
            'generate' => 'Générer',
            'avatar_colour' => 'Couleur d\'arrière-plan',
            'avatar_colour_palette' => 'Palette',
            'avatar_colour_basic' => 'Basique',
        ],
        'meta' => [
            'title' => 'Générateur d\'Avatar Minecraft',
            'description' => 'Minecraft Avatar Maker: créez des images de profil Minecraft personnalisées en utilisant votre skin Minecraft',
        ],
    ],
    'totem' => [
        'title' => 'Totem Minecraft personnalisé',
        'subtitle' => 'Utilisez le générateur de Totem Minecraft pour créer un pack de ressources personnalisées avec un Totem d\'immortalité à partir de n\'importe quel skin.',
        'download_info' => 'Heureux avec l\'aperçu ? Choisissez votre version de Minecraft pour enregistrer votre pack de ressources personnalisé :',
        'meta' => [
            'title' => 'Générateur de totem personnalisé Minecraft',
            'description' => 'Totems Minecraft personnalisés : générez et créez un pack de ressources Minecraft personnalisé avec un Totem d\'Imortalité en utilisant votre skin Minecraft ou celui de n\'importe quel autre joueur.',
        ],
        'type' => [
            'mini' => 'Une version miniature de votre skin !',
            'full' => 'Une version complète de votre skin !',
            'model3d' => 'Un modèle 3D de votre skin !',
            'add_designs' => 'Vous voulez voir plus de designs ? Soumettez votre suggestion de design ici :',
        ],
    ],
    'achievement' => [
        'header' => [
            'title' => 'Créez votre propre Achievement Minecraft',
            'subtitle' => 'Utilisez le générateur de Achievement Minecraft pour créer vos propres réalisations personnalisées et utiliser montrer vos progrès dans tout ce que vous aimez !',
        ],
        'generator' => [
            'yellow_text' => 'Texte jaune',
            'white_text' => 'Texte blanc',
            'choose_icon' => 'Choisir une icône',
            'face' => 'Face Minecraft au lieu de l\'icône',
            'form_submit' => 'Télécharger',
            'form_label' => 'Nom d\'utilisateur Minecraft',
            'download' => 'Télécharger',
            'embed' => 'Intégrer',
            'embed_copy' => 'Copie',
        ],
        'meta' => [
            'title' => 'Générateur de Achievement Minecraft',
            'description' => 'Générer des Achievements et des Avancements Minecraft personnalisés avec le créateur de Achievements. Télécharger l\'image directement, l\'utiliser dans les signatures du forum, intégrer avec du code HTML ou BB, et plus encore',
        ],
    ],
    'armor' => [
        'header' => [
            'title' => 'Créateur de porte-armure Minecraft',
            'subtitle' => 'Générez et créez vos propres portes armures Minecraft personnalisées. Créez différentes poses, positions, placez des objets et bien plus encore.',
        ],
        'meta' => [
            'title' => 'Créateur de porte-armure Minecraft',
            'description' => 'Générez et créez facilement des porte-armures Minecraft personnalisés. L\'éditeur vous aide à faire différentes positions, placer des objets, des armures personnalisés, et bien plus encore.',
        ],
    ],
    'banner' => [
        'editor' => [
            'header' => [
                'title' => 'Éditeur de bannière Minecraft',
                'subtitle' => 'Concevez et créez vos propres bannières Minecraft personnalisées. Celles-ci peuvent être utilisés pour décorer votre monde ou aussi comme <a href="https://optifine.net" target="_blank" rel="nofollow">Cape Optifine</a>.',
            ],
            'meta' => [
                'title' => 'Créateur de bannière Minecraft',
                'description' => 'Créez et concevez vos propres bannières Minecraft personnalisées avec tous les motifs et couleurs du jeu ! Ils peuvent être utilisés pour décorer votre monde ou être portés en tant que cape Optifine. Vous pouvez générer des commandes pour les obtenires en tant que bannières ou les boucliers.',
            ],
            'toolbar' => [
                'title' => 'Banner Editor',
                'randomise' => 'Randomise',
                'clear_layers' => 'Clear layers',
                'help' => 'Help',
                'save_banner' => 'Save banner',
                'submit_to_gallery' => 'Submit design to banner gallery',
                'reset_from_url' => 'Reset to banner from URL',
                'minecraft_version' => 'Minecraft Version',
                'texture_type' => 'Texture Type',
                'banner' => 'Banner',
                'shield' => 'Shield',
                'version_1_21' => '1.21+',
                'version_1_16' => '1.16 - 1.20',
                'version_1_13' => '1.13 - 1.15',
                'version_1_8' => '1.8 - 1.12',
                'color_black' => 'Black',
                'color_dark_grey' => 'Dark grey',
                'color_grey' => 'Grey',
                'color_white' => 'White',
                'color_pink' => 'Pink',
                'color_magenta' => 'Magenta',
                'color_purple' => 'Purple',
                'color_blue' => 'Blue',
                'color_cyan' => 'Cyan',
                'color_light_blue' => 'Light blue',
                'color_green' => 'Green',
                'color_lime' => 'Lime',
                'color_yellow' => 'Yellow',
                'color_orange' => 'Orange',
                'color_brown' => 'Brown',
                'color_red' => 'Red',
            ],
            'tools' => [
                'share_link' => 'Share link',
                'share_link_placeholder' => 'Share link',
                'generate_codes' => 'Generate codes',
                'target_selector' => 'Target selector',
                'command_give' => 'Give',
                'command_setblock' => 'Setblock',
                'command_replaceitem_shield' => 'Shield',
                'code_placeholder' => 'Select a command to generate code',
                'import_code' => 'Import code',
                'background_grass' => 'Grass background',
            ],
            'modal' => [
                'save_banners' => 'Save banners',
                'share_saved_gallery' => 'Share saved gallery',
                'share_saved_gallery_placeholder' => 'Share saved gallery',
                'export_to_chest' => 'Export to chest',
                'delete_all' => 'Delete all',
            ],
        ],
        'gallery' => [
            'header' => [
                'title' => 'Galerie de bannières Minecraft',
                'subtitle' => 'Parcourez la galerie de :count bannières Minecraft conçues sur mesure. Vous pouvez utiliser une bannière comme cape pour rendre votre skin Minecraft plus unique, ou utilisez une bannière comme drapeau pour décorer votre monde.',
            ],
            'meta' => [
                'title' => 'Galerie de bannières Minecraft',
                'description' => 'Parcourez la galerie de :count bannières Minecraft conçues sur mesure. Vous pouvez utiliser une bannière comme cape pour rendre votre skin Minecraft plus unique, ou utilisez une bannière comme drapeau pour décorer votre monde.',
            ],
            'add_design' => 'Add your design',
            'sort' => 'Sort:',
            'sort_newest' => 'Newest',
            'sort_oldest' => 'Oldest',
            'sort_favorites' => 'Most Favorites',
            'sort_views' => 'Most Views',
            'sort_last_week' => 'Last Week',
            'sort_last_30d' => 'Last 30 Days',
            'clear_filters' => 'Clear filters',
            'no_banners' => 'No banners yet',
            'no_banners_message' => 'Be the first to publish a banner design!',
            'create_banner' => 'Create a banner',
        ],
        'publish' => [
            'title' => 'Publish banner',
            'title_label' => 'Title',
            'description_label' => 'Description',
            'tags_label' => 'Tags',
            'tags_max_reached' => 'Maximum 5 tags reached',
            'tags_add_placeholder' => 'Add a tag',
            'tags_help' => 'Press enter, tab, or comma to add a tag.',
            'tags_max_error' => 'You can add a maximum of 5 tags.',
            'generate_banner_error' => 'Please generate a banner before publishing.',
            'invalid_code_format' => 'Invalid banner code format.',
            'invalid_base_color' => 'Invalid base color. Must be between 0 and 15.',
            'invalid_patterns_format' => 'Invalid patterns format.',
            'invalid_pattern_structure' => 'Invalid pattern structure.',
            'invalid_pattern_color' => 'Invalid pattern color. Must be between 0 and 15.',
        ],
        'edit' => [
            'title' => 'Edit banner',
            'title_label' => 'Title',
            'description_label' => 'Description',
            'tags_label' => 'Tags',
            'tags_max_reached' => 'Maximum 5 tags reached',
            'tags_add_placeholder' => 'Add a tag',
            'tags_help' => 'Press enter, tab, or comma to add a tag.',
            'tags_max_error' => 'You can add a maximum of 5 tags.',
            'save_changes' => 'Save changes',
            'cancel' => 'Cancel',
            'edit_details' => 'Edit banner details',
            'delete' => 'Delete banner',
            'delete_confirm' => 'Are you sure you want to delete this banner? This action cannot be undone.',
        ],
        'show' => [
            'edit_design' => 'Edit banner design',
            'banner_give_command' => 'Banner give command',
            'setblock_command' => 'Setblock command',
            'shield_give_command' => 'Shield give command',
        ],
        'already_exists' => 'This banner already exists in the gallery.',
    ],
    'search' => [
        'meta' => [
            'title' => 'Résultats de recherche : :search',
        ],
        'what_are_you_searching_for' => 'What are you searching for?',
        'title' => 'Résultats de recherche',
        'results' => 'Page :current pour :count résultat|Page :current d\'environ :count résultats ',
        'results_count' => ':count result|:count results',
        'time' => '(:time secondes)',
        'username_available' => 'Nom d\'utilisateur disponible*',
        'username_unavailable' => 'Nom d\'utilisateur non disponible',
        'username_status' => 'Statut',
        'username_status_available' => 'Disponible*',
        'username_status_unavailable' => 'Indisponible',
        'username_searches' => 'Recherches',
        'username_searches_count' => ':count / jour',
        'username_available_disclaimer' => '*Sauf si le nom est temporairement ou définitivement banni par Mojang.',
        'no_results' => 'Aucun profil trouvé. Essayez de rechercher avec UUID en modifiant le type de recherche.',
        'no_results_tags' => 'Pas de skins taggés trouvés. Essayez de rechercher d\'autres tags tels que "bleu", "fille", "renard", etc...',
        'again' => 'Rechercher de nouveau',
        'sorry' => 'Désoléééééé...',
        'view_profile' => 'Afficher le profil',
        'view_all' => 'View all',
        'filters' => 'Filters',
        'more_results' => 'more results',
        'more_results_fallback' => 'more results',
        'close' => 'Close',
        'clear_filters' => 'Clear all',
        'profiles' => 'Profiles',
        'verified_only' => 'Verified only',
        'verification' => 'Verification',
        'all' => 'All',
        'verified' => 'Verified',
        'not_verified' => 'Not verified',
        'country' => 'Country',
        'country_placeholder' => 'e.g. US, UK',
        'no_types_found' => 'No project types found for this search',
        'no_categories_found' => 'No categories found for this search',
        'featured' => 'Featured',
        'yes' => 'Yes',
        'no' => 'No',
        'skins' => 'Skins',
        'tags' => 'Tags',
        'no_tags_found' => 'No tags found for this search',
        'min_profiles' => 'Min profiles using',
        'try_different' => 'Try a different search term',
        'skins_no_results' => 'No skins found',
        'empty_state' => [
            'title' => 'No matches this time',
            'message' => "We didn't find any results for this search. Try adjusting your keywords or browsing instead.",
        ],
    ],
    'collection' => [
        'title' => 'Collection de skin Minecraft',
        'subtitle' => 'Parcourez notre collection de skins Minecraft.',
        'filters' => 'Filtres',
        'title_trending' => 'Tendance',
        'title_all' => 'Toutes les skins Minecraft',
        'skin_tags' => 'Skins taggés',
        'filters_skin_type' => 'Type de peau',
        'filter_skin_type_steve' => 'Type de Steve',
        'filter_skin_type_alex' => 'Type d\'Alex',
        'cancel' => 'Abandonner',
        'apply' => 'Appliquer',
        'username_minecraft_skin' => 'Thème Minecraft de :username',
        'user_downloads' => '<span class="fw-500">téléchargements</span>téléchargement<span class="fw-500">téléchargements</span>téléchargements',
    ],
    'favourites' => [
        'title' => 'Favoris',
        'subtitle' => 'Voir et gérer les skins que vous avez enregistrés plus tard dans votre liste de favoris',
        'sort' => 'Trier par',
        'toast' => [
            'added' => 'Ajouté à vos favoris',
            'removed' => 'Supprimé de vos favoris',
        ],
        'skins' => [
            'button' => 'Skins',
            'empty_headline' => 'Aucun skins favoris pour le moment',
            'empty_subtitle' => 'Vous n\'avez pas encore de skins enregistrés dans votre liste de favoris. Visitez la page du serveur et découvrez votre prochain skin favori !',
            'empty_browse' => 'Parcourir les skins',
            'meta' => [
                'title' => 'Mes skins favoris',
                'description' => 'Mes skins favoris Minecraft',
            ],
        ],
        'servers' => [
            'button' => 'Serveurs',
            'empty_headline' => 'Aucun serveur favoris pour le moment',
            'empty_subtitle' => 'Vous n\'avez pas encore de serveurs enregistrés dans votre liste de favoris. Visitez la page du serveur et découvrez votre prochain serveur favori !',
            'empty_browse' => 'Parcourir les serveurs',
            'meta' => [
                'title' => 'Mes serveurs favoris',
                'description' => 'Mes serveurs Minecraft favoris',
            ],
        ],

    ],
    'cape' => [
        'editor' => [
            'title' => 'Éditeur de cape Minecraft',
            'subtitle' => 'Utilisez l\'éditeur de cape Minecraft pour créer votre propre cape !',
            'meta' => [
                'title' => 'Éditeur de cape Minecraft',
                'description' => 'Utilisez l\'éditeur de cape Minecraft pour créer votre propre cape !',
            ],
        ],
        'list' => [
            'title' => 'Captures Minecraft',
            'subtitle' => 'Captures officielles de Minecraft',
            'meta' => [
                'title' => 'Liste des Capes Minecraft',
                'description' => 'Liste de capes Minecraft : Voir toutes les capes officielles, Minecon, Capes personnelles, spéciales',
            ],
        ],
        'detail' => [
            'title' => 'Cape :cape',
            'info' => 'Informations de la cape',
            'profile_list' => 'Profils avec ce cape',
            'profiles' => ':profiles profile|:profiles profiles',
            'meta' => [
                'title' => 'Liste des Capes Minecraft',
                'description' => 'Liste des capsules Minecraft : Voir tous les caps officiels de Minecraft, y compris Mojang, Minecon, Capes personnels, Speical et vanité',
            ],
        ],
        'list-custom' => [
            'title' => 'Capes Minecraft personnalisé',
            'description' => 'Parcourez et regardez les capes personnalisées qui ont été créés et utilisés par les membres de SkinMC.',
        ],
    ],
    'servers' => [
        'title' => 'Serveurs Minecraft',
        'subtitle' => 'Parcourir et explorer les serveurs minecraft',
        'all' => 'Tous les serveurs',
        'manage_your_servers' => 'Gérez vos serveurs',
        'add_new_server' => 'Ajouter un nouveau serveur',
        'filters' => [
            'trending' => 'Tendance',
            'updated' => 'Mis à jour',
            'new' => 'Nouveau',
            'most_viewed' => 'Les plus consultés',
            'top_voted' => 'Meilleurs votants',
            'sorting' => 'Trier',
            'sort_by_latest' => 'Trier par plus récent',
            'sort_by_oldest' => 'Trier par plus ancien',
            'categories' => 'Catégories',
            'server_location' => 'Localisation du serveur',
            'show_results' => 'Afficher les résultats',
            'show_more' => 'Montrer plus',
            'show_less' => 'Afficher moins',
            'clear_filters' => 'Annuler les filtres',
            'reviews' => 'Avis',
            'sort_by_highest_rating' => 'Trier par note la plus élevée',
            'sort_by_lowest_rating' => 'Trier par note la plus basse',
            'bedrock_and_java_support' => 'Support Bedrock et Java',
        ],
        'review-count' => ':count Avis|:count Avis',
        'meta' => [
            'title' => 'Liste des serveurs Minecraft',
            'description' => 'Naviguez et explorez la liste des serveurs Minecraft pour trouver le meilleur serveur Minecraft ! Filtrez par le dernier, le plus populaire et bien plus encore',
        ],
        'reviews' => [
            'meta' => [
                'title' => 'Écrire un avis',
            ],
            'editing' => 'Vous modifiez votre avis du :date. Voulez-vous supprimer votre avis à la place ?',
            'welcome' => 'Bonjour :username. Comment a été votre expérience globale avec :servername?',
            'subtitle' => 'Laissez un score global de votre expérience passée avec le serveur.',
            'scale' => [
                'great' => 'Très bon',
                'good' => 'Bon',
                'okay' => 'D\'accord',
                'meh' => 'Bof',
                'bad' => 'Mauvais',
            ],
            'rate-experience' => 'Ensuite, évaluez votre expérience dans ces domaines',
            'overall' => 'Global',
            'server-team' => 'Équipe du serveur',
            'community' => 'Communauté',
            'experience' => 'Expérience',
            'availablility' => 'Temps de disponibilité et disponibilité',
            'shop' => 'Boutique',
            'write-review-title' => 'Écrire un avis',
            'write-review-subtitle' => 'Laissez quelques notes, vous pouvez mettre en valeur ce que vous avez apprécié, ce qui a rendu votre expérience spéciale, ou proposer quelques suggestions.',
            'write-review-helper' => 'Écrivez un avis sur le serveur pour partager votre expérience avec de nouveaux joueurs et aider les propriétaires du serveur avec des commentaires.',
            'write-review-tips' => 'Voici quelques astuces',
            'submit-title' => 'Prêt à soumettre votre serveur ?',
            'submit-subtitle' => 'Vous y êtes presque !',
            'submit-review' => 'Soumettre mon avis',
            'back' => 'Retour',
            'continue' => 'Continuer',
            'delete-title' => 'Êtes-vous sûr de vouloir supprimer votre avis ?',
            'tos-checkbox-part-1' => '',
            'tos-checkbox-part-2' => 'revoir les lignes directrices.',
            'tos-checkbox-part-3' => 'Votre avis sera publié après soumission, mais peut être revu.',
        ],
        'slots' => 'Emplacements',
        'empty-helper' => 'You can try to do another search.',
        'empty' => 'Hmm c\'est toujours vide ici.',
        'verified' => 'Vérifié',
        'review_translate_show_original' => 'Afficher l’original',
        'review_translate' => 'Traduire la critique',
        'description_translate' => 'Traduire la description',
        'create' => [
            'welcome' => 'Bienvenue',
            'basics' => 'Basiques',
            'categories' => 'Catégories',
            'social_links' => 'Liens sociaux',
            'trailer_video' => 'Bande-annonce',
            'images' => 'Images',
            'images_description' => 'Vous pouvez ensuite télécharger des photos pour montrer ce que votre serveur offre.',
            'submit' => 'Envoyer',
            'lets_get_your_server_added' => 'Ajoutons votre serveur.',
            'basics-subtitle' => 'Faites savoir aux gens de quoi consiste votre serveur.',
            'description' => 'Description',
            'description_tips' => 'Voici quelques astuces',
            'description_hint' => 'Écrivez une bonne description pour votre serveur afin d\'attirer de nouveaux joueurs.',
            'categories-subtitle' => 'Choisissez des catégories pour votre serveur',
            'missing-category' => 'Une catégorie est manquante ?',
            'social_links_description' => 'Où les joueurs peuvent-ils se connecter à votre serveur sur les réseaux sociaux ?',
            'trailer_video_description' => 'Présentez votre serveur avec une vidéo YouTube.',
            'trailer_video_hint' => 'Coller l\'URL ou l\'ID de la vidéo :',
            'ready_to_submit_your_server' => 'Prêt à soumettre votre serveur ?',
            'review-hint' => 'Après la soumission, l\'équipe examinera soigneusement votre demande de liste de serveurs. Ensuite, après décision, votre serveur sera publié, ou faites les modifications demandées avant de passer en ligne.',
            'terms' => [
                'part-1' => 'En soumettant ce formulaire, vous êtes autorisé à accepter les conditions d\'utilisation, la politique de confidentialité et les directives communautaires de SkinMC. Vous confirmez également que toutes les informations ci-dessus sont exactes, vous avez correctement suivi les',
                'part-2' => 'pré-requis du serveur pour la configuration',
                'part-3' => ', et que le serveur Minecraft est propriétaire et géré par l\'entité que vous représentez.',
            ],
            'submit-application' => 'Soumettre une demande',
            'video-id-helper' => [
                'part-1' => 'L\'identifiant de la vidéo est la chaîne de chiffres et de lettres après',
                'part-2' => 'Par exemple si votre url vidéo est',
                'part-3' => ', alors votre identifiant vidéo serait',
            ],
            'welcome_description' => 'Dans cette étape, nous allons commencer à ajouter votre serveur. Parlez-nous un peu à ce sujet, écrivez une description, et à l\'étape suivante vous pouvez télécharger quelques images.',
        ],
        'copy_server_ip' => 'Copier l\'IP du serveur',
        'all_minecraft_servers' => 'Tous les serveurs Minecraft',
        'promo' => [
            'title' => 'Hébergez-vous un serveur Minecraft ?',
            'ready_to_list_your_server' => 'Prêt à soumettre votre serveur ?',
            'everything_you_need' => 'Tout ce dont vous avez besoin pour agrandir votre serveur',
            'list_your_server' => 'Lister votre serveur',
            'list_your_server_description' => 'Créez une liste pour votre serveur, ajoutez des photos, des réseaux sociaux et bien plus.',
            'find_players' => 'Trouver des joueurs',
            'find_players_description' => 'Trouvez et atteignez de nouveaux joueurs pour rejoindre votre serveur et faire grandir votre communauté.',
            'get_reviews' => 'Obtenez des avis',
            'get_reviews_description' => 'Demandez à votre communauté d\'évaluer votre serveur et de les récompenser en jeu.',
            'why_list_on_skinmc' => 'Pourquoi devriez-vous lister votre serveur sur SkinMC',
            'others' => 'Autres',
            'quality_check_and_confirmation' => 'Vérification de la qualité et confirmation',
            'quality_check_description' => 'Notre équipe passe en revue chaque serveur pour assurer la qualité.',
            'verified_players' => 'Avis des joueurs Minecraft vérifiés',
            'verified_players_description' => 'Collectez des commentaires authentiques des joueurs à partir de comptes légitimes avec l\'intégration Votifier.',
            'international' => 'International',
            'international_description' => 'Avec les fonctionnalités de traduction, votre annonce est disponible pour plus de joueurs.',
            'server_listing_page' => 'Page de liste des serveurs puissants',
            'server_listing_page_description' => 'Ajoutez des photos, des textes de description, des vidéos youtube, et soulignez pourquoi les lecteurs devraient rejoindre votre serveur.',
            'social_connections' => 'Connexions aux réseaux sociaux',
            'social_connections_description' => 'Connectez vos comptes sociaux serveurs et montrez aux nouveaux joueurs où ils peuvent vous trouver.',
            'verified_badge' => 'Badge de vérification',
            'verified_badge_description' => 'Les serveurs authentiques peuvent demander un badge de vérification.',
            'owner_profile' => 'Profil du propriétaire',
            'owner_profile_description' => 'Ajoutez une touche personnelle, en complétant votre profil personnalisé.',
            'categories' => 'Catégories',
            'categories_description' => 'Différentes catégories pour faciliter la recherche de votre serveur.',
            'vote' => 'Voter',
            'vote_description' => 'Demandez aux utilisateurs de voter pour votre serveur.',
            'fair_listings' => 'Listes équitables',
            'fair_listings_description' => 'Les listes de serveurs ne peuvent pas être augmentées artificiellement dans les résultats sur SkinMC.',
            'support' => 'Assistance 24h',
            'support_description' => 'Vous avez besoin d\'aide ou avez des questions ? Vous pouvez toujours contacter et recevoir une réponse rapide.',
            'custom_features' => 'Fonctionnalités personnalisées',
            'custom_features_description' => 'Il manque une fonctionnalité pour votre serveur? Ouvrez un ticket, et nous allons l\'implémenter.',
            'faq' => [
                'title' => 'Réponses à vos questions',
                'suited-question' => 'Mon serveur Minecraft est-il adapté au SkinMC ?',
                'suited-answer' => 'Les joueurs Minecraft sur SkinMC aiment découvrir de nouvelles expériences, du contenu et s\'impliquer avec les communautés. Sur la plate-forme, vous trouverez une grande variété de serveurs Minecraft différents, uniques et amusants. Depuis un grand réseau jusqu\'à un petit serveur de survie, il peut faire quelqu\'un de jour!',
                'get-started-question' => 'Comment puis-je commencer ?',
                'get-started-answer' => 'Ajouter votre serveur Minecraft à la liste des serveurs SkinMC est très facile ! Vous devrez d\'abord créer un compte, si vous ne l\'avez pas déjà fait, puis suivre le guide d\'installation pour que votre serveur soit répertorié. Ajoutez quelques photos et une bonne description, et votre serveur sera publié en un rien de temps !',
                'players-question' => 'Comment puis-je obtenir plus de joueurs sur mon serveur Minecraft ?',
                'players-answer' => 'Construire une communauté est la partie la plus cruciale d\'un serveur Minecraft durable. Utilisez la liste de serveurs Minecraft sur SkinMC pour trouver un nouveau public et continuer à construire votre communauté. Demandez à vos joueurs de recommander votre serveur ou de partager votre annonce sur les plateformes de réseaux sociaux. La collecte de bons avis peut également jouer un rôle important pour une grande présence de serveur qui attire de nouveaux joueurs.',
                'more-question' => 'J\'ai plus de questions. Où puis-je obtenir de l\'aide ?',
                'more-answer' => 'Vous pouvez contacter SkinMC à tout moment, 24 heures, en utilisant soit le bouton d\'aide, le service d\'assistance, ou en rejoignant le serveur Discord.',
            ],
            'ready_to_list_description' => 'Ajoutez votre serveur Minecraft à la liste des serveurs SkinMC en quelques minutes. Si vous avez besoin d\'aide, vous pouvez vous adresser 24 heures sur 24 et recevoir des réponses rapidement.',
        ],
        'manage' => [
            'index' => [
                'welcome' => 'Bon retour, :username',
                'your_servers' => 'Vos serveurs',
                'reviews_today' => 'Avis du jour',
                'no_reviews_today' => 'Aucun avis aujourd\'hui',
                'no_reviews_text' => 'Vos serveurs n\'ont reçu aucun avis aujourd\'hui. Pourquoi ne pas demander à vos joueurs d\'en laisser un ?',
                'tips' => [
                    'title' => 'Astuces',
                    'description-title' => 'Écrire une bonne description du serveur',
                    'description-body' => 'Conseils utiles et conseils pour écrire une excellente description de serveur.',
                    'images-title' => 'Ajout d\'images du serveur',
                    'images-body' => 'Faites ressortir votre serveurs de la liste avec des images géniales.',
                ],
            ],
            'listings' => [
                'title' => 'Vos serveurs Minecraft (:count)',
            ],
            'insights' => [
                'title' => 'Analyses',
            ],
            'edit_server' => 'Modifier le serveur',
            'listing' => 'Liste',
            'to_do' => 'À faire',
            'last_update' => 'Dernière mise à jour',
            'add_more_photos_to_publish' => 'Ajouter plus de photos pour publier',
            'looks_empty_here' => 'Cela semble vide ici.',
            'get_started_by_adding_a_new_server' => 'Commencez par ajouter un nouveau serveur ?',
        ],
        'status' => [
            'approved' => 'Approuvé',
            'pending_approval' => 'En attente de validation',
            'published' => 'Publié',
            'in_review' => 'En révision',
        ],
    ],
    'editor' => [
        'import' => [
            'title' => 'Importer un Skin',
            'import_by_username' => 'Importer par nom d\'utilisateur',
            'import_button' => 'Importer',
            'drag' => 'Glissez et déposez un skin ici, ou cliquez',
            'click' => 'Sélectionnez une image',
        ],
        'download' => [
            'error' => [
                'no-data' => 'Aucune donnée de skin fournie. Veuillez réessayer.',
                'invalid-format' => 'Le format des données du skin est invalide. Veuillez réessayer.',
                'invalid-data' => 'Les données du skin sont corrompues. Veuillez réessayer.',
                'generic' => 'Une erreur est survenue lors du téléchargement de votre skin. Veuillez réessayer.',
            ],
        ],
        'draw' => 'Dessiner',
        'eyedropper' => 'Pipette',
        'fill' => 'Remplir',
        'move' => 'Déplacer',
        'decrease_brightness' => 'Diminuer la luminosité',
        'increase_brightness' => '',
        'erase' => 'Effacer',
        'undo' => 'Revenir en arrière (CTRL+Z)',
        'redo' => 'Avancer (CTRL+Y)',
        'default_view' => 'Vue par défaut',
        'zoom_in' => 'Zoomer (CTRL +)',
        'zoom_out' => 'Dézoomer (CTRL -)',
        'saved' => 'Dernière sauvegarde à l\'instant',
        'saving' => 'Enregistrement automatique...',
        'save_error' => 'Une erreur s\'est produite',
        'new_skin' => 'Nouveau skin',
        'previous_skins' => 'Skins précédents',
        'backed_up_title' => 'Skins enregistrés automatiquement',
        'backed_up_info' => 'Sauvegarde temporaire sur votre stockage local.',
        'backed_up_empty_title' => 'Cela semble vide ici',
        'backed_up_empty_info' => 'Une fois que vous commencez à éditer des skins, vous verrez vos 32 derniers skins modifiés ici.',
        'backed_up_skins_count' => 'de 32 sauvegardes de skin utilisées',
        'backed_up_skins_count_info' => 'Une fois 32 skins atteints, une apparence plus ancienne sera remplacée par une nouvelle.',
        'layers' => 'Couches',
        'body' => [
            'title' => 'Corps',
            'overlay' => 'Overlay',
            'head' => 'Tête',
            'torso' => 'Torse',
            'l_arm' => 'Bras gauche',
            'r_arm' => 'Bras droit',
            'l_leg' => 'jambe gauche',
            'r_leg' => 'jambe droite',
        ],
        'model' => 'Modélisation',
        'steve' => 'Steve',
        'alex' => 'Alex',
        'stance' => [
            'title' => 'Position',
            'default' => 'Par défaut',
            'walk' => 'Marcher',
            'run' => 'Exécuter',
            'hug' => 'T-pose',
            'fly' => 'Vol',
        ],
        'fullscreen' => 'Plein écran',
        'fullscreen_exit' => 'Quitter le plein écran',
        'grid' => 'Grille',
        'show_grid' => 'Afficher la grille',
        'download' => [
            'title' => 'Enregistrer et télécharger',
            'subtitle' => 'Compte SkinMC',
            'description' => 'Voulez-vous créer un compte SkinMC gratuit pour enregistrer votre skin et ceux futurs dans le cloud ?',
            'start_description' => 'Commencez à télécharger directement sans enregistrer dans le cloud',
            'start' => 'Télécharger le thème',
        ],
        'help' => [
            'title' => 'Éditeur de Skin Minecraft',
            'about' => 'Créez et modifiez facilement votre skin Minecraft personnalisé avec l\'éditeur SkinMC. Vous pouvez choisir entre le modèle de Steve et Alex , importer des skins à partir d\'un fichier ou d\'un nom d\'utilisateur, et créer votre propre skin Minecraft.',
            'draw' => 'Dessiner à l\'aide de l\'outil stylet. Sélectionnez une couleur à partir de l\'échantillon à utiliser avec elle.',
            'eyedropper' => 'Utilisez la pipette pour sélectionner une couleur de votre skin et l\'ajouter à votre palette actuelle.',
            'fill' => 'Remplissez des zones entières de votre skin à l\'aide de l\'outil de remplissage. Sélectionnez une couleur avant d\'utiliser le remplissage.',
            'move' => 'Faites glisser et déplacez la toile de l\'éditeur de peau à l\'aide de l\'outil de déplacement.',
            'decrease_brightness' => 'Diminuer la luminosité de la couleur actuellement active.',
            'increase_brightness' => 'Augmente la luminosité de la couleur actuellement active.',
            'erase' => 'Effacer les pixels dessinés sur le calque secondaire de superposition.',
            'minimap' => 'Minimap',
            'minimap_info' => 'The minimap can show you the skin texture in a flat view while in 3D mode. In 2D mode the minimap switches to a 3D preview of your skin. You can zoom in and out.',
            'autosave' => 'Autosave',
            'autosave_info' => 'The autosave feature saves your skin automatically every 30 seconds. You can access the autosaved skins in the editor by pressing the folder icon, and choosing "Previous skins".',
            '2d_editor' => '2D and 3D editor',
            '2d_editor_info' => 'Toggle between editing your Minecraft skin in 2D or 3D mode.',
        ],
    ],
    'account' => [
        'level' => 'Niveau',
        'level_history' => 'Historique du niveau',
        'xp' => 'XP',
        'my_xp' => 'Mon XP',
        'xp_to_next_level' => ':xp XP jusqu\'au niveau suivant',
        'xp_info' => 'Qu\'est-ce que l\'XP ?',
        'xp_info_tooltip' => 'XP est gagné pour diverses activités telles que l\'ajout de balises à des skins, l\'invitation à des amis, les commentaires et bien plus encore. Avec chaque XP gagné, vous pouvez monter de niveau et débloquer des choses cool !',
        'settings' => [
            'title' => 'Compte client',
            'show_profile' => 'Aller au profil',
            'friends' => 'Amis',
            'friends_detail' => 'Restez connecté en utilisant votre liste d\'amis sur SkinMC.',
            'security' => 'Sécurité',
            'security_detail' => 'Mettez à jour votre mot de passe de connexion et protégez votre compte',
            'social' => 'Comptes des réseaux sociaux',
            'social_detail' => 'Personnalisez votre profil en ajoutant votre réseau social',
            'link' => 'Lier le compte Minecraft',
            'link_detail' => 'Liez votre compte Minecraft et revendiquez votre profil.',
            'logout' => 'Voulez-vous vous déconnecter de votre compte SkinMC ?',
            'automatic_backups' => 'Sauvegardes automatiques de skin',
            'automatic_backups_info' => 'En tant que membre de SkinMC plus vos skins sont sauvegardés quotidiennement.',
        ],
        'capes' => [
            'title' => 'Cape Minecraft SkinMC',
            'description' => 'Portez n\'importe quelle cape que vous souhaitez en jeu avec SkinMC Capes gratuitement.',
            'drop' => 'Glissez et déposez une cape ici',
            'drop-hint' => 'Dimensions 64x32px',
            'select' => 'Sélectionnez une image',
            'upload-cape' => 'Charger et utiliser cape',
            'save-and-use' => 'Enregistrer & utiliser',
            'uploaded-cape' => 'Cape téléchargée',
            'no-cape' => 'Pas de cape',
            'remove-cape' => 'Retirer le vote',
            'download' => 'Téléchargez le mod SkinMC pour voir vos caps et ceux des autres joueurs en jeu.',
            'learn-more' => 'En savoir plus',
            'link-account' => 'Veuillez lier votre compte Minecraft pour télécharger un cape.',
            'updated' => 'Votre cape a été mise à jour !',
            'removed' => 'Votre cape a été retirée.',
            'active' => 'Votre cape est activé !',
        ],
        'favourite' => 'Favori',
        'remove_favourite' => 'Retirer des favoris',
        'added_to_favourites' => 'Ajouté aux favoris',
        'removed_from_favourites' => 'Retirer des favoris',
        'welcome' => 'Nous sommes heureux de vous voir !',
        'view-profile' => 'Voir mon profil',
        'security' => [
            'title' => 'Sécurité',
            'email' => 'Adresse e-mail',
            'email-title' => 'Mettez à jour votre adresse e-mail',
            'save' => 'Enregistrer',
            'password' => 'Mot de passe',
            'password-title' => 'Changez votre mot de passe à tout moment.',
            'social-provider' => 'Pour mettre à jour vos informations de compte, comme votre mot de passe, veuillez vous rendre sur votre fournisseur de connexion :',
            'social-provider-email' => 'Votre adresse e-mail associée avec votre fournisseur de connexion',
            'social-provider-connected' => 'Fournisseurs de connexion actuellement connectés',
            'current-password' => 'Mot de passe actuel ',
            'forgot' => 'Mot de passe oublié ?',
            'edit' => 'Editer',
            'delete' => 'Supprimer mon compte',
            'account-deletion' => 'Supprimer votre compte SkinMC.',
            'delete-info' => 'Merci de confirmer pour continuer',
            'delete-confirmation' => 'La suppression de votre compte est irréversible. Toutes vos informations personnelles et contenus tels que les publications, les favoris, les capsules téléchargées, les personnalisations, etc. sera supprimé et ne pourra pas être récupéré.',
            'delete-confirmation-info' => 'Entrez votre mot de passe pour continuer',
            'delete-confirmation-info-social' => 'Type "delete" to confirm account deletion',
            'type-delete' => 'Type "delete" to confirm',
            'type-delete-label' => 'Type "delete" to confirm',
            'yes-confirm-delete' => 'Oui, confirmer la suppression',
            'account-successfully-deleted' => 'Votre compte et vos données ont été supprimés avec succès.',
        ],
        'social' => [
            'title' => 'Comptes sociaux',
            'edit' => 'Editer',
            'save' => 'Enregistrer',
            'link-account' => 'Liez votre compte Minecraft à SkinMC pour afficher vos liens sociaux sur votre profil.',
            'finish-setup' => 'Terminer la configuration',
            'connect-account' => 'Connectez vos comptes',
            'connect-description' => 'Choisissez les comptes que vous souhaitez connecter et déverrouiller les intégrations SkinMC spéciales.',
            'empty' => 'Aucun compte ajouté',
            'empty-description' => 'Vos comptes de réseaux sociaux apparaîtront ici et sur votre profil public. Une fois ajoutés, ils ajouteront plus de personnalisation à votre page et activeront les intégrations.',
            'connect' => 'Connexion',
            'username' => 'Nom d\'utilisateur',
            'spotify' => 'Ajoutez votre nom d\'utilisateur Spotify pour afficher vos informations Spotify sur votre profil.',
            'discord' => 'Entrez votre nom d\'utilisateur et votre numéro Discord pour afficher vos informations Discord sur votre profil SkinMC.',
            'youtube' => 'Ajoutez votre chaîne YouTube à SkinMC qui affichera votre chaîne YouTube sur votre profil.',
            'youtube-format' => 'Utilisez le format suivant en fonction de votre lien de chaîne :',
            'twitter' => 'Entrez votre nom d\'utilisateur X (anciennement Twitter) pour l\'afficher sur votre profil.',
            'bluesky' => 'Entrez votre identifiant Bluesky, par exemple username.bsky.social pour afficher votre profil Bluesky sur votre profil.',
            'twitch' => 'Entrez votre nom d\'utilisateur Twitch pour afficher votre chaîne Twitch sur votre profil.',
            'reddit' => 'Entrez votre nom d\'utilisateur Reddit pour afficher votre profil Reddit sur votre profil.',
            'github' => 'Entrez votre nom d\'utilisateur Reddit pour afficher votre profil Reddit sur votre profil.',
            'telegram' => 'Entrez votre nom d\'utilisateur Telegram pour afficher votre lien Telegram sur votre profil.',
            'tiktok' => 'Entrez votre nom d\'utilisateur TikTok pour afficher votre profil TikTok sur votre profil.',
            'snapchat' => 'Entrez votre nom d\'utilisateur Snapchat pour afficher votre profil Snapchat sur votre profil.',
            'instagram' => 'Entrez votre nom d\'utilisateur Instagram pour afficher votre profil Instagram sur votre profil.',
            'facebook' => 'Entrez votre nom d\'utilisateur Facebook pour afficher votre profil Facebook sur votre profil.',
            'includes_skinmc_plus_benefits' => 'Inclut les avantages de SkinMC plus',
        ],
        'recover' => [
            'title' => 'Récupérer votre compte',
            'subtitle' => 'Veuillez entrer votre nouveau mot de passe et le confirmer pour terminer la récupération de votre compte.',
            'new_password' => 'Nouveau mot de passe',
            'repeat_new_password' => 'Répéter le nouveau mot de passe',
            'submit' => 'Récupérer le compte',
        ],
        'customise' => [
            'title' => 'Personnalisez votre profil',
            'description' => 'Ajoutez vos médias sociaux, choisissez un emoji, définissez votre position et plus encore',
            'information' => 'Informations',
            'preview' => 'Aperçu',
            'location' => [
                'title' => 'Lieu',
                'description' => 'Choisissez l\'emplacement que vous souhaitez ajouter à votre profil.',
            ],
            'biography' => [
                'title' => 'À propos de moi',
                'description' => 'Écrivez une biographie pour votre profil.',
            ],
            'status' => 'Status',
            'status-toggle' => 'Afficher mon statut en ligne',
            'emoji' => 'Émoji',
            'name-history-toggle' => 'Rendre l’historique du nom d’utilisateur privé',
            'name-history-info' => 'L\'historique de votre nom d\'utilisateur Minecraft est actuellement',
            'name-history-toggle-on' => 'privé',
            'name-history-toggle-off' => 'publique',
            'theme' => 'Thème de profil',
            'theme-primary' => 'Principale',
            'theme-secondary' => 'Secondaire',
            'appearance' => 'Apparence',
        ],
        'link' => [
            'manage' => 'Gérer le compte Minecraft lié',
            'description' => 'Voir et gérer votre compte Minecraft lié',
            'title' => 'Compte Minecraft lié',
            'current' => 'Compte Minecraft actuellement lié.',
            'status' => 'Vous avez maintenant un accès complet à toutes les fonctionnalités de SkinMC !',
            'linked' => 'Lié',
            'disconnect' => 'Se déconnecter',
            'disconnect-title' => 'Déconnecter le compte Minecraft',
            'disconnect-info' => 'Êtes-vous sûr de vouloir déconnecter votre compte Minecraft ?',
            'disconnect-features' => 'Vous perdrez l\'accès aux commentaires, à la personnalisation et aux autres fonctionnalités qui nécessitent un compte Minecraft lié. Pour les utiliser à nouveau, vous devrez lier un compte Minecraft.',
            'disconnect-following' => 'Déconnecter votre compte Minecraft supprimera définitivement tous vos profils suivis.',
            'disconnect-posts' => 'Vos messages de flux créés et aimés seront supprimés.',
            'can-not-undo' => 'Cela ne peut pas être annulé.',
            'are-you-sure' => 'Êtes-vous sûr ?',
            'confirm' => 'Oui, confirmer la déconnexion',
            'cancel' => 'Non, annuler',
            'success' => 'Votre compte a été déconnecté avec succès !',
        ],
        'finish-setup' => [
            'title' => 'Terminer la configuration du compte',
            'description' => 'Terminez la configuration de votre compte et obtenez un accès complet à toutes les fonctionnalités en liant votre compte Minecraft à SkinMC.',
            'link' => 'Lier le compte Minecraft',
            'get-started' => 'C\'est parti',
            'skip' => 'Passer',
            'claim' => 'Réclamer votre profil',
            'customise' => 'Personnalisez votre page',
            'social' => 'Ajouter des liens sociaux',
            'comment' => 'Accès au système de commentaires',
            'direct_message' => 'Envoyer des messages directs',
            'feed' => 'Publier les mises à jour de l\'état du flux',
            'follow' => 'Suivre vos amis',
            'badge' => 'Badge affiché sur votre profil',
            'cape' => 'Capes Minecraft personnalisé',
            'backup' => 'Sauvegarde automatique du skin',
            'more' => 'Et plus...',
        ],
        'skins' => [
            'title' => 'Gérer les skins',
            'toggle' => 'Activité la visibilité du skin',
        ],
        'invite' => [
            'title' => 'Mes invitations',
            'headline' => 'Invitez vos amis',
            'info' => 'Créez un code d\'invitation à partager avec votre ami. Une fois qu\'il l\'acceptera, vous gagnerez tous deux de l\'XP supplémentaire !',
            'description' => 'Créez une invitation pour vos amis et vous gagnerez tous deux de l\'XP supplémentaire.',
            'generate' => 'Créer un code d\'invitation',
            'empty' => 'Vous n\'avez pas encore créé d\'invitations.',
            'code' => 'Code',
            'expiry' => 'Chaque code fonctionne une fois.',
            'status' => [
                'title' => 'Status',
                'pending' => 'En attente',
                'accepted' => 'Accepté',
            ],
            'add_invite' => [
                'button' => 'Vous avez une invitation ?',
                'title' => 'Ajouter un code d\'invitation',
                'redeem' => 'Utiliser l\'invitation',
            ],
            'share' => 'Envoyez à votre ami un lien d\'invitation',
        ],
        'emoji' => [
            'title' => 'SkinMC Emoji',
            'introducing' => 'Introduction',
            'info' => 'Personnalisez votre profil avec des emoji. Débloquez plus au fur et à mesure que vous passez au niveau supérieur.',
            'unlocked_at' => 'Déverrouillé au niveau :level',
            'unlocks_at' => 'Atteignez le niveau :level pour déverrouiller',
            'turn_off' => 'Afficher l\'émoji',
        ],
    ],
    'notifications' => [
        'title' => 'Notifications',
        'view_all' => 'Tout voir',
        'view_all_notifications' => 'Voir toutes les notifications',
        'image' => 'Photo de notification',
        'archived' => 'Archivé',
        'inbox' => 'Boîte de réception',
        'empty' => [
            'title' => 'Vous êtes à jour !',
            'text' => 'De nouvelles notifications apparaîtront ici.',
            'text-archived' => 'Les notifications archivées apparaîtront ici.',
        ],
        'action' => [
            'archive' => 'Déplacer vers les archives',
            'unarchive' => 'Désarchiver',
            'open' => 'Appuyez pour ouvrir',
        ],
        'toast' => [
            'archive' => 'Notification déplacée vers les archives',
            'unarchive' => 'Notification déplacée vers la boîte de réception',
            'undo' => 'Annuler',
        ],
    ],
    'error' => [
        'offline' => [
            'title' => 'Pas d’Internet',
            'subtitle' => 'Votre connexion internet a été déconnectée. Veuillez vérifier votre connexion et recharger la page pour réessayer.',
            'try_again' => 'Réessayez',
        ],
        '404' => [
            'title' => '404 — Page introuvable.',
            'subtitle' => 'Hm, on dirait que rien n\'a été trouvé à cet endroit. Essayez peut-être de revenir en arrière, ou de commencer une nouvelle recherche ?',
            'try_again' => 'Retour à la page d\'accueil',
        ],
    ],
    'heads' => [
        'list' => [
            'meta' => [
                'title' => 'Base de données des têtes Minecraft',
                'description' => 'Explorez la base de données des têtes de Minecraft pour décorer votre monde, ou générez votre propre commande de don. Voir les têtes officielles, les têtes de joueurs et les têtes personnalisées qui comportent des textures qui ne changent jamais.',
            ],
            'header' => [
                'title' => 'Têtes Minecraft',
                'subtitle' => 'Explorez notre base de données de têtes Minecraft pour décorer votre monde, ou générez votre propre commande de don. Les têtes de joueur montrent le skin actuel porté par un utilisateur et peuvent changer lorsque l\'utilisateur met à jour son skin. Les têtes personnalisées sont liées au fichier de skin Mojang et ne changent jamais. Les têtes personnalisées doivent être appelées en utilisant un bloc de commande car la commande est très longue.',
            ],
            'count' => [
                'heads' => ':heads head|:heads tête',
            ],
            'customheads' => [
                'title' => 'Têtes personnalisées',
                'description' => 'Les têtes personnalisées utilisent le chemin direct vers le fichier de texture sur les serveurs de Mojang, ce qui signifie que les textures ne seront jamais supprimées et que les têtes ne changeront jamais.',
                'version' => 'Minecraft 1.8 ou supérieur',
            ],
            'playerheads' => [
                'title' => 'Têtes du joueur',
                'description' => 'Les têtes de joueur utilisent la texture actuelle du skin d\'un joueur Minecraft. Comme ils sont basés sur le nom d\'utilisateur, quand le joueur change de nom ou de peau, la tête change.',
                'version' => 'Toutes les versions de Minecraft',
            ],
        ],
    ],
    'mod' => [
        'title' => 'SkinMC Mod: Cape customisé gratuitement',
        'headline' => 'Introduction du mod SkinMC pour plus de personnalisation',
        'description' => 'Revenir à la communauté Minecraft, avec un mod gratuit qui permet aux joueurs plus de personnalisation avec des capes personnalisées, disponible et visible pour toute personne utilisant le mod.',
        'download' => 'Télécharger maintenant',
        'download-title' => 'Télécharger le mod',
        'requires' => 'Requis',
        'select-version' => 'Choisissez votre version de Minecraft',
        'get-started' => 'Commencer est simple',
        'step-1' => '1. Obtenir le mod',
        'step-1-detail' => 'Installez Fabric, puis téléchargez le mod pour votre version de jeu et installez-le en plaçant le jar dans le dossier de vos mods.',
        'step-2' => '2. Liez votre compte',
        'step-2-detail' => 'Si vous ne l\'avez pas déjà fait, inscrivez-vous et connectez votre compte Minecraft à SkinMC.',
        'step-3' => '3. Chargez votre cape',
        'step-3-detail' => 'Allez sur votre compte et téléchargez votre cape personnalisée. Elle sera visible dans le jeu.',
        'all-versions' => 'Toutes les versions',
        'latest' => 'Plus récent',
        'logged-in' => 'Chargez votre cape',
        'mirror' => 'Inverser',
        'download-via' => 'Télécharger via :',
        'curseforge' => 'CurseForge',
    ],
    'app' => [
        'title' => 'Application Android SkinMC',
        'headline' => 'Dites bonjour à l\'application Android SkinMC.',
        'play-store-attribution' => 'Google Play et le logo Google Play sont des marques de Google LLC.',
        'features' => 'Fonctionnalités pratiques pour vos déplacements',
        'feature-qr' => 'Scanner de QR Code intégré',
        'feature-qr-detail' => 'Utilisez le scanner QR-Code intégré pour obtenir facilement un skin de votre bureau vers l\'application, ou scannez le QR-Code de votre profil d\'ami.',
        'feature-files' => 'Sauvegarde directement dans les fichiers',
        'feature-files-detail' => 'Avec l\'utilisation du gestionnaire de fichiers Android, l\'application peut facilement enregistrer des skins, rendant plus facile l\'application dans Bedrock Edition.',
        'feature-noads' => 'Pas de publicité',
        'feature-noads-detail' => 'Une interface propre, sans distractions. Profitez d\'une expérience sans publicité sans nuisances envahissantes du Web à l\'application.',
        'feature-experience' => 'Expérience',
        'feature-experience-detail' => 'Profitez de l\'expérience complète SkinMC n\'importe où, avec des fonctionnalités ajoutées. Personnalisez votre profil, ajoutez votre bio, créez un code QR amusant et plus encore !',
        'get-app-headline' => 'Téléchargez l\'application SkinMC',
        'get-app-detail' => 'Votre propre compagnon Minecraft pour votre Android — disponible gratuitement.',
    ],
    'random' => [
        'title' => 'Chargement du skin Minecraft aléatoirement',
        'description' => 'Chargement du skin Minecraft aléatoirement',
        'headline' => 'Veuillez patienter...',
        'redirect' => 'Vous serez automatiquement redirigé. La page ne se chargera pas?',
        'click-here' => 'Cliquez ici',
        'messages' => [
            '1' => 'Chargement du skin Minecraft aléatoirement...',
            '2' => 'Extraction en cours...',
            '3' => 'Creeper, homme cruel...',
            '4' => 'Recherche dans les coffres...',
            '5' => 'Saviez-vous que la peau à venir est complètement aléatoire?',
            '6' => 'Peau aléatoire entrante...',
            '7' => 'Encore un bloc...',
            '8' => 'Tri de l\'inventaire...',
            '9' => 'Fabrication de la pioche en diamant...',
            '10' => 'Recherche d\'Herobrine...',
        ],
    ],
    'feed' => [
        'title' => 'Fil d\'actualités',
        'following' => 'Abonné',
        'sign-up' => 'Inscrivez-vous ou connectez-vous pour rejoindre la conversation.',
        'link-account' => 'Liez votre compte Minecraft pour rejoindre la conversation.',
        'placeholder' => 'Que se passe-t-il?',
        'audience' => 'Audience',
        'audience-title' => 'Qui peut le voir?',
        'everyone' => 'Tout le monde',
        'everyone-info' => 'N\'importe qui sur ou hors SkinMC.',
        'followers' => 'Abonnés',
        'followers-info' => 'Connecté ou des membres qui me suivent.',
        'private' => 'Seulement moi',
        'private-info' => 'Publication privée que je peux voir.',
        'submit' => 'Poster',
        'like' => 'Aimer',
        'comment' => 'Répondre',
        'share' => 'Partager',
        'remaining' => 'Restant',
        'profile' => 'Publier par :username',
        'posts' => 'Toutes les publications',
        'my-posts' => 'Mes publications',
        'view-all' => 'Voir toutes les publications',
        'post' => [
            'meta' => ':username sur SkinMC: :text',
            'title' => 'Publication',
            'created' => 'Mise à jour du statut postée !',
            'confirm-delete' => 'Êtes-vous sûr de vouloir supprimer ce message ? Il ne peut pas être annulé.',
            'delete' => 'Supprimer la publication',
            'deleted' => 'Votre publication a été supprimée.',
        ],
        'repost' => [
            'button' => 'Reposter',
            'quote_button' => 'Citation',
            'title' => 'Republier ce post',
            'quote_title' => 'Citer ce post',
            'quote_label' => 'Ajouter un commentaire (facultatif)',
            'quote_placeholder' => 'Ajoutez vos pensés...',
            'reposted' => 'reposté',
            'success' => 'Reposté !',
            'removed' => 'Republication supprimée.',
            'already_reposted' => 'Vous avez déjà reposté ceci.',
            'undo' => 'Annuler le repost',
            'original_deleted' => 'Le post original a été supprimé.',
            'deleted_post' => 'Ce post a été supprimé',
        ],
        'hashtags' => [
            'title' => 'Trending',
            'trending-now' => 'Trending now',
            'post' => 'post',
            'posts' => 'posts',
            'posts-count' => ':count post|:count posts',
            'hashtag' => 'Hashtag',
            'hashtags' => 'Hashtags',
            'no-results' => 'No hashtags found',
        ],
        'search' => [
            'title' => 'Search',
            'placeholder' => 'Search posts, hashtags...',
            'no-results' => 'No results found',
            'posts' => 'Posts',
            'no-hashtags-found' => 'No hashtags found matching ":query"',
            'no-results-found' => 'No results found for ":query"',
        ],
        'poll' => [
            'title' => 'Sondage',
            'create' => 'Créer un sondage',
            'option' => 'Option',
            'add_option' => 'Ajouter une option',
            'duration' => 'Durée',
            'duration_1' => '1 jour',
            'duration_3' => '3 jours',
            'duration_7' => '7 jours',
            'votes' => '{0} votes|{1} vote|[2,*] votes',
            'ended' => 'Sondage terminé',
            'ends_in' => 'Termine dans :time',
            'login_required' => 'Connectez-vous pour voter',
        ],
        'gif' => [
            'title' => 'GIF',
            'search_placeholder' => 'Chercher des GIFs dans KLIPY...',
            'no_results' => 'Aucun GIFs trouvé',
            'powered_by' => 'Propulsé par',
            'categories' => 'Catégories',
            'trending' => 'Tendance',
        ],
        'media' => 'Média',
        'follow-suggestions' => 'Suivre l\'équipe',
        'explore' => 'Découvrir',
        'hashtag' => 'Hashtag',
        'no_users' => 'No users found.',
        'stories' => [
            'archive' => [
                'title' => 'Archives de stories',
                'subtitle' => 'Vos stories archivées ne sont visibles que pour vous',
                'empty' => 'Aucune story archivée pour le moment',
                'empty-description' => 'Les stories que vous publiez apparaîtront ici après 24 heures.',
                'action' => 'Archive',
                'archived' => 'La story a été déplacée dans les archives.',
                'already-archived' => 'Cette story est déjà archivée.',
            ],
        ],
    ],
    'private' => [
        'title' => 'Publications privées',
        'text' => 'Cette publication est privée.',
    ],
    'liked' => [
        'title' => 'Aimé',
    ],
    'following' => [
        'title' => 'Abonné',
        'text' => 'Connectez-vous pour voir cette publication.',
    ],
    'tags' => [
        'empty' => 'Pas de tags à voter pour le moment',
        'empty-subtitle' => 'Soyez le premier à en ajouter un',
    ],
    'inbox' => [
        'title' => 'Messages',
        'details' => 'Détails',
        'message_user' => 'Message',
        'write_message' => 'Écrire un message',
        'empty' => [
            'no_message_selected' => 'Pas de message sélectionné',
            'open_or_start_conversation' => 'Ouvrez une conversation à partir de la liste de messages ou démarrez une nouvelle.',
            'no_messages' => 'Aucun message non lu',
            'start_conversation' => 'Une fois que vous commencez une nouvelle conversation, vos messages seront affichés ici.',
            'conversation' => 'Ceci est le début de votre conversation avec :username.',
            'users' => 'Impossible de trouver les utilisateurs qui correspondent à la requête actuelle.',
        ],
        'typing' => ':username est en train d\'écrire...',
        'new_message' => 'Nouveau message',
        'mark_unread' => 'Marquer comme non lu',
        'send_message' => 'Envoyer un message',
        'delete_message' => 'Supprimer le message pour vous',
        'latest_conversations' => 'Dernières conversations',
        'delete_conversation' => 'Supprimer la conversation',
        'show_details' => 'Afficher les détails',
        'hide_details' => 'Masquer les détails',
        'unread' => 'Non-lu',
        'deleted' => 'Supprimé',
        'report_message' => 'Signaler le message',
        'add_reaction' => 'Ajouter une réaction',
        'today' => 'Aujourd\'hui',
        'reconnect' => 'Veuillez reconnecter votre compte Minecraft pour discuter',
        'account_disconnected' => 'Cet utilisateur a déconnecté son compte Minecraft lié.',
        'saved_messages' => 'Messages enregistrés',
        'new_message_to_label' => 'À',
        'external-link-to' => 'Ce lien vous amènera vers',
        'external-link-confirmation' => 'Êtes-vous sûr de vouloir y aller ?',
        'external-link' => 'Lien externe',
        'reply' => 'Répondre',
    ],
    'server' => [
        'manage' => [
            'stats' => 'Statistiques',
        ],
    ],
    'report' => [
        'button' => 'Signaler',
        'title' => 'Signaler le contenu',
        'describe' => 'Décrivez brièvement pourquoi vous signalez ceci',
        'select' => 'Sélectionnez la raison du signalement',
        'submit' => 'Envoyer le signalement',
        'reasons' => [
            'INAPPROPRIATE_CONTENT' => 'Contenu inapproprié',
            'SPAM' => 'Spam',
            'HARASSMENT' => 'Harcèlement',
            'OTHER' => 'Autre',
        ],
    ],
    'leaderboard' => [
        'title' => 'Classement',
        'description' => 'Voir le classement des utilisateurs de SkinMC.',
        'headline' => 'Top 10',
        'all-time-invites' => 'Invitations en tout temps',
        'all-time-xp' => 'XP de tous les temps',
        '30-day-xp' => '30 jours d\'XP',
    ],
];
