<?php

return [
    'auth' => [
        'login' => [
            'title' => 'Bienvenue sur SkinMC',
        ],
        'register' => [
            'title' => 'Inscrivez-vous à SkinMC',
            'subtitle' => 'Commencez à créer votre compte pour profiter de toutes les fonctionnalités.'
        ]
    ],

    'home' => [
        'hero_slogan' => 'Votre place pour les skins Minecraft.',
        'hero_cta' => 'Surprenez-moi',
        'hero_explore_cta' => 'Explorer les skins',
        'skin_viewer' => 'Visualiseur de skins',
        'skin_viewer_detail' => 'Voir :count skins',
        'skin_editor' => 'Éditeur de skins',
        'skin_editor_detail' => 'Concevez votre propre skin',
        'avatar_maker' => 'Générateur d\'avatar',
        'avatar_maker_detail' => 'Générez votre avatar Minecraft personnalisé.',
        'trending' => 'Tendance',
        'minecraft_skin' => 'Skin Minecraft',
        'favourite' => 'Favori',
        'collections' => 'Collections',
        'collections_detail' => 'Skins Minecraft organisés pour chaque occasion',
        'about_skinmc' => 'À propos de SkinMC',
        'about_find' => 'Trouver un skin',
        'about_find_detail' => 'Utilisez la recherche SkinMC pour trouver n\'importe quel pseudonyme Minecraft, afin de voir et télécharger votre prochain skin.',
        'about_download' => 'Télécharger ou modifier',
        'about_download_detail' => 'Vous avez trouvé un skin que vous appréciez ? Ajoutez-le à vos favoris, modifiez ou téléchargez-le afin d\'en faire le votre.',
        'about_platform' => 'Multi-plateforme',
        'about_platform_detail' => 'Voulez-vous prendre le skin ? Scannez le QR code et enregistrez l\'image sur votre téléphone pour Minecraft PE.',
        'meta' => [
            'title' => 'Visualiseur de skins Minecraft',
            'description' => 'Visualisez et téléchargez les skins Minecraft, découvrez les meilleurs skins dans les collections organisées, vérifiez la disponibilité d\'un pseudonyme, son historique, et bien plus encore !',
        ],
        'recently_viewed' => 'Récemment consulté',
        'explore_title' => 'Testez une nouveautée',
        'explore' => 'Explorez de nouvelles idées et outils',
        'servers_browse' => 'Voir les serveurs',
        'servers' => 'Découvrez les meilleurs serveurs Minecraft',
        'heads' => 'Têtes Minecraft',
        'head_description' => 'Parcourez les têtes de skins dans la base de donnée de Minecraft, ou créez en un.',
        'achievement' => 'Générateur de succès',
        'achievement_detail' => 'Créez vos propres succès personnalisés.',
        'continue' => 'Continuer la navigation'
    ],
    'profile' => [
        'verified' => 'Profil vérifié',
        'minecraft_profile' => 'Profil Minecraft',
        'show_qr_code' => 'Afficher le QR code',
        'favourite' => 'Favori',
        'user_title' => 'Skins Minecraft de :username',
        'user_views' => 'Vu :views fois|Vu :vues fois',
        'uuid' => 'UUID',
        'copy' => 'Copier',
        'link' => 'Lier',
        'skin_history' => 'Histoique des skins Minecraft (:skins)',
        'username_history' => 'Historique des pseudonymes',
        'username_history_name' => 'Pseudo',
        'username_history_timestamp' => 'Changé le',
        'username_history_initial_name' => 'Pseudo initial',
        'user_downloads' => ':downloads téléchargement|:downloads téléchargements',
        'download_skin' => 'Télécharger le skin',
        'apply_skin' => 'Appliquer le skin',
        'capes' => 'Capes',
        'claim_profile' => 'Êtes-vous :username ? Réclamez votre profil afin de le vérifier & de le personnaliser !',
        'claimed' => 'Profil réclamé',
        'meta_description' => 'Voir et télécharger le skin Minecraft de :username. Voir l\'UUID lié au pseudo, l\'historique de son nom, des statistiques détaillées, et plus',
        'created_at' => 'Mis à jour : :changed_at',
        'skins' => [
            'meta_title' => 'Historique des skins Minecraft de :username',
            'meta_description' => 'Regarde l\'historique des skins Minecraft précédemment utilisées par :username. Utilisez cet historique afin de parcourir les skins qui ont été utilisés par le passé, en avoir une sauvegarde et les récupérer.',
            'title' => 'Historique des skins Minecraft'
        ],
        'qr_code' => [
            'meta_title' => 'QR code de :username',
            'meta_description' => 'QR code personnalisé du profil Minecraft de :username'
        ],
        'sub_nav' => [
            'skin' => 'Skin',
            'about' => 'À propos',
            'usernames' => 'Pseudonymes',
            'head' => 'Tête',
            'comments' => 'Commentaires'
        ],
        'cape' => 'Cape',
        'elytra' => 'Élytres',
        'nametag' => 'Pseudonyme',
        'animation' => 'Animation',
        'rotation' => 'Rotation',
        'none' => 'Aucun',
        'idle' => 'Au repos',
        'walk' => 'Marche',
        'run' => 'Course',
        'fly' => 'Vol',
        'follow' => 'S\'abonner',
        'following' => 'Abonné',
        'unfollow' => 'Se désabonner',
        'followers' => 'Abonné|Abonnés',
        'toast' => [
            'following' => 'Vous vous êtes abonné à :username !',
            'follow-self-error' => 'Désolé :username, mais tu ne peux pas te suivre toi-même.',
            'unfollowed' => 'Vous vous êtes désabonné de :username'
        ],
        'edit' => 'Modifier votre profil',
        'joined' => 'Rejoint',
        'server-fav-list-empty' => 'On dirait que :username n\'a pas encore de serveurs favoris. Une fois que :username auras enregistré un serveur comme favoris, vous pouvez le voir ici.',
        'server-own-list-empty' => 'On dirait que :username n\'a pas encore de serveurs favoris. Une fois que :username auras enregistré un serveur comme favoris, vous pouvez le voir ici.',
        'capes-list-empty' => 'On dirait que :username ne porte pas encore de capes. Une fois que :username porte une cape, vous pourrez le voir ici.',
        'feed-own-list-empty' => 'Il semble que vous n\'ayez rien posté sur le flux ! Une fois que vous auriez posté quelque chose, vous pouvez voir vos messages ici.',
        'feed-list-empty' => 'Hmm, il semble que :username n\'ait encore rien posté dans le flux. Une fois que :username postera quelque chose, vous pouvez le voir ici.',
        'following-own-list-empty' => 'Il paraît que vous ne suivez encore personne ! Une fois que vous suivrez des personnes, vous pourrez les voir ici.',
        'following-list-empty' => 'Hmm, il paraît que :username ne s\'est abonné à personne. Une fois qu\'il se sera abonné à quelqu\'un, vous pourrez voir ses abonnements ici.',
        'followers-own-list-empty' => 'les personnes qui s\'abonnent à vous seront affichés ici.',
        'followers-list-empty' => 'Hmm, il paraît que :username n\'est pas encore suivi. Soyez le premier à vous abonner à :username. Les abonnés de :username apparaîtrons ici, uen fois que quelqu\'un s\'y abonnera.',
        'render' => 'Moteur de rendu',
        '3d' => 'Rendu 3D',
        '2d' => 'Rendu 2D',
        'name-history-info' => 'L\'historique des pseudonymes disparaît. Majong a retiré l\'accès à l\'historique des noms via leur API le 13 septembre 2022, résultant à un historique des pseudos indisponible. Si vous voulez retirer la visibilité de vous anciens pseudonymes, merci de réclamer votre profil et d\'aller dans vos paramètres afin de les rendre privés.',
        'edit-skins' => 'Modifier l\'historique des skins',
        'hide-skin' => 'Masquer le skin',
        'show-skin' => 'Afficher le skin',
        'edit-skin' => 'Modifier le skin',
        'servers' => [
            'title' => 'Serveurs de :username',
        ],
        'cape-list' => [
            'title' => 'Capes de :username',
        ]
    ],
    'skin' => [
        'meta' => [
            'title' => 'Skin Minecraft de :username',
            'description' => 'Skin Minecraft. Téléchargez et visualisez le skin, et voyez quels joueurs portent également le même skin.',
            'tags' => ':username Skin Minecraft, :username Skin, Minecraft Skin, :username Skin Minecraft personnalisé, Télécharger Skin, Joueurs avec le même skin',
        ],
        'title' => 'Skin Minecraft de :username',
        'head' => 'Commandes pour obtenir la tête',
        'head_info' => 'À utiliser avec les blocs de commande',
        'first_wearing' => 'Premier joueur vu porter cette apparence :',
        'profiles' => 'Profile de :profiles|Profiles de :profiles',
        'profiles_title' => ':profile avec ce skin |:profiles avec ce skin'
    ],
    'skins' => [
        'meta' => [
            'title' => 'Page :current — Touts les Skins Minecraft',
            'description' => 'Parcourez notre liste :last pages de :total skins Minecraft personnalisés et téléchargez votre prochain skin préféré !',
            'tags' => ':username Skin Minecraft, :username Skin, Minecraft Skin, :username Skin Minecraft personnalisé, Télécharger le Skin, Joueurs avec le même skin',
            'tags-title' => ':tag Skins Minecraft',
            'tags-description' => 'Parcourez notre liste de :last pages de :total :tag skins Minecraft et téléchargez votre skin :tag préféré !',
            'tags-metatags' => ':tag Skin Minecraft, :tag Skin, Skin Minecraft, :tag Skin Minecraft personnalisé, Télécharger un skin :tag, Skin :tag Minecraft',
        ],
        'title-skin-tags' => 'Skins Minecraft taggés',
        'subtitle' => 'Page :current sur :last de :total Skins Minecraft',
        'subtitle-skin-tags' => 'Page :current sur :last de :total Skins Minecraft taggés',
        'sort_by' => 'Trier par',
        'latest' => 'Derniers skins',
        'most_profiles' => 'Skins les plus utilisés',
        'profiles_today' => 'Tendance d\'aujourd\'hui',
        'profiles_this_week' => 'Tendance de cette semaine',
        'profiles_this_month' => 'Tendance du mois',
        'default' => 'Tri par défaut',
        'this_month' => 'Ajoutés ce mois',
        'this_week' => 'Ajoutés cette semaine',
        'today' => 'Ajoutés aujourd\'hui',
        'random' => 'Random',
        'similar' => 'Skins similaires',
        'no_similar_skins' => 'Malheureusement, aucuns skins similaires ont été trouvés.',
        'favorite' => ':favoris:favoris',
    ],
    'skin-tags' => [
        'faq' => 'Que sont les tags ?',
        'about' => 'Les tags sont un moyen d\'ajouter vos catégories aux skins. Ajouter des tags vous permet de découvrir plus de skins que vous aimez facilement !',
        'guidelines' => [
            'good' => [
                'title' => 'Les directives générales pour les bonnes balises sont :',
                'short' => 'Court',
                'descriptive' => 'Description',
                'spelled' => 'Orthographe correcte',
            ],
            'bad' => [
                'title' => 'Ne pas ajouter de balises telles que:',
                'general' => 'Trop général',
                'specific' =>  'Trop spécifique',
                'too-many-tags' =>  'Doit être trois balises séparées',
                'spelling' => 'Doit être :example',
            ],
        ],
        'toast' => [
            'added' => 'Étiquette ”:tag” ajoutée pour le vote',
            'removed' => 'L\'étiquette ”:tag” a été supprimé',
            'upvote' => 'Voté pour ":tag"',
            'downvote' => 'Voté contre ”:tag”'
        ],
        'vote' => [
            'up' => 'Voter',
            'down' => 'Voter contre',
            'remove' => 'Retirer le vote',
        ],
    ],
    'contact' => [
        'contact' => 'Contact',
        'email' => 'N\'hésitez pas à nous écrire à <a href="mailto:support@skinmc.net">support@skinmc.net</a> pour toutes questions.',
        'faq' => 'Nous vous prions de bien vouloir d\'abord consulter la page <a href=":link">FAQ</a> si votre question y est déjà répondue.',
        'other' => 'Autres moyens de se connecter',
        'other_discord' => 'Rejoignez le serveur Discord et connectez-vous avec d\'autres joueurs, discutez à propos des jeux, partagez vos packs favoris et obtenez de l\'aide de la communauté.',
        'other_twitter' => 'Suivez-nous sur X (avant Twitter) pour voir quand une nouvelle mise à jour, une nouvelle fonctionnalité est publiée, même voir le skin de la semaine et encore plus.',
        'other_instagram' => 'Suivez SkinMC sur Instagram pour naviguer et découvrir de nouveaux skins et images Minecraft mis en avant.',
        'other_facebook' => 'Devenez fan sur Facebook et voyez tous les messages où vous pouvez commenter et parler à d\'autres tout en explorant le contenu de Minecraft.'
    ],
    'about' => [
        'intro' => '<span>Votre plateforme</span> <span></span> <span>pour</span> <span>skins Minecraft</span> <span>.</span>',
        'header_credit' => 'Illustration "Bataille du Nether Épique" par',
        'info' => 'Garder une trace de tout.',
        'info_explainer' => 'Voir l\'historique des noms des joueurs, voir leurs skins précédents, les ajouter en tant qu\'ami, télécharger des skins et même obtenir des statistiques détaillées.',
        'card_find_title' => 'Trouvez n\'importe quel minecrafter',
        'card_find_detail' => 'Commencez par rechercher un nom d\'utilisateur ou un UUID de votre choix.',
        'card_view_title' => 'Afficher, enregistrer et éditer',
        'card_view_detail' => 'Vous avez trouvé un skin que vous aimez ? Enregistrez-le en téléchargeant ou en utilisant l\'éditeur pour le faire vous-même.',
        'card_claim_title' => 'Obtenir une vérification',
        'card_claim_detail' => 'Liez votre compte Minecraft et revendiquez votre profil pour débloquer de nouvelles fonctionnalités !',
        'card_customise_title' => 'Personnalisez votre profil',
        'card_customise_detail' => 'Les joueurs vérifiés peuvent ajouter leurs liens vers les réseaux sociaux et faire leur propre profil.',
        'card_friends_title' => 'Ajoutez vos amis',
        'card_friends_detail' => 'Connectez-vous avec vos amis sur SkinMC et montrez votre liste d\'amis sur le profil.',
        'card_history_title' => 'Nom d\'utilisateur et historique du thème',
        'card_history_detail' => 'Utilisez la recherche avancée pour trouver et voir le nom d\'utilisateur/l\'historique du skin d\'un joueur.',
        'founders' => 'Les fondateurs',
        'founders_cofounder' => 'Co-fondateurs de SkinMC',
        'head_of_design' => 'Chef de design',
        'head_of_code' => 'Chef de code',
        'feedback' => 'Envoyez-nous votre avis',
        'faq' => 'Des questions sur Minecraft, des skins et plus encore ? Lisez notre FAQ avec les réponses aux questions les plus fréquemment posées.',
        'faq_link' => 'Visiter la FAQ',
        'contact' => 'Vous voulez nous contacter ou vous avez d\'autres questions ? Contactez-nous directement.',
        'contact_link' => 'Contactez-nous',

    ],
    'faq' => [
        'title' => 'Foire aux questions',
        'subtitle' => 'Foire aux questions',
        'help' => 'Besoin d\'aide supplémentaire?',
        'discord' => 'Rejoignez le serveur Discord pour discuter avec d\'autres joueurs Minecraft.',
        'contact' => 'Contactez-nous',
        'q' => [
            'change_skin_t' => 'Comment puis-je changer mon skin Minecraft ?',
            'change_skin' => '
                <p>Pour changer votre Skin faites ce qui suit :</p>
                <ol>
                    <li>Visitez <a href="https://my.minecraft.net/en-us/login/">https://my. inecraft.net/en-us/login/</a> et connectez-vous avec votre compte Mojang.</li><li>Une fois connecté, sélectionnez <b>"Skin"</b> dans le menu de gauche.</li><li>Ensuite, choisissez un modèle que vous préférez et téléchargez un skin de votre goût.</li>
                </ol>',
            'change_username_t' => 'Comment puis-je changer mon nom d\'utilisateur Minecraft ?',
            'change_username' => '
                <p>Pour modifier votre nom d\'utilisateur :</p>
                <ol>
                    <li>Visitez <a href="https://account.mojang.com/login" target="_blank" rel="nofollow">https://account. ojang.com/connectez-vous</a> et connectez-vous avec votre compte Mojang.</li>
                    <li>Trouvez votre nom de profil Minecraft et appuyez sur le <b>"(Change)"</b> bouton</li>
                    <li>Sur la page suivante, entrez le nouveau nom d\'utilisateur que vous souhaitez.</li>
                    <li>Enfin, confirmez les modifications en saisissant votre mot de passe et en appuyant sur "Changer de nom".</li>
                </ol>',
            'dl_t' => 'Comment télécharger le skin Minecraft de quelqu\'un ?',
            'dl' => '
                <p>Pour télécharger n\'importe qui Skin de Minecraft, faites ce qui suit :</p>
                <ol>
                    <li>Appuyez sur la barre de recherche et entrez le nom d\'utilisateur du joueur dont vous souhaitez télécharger le skin.</li>
                    <li>Sur la page de profil, vous pouvez prévisualiser le skin</li>
                    <li>Cliquez sur le <strong>Télécharger le Skin</strong> sous l\'aperçu</li>
                </ol>',
            'submit_q' => 'Comment puis-je soumettre un skin à une collection ?',
            'submit_a' => '<p>Merci de remplir le formulaire suivant avec la catégorie et le pseudonyme du joueur que vous voudriez ajouter à la collection. <a href="https://forms.gle/f4Jh5RpGfsHAZ5xE8" target="_blank">Formulaire de submition</a>',
            'mcpe_t' => 'Puis-je utiliser le Skin sur Minecraft PE ?',
            'mcpe' => '
                <p>Oui. Pour utiliser le Skin dans Minecraft Pocket Edition, faites ce qui suit :</p>
                <ol>
                    <li>Open SkinMC. sur votre smartphone et appuyez sur la barre de recherche</li>
                    <li>Entrez le nom d\'utilisateur de l\'apparence du joueur que vous souhaitez télécharger</li>
                    <li>Appuyez sur le bouton <strong>Télécharger Skin</strong> sous l\'aperçu </li>
                    <li>Ouvrez Minecraft PE et appuyez sur <strong>Profil</strong> sur le côté droit</li>
                    <li>Tapez sur le <strong>+</strong>, ou modifiez le caractère et allez dans l\'onglet "skins classiques"</li>
                    <li>Appuyez sur "propriété", puis "importer", puis "choisir une nouvelle peau"</li>
                </ol>',
            'change_times_t' => 'À quelle fréquence puis-je changer mon nom d\'utilisateur ?',
            'change_times' => '<p>Vous pouvez changer votre pseudo Minecraft <strong>une fois </strong> tous les <strong>30 jours</strong>.</p>',
            'available_t' => 'Après que j\'ai changé mon nom d\'utilisateur, quand est-il disponible pour les autres de le réclamer?',
            'available' => '<p>Si vous souhaitez revenir à votre nom d\'utilisateur précédent, vous pouvez revenir en arrière <strong>après 30 jours.</strong> Tout le monde a besoin d\'attendre un <strong>7 jours supplémentaires</strong> (37 jours après le changement) avant de pouvoir réclamer votre ancien nom d\'utilisateur. </p>',
            'username_history_t' => 'Pouvez-vous supprimer l\'historique de mon nom d\'utilisateur s\'il vous plaît ?',
            'username_history' => '
                <p>Comme les données de l\'historique du nom d\'utilisateur viennent de Mojang, l\'historique du nom d\'utilisateur ne peut pas être supprimé. Mojang a précédemment déclaré que leur intention était que les noms d\'utilisateur précédents puissent être vus1, et qu\'ils fournissent une méthode directe pour le public pour accéder à ces informations2.</p>
                <p class="font-14">1<a href="https://help.minecraft.net/hc/en-us/articles/360034636712-Minecraft-Usernames" target="_blank" rel="noreferrer">https://help. inecraft. et/hc/en-us/articles/360034636712-Minecraft-Usernames</a></p>
                <p class="font-14 mb-0">2<a href="https://twitter.com/dinnerbone/status/554739042529849345" target="_blank" rel="noreferrer">https://twitter. om/dinnerbone/status/554739042529849345</a> (Tweet archivé il y a 2 ans : <a href="http://archive.is/TeAyj" target="_blank" rel="noreferrer">http://archive. s/TeAyj</a>)
                </p>',
        ],
    ],
    'avatars' => [
        'start' => [
            'title' => 'Créez votre propre avatar Minecraft',
            'subtitle' => 'Utilisez le générateur d\'avatar Minecraft pour créer un avatar amusant à partir de n\'importe quel skin !',
            'avatar_face' => 'Avatar de style visage',
            'avatar_bust' => 'Avatar de style buste',
            'avatar_cube' => 'Avatar de style cube',
            'avatar_head3d' => 'Têtes 3D personnalisés',
        ],
        'user' => [
            'title' => 'Choisir un skin',
            'subtitle' => 'Entrez le nom d\'utilisateur Minecraft pour l\'avatar que vous souhaitez générer',
            'form_label' => 'Nom d\'utilisateur Minecraft',
            'form_submit' => 'Continuer',
        ],
        'output' => [
            'title' => 'Prévisualiser et enregistrer',
            'subtitle' => 'Profitez de votre nouvel avatar Minecraft',
            'download_info' => 'Heureux avec le résultat ? Commencez à utiliser votre nouvel avatar en le téléchargeant ici',
            'download_button' => 'Télécharger l\'avatar',
            'avatar_style' => 'Style de l\'avatar',
            'skin_username' => 'Nom d\'utilisateur du thème',
            'change' => 'Changement',
            'generate' => 'Générer',
            'avatar_colour' => 'Couleur d\'arrière-plan',
            'avatar_colour_palette' => 'Palette',
            'avatar_colour_basic' => 'Basique',
        ],
        'meta' => [
            'title' => 'Générateur d\'Avatar Minecraft',
            'description' => 'Minecraft Avatar Maker: créez des images de profil Minecraft personnalisées en utilisant votre skin Minecraft',
        ],
    ],
    'totem' => [
        'title' => 'Totem Minecraft personnalisé',
        'subtitle' => 'Utilisez le générateur de Totem Minecraft pour créer un pack de ressources personnalisées avec un Totem d\'immortalité à partir de n\'importe quel skin.',
        'download_info' => 'Heureux avec l\'aperçu ? Choisissez votre version de Minecraft pour enregistrer votre pack de ressources personnalisé :',
        'meta' => [
            'title' => 'Générateur de totem personnalisé Minecraft',
            'description' => 'Totems Minecraft personnalisés : générez et créez un pack de ressources Minecraft personnalisé avec un Totem d\'Imortalité en utilisant votre skin Minecraft ou celui de n\'importe quel autre joueur.',
        ],
        'type' => [
            'mini' => 'Une version miniature de votre skin !',
            'full' => 'Une version complète de votre skin !',
            'model3d' => 'Un modèle 3D de votre skin !',
            'add_designs' => 'Vous voulez voir plus de designs ? Soumettez votre suggestion de design ici :'
        ]
    ],
    'achievement' => [
        'header' => [
            'title' => 'Créez votre propre Achievement Minecraft',
            'subtitle' => 'Utilisez le générateur de Achievement Minecraft pour créer vos propres réalisations personnalisées et utiliser montrer vos progrès dans tout ce que vous aimez !',
        ],
        'generator' => [
            'yellow_text' => 'Texte jaune',
            'white_text' => 'Texte blanc',
            'choose_icon' => 'Choisir une icône',
            'face' => 'Face Minecraft au lieu de l\'icône',
            'form_submit' => 'Télécharger',
            'form_label' => 'Nom d\'utilisateur Minecraft',
            'download' => 'Télécharger',
            'embed' => 'Intégrer',
            'embed_copy' => 'Copie',
        ],
        'meta' => [
            'title' => 'Générateur de Achievement Minecraft',
            'description' => 'Générer des Achievements et des Avancements Minecraft personnalisés avec le créateur de Achievements. Télécharger l\'image directement, l\'utiliser dans les signatures du forum, intégrer avec du code HTML ou BB, et plus encore',
        ],
    ],
    'armor' => [
        'header' => [
            'title' => 'Créateur de porte-armure Minecraft',
            'subtitle' => 'Générez et créez vos propres portes armures Minecraft personnalisées. Créez différentes poses, positions, placez des objets et bien plus encore.',
        ],
        'meta' => [
            'title' => 'Créateur de porte-armure Minecraft',
            'description' => 'Générez et créez facilement des porte-armures Minecraft personnalisés. L\'éditeur vous aide à faire différentes positions, placer des objets, des armures personnalisés, et bien plus encore.',
        ],
    ],
    'banner' => [
        'editor' => [
            'header' => [
                'title' => 'Éditeur de bannière Minecraft',
                'subtitle' => 'Concevez et créez vos propres bannières Minecraft personnalisées. Celles-ci peuvent être utilisés pour décorer votre monde ou aussi comme <a href="https://optifine.net" target="_blank" rel="nofollow">Cape Optifine</a>.',
            ],
            'meta' => [
                'title' => 'Créateur de bannière Minecraft',
                'description' => 'Créez et concevez vos propres bannières Minecraft personnalisées avec tous les motifs et couleurs du jeu ! Ils peuvent être utilisés pour décorer votre monde ou être portés en tant que cape Optifine. Vous pouvez générer des commandes pour les obtenires en tant que bannières ou les boucliers.',
            ],
        ],
        'gallery' => [
            'header' => [
                'title' => 'Galerie de bannières Minecraft',
                'subtitle' => 'Parcourez la galerie de :count bannières Minecraft conçues sur mesure. Vous pouvez utiliser une bannière comme cape pour rendre votre skin Minecraft plus unique, ou utilisez une bannière comme drapeau pour décorer votre monde.',
            ],
            'meta' => [
                'title' => 'Galerie de bannières Minecraft',
                'description' => 'Parcourez la galerie de :count bannières Minecraft conçues sur mesure. Vous pouvez utiliser une bannière comme cape pour rendre votre skin Minecraft plus unique, ou utilisez une bannière comme drapeau pour décorer votre monde.',
            ],
        ],
    ],
    'search' => [
        'meta' => [
            'title' => 'Résultats de recherche : :search',
        ],
        'title' => 'Résultats de recherche',
        'results' => 'Page :current pour :count résultat|Page :current d\'environ :count résultats ',
        'time' => '(:time secondes)',
        'username_available' => 'Nom d\'utilisateur disponible*',
        'username_unavailable' => 'Nom d\'utilisateur non disponible',
        'username_status' => 'Statut',
        'username_status_available' => 'Disponible*',
        'username_status_unavailable' => 'Indisponible',
        'username_searches' => 'Recherches',
        'username_searches_count' => ':count / jour',
        'username_available_disclaimer' => '*Sauf si le nom est temporairement ou définitivement banni par Mojang.',
        'no_results' => 'Aucun profil trouvé. Essayez de rechercher avec UUID en modifiant le type de recherche.',
        'no_results_tags' => 'Pas de skins taggés trouvés. Essayez de rechercher d\'autres tags tels que "bleu", "fille", "renard", etc...',
        'again' => 'Rechercher de nouveau',
        'sorry' => 'Désoléééééé...',
        'view_profile' => 'Afficher le profil',
    ],
    'collection' => [
        'title' => 'Collection de skin Minecraft',
        'subtitle' => 'Parcourez notre collection de skins Minecraft.',
        'filters' => 'Filtres',
        'title_trending' => 'Tendance',
        'title_all' => 'Toutes les skins Minecraft',
        'skin_tags' => 'Skins taggés',
        'filters_skin_type' => 'Type de peau',
        'filter_skin_type_steve' => 'Type de Steve',
        'filter_skin_type_alex' => 'Type d\'Alex',
        'cancel' => 'Abandonner',
        'apply' => 'Appliquer',
        'username_minecraft_skin' => 'Thème Minecraft de :username',
        'user_downloads' => '<span class="fw-500">téléchargements</span>téléchargement<span class="fw-500">téléchargements</span>téléchargements',
    ],
    'favourites' => [
        'title' => 'Favoris',
        'subtitle' => 'Voir et gérer les skins que vous avez enregistrés plus tard dans votre liste de favoris',
        'sort' => 'Trier par',
        'toast' => [
            'added' => 'Ajouté à vos favoris',
            'removed' => 'Supprimé de vos favoris'
        ],
        'skins' => [
            'button' => 'Skins',
            'empty_headline' => 'Aucun skins favoris pour le moment',
            'empty_subtitle' => 'Vous n\'avez pas encore de skins enregistrés dans votre liste de favoris. Visitez la page du serveur et découvrez votre prochain skin favori !',
            'empty_browse' => 'Parcourir les skins',
            'meta' => [
                'title' => 'Mes skins favoris',
                'description' => 'Mes skins favoris Minecraft',
            ],
        ],
        'servers' => [
            'button' => 'Serveurs',
            'empty_headline' => 'Aucun serveur favoris pour le moment',
            'empty_subtitle' => 'Vous n\'avez pas encore de serveurs enregistrés dans votre liste de favoris. Visitez la page du serveur et découvrez votre prochain serveur favori !',
            'empty_browse' => 'Parcourir les serveurs',
            'meta' => [
                'title' => 'Mes serveurs favoris',
                'description' => 'Mes serveurs Minecraft favoris',
             ],
        ],

    ],
    'cape' => [
        'editor' => [
            'title' => 'Éditeur de cape Minecraft',
            'subtitle' => 'Utilisez l\'éditeur de cape Minecraft pour créer votre propre cape !',
            'meta' => [
                'title' => 'Éditeur de cape Minecraft',
                'description' => 'Utilisez l\'éditeur de cape Minecraft pour créer votre propre cape !',
            ],
        ],
        'list' => [
            'title' => 'Captures Minecraft',
            'subtitle' => 'Captures officielles de Minecraft',
            'meta' => [
                'title' => 'Liste des Capes Minecraft',
                'description' => 'Liste de capes Minecraft : Voir toutes les capes officielles, Minecon, Capes personnelles, spéciales',
            ],
        ],
        'detail' => [
            'title' => 'Cape :cape',
            'info' => 'Informations de la cape',
            'profile_list' => 'Profils avec ce cape',
            'profiles' => ':profiles profile|:profiles profiles',
            'meta' => [
                'title' => 'Liste des Capes Minecraft',
                'description' => 'Liste des capsules Minecraft : Voir tous les caps officiels de Minecraft, y compris Mojang, Minecon, Capes personnels, Speical et vanité',
            ],
        ],
        'list-custom' => [
            'title' => 'Capes Minecraft personnalisé',
            'description' => 'Parcourez et regardez les capes personnalisées qui ont été créés et utilisés par les membres de SkinMC.'
        ]
    ],
    'servers' => [
        'title' => 'Serveurs Minecraft',
        'subtitle' => 'Parcourir et explorer les serveurs minecraft',
        'all' => 'Tous les serveurs',
        'manage_your_servers' => 'Gérez vos serveurs',
        'add_new_server' => 'Ajouter un nouveau serveur',
        'filters' => [
            'trending' => 'Tendance',
            'updated' => 'Mis à jour',
            'new' => 'Nouveau',
            'most_viewed' => 'Les plus consultés',
            'top_voted' => 'Meilleurs votants',
            'sorting' => 'Trier',
            'sort_by_latest' => 'Trier par plus récent',
            'sort_by_oldest' => 'Trier par plus ancien',
            'categories' => 'Catégories',
            'server_location' => 'Localisation du serveur',
            'show_results' => 'Afficher les résultats',
            'show_more' => 'Montrer plus',
            'show_less' => 'Afficher moins',
            'clear_filters' => 'Annuler les filtres',
            'reviews' => 'Avis',
            'sort_by_highest_rating' => 'Trier par note la plus élevée',
            'sort_by_lowest_rating' => 'Trier par note la plus basse',
            'bedrock_and_java_support' => 'Support Bedrock et Java'
        ],
        'review-count' => ':count Avis|:count Avis',
        'meta' => [
            'title' => 'Liste des serveurs Minecraft',
            'description' => 'Naviguez et explorez la liste des serveurs Minecraft pour trouver le meilleur serveur Minecraft ! Filtrez par le dernier, le plus populaire et bien plus encore',
        ],
        'reviews' => [
            'meta' => [
                'title' => 'Écrire un avis',
            ],
            'editing' => 'Vous modifiez votre avis du :date. Voulez-vous supprimer votre avis à la place ?',
            'welcome' => 'Bonjour :username. Comment a été votre expérience globale avec :servername?',
            'subtitle' => 'Leave an overall score of your past experience with the server.',
            'scale' => [
                'great' => 'Great',
                'good' => 'Good',
                'okay' => 'Okay',
                'meh' => 'Meh',
                'bad' => 'Bad',
            ],
            'rate-experience' => 'Next, rate your experience in these areas',
            'overall' => 'Overall',
            'server-team' => 'Server team',
            'community' => 'Community',
            'experience' => 'Experience',
            'availablility' => 'Uptime and availability',
            'shop' => 'Shop',
            'write-review-title' => 'Write a review',
            'write-review-subtitle' => 'Leave a few notes, you can highlight what you enjoyed, what made your experience special, or offer a few suggestions.',
            'write-review-helper' => 'Write a server review to share your experience with new players, and help the server owners with feedback.',
            'write-review-tips' => 'Here are some tips',
            'submit-title' => 'Ready to submit your review?',
            'submit-subtitle' => 'Almost done!',
            'submit-review' => 'Submit my review',
            'back' => 'Back',
            'continue' => 'Continue',
            'delete-title' => 'Are you sure you would like to delete your review?',
            'tos-checkbox-part-1' => 'By submitting this form you accept SkinMC\'s Terms of Service, Privacy Policy, and Community Guidelines. You also confirm that all of the information is accurate, and follows the',
            'tos-checkbox-part-2' => 'review guidelines.',
            'tos-checkbox-part-3' => 'Your review will be published after submission, but can be subject to review.'
        ],
        'slots' => 'Slots',
        'empty-helper' => 'You can try to do another search or',
        'empty' => 'Hmm it\'s still empty here.',
        'verified' => 'Verified',
        'review_translate_show_original' => 'Show original',
        'review_translate' => 'Traduire la critique',
        'description_translate' => 'Translate description',
        'create' => [
            'welcome' => 'Welcome',
            'basics' => 'Basics',
            'categories' => 'Categories',
            'social_links' => 'Social links',
            'trailer_video' => 'Trailer video',
            'images' => 'Images',
            'images_description' => 'You can upload photos afterwards, to showcase what your server offers.',
            'submit' => 'Submit',
            'lets_get_your_server_added' => 'Let\'s get your server added.',
            'basics-subtitle' => 'Let people know what your server is about.',
            'description' => 'Description',
            'description_tips' => 'Here are some tips',
            'description_hint' => 'Write a good description for your server to attract new players.',
            'categories-subtitle' => 'Choose some categories for your server',
            'missing-category' => 'Missing a category?',
            'social_links_description' => 'Where can players connect with your server on social media?',
            'trailer_video_description' => 'Showcase your server with a YouTube video.',
            'trailer_video_hint' => 'Paste the video URL or ID:',
            'ready_to_submit_your_server' => 'Ready to submit your server?',
            'review-hint' => 'After submission the team will carefully review your server listing application. Then upon decision, your server will be published, or changes requested before going live.',
            'terms' => [
                'part-1' => 'By submitting this form you are authorised to accept SkinMC\'s Terms of Service, Privacy Policy, and Community Guidelines. You also confirm that all of the information above is accurate, you have properly followed the',
                'part-2' => 'server requirements for setup',
                'part-3' => ', and that the Minecraft server is owned and managed by the entity you are representing.'
            ],
            'submit-application' => 'Submit application',
            'video-id-helper' => [
                'part-1' => 'The video ID is the string of numbers and letters after',
                'part-2' => 'For example if your video url is',
                'part-3' => ', then your video ID would be'
            ],
            'welcome_description' => 'In this step, we\'ll get started on adding your server. Tell us a bit about it, write a description, and in the next step you can upload some images.'
        ],
        'copy_server_ip' => 'Copy server IP',
        'all_minecraft_servers' => 'All Minecraft Servers',
        'promo' => [
            'title' => 'Do you host a Minecraft Server?',
            'ready_to_list_your_server' => 'Ready to list your Server?',
            'everything_you_need' => 'Everything you need to grow your server',
            'list_your_server' => 'List your server',
            'list_your_server_description' => 'Create a listing for your server, add photos, social media and more.',
            'find_players' => 'Find players',
            'find_players_description' => 'Find and reach new players to join your server and grow your community.',
            'get_reviews' => 'Get reviews',
            'get_reviews_description' => 'Ask your community to review your server, and reward them in game.',
            'why_list_on_skinmc' => 'Why you should list your Server on SkinMC',
            'others' => 'Others',
            'quality_check_and_confirmation' => 'Quality check and confirmation',
            'quality_check_description' => 'Our team reviews every server to ensure quality.',
            'verified_players' => 'Reviews from verified Minecraft players',
            'verified_players_description' => 'Collect authentic player reviews from legitimate accounts with Votifier integration.',
            'international' => 'International',
            'international_description' => 'With translation features your listing is available to more players.',
            'server_listing_page' => 'Powerful Server listing page',
            'server_listing_page_description' => 'Add photos, description texts, youtube videos, and highlight why players should join your server.',
            'social_connections' => 'Social media connections',
            'social_connections_description' => 'Connect your Servers social accounts and show new players where they can find you.',
            'verified_badge' => 'Verification badge',
            'verified_badge_description' => 'Authentic servers can apply for a verification badge.',
            'owner_profile' => 'Owner profile',
            'owner_profile_description' => 'Add a personal touch, by completing your custom profile.',
            'categories' => 'Categories',
            'categories_description' => 'Different categories to make it easier to find your server.',
            'vote' => 'Vote',
            'vote_description' => 'Ask users to vote for your server.',
            'fair_listings' => 'Fair listings',
            'fair_listings_description' => 'Server listings can not be artificially boosted in results on SkinMC.',
            'support' => '24h support',
            'support_description' => 'Do you need help or have questions? You can always reach out and receive a fast reply.',
            'custom_features' => 'Custom features',
            'custom_features_description' => 'Missing a feature for your server? Open a ticket, and we\'ll implement it.',
            'faq' => [
                'title' => 'Answers to your questions',
                'suited-question' => 'Is my Minecraft Server suited for SkinMC?',
                'suited-answer' => 'Minecraft Players on SkinMC love to discover new experiences, content and engage with communities. On the platform you\'ll find a large variety of different, unique, fun Minecraft servers. From a large network to even a small survival server, it can make someones day!',
                'get-started-question' => 'How do I get started?',
                'get-started-answer' => 'Adding your Minecraft Server to the SkinMC Server List is very easy! You will first need to create an account, if you haven\'t already, and then follow the setup guide to get your server listed. Add a few photos and a nice description, and your server will be published in no time!',
                'players-question' => 'How can I get more players on my Minecraft Server?',
                'players-answer' => 'Building a community is the most crucial part of a long lasting Minecraft Server. Use the Minecraft Server List on SkinMC to find a new audience and continue to build your community. Ask your players to recommend your Server, or share your listing on social media platforms. Collecting good reviews can also play an important role to a great Server listing presence that attracts new players.',
                'more-question' => 'I have more questions. Where can I get help?',
                'more-answer' => 'You can reach out to SkinMC at any time, 24 hours, by using either the help button, the help desk, or by joining the Discord server.'
            ],
            'ready_to_list_description' => 'Add your Minecraft Server to the SkinMC Server List in just a few minutes. If you need any help, you can reach out around the clock and receive answers quickly.'
        ],
        'manage' => [
            'index' => [
                'welcome' => 'Welcome back, :username',
                'your_servers' => 'Your servers',
                'reviews_today' => 'Reviews today',
                'no_reviews_today' => 'No reviews today',
                'no_reviews_text' => 'Your servers haven\'t received any reviews today. Why not ask your players to leave one?',
                'tips' => [
                    'title' => 'Tips',
                    'description-title' => 'Write a good server description',
                    'description-body' => 'Helpful tips and advice to write a great server description.',
                    'images-title' => 'Adding server images',
                    'images-body' => 'Make your server listing stand out with great images.'
                ]
            ],
            'listings' => [
                'title' => 'Your Minecraft servers (:count)'
            ],
            'insights' => [
                'title' => 'Insights'
            ],
            'edit_server' => 'Edit server',
            'listing' => 'Listing',
            'to_do' => 'To do',
            'last_update' => 'Last update',
            'add_more_photos_to_publish' => 'Add more photos to publish',
            'looks_empty_here' => 'Looks empty here.',
            'get_started_by_adding_a_new_server' => 'Get started by adding a new server?'
        ],
        'status' => [
            'approved' => 'Approved',
            'pending_approval' => 'Pending approval',
            'published' => 'Published',
            'in_review' => 'In review'
        ]
    ],
    'editor' => [
        'import' => [
            'title' => 'Import Skin',
            'import_by_username' => 'Import by username',
            'import_button' => 'Import',
            'drag' => 'Drag and drop a skin here, or click',
            'click' => 'Select image'
        ],
        'draw' => 'Draw',
        'eyedropper' => 'Eyedropper',
        'fill' => 'Fill',
        'move' => 'Move',
        'decrease_brightness' => 'Decrease brightness',
        'increase_brightness' => 'Increase brightness',
        'erase' => 'Erase',
        'undo' => 'Step back (CTRL+Z)',
        'redo' => 'Step forward (CTRL+Y)',
        'default_view' => 'Default view',
        'zoom_in' => 'Zoom in (CTRL +)',
        'zoom_out' => 'Zoom out (CTRL -)',
        'saved' => 'Dernière sauvegarde à l\'instant',
        'saving' => 'Enregistrement automatique...',
        'save_error' => 'Une erreur s\'est produite',
        'new_skin' => 'New skin',
        'previous_skins' => 'Previous skins',
        'backed_up_title' => 'Automatically saved skins',
        'backed_up_info' => 'Temporarily backed up to your local storage.',
        'backed_up_empty_title' => 'It\'s empty here',
        'backed_up_empty_info' => 'Once you start editing skins you\'ll see your 32 last edited skins here.',
        'backed_up_skins_count' => 'of 32 skin backups used',
        'backed_up_skins_count_info' => 'You can back up to up 32 skins. Once you reach 32 skins an older skin will be replaced with a new one.',
        'layers' => 'Couches',
        'body' => [
            'title' => 'Corps',
            'overlay' => 'Overlay',
            'head' => 'Tête',
            'torso' => 'Torse',
            'l_arm' => 'Bras gauche',
            'r_arm' => 'Bras droit',
            'l_leg' => 'jambe gauche',
            'r_leg' => 'jambe droite',
        ],
        'model' => 'Modélisation',
        'steve' => 'Steve',
        'alex' => 'Alex',
        'stance' => [
            'title' => 'Position',
            'default' => 'Par défaut',
            'walk' => 'Marcher',
            'run' => 'Exécuter',
            'hug' => 'T-pose',
            'fly' => 'Vol',
        ],
        'fullscreen' => 'Fullscreen',
        'fullscreen_exit' => 'Exit fullscreen',
        'grid' => 'Grille',
        'show_grid' => 'Afficher la grille',
        'download' => [
            'title' => 'Enregistrer et télécharger',
            'subtitle' => 'Compte SkinMC',
            'description' => 'Voulez-vous créer un compte SkinMC gratuit pour enregistrer votre skin et ceux futurs dans le cloud ?',
            'start_description' => 'Commencez à télécharger directement sans enregistrer dans le cloud',
            'start' => 'Télécharger le thème',
        ],
        'help' => [
            'title' => 'Minecraft Skin Editor',
            'about' => 'Create and edit your custom Minecraft Skin easily with the SkinMC Editor. You can choose between Steve and Alex models, import skins from a file or username, and create your very own Minecraft Skin.',
            'draw' => 'Draw using the pen tool. Select a colour from the swatch to use with it.',
            'eyedropper' => 'Use the eyedropper to select a colour from your skin and add it to your current palette.',
            'fill' => 'Fill entire areas of your skin using the fill tool. Select a colour before using fill.',
            'move' => 'Pan and move around the skin editor canvas with the move tool.',
            'decrease_brightness' => 'Decrease the brightness of the currently active colour.',
            'increase_brightness' => 'Increase the brightness of the currently active colour.',
            'erase' => 'Erase pixels drawn on the secondary overlay layer.',
        ],
    ],
    'account' => [
        'level' => 'Level',
        'level_history' => 'Level history',
        'xp' => 'XP',
        'my_xp' => 'My XP',
        'xp_to_next_level' => ':xp XP to next level',
        'xp_info' => 'What are XP?',
        'xp_info_tooltip' => 'XP is earned for various activities such as adding tags to skins, inviting friends, commenting, and much more. With each XP earned you can level up and unlock cool things!',
        'settings' => [
            'title' => 'Compte client',
            'show_profile' => 'Aller au profil',
            'friends' => 'Amis',
            'friends_detail' => 'Restez connecté en utilisant votre liste d\'amis sur SkinMC.',
            'security' => 'Sécurité',
            'security_detail' => 'Mettez à jour votre mot de passe de connexion et protégez votre compte',
            'social' => 'Comptes des réseaux sociaux',
            'social_detail' => 'Personnalisez votre profil en ajoutant votre réseau social',
            'link' => 'Lier le compte Minecraft',
            'link_detail' => 'Liez votre compte Minecraft et revendiquez votre profil.',
            'logout' => 'Voulez-vous vous déconnecter de votre compte SkinMC ?',
            'automatic_backups' => 'Automatic skin backups',
            'automatic_backups_info' => 'As a SkinMC plus member your skins are backed up daily.',
        ],
        'capes' => [
            'title' => 'SkinMC Minecraft Cape',
            'description' => 'Wear any cape you wish in-game with SkinMC Capes for free.',
            'drop' => 'Drag and drop a cape here',
            'drop-hint' => 'Dimensions 64x32px',
            'select' => 'Select image',
            'upload-cape' => 'Upload & use cape',
            'save-and-use' => 'Save & use',
            'uploaded-cape' => 'Uploaded cape',
            'no-cape' => 'No cape',
            'remove-cape' => 'Remove cape',
            'download' => 'Download the SkinMC Mod to see your and other players capes in-game.',
            'learn-more' => 'Learn more',
            'link-account' => 'Please link your Minecraft account to upload a cape.',
            'updated' => 'Your cape has been updated!',
            'removed' => 'Your cape has been removed.',
            'active' => 'Your cape is activated!'
        ],
        'favourite' => 'Favourite',
        'remove_favourite' => 'Remove favourite',
        'added_to_favourites' => 'Added to favourites',
        'removed_from_favourites' => 'Removed from favourites',
        'welcome' => 'Nice to see you!',
        'view-profile' => 'View my profile',
        'security' => [
            'title' => 'Sécurité',
            'email' => 'Adresse e-mail',
            'email-title' => 'Update your email address.',
            'save' => 'Enregistrer',
            'password' => 'Mot de passe',
            'password-title' => 'Change your password at any time.',
            'social-provider' => 'To update your account information, such as your password, please visit your login provider:',
            'social-provider-email' => 'Your associated email address with your login provider',
            'social-provider-connected' => 'Currently connected login providers',
            'current-password' => 'Current password',
            'forgot' => 'Forgot password?',
            'edit' => 'Editer',
            'delete' => 'Delete my account',
            'account-deletion' => 'Delete your SkinMC account.',
            'delete-info' => 'Please confirm to continue',
            'delete-confirmation' => 'Deleting your account is irreversible. All your personal information and content such as posts, favourites, uploaded capes, customisations, etc. will be deleted and can not be recovered.',
            'delete-confirmation-info' => 'Enter your password to continue',
            'yes-confirm-delete' => 'Yes, confirm delete',
            'account-successfully-deleted' => 'Your account and data has been successfully deleted.'
        ],
        'social' => [
            'title' => 'Comptes sociaux',
            'edit' => 'Editer',
            'save' => 'Enregistrer',
            'link-account' => 'Link your Minecraft account to SkinMC to display your social links on your profile.',
            'finish-setup' => 'Finish setup',
            'connect-account' => 'Connect your accounts',
            'connect-description' => 'Choose which accounts you wish to connect and unlock special SkinMC integrations.',
            'empty' => 'No accounts added',
            'empty-description' => 'Your social media accounts will show up here and on your public profile. Once added they will add more personalisation to your page as well as enable integrations.',
            'connect' => 'Connect',
            'username' => 'username',
            'spotify' => 'Add your Spotify username to show your Spotify information on your profile.',
            'discord' => 'Enter your Discord username and number to display your Discord information on your SkinMC profile.',
            'youtube' => 'Add your YouTube channel to SkinMC which will display your YouTube channel on your profile.',
            'youtube-format' => 'Use the following format depending on your channel link:',
            'twitter' => 'Enter your Twitter username to display it on your profile.',
            'twitch' => 'Enter your Twitch username to display your Twitch channel on your profile.',
            'reddit' => 'Enter your Reddit username to display your Reddit profile on your profile.',
            'github' => 'Enter your GitHub username to display your GitHub profile on your profile.',
            'telegram' => 'Enter your Telegram username to display your Telegram link on your profile.',
            'tiktok' => 'Enter your TikTok username to display your TikTok profile on your profile.',
            'snapchat' => 'Enter your Snapchat username to display your Snapchat profile on your profile.',
            'instagram' => 'Enter your Instagram username to display your Instagram profile on your profile.',
            'facebook' => 'Enter your Facebook username to display your Facebook profile on your profile.',
            'includes_skinmc_plus_benefits' => 'Includes SkinMC plus benefits',
        ],
        'recover' => [
            'title' => 'Récupérer votre compte',
            'subtitle' => 'Veuillez entrer votre nouveau mot de passe et le confirmer pour terminer la récupération de votre compte.',
            'new_password' => 'Nouveau mot de passe',
            'repeat_new_password' => 'Répéter le nouveau mot de passe',
            'submit' => 'Récupérer le compte',
        ],
        'customise' => [
            'title' => 'Customise your profile',
            'description' => 'Add your social media, choose an emoji, set your location and more',
            'information' => 'Information',
            'preview' => 'Preview',
            'location' => [
                'title' => 'Location',
                'description' => 'Choose which location you would like to add to your profile.',
            ],
            'biography' => [
                'title' => 'About me',
                'description' => 'Write a bio for your profile.',
            ],
            'status' => 'Status',
            'status-toggle' => 'Show my online status',
            'emoji' => 'Emoji',
            'name-history-toggle' => 'Make username history private',
            'name-history-info' => 'Your Minecraft username history is currently',
            'name-history-toggle-on' => 'private',
            'name-history-toggle-off' => 'public',
            'theme' => 'Profile theme',
            'theme-primary' => 'Primary',
            'theme-secondary' => 'Secondary',
        ],
        'link' => [
            'manage' => 'Manage linked Minecraft account',
            'description' => 'See and manage your linked Minecraft account',
            'title' => 'Linked Minecraft account',
            'current' => 'Currently linked Minecraft account.',
            'status' => 'You now have full access to all SkinMC features!',
            'linked' => 'Linked',
            'disconnect' => 'Disconnect',
            'disconnect-title' => 'Disconnect Minecraft account',
            'disconnect-info' => 'Are you sure you would like to disconnect your Minecraft account?',
            'disconnect-features' => 'You will lose access to commenting, customisation and other features which require a linked Minecraft account. To use these again you will be required to link a Minecraft account.',
            'disconnect-following' => 'Disconnecting your Minecraft account will permanently remove all your followed profiles.',
            'disconnect-posts' => 'Your created feed posts and liked will be deleted.',
            'can-not-undo' => 'This can\'t be undone.',
            'are-you-sure' => 'Are you sure?',
            'confirm' => 'Yes, confirm disconnect',
            'cancel' => 'No, cancel',
            'success' => 'Your account was successfully disconnected!'
        ],
        'finish-setup' => [
            'title' => 'Finish account setup',
            'description' => 'Finish setting up your account, and get full access to all features by linking your Minecraft account to SkinMC.',
            'link' => 'Link Minecraft account',
            'get-started' => 'Get started',
            'skip' => 'Skip',
            'claim' => 'Claim your profile',
            'customise' => 'Customise your page',
            'social' => 'Add social links',
            'comment' => 'Access to comment system',
            'direct_message' => 'Send direct messages',
            'feed' => 'Post status updates to the feed',
            'follow' => 'Follow your friends',
            'badge' => 'Badge displayed on your profile',
            'cape' => 'Custom Minecraft cape',
            'backup' => 'Automatic skin backup',
            'more' => 'And more...'
        ],
        'skins' => [
            'title' => 'Manage skins',
            'toggle' => 'Skin visibility toggled',
        ],
        'invite' => [
            'title' => 'My invites',
            'headline' => 'Invite your friends',
            'info' => 'Create an invite code to share with your friend. Once they accept it, you\'ll both earn some extra XP!',
            'description' => 'Create an invite for your friends and you\'ll both earn some extra XP.',
            'generate' => 'Create invite code',
            'empty' => 'You haven\'t created any invites yet.',
            'code' => 'Code',
            'expiry' => 'Each code works once.',
            'status' => [
                'title' => 'Status',
                'pending' => 'Pending',
                'accepted' => 'Accepted'
            ],
            'add_invite' => [
                'button' => 'Have an invite?',
                'title' => 'Add an invite code',
                'redeem' => 'Redeem invite',
            ],
            'share' => 'Send your friend an invite link'
        ],
        'emoji' => [
            'title' => 'SkinMC Emoji',
            'introducing' => 'Introducing',
            'info' => 'Customise your profile with emoji. Unlock more as you level up.',
            'unlocked_at' => 'Unlocked at level :level',
            'unlocks_at' => 'Reach level :level to unlock',
            'turn_off' => 'Show emoji'
        ]
    ],
    'notifications' => [
        'title' => 'Notifications',
        'view_all' => 'View all',
        'view_all_notifications' => 'View all notifications',
        'image' => 'Notification photo',
        'archived' => 'Archived',
        'inbox' => 'Inbox',
        'empty' => [
            'title' => 'You\'re up to date!',
            'text' => 'New notifications will show up here.',
            'text-archived' => 'Archived notifications will show up here.',
        ],
        'action' => [
            'archive' => 'Move to archive',
            'unarchive' => 'Unarchive',
            'open' => 'Tap to open',
        ],
        'toast' => [
            'archive' => 'Notification moved to archive',
            'unarchive' => 'Notification moved to inbox',
            'undo' => 'Undo',
        ]
    ],
    'error' => [
        'offline' => [
            'title' => 'No internet',
            'subtitle' => 'Your internet was disconnected. Please check your connection and reload the page to try again.',
            'try_again' => 'Try again'
        ],
        '404' => [
            'title' => '404 — Page not found.',
            'subtitle' => 'Hm, it looks like nothing was found at this location. Maybe try going back, or start a new search?',
            'try_again' => 'Back home'
        ],
    ],
    'heads' => [
        'list' => [
            'meta' => [
                'title' => 'Minecraft heads database',
                'description' => 'Explore the database of Minecraft heads to decorate your world with, or generate your own give command. View official heads, player heads and custom heads that feature textures which never change.'
            ],
            'header' => [
                'title' => 'Minecraft heads',
                'subtitle' => 'Explore our database of Minecraft heads to decorate your world, or generate your own give command. Player heads show the current skin worn by a user, and can change as the user updates their skin. Custom heads are linked to the Mojang skin file and never change. Custom heads must be summoned using a command block as the command is very long.',
            ],
            'count' => [
                'heads' => ':heads head|:heads heads',
            ],
            'customheads' => [
                'title' => 'Custom heads',
                'description' => 'Custom heads use the direct path to the texture file on the Mojang servers. Hence textures will never be deleted and the heads never change.',
                'version' => 'Minecraft 1.8 or later',
            ],
            'playerheads' => [
                'title' => 'Player heads',
                'description' => 'Player heads use the current skin texture of a Minecraft player. As they are username based, when the player changes their name or skin, the head changes.',
                'version' => 'All Minecraft versions',
            ]
        ],
    ],
    'mod' => [
        'title' => 'SkinMC Mod: Free custom capes',
        'headline' => 'Introducing the SkinMC Mod for more customisation',
        'description' => 'Giving back to the Minecraft community, with a free mod which enables players more customisation with custom capes, available and visible for anyone using the mod.',
        'download' => 'Download now',
        'download-title' => 'Download the mod',
        'requires' => 'Requires',
        'select-version' => 'Choose your Minecraft version',
        'get-started' => 'Getting started is simple',
        'step-1' => '1. Get the mod',
        'step-1-detail' => 'Install Fabric, then download the mod for your game version and install it by putting the jar in your mods folder.',
        'step-2' => '2. Link your account',
        'step-2-detail' => 'If you haven\'t already, sign up/in and connect your Minecraft account to SkinMC.',
        'step-3' => '3. Upload your cape',
        'step-3-detail' => 'Go to your account and upload your custom cape. It will be visible in-game.',
        'all-versions' => 'All versions',
        'latest' => 'Latest',
        'logged-in' => 'Upload your cape',
        'mirror' => 'Mirror',
        'download-via' => 'Download via:',
        'curseforge' => 'CurseForge',
    ],
    'app' => [
        'title' => 'SkinMC Android App',
        'headline' => 'Say hello to the SkinMC Android App.',
        'play-store-attribution' => 'Google Play et le logo Google Play sont des marques de Google LLC.',
        'features' => 'Convenient features for on the go',
        'feature-qr' => 'Built in QR-Code scanner',
        'feature-qr-detail' => 'Use the built in QR-Code scanner to easily get a skin from your Desktop to the app, or scan your friends custom profile QR-Code.',
        'feature-files' => 'Saves directly to files',
        'feature-files-detail' => 'With the usage of Android Files Manager, the app can conveniently save Skins, making it easier to apply in Bedrock Edition.',
        'feature-noads' => 'No ads',
        'feature-noads-detail' => 'A clean designed interface, without distractions. Enjoy an Ad-free experience without intrusive annoyances from web to app.',
        'feature-experience' => 'Experience',
        'feature-experience-detail' => 'Enjoy the full SkinMC experience anywhere, with added features. Customise your profile, add your bio, create a fun QR-Code and more!',
        'get-app-headline' => 'Get the SkinMC App',
        'get-app-detail' => 'Your very own Minecraft companion for your Android — available for free.'
    ],
    'random' => [
        'title' => 'Loading random Minecraft skin',
        'description' => 'Loading random Minecraft skin',
        'headline' => 'Please wait...',
        'redirect' => 'You will be automatically redirected. Page not loading?',
        'click-here' => 'Click here',
        'messages' => [
            '1' => 'Loading random Minecraft skin...',
            '2' => 'Digging down...',
            '3' => 'Creeper, aw man...',
            '4' => 'Searching through chests...',
            '5' => 'Did you know the coming skin is completely random?',
            '6' => 'Random skin incoming...',
            '7' => 'One more block...',
            '8' => 'Sorting inventory...',
            '9' => 'Crafting diamond pickaxe...',
            '10' => 'Looking for Herobrine...',
        ],
    ],
    'feed' => [
        'title' => 'Feed',
        'following' => 'Following',
        'sign-up' => 'Sign up or log in to join the conversation.',
        'link-account' => 'Link your Minecraft account to join the conversation.',
        'placeholder' => 'What is happening?',
        'audience' => 'Audience',
        'audience-title' => 'Who can see this?',
        'everyone' => 'Everyone',
        'everyone-info' => 'Anyone on or off SkinMC.',
        'followers' => 'Followers',
        'followers-info' => 'Signed in or members following me.',
        'private' => 'Only me',
        'private-info' => 'Private post only I can see.',
        'submit' => 'Post',
        'like' => 'Like',
        'comment' => 'Reply',
        'share' => 'Share',
        'remaining' => 'Remaining',
        'profile' => 'Posts by :username',
        'posts' => 'All posts',
        'my-posts' => 'My posts',
        'view-all' => 'View all posts',
        'post' => [
            'meta' => ':username on SkinMC: :text',
            'title' => 'Post',
            'created' => 'Status update posted!',
            'confirm-delete' => 'Are you sure you would like to delete this post? It can not be undone.',
            'delete' => 'Delete post',
            'deleted' => 'Your post was deleted.',
        ],
        'follow-suggestions' => 'Follow the team',
        'explore' => 'Explore',
        'hashtag' => 'Hashtag',
    ],
    'private' => [
        'title' => 'Private posts',
        'text' => 'This post is private.'
    ] ,
    'liked' => [
        'title' => 'Liked'
    ],
    'following' => [
        'title' => 'Following',
        'text' => 'Sign in to view this post.'
    ],
    'tags' => [
        'empty' => 'No tags to vote on yet',
        'empty-subtitle' => 'Be the first to add one',
    ],
    'inbox' => [
        'title' => 'Messages',
        'details' => 'Details',
        'message_user' => 'Message',
        'write_message' => 'Write a message',
        'empty' => [
            'no_message_selected' => 'No message selected',
            'open_or_start_conversation' => 'Open a conversation from the message list, or start a new one.',
            'no_messages' => 'No unread messages',
            'start_conversation' => 'Once you start a new conversation, your messages will be displayed here.',
            'conversation' => 'This is the beginning of your conversation with :username.',
            'users' => 'Unable to find any users that match the current query.'
        ],
        'typing' => ':username is typing...',
        'new_message' => 'New message',
        'mark_unread' => 'Mark unread',
        'send_message' => 'Send message',
        'delete_message' => 'Delete message for you',
        'latest_conversations' => 'Latest conversations',
        'delete_conversation' => 'Delete conversation',
        'show_details' => 'Show details',
        'hide_details' => 'Hide details',
        'unread' => 'Unread',
        'deleted' => 'Deleted',
        'report_message' => 'Report message',
        'add_reaction' => 'Add reaction',
        'today' => 'Today',
        'reconnect' => 'Please reconnect your Minecraft account to chat',
        'account_disconnected' => 'This user disconnected their linked Minecraft account.',
        'saved_messages' => 'Saved messages',
        'new_message_to_label' => 'To',
        'external-link-to' => 'This link will take you to',
        'external-link-confirmation' => 'Are you sure you want to go there?',
        'external-link' => 'External link',
        'reply' => 'Reply'
    ],
    'server' => [
        'manage' => [
            'stats' => 'Stats'
        ]
    ],
    'report' => [
        'button' => 'Report',
        'title' => 'Report content',
        'describe' => 'Briefly describe why you are reporting this',
        'select' => 'Select report reason',
        'submit' => 'Submit report',
        'reasons' => [
            'INAPPROPRIATE_CONTENT' => 'Inappropriate content',
            'SPAM' => 'Spam',
            'HARASSMENT' => 'Harassment',
            'OTHER' => 'Other',
        ]
    ],
    'leaderboard' => [
        'title' => 'Leaderboard',
        'description' => 'View the SkinMC leaderboard of users.',
        'headline' => 'Top 10',
        'all-time-invites' => 'All time invites',
        'all-time-xp' => 'All time XP',
        '30-day-xp' => '30 days XP'
    ],
];
