<?php

return [
    'skins' => 'Utseenden',
    'avatars' => 'Avatarer',
    'editor' => 'Redigerare',
    'heads' => 'Huvuden',
    'capes' => 'Mantlar',
    'servers' => 'Servrar',
    'achievement' => 'Framsteg',
    'armor' => 'Rustningsställ',
    'banners' => 'Banderoller',
    'banner' => 'Banner Editor',
    'banner_gallery' => 'Banner Gallery',
    'profile' => 'Min profil',

    'generators' => 'Generatorer',

    // Navigation dropdowns
    'feed' => 'Feed',
    'discover' => 'Discover',
    'mods' => 'Mods',
    'shaders' => 'Shaders',
    'resource_packs' => 'Resource Packs',
    'modpacks' => 'Modpacks',
    'datapacks' => 'Data Packs',
    'plugins' => 'Plugins',

    'logout' => 'Logga ut',
    'register' => 'Registrera dig',
    'login' => 'Logga in',
    'about' => 'Om oss',
    'contact' => 'Kontakta',
    'faqs' => 'Vanliga frågor',

    'minecraft_name' => 'Minecraft namn',
    'minecraft_uuid' => 'Minecraft UUID',
    'what' => 'Vad',
    'recent_searches' => 'Senaste sökningar',
    'username' => 'Användarnamn',
    'uuid' => 'UUID',
    'search' => 'Sök',
    'search_placeholder' => 'Prova',
    'search_placeholder_uuid' => 'Ange UUID',
    'start_search' => 'Börja söka',
    'cancel_search' => 'Avbryt',
    'search_type' => 'Söktyp',
    'search_type_all' => 'Alla resultat',
    'profiles' => 'Profiler',
    'view_skin' => 'Visa utseende',
    'edit_skin' => 'Redigera utseende',
    'make_avatar' => 'Skapa avatar',
    'find_heads' => 'Hitta spelarhuvuden',
    'no_results_found' => 'No suggestions yet. Hit Enter to look it up.',

    'home' => 'Hem',
    'help' => 'Hjälp',
    'tools' => 'Verktyg',
    'more-tools' => 'Fler verktyg',
    'skin_viewer' => 'Utseendevisare',
    'avatar_maker' => 'Avatarskapare',
    'collections' => 'Samlingar',
    'popular_skins' => 'Populära utseenden',
    'cartoon_skins' => 'Tecknade utseenden',
    'animal_skins' => 'Djurutseenden',
    'community' => 'Community',
    'imprint' => 'Imprint',
    'cookies' => 'Kakor',
    'terms' => 'Användarvillkor',
    'privacy' => 'Sekretesspolicy',
    'app' => 'App',
    'mod' => 'Mod',
    'totem' => 'Totem',
    'cube' => 'Cube',
    'new' => 'New',

    'feedback' => 'Feedback',
    'status' => 'Status',
    'recent_searches_placeholder' => 'När du börjar söka visas dina tidigare sökningar här.',
    'recent_views_placeholder' => 'Efter att du har besökt några profiler kommer de senaste visas här.',
    'moderate' => 'Moderera',
    'listings' => 'Listor',
    'add' => 'Lägg till',

    // Autocomplete types
    'autocomplete' => [
        'profile' => 'Profile',
        'server' => 'Server',
        'project' => 'Project',
        'skin_tag' => 'Skin Tag',
        'server_category' => 'Server Category',
        'modrinth_category' => 'Project Category',
    ],

    'theme' => [
        'title' => 'Theme',
        'dark' => 'Mörk',
        'light' => 'Ljus',
        'auto' => 'Auto',
    ],

    'language' => 'Language',
];
