<?php

return [
    'login' => [
        'title' => 'ログイン',
        'email' => 'メールアドレス',
        'password' => 'パスワード',
        'button' => 'ログイン',
        'editor_save_context' => "Log in to save your skin to the gallery. Your work won\\'t be lost.",
        'forgot' => 'パスワードをお忘れですか？',
        'reset' => 'リセット',
        'register' => 'まだアカウントを持っていませんか？',
        'signup' => 'サインアップ',
        'google' => 'Googleで続ける',
        'microsoft' => 'Microsoftで続ける',
        'facebook' => 'Facebookで続ける',
        'twitter' => 'X（旧Twitter）で続ける',
        'divider' => 'または',
    ],
    'signup' => [
        'title' => 'サインアップ',
        'existing' => '既にアカウントをお持ちですか？',
        'button' => '同意して続ける',
        'terms_by_selecting' => '選択',
        'terms_agree_to' => '、SkinMCを同意します',
        'terms_acknowledge' => 'を認める。',
    ],
    'recover' => [
        'title' => 'アカウントを復元',
        'description' => 'パスワードを忘れましたか? メールアドレスを入力して復元してください。',
        'button' => 'リカバリーメールを送信',
        'found' => 'パスワードを覚えだしましたか？',
    ],
    'logout' => [
        'title' => 'ログアウト',
        'description' => 'SkinMCアカウントからログアウトしてもよろしいですか？',
        'logout' => 'ログアウト',
        'cancel' => 'キャンセル',
    ],
    'profile_qrcode' => [
        'title' => 'QRコードを読み取る',
        'done' => '完了',
    ],
    'language' => [
        'title' => '言語',
        'description' => '言語を選択してください',
        'contribute' => '貢献',
        'contribute_add' => '翻訳を追加',
        'updated' => '言語を設定しました',
    ],
    'copied' => 'クリップボードにコピーされました！',
    'close' => '閉じる',
    'feedback' => [
        'title' => 'フィードバック',
        'type' => [
            'select' => 'フィードバックの種類を選択',
            'label' => 'フィードバックタイプ',
            'comment' => 'コメント',
            'question' => '質問',
            'bug' => 'バグ報告',
            'feature' => '新しい機能の提案',
        ],
        'submit' => '送信',
        'nps' => '0点から10点までの評価で、SkinMCを友人に勧めたいと思いますか？',
        'success' => [
            'title' => 'ありがとうございました！',
            'message' => 'あなたのメッセージは送信されました！さらに質問がある場合は、Discordに参加するか、別のメッセージを送信してください。',
        ],
    ],
];
