<?php

return [
    'skins' => 'スキン',
    'avatars' => 'アバター',
    'editor' => 'エディター',
    'heads' => 'Head',
    'capes' => 'マント（ケープ）',
    'servers' => 'サーバー',
    'achievement' => '実績',
    'armor' => '防具立て',
    'banners' => 'バナー',
    'banner' => 'Banner Editor',
    'profile' => 'マイプロフィール',

    'generators' => '生成',

    // Navigation dropdowns
    'feed' => 'Feed',
    'discover' => 'Discover',
    'mods' => 'Mods',
    'shaders' => 'Shaders',
    'resource_packs' => 'Resource Packs',

    'logout' => 'ログアウト',
    'register' => 'サインアップ',
    'login' => 'ログイン',
    'about' => 'About',
    'contact' => 'お問い合わせ',
    'faqs' => 'よくある質問',

    'minecraft_name' => 'Minecraft 名',
    'minecraft_uuid' => 'Minecraft UUID',
    'what' => 'What',
    'recent_searches' => '最近の検索',
    'username' => 'ユーザー名',
    'uuid' => 'UUID',
    'search' => '検索',
    'search_placeholder' => 'お試しください',
    'search_placeholder_uuid' => 'UUIDを入力',
    'start_search' => '検索を開始',
    'cancel_search' => 'キャンセル',
    'search_type' => '検索タイプ',
    'search_type_all' => 'すべての結果',
    'profiles' => 'プロフィール',
    'view_skin' => 'スキンを表示',
    'edit_skin' => 'スキンを編集',
    'make_avatar' => 'アバターを作成',
    'find_heads' => 'プレイヤーのヘッドを見つける',

    'home' => 'ホーム',
    'help' => 'ヘルプ',
    'tools' => 'ツール',
    'more-tools' => '他のツール',
    'skin_viewer' => 'スキンビューアー',
    'avatar_maker' => 'アバターメーカー',
    'collections' => 'コレクション',
    'popular_skins' => '人気のスキン',
    'cartoon_skins' => '漫画のスキン',
    'animal_skins' => '動物のスキン',
    'community' => 'コミュニティ',
    'imprint' => 'インプリント',
    'cookies' => 'Cookie',
    'terms' => '利用規約',
    'privacy' => 'プライバシーポリシー',
    'app' => 'アプリ',
    'mod' => 'Mod',
    'totem' => 'トーテム',
    'cube' => 'Cube',
    'new' => 'New',

    'feedback' => 'フィードバック',
    'status' => 'ステータス',
    'recent_searches_placeholder' => '検索をはじめると、過去の検索結果がここに表示されます。',
    'recent_views_placeholder' => 'いくつかのプロフィールを訪問した後、過去に訪問したプロフィールがここに表示されます。',
    'moderate' => 'モデレート',
    'listings' => '一覧',
    'add' => '追加',

    'theme' => [
        'title' => 'Theme',
        'dark' => 'ダーク',
        'light' => 'ライト',
        'auto' => 'Auto'
    ],
];
