<?php

return [
    'auth' => [
        'login' => [
            'title' => 'SkinMCへようこそ！',
        ],
        'register' => [
            'title' => 'SkinMCにサインアップ',
            'subtitle' => 'まずはアカウントを作成して、フルアクセスをお試しください。',
        ],
    ],

    'home' => [
        'hero_slogan' => 'Minecraftのスキンのためのあなたの場所',
        'hero_slogan_alt_1' => 'Everything Minecraft. One place.',
        'hero_slogan_alt_2' => 'Where Minecrafters meet.',
        'hero_cta' => '私を驚かせて',
        'hero_explore_cta' => 'スキンを探索',
        'skin_viewer' => 'スキンビューアー',
        'skin_viewer_detail' => ':count個のスキンを見る',
        'skin_editor' => 'スキンエディター',
        'skin_editor_detail' => '自分のスキンをデザインする',
        'avatar_maker' => 'アバタージェネレーター',
        'avatar_maker_detail' => 'あなただけのプロフィール画像を生成しよう',
        'trending' => 'トレンド',
        'minecraft_skin' => 'Minecraft スキン',
        'favourite' => 'お気に入り',
        'collections' => 'コレクション',
        'collections_detail' => '毎回キュレートされたマインクラフトスキン',
        'creations_title' => 'Skin creations',
        'creations_description' => 'Browse and upload custom Minecraft skin creations.',
        'about_skinmc' => 'SkinMCについて',
        'about_find' => 'スキンを探す',
        'about_find_detail' => '次の新しいスキンを検索、表示、ダウンロードするには、任意の Minecraft ユーザー名を検索します。',
        'about_download' => 'ダウンロードまたは編集',
        'about_download_detail' => 'お気に入りのスキンを見つけました。お気に入りに追加したり、編集したり、ダウンロードしたりして自分のスキンにしましょう。',
        'about_platform' => 'クロスプラットフォーム',
        'about_platform_detail' => '外出先でスキンを取りたいですか？QRコードをスキャンし、MinecraftのPE用に携帯電話に画像を保存してください。',
        'meta' => [
            'title' => 'Minecraft スキンビューアー',
            'description' => 'Minecraft のスキンを表示してダウンロードし、キュレーションされたコレクションで最高のスキンを発見し、ユーザー名の可用性と履歴を確認します!',
        ],
        'recently_viewed' => '最近見たもの',
        'explore_title' => '新しい機能！',
        'explore' => '新しいアイデアやツールを見つけよう',
        'servers_browse' => 'サーバーを検索',
        'servers' => '最高のMinecraft サーバーを発見する',
        'servers_new_upcoming' => 'New & upcoming servers',
        'servers_new_upcoming_browse' => 'Find fresh servers with smaller communities that are currently online.',
        'servers_upcoming_players' => 'players',
        'servers_upcoming_badge' => 'New',
        'heads' => 'Minecraft ヘッド',
        'head_description' => 'Minecraft ヘッドのデータベースを閲覧したり、新しいヘッドを作成したりできます。',
        'achievement' => '実績ジェネレーター',
        'achievement_detail' => '自分だけのオリジナルな実績を作りましょう',
        'continue' => 'ブラウジングを続ける',
        'totem' => 'Minecraft Totem Generator',
        'totem_description' => 'Create a custom Minecraft resource pack with a Totem of Undying from any skin.',
        'banner' => 'Minecraft Banner Generator',
        'banner_description' => 'Generate and preview custom Minecraft banners and patterns.',
        'capes' => 'Minecraft Capes',
        'capes_description' => 'Browse the largest collection of Minecraft capes, or create your own.',

    ],
    'profile' => [
        'verified' => '確認済みのプロフィール',
        'minecraft_profile' => 'Minecraft プロファイル',
        'show_qr_code' => 'QRコードを表示',
        'favourite' => 'お気に入り',
        'user_title' => ':username Minecraft スキン',
        'user_views' => ':viewed :views time|viewed :views times',
        'uuid' => 'UUID',
        'copy' => 'コピー',
        'link' => 'リンク',
        'skin_history' => 'スキンの履歴 (:skins)',
        'username_history' => 'ユーザー名の履歴',
        'username_history_name' => '名前',
        'username_history_timestamp' => '変更日時',
        'username_history_initial_name' => '最初の名前',
        'user_downloads' => ':downloads|ダウンロード数',
        'download_skin' => 'スキンをダウンロード',
        'apply_skin' => 'スキンを適用',
        'capes' => 'マント',
        'claim_profile' => 'あなたは:usernameですか？プロフィールを確認してカスタマイズしましょう！',
        'claimed' => '要求されたプロフィール',
        'meta_description' => ':username のスキンを閲覧やダウンロードしたりUUID、ユーザー名の履歴、詳細な統計情報などを見ることができます。',
        'created_at' => '更新日: :changed_at',
        'skins' => [
            'meta_title' => ':username のMinecraft スキンの履歴',
            'meta_description' => ':username のMinecraftスキンの履歴と以前使用したスキンを表示します。履歴を使用して、古いスキンや過去に使用したスキンを閲覧したり、バックアップやロールバックを行ったり、新しいスキンを収集することができます。',
            'title' => 'Minecraft スキンの履歴',
        ],
        'qr_code' => [
            'meta_title' => ':username のQRコード',
            'meta_description' => ':username のカスタムプロフィールのQR コード',
        ],
        'sub_nav' => [
            'skin' => 'スキン',
            'about' => 'About',
            'usernames' => 'ユーザー名',
            'head' => 'Head',
            'comments' => 'コメント',
        ],
        'cape' => 'マント',
        'elytra' => 'エリトラ',
        'nametag' => 'Name tag',
        'animation' => 'アニメーション',
        'rotation' => '回転',
        'none' => 'なし',
        'idle' => '待機',
        'walk' => '歩く',
        'run' => '走る',
        'fly' => '飛ぶ',
        'follow' => 'フォロー',
        'following' => 'フォロー中',
        'unfollow' => 'フォロー解除',
        'followers' => 'フォロワー',
        'toast' => [
            'following' => ':username さんをフォローしました！',
            'follow-self-error' => '申し訳ありませんが、自分自身をフォローできません。',
            'unfollowed' => ':username さんをフォロー解除しました',
        ],
        'edit' => 'プロフィールを編集',
        'joined' => '参加済み',
        'role' => 'Role',
        'server-fav-list-empty' => 'Looks like :username hasn\'t got any favourite servers yet. Once :username has saved a server as their favourite, you can see it here.',
        'server-own-list-empty' => 'Looks like :username hasn\'t got any servers yet. Once :username has listed a server, you can see it here.',
        'capes-list-empty' => 'Looks like :username isn\'t wearing any capes yet. Once :username is wearing a cape, you can see it here.',
        'feed-own-list-empty' => 'Looks like you haven\'t posted anything to the feed yet! Once you post, you can see your posts here.',
        'feed-list-empty' => 'Hmm, it seems like :username hasn\'t posted anything to the feed yet. Once :username posts something you can see it here.',
        'following-own-list-empty' => 'まだ誰もフォローしていないようですね！フォローを始めたら、ここで見ることができます。',
        'following-list-empty' => 'うーん、:username さんは誰もフォローしていないようです。username さんがフォローを始めたら、ここに表示されます。',
        'followers-own-list-empty' => 'あなたのプロフィールをフォローし始めると、ここに表示されます。',
        'followers-list-empty' => 'うーん、:username さんは誰もフォローしていないようです。最初に:username さんをフォローしましょう。フォローされるとここで見ることができます。',
        'render' => 'レンダラー',
        '3d' => '3D レンダリング',
        '2d' => '2D レンダリング',
        'name-history-info' => 'ユーザー名の履歴はなくなります。 Mojangは2022年9月13日に名前履歴APIへのアクセスをサポートしなくなり、正確な名前履歴が利用できなくなりました。 自分の名前の履歴を非表示にしたい場合は、プロフィールを登録して設定に移動して非表示に設定できます。',
        'edit-skins' => 'スキン履歴を編集',
        'hide-skin' => 'スキンを隠す',
        'show-skin' => 'スキンを表示',
        'edit-skin' => 'スキンを編集',
        'servers' => [
            'title' => ':username\'s servers',
        ],
        'cape-list' => [
            'title' => ':username\'s capes',
        ],
    ],
    'skin' => [
        'meta' => [
            'title' => ':username のMinecraft スキン',
            'description' => 'Minecraft スキン。スキンをダウンロードして表示し、同じスキンを着ているプレイヤーを確認できます。',
            'tags' => ':username Minecraft スキン, :username スキン, Minecraft スキン, :username カスタムMinecraft スキン, スキンをダウンロード、 同じスキンを持つプレーヤー',
        ],
        'title' => ':username のMinecraft スキン',
        'head' => '頭の入手コマンド',
        'head_info' => 'コマンドブロックで使用する',
        'first_wearing' => 'このスキンを着用した最初のプレイヤー:',
        'profiles' => ':profiles プロフィール',
        'profiles_title' => ':profile このスキンを使用しているプロファイル',
        'screenshot' => 'Screenshot',
    ],
    'skins' => [
        'meta' => [
            'title' => 'ページ :current — すべての Minecraft スキン',
            'description' => ':last ほどのカスタムスキンをご覧ください！そして、お気に入りのスキンをダウンロードしよう！',
            'tags' => ':username Minecraft スキン, :username スキン, Minecraft スキン, :username カスタムMinecraft スキン, スキンをダウンロード、 同じスキンを持つプレーヤー',
            'tags-title' => ':tag Minecraft スキン',
            'tags-description' => ':last ページにわたる:total 個の:tag Minecraft スキンのリストを見て、お気に入りの:tagスキンをダウンロードしよう！',
            'tags-metatags' => ':tag Minecraft スキン, :tag スキン, Minecraft スキン, :tag カスタムMinecraftスキン, ダウンロード:tag スキン, Minecraftの:tag スキン',
        ],
        'title-skin-tags' => 'タグ付けされたMinecraft スキン',
        'subtitle' => 'ページ :current の :last から :total Minecraft Skins',
        'subtitle-skin-tags' => 'ページ :current の :last から :total タグ付けされたMinecraft Skins',
        'sort_by' => '並べ替え',
        'latest' => '最新のスキン',
        'most_profiles' => '最も使用されているスキン',
        'profiles_today' => '今日最も使用されている順',
        'profiles_this_week' => '今週最も使用されている順',
        'profiles_this_month' => '今月最も使用されている順',
        'default' => 'デフォルトの並べ替え',
        'this_month' => '今月追加された順',
        'this_week' => '今週追加された順',
        'today' => '今日追加された順',
        'random' => 'ランダム',
        'similar' => '似ているスキン',
        'no_similar_skins' => '似たようなスキンは見つかりませんでした。',
        'favorite' => ':count 個のお気に入り',
    ],
    'skin-tags' => [
        'faq' => 'タグとは？',
        'about' => 'タグはスキンに関連するカテゴリを追加するものです。タグを追加することで、より多くのスキンを簡単に発見することができます！',
        'guidelines' => [
            'good' => [
                'title' => '良いタグはこのようにしたら良いです',
                'short' => '短い',
                'descriptive' => 'スキンに合うタグ',
                'spelled' => '正しいスペル',
            ],
            'bad' => [
                'title' => '悪いタグの例',
                'general' => '一般的すぎる',
                'specific' => '長すぎる',
                'too-many-tags' => 'タグは他に分けなければならない',
                'spelling' => ':example でなければなりません',
            ],
        ],
        'toast' => [
            'added' => 'タグ「:tag」を追加しました',
            'removed' => 'タグ「:tag」は削除されました',
            'upvote' => '「:tag」を賛成しました',
            'downvote' => '「:tag」を反対しました',
        ],
        'vote' => [
            'up' => '賛成',
            'down' => '反対',
            'remove' => '投票を削除',
        ],
    ],
    'contact' => [
        'contact' => 'お問い合わせ',
        'email' => 'ご質問は、 <a href="mailto:support@skinmc.net">support@skinmc.net</a> までお気軽にお問い合わせください。',
        'faq' => '<a href=":link">FAQページ</a>に回答がある場合は、そちらをご覧ください。',
        'other' => 'その他のお問い合わせ方法',
        'other_discord' => 'Discordサーバーに参加して、他の人とつながり、ゲームについてチャットしたり、お気に入りのパックを共有したり、コミュニティからヘルプを得たりしましょう。',
        'other_twitter' => 'ツイッターをフォローして、新しいアップデートや機能のリリース、今週のスキンなどをご覧ください。',
        'other_instagram' => 'インスタグラムでSkinMCをフォローして、新しいマインクラフトスキンや画像を見つけましょう。',
        'other_bluesky' => 'Follow SkinMC on Bluesky to see when a new update or feature is released, see the skin of the week and more.',
    ],
    'about' => [
        'intro' => '<span></span> <span>プラットフォーム</span> <span>for</span> <span>Minecraft</span> <span>スキン。</span>',
        'header_credit' => 'イラストレーション「叙事詩ネザーバトル」によるもの',
        'info' => 'すべてを追跡します。',
        'info_explainer' => 'プレイヤーの名前の歴史を表示し、彼らの以前のスキンを参照してください、友人としてそれらを追加し、スキンをダウンロードし、さらに詳細な統計を取得します。',
        'card_find_title' => '任意のMinecrafterを見つける',
        'card_find_detail' => '任意のプレイヤーユーザー名または選択したUUIDを検索することから始めましょう。',
        'card_view_title' => '表示、保存、編集',
        'card_view_detail' => 'お気に入りのスキンを見つけましたか？エディターを使って保存して自分のスキンにしましょう。',
        'card_claim_title' => '確認する',
        'card_claim_detail' => 'あなたのMinecraftアカウントをリンクし、あなたのプロフィールを主張してクールな新機能をアンロックしましょう！',
        'card_customise_title' => 'プロフィールをカスタマイズ',
        'card_customise_detail' => '検証済みのプレイヤーは、ソーシャルメディアのリンクを追加して独自のプロフィールを作成できます。',
        'card_friends_title' => '友達を追加',
        'card_friends_detail' => 'SkinMCでフレンドとつながり、プロフィールにフレンドリストを表示します。',
        'card_history_title' => 'ユーザー名とスキンの履歴',
        'card_history_detail' => '高度な検索を使用して、プレイヤーのユーザー名/スキン履歴を見つけて表示します。',
        'founders' => '創設者たち',
        'founders_cofounder' => 'SkinMCの共同創設者',
        'head_of_design' => '設計責任者',
        'head_of_code' => 'コード責任者',
        'feedback' => 'フィードバックを送信',
        'faq' => 'マインクラフト、スキンなどについてのご質問はFAQの回答をご覧ください。',
        'faq_link' => 'FAQセンターにアクセスする',
        'contact' => 'ご質問やご質問がありますか? 気軽にお問い合わせください。',
        'contact_link' => 'お問い合わせ',

    ],
    'faq' => [
        'title' => 'よくある質問',
        'subtitle' => 'よくある質問',
        'help' => 'さらにヘルプが必要ですか？',
        'discord' => 'Discordサーバーに参加して他のMinecraftプレイヤーとチャットしましょう。',
        'contact' => 'お問い合わせ',
        'q' => [
            'change_skin_t' => 'Minecraft のスキンを変更するにはどうすればいいですか?',
            'change_skin' => '
<p>スキンを変更するには</p>
                <ol>
                    <li><a href="https://www.minecraft.net/ja-jp/login" target="_blank" rel="nofollow">https://www.minecraft.net/ja-jp/login</a>にてMicrosoftアカウントでログインする。</li><li>ログイン後<b>"スキンを変更する"</b>を押し</li><li>次に、お好みのモデルを選択し、お好みのスキンをアップロードします。</li>
                </ol>',
            'change_username_t' => 'Minecraft のユーザー名を変更するにはどうすればいいですか?',
            'change_username' => '
                <p>ユーザー名を変更するには</p>
                <ol>
                    <li><a href="https://www.minecraft.net/ja-jp/login" target="_blank" rel="nofollow">https://www.minecraft.net/ja-jp/login</a>にてMicrosoftアカウントでログインする。</li>
                    <li><b>プロフィール名</b>を選択する。</li>
                    <li>テキストフィルドに好きなユーザー名を打つ。</li>
                    <li>ユーザー名を確認したら、"プロフィール名を変更する"をクリックすることで変更できます!</li>
                </ol>',
            'dl_t' => 'Minecraft スキンをダウンロードするにはどうすればいいですか?',
            'dl' => '
                <p>任意のMinecraftスキンをダウンロードするには</p>
                <ol>
                    <li>検索バーを押し、スキンをダウンロードしたいプレイヤーのユーザー名を入力してください。</li>
                    <li>プロフィールページでは、スキンをプレビューすることができます。</li>
                    <li>プレビューの下にある<strong>スキンをダウンロード</strong>ボタンをクリックする。</li>
                </ol>',
            'submit_q' => 'コレクションにスキンを出すにはどうすればよいですか？',
            'submit_a' => '<p>以下のフォームに、コレクションに追加したいユーザー名とそのカテゴリーをご記入ください。<a href="https://forms.gle/f4Jh5RpGfsHAZ5xE8" target="_blank">Collection submission form</a>',
            'mcpe_t' => 'Minecraft PEでスキンを使用することはできますか?',
            'mcpe' => '
                <p>Minecraft スマホ版でスキンを使用するには、次のようにしてください</p>
                <ol>
                    <li>スマートフォンでSkinMC.netを開き、検索バーをタップします。</li>
                    <li>ダウンロードしたいプレーヤーのユーザー名を入力してください。</li>
                    <li>プレビューの下にある<strong>スキンをダウンロード</strong>ボタンをタップします。</li>
                    <li>Minecraftを開き、右側の<strong>Profile</strong>をタップします。</li>
                    <li><strong>+</strong>をタップするかキャラクターを編集し"クラシックスキンタブ "に移動する。</li>
                    <li>「所有」→「インポート」→「新しいスキンを選択」をタップ</li>
                </ol>',
            'change_times_t' => 'どのくらいの頻度でユーザー名を変更できますか?',
            'change_times' => '<p>Minecraftのユーザー名を <strong></strong> <strong>30 日</strong>に 1 回変更できます。</p>',
            'available_t' => '私がユーザー名を変更した後、他の人がそれを主張できるようになるのはいつですか?',
            'available' => '<p>以前のユーザーネームに戻したい場合は、<strong>30日後に戻すことができます</strong>。それ以外の人は、あなたの古いユーザー名を変更できるようになるまで、さらに<strong>7日間</strong>(変更後37日間) 待つ必要があります。 </p>',
            'username_history_t' => 'ユーザー名の履歴を削除していただけますか。',
            'username_history' => '
                <p>ユーザー名の履歴データはMojangから提供されているため、ユーザー名の履歴を削除することはできません。Mojangは以前、彼らの意図は以前のユーザー名が見られることであり¹、一般ユーザーがこの情報に直接アクセスできる方法を提供することであると述べています²。</p>
                <p class="font-14">¹<a href="https://help.minecraft.net/hc/en-us/articles/360034636712-Minecraft-Usernames" target="_blank" rel="noreferrer">https://help.minecraft.net/hc/en-us/articles/360034636712-Minecraft-Usernames</a></p>
                <p class="font-14 mb-0">²<a href="https://twitter.com/dinnerbone/status/554739042529849345" target="_blank" rel="noreferrer">https://twitter.com/dinnerbone/status/554739042529849345</a> (2年前にポスト: <a href="http://archive.is/TeAyj" target="_blank" rel="noreferrer">http://archive.is/TeAyj</a>)
                </p>',
        ],
    ],
    'avatars' => [
        'start' => [
            'title' => '自分の Minecraft アバターを作成する',
            'subtitle' => 'Minecraft のアバタージェネレーターを使用して、任意のスキンから楽しいアバターを作成します!',
            'avatar_face' => '顔スタイルのアバター',
            'avatar_bust' => 'バストスタイルのアバター',
            'avatar_cube' => 'キューブスタイルのアバター',
            'avatar_head3d' => '3D headshot',
            'avatar_bust3d' => '3D bust',
        ],
        'user' => [
            'title' => 'スキンを選択',
            'subtitle' => '生成したいアバターのMinecraftのユーザー名を入力してください',
            'form_label' => 'Minecraft ユーザー名',
            'form_submit' => '続ける',
        ],
        'output' => [
            'title' => 'プレビューと保存',
            'subtitle' => '新しいマインクラフトのアバターをお楽しみください',
            'download_info' => '結果に満足していますか？新しいアバターをここからダウンロードして使い始めましょう',
            'download_button' => 'アバターをダウンロード',
            'avatar_style' => 'アバターのスタイル',
            'skin_username' => 'スキンユーザー名',
            'change' => '変更',
            'generate' => '生成',
            'avatar_colour' => '背景色',
            'avatar_colour_palette' => 'パレット',
            'avatar_colour_basic' => '基本',
            'show_nametag' => 'Show nametag',
            'loading_3d' => 'Loading 3D viewer…',
        ],
        'meta' => [
            'title' => 'Minecraft アバターの生成',
            'description' => 'Minecraft アバターメーカー：Minecraft スキンを使用してカスタム Minecraft プロフィール画像を作成します',
        ],
    ],
    'totem' => [
        'title' => 'カスタム トーテム',
        'subtitle' => 'トーテムジェネレーターを使って、トーテムに好きなスキンが入ったカスタムリソースパックを作成できます。',
        'download_info' => 'プレビューをお楽しみいただけましたか？カスタムリソース パックを保存するには、Minecraft のバージョンを選択してください',
        'download_failed' => 'Could not load skin image. Check the username or try uploading an image.',
        'base64_size' => 'The image must be less than 256KB.',
        'meta' => [
            'title' => 'カスタムトーテムジェネレーター',
            'description' => 'カスタムトーテム：自分や他のプレイヤーのスキンを使って、不死のトーテムを含むカスタムリソースパックを生成して作成します。',
        ],
        'type' => [
            'mini' => 'あなたのスキンのミニバージョン！',
            'full' => 'あなたのフルバージョンのスキンです！',
            'model3d' => 'あなたのスキンの3Dモデル！',
            'add_designs' => 'もっとデザインを見たいですか？こちらからデザインをご提案ください',
        ],
    ],
    'achievement' => [
        'header' => [
            'title' => '独自の Minecraft 実績を作成する',
            'subtitle' => 'Minecraft アチーブメントジェネレーターを使用して、独自のカスタム実績を作成し、あなたが好きなことにあなたの進歩を示す使用してください!',
        ],
        'generator' => [
            'yellow_text' => '黄色のテキスト',
            'white_text' => '白のテキスト',
            'choose_icon' => 'アイコンを選択',
            'face' => 'アイコンの代わりに Minecraft の顔',
            'form_submit' => 'ダウンロード',
            'form_label' => 'Minecraft ユーザー名',
            'download' => 'ダウンロード',
            'embed' => '埋め込み',
            'embed_copy' => 'コピー',
        ],
        'meta' => [
            'title' => 'Minecraft 実績ジェネレーター',
            'description' => '実績作成者でカスタム Minecraft の実績と進歩を生成します。 画像を直接ダウンロードし、フォーラムの署名で使用し、HTMLまたはBBコードで埋め込むなど。',
        ],
    ],
    'armor' => [
        'header' => [
            'title' => '防具立てクリエーター',
            'subtitle' => '自分だけのカスタム防具立てを作成できます。さまざまなポーズや位置、アイテムの配置などを作成できます。',
        ],
        'meta' => [
            'title' => '防具立てクリエイター',
            'description' => '自分好みの防具建てを簡単に生成、作成できます。エディタを使用すると、さまざまなポーズ、位置、アイテムの配置、カスタムスキンなどを作成できます。',
        ],
    ],
    'banner' => [
        'editor' => [
            'header' => [
                'title' => 'Minecraft バナーエディター',
                'subtitle' => '独自のマインクラフトバナーをデザインして作成しましょう。 これらはあなたの世界を飾るために使用したり、一般的に <a href="https://optifine.net" target="_blank" rel="nofollow">Optifine</a> マントとして使用されている場合にも使用できます。',
            ],
            'meta' => [
                'title' => 'Minecraft バナークリエイター',
                'description' => 'ゲームに登場するすべてのパターンと色を使って、自分だけのカスタムバナーデザインを作成、デザインできます！バナーケープを使って、ワールドを飾ったり、Optifine マントとして身につけたりできます。バナーやシールドのコードを生成できます。',
            ],
            'toolbar' => [
                'title' => 'Banner Editor',
                'randomise' => 'Randomise',
                'clear_layers' => 'Clear layers',
                'help' => 'Help',
                'save_banner' => 'Save banner',
                'submit_to_gallery' => 'Add to gallery',
                'reset_from_url' => 'Load from link',
                'minecraft_version' => 'Minecraft version',
                'texture_type' => 'Texture type',
                'banner' => 'Banner',
                'shield' => 'Shield',
                'version_1_21' => '1.21+',
                'version_1_16' => '1.16 - 1.20',
                'version_1_13' => '1.13 - 1.15',
                'version_1_8' => '1.8 - 1.12',
            ],
            'tools' => [
                'share_link' => 'Share link',
                'share_link_placeholder' => 'Share link',
                'generate_codes' => 'Generate codes',
                'target_selector' => 'Target selector',
                'command_give' => 'Give',
                'command_setblock' => 'Setblock',
                'command_replaceitem_shield' => 'Shield',
                'code_placeholder' => 'Pick a command to generate code',
                'import_code' => 'Import code',
                'background_grass' => 'Grass background',
            ],
            'modal' => [
                'save_banners' => 'Saved banners',
                'share_saved_gallery' => 'Share saved gallery',
                'share_saved_gallery_placeholder' => 'Share saved gallery',
                'export_to_chest' => 'Export to chest',
                'delete_all' => 'Delete all',
            ],
        ],
        'gallery' => [
            'header' => [
                'title' => 'Minecraft バナーギャラリー',
                'subtitle' => 'Browse the gallery of :count custom designed Minecraft banners and patterns. Use it as a shield or cape to make your Minecraft skin more unique, or as a flag to decorate your world.',
            ],
            'meta' => [
                'title' => 'Minecraft バナーギャラリー',
                'description' => 'Browse the gallery of :count custom designed Minecraft Banners. You can use a Banner Design and Pattern as a Shield or cape to make your Minecraft skin more unique, or use it as a flag to decorate your world.',
            ],
            'add_design' => 'Add design',
            'sort' => 'Sort:',
            'sort_trending' => 'Trending',
            'sort_best' => 'Best of',
            'sort_newest' => 'Newest',
            'sort_oldest' => 'Oldest',
            'sort_favorites' => 'Most favourites',
            'sort_views' => 'Most views',
            'sort_last_week' => 'Last week',
            'sort_last_30d' => 'Last 30 days',
            'clear_filters' => 'Clear filters',
            'no_banners' => 'No banners yet',
            'no_banners_message' => 'No designs yet. Be the first to share one.',
            'create_banner' => 'Create a banner',
        ],
        'publish' => [
            'title' => 'Publish banner',
            'publish_button' => 'Publish',
            'title_label' => 'Title',
            'description_label' => 'Description',
            'tags_label' => 'Tags',
            'tags_max_reached' => 'Maximum 5 tags reached',
            'tags_add_placeholder' => 'Add a tag',
            'tags_help' => 'Press enter, tab, or comma to add a tag.',
            'tags_max_error' => 'You can add a maximum of 5 tags.',
            'generate_banner_error' => 'Create a design first.',
            'invalid_code_format' => 'Invalid banner code format.',
            'invalid_base_color' => 'Invalid base colour. Must be between 0 and 15.',
            'invalid_patterns_format' => 'Invalid patterns format.',
            'invalid_pattern_structure' => 'Invalid pattern structure.',
            'invalid_pattern_unknown' => 'Unknown pattern.',
            'invalid_pattern_color' => 'Invalid pattern colour. Must be between 0 and 15.',
        ],
        'edit' => [
            'title' => 'Edit banner',
            'title_label' => 'Title',
            'description_label' => 'Description',
            'tags_label' => 'Tags',
            'tags_max_reached' => 'Maximum 5 tags reached',
            'tags_add_placeholder' => 'Add a tag',
            'tags_help' => 'Press enter, tab, or comma to add a tag.',
            'tags_max_error' => 'You can add a maximum of 5 tags.',
            'save_changes' => 'Save changes',
            'cancel' => 'Cancel',
            'edit_details' => 'Edit banner details',
            'delete' => 'Delete banner',
            'delete_confirm' => 'Delete this banner? This cannot be undone.',
        ],
        'show' => [
            'edit_design' => 'Edit design',
            'banner_give_command' => 'Banner give command',
            'setblock_command' => 'Setblock command',
            'shield_give_command' => 'Shield give command',
            'views_count' => ':count view|:count views',
            'favourites_count' => ':count favourite|:count favourites',
            'favourite_label' => 'favourite',
            'favourites_label' => 'favourites',
            'similar_banners' => 'Similar banners',
        ],
        'already_exists' => 'This banner is already in the gallery.',
    ],
    'skin_creations' => [
        'search_tab' => 'Creations',
        'gallery' => [
            'title' => 'Skin Creations',
            'description' => 'Browse :count custom Minecraft skin creations.',
            'header' => [
                'title' => 'Skin Creations',
                'subtitle' => ':count creation|:count creations',
            ],
            'tab_creations' => 'Creations',
            'upload' => 'Upload skin',
            'downloadable_only' => 'Downloadable only',
            'sort_trending' => 'Trending',
            'sort_best' => 'Best',
            'sort_newest' => 'Newest',
            'sort_oldest' => 'Oldest',
            'sort_favorites' => 'Most favourites',
            'sort_views' => 'Most views',
            'sort_last_week' => 'Last week',
            'sort_last_30d' => 'Last 30 days',
            'sort_recently_updated' => 'Recently updated',
            'empty_title' => 'No creations yet',
            'empty_message' => 'Be the first to share a skin creation.',
            'clear_filters' => 'Clear',
        ],
        'upload' => [
            'title' => 'Upload skin creation',
            'description' => 'Upload a Minecraft skin to the gallery.',
            'heading' => 'Upload skin',
            'subtitle' => 'Drag and drop a PNG or choose a file. Add a title, description, and tags.',
            'drop_here' => 'Drop here',
            'drag_or_click' => 'Drag and drop a skin or click to choose',
            'format_hint' => 'PNG · 64×32 or 64×64',
            'choose_file' => 'Choose file',
            'title_label' => 'Title',
            'title_placeholder' => 'e.g. Mystical Warrior Skin',
            'description_label' => 'Description',
            'description_placeholder' => 'Tell others about your skin creation...',
            'tags_label' => 'Tags',
            'tags_placeholder' => 'e.g. fantasy, knight, blue',
            'tags_hint' => 'Up to 12 tags, comma-separated.',
            'downloadable' => 'Allow download',
            'downloadable_hint' => 'Allow other users to directly download your creation.',
            'visibility_label' => 'Visibility',
            'more_options' => 'More options',
            'credit_label' => 'Credit',
            'credit_placeholder' => 'Optional credit or attribution',
            'alt_text_label' => 'Alt text',
            'alt_text_subtitle' => 'This helps people using screen readers understand what your skin is about.',
            'alt_text_placeholder' => 'Describe what your skin looks like (optional)',
            'submit' => 'Publish',
            'cancel' => 'Cancel',
            'edit_in_editor' => 'Edit skin',
            'please_upload_skin' => 'Please upload a skin first.',
            'remixable' => 'Allow remixing',
            'remixable_hint' => 'Allow other users to remix your creation.',
        ],
        'edit' => [
            'title' => 'Edit skin creation',
            'description' => 'Edit your skin creation.',
            'heading' => 'Edit creation',
            'subtitle' => 'Update title, description, tags, or re-upload the skin.',
            'submit' => 'Save changes',
        ],
        'show' => [
            'download' => 'Download',
            'download_button' => 'Download skin',
            'open_in_editor' => 'Open in editor',
            'edit' => 'Edit details',
            'delete' => 'Delete',
            'delete_confirm' => 'Delete this creation? This cannot be undone.',
            'similar' => 'Similar creations',
            'created_at_ago' => 'Created :time',
            'updated_at_ago' => 'Updated :time',
            'created_and_updated' => 'Created :created · Updated :updated',
            'version_number' => 'Version :number',
            'version_history' => 'Version history',
            'iterations' => 'Iterations',
            'before_after' => 'Before & after',
            'previous' => 'Previous',
            'current' => 'Current',
            'tagged' => 'Tagged',
            'tagged_alt' => 'Tagged',
            'no_tags' => 'No tags',
            'stats' => 'Stats',
            'no_stats' => 'No stats',
        ],
        'validation' => [
            'invalid_skin_format' => 'Invalid skin format. Minecraft skins must be 64×32 or 64×64 PNG.',
            'tags_max_error' => 'You can add a maximum of 12 tags.',
        ],
        'deleted' => 'Creation deleted.',
        'download_disabled' => 'This creation is not available for download.',
        'editor' => [
            'save_to_gallery' => 'Save to gallery',
            'save_new_version' => 'Save new version',
            'save_updated_skin_version' => 'Save updated skin version',
            'save_as_new_creation' => 'Save as new creation',
            'published_successfully' => 'Your skin has been published successfully!',
            'saved_new_version' => 'New version saved.',
            'previous_skin_available' => 'A previously edited skin was found. Would you like to restore it?',
            'restore_skin' => 'Restore',
            'skin_loaded' => 'Skin loaded successfully',
            'preparing_upload' => 'Preparing your upload…',
            'bridge_fail_missing' => 'Your skin is still safe in the editor. Try saving to gallery again.',
            'bridge_fail_invalid' => 'Your skin is still safe in the editor. We couldn\'t use the saved copy — please try saving to gallery again.',
            'bridge_fail_server' => 'Your skin is still safe in the editor. Something went wrong — please try saving to gallery again.',
            'pending_replaced' => 'Your previous pending upload was replaced with your latest skin.',
            'claim_step' => 'Step 1 of 2',
            'claim_title' => 'Link your Minecraft account',
            'claim_description' => 'To publish skins to the gallery, link your Minecraft account first. This is a quick, one-time setup.',
            'claim_skin_safe' => 'Your skin is saved and will be ready to publish right after linking.',
            'claim_button' => 'Link Minecraft Account',
            'claim_reassurance' => 'Your skin is safe — you\'ll continue to publishing after linking.',
            'claim_posting' => 'Saving your skin…',
            'claim_fail' => 'Something went wrong — your skin is safe in the editor. Please try again.',
        ],
        'visibility' => [
            'public' => 'Public',
            'unlisted' => 'Unlisted',
            'draft' => 'Draft',
        ],
    ],
    'search' => [
        'meta' => [
            'title' => '検索結果：:search',
        ],
        'what_are_you_searching_for' => 'What are you searching for?',
        'title' => '検索結果',
        'results' => ':current の:count 件の結果 ',
        'results_count' => ':count result|:count results',
        'time' => '(:time 秒)',
        'username_available' => '利用可能なユーザー名*',
        'username_unavailable' => 'ユーザー名は利用できません',
        'username_status' => 'ステータス',
        'username_status_available' => '利用可能*',
        'username_status_unavailable' => '使用不可',
        'username_searches' => '検索',
        'username_searches_count' => ':count/日',
        'username_available_disclaimer' => '*名前が一時的または恒久的にMojangによって禁止されていない限り。',
        'no_results' => 'プロファイルが見つかりません。検索タイプをUUIDに変更してUUIDで検索してみてください。',
        'no_results_tags' => 'タグ付けされたスキンが見つかりません。"blue"、"girl"、"fox "など、他のタグで検索してみてください。',
        'again' => '再検索',
        'sorry' => 'すみません!!!!!!!!!!!!!!',
        'view_profile' => 'プロフィールを見る',
        'view_all' => 'View all',
        'filters' => 'Filters',
        'more_results' => 'more results',
        'more_results_fallback' => 'more results',
        'close' => 'Close',
        'clear_filters' => 'Clear all',
        'profiles' => 'Profiles',
        'verified_only' => 'Verified only',
        'verification' => 'Verification',
        'all' => 'All',
        'verified' => 'Verified',
        'not_verified' => 'Not verified',
        'country' => 'Country',
        'country_placeholder' => 'e.g. US, UK',
        'no_types_found' => 'No project types found for this search',
        'no_categories_found' => 'No categories found for this search',
        'featured' => 'Featured',
        'yes' => 'Yes',
        'no' => 'No',
        'skins' => 'Skins',
        'tags' => 'Tags',
        'no_tags_found' => 'No tags found for this search',
        'min_profiles' => 'Min profiles using',
        'try_different' => 'Try a different search term',
        'skins_no_results' => 'No skins found',
        'empty_state' => [
            'title' => 'No matches this time',
            'message' => "We didn't find any results for this search. Try adjusting your keywords or browsing instead.",
        ],
    ],
    'collection' => [
        'title' => 'Minecraft スキンコレクション',
        'subtitle' => '私たちのキュレートされたMinecraftのスキンのコレクションをご覧ください。',
        'filters' => 'フィルタ',
        'title_trending' => 'トレンド',
        'title_all' => 'すべての Minecraft スキン',
        'skin_tags' => 'タグ付きスキン',
        'filters_skin_type' => 'スキンの種類',
        'filter_skin_type_steve' => 'スティーブの種類',
        'filter_skin_type_alex' => 'アレックスの種類',
        'cancel' => 'キャンセル',
        'apply' => '適用',
        'username_minecraft_skin' => ':username Minecraft スキン',
        'user_downloads' => '<span class="fw-500">:downloads</span> download|<span class="fw-500">:downloads</span> ダウンロード',
    ],
    'favourites' => [
        'title' => 'お気に入り',
        'subtitle' => 'View and manage skins, heads, servers and banners you saved for later in your favourites list',
        'sort' => '並べ替え',
        'toast' => [
            'added' => 'お気に入りリストに追加しました',
            'removed' => 'お気に入りリストから削除されました',
            'login_required' => 'Sign in to add to favourites',
        ],
        'skins' => [
            'button' => 'スキン',
            'empty_headline' => 'No skins saved yet.',
            'empty_subtitle' => 'Skins you save will appear here.',
            'empty_browse' => 'スキンを閲覧',
            'meta' => [
                'title' => 'お気に入りのスキン',
                'description' => 'お気に入りに保存したMinecraft スキン',
            ],
        ],
        'heads' => [
            'button' => 'Heads',
            'empty_headline' => 'No heads saved yet.',
            'empty_subtitle' => 'Heads you save will appear here.',
            'empty_browse' => 'Browse heads',
            'meta' => [
                'title' => 'My favourite heads',
                'description' => 'My favourite custom Minecraft heads',
            ],
        ],
        'creations' => [
            'heading' => 'Skin creations',
            'empty_headline' => 'No favourite skin creations yet',
        ],
        'servers' => [
            'button' => 'サーバー',
            'empty_headline' => 'No servers saved yet.',
            'empty_subtitle' => 'Save servers you want to revisit later.',
            'empty_browse' => 'サーバーを閲覧',
            'meta' => [
                'title' => 'お気に入りのサーバー',
                'description' => 'お気に入りのMinecraftサーバー',
            ],
        ],
        'banners' => [
            'button' => 'Banners',
            'empty_headline' => 'No banners saved yet.',
            'empty_subtitle' => 'Banners you save will be shown here.',
            'empty_browse' => 'Browse banners',
            'meta' => [
                'title' => 'My favourite banners',
                'description' => 'My favourite Minecraft banners',
            ],
        ],
    ],
    'cape' => [
        'editor' => [
            'title' => 'Minecraft マントエディター',
            'subtitle' => 'Minecraft マントエディターを使って、お気に入りのマントを作成しましょう。',
            'meta' => [
                'title' => 'Minecraft マントエディター',
                'description' => 'Minecraft マントエディターを使って、お気に入りのマントを作成しましょう。',
            ],
        ],
        'list' => [
            'title' => 'MinecraftのCapes',
            'subtitle' => 'Minecraft の公式ケープ',
            'meta' => [
                'title' => 'Minecraft ケープリスト',
                'description' => 'Minecraft マントリスト: Mojang、Minecon、Personal、Speical、vanity Capes を含むすべての公式の Minecraft マントを表示',
            ],
        ],
        'detail' => [
            'title' => ':Cape Cape Cape',
            'info' => 'マントの情報',
            'profile_list' => 'このマントを持つプロファイル',
            'profiles' => ':profiles プロフィール',
            'meta' => [
                'title' => 'Minecraft ケープリスト',
                'description' => 'Minecraft マントリスト: Mojang、Minecon、Personal、Speical、vanity Capes を含むすべての公式の Minecraft マントを表示',
            ],
        ],
        'list-custom' => [
            'title' => 'カスタムMinecraft マント',
            'description' => 'SkinMCメンバーによって作ったカスタムマントを閲覧する。',
        ],
    ],
    'servers' => [
        'title' => 'Minecraft サーバー',
        'subtitle' => 'Minecraftのサーバーを閲覧・探索する',
        'all' => 'すべてのサーバー',
        'manage_your_servers' => 'サーバーを管理',
        'add_new_server' => '新しいサーバーを追加',
        'filters' => [
            'trending' => 'トレンド',
            'updated' => '更新日時',
            'new' => '新規作成',
            'most_viewed' => 'よく見られている',
            'top_voted' => 'トップ投票',
            'sorting' => '並べ替え',
            'sort_by_latest' => '最新順',
            'sort_by_oldest' => '古い順',
            'categories' => 'カテゴリー',
            'server_location' => 'サーバーの場所',
            'show_results' => '結果を表示',
            'show_more' => 'もっと表示',
            'show_less' => '一部非表示',
            'clear_filters' => 'フィルターを解除',
            'reviews' => 'レビュー',
            'sort_by_highest_rating' => '最高評価でソート',
            'sort_by_lowest_rating' => '最低評価でソート',
            'bedrock_and_java_support' => '統合版とJava版の対応',
            'sort_by' => 'Sort:',
            'sort_ranking' => 'Best',
            'sort_newest' => 'Newest',
            'sort_new_upcoming' => 'New & upcoming',
            'sort_most_players' => 'Most players',
            'sort_top_rated' => 'Top rated',
            'sort_most_votes' => 'Most votes',
        ],
        'review-count' => ':count件のレビュー',
        'meta' => [
            'title' => 'Minecraft サーバーリスト',
            'description' => 'Minecraftサーバーリストを参照して探索し、最高のMinecraftサーバーを見つけましょう！最新、最も人気があり、より多くのものでフィルタリングします。',
        ],
        'reviews' => [
            'meta' => [
                'title' => 'レビューを書こう！',
            ],
            'editing' => ':dateからレビューを編集しています。代わりにレビューを削除しますか？',
            'welcome' => 'やあ:usernameさん、:servername の体験はどのようなものでしたか?',
            'subtitle' => '過去に利用したサーバーの総合評価をご記入ください。',
            'scale' => [
                'great' => '素晴らしい',
                'good' => '良い',
                'okay' => 'まあまあ',
                'meh' => 'う～ん',
                'bad' => '悪い',
            ],
            'rate-experience' => '次に、これらの分野で評価してください',
            'overall' => '全体',
            'server-team' => 'サーバーチーム',
            'community' => 'コミュニティー',
            'experience' => '使い心地',
            'availablility' => '稼働時間と有効期間',
            'shop' => 'ショップ',
            'write-review-title' => 'レビューを書く',
            'write-review-subtitle' => '何が楽しかったか、何が特別な体験だったか、またはいくつかの提案をすることができます。',
            'write-review-helper' => 'サーバーレビューを書いて、あなたの経験を新しいプレイヤーと共有し、フィードバックでサーバーオーナーを助けましょう。',
            'write-review-tips' => 'ヒント',
            'submit-title' => 'レビューを投稿する準備はできましたか？',
            'submit-subtitle' => 'ほぼ完了！',
            'submit-review' => 'レビューを送信',
            'back' => '戻る',
            'continue' => '続ける',
            'delete-title' => 'レビューを削除してもよろしいですか？',
            'tos-checkbox-part-1' => 'このフォームを送信することで、SkinMCの利用規約、プライバシーポリシー、コミュニティガイドラインに同意したことになります。また、すべての情報が正確であることを確認します。',
            'tos-checkbox-part-2' => 'レビューのガイドライン',
            'tos-checkbox-part-3' => 'あなたのレビューは投稿後に掲載されますが、審査の対象となる場合があります。',
            'cannot_review_own_server' => 'You cannot review your own server.',
        ],
        'slots' => 'スロット',
        'empty-helper' => 'You can try to do another search.',
        'empty' => 'うーん、何もないようです。',
        'verified' => '認証済み',
        'review_translate_show_original' => 'オリジナルを表示',
        'review_translate' => 'レビューを翻訳',
        'description_translate' => '説明を翻訳',
        'create' => [
            'welcome' => 'ようこそ！',
            'basics' => '基本情報',
            'categories' => 'カテゴリー',
            'social_links' => 'ソーシャルリンク',
            'trailer_video' => '予告編動画',
            'images' => 'イメージ',
            'images_description' => '後で写真をアップロードして、サーバーが提供するサービスを紹介することもできます。',
            'submit' => '送信',
            'lets_get_your_server_added' => 'あなたのサーバーを追加しましょう。',
            'basics-subtitle' => '自分のサーバーがどんなものかを知ってもらおう。',
            'description' => '説明',
            'description_tips' => 'ヒント',
            'description_hint' => '新しいプレイヤーを惹きつけるために、サーバーの良い説明を書きましょう。',
            'categories-subtitle' => 'サーバーのカテゴリーを選ぶ',
            'missing-category' => 'カテゴリがありませんか？',
            'social_links_description' => 'プレイヤーはソーシャルメディアでサーバーとつながることができますか？',
            'trailer_video_description' => 'YouTube動画でサーバーを紹介しましょう',
            'trailer_video_hint' => '動画のURLまたはIDを貼り付ける',
            'ready_to_submit_your_server' => 'サーバーを申請する準備はできましたか？',
            'review-hint' => '申請後、チームはサーバー掲載申請を慎重に審査します。その後、決定次第、サーバーは公開されるか、公開前に変更が要求されます。',
            'terms' => [
                'part-1' => 'このフォームを送信することにより、SkinMCの利用規約、プライバシーポリシー、コミュニティガイドラインに同意したものとみなされます。また、上記のすべての情報が正確であること、「利用規約」、「プライバシーポリシー」、「コミュニティガイドライン」に従っていることを確認します。',
                'part-2' => 'セットアップに必要なサーバーの条件',
                'part-3' => 'また、Minecraft サーバーはあなたが代表を務める団体によって所有および管理されています。',
            ],
            'submit-application' => '申請を送信',
            'video-id-helper' => [
                'part-1' => '動画IDは、以下の数字とアルファベットの文字列です。',
                'part-2' => '例えば、動画のURLが',
                'part-3' => 'この場合、ビデオIDは次のようになります。',
            ],
            'welcome_description' => 'このステップではサーバーの追加を開始します。次のステップでは画像をアップロードすることができます。',
        ],
        'votes' => [
            'vote' => 'Vote',
            'voted' => 'Voted',
            'success' => 'Your vote has been recorded!',
            'login_required' => 'Please log in to vote for this server.',
            'profile_required' => 'Link your Minecraft account to vote.',
            'server_ineligible' => 'This server is not currently eligible for voting.',
            'self_vote_blocked' => 'You cannot vote for your own server.',
            'cooldown' => 'You can only vote once every 24 hours.',
            'cooldown_tooltip' => 'You can vote again :time',
            'count' => ':count vote|:count votes',
        ],
        'copy_server_ip' => 'IPアドレスをコピー',
        'all_minecraft_servers' => 'すべてのMinecraft サーバー',
        'promo' => [
            'title' => 'Minecraft サーバーをホストしていますか?',
            'ready_to_list_your_server' => 'サーバーをリストアップする準備はできましたか？',
            'everything_you_need' => 'サーバーの成長に必要なもの',
            'list_your_server' => 'サーバー一覧',
            'list_your_server_description' => 'サーバーのリストを作成し、写真やソーシャルメディアなどを追加してください。',
            'find_players' => 'プレイヤーを探す',
            'find_players_description' => '新しいプレイヤーを見つけてサーバーに参加させ、コミュニティを発展させましょう。',
            'get_reviews' => 'レビューを取得',
            'get_reviews_description' => 'コミュニティにサーバーのレビューを依頼し、ゲーム内で報酬を与えましょう。',
            'why_list_on_skinmc' => 'サーバーをSkinMCに登録するメリット',
            'others' => 'その他',
            'quality_check_and_confirmation' => '品質チェックと確認',
            'quality_check_description' => '私たちは品質を確保するためにすべてのサーバーをレビューします。',
            'verified_players' => '確認済みのMinecraft プレーヤーからのレビュー',
            'verified_players_description' => 'Votifierの統合で正当なアカウントから本物のプレイヤーのレビューを収集します。',
            'international' => '国際',
            'international_description' => '翻訳機能により、あなたのリスティングはより多くのプレーヤーが利用できるようになります。',
            'server_listing_page' => 'パワフルなサーバーリストページ',
            'server_listing_page_description' => '写真や説明文、youtubeの動画を追加しプレイヤーがあなたのサーバーに参加すべき理由を強調しましょう。',
            'social_connections' => 'ソーシャルメディア',
            'social_connections_description' => 'あなたのサーバーのソーシャルアカウントに接続し、新しいプレーヤーがあなたを見つけられる場所を表示します。',
            'verified_badge' => '認証バッジ',
            'verified_badge_description' => '認証されたサーバーは認証バッジを申請することができます。',
            'owner_profile' => 'オーナープロフィール',
            'owner_profile_description' => 'カスタムプロフィールを完成させることで、特徴的なタッチを加えましょう。',
            'categories' => 'カテゴリー',
            'categories_description' => 'サーバーを見つけやすくするためのさまざまなカテゴリー。',
            'vote' => '投票',
            'vote_description' => 'ユーザーにあなたのサーバーに投票してもらいましょう。',
            'review' => 'Review',
            'review_description' => 'Ask users to review your server.',
            'fair_listings' => '公正なリスト',
            'fair_listings_description' => 'SkinMCでは、サーバーのリストを人為的に上げることはできません。',
            'support' => '24時間サポート',
            'support_description' => 'ヘルプが必要ですか？いつでもご連絡ください。',
            'custom_features' => 'カスタム機能',
            'custom_features_description' => 'サーバーの機能が不足していますか？チケットにご記入ください。',
            'faq' => [
                'title' => 'あなたの質問への回答',
                'suited-question' => '私のMinecraftサーバーはSkinMCに適していますか？',
                'suited-answer' => 'SkinMCのMinecraftプレイヤーは、新しい体験やコンテンツを発見したり、コミュニティと交流したりするのが大好きです。SkinMCには、ユニークで楽しいマインクラフトサーバーがたくさんあります。大規模なネットワークから小規模なサバイバルサーバーまで、誰かの一日を盛り上げることができます！',
                'get-started-question' => '始めるにはどうすればいいですか?',
                'get-started-answer' => 'Minecraft サーバーを SkinMC サーバーリストに追加するのはとても簡単です! まだアカウントを作成していない場合は、まずアカウントを作成し、セットアップガイドに従ってサーバーを一覧表示します。 いくつかの写真と素敵な説明を追加すると、サーバーはすぐに公開されます!',
                'players-question' => 'Minecraft サーバーで他のプレイヤーを獲得するにはどうすればいいですか?',
                'players-answer' => 'マインクラフトサーバーを長続きさせるには、コミュニティの構築が最も重要です。SkinMCのマインクラフトサーバーリストを利用して、新しいユーザーを見つけ、コミュニティを作りましょう。プレイヤーにあなたのサーバーを推薦してもらったり、ソーシャルメディアプラットフォームでリストを共有しましょう。良いレビューを集めることも、新しいプレイヤーを惹きつけるサーバーリストの重要な役割です。',
                'more-question' => 'もっと質問があります。どこで相談できますか？',
                'more-answer' => 'ヘルプボタン、ヘルプデスク、Discordサーバーのいずれかを使って、24時間いつでもSkinMCに連絡することができます。',
            ],
            'ready_to_list_description' => 'わずか数分であなたのMinecraftサーバーをSkinMCサーバーリストに追加できます。何かお困りのことがあれば、24時間いつでもご連絡ください。',
        ],
        'manage' => [
            'index' => [
                'welcome' => ':username さん、おかえりなさい',
                'your_servers' => 'あなたのサーバー',
                'reviews_today' => '今日のレビュー',
                'no_reviews_today' => '今日のレビューはありません',
                'no_reviews_text' => '今日、あなたのサーバーにはレビューが届いていません。プレイヤーにレビューをお願いしてみてはいかがでしょうか？',
                'tips' => [
                    'title' => 'ヒント',
                    'description-title' => '良いサーバーの説明を書く',
                    'description-body' => 'サーバーの説明文を書くのに役立つヒントやアドバイス。',
                    'images-title' => 'サーバー画像を追加中',
                    'images-body' => '素敵な画像でサーバーリストを目立たせましょう。',
                ],
            ],
            'listings' => [
                'title' => 'あなたのマインクラフトサーバー(:count)',
            ],
            'insights' => [
                'title' => 'インサイト',
                'metrics' => [
                    'servers' => 'Servers',
                    'live_count' => ':count live',
                    'votes_30d' => 'Votes (30 days)',
                    'all_time_count' => ':count all-time',
                    'favorites' => 'Favourites',
                    'reviews_count' => ':count reviews',
                    'average_rating' => 'Average rating',
                    'pending_draft_count' => ':pending pending, :draft draft',
                ],
                'trends' => [
                    'votes_title' => 'Vote trend',
                    'reviews_title' => 'Review trend',
                    'last_days' => 'Last :days days',
                    'vs_previous' => 'vs previous period',
                ],
                'opportunities' => [
                    'title' => 'Top opportunities',
                    'click_to_view' => 'Click an item to view affected servers.',
                    'missing_photos_draft' => 'Draft listings blocked by missing photos',
                    'no_votes_30d' => 'Live servers with no votes in 30 days',
                    'low_completeness' => 'Listings below 75% completeness',
                    'low_rating' => 'Servers below 3.5 rating (3+ reviews)',
                    'meta_missing_photos' => ':count/5 photos',
                    'meta_no_votes_30d' => '0 votes / 30d',
                    'meta_incomplete' => ':score%',
                    'meta_low_rating' => ':rating/5',
                    'none' => 'No servers in this category.',
                ],
                'review_breakdown' => [
                    'title' => 'Review category breakdown',
                    'empty' => 'No review data yet.',
                    'weakest' => 'Weakest category: :category',
                ],
                'top_lists' => [
                    'by_favorites' => 'Top by favourites',
                    'by_votes_30d' => 'Top by votes (30 days)',
                    'lowest_rated' => 'Lowest rated (3+ reviews)',
                    'empty' => 'No server data available.',
                    'empty_votes' => 'No vote data available.',
                    'empty_ratings' => 'Not enough review data yet.',
                ],
                'table' => [
                    'server' => 'Server',
                    'status' => 'Status',
                    'listing_score' => 'Listing score',
                    'avg_rating' => 'Avg',
                    'votes_30d' => 'Votes 30d',
                    'votes_all' => 'Votes',
                    'last_review' => 'Last review',
                    'live' => 'Live',
                    'pending' => 'Pending',
                    'draft' => 'Draft',
                    'empty_title' => 'No servers yet',
                    'empty_subtitle' => 'Add your first listing to see insights.',
                ],
                'activity' => [
                    'title' => 'Recent activity',
                    'review' => 'Review',
                    'vote' => 'Vote',
                    'vote_summary' => 'New vote received',
                    'view_review' => 'View review',
                    'by_user' => 'by :user',
                    'unknown_user' => 'Unknown',
                    'empty_title' => 'No activity yet',
                    'empty_subtitle' => 'Votes and reviews will appear here.',
                ],
            ],
            'edit_server' => 'サーバーを編集',
            'listing' => '一覧',
            'to_do' => 'To do',
            'last_update' => '最終更新日時',
            'add_more_photos_to_publish' => '写真を追加して公開する',
            'looks_empty_here' => 'ここは何もないようです',
            'get_started_by_adding_a_new_server' => '新しいサーバーの追加から始めませんか？',
        ],
        'status' => [
            'approved' => '承認済',
            'pending_approval' => '承認待ち',
            'published' => '公開済み',
            'draft' => 'Draft',
            'need_more_images' => 'Need :count more to publish',
            'ready_for_approval' => 'Ready for approval',
            'in_review' => 'レビュー中',
        ],
    ],
    'editor' => [
        'import' => [
            'title' => 'スキンのインポート',
            'import_by_username' => 'ユーザー名でインポート',
            'import_button' => 'インポート',
            'drag' => 'ここにスキンをドラッグ＆ドロップするか、またはクリック',
            'click' => '画像を選択',
        ],
        'download' => [
            'error' => [
                'no-data' => 'No skin data was provided. Please try again.',
                'invalid-format' => 'The skin data format is invalid. Please try again.',
                'invalid-data' => 'The skin data is corrupted. Please try again.',
                'generic' => 'Something went wrong while downloading your skin. Please try again.',
            ],
        ],
        'draw' => '描く',
        'eyedropper' => 'スポイト',
        'fill' => '埋める',
        'move' => '移動',
        'decrease_brightness' => '暗くする',
        'increase_brightness' => '明るくする',
        'erase' => '消しゴム',
        'undo' => '戻る (CTRL+Z)',
        'redo' => '元に戻す (CTRL+Y)',
        'default_view' => 'デフォルトビュー',
        'zoom_in' => 'ズームイン (CTRL+)',
        'zoom_out' => 'ズームアウト (CTRL -)',
        'saved' => '最終保存日時',
        'saving' => '自動保存中...',
        'save_error' => 'エラーが発生',
        'new_skin' => '新しいスキン',
        'automatically_saved_skins' => 'Automatically saved skins',
        'recovered_skins' => 'Recovered skins',
        'load' => 'Load',
        'delete' => 'Delete',
        'backed_up_title' => '自動保存されたスキン',
        'backed_up_info' => '一時的にローカルストレージにバックアップされました。',
        'backed_up_empty_title' => 'ここは何もないようです',
        'backed_up_empty_info' => 'スキンの編集を開始すると、32個の最後の編集済みスキンがここに表示されます。',
        'recovered_empty_title' => 'No recovered skins',
        'recovered_empty_info' => 'Recovered skins will appear here when you navigate away or close the editor.',
        'backed_up_skins_count' => '（32個以内）のスキンバックアップを使っています',
        'backed_up_skins_count_info' => '最大32枚のスキンをバックアップできます。32枚のスキンに達すると、古いスキンが新しいスキンに置き換えられます。',
        'layers' => 'レイヤー',
        'body' => [
            'title' => '本文',
            'overlay' => 'オーバーレイ',
            'head' => '頭',
            'torso' => '胴体',
            'l_arm' => '左腕',
            'r_arm' => '右腕',
            'l_leg' => '左足',
            'r_leg' => '右足',
        ],
        'model' => 'モデル',
        'steve' => 'スティーブ',
        'alex' => 'アレックス',
        'stance' => [
            'title' => '位置',
            'default' => 'デフォルト',
            'walk' => '歩く',
            'run' => '実行',
            'hug' => 'Tポーズ',
            'fly' => '飛ぶ',
        ],
        'fullscreen' => 'フルスクリーン',
        'fullscreen_exit' => '全画面表示を終了',
        'grid' => 'グリッド',
        'show_grid' => 'グリッドを表示',
        'download' => [
            'title' => '保存してダウンロード',
            'subtitle' => 'SkinMCアカウント',
            'description' => 'お肌と将来のスキンをクラウドに保存するための無料SkinMCアカウントを作成しますか？',
            'start_description' => 'クラウドに保存せずに直接ダウンロードを開始する',
            'start' => 'スキンをダウンロード',
        ],
        'help' => [
            'title' => 'Minecraft スキンエディター',
            'about' => 'SkinMCエディタでカスタムMinecraftスキンを簡単に作成・編集できます。 SteveとAlexのどちらかを選択し、ファイルまたはユーザー名からスキンをインポートし、独自のMinecraftスキンを作成できます。',
            'draw' => 'ペンツールを使用して描きます。スウォッチで使用する色を選択してくださ',
            'eyedropper' => 'スポイトを使用して、スキンから色を選択し、現在のパレットに追加します。',
            'fill' => '塗りつぶしツールを使用してスキン全体を塗りつぶします。塗りつぶす前に色を選択してください。',
            'move' => '移動ツールを使ってスキンエディターのキャンバスを移動します。',
            'decrease_brightness' => '現在アクティブな色の明るさを下げる。',
            'increase_brightness' => '現在アクティブな色の明るさを上げる。',
            'erase' => '2番目のオーバーレイレイヤーに描画されたピクセルを消去',
            'minimap' => 'Minimap',
            'minimap_info' => 'The minimap can show you the skin texture in a flat view while in 3D mode. In 2D mode the minimap switches to a 3D preview of your skin. You can zoom in and out.',
            'autosave' => 'Autosave',
            'autosave_info' => 'The autosave feature saves your skin automatically every 30 seconds. You can access the autosaved skins in the editor by pressing the folder icon, and choosing "Previous skins".',
            '2d_editor' => '2D and 3D editor',
            '2d_editor_info' => 'Toggle between editing your Minecraft skin in 2D or 3D mode.',
        ],
    ],
    'account' => [
        'level' => 'レベル',
        'level_history' => 'レベル履歴',
        'xp' => 'XP',
        'my_xp' => 'マイXP',
        'xp_to_next_level' => ':xp XPから次のレベルへ',
        'xp_info' => 'XPとは？',
        'xp_info_tooltip' => 'XPはスキンにタグを追加したり、友達を招待したり、コメントしたりなど様々なアクティビティで獲得できます。XPを獲得するごとにレベルアップしクールなものをアンロックすることができます！',
        'table' => [
            'description' => 'Description',
            'points' => 'Points',
        ],
        'my_stuff' => [
            'title' => 'My stuff',
            'creations' => 'Creations',
            'collections' => 'Collections',
            'favourites' => 'Favourites',
            'skins' => 'Manage skins',
            'capes' => 'Capes',
            'banners' => 'Banners',
            'servers' => 'Servers',
        ],
        'settings' => [
            'title' => 'アカウント',
            'show_profile' => 'プロファイルに移動',
            'friends' => '友達',
            'friends_detail' => 'SkinMCでフレンドリストを使用して接続を維持します。',
            'security' => 'セキュリティ',
            'security_detail' => 'ログインパスワードを更新し、アカウントを安全に保ちます',
            'social' => 'ソーシャルメディアアカウント',
            'social_detail' => 'ソーシャルメディアを追加してプロフィールをカスタマイズする',
            'link' => 'Minecraftアカウントをリンクする',
            'link_detail' => 'Minecraftアカウントをリンクし、プロフィールを要求します。',
            'logout' => 'SkinMCアカウントからログアウトしますか？',
            'automatic_backups' => 'スキンの自動バックアップ',
            'automatic_backups_info' => 'SkinMC plus会員になると、スキンは毎日バックアップされます。',
        ],
        'capes' => [
            'title' => 'SkinMC Minecraft マント',
            'description' => 'SkinMC マントを使えば、ゲーム内で好きなマントを無料で着用できます。',
            'drop' => 'マントをここにドラッグ＆ドロップする',
            'drop-hint' => 'サイズ 64x32px',
            'select' => '画像を選択',
            'upload-cape' => 'マントをアップロードして使用',
            'save-and-use' => '保存して使用',
            'uploaded-cape' => 'マントをアップロードしました',
            'no-cape' => 'マントなし',
            'remove-cape' => 'マントを削除',
            'download' => 'SkinMC Modをダウンロードすると、ゲーム内で自分や他のプレイヤーのマントを見ることができます。',
            'learn-more' => '続きを読む',
            'link-account' => 'マントをアップロードするには、Minecraft アカウントをリンクしてください。',
            'updated' => 'マントを更新しました！',
            'removed' => 'マントを取り除きました。',
            'active' => 'マントが有効になりました！',
        ],
        'favourite' => 'お気に入り',
        'remove_favourite' => 'お気に入りを削除',
        'added_to_favourites' => 'ブックマークに追加しました',
        'removed_from_favourites' => 'お気に入りから削除しました',
        'welcome' => 'はじめまして！',
        'view-profile' => 'プロフィールを見る',
        'security' => [
            'title' => 'セキュリティ',
            'email' => 'メールアドレス',
            'email-title' => 'メールアドレスを更新してください。',
            'save' => '保存',
            'password' => 'パスワード',
            'password-title' => 'パスワードはいつでも変更できます。',
            'social-provider' => 'パスワードなどのアカウント情報を更新するには、ログインプロバイダにアクセスしてください',
            'social-provider-email' => 'ログインプロバイダーに関連付けられたメールアドレス',
            'social-provider-connected' => '現在接続中のログインプロバイダー',
            'current-password' => '現在のパスワード',
            'forgot' => 'パスワードを忘れましたか？',
            'edit' => '編集',
            'delete' => 'アカウントの削除',
            'account-deletion' => 'SkinMCアカウントを削除します。',
            'delete-info' => '続行するには確認してください',
            'delete-confirmation' => 'アカウントの削除はもとに戻すことができません。投稿、お気に入り、アップロードしたケープ、カスタマイズなどの個人情報やコンテンツはすべて削除され、復元することができません。',
            'delete-confirmation-info' => '続行するにはパスワードを入力してください',
            'delete-confirmation-info-social' => 'Type "delete" to confirm account deletion',
            'type-delete' => 'Type "delete" to confirm',
            'type-delete-label' => 'Type "delete" to confirm',
            'yes-confirm-delete' => '削除を確認',
            'account-successfully-deleted' => 'アカウントとデータは正常に削除されました。',
        ],
        'social' => [
            'title' => 'ソーシャルアカウント',
            'edit' => '編集',
            'save' => '保存',
            'link-account' => 'あなたのMinecraft アカウントをSkinMCにリンクし、あなたのプロフィールにソーシャルリンクを表示します。',
            'finish-setup' => 'セットアップの完了',
            'connect-account' => 'アカウントに接続',
            'connect-description' => '接続するアカウントを選択し、SkinMCの特別な統合機能をアンロックします。',
            'empty' => 'アカウントが追加されていません',
            'empty-description' => 'ソーシャルメディアのアカウントは、ここと公開プロフィールに表示されます。追加されると、あなたのページにパーソナライズが追加され、統合も可能になります。',
            'connect' => '接続',
            'username' => 'ユーザー名',
            'spotify' => 'Spotifyのユーザー名を追加して、Spotifyの情報をプロフィールに表示します。',
            'discord' => 'Discordのユーザー名と番号を入力して、SkinMCのプロフィールにDiscordの情報を表示します。',
            'youtube' => 'SkinMCにYouTubeチャンネルを追加し、プロフィールにYouTubeチャンネルを表示します。',
            'youtube-format' => 'チャンネルリンクに応じて、次のフォーマットを使用します',
            'twitter' => 'Enter your X (formerly Twitter) username to display it on your profile.',
            'bluesky' => 'Enter your Bluesky handle e.g. username.bsky.social to display your Bluesky profile on your profile.',
            'twitch' => 'Twitchのユーザー名を入力し、プロフィールにTwitchチャンネルを表示します。',
            'reddit' => 'Redditのユーザー名を入力して、プロフィールにRedditのプロフィールを表示します。',
            'github' => 'GitHubのユーザー名を入力して、あなたのプロフィールにGitHubのプロフィールを表示します。',
            'telegram' => 'Telegramユーザー名を入力すると、プロフィールにTelegramリンクが表示されます。',
            'tiktok' => 'TikTokのユーザー名を入力し、TikTokプロファイルをプロフィールに表示します。',
            'snapchat' => 'Snapchatのユーザー名を入力すると、プロフィールにSnapchatのプロフィールが表示されます。',
            'instagram' => 'Instagramのユーザー名を入力して、プロフィールにInstagramのプロフィールを表示します。',
            'facebook' => 'Facebookのユーザー名を入力して、プロフィールにFacebookのプロフィールを表示します。',
            'includes_skinmc_plus_benefits' => 'SkinMCプラス特典を含む',
        ],
        'recover' => [
            'title' => 'アカウントを復元する',
            'subtitle' => '新しいパスワードを入力し、アカウントの回復を完了するために確認してください。',
            'new_password' => '新しいパスワード',
            'repeat_new_password' => '新しいパスワードを再入力',
            'submit' => 'アカウントを復元する',
        ],
        'customise' => [
            'title' => 'プロフィールをカスタマイズ',
            'description' => 'ソーシャルメディアの追加、絵文字の選択、位置情報の設定など',
            'information' => '情報',
            'preview' => 'プレビュー',
            'location' => [
                'title' => 'ロケーション',
                'description' => 'プロフィールに追加したい場所を選択してください。',
            ],
            'biography' => [
                'title' => '私について',
                'description' => 'プロフィールに自己紹介を書こう!',
            ],
            'status' => 'ステータス',
            'status-toggle' => 'オンライン状態を表示',
            'emoji' => '絵文字',
            'name-history-toggle' => 'ユーザー名の履歴を非公開にする',
            'name-history-info' => 'あなたのマインクラフトのユーザー名履歴は現在あります',
            'name-history-toggle-on' => '非公開',
            'name-history-toggle-off' => '公開',
            'theme' => 'プロフィールテーマ',
            'theme-primary' => 'プライマリ',
            'theme-secondary' => 'セカンダリ',
            'appearance' => 'Appearance',
        ],
        'link' => [
            'manage' => '連携済みのMinecraft アカウントを管理',
            'description' => '連携済みのMinecraft アカウントを表示および管理',
            'title' => '連携済みのMinecraft アカウント',
            'current' => '現在連携済みのMinecraft アカウントがあります。',
            'status' => 'これでSkinMCの全機能にアクセスできるようになりました！',
            'linked' => '連携済み',
            'disconnect' => '切断',
            'disconnect-title' => '切断済みのMinecraft アカウント',
            'disconnect-info' => '本当にMinecraft アカウントを切断してもよろしいですか？',
            'disconnect-features' => 'Minecraft アカウントとのリンクが必要なコメント、カスタマイズ、その他の機能が利用できなくなります。これらを再び使用するには、Minecraft アカウントをリンクする必要があります。',
            'disconnect-following' => 'Minecraft アカウントを切断すると、フォローしたすべてのプロファイルが永久に削除されます。',
            'disconnect-posts' => '作成されたフィードの投稿と「いいね！」は削除されます。',
            'can-not-undo' => 'この操作は元に戻すことができません。',
            'are-you-sure' => 'それでも実行しますか？',
            'confirm' => 'はい、切断をします。',
            'cancel' => 'キャンセル',
            'success' => 'アカウントの切断に成功しました。',
        ],
        'finish-setup' => [
            'title' => 'アカウントの設定を完了する',
            'description' => 'アカウントの設定を完了し、Minecraft アカウントとSkinMCをリンクすることで、すべての機能にフルアクセスできます。',
            'link' => 'Minecraft アカウントを紐づく',
            'get-started' => '始めよう！',
            'skip' => 'スキップ',
            'download_skin' => 'Download skin',
            'claim' => 'プロフィールを取得',
            'pending_upload' => 'Link your Minecraft account to finish publishing your skin.',
            'customise' => 'ページをカスタマイズする',
            'social' => 'ソーシャルリンクを追加',
            'comment' => 'コメントシステムへのアクセス',
            'direct_message' => 'ダイレクトメッセージを送信',
            'feed' => 'フィードにステータスを更新する',
            'follow' => '友達をフォローする',
            'badge' => 'プロフィールにバッジが表示されました',
            'cape' => 'カスタムMinecraft マント',
            'backup' => 'スキンの自動バックアップ',
            'more' => 'その他...',
        ],
        'creations' => [
            'title' => 'Creations',
            'published' => 'Published',
            'private' => 'Private',
            'unlisted' => 'Unlisted',
            'drafts' => 'Drafts',
            'empty_title' => 'No creations yet',
            'empty_published' => 'You have no published creations. Upload a skin and set visibility to "Public" to show it here.',
            'empty_private' => 'You have no private (unlisted) creations.',
            'empty_unlisted' => 'You have no unlisted creations.',
            'empty_drafts' => 'You have no drafts. Save a creation as draft from the editor or upload page.',
            'empty_browse' => 'Browse gallery',
            'empty_upload' => 'Upload skin',
            'meta' => [
                'title' => 'My creations',
                'description' => 'View and manage your skin creations.',
            ],
        ],
        'banners' => [
            'title' => 'Banners',
            'published' => 'Published',
            'drafts' => 'Drafts',
            'empty_title' => 'No banners yet',
            'empty_published' => 'You have no published banners. Create a banner in the editor and publish it to show it here.',
            'empty_drafts' => 'You have no draft banners. Create a banner in the editor without publishing to save as draft.',
            'empty_browse' => 'Browse gallery',
            'empty_create' => 'Create banner',
            'meta' => [
                'title' => 'My banners',
                'description' => 'View and manage your Minecraft banners.',
            ],
        ],
        'skins' => [
            'title' => 'スキンを管理',
            'subtitle' => 'Choose which skins appear on your profile. Your current Minecraft skin is always shown.',
            'toggle' => 'スキンの可視性の切り替え',
            'section_currently_worn' => 'Currently worn in Minecraft',
            'section_profile_skins' => 'Skins on your profile',
            'active_badge' => 'Active in Minecraft',
            'active_synced_copy' => 'Synced from your Minecraft account.',
            'active_action_copy' => 'Always visible on your profile. To hide it, change your skin in Minecraft.',
            'open_minecraft_skin_settings' => 'Open Minecraft skin settings',
            'show_on_profile' => 'Show on profile',
            'show_on_profile_tooltip' => 'Controls visibility on your SkinMC profile.',
            'empty' => 'No skins in your history yet. Skins you wear in Minecraft will appear here.',
            'empty_other' => 'No other skins yet. Skins you have worn will appear here; you can show or hide them on your profile.',
            'empty_not_claimed_title' => 'Link your Minecraft account',
            'empty_not_claimed' => 'Connect your Minecraft account to see your skin history and choose which skins appear on your profile.',
        ],
        'invite' => [
            'title' => '招待',
            'headline' => '友だちを招待する',
            'info' => '招待コードを作成して友達と共有しましょう。招待コードを受け入れたら、両方とも追加のXPを獲得できます！',
            'description' => 'フレンドへの招待を作成すると、両方とも追加のXPを獲得できます。',
            'generate' => '招待コードを作成',
            'empty' => 'まだ招待を作成していません。',
            'code' => 'コード',
            'expiry' => '各コードは一度のみ動作します。',
            'status' => [
                'title' => 'ステータス',
                'pending' => '保留中',
                'accepted' => '承認済み',
            ],
            'add_invite' => [
                'button' => '招待をお持ちですか？',
                'title' => '招待コードを追加',
                'redeem' => '招待を引き換え',
            ],
            'share' => '友達に招待リンクを送信',
        ],
        'emoji' => [
            'title' => 'SkinMC 絵文字',
            'introducing' => '紹介',
            'info' => '絵文字でプロフィールをカスタマイズ。レベルアップでさらにアンロック',
            'unlocked_at' => 'レベル :level で解放されました',
            'unlocks_at' => 'レベル:level に達するとアンロックできます',
            'turn_off' => '絵文字を見る',
        ],
    ],
    'notifications' => [
        'title' => '通知',
        'view_all' => 'すべて表示',
        'view_all_notifications' => '全ての通知を表示する',
        'image' => '通知画像',
        'archived' => 'アーカイブ済み',
        'inbox' => '受信箱',
        'settings' => [
            'title' => 'Notification settings',
            'open' => 'Open notification settings',
            'save' => 'Save',
            'saved' => 'Notification settings updated.',
            'server_owner_alerts' => [
                'title' => 'Server owner alerts',
                'description' => 'Receive reminders and listing insights to help keep your server visible and up to date.',
                'toggle' => 'Enable server owner alerts',
                'unavailable' => 'This alert preference is managed globally by the administrators.',
            ],
        ],
        'empty' => [
            'title' => '最新バージョンです！',
            'text' => '新しい通知はここに表示されます。',
            'text-archived' => 'アーカイブされた通知はここに表示されます。',
        ],
        'action' => [
            'archive' => 'アーカイブに移動',
            'unarchive' => 'アーカイブから戻す',
            'open' => 'タップして開く',
        ],
        'toast' => [
            'archive' => '通知をアーカイブに移動しました',
            'unarchive' => '通知を受信箱に移動しました',
            'undo' => '元に戻す',
        ],
    ],
    'error' => [
        'offline' => [
            'title' => 'インターネットに接続されていません',
            'subtitle' => 'インターネットが切断されました。接続を確認し、ページを再読み込みして再試行してください。',
            'try_again' => '再実行',
        ],
        '404' => [
            'title' => '404 — Page not found.',
            'subtitle' => 'この場所には何も見つかりませんでした。戻るか、新しい検索を開始しますか？',
            'try_again' => 'ホームへ戻る',
        ],
    ],
    'heads' => [
        'list' => [
            'meta' => [
                'title' => 'Minecraft ヘッドデータベース',
                'description' => 'Minecraft ヘッドデータベースを検索して、あなたの世界を飾ったり、独自のコマンドを生成したりできます。公式ヘッドやプレイヤーヘッド、テクスチャが変更されないカスタムヘッドを見ることができます。',
            ],
            'header' => [
                'title' => 'Minecraft ヘッド',
                'subtitle' => 'Minecraft ヘッドのデータベースを調べて、あなたの世界を飾ったり、あなた自身のgiveコマンドを生成したりしましょう。 プレーヤーヘッドは、ユーザーが着用している現在のスキンを表示し、ユーザーが自分のスキンを更新すると変更することができます。 カスタムヘッドはMojangスキンファイルにリンクされ、変更されることはありません。 コマンドが非常に長いため、コマンドブロックを使用してカスタムヘッドを呼び出す必要があります。',
            ],
            'count' => [
                'heads' => ':heads ヘッド',
            ],
            'customheads' => [
                'title' => 'カスタムヘッド',
                'description' => 'カスタムヘッドは、Mojangサーバー上のテクスチャファイルへの直接パスを使用します。そのため、テクスチャが削除されることはなく、ヘッドが変更されることもありません。',
                'version' => 'Minecraft 1.8以降',
            ],
            'playerheads' => [
                'title' => 'プレイヤーヘッド',
                'description' => 'プレイヤーヘッドは Minecraft プレイヤーの現在のスキンテクスチャを使用します。ユーザー名ベースなので、プレイヤーの名前やスキンが変わるとヘッドも変わります。',
                'version' => 'すべてのMinecraft バージョン',
            ],
        ],
    ],
    'mod' => [
        'title' => 'SkinMC Mod：無料カスタムマント',
        'headline' => 'さらなるカスタマイズを可能にするSkinMC Modの紹介',
        'description' => 'Minecraft コミュニティへの恩返しとして、カスタムマントでプレイヤーをより魅力的にできるようにする無料Modを提供します。',
        'download' => '今すぐダウンロード',
        'download-title' => 'Modをダウンロード',
        'requires' => '必須',
        'select-version' => 'Minecraftのバージョンを選択',
        'get-started' => 'はじめるのは簡単です',
        'step-1' => '1. Modを入手',
        'step-1-detail' => 'Fabricをインストールし、ゲームバージョンのModをダウンロードし、jarファイルをmodsフォルダに入れてインストールします。',
        'step-2' => '2. アカウントと連携する',
        'step-2-detail' => 'まだサインアップしていない場合は、Minecraft アカウントをSkinMCに接続してください。',
        'step-3' => '3. マントをアップロードする',
        'step-3-detail' => 'アカウントにアクセスしカスタムマントをアップロードしてください。すると、ゲーム内で表示されます。',
        'all-versions' => 'すべてのバージョン',
        'latest' => '最新',
        'logged-in' => 'マントをアップロードする',
        'mirror' => '左右反転',
        'download-via' => 'ダウンロード経由:',
        'curseforge' => 'CurseForge',
    ],
    'app' => [
        'title' => 'SkinMC Android アプリ',
        'headline' => 'SkinMC Android アプリにようこそ。',
        'play-store-attribution' => 'Google PlayおよびGoogle PlayのロゴはGoogle LLCの商標です。',
        'features' => '外出先で便利な機能',
        'feature-qr' => 'QRコードスキャナーを搭載',
        'feature-qr-detail' => '内蔵のQRコードスキャナを使用すると、デスクトップからアプリにスキンを簡単に取得したり、友達のカスタムプロファイルQRコードをスキャンしたりできます。',
        'feature-files' => '直接ファイルに保存',
        'feature-files-detail' => 'Androidファイルマネージャの使用により、アプリは便利にスキンを保存することができ、統合版での適用が容易になります。',
        'feature-noads' => '広告無し！',
        'feature-noads-detail' => '邪魔にならないクリーンなデザインのインターフェース。ウェブからアプリまで、邪魔な煩わしさのない広告のない体験をお楽しみください。',
        'feature-experience' => '使い心地',
        'feature-experience-detail' => 'SkinMCの機能を追加して、どこでもSkinMCの体験をお楽しみください。プロフィールをカスタマイズし、プロフィールを追加し、楽しいQRコードを作成しましょう！',
        'get-app-headline' => 'SkinMCアプリを入手',
        'get-app-detail' => 'あなたのAndroid向けのMinecraft コンパニオンは無料で利用できます。',
    ],
    'random' => [
        'title' => 'ランダムにMinecraft スキンを読み込み中',
        'description' => 'ランダムにMinecraft スキンを読み込み中',
        'headline' => 'しばらくお待ちください...',
        'redirect' => '自動的にリダイレクトされます。ページが読み込まれませんか？',
        'click-here' => 'ここをクリック',
        'messages' => [
            '1' => 'ランダムにMinecraft スキンを読み込み中...',
            '2' => '掘り下げています...',
            '3' => 'クリーパーだ！大変だ...。',
            '4' => 'チェストから物を探し中...',
            '5' => '来ているスキンが完全にランダムであることをご存知ですか？',
            '6' => 'ランダムなスキンが入ってきました...',
            '7' => 'あと1ブロック...',
            '8' => '在庫を並べ替えています...',
            '9' => 'ダイヤモンドのツルハシを作成しています...',
            '10' => 'Herobrineを探しています...',
        ],
    ],
    'feed' => [
        'title' => 'フィード',
        'following' => 'フォロー中',
        'sign-up' => '会話に参加するにはサインアップまたはログインしてください。',
        'link-account' => 'Minecraft アカウントをリンクして会話に参加しましょう。',
        'placeholder' => 'What is happening?',
        'audience' => 'オーディエンス',
        'audience-title' => '誰がこれを見ることができますか？',
        'everyone' => '全員',
        'everyone-info' => 'SkinMCにいる人、いない人。',
        'followers' => 'フォロワー',
        'followers-info' => 'サインインまたはフォローしているメンバー。',
        'private' => '自分だけ',
        'private-info' => 'プライベート投稿のみが表示されます。',
        'submit' => '投稿',
        'like' => 'いいね！',
        'comment' => '返信',
        'share' => '共有',
        'share_dialog' => [
            'title' => 'Share',
            'subtitle' => 'Share this page with friends',
            'native' => 'Share via device',
            'copy_link' => 'Copy link',
            'social' => 'Popular networks',
            'copied' => 'Link copied!',
            'native_failed' => 'Could not open the share menu.',
            'native_unsupported' => 'Native sharing is not available on this device.',
            'close' => 'Close',
            'networks' => [
                'x' => 'Share on X',
                'facebook' => 'Share on Facebook',
                'reddit' => 'Share on Reddit',
                'whatsapp' => 'Share on WhatsApp',
                'telegram' => 'Share on Telegram',
                'email' => 'Share by email',
                'bluesky' => 'Share on Bluesky',
                'pinterest' => 'Pin on Pinterest',
            ],
        ],
        'remaining' => '残り',
        'profile' => ':username による投稿',
        'posts' => 'すべての投稿',
        'my-posts' => '自分の投稿',
        'view-all' => 'すべての投稿を表示',
        'post' => [
            'meta' => 'SkinMC上での:username ： :text',
            'title' => '投稿',
            'created' => 'ステータスの更新を投稿しました！',
            'confirm-delete' => 'この投稿を削除してもよろしいですか？元に戻すことはできません。',
            'delete' => '投稿を削除',
            'deleted' => '投稿が削除されました。',
        ],
        'repost' => [
            'button' => 'Repost',
            'quote_button' => 'Quote',
            'title' => 'Repost this post',
            'quote_title' => 'Quote post',
            'quote_label' => 'Add a comment (optional)',
            'quote_placeholder' => 'Add your thoughts...',
            'reposted' => 'reposted',
            'success' => 'Reposted!',
            'removed' => 'Repost removed.',
            'already_reposted' => 'You have already reposted this.',
            'undo' => 'Undo repost',
            'original_deleted' => 'The original post has been deleted.',
            'deleted_post' => 'This post has been deleted',
        ],
        'hashtags' => [
            'title' => 'Trending',
            'trending-now' => 'Trending now',
            'post' => 'post',
            'posts' => 'posts',
            'posts-count' => ':count post|:count posts',
            'hashtag' => 'Hashtag',
            'hashtags' => 'Hashtags',
            'no-results' => 'No hashtags found',
        ],
        'search' => [
            'title' => 'Search',
            'placeholder' => 'Search posts, hashtags...',
            'no-results' => 'No results found',
            'posts' => 'Posts',
            'no-hashtags-found' => 'No hashtags found matching ":query"',
            'no-results-found' => 'No results found for ":query"',
        ],
        'poll' => [
            'title' => 'Poll',
            'create' => 'Create a poll',
            'option' => 'Option',
            'add_option' => 'Add option',
            'duration' => 'Duration',
            'duration_1' => '1 day',
            'duration_3' => '3 days',
            'duration_7' => '7 days',
            'votes' => '{0} votes|{1} vote|[2,*] votes',
            'ended' => 'Poll ended',
            'ends_in' => 'Ends :time',
            'login_required' => 'Sign in to vote',
        ],
        'gif' => [
            'title' => 'GIF',
            'search_placeholder' => 'Search KLIPY for GIFs...',
            'no_results' => 'No GIFs found',
            'powered_by' => 'Powered by',
            'categories' => 'Categories',
            'trending' => 'Trending',
        ],
        'embed' => [
            'title' => 'Embed',
            'attach' => 'Attach',
            'attached' => 'Attached',
            'share_to_feed' => 'Share to feed',
            'search_placeholder' => 'Search by name or username',
            'loading' => 'Searching attachments...',
            'relevant_for_you' => 'Relevant for you',
            'no_relevant' => 'No personal suggestions yet. Start typing to search.',
            'start_typing' => 'Start typing to search attachments.',
            'no_results' => 'No matching attachments yet. Try another search.',
            'invalid' => 'Could not find that attachment. Please select it again.',
            'unavailable' => 'Attachment unavailable',
            'too_many_attachments' => 'You can only attach one item per post.',
            'types' => [
                'skin' => 'Skin',
                'skin_creation' => 'Skin creation',
                'server' => 'Server',
                'banner' => 'Banner',
                'cape' => 'Cape',
            ],
            'cape_subtitle' => [
                'official' => 'Official cape',
                'optifine' => 'OptiFine cape',
                'custom' => 'Custom cape',
            ],
        ],
        'image_preview' => [
            'image_singular' => 'image',
            'image_plural' => 'images',
            'selected' => 'selected',
            'clear_all' => 'Clear all',
            'selected_image_preview' => 'Selected image preview',
            'texture_upload_hint' => 'This image appears to be a Minecraft skin or cape texture. Please upload it properly as a skin or cape first, then share it to the feed from there.',
            'skin_upload' => 'Skin Upload',
            'cape_upload' => 'Cape Upload',
            'compress_image' => 'Compress Image',
        ],
        'image_too_large' => 'Your image exceeds 5MB',
        'compress_first' => 'Compress the image first.',
        'media' => 'Media',
        'follow-suggestions' => 'チームをフォロー',
        'explore' => '探索',
        'hashtag' => 'ハッシュタグ',
        'no_users' => 'No users found.',
        'stories' => [
            'archive' => [
                'title' => 'Story Archive',
                'subtitle' => 'Your archived stories are only visible to you',
                'empty' => 'No archived stories yet',
                'empty-description' => 'Stories you post will appear here after 24 hours.',
                'action' => 'Archive',
                'archived' => 'Story moved to archive.',
                'already-archived' => 'Story is already archived.',
            ],
        ],
    ],
    'private' => [
        'title' => '非公開投稿',
        'text' => 'この投稿は非公開です。',
    ],
    'liked' => [
        'title' => '「いいね」済み',
    ],
    'following' => [
        'title' => 'フォロー中',
        'text' => 'この投稿を表示するにはサインインしてください。',
    ],
    'tags' => [
        'empty' => '投票するタグはまだない',
        'empty-subtitle' => '最初に追加しよう',
    ],
    'inbox' => [
        'title' => 'メッセージ',
        'details' => '詳細',
        'message_user' => 'メッセージ',
        'write_message' => 'メッセージを書く',
        'empty' => [
            'no_message_selected' => 'メッセージが選択されていません',
            'open_or_start_conversation' => 'メッセージ一覧から会話を開くか、新しい会話を開始します。',
            'no_messages' => '未読メッセージはありません',
            'start_conversation' => '新しい会話を開始すると、ここにメッセージが表示されます。',
            'conversation' => ':username との会話の始まりです。',
            'users' => '現在のクエリに一致するユーザが見つかりません。',
        ],
        'typing' => ':username が入力しています...',
        'new_message' => '新しいメッセージ',
        'mark_unread' => '未読にする',
        'send_message' => 'メッセージを送信',
        'delete_message' => 'メッセージを削除',
        'latest_conversations' => '最近の会話',
        'delete_conversation' => '会話を削除',
        'show_details' => '詳細を表示',
        'hide_details' => '詳細を隠す',
        'unread' => '未読',
        'deleted' => '削除済み',
        'report_message' => 'メッセージを通報',
        'add_reaction' => 'リアクションを追加',
        'today' => '今日',
        'reconnect' => 'チャットするには、Minecraft アカウントを再接続してください',
        'account_disconnected' => 'このユーザーはリンクされたMinecraft アカウントとの接続を切断しました。',
        'saved_messages' => 'メッセージを保存しました',
        'new_message_to_label' => '宛先',
        'external-link-to' => 'このリンクをクリックすると',
        'external-link-confirmation' => '本当にそこへ行きますか？',
        'external-link' => '外部リンク',
        'reply' => 'Reply',
    ],
    'server' => [
        'manage' => [
            'stats' => '統計',
        ],
    ],
    'report' => [
        'button' => '報告',
        'title' => '通報内容',
        'describe' => 'これを報告する理由を英語で簡単に説明してください',
        'select' => '違反報告の理由を選択',
        'submit' => '通報する',
        'reasons' => [
            'INAPPROPRIATE_CONTENT' => '不適切なコンテンツ',
            'SPAM' => 'スパム',
            'HARASSMENT' => '嫌がらせ、迷惑',
            'OTHER' => 'その他',
        ],
    ],
    'leaderboard' => [
        'title' => 'リーダーボード',
        'description' => 'SkinMCのリーダーボードを見る。',
        'headline' => 'トップ 10',
        'all-time-invites' => 'すべての招待プレイヤー',
        'all-time-xp' => '通算XP',
        '30-day-xp' => '30日間のXP',
    ],
    'boards' => [
        'title' => 'Boards',
        'meta_title' => 'My Boards',
        'meta_description' => 'Organize your saved Minecraft skins, creations, and banners into boards.',
        'all_pins' => 'All Pins',
        'save' => 'Save',
        'saved' => 'Saved',
        'save_to_board' => 'Save to board',
        'save_to_label' => 'Save to: :board',
        'saved_to_label' => 'Saved to :board',
        'choose_board' => 'Choose board',
        'search_boards' => 'Search',
        'no_boards' => 'No boards yet',
        'no_boards_match' => 'No boards found',
        'create_board' => 'Create board',
        'create' => 'Create',
        'cancel' => 'Cancel',
        'add' => 'Add',
        'create_placeholder' => 'Like "Medieval Builds" or "PvP Loadouts"',
        'field_name' => 'Name',
        'secret_label' => 'Secret',
        'secret_description' => 'So only you and collaborators can see it.',
        'keep_secret' => 'Keep this board secret',
        'add_collaborators' => 'Add collaborators (optional)',
        'collaborator_search_placeholder' => 'Search by name or email',
        'edit_board' => 'Edit board',
        'leave_board' => 'Leave board',
        'leave_board_confirm' => 'Leave this board? You will no longer be able to add pins to it.',
        'delete_board' => 'Delete board',
        'delete_confirm' => 'Are you sure you want to delete this board? All pins will be removed.',
        'empty_headline' => 'No pins yet',
        'empty_subtitle' => 'Start saving skins, creations, and banners to this board.',
        'empty_boards_headline' => 'No boards yet',
        'empty_boards_subtitle' => 'Save your first skin to automatically create a board.',
        'browse_skins' => 'Browse skins',
        'pins_count' => '{0} No pins|{1} 1 pin|[2,*] :count pins',
        'secret_badge' => 'Secret',
        'public_boards' => 'Boards',
        'collaborator_unknown_user' => 'Someone',
        'collaborating' => 'Collaborating',
        'your_boards' => 'Your boards',
        'boards_you_collaborate_on' => 'Boards you collaborate on',
        'empty_collaborating' => 'No boards you collaborate on yet.',
        'toast' => [
            'saved_to' => 'Saved to :board',
            'removed' => 'Pin removed',
            'created' => 'Board created',
            'updated' => 'Board updated',
            'deleted' => 'Board deleted',
            'collaborator_added' => 'Collaborator added',
            'collaborator_removed' => 'Collaborator removed',
            'left_board' => 'You left the board',
        ],
    ],
];
