<?php

return [
    'skins' => 'Skinler',
    'avatars' => 'Avatarlar',
    'editor' => 'Düzenleyici',
    'heads' => 'Kafalar',
    'capes' => 'Pelerinler',
    'servers' => 'Sunucular',
    'achievement' => 'Başarımlar',
    'armor' => 'Zırh Askısı',
    'banners' => 'Flamalar',
    'profile' => 'My profile',

    'generators' => 'Generators',

    'logout' => 'Çıkış',
    'register' => 'Kaydol',
    'login' => 'Giriş yap',
    'about' => 'Hakkında',
    'contact' => 'İletişim',
    'faqs' => 'SSS',

    'minecraft_name' => 'Minecraft Adı',
    'minecraft_uuid' => 'Minecraft UUID',
    'what' => 'What',
    'recent_searches' => 'Son aramalar',
    'username' => 'Kullanıcı Adı',
    'uuid' => 'UUID',
    'search' => 'Arama',
    'search_placeholder' => 'Deneme',
    'search_placeholder_uuid' => 'UUID\'yi girin',
    'start_search' => 'Aramaya başla',
    'cancel_search' => 'Vazgeç',
    'search_type' => 'Arama Tipi',
    'search_type_all' => 'All results',
    'profiles' => '',
    'view_skin' => 'View skin',
    'edit_skin' => 'Skin\'i düzenle',
    'make_avatar' => 'Avatar yap',
    'find_heads' => 'Oyuncu kafalarını bulun',

    'home' => 'Ana sayfa',
    'help' => 'Yardım',
    'tools' => 'Araçlar',
    'more-tools' => 'More tools',
    'skin_viewer' => 'Skin görüntüleyici',
    'avatar_maker' => 'Avatar yapımcısı',
    'collections' => 'Koleksiyon',
    'popular_skins' => 'Popüler Skinler',
    'cartoon_skins' => 'Karikatür skinleri',
    'animal_skins' => 'Hayvan skinleri',
    'community' => 'Topluluk',
    'imprint' => 'Künye',
    'cookies' => 'Çerezler',
    'terms' => 'Terms of Service',
    'privacy' => 'Privacy policy',
    'app' => 'App',
    'mod' => 'Mod',
    'totem' => 'Totems',

    'feedback' => 'Feedback',
    'status' => 'Status',
    'recent_searches_placeholder' => 'As you start searching, your past searches will show here.',
    'recent_views_placeholder' => 'After visiting some profiles, your past visited ones will show here.',
    'moderate' => 'Orta düzeyde',
    'listings' => 'Listings',
    'add' => 'Add',

    'theme' => [
        'dark' => 'Dark',
        'light' => 'Light',
        'auto' => 'Automatic'
    ],
];
