<?php

return [
    'skins' => 'Skinler',
    'avatars' => 'Avatarlar',
    'editor' => 'Düzenleyici',
    'heads' => 'Kafalar',
    'capes' => 'Pelerinler',
    'servers' => 'Sunucular',
    'achievement' => 'Başarımlar',
    'armor' => 'Zırh Askısı',
    'banners' => 'Flamalar',
    'banner' => 'Banner Editor',
    'profile' => 'Profilim',

    'generators' => 'Oluşturucular',

    // Navigation dropdowns
    'feed' => 'Feed',
    'discover' => 'Discover',
    'mods' => 'Mods',
    'shaders' => 'Shaders',
    'resource_packs' => 'Resource Packs',
    'modpacks' => 'Modpacks',
    'datapacks' => 'Data Packs',
    'plugins' => 'Plugins',

    'logout' => 'Çıkış',
    'register' => 'Kaydol',
    'login' => 'Giriş yap',
    'about' => 'Hakkında',
    'contact' => 'İletişim',
    'faqs' => 'SSS',

    'minecraft_name' => 'Minecraft Adı',
    'minecraft_uuid' => 'Minecraft UUID',
    'what' => 'Başlık',
    'recent_searches' => 'Son aramalar',
    'username' => 'Kullanıcı Adı',
    'uuid' => 'UUID',
    'search' => 'Arama',
    'search_placeholder' => 'Şunu Deneyin',
    'search_placeholder_uuid' => 'UUID\'yi girin',
    'start_search' => 'Aramaya başla',
    'cancel_search' => 'Vazgeç',
    'search_type' => 'Arama Tipi',
    'search_type_all' => 'Tüm sonuçlar',
    'profiles' => 'Profiller',
    'view_skin' => 'Skin\'i görüntüle',
    'edit_skin' => 'Skin\'i düzenle',
    'make_avatar' => 'Avatar yap',
    'find_heads' => 'Oyuncu kafalarını bulun',
    'no_results_found' => 'No suggestions yet. Hit Enter to look it up.',

    'home' => 'Ana sayfa',
    'help' => 'Yardım',
    'tools' => 'Araçlar',
    'more-tools' => 'Daha fazla araç',
    'skin_viewer' => 'Skin görüntüleyici',
    'avatar_maker' => 'Avatar yapımcısı',
    'collections' => 'Koleksiyon',
    'popular_skins' => 'Popüler Skinler',
    'cartoon_skins' => 'Karikatür skinleri',
    'animal_skins' => 'Hayvan skinleri',
    'community' => 'Topluluk',
    'imprint' => 'Künye',
    'cookies' => 'Çerezler',
    'terms' => 'Hizmet Şartları',
    'privacy' => 'Gizlilik politikası',
    'app' => 'Uygulama',
    'mod' => 'Mod',
    'totem' => 'Totemler',
    'cube' => 'Cube',
    'new' => 'New',

    'feedback' => 'Geri Bildirim',
    'status' => 'Durum',
    'recent_searches_placeholder' => 'Aramaya başladığınızda, geçmiş aramalarınız burada gösterilecektir.',
    'recent_views_placeholder' => 'Bazı profilleri ziyaret ettikten sonra, daha önce ziyaret ettiğiniz profiller burada gösterilecektir.',
    'moderate' => 'Orta düzeyde',
    'listings' => 'Listeler',
    'add' => 'Ekle',

    // Autocomplete types
    'autocomplete' => [
        'profile' => 'Profile',
        'server' => 'Server',
        'project' => 'Project',
        'skin_tag' => 'Skin Tag',
        'server_category' => 'Server Category',
        'modrinth_category' => 'Project Category',
    ],

    'theme' => [
        'title' => 'Theme',
        'dark' => 'Koyu',
        'light' => 'Aydınlık',
        'auto' => 'Auto',
    ],

    'language' => 'Language',
];
