<?php

return [
    'auth' => [
        'login' => [
            'title' => 'SkinMC\'ye hoş geldiniz',
        ],
        'register' => [
            'title' => 'SkinMC\'ye kaydolun',
            'subtitle' => 'Başlayın ve tam erişim için hesabınızı oluşturun.',
        ],
    ],

    'home' => [
        'hero_slogan' => 'Minecraft Skins için yeriniz.',
        'hero_slogan_alt_1' => 'Everything Minecraft. One place.',
        'hero_slogan_alt_2' => 'Where Minecrafters meet.',
        'hero_cta' => 'Şaşırt beni',
        'hero_explore_cta' => 'Ciltleri keşfedin',
        'skin_viewer' => 'Skin görüntüleyici',
        'skin_viewer_detail' => 'Araştır :count Skinleri',
        'skin_editor' => 'Skin düzenleyici',
        'skin_editor_detail' => 'Kendi skiniz\'i tasarlayın',
        'avatar_maker' => 'Avatar oluşturucu',
        'avatar_maker_detail' => 'Özel Minecraft avatar profil resimlerinizi oluşturun.',
        'trending' => 'Trend olan',
        'minecraft_skin' => 'Minecraft skin',
        'favourite' => 'Favori',
        'collections' => 'Koleksiyon',
        'collections_detail' => 'Her durum için küratörlüğünde Minecraft skinleri',
        'about_skinmc' => 'SkinMC Hakkında',
        'about_find' => 'Herhangi bir skin bulun',
        'about_find_detail' => 'Bir sonraki yeni skinizi bulmak, görüntülemek ve indirmek için herhangi bir Minecraft Kullanıcı Adı için SkinMC aramasını kullanın.',
        'about_download' => 'İndirin veya düzenleyin',
        'about_download_detail' => 'Beğendiğiniz bir kaplama mı buldunuz? Favorilerinize ekleyin, düzenleyin veya indirin ve kendinize ait hale getirin.',
        'about_platform' => 'Çapraz platform',
        'about_platform_detail' => 'Dış görünümü hareket halindeyken de kullanmak ister misiniz? QR kodunu tarayın ve Minecraft PE için görüntüyü telefonunuza kaydedin.',
        'meta' => [
            'title' => 'Minecraft Skin Görüntüleyici',
            'description' => 'Minecraft skinlerini görüntüleyin ve indirin, seçilmiş koleksiyonlardaki en iyi skinleri keşfedin, kullanıcı adı kullanılabilirliğini ve geçmişini kontrol edin ve çok daha fazlasını yapın!',
        ],
        'recently_viewed' => 'Son görüntülenenler',
        'explore_title' => 'Yeni bir şey deneyin',
        'explore' => 'Yeni fikirler ve araçlar keşfedin',
        'servers_browse' => 'Sunuculara göz atın',
        'servers' => 'En iyi Minecraft Sunucularını keşfedin',
        'heads' => 'Minecraft kafaları',
        'head_description' => 'Minecraft kafaları veritabanına göz atın veya yenilerini oluşturun.',
        'achievement' => 'Başarım oluşturucu',
        'achievement_detail' => 'Kendi, özel ve kişiselleştirilmiş başarımlarınızı oluşturun.',
        'continue' => 'Göz atmaya devam edin',
        'totem' => 'Minecraft Totem Generator',
        'totem_description' => 'Create a custom Minecraft resource pack with a Totem of Undying from any skin.',
        'banner' => 'Minecraft Banner Generator',
        'banner_description' => 'Generate and preview custom Minecraft banners and patterns.',
        'capes' => 'Minecraft Capes',
        'capes_description' => 'Browse the largest collection of Minecraft capes, or create your own.',

    ],
    'profile' => [
        'verified' => 'Doğrulanmış profil',
        'minecraft_profile' => 'Minecraft profili',
        'show_qr_code' => 'QR kodunu göster',
        'favourite' => 'Favori',
        'user_title' => ':username Minecraft Skini',
        'user_views' => 'Görüntülenen :views time|Viewed :views süreleri',
        'uuid' => 'UUID',
        'copy' => 'Kopyala',
        'link' => 'Bağlantı',
        'skin_history' => 'Minecraft görünüm geçmişi (:skins)',
        'username_history' => 'Kullanıcı adı geçmişi',
        'username_history_name' => 'İsim',
        'username_history_timestamp' => 'Değiştirildi',
        'username_history_initial_name' => 'İlk isim',
        'user_downloads' => ':downloads download|:downloads indirmeler',
        'download_skin' => 'Skin indir',
        'apply_skin' => 'Skin uygulayın',
        'capes' => 'Pelerinler',
        'claim_profile' => 'Siz :username misiniz? Profilinizi doğrulamak ve özelleştirmek için sahiplenin!',
        'claimed' => 'Sahiplenmiş Profil',
        'meta_description' => 'Görüntüleyin ve indirin View and download :username Minecraft Skin. UUID\'lerini, isim geçmişlerini, ayrıntılı istatistiklerini ve daha fazlasını görün',
        'created_at' => 'Güncellendi: :changed_at',
        'skins' => [
            'meta_title' => ':username Minecraft Geçmişi',
            'meta_description' => 'Görünüm :username Minecraft Skinleri geçmişi ve daha önce kullanılan Skinler. Eski veya geçmişte kullanılan kaplamalara göz atmak, yedeklemek ve geri almak veya yeni kaplamalar toplamak için geçmişi kullanın.',
            'title' => 'Minecraft Skin geçmişi',
        ],
        'qr_code' => [
            'meta_title' => ':kullanıcı adının QR Kodu',
            'meta_description' => ':kullanıcı adı Özel Minecraft Profili QR Kodu',
        ],
        'sub_nav' => [
            'skin' => 'Cilt',
            'about' => 'Hakkında',
            'usernames' => 'Kullanıcı adları',
            'head' => 'Kafa',
            'comments' => 'Yorumlar',
        ],
        'cape' => 'Pelerin',
        'elytra' => 'Elitra',
        'nametag' => 'İsim etiketi',
        'animation' => 'Animasyon',
        'rotation' => 'Rotasyon',
        'none' => 'Hiçbiri',
        'idle' => 'Boşta',
        'walk' => 'Yürümek',
        'run' => 'Koşmak',
        'fly' => 'Uçmak',
        'follow' => 'Takip et',
        'following' => 'Takip etmek',
        'unfollow' => 'Takibi bırak',
        'followers' => 'Takipçi|Takipçiler',
        'toast' => [
            'following' => 'Şimdi takip ediyorsunuz :kullanıcı adı!',
            'follow-self-error' => 'Üzgünüm :kullanıcı adı, kendinizi takip edemezsiniz.',
            'unfollowed' => 'Takibi bıraktınız :username',
        ],
        'edit' => 'Profili düzenle',
        'joined' => 'Katıldım',
        'role' => 'Role',
        'server-fav-list-empty' => 'Görünüşe göre :username kullanıcısının henüz favori sunucusu yok. :username bir sunucuyu favori olarak kaydettiğinde, onu burada görebilirsiniz.',
        'server-own-list-empty' => 'Görünüşe göre :username henüz herhangi bir sunucuya sahip değil. :username bir sunucu listelediğinde, onu burada görebilirsiniz.',
        'capes-list-empty' => 'Görünüşe göre :username henüz pelerin giymiyor. :username pelerin giydiğinde, bunu burada görebilirsiniz.',
        'feed-own-list-empty' => 'Görünüşe göre henüz feed\'e hiçbir şey göndermediniz! Gönderdiğinizde, gönderilerinizi burada görebilirsiniz.',
        'feed-list-empty' => 'Hmm, görünüşe göre :username henüz feed\'e hiçbir şey paylaşmamış. :username bir şey paylaştığında, bunu burada görebilirsiniz.',
        'following-own-list-empty' => 'Görünüşe göre henüz kimseyi takip etmiyorsunuz! İnsanları takip etmeye başladığınızda, onları burada görebilirsiniz.',
        'following-list-empty' => 'Hmm, :kullanıcı adı kimseyi takip etmiyor gibi görünüyor. Kullanıcı adı kişileri takip etmeye başladığında onları burada görebilirsiniz.',
        'followers-own-list-empty' => 'İnsanlar profilinizi takip etmeye başladığında, burada görüneceklerdir.',
        'followers-list-empty' => 'Hmm, :username kimse tarafından takip edilmiyor gibi görünüyor. Takip eden ilk kişi sen ol :username. Daha fazla kişi takip ettiğinde, onları burada görebilirsiniz.',
        'render' => 'Görüntüleyici',
        '3d' => '3D görüntü',
        '2d' => '2D görüntü',
        'name-history-info' => 'Kullanıcı Adı Geçmişi ortadan kalkıyor. Mojang, 13 Eylül 2022 tarihinde isim geçmişi API\'sine erişim desteğini kaldırdı ve bu da doğru bir isim geçmişinin artık mevcut olmamasına neden oldu. İsim geçmişinizi gizlemek istiyorsanız, profilinizi talep edin ve özel yapmak için ayarlara gidin.',
        'edit-skins' => 'Cilt geçmişini düzenleme',
        'hide-skin' => 'Cildi Gizle',
        'show-skin' => 'Cildi Göster',
        'edit-skin' => 'Cildi düzenle',
        'servers' => [
            'title' => ':username kullanıcısının sunucuları',
        ],
        'cape-list' => [
            'title' => ':username kullanıcısının pelerinleri',
        ],
    ],
    'skin' => [
        'meta' => [
            'title' => ':username Minecraft Skini',
            'description' => 'Minecraft Kaplaması. Kaplamayı indirip görüntüleyin ve hangi oyuncuların da aynı kaplamayı giydiğini görün.',
            'tags' => ':username Minecraft Cilt, :username Cilt, Minecraft Skin, :username Özel Minecraft Cildi, Cilt İndir, Aynı Cilde sahip oyuncular',
        ],
        'title' => ':username Minecraft Cildi',
        'head' => 'Baş komutları',
        'head_info' => 'Komut blokları ile kullanmak için',
        'first_wearing' => 'Bu Cildi giyen ilk oyuncu',
        'profiles' => ':profiller profil|:profiller profiller',
        'profiles_title' => ':profiles bu cilt ile profil|:profiles bu cilt ile profiller',
        'screenshot' => 'Ekran görüntüsü',
    ],
    'skins' => [
        'meta' => [
            'title' => 'Sayfa :current - Tüm Minecraft Ciltleri',
            'description' => 'Son sayfalardaki :total özel Minecraft kaplamaları listemize göz atın ve sıradaki favori kaplamanızı indirin!',
            'tags' => ':username Minecraft Cilt, :username Cilt, Minecraft Cilt, :username Özel Minecraft Cilt, Cilt İndir, Aynı Cilde sahip oyuncular',
            'tags-title' => ':tag Minecraft Ciltleri',
            'tags-description' => 'Toplam :tag Minecraft kaplamalarından oluşan :last pages listemize göz atın ve en sevdiğiniz :tag kaplamasını indirin!',
            'tags-metatags' => ':tag Minecraft Skin, :tag Skin, Minecraft Skin, :tag Özel Minecraft Skin, İndir :tag Skin, Minecraft :tag Skins',
        ],
        'title-skin-tags' => 'Etiketlenmiş Minecraft Clitleri',
        'subtitle' => 'Page :current of :last from :total Minecraft Skins',
        'subtitle-skin-tags' => 'Page :current of :last from :total Tagged Minecraft Skins',
        'sort_by' => 'Şuna göre sırala',
        'latest' => 'Son Ciltler',
        'most_profiles' => 'En çok kullanılan skinler',
        'profiles_today' => 'Bugün en çok kullanılan',
        'profiles_this_week' => 'Bu hafta en çok kullanılan',
        'profiles_this_month' => 'Bu ay en çok kullanılan',
        'default' => 'Varsayılan Sıralama',
        'this_month' => 'Bu ay eklendi',
        'this_week' => 'Bu hafta eklendi',
        'today' => 'Bugün eklendi',
        'random' => 'Rastgele',
        'similar' => 'Benzer Ciltler',
        'no_similar_skins' => 'Henüz benzer skinler bulunamadı.',
        'favorite' => ':count favori|:count favori',
    ],
    'skin-tags' => [
        'faq' => 'Etiketler nedir?',
        'about' => 'Etiketler, dış görünümlere ilgili kategoriler eklemenin bir yoludur. Etiket eklemek, beğendiğiniz daha fazla dış görünümü kolayca keşfetmenizi sağlar!',
        'guidelines' => [
            'good' => [
                'title' => 'İyi etiketler için genel kurallar şunlardır:',
                'short' => 'Kısa',
                'descriptive' => 'Tanımlayıcı & Açıklayıcı',
                'spelled' => 'Doğru Yazıldı',
            ],
            'bad' => [
                'title' => 'Gibi etiketler eklemeyin:',
                'general' => 'Çok genel',
                'specific' => 'Çok spesifik',
                'too-many-tags' => 'Üç ayrı etiket olmalıdır',
                'spelling' => 'Şöyle olmalı :example',
            ],
        ],
        'toast' => [
            'added' => 'Oylama için “:tag” etiketi eklendi',
            'removed' => '“:tag” etiketi kaldırıldı',
            'upvote' => '”:tag” beğenildi',
            'downvote' => '”:tag” beğenilmedi',
        ],
        'vote' => [
            'up' => 'Yukarı oy',
            'down' => 'Aşağı oy',
            'remove' => 'Oylamayı kaldır',
        ],
    ],
    'contact' => [
        'contact' => 'İletişim',
        'email' => 'Sorularınız için lütfen <a href="mailto:support@skinmc.net">support@skinmc.net</a> adresinden bize yazmaktan çekinmeyin.',
        'faq' => 'Sorunuz zaten orada yanıtlanmışsa, öncelikle <a href=":link">FAQ page</a> göz atmanızı rica ederiz.',
        'other' => 'Bağlanmanın diğer yolları',
        'other_discord' => 'Discord sunucusuna katılın ve diğer kullanıcılarla bağlantı kurun, oyunlar hakkında sohbet edin, en sevdiğiniz favori paketleri paylaşın ve topluluktan yardım alın.',
        'other_twitter' => 'Twitter\'da takip ederek yeni güncellemelerin veya özelliklerin ne zaman yayınlandığını öğrenin, haftanın temalarını görün ve daha fazlasını keşfedin.',
        'other_instagram' => 'Yeni öne çıkan harika Minecraft Ciltlerini ve görsellerine göz atmak ve keşfetmek için SkinMC\'yi Instagram\'da takip edin.',
        'other_facebook' => 'Facebook\'ta hayran olun ve Minecraft içeriğini keşfederken yorum yapabileceğiniz ve başkalarıyla konuşabileceğiniz tüm gönderileri görün.',
    ],
    'about' => [
        'intro' => '<span>Minecraft</span> <span>Skinleri</span> <span>için</span> <span>platformunuz.</span>',
        'header_credit' => '“Epic Nether Battle” adlı illüstrasyon',
        'info' => 'Her şeyin kaydını tutun.',
        'info_explainer' => 'Bir oyuncunun isim geçmişini görüntüleyin, önceki görünümlerini görün, arkadaş olarak ekleyin, görünümleri indirin ve hatta ayrıntı istatistiklerini alın.',
        'card_find_title' => 'Herhangi bir Minecraft Oyuncusunu Bul',
        'card_find_detail' => 'İstediğiniz herhangi bir oyuncunun kullanıcı adını veya UUID\'sini arayarak başlayın.',
        'card_view_title' => 'Görüntüle, kaydet ve düzenle',
        'card_view_detail' => 'Beğendiğiniz bir tema buldunuz mu? İndirerek kaydedin veya düzenleyiciyi kullanarak kendi temanızı oluşturun.',
        'card_claim_title' => 'Doğrulanın',
        'card_claim_detail' => 'Minecraft hesabını bağla ve profilini talep ederek harika yeni özelliklerin kilidini aç!',
        'card_customise_title' => 'Profilinizi özelleştirin',
        'card_customise_detail' => 'Doğrulanmış oyuncular sosyal medya bağlantılarını ekleyebilir ve profillerini kendilerine ait hale getirebilirler.',
        'card_friends_title' => 'Arkadaşlarınızı ekleyin',
        'card_friends_detail' => 'SkinMC\'de arkadaşlarınızla bağlantı kurun ve profilinizde arkadaş listenizi gösterin.',
        'card_history_title' => 'Kullanıcı adı ve skin geçmişi',
        'card_history_detail' => 'Gelişmiş arama özelliğini kullanarak bir oyuncunun kullanıcı adı/skin geçmişini bulabilir ve görüntüleyebilirsiniz.',
        'founders' => 'Kurucular',
        'founders_cofounder' => 'SkinMC\'nin kurucu ortağı',
        'head_of_design' => 'Tasarım başkanı',
        'head_of_code' => 'Kod başkanı',
        'feedback' => 'Bize geri bildirimde bulunun',
        'faq' => 'Minecraft, Skinler ve daha fazlası hakkında sorularınız mı var? En sık sorulan soruların yanıtlarını içeren SSS bölümümüzü okuyun.',
        'faq_link' => 'SSS merkezini ziyaret edin',
        'contact' => 'İletişim kurmak mı istiyorsunuz veya başka sorularınız mı var? Doğrudan bizimle iletişime geçin.',
        'contact_link' => 'Bize ulaşın',

    ],
    'faq' => [
        'title' => 'SSS',
        'subtitle' => 'Sıkça sorulan sorular',
        'help' => 'Daha fazla yardıma ihtiyacın mı var?',
        'discord' => 'Diğer Minecraft oyuncularıyla sohbet etmek için Discord sunucusuna katılın.',
        'contact' => 'Bize ulaşın',
        'q' => [
            'change_skin_t' => 'Minecraft Skin\'imi nasıl değiştiririm?',
            'change_skin' => '
                <p>To change your Skin do the following:</p>
                <ol>
                    <li>Visit <a href="https://my.minecraft.net/en-us/login/">https://my.minecraft.net/en-us/login/</a> and sign in with your Mojang account.</li><li>Once signed in, select <b>"Skin"</b> on the left menu.</li><li>Then, choose a Model you prefer and upload a the Skin of your liking.</li>
                </ol>',
            'change_username_t' => 'Minecraft kullanıcı adımı nasıl değiştiririm?',
            'change_username' => '
                <p>To change your Username do the following:</p>
                <ol>
                    <li>Visit <a href="https://account.mojang.com/login" target="_blank" rel="nofollow">https://account.mojang.com/login</a> and log in with your Mojang account.</li>
                    <li>Find your Minecraft Profile Name and press the <b>"(Change)"</b> button</li>
                    <li>On the next page, enter your desired new username.</li>
                    <li>Finally, confirm the changes by entering your password and pressing "Change name".</li>
                </ol>',
            'dl_t' => 'Birinin Minecraft Skin\'ini nasıl indirebilirim?',
            'dl' => '
                <p>To download anyones Minecraft Skin do the following:</p>
                <ol>
                    <li>Press on the search bar and enter the username of the player you would like to download the skin from.</li>
                    <li>On the profile page you can preview the skin</li>
                    <li>Click on the <strong>Download Skin</strong> button under the preview</li>
                </ol>',
            'submit_q' => 'Bir koleksiyona nasıl skin gönderebilirim?',
            'submit_a' => '<p>Please fill out the following short form with the usernames and their category of which you would like to add to the collections. <a href="https://forms.gle/f4Jh5RpGfsHAZ5xE8" target="_blank">Collection submission form</a>',
            'mcpe_t' => 'Minecraft PE\'de Skin kullanabilir miyim?',
            'mcpe' => '
                <p>Yes. To use the Skin in Minecraft Pocket Edition do the following:</p>
                <ol>
                    <li>Open SkinMC.net on your smartphone and tap the search bar</li>
                    <li>Enter the username of the player\'s skin you would like to download</li>
                    <li>Tap the <strong>Download Skin</strong> button under the preview </li>
                    <li>Open Minecraft PE and tap on <strong>Profile</strong> on the right side</li>
                    <li>Tap on the <strong>+</strong>, or edit character and go to the "classic skins tab"</li>
                    <li>Tap on "owned", then "import", then "choose new skin"</li>
                </ol>',
            'change_times_t' => 'Kullanıcı adımı ne sıklıkla değiştirebilirim?',
            'change_times' => '<p>Minecraft kullanıcı adınızı her <strong>30 günde bir</strong> <strong>bir kez</strong> değiştirebilirsiniz.</p>',
            'available_t' => 'Kullanıcı adımı değiştirdikten sonra, diğer kullanıcılar ne zaman bu kullanıcı adını talep edebilir?',
            'available' => '<p>If you want to change back to your previous username, you can change back <strong>after 30 days.</strong> Everyone else needs to wait an additional <strong>7 days</strong> (37 days after changing) before they can claim your old username. </p>',
            'username_history_t' => 'Kullanıcı adı geçmişimi silebilir misiniz lütfen?',
            'username_history' => '
                <p>As the username history data comes from Mojang, the username history can not be removed. Mojang has previously stated that their intention was that previous usernames can be seen¹, and that they provide a direct method for the public to access this information².</p>
                <p class="font-14">¹<a href="https://help.minecraft.net/hc/en-us/articles/360034636712-Minecraft-Usernames" target="_blank" rel="noreferrer">https://help.minecraft.net/hc/en-us/articles/360034636712-Minecraft-Usernames</a></p>
                <p class="font-14 mb-0">²<a href="https://twitter.com/dinnerbone/status/554739042529849345" target="_blank" rel="noreferrer">https://twitter.com/dinnerbone/status/554739042529849345</a> (Tweet archived 2 years ago: <a href="http://archive.is/TeAyj" target="_blank" rel="noreferrer">http://archive.is/TeAyj</a>)
                </p>',
        ],
    ],
    'avatars' => [
        'start' => [
            'title' => 'Kendi Minecraft avatarınızı oluşturun',
            'subtitle' => 'Minecraft avatar oluşturucuyu kullanarak herhangi bir görünümden eğlenceli bir avatar oluşturun!',
            'avatar_face' => 'Yüz stili avatar',
            'avatar_bust' => 'Göğüs stili avatar',
            'avatar_cube' => 'Küp stili avatar',
            'avatar_head3d' => 'Özel 3D kafa',
        ],
        'user' => [
            'title' => 'Cilt Seç',
            'subtitle' => 'Oluşturmak istediğiniz avatar için Minecraft kullanıcı adını girin',
            'form_label' => 'Minecraft kullanıcı adı',
            'form_submit' => 'Devam',
        ],
        'output' => [
            'title' => 'Önizle ve kaydet',
            'subtitle' => 'Yeni Minecraft avatarınızı kullanmanın keyfini çıkarın',
            'download_info' => 'Sonuçtan memnun musunuz? Yeni avatarınızı buradan indirerek kullanmaya başlayın',
            'download_button' => 'Avatarı indir',
            'avatar_style' => 'Avatar stili',
            'skin_username' => 'Skin kullanıcı adı',
            'change' => 'Değiştir',
            'generate' => 'Oluştur',
            'avatar_colour' => 'Arka plan rengi',
            'avatar_colour_palette' => 'Palet',
            'avatar_colour_basic' => 'Temel',
        ],
        'meta' => [
            'title' => 'Minecraft Avatar Oluşturucu',
            'description' => 'Minecraft Avatar Oluşturucu: Minecraft görünümünüzü kullanarak özel Minecraft profil resimleri oluşturun',
        ],
    ],
    'totem' => [
        'title' => 'Özel Minecraft Totemi',
        'subtitle' => 'Minecraft Totem oluşturucuyu kullanarak herhangi bir görünümden Ölümsüz Totem içeren özel bir kaynak paketi oluşturun.',
        'download_info' => 'Önizlemeyi beğendiniz mi? Özel kaynak paketinizi kaydetmek için Minecraft sürümünüzü seçin:',
        'meta' => [
            'title' => 'Özel Minecraft Totemi Oluşturucu',
            'description' => 'Özel Minecraft Totemleri: Kendi veya başka oyuncuların Minecraft skin\'lerini kullanarak Ölümsüzlük Totemi ile özel bir Minecraft Kaynak Paketi oluşturun.',
        ],
        'type' => [
            'mini' => 'Skin\'inizin mini versiyonu!',
            'full' => 'Skin\'inizin tam versiyonu!',
            'model3d' => 'Skin\'inizin 3d model versiyonu!',
            'add_designs' => 'Daha fazla tasarım görmek ister misiniz? Tasarım önerinizi buradan gönderin:',
        ],
    ],
    'achievement' => [
        'header' => [
            'title' => 'Kendi Minecraft başarımınızı oluşturun',
            'subtitle' => 'Minecraft Başarım Oluşturucuyu kullanarak kendi özel başarımınızı oluşturun ve istediğiniz her alanda ilerlemenizi gösterin!',
        ],
        'generator' => [
            'yellow_text' => 'Sarı yazı',
            'white_text' => 'Beyaz yazı',
            'choose_icon' => 'Simge seç',
            'face' => 'Simge yerine Minecraft yüzü',
            'form_submit' => 'İndir',
            'form_label' => 'Minecraft kullanıcı adı',
            'download' => 'İndir',
            'embed' => 'Gömülü',
            'embed_copy' => 'Kopyala',
        ],
        'meta' => [
            'title' => 'Minecraft Başarım Oluşturucu',
            'description' => 'Başarım oluşturucusu ile özel Minecraft Başarımları ve İlerlemeleri oluşturun. Görüntüyü doğrudan indirin, forum imzalarında kullanın, HTML veya BB koduyla gömün ve daha fazlasını yapın',
        ],
    ],
    'armor' => [
        'header' => [
            'title' => 'Minecraft Zırh Standı Oluşturucu',
            'subtitle' => 'Kendi özel Minecraft Zırh Standlarınızı oluşturun ve tasarlayın. Farklı pozlar, pozisyonlar oluşturun, öğeleri yerleştirin ve çok daha fazlasını yapın.',
        ],
        'meta' => [
            'title' => 'Minecraft Zırh Standı Oluşturucu',
            'description' => 'Özel Minecraft Zırh Standlarını kolayca oluşturun ve tasarlayın. Editör, farklı pozlar, konumlar, öğeleri yerleştirme, özel görünümler ve çok daha fazlasını yapmanıza yardımcı olur.',
        ],
    ],
    'banner' => [
        'editor' => [
            'header' => [
                'title' => 'Minecraft Flama Düzenleyici',
                'subtitle' => 'Kendi özel Minecraft Flamalarınızı tasarlayın ve oluşturun. Bunlar dünyanızı süslemek için kullanılabilir veya genellikle <a href="https://optifine.net" target="_blank" rel="nofollow">Optifine</a> pelerinleri olarak da kullanılır.',
            ],
            'meta' => [
                'title' => 'Minecraft Flama Oluşturucu',
                'description' => 'Oyundaki tüm desen ve renkleri kullanarak kendi özel Minecraft Flama tasarımlarınızı oluşturun ve tasarlayın! Bunlar, dünyanızı süslemek için kullanılabilir veya Flama Pelerinini kullanarak Optifine Pelerin olarak giyilebilir. Flamalar veya kalkanlar için hediye kodları oluşturabilirsiniz.',
            ],
            'toolbar' => [
                'title' => 'Banner Editor',
                'randomise' => 'Randomise',
                'clear_layers' => 'Clear layers',
                'help' => 'Help',
                'save_banner' => 'Save banner',
                'submit_to_gallery' => 'Add to gallery',
                'reset_from_url' => 'Load from link',
                'minecraft_version' => 'Minecraft version',
                'texture_type' => 'Texture type',
                'banner' => 'Banner',
                'shield' => 'Shield',
                'version_1_21' => '1.21+',
                'version_1_16' => '1.16 - 1.20',
                'version_1_13' => '1.13 - 1.15',
                'version_1_8' => '1.8 - 1.12',
            ],
            'tools' => [
                'share_link' => 'Share link',
                'share_link_placeholder' => 'Share link',
                'generate_codes' => 'Generate codes',
                'target_selector' => 'Target selector',
                'command_give' => 'Give',
                'command_setblock' => 'Setblock',
                'command_replaceitem_shield' => 'Shield',
                'code_placeholder' => 'Pick a command to generate code',
                'import_code' => 'Import code',
                'background_grass' => 'Grass background',
            ],
            'modal' => [
                'save_banners' => 'Saved banners',
                'share_saved_gallery' => 'Share saved gallery',
                'share_saved_gallery_placeholder' => 'Share saved gallery',
                'export_to_chest' => 'Export to chest',
                'delete_all' => 'Delete all',
            ],
        ],
        'gallery' => [
            'header' => [
                'title' => 'Minecraft Flama Galerisi',
                'subtitle' => 'Browse the gallery of :count custom designed Minecraft banners and patterns. Use it as a shield or cape to make your Minecraft skin more unique, or as a flag to decorate your world.',
            ],
            'meta' => [
                'title' => 'Minecraft Flama Galerisi',
                'description' => 'Browse the gallery of :count custom designed Minecraft Banners. You can use a Banner Design and Pattern as a Shield or cape to make your Minecraft skin more unique, or use it as a flag to decorate your world.',
            ],
            'add_design' => 'Add design',
            'sort' => 'Sort:',
            'sort_trending' => 'Trending',
            'sort_best' => 'Best of',
            'sort_newest' => 'Newest',
            'sort_oldest' => 'Oldest',
            'sort_favorites' => 'Most favourites',
            'sort_views' => 'Most views',
            'sort_last_week' => 'Last week',
            'sort_last_30d' => 'Last 30 days',
            'clear_filters' => 'Clear filters',
            'no_banners' => 'No banners yet',
            'no_banners_message' => 'No designs yet. Be the first to share one.',
            'create_banner' => 'Create a banner',
        ],
        'publish' => [
            'title' => 'Publish banner',
            'publish_button' => 'Publish',
            'title_label' => 'Title',
            'description_label' => 'Description',
            'tags_label' => 'Tags',
            'tags_max_reached' => 'Maximum 5 tags reached',
            'tags_add_placeholder' => 'Add a tag',
            'tags_help' => 'Press enter, tab, or comma to add a tag.',
            'tags_max_error' => 'You can add a maximum of 5 tags.',
            'generate_banner_error' => 'Create a design first.',
            'invalid_code_format' => 'Invalid banner code format.',
            'invalid_base_color' => 'Invalid base colour. Must be between 0 and 15.',
            'invalid_patterns_format' => 'Invalid patterns format.',
            'invalid_pattern_structure' => 'Invalid pattern structure.',
            'invalid_pattern_unknown' => 'Unknown pattern.',
            'invalid_pattern_color' => 'Invalid pattern colour. Must be between 0 and 15.',
        ],
        'edit' => [
            'title' => 'Edit banner',
            'title_label' => 'Title',
            'description_label' => 'Description',
            'tags_label' => 'Tags',
            'tags_max_reached' => 'Maximum 5 tags reached',
            'tags_add_placeholder' => 'Add a tag',
            'tags_help' => 'Press enter, tab, or comma to add a tag.',
            'tags_max_error' => 'You can add a maximum of 5 tags.',
            'save_changes' => 'Save changes',
            'cancel' => 'Cancel',
            'edit_details' => 'Edit banner details',
            'delete' => 'Delete banner',
            'delete_confirm' => 'Delete this banner? This cannot be undone.',
        ],
        'show' => [
            'edit_design' => 'Edit design',
            'banner_give_command' => 'Banner give command',
            'setblock_command' => 'Setblock command',
            'shield_give_command' => 'Shield give command',
            'views_count' => ':count view|:count views',
            'favourites_count' => ':count favourite|:count favourites',
            'favourite_label' => 'favourite',
            'favourites_label' => 'favourites',
            'similar_banners' => 'Similar banners',
        ],
        'already_exists' => 'This banner is already in the gallery.',
    ],
    'search' => [
        'meta' => [
            'title' => 'Arama sonuçları: :search',
        ],
        'what_are_you_searching_for' => 'What are you searching for?',
        'title' => 'Arama sonuçları',
        'results' => 'Sayfa :current için :count sonuç|Sayfa :current yaklaşık :count sonuç ',
        'results_count' => ':count result|:count results',
        'time' => '(:time saniye)',
        'username_available' => 'Kullanıcı adı kullanılabilir*',
        'username_unavailable' => 'Kullanıcı adı kullanılamaz',
        'username_status' => 'Durum',
        'username_status_available' => 'Kullanılabilir*',
        'username_status_unavailable' => 'Kullanılamaz',
        'username_searches' => 'Aramalar',
        'username_searches_count' => ':count / gün',
        'username_available_disclaimer' => '*Ad, Mojang tarafından geçici veya kalıcı olarak yasaklanmadıkça.',
        'no_results' => 'Hiçbir profil bulunamadı. Arama türünü değiştirerek UUID ile arama yapmayı deneyin.',
        'no_results_tags' => 'Hiçbir etiketli skin bulunamadı. “mavi”, ‘kız’, “tilki” gibi diğer etiketleri aramayı deneyin.',
        'again' => 'Tekrar ara',
        'sorry' => 'Üzgünüm...',
        'view_profile' => 'Profili görüntüle',
        'view_all' => 'View all',
        'filters' => 'Filters',
        'more_results' => 'more results',
        'more_results_fallback' => 'more results',
        'close' => 'Close',
        'clear_filters' => 'Clear all',
        'profiles' => 'Profiles',
        'verified_only' => 'Verified only',
        'verification' => 'Verification',
        'all' => 'All',
        'verified' => 'Verified',
        'not_verified' => 'Not verified',
        'country' => 'Country',
        'country_placeholder' => 'e.g. US, UK',
        'no_types_found' => 'No project types found for this search',
        'no_categories_found' => 'No categories found for this search',
        'featured' => 'Featured',
        'yes' => 'Yes',
        'no' => 'No',
        'skins' => 'Skins',
        'tags' => 'Tags',
        'no_tags_found' => 'No tags found for this search',
        'min_profiles' => 'Min profiles using',
        'try_different' => 'Try a different search term',
        'skins_no_results' => 'No skins found',
        'empty_state' => [
            'title' => 'No matches this time',
            'message' => "We didn't find any results for this search. Try adjusting your keywords or browsing instead.",
        ],
    ],
    'collection' => [
        'title' => 'Minecraft skin koleksiyonu',
        'subtitle' => 'Minecraft skin koleksiyonumuzu inceleyin.',
        'filters' => 'Filtreler',
        'title_trending' => 'Trend olan',
        'title_all' => 'Tüm Minecraft Skin\'leri',
        'skin_tags' => 'Etiketlenmiş Skin\'ler',
        'filters_skin_type' => 'Skin türü',
        'filter_skin_type_steve' => 'Steve türü',
        'filter_skin_type_alex' => 'Alex türü',
        'cancel' => 'İptal',
        'apply' => 'Uygula',
        'username_minecraft_skin' => ':username kullanıcısının Minecraft skin\'i',
        'user_downloads' => '<span class="fw-500">:downloads</span> indirme|<span class="fw-500">:downloads</span> indirme',
    ],
    'favourites' => [
        'title' => 'Favoriler',
        'subtitle' => 'View and manage skins you saved for later in your favourites list',
        'sort' => 'Şuna göre sırala',
        'toast' => [
            'added' => 'Favoriler listenize eklendi',
            'removed' => 'Favoriler listenizden çıkarıldı',
            'login_required' => 'Sign in to add to favourites',
        ],
        'skins' => [
            'button' => 'Skinler',
            'empty_headline' => 'Henüz favori skin yok',
            'empty_subtitle' => 'Henüz favoriler listenize kaydedilmiş herhangi bir skin yok. Sunucu sayfasını ziyaret edin ve bir sonraki favorinizi keşfedin!',
            'empty_browse' => 'Skinlere göz atın',
            'meta' => [
                'title' => 'Favori skinlerim',
                'description' => 'Favori kaydedilmiş Minecraft skinlerim',
            ],
        ],
        'servers' => [
            'button' => 'Sunucular',
            'empty_headline' => 'Henüz favori sunucu yok',
            'empty_subtitle' => 'Henüz favoriler listenize kaydedilmiş herhangi bir sunucu yok. Sunucu sayfasını ziyaret edin ve bir sonraki favorinizi keşfedin!',
            'empty_browse' => 'Sunuculara göz atın',
            'meta' => [
                'title' => 'Favori sunucularım',
                'description' => 'Favori Minecraft sunucularım',
            ],
        ],

    ],
    'cape' => [
        'editor' => [
            'title' => 'Minecraft pelerin düzenleyicisi',
            'subtitle' => 'Minecraft pelerin düzenleyicisini kullanarak kendi özel tasarım pelerinini oluştur.',
            'meta' => [
                'title' => 'Minecraft Pelerin Düzenleyicisi',
                'description' => 'Minecraft Pelerin Düzenleyicisi\'ni kullanarak kendi özel tasarım pelerinini oluştur.',
            ],
        ],
        'list' => [
            'title' => 'Minecraft pelerinleri',
            'subtitle' => 'Official capes of Minecraft',
            'meta' => [
                'title' => 'Minecraft Pelerin Listesi',
                'description' => 'Minecraft pelerin listesi: Mojang, Minecon, Kişisel, Özel ve süs pelerinleri dahil olmak üzere tüm resmi Minecraft pelerinlerini görüntüleyin',
            ],
        ],
        'detail' => [
            'title' => ':cape Pelerin',
            'info' => 'Pelerin bilgileri',
            'profile_list' => 'Bu pelerinli profiller',
            'profiles' => ':profiles profil|:profiles profil',
            'meta' => [
                'title' => 'Minecraft Capes List',
                'description' => 'Minecraft cape list: View all official Minecraft capes including Mojang, Minecon, Personal, Speical and vanity capes',
            ],
        ],
        'list-custom' => [
            'title' => 'Özel Minecraft Pelerinleri',
            'description' => 'SkinMC üyeleri tarafından oluşturulan ve kullanılan özel pelerinleri göz atın ve görüntüleyin.',
        ],
    ],
    'servers' => [
        'title' => 'Minecraft sunucuları',
        'subtitle' => 'Minecraft sunucularına göz atın ve keşfedin',
        'all' => 'Tüm sunucular',
        'manage_your_servers' => 'Sunucularınızı yönetin',
        'add_new_server' => 'Yeni sunucu ekle',
        'filters' => [
            'trending' => 'Trend olan',
            'updated' => 'Güncellenen',
            'new' => 'Yeni',
            'most_viewed' => 'En çok görüntülenen',
            'top_voted' => 'En çok oy alanlar',
            'sorting' => 'Sıralama',
            'sort_by_latest' => 'En yeniye göre sırala',
            'sort_by_oldest' => 'En eskiye göre sırala',
            'categories' => 'Kategoriler',
            'server_location' => 'Sunucu konumu',
            'show_results' => 'Sonuçları göster',
            'show_more' => 'Daha fazla göster',
            'show_less' => 'Daha az göster',
            'clear_filters' => 'Filtreleri temizle',
            'reviews' => 'Yorumlar',
            'sort_by_highest_rating' => 'En yüksek puana göre sırala',
            'sort_by_lowest_rating' => 'En düşük puana göre sırala',
            'bedrock_and_java_support' => 'Bedrock ve Java desteği',
        ],
        'review-count' => ':count Yorum|:count Yorum',
        'meta' => [
            'title' => 'Minecraft Sunucu Listesi',
            'description' => 'Minecraft Sunucuları listesini inceleyin ve keşfedin, en iyi Minecraft sunucusunu bulun! En yeni, en popüler ve daha birçok kritere göre filtreleyin',
        ],
        'reviews' => [
            'meta' => [
                'title' => 'Bir yorum yaz',
            ],
            'editing' => 'Yorumunuzu :date tarihinde düzenliyorsunuz. Yorumunuzu silmek ister misiniz?',
            'welcome' => 'Merhaba :username. :servername ile genel deneyiminiz nasıldı?',
            'subtitle' => 'Sunucu ile ilgili geçmiş deneyiminiz için genel bir puan bırakın.',
            'scale' => [
                'great' => 'Harika',
                'good' => 'İyi',
                'okay' => 'Tamam',
                'meh' => 'Meh',
                'bad' => 'Kötü',
            ],
            'rate-experience' => 'Ardından, bu alanlardaki deneyiminizi değerlendirin',
            'overall' => 'Genel',
            'server-team' => 'Sunucu ekibi',
            'community' => 'Topluluk',
            'experience' => 'Deneyim',
            'availablility' => 'Çalışma süresi ve kullanılabilirlik',
            'shop' => 'Mağaza',
            'write-review-title' => 'Bir yorum yaz',
            'write-review-subtitle' => 'Birkaç not bırakın, beğendiğiniz şeyleri, deneyiminizi özel kılan şeyleri vurgulayabilir veya birkaç öneride bulunabilirsiniz.',
            'write-review-helper' => 'Sunucu hakkındaki deneyimlerinizi yeni oyuncularla paylaşmak ve sunucu sahiplerine geri bildirimde bulunmak için bir sunucu yorumu yazın.',
            'write-review-tips' => 'İşte bazı ipuçları',
            'submit-title' => 'Yorumunuzu göndermeye hazır mısınız?',
            'submit-subtitle' => 'Neredeyse bitti!',
            'submit-review' => 'Yorumumu gönder',
            'back' => 'Geri',
            'continue' => 'Devam',
            'delete-title' => 'Yorumunuzu silmek istediğinizden emin misiniz?',
            'tos-checkbox-part-1' => 'Bu formu göndererek SkinMC\'nin Hizmet Şartları, Gizlilik Politikası ve Topluluk Kurallarını kabul etmiş olursunuz. Ayrıca, tüm bilgilerin doğru olduğunu ve',
            'tos-checkbox-part-2' => 'yorum kurallarına uygun olduğunu onaylamış olursunuz.',
            'tos-checkbox-part-3' => 'Yorumunuz gönderildikten sonra yayınlanacaktır, ancak incelemeye tabi tutulabilir.',
        ],
        'slots' => 'Slotlar',
        'empty-helper' => 'You can try to do another search.',
        'empty' => 'Hmm, burası hala boş.',
        'verified' => 'Doğrulanmış',
        'review_translate_show_original' => 'Orijinalini göster',
        'review_translate' => 'Yorumu çevir',
        'description_translate' => 'Açıklamayı çevir',
        'create' => [
            'welcome' => 'Hoş Geldiniz',
            'basics' => 'Temel Bilgiler',
            'categories' => 'Kategoriler',
            'social_links' => 'Sosyal bağlantılar',
            'trailer_video' => 'Tanıtım videosu',
            'images' => 'Görüntüler',
            'images_description' => 'Daha sonra, sunucunuzun sunduğu hizmetleri tanıtmak için fotoğraf yükleyebilirsiniz.',
            'submit' => 'Gönder',
            'lets_get_your_server_added' => 'Sunucunuzu ekleyelim.',
            'basics-subtitle' => 'İnsanlara sunucunuzun ne hakkında olduğunu anlatın.',
            'description' => 'Açıklama',
            'description_tips' => 'İşte bazı ipuçları',
            'description_hint' => 'Yeni oyuncuları çekmek için sunucunuz için iyi bir açıklama yazın.',
            'categories-subtitle' => 'Sunucunuz için bazı kategoriler seçin',
            'missing-category' => 'Bir kategoriyi eksik mi?',
            'social_links_description' => 'Oyuncular sosyal medyada sunucunuza nereden bağlanabilirler?',
            'trailer_video_description' => 'Sunucunuzu bir YouTube videosuyla tanıtın.',
            'trailer_video_hint' => 'Video URL\'sini veya kimliğini (ID) yapıştırın:',
            'ready_to_submit_your_server' => 'Sunucunuzu göndermeye hazır mısınız?',
            'review-hint' => 'Gönderildikten sonra ekip, sunucu listeleme başvurunuzu dikkatlice inceleyecektir. Ardından karar verildikten sonra sunucunuz yayınlanacak veya yayına girmeden önce değişiklikler talep edilecektir.',
            'terms' => [
                'part-1' => 'Bu formu göndererek, SkinMC\'nin Hizmet Şartları, Gizlilik Politikası ve Topluluk Kurallarını kabul etmiş olursunuz. Ayrıca, yukarıdaki tüm bilgilerin doğru olduğunu ve',
                'part-2' => 'kurulum için sunucu gereksinimlerini',
                'part-3' => ', ve Minecraft sunucusunun temsil ettiğiniz kuruluş tarafından sahip olunduğunu ve yönetildiğini de kabul etmiş olursunuz.',
            ],
            'submit-application' => 'Başvuruyu gönder',
            'video-id-helper' => [
                'part-1' => 'Video kimliği, ardından gelen sayı ve harf dizisidir',
                'part-2' => 'Örneğin, video url\'niz ise',
                'part-3' => ', video kimliğiniz',
            ],
            'welcome_description' => 'Bu adımda, sunucunuzu eklemeye başlayacağız. Sunucunuz hakkında biraz bilgi verin, bir açıklama yazın ve bir sonraki adımda bazı resimler yükleyebilirsiniz.',
        ],
        'copy_server_ip' => 'Sunucunun IP\'sini kopyala',
        'all_minecraft_servers' => 'Tüm Minecraft Sunucuları',
        'promo' => [
            'title' => 'Bir Minecraft sunucusuna ev sahipliği yapıyor musunuz?',
            'ready_to_list_your_server' => 'Sunucunuzu listelemeye hazır mısınız?',
            'everything_you_need' => 'Sunucunuzu büyütmek için ihtiyacınız olan her şey',
            'list_your_server' => 'Sunucunuzu listeleyin',
            'list_your_server_description' => 'Sunucunuz için bir liste oluşturun, fotoğraflar, sosyal medya hesapları ve daha fazlasını ekleyin.',
            'find_players' => 'Oyuncuları bulun',
            'find_players_description' => 'Sunucunuza katılacak yeni oyuncular bulun ve onlara ulaşın, topluluğunuzu büyütün.',
            'get_reviews' => 'Yorumları alın',
            'get_reviews_description' => 'Topluluğunuzdan sunucunuzu incelemelerini isteyin ve onlara oyun içinde ödül verin.',
            'why_list_on_skinmc' => 'Sunucunuzu SkinMC\'ye neden kaydetmelisiniz',
            'others' => 'Diğerleri',
            'quality_check_and_confirmation' => 'Kalite kontrolü ve onay',
            'quality_check_description' => 'Ekibimiz kaliteyi sağlamak için her sunucuyu inceler.',
            'verified_players' => 'Doğrulanmış Minecraft oyuncularının yorumları',
            'verified_players_description' => 'Votifier entegrasyonu ile meşru hesaplardan gerçek oyuncu yorumlarını toplayın.',
            'international' => 'Uluslararası',
            'international_description' => 'Çeviri özellikleri sayesinde, listeniz daha fazla oyuncuya ulaşabilir.',
            'server_listing_page' => 'Güçlü Sunucu listeleme sayfası',
            'server_listing_page_description' => 'Fotoğraflar, açıklama metinleri, YouTube videoları ekleyin ve oyuncuların sunucunuza neden katılmaları gerektiğini vurgulayın.',
            'social_connections' => 'Sosyal medya bağlantıları',
            'social_connections_description' => 'Sunucularınızın sosyal medya hesaplarını bağlayın ve yeni oyunculara sizi nerede bulabileceklerini gösterin.',
            'verified_badge' => 'Doğrulama rozeti',
            'verified_badge_description' => 'Otantik sunucular doğrulama rozeti için başvurabilirler.',
            'owner_profile' => 'Sahibin profili',
            'owner_profile_description' => 'Özel profilinizi tamamlayarak kişisel bir dokunuş ekleyin.',
            'categories' => 'Kategoriler',
            'categories_description' => 'Sunucunuzun daha kolay bulunabilmesi için farklı kategoriler.',
            'vote' => 'Oyla',
            'vote_description' => 'Kullanıcılardan sunucunuz için oy vermelerini isteyin.',
            'fair_listings' => 'Adil listeler',
            'fair_listings_description' => 'Sunucu listeleri SkinMC\'deki sonuçlarda yapay olarak yükseltilemez.',
            'support' => '24 saat destek',
            'support_description' => 'Yardıma mı ihtiyacınız var veya sorularınız mı var? Her zaman bize ulaşabilir ve hızlı bir yanıt alabilirsiniz.',
            'custom_features' => 'Özel özellikler',
            'custom_features_description' => 'Sunucunuz için bir özellik eksik mi? Bir bilet açın, biz de onu sağlayalım.',
            'faq' => [
                'title' => 'Sorularınızın yanıtları',
                'suited-question' => 'Minecraft Sunucum SkinMC için uygun mu?',
                'suited-answer' => 'SkinMC\'deki Minecraft Oyuncuları yeni deneyimler ve içerikler keşfetmeyi ve topluluklarla etkileşim kurmayı severler. Platformda çok çeşitli, benzersiz ve eğlenceli Minecraft sunucuları bulabilirsiniz. Büyük bir ağdan küçük bir hayatta kalma sunucusuna kadar, bu sunucular birinin gününü güzelleştirebilir!',
                'get-started-question' => 'Nasıl başlayabilirim?',
                'get-started-answer' => 'Adding your Minecraft Server to the SkinMC Server List is very easy! You will first need to create an account, if you haven\'t already, and then follow the setup guide to get your server listed. Add a few photos and a nice description, and your server will be published in no time!',
                'players-question' => 'Minecraft sunucuma nasıl daha fazla oyuncu çekebilirim?',
                'players-answer' => 'Building a community is the most crucial part of a long lasting Minecraft Server. Use the Minecraft Server List on SkinMC to find a new audience and continue to build your community. Ask your players to recommend your Server, or share your listing on social media platforms. Collecting good reviews can also play an important role to a great Server listing presence that attracts new players.',
                'more-question' => 'Daha fazla sorum var. Nereden yardım alabilirim?',
                'more-answer' => 'You can reach out to SkinMC at any time, 24 hours, by using either the help button, the help desk, or by joining the Discord server.',
            ],
            'ready_to_list_description' => 'Add your Minecraft Server to the SkinMC Server List in just a few minutes. If you need any help, you can reach out around the clock and receive answers quickly.',
        ],
        'manage' => [
            'index' => [
                'welcome' => 'Tekrar hoş geldiniz, :username',
                'your_servers' => 'Sizin sunucularınız',
                'reviews_today' => 'Bugünkü yorumlar',
                'no_reviews_today' => 'Bugün yorum yok',
                'no_reviews_text' => 'Sunucularınız bugün herhangi bir yorum almadı. Oyuncularınızdan yorum bırakmalarını istemeye ne dersiniz?',
                'tips' => [
                    'title' => 'İpuçları',
                    'description-title' => 'Güzel bir sunucu açıklaması yazın',
                    'description-body' => 'Harika bir sunucu açıklamaları için faydalı ipuçları ve tavsiyeler.',
                    'images-title' => 'Sunucu görselleri ekleme',
                    'images-body' => 'Harika görsellerle sunucu listenizi öne çıkarın.',
                ],
            ],
            'listings' => [
                'title' => 'Senin Minecraft sunucuların (:count)',
            ],
            'insights' => [
                'title' => 'İzlenimler',
            ],
            'edit_server' => 'Sunucuyu düzenle',
            'listing' => 'Listeleme',
            'to_do' => 'Yapılacaklar',
            'last_update' => 'Son güncelleme',
            'add_more_photos_to_publish' => 'Yayınlamak için daha fazla görsel ekleyin',
            'looks_empty_here' => 'Burası boş görünüyor.',
            'get_started_by_adding_a_new_server' => 'Yeni bir sunucu ekleyerek başlayalım mı?',
        ],
        'status' => [
            'approved' => 'Onaylandı',
            'pending_approval' => 'Onay bekliyor',
            'published' => 'Yayınlandı',
            'in_review' => 'İnceleniyor',
        ],
    ],
    'editor' => [
        'import' => [
            'title' => 'Skin\'i İçe Aktar',
            'import_by_username' => 'Kullanıcı adıyla içe aktar',
            'import_button' => 'İçe Aktar',
            'drag' => 'Buraya bir skin sürükleyip bırakın, veya tıklayın',
            'click' => 'Görseli seç',
        ],
        'download' => [
            'error' => [
                'no-data' => 'Skin verisi sağlanamadı. Lütfen tekrar deneyin.',
                'invalid-format' => 'Skin veri formatı geçersiz. Lütfen tekrar deneyin.',
                'invalid-data' => 'Skin verisi bozuk. Lütfen tekrar deneyin.',
                'generic' => 'Skininiz indirilirken bir şeyler yanlış gitti. Lütfen tekrar deneyin.',
            ],
        ],
        'draw' => 'Çiz',
        'eyedropper' => 'Renk seçici',
        'fill' => 'Doldur',
        'move' => 'Taşı',
        'decrease_brightness' => 'Parlaklığı azalt',
        'increase_brightness' => 'Parlaklığı artır',
        'erase' => 'Silgi',
        'undo' => 'Geri al (CTRL+Z)',
        'redo' => 'İleri al (CTRL+Y)',
        'default_view' => 'Varsayılan görünüm',
        'zoom_in' => 'Yakınlaştır (CTRL +)',
        'zoom_out' => 'Uzaklaştır (CTRL -)',
        'saved' => 'Az önce kaydedildi',
        'saving' => 'Otomatik kaydediliyor...',
        'save_error' => 'Bir hata oluştu',
        'new_skin' => 'Yeni skin',
        'previous_skins' => 'Önceki skinler',
        'backed_up_title' => 'Otomatik olarak kaydedilen skinler',
        'backed_up_info' => 'Geçici olarak yerel depolama alanınıza yedeklenmiştir.',
        'backed_up_empty_title' => 'Burası boş',
        'backed_up_empty_info' => 'Skinleri düzenlemeye başladığınızda, son düzenlediğiniz 32 skin burada görünecektir.',
        'backed_up_skins_count' => 'tanesi kullanılan 32 skin yedeklemeleri',
        'backed_up_skins_count_info' => 'En fazla 32 skine kadar yedekleyebilirsiniz. 32 skine ulaştığınızda en eski skin yeni olanla değiştirilir.',
        'layers' => 'Katmanlar',
        'body' => [
            'title' => 'Vücut',
            'overlay' => 'Kaplama',
            'head' => 'Kafa',
            'torso' => 'Gövde',
            'l_arm' => 'Sol kol',
            'r_arm' => 'Sağ kol',
            'l_leg' => 'Sol bacak',
            'r_leg' => 'Sağ bacak',
        ],
        'model' => 'Model',
        'steve' => 'Steve',
        'alex' => 'Alex',
        'stance' => [
            'title' => 'Pozisyon',
            'default' => 'Varsayılan',
            'walk' => 'Yürümek',
            'run' => 'Koşmak',
            'hug' => 'T poz',
            'fly' => 'Uçmak',
        ],
        'fullscreen' => 'Tam Ekran',
        'fullscreen_exit' => 'Tam ekrandan çık',
        'grid' => 'Kılavuz',
        'show_grid' => 'Kılavuzu göster',
        'download' => [
            'title' => 'Kaydet ve İndir',
            'subtitle' => 'SkinMC Hesabı',
            'description' => 'Skininizi ve gelecekteki skinlerinizi buluta kaydetmek için ücretsiz bir SkinMC hesabı oluşturmak ister misiniz?',
            'start_description' => 'Buluta kaydetmeden doğrudan indirmeye başlayın',
            'start' => 'Skin indir',
        ],
        'help' => [
            'title' => 'Minecraft Skin Düzenleyicisi',
            'about' => 'Create and edit your custom Minecraft Skin easily with the SkinMC Editor. You can choose between Steve and Alex models, import skins from a file or username, and create your very own Minecraft Skin.',
            'draw' => 'Kalem aracını kullanarak çizim yapın. Kullanmak için renk örneğinden bir renk seçin.',
            'eyedropper' => 'Renk seçici aracını kullanarak skininizden bir renk seçin ve mevcut paletinize ekleyin.',
            'fill' => 'Doldurma aracını kullanarak skininizin tüm alanlarını doldurun. Doldurma işlemini gerçekleştirmeden önce bir renk seçin.',
            'move' => 'Taşıma aracını kullanarak skin düzenleyici tuvalini kaydırın ve hareket ettirin.',
            'decrease_brightness' => 'Şu anda aktif olan rengin parlaklığını azaltın.',
            'increase_brightness' => 'Şu anda aktif olan rengin parlaklığını artırın.',
            'erase' => 'İkincil kaplama katmanına çizilen pikselleri silin.',
            'minimap' => 'Minimap',
            'minimap_info' => 'The minimap can show you the skin texture in a flat view while in 3D mode. In 2D mode the minimap switches to a 3D preview of your skin. You can zoom in and out.',
            'autosave' => 'Autosave',
            'autosave_info' => 'The autosave feature saves your skin automatically every 30 seconds. You can access the autosaved skins in the editor by pressing the folder icon, and choosing "Previous skins".',
            '2d_editor' => '2D and 3D editor',
            '2d_editor_info' => 'Toggle between editing your Minecraft skin in 2D or 3D mode.',
        ],
    ],
    'account' => [
        'level' => 'Seviye',
        'level_history' => 'Seviye geçmişi',
        'xp' => 'XP',
        'my_xp' => 'Benim XP\'m',
        'xp_to_next_level' => 'Sonraki seviye için :xp XP',
        'xp_info' => 'XP nedir?',
        'xp_info_tooltip' => 'XP is earned for various activities such as adding tags to skins, inviting friends, commenting, and much more. With each XP earned you can level up and unlock cool things!',
        'settings' => [
            'title' => 'Hesap',
            'show_profile' => 'Profile git',
            'friends' => 'Arkadaşlar',
            'friends_detail' => 'SkinMC\'deki arkadaş listenizi kullanarak bağlantıda kalın.',
            'security' => 'Güvenlik',
            'security_detail' => 'Giriş şifrenizi güncelleyin ve hesabınızı güvende tutun',
            'social' => 'Sosyal medya hesapları',
            'social_detail' => 'Sosyal medya hesaplarınızı ekleyerek profilinizi özelleştirin',
            'link' => 'Minecraft hesabınızı bağlayın',
            'link_detail' => 'Minecraft hesabınızı bağlayın ve profilinizi alın.',
            'logout' => 'SkinMC hesabınızdan çıkış yapmak istiyor musunuz?',
            'automatic_backups' => 'Otomatik skin yedeklemeleri',
            'automatic_backups_info' => 'SkinMC plus üyesi olarak, skinleriniz her gün yedeklenir.',
        ],
        'capes' => [
            'title' => 'SkinMC Minecraft Pelerin',
            'description' => 'SkinMC Capes ile oyun içinde istediğiniz herhangi bir pelerini ücretsiz olarak giyebilirsiniz.',
            'drop' => 'Buraya bir pelerini sürükleyip bırakın',
            'drop-hint' => 'Boyutlar 64x32px',
            'select' => 'Görseli seç',
            'upload-cape' => 'Pelerini yükle ve kullan',
            'save-and-use' => 'Kaydet ve kullan',
            'uploaded-cape' => 'Yüklenen pelerin',
            'no-cape' => 'Pelerin yok',
            'remove-cape' => 'Pelerini kaldır',
            'download' => 'Kendinizin ve diğer oyuncuların pelerinlerini oyun içerisinde görmek için SkinMC modunu indirin.',
            'learn-more' => 'Daha fazlasını öğren',
            'link-account' => 'Pelerin yüklemek için lütfen Minecraft hesabınıza bağlanın.',
            'updated' => 'Pelerininiz güncellendi!',
            'removed' => 'Pelerininiz kaldırıldı.',
            'active' => 'Pelerininiz etkinleştirildi!',
        ],
        'favourite' => 'Favori',
        'remove_favourite' => 'Favoriyi kaldır',
        'added_to_favourites' => 'Favorilere eklendi',
        'removed_from_favourites' => 'Favorilerden kaldırıldı',
        'welcome' => 'Sizi görmek güzel!',
        'view-profile' => 'Profilimi görüntüle',
        'security' => [
            'title' => 'Güvenlik',
            'email' => 'E-posta adresi',
            'email-title' => 'E-posta adresinizi güncelleyin.',
            'save' => 'Kaydet',
            'password' => 'Şifre',
            'password-title' => 'Şifrenizi herhangi bir zamanda değiştirebilirsiniz.',
            'social-provider' => 'Şifreniz gibi hesap bilgilerinizi güncellemek için lütfen giriş sağlayıcınızı ziyaret edin:',
            'social-provider-email' => 'Giriş sağlayıcınızla ilişkili e-posta adresiniz',
            'social-provider-connected' => 'Şu anda bağlı giriş sağlayıcıları',
            'current-password' => 'Şu anki şifre',
            'forgot' => 'Şifrenizi mi unuttunuz?',
            'edit' => 'Düzenle',
            'delete' => 'Hesabımı sil',
            'account-deletion' => 'SkinMC hesabınızı silin.',
            'delete-info' => 'Devam etmek için lütfen onaylayın',
            'delete-confirmation' => 'Deleting your account is irreversible. All your personal information and content such as posts, favourites, uploaded capes, customisations, etc. will be deleted and can not be recovered.',
            'delete-confirmation-info' => 'Devam etmek için şifrenizi girin',
            'delete-confirmation-info-social' => 'Type "delete" to confirm account deletion',
            'type-delete' => 'Type "delete" to confirm',
            'type-delete-label' => 'Type "delete" to confirm',
            'yes-confirm-delete' => 'Evet, silme işlemini kabul ediyorum',
            'account-successfully-deleted' => 'Hesabınız ve verileriniz başarıyla silinmiştir.',
        ],
        'social' => [
            'title' => 'Sosyal hesaplar',
            'edit' => 'Düzenle',
            'save' => 'Kaydet',
            'link-account' => 'Link your Minecraft account to SkinMC to display your social links on your profile.',
            'finish-setup' => 'Kurulumu tamamla',
            'connect-account' => 'Hesaplarını bağla',
            'connect-description' => 'Choose which accounts you wish to connect and unlock special SkinMC integrations.',
            'empty' => 'Hiç hesap eklenmemiş',
            'empty-description' => 'Your social media accounts will show up here and on your public profile. Once added they will add more personalisation to your page as well as enable integrations.',
            'connect' => 'Bağlan',
            'username' => 'Kullanıcı adı',
            'spotify' => 'Spotify kullanıcı adınızı ekleyerek profilinizde Spotify bilgilerinizi gösterin.',
            'discord' => 'Discord kullanıcı adınızı ve numaranızı girerek Discord bilgilerinizi SkinMC profilinizde görüntüleyin.',
            'youtube' => 'YouTube kanalınızı SkinMC\'ye ekleyin, böylece YouTube kanalınız profilinizde görüntülenir.',
            'youtube-format' => 'Kanal bağlantınıza göre aşağıdaki formatı kullanın:',
            'twitter' => 'Profilinizde görüntülemek için X (eski adıyla Twitter) kullanıcı adınızı girin.',
            'bluesky' => 'Bluesky profilinizi profilinizde görüntülemek için Bluesky kullanıcı adınızı girin, örneğin kullanıcıadı.bsky.social.',
            'twitch' => 'Profilinde Twitch kanalını görüntülemek için Twitch kullanıcı adını gir.',
            'reddit' => 'Reddit profilinizi profilinizde görüntülemek için Reddit kullanıcı adınızı girin.',
            'github' => 'GitHub profilinizi profilinizde görüntülemek için GitHub kullanıcı adınızı girin.',
            'telegram' => 'Telegram bağlantınızı profilinizde görüntülemek için Telegram kullanıcı adınızı girin.',
            'tiktok' => 'TikTok profilinizi profilinizde görüntülemek için TikTok kullanıcı adınızı girin.',
            'snapchat' => 'Snapchat profilinizi profilinizde görüntülemek için Snapchat kullanıcı adınızı girin.',
            'instagram' => 'Instagram profilinizi profilinizde görüntülemek için Instagram kullanıcı adınızı girin.',
            'facebook' => 'Facebook profilinizi profilinizde görüntülemek için Facebook kullanıcı adınızı girin.',
            'includes_skinmc_plus_benefits' => 'SkinMC artı avantajları içerir',
        ],
        'recover' => [
            'title' => 'Hesabınızı kurtarın',
            'subtitle' => 'Hesabınızı kurtarma işlemini tamamlamak için lütfen yeni şifrenizi girin ve onaylayın.',
            'new_password' => 'Yeni şifre',
            'repeat_new_password' => 'Yeni şifreyi tekrar yazın',
            'submit' => 'Hesabınızı kurtarın',
        ],
        'customise' => [
            'title' => 'Profilinizi özelleştirin',
            'description' => 'Sosyal medya hesaplarınızı ekleyin, bir emoji seçin, konumunuzu ayarlayın ve daha fazlasını yapın',
            'information' => 'Bilgi',
            'preview' => 'Önizleme',
            'location' => [
                'title' => 'Konum',
                'description' => 'Profilinize eklemek istediğiniz konumu seçin.',
            ],
            'biography' => [
                'title' => 'Hakkımda',
                'description' => 'Profiliniz için bir biyografi yazın.',
            ],
            'status' => 'Durum',
            'status-toggle' => 'Çevrimiçi durumumu göster',
            'emoji' => 'Emoji',
            'name-history-toggle' => 'Kullanıcı adı geçmişini gizli yap',
            'name-history-info' => 'Minecraft kullanıcı adı geçmişiniz şu anda',
            'name-history-toggle-on' => 'gizli',
            'name-history-toggle-off' => 'herkese açık',
            'theme' => 'Profil teması',
            'theme-primary' => 'Birincil',
            'theme-secondary' => 'İkincil',
            'appearance' => 'Görünüm',
        ],
        'link' => [
            'manage' => 'Bağlı Minecraft hesabını yönet',
            'description' => 'Bağlı Minecraft hesabınızı görüntüleyin ve yönetin',
            'title' => 'Bağlı Minecraft hesabı',
            'current' => 'Şu anda bağlı Minecraft hesabı.',
            'status' => 'Artık tüm SkinMC özelliklerine tam erişiminiz var!',
            'linked' => 'Bağlantılı',
            'disconnect' => 'Bağlantıyı Kes',
            'disconnect-title' => 'Minecraft hesabından bağlantıyı kes',
            'disconnect-info' => 'Minecraft hesabınızla bağlantıyı kesmek istediğinizden emin misiniz?',
            'disconnect-features' => 'Yorum yapma, özelleştirme ve bağlantılı bir Minecraft hesabı gerektiren diğer özelliklere erişiminizi kaybedeceksiniz. Bunları tekrar kullanmak için bir Minecraft hesabı bağlamanız gerekecektir.',
            'disconnect-following' => 'Minecraft hesabınızı bağlantısını keserseniz, takip ettiğiniz tüm profiller kalıcı olarak silinir.',
            'disconnect-posts' => 'Oluşturduğunuz feed gönderileri ve beğendikleriniz silinecektir.',
            'can-not-undo' => 'Bu işlem geri alınamaz.',
            'are-you-sure' => 'Emin misiniz?',
            'confirm' => 'Evet, bağlantıyı kesmeyi onaylıyorum',
            'cancel' => 'Hayır, iptal et',
            'success' => 'Hesabınızın bağlantısı başarıyla kesildi!',
        ],
        'finish-setup' => [
            'title' => 'Hesap kurulumunu tamamla',
            'description' => 'Hesabınızı kurmayı tamamlayın ve Minecraft hesabınızı SkinMC\'ye bağlayarak tüm özelliklere tam erişim elde edin.',
            'link' => 'Minecraft hesabı bağla',
            'get-started' => 'Başlayın',
            'skip' => 'Atla',
            'claim' => 'Profilinizi talep edin',
            'customise' => 'Sayfanızı özelleştirin',
            'social' => 'Sosyal bağlantılar ekle',
            'comment' => 'Yorum sistemine erişim',
            'direct_message' => 'Direkt mesaj gönder',
            'feed' => 'Feed\'e durum güncellemeleri yayınlayın',
            'follow' => 'Arkadaşlarınızı takip edin',
            'badge' => 'Profilinizde gözüken rozet',
            'cape' => 'Özel Minecraft pelerini',
            'backup' => 'Otomatik skin yedeklemesi',
            'more' => 'Ve daha fazlası...',
        ],
        'skins' => [
            'title' => 'Skinleri yönetin',
            'toggle' => 'Skin görünürlüğü açık',
        ],
        'invite' => [
            'title' => 'Benim davetiyelerim',
            'headline' => 'Arkadaşlarınızı davet edin',
            'info' => 'Arkadaşınızla paylaşmak için bir davet kodu oluşturun. Arkadaşınız kabul ettiğinde, ikiniz de ekstra XP kazanacaksınız!',
            'description' => 'Arkadaşlarınız için bir davet oluşturun ve ikiniz de ekstra XP kazanın.',
            'generate' => 'Davet kodu oluştur',
            'empty' => 'Henüz hiçbir davet oluşturmadınız.',
            'code' => 'Kod',
            'expiry' => 'Her kod bir kez çalışır.',
            'status' => [
                'title' => 'Durum',
                'pending' => 'Bekliyor',
                'accepted' => 'Kabul Edildi',
            ],
            'add_invite' => [
                'button' => 'Davetiniz var mı?',
                'title' => 'Bir davet kodu ekleyin',
                'redeem' => 'Davetiyeyi kullan',
            ],
            'share' => 'Arkadaşınıza bir davet bağlantısı gönderin',
        ],
        'emoji' => [
            'title' => 'SkinMC Emoji',
            'introducing' => 'Tanıtım',
            'info' => 'Profilinizi emojiyle özelleştirin. Daha fazlası seviye atladığınızda açılır.',
            'unlocked_at' => 'Açılacağı seviye: :level',
            'unlocks_at' => 'Açmak için :level seviyeye ulaşın',
            'turn_off' => 'Emoji göster',
        ],
    ],
    'notifications' => [
        'title' => 'Bildirimler',
        'view_all' => 'Tümünü gör',
        'view_all_notifications' => 'Tüm bildirimleri gör',
        'image' => 'Bildirim görseli',
        'archived' => 'Arşivlenmiş',
        'inbox' => 'Gelen Kutusu',
        'empty' => [
            'title' => 'Güncel bilgilere sahipsiniz!',
            'text' => 'Yeni bildirimler burada gösterilecektir.',
            'text-archived' => 'Arşivlenmiş bildirimler burada gösterilecektir.',
        ],
        'action' => [
            'archive' => 'Arşive taşı',
            'unarchive' => 'Arşivden çıkar',
            'open' => 'Açmak için dokun',
        ],
        'toast' => [
            'archive' => 'Bildirim arşive taşındı',
            'unarchive' => 'Bildirim gelen kutusuna taşındı',
            'undo' => 'Geri al',
        ],
    ],
    'error' => [
        'offline' => [
            'title' => 'İnternet yok',
            'subtitle' => 'İnternet bağlantınız kesildi. Lütfen bağlantınızı kontrol edin ve sayfayı yeniden yükleyerek tekrar deneyin.',
            'try_again' => 'Tekrar dene',
        ],
        '404' => [
            'title' => '404 — Sayfa bulunamadı.',
            'subtitle' => 'Hm, bu konumda hiçbir şey bulunamamış gibi gözüküyor. Belki geri dönmeyi veya yeni bir arama başlatmayı deneyebilirsiniz, ne dersiniz?',
            'try_again' => 'Ana sayfaya dön',
        ],
    ],
    'heads' => [
        'list' => [
            'meta' => [
                'title' => 'Minecraft kafa veritabanı',
                'description' => 'Dünyanızı süslemek için Minecraft kafalarının veritabanını keşfedin veya kendi give komutunuzu oluşturun. Asla değişmeyen dokulara sahip resmi kafaları, oyuncu kafalarını ve özel kafaları görüntüleyin.',
            ],
            'header' => [
                'title' => 'Minecraft kafaları',
                'subtitle' => 'Dünyanızı süslemek için Minecraft kafaları veritabanımızı keşfedin veya kendi give komutunuzu oluşturun. Oyuncu kafaları, kullanıcının giydiği mevcut görünümü gösterir ve kullanıcı görünümünü güncelledikçe değişebilir. Özel kafalar Mojang görünüm dosyasına bağlıdır ve asla değişmez. Komut çok uzun olduğu için özel kafalar bir komut bloğu kullanılarak çağrılmalıdır.',
            ],
            'count' => [
                'heads' => ':heads kafa|:heads kafa',
            ],
            'customheads' => [
                'title' => 'Özel kafalar',
                'description' => 'Özel kafalar, Mojang sunucularındaki doku dosyasına doğrudan yol kullanır. Bu nedenle dokular asla silinmez ve kafalar asla değişmez.',
                'version' => 'Minecraft 1.8 veya üstü',
            ],
            'playerheads' => [
                'title' => 'Oyuncu kafaları',
                'description' => 'Oyuncu kafaları, Minecraft oyuncusunun mevcut cilt dokusunu kullanır. Kullanıcı adına dayalı oldukları için, oyuncu adını veya cilt dokusunu değiştirdiğinde kafa da değişir.',
                'version' => 'Tüm Minecraft sürümleri',
            ],
        ],
    ],
    'mod' => [
        'title' => 'SkinMC Mod: Ücretsiz özel pelerinler',
        'headline' => 'Daha fazla özelleştirme için SkinMC Mod\'u tanıtıyoruz',
        'description' => 'Minecraft topluluğuna geri ödeme yapmak için, oyuncuların özel pelerinlerle daha fazla özelleştirme yapabilmelerini sağlayan ücretsiz bir mod sunuyoruz. Bu mod, modu kullanan herkes tarafından kullanılabilir ve görülebilir.',
        'download' => 'Şimdi indir',
        'download-title' => 'Modu indir',
        'requires' => 'Gerekli:',
        'select-version' => 'Minecraft sürümünüzü seçin',
        'get-started' => 'Başlamak çok kolay',
        'step-1' => '1. Modu indirin',
        'step-1-detail' => 'Fabric\'i yükleyin, ardından oyun sürümünüz için modu indirin ve jar dosyasını mods klasörünüze koyarak yükleyin.',
        'step-2' => '2. Hesabınızı bağlayın',
        'step-2-detail' => 'Henüz yapmadıysanız, kaydolun/giriş yapın ve Minecraft hesabınızı SkinMC\'ye bağlayın.',
        'step-3' => '3. Pelerininizi yükleyin',
        'step-3-detail' => 'Hesabına git ve özel pelerini yükle. Oyun içinde görünür olacak.',
        'all-versions' => 'Tüm sürümler',
        'latest' => 'En son',
        'logged-in' => 'Pelerininizi yükleyin',
        'mirror' => 'Yedek',
        'download-via' => 'Şunla beraber indir:',
        'curseforge' => 'CurseForge',
    ],
    'app' => [
        'title' => 'SkinMC Android Uygulaması',
        'headline' => 'SkinMC Android Uygulamasına merhaba deyin.',
        'play-store-attribution' => 'Google Play ve Google Play logosu Google LLC kuruluşunun ticari markalarıdır.',
        'features' => 'Hareket halindeyken kullanışlı özellikler',
        'feature-qr' => 'Dahili QR Kod tarayıcı',
        'feature-qr-detail' => 'Yerleşik QR kodu tarayıcısını kullanarak masaüstünüzden uygulamaya kolayca bir görünüm ekleyin veya arkadaşlarınızın özel profil QR kodunu tarayın.',
        'feature-files' => 'Doğrudan dosyalara kaydeder',
        'feature-files-detail' => 'Android Dosya Yöneticisi kullanılarak, uygulama Skins\'i kolayca kaydedebilir ve Bedrock Edition\'da uygulamayı kolaylaştırır.',
        'feature-noads' => 'Reklam yok',
        'feature-noads-detail' => 'Dikkatinizi dağıtmayan, temiz bir arayüz. Web\'den uygulamaya kadar rahatsız edici reklamlar olmadan reklam içermeyen bir deneyimin keyfini çıkarın.',
        'feature-experience' => 'Deneyim',
        'feature-experience-detail' => 'Ekstra özelliklerle SkinMC deneyiminin tadını her yerde çıkarın. Profilinizi özelleştirin, biyografinizi ekleyin, eğlenceli bir QR kodu oluşturun ve daha fazlasını yapın!',
        'get-app-headline' => 'SkinMC Uygulamasını indirin',
        'get-app-detail' => 'Android cihazınız için size özel Minecraft arkadaşı — ücretsiz olarak kullanılabilir.',
    ],
    'random' => [
        'title' => 'Rastgele Minecraft skini yükleniyor',
        'description' => 'Rastgele Minecraft skini yükleniyor',
        'headline' => 'Lütfen bekleyin...',
        'redirect' => 'Otomatik olarak yönlendirileceksiniz. Sayfa yüklenmiyor mu?',
        'click-here' => 'Buraya tıklayın',
        'messages' => [
            '1' => 'Rastgele Minecraft skini yükleniyor...',
            '2' => 'Kazmaya devam...',
            '3' => 'Creeper, ah dostum...',
            '4' => 'Sandıkları arıyor...',
            '5' => 'Gelecek skinin tamamen rastgele olduğunu biliyor muydun?',
            '6' => 'Rastgele skin geliyor...',
            '7' => 'Bir blok daha...',
            '8' => 'Envanter sıralanıyor...',
            '9' => 'Elmas kazma yapılıyor...',
            '10' => 'Herobrine aranıyor...',
        ],
    ],
    'feed' => [
        'title' => 'Feed',
        'following' => 'Takip edilenler',
        'sign-up' => 'Sohbete katılmak için kayıt olun veya giriş yapın.',
        'link-account' => 'Sohbete katılmak için Minecraft hesabını bağla.',
        'placeholder' => 'Ne oluyor?',
        'audience' => 'Seyirci',
        'audience-title' => 'Bunu kimler görebilir?',
        'everyone' => 'Herkes',
        'everyone-info' => 'SkinMC\'de veya dışında olan herkes.',
        'followers' => 'Takipçiler',
        'followers-info' => 'Giriş yapmış veya beni takip eden üyeler.',
        'private' => 'Sadece ben',
        'private-info' => 'Sadece benim görebildiğim özel gönderi.',
        'submit' => 'Gönder',
        'like' => 'Beğen',
        'comment' => 'Yanıtla',
        'share' => 'Paylaş',
        'remaining' => 'Kalan',
        'profile' => ':username tarafından gönderiler',
        'posts' => 'Tüm gönderiler',
        'my-posts' => 'Benim gönderilerim',
        'view-all' => 'Tüm gönderileri görüntüle',
        'post' => [
            'meta' => ':username SkinMC\'de: :text',
            'title' => 'Gönderi',
            'created' => 'Durum güncellemesi yayınlandı!',
            'confirm-delete' => 'Bu gönderiyi silmek istediğinizden emin misiniz? Bu işlem geri alınamaz.',
            'delete' => 'Gönderiyi sil',
            'deleted' => 'Gönderiniz silindi.',
        ],
        'repost' => [
            'button' => 'Repost',
            'quote_button' => 'Quote',
            'title' => 'Repost this post',
            'quote_title' => 'Quote post',
            'quote_label' => 'Add a comment (optional)',
            'quote_placeholder' => 'Add your thoughts...',
            'reposted' => 'reposted',
            'success' => 'Reposted!',
            'removed' => 'Repost removed.',
            'already_reposted' => 'You have already reposted this.',
            'undo' => 'Undo repost',
            'original_deleted' => 'The original post has been deleted.',
            'deleted_post' => 'This post has been deleted',
        ],
        'hashtags' => [
            'title' => 'Trending',
            'trending-now' => 'Trending now',
            'post' => 'post',
            'posts' => 'posts',
            'posts-count' => ':count post|:count posts',
            'hashtag' => 'Hashtag',
            'hashtags' => 'Hashtags',
            'no-results' => 'No hashtags found',
        ],
        'search' => [
            'title' => 'Search',
            'placeholder' => 'Search posts, hashtags...',
            'no-results' => 'No results found',
            'posts' => 'Posts',
            'no-hashtags-found' => 'No hashtags found matching ":query"',
            'no-results-found' => 'No results found for ":query"',
        ],
        'poll' => [
            'title' => 'Poll',
            'create' => 'Create a poll',
            'option' => 'Option',
            'add_option' => 'Add option',
            'duration' => 'Duration',
            'duration_1' => '1 day',
            'duration_3' => '3 days',
            'duration_7' => '7 days',
            'votes' => '{0} votes|{1} vote|[2,*] votes',
            'ended' => 'Poll ended',
            'ends_in' => 'Ends :time',
            'login_required' => 'Sign in to vote',
        ],
        'gif' => [
            'title' => 'GIF',
            'search_placeholder' => 'Search KLIPY for GIFs...',
            'no_results' => 'No GIFs found',
            'powered_by' => 'Powered by',
            'categories' => 'Categories',
            'trending' => 'Trending',
        ],
        'media' => 'Media',
        'follow-suggestions' => 'Ekibi takip et',
        'explore' => 'Keşfet',
        'hashtag' => 'Hashtag',
        'no_users' => 'No users found.',
        'stories' => [
            'archive' => [
                'title' => 'Story Archive',
                'subtitle' => 'Your archived stories are only visible to you',
                'empty' => 'No archived stories yet',
                'empty-description' => 'Stories you post will appear here after 24 hours.',
                'action' => 'Archive',
                'archived' => 'Story moved to archive.',
                'already-archived' => 'Story is already archived.',
            ],
        ],
    ],
    'private' => [
        'title' => 'Gizli gönderiler',
        'text' => 'Bu gönderi gizlidir.',
    ],
    'liked' => [
        'title' => 'Beğenildi',
    ],
    'following' => [
        'title' => 'Takip edilenler',
        'text' => 'Bu gönderiyi görmek için giriş yapın.',
    ],
    'tags' => [
        'empty' => 'Henüz oylanacak etiket yok',
        'empty-subtitle' => 'İlk ekleyen siz olun',
    ],
    'inbox' => [
        'title' => 'Mesajlar',
        'details' => 'Detaylar',
        'message_user' => 'Mesaj',
        'write_message' => 'Bir mesaj yaz',
        'empty' => [
            'no_message_selected' => 'Hiçbir mesaj seçilmedi',
            'open_or_start_conversation' => 'Mesaj listesinden bir sohbet açın veya yeni bir tane başlatın.',
            'no_messages' => 'Okunmamış mesaj yok',
            'start_conversation' => 'Yeni bir sohbete başlattığınızda, mesajlarınız burada görüntülenecektir.',
            'conversation' => 'Bu, :username ile sohbetinizin başlangıcıdır.',
            'users' => 'Mevcut sorguyla eşleşen kullanıcı bulunamadı.',
        ],
        'typing' => ':username yazıyor...',
        'new_message' => 'Yeni mesaj',
        'mark_unread' => 'Okunmadı olarak işaretle',
        'send_message' => 'Mesajı gönder',
        'delete_message' => 'Mesajı kendiniz için silin',
        'latest_conversations' => 'Son sohbetler',
        'delete_conversation' => 'Sohbeti sil',
        'show_details' => 'Detayları göster',
        'hide_details' => 'Detayları gizle',
        'unread' => 'Okunmamış',
        'deleted' => 'Silindi',
        'report_message' => 'Mesajı bildir',
        'add_reaction' => 'Tepki ekle',
        'today' => 'Bugün',
        'reconnect' => 'Sohbet etmek için lütfen Minecraft hesabınızı tekrar bağlayın',
        'account_disconnected' => 'Bu kullanıcı bağlı Minecraft hesabının bağlantısını kesmiştir.',
        'saved_messages' => 'Kaydedilmiş mesajlar',
        'new_message_to_label' => 'Hedef',
        'external-link-to' => 'Bu bağlantı sizi şu sayfaya yönlendirecektir:',
        'external-link-confirmation' => 'Oraya gitmek istediğinizden emin misiniz?',
        'external-link' => 'Dış bağlantı',
        'reply' => 'Yanıtla',
    ],
    'server' => [
        'manage' => [
            'stats' => 'İstatistikler',
        ],
    ],
    'report' => [
        'button' => 'Bildir',
        'title' => 'Rapor içeriği',
        'describe' => 'Bunu neden bildirdiğinizi kısaca açıklayın',
        'select' => 'Bildirme sebebinizi seçin',
        'submit' => 'Raporu gönder',
        'reasons' => [
            'INAPPROPRIATE_CONTENT' => 'Uygunsuz içerik',
            'SPAM' => 'Spam',
            'HARASSMENT' => 'Taciz',
            'OTHER' => 'Diğer',
        ],
    ],
    'leaderboard' => [
        'title' => 'Liderlik Tablosu',
        'description' => 'SkinMC kullanıcılarının liderlik tablosunu görüntüleyin.',
        'headline' => 'İlk 10',
        'all-time-invites' => 'Toplam davet',
        'all-time-xp' => 'Toplam XP',
        '30-day-xp' => 'Son 30 gündeki XP',
    ],
];
