<?php

return [
    'auth' => [
        'login' => [
            'title' => 'SkinMC\'ye hoş geldiniz',
        ],
        'register' => [
            'title' => 'SkinMC\'ye kaydolun',
            'subtitle' => 'Başlayın ve tam erişim için hesabınızı oluşturun.'
        ]
    ],

    'home' => [
        'hero_slogan' => 'Minecraft Skins için yeriniz.',
        'hero_cta' => 'Şaşırt beni',
        'hero_explore_cta' => 'Ciltleri keşfedin',
        'skin_viewer' => 'Skin görüntüleyici',
        'skin_viewer_detail' => 'Araştır :count Skinleri',
        'skin_editor' => 'Skin düzenleyici',
        'skin_editor_detail' => 'Kendi skiniz\'i tasarlayın',
        'avatar_maker' => 'Avatar oluşturucu',
        'avatar_maker_detail' => 'Özel Minecraft avatar profil resimlerinizi oluşturun.',
        'trending' => 'Trend olan',
        'minecraft_skin' => 'Minecraft skin',
        'favourite' => 'Favori',
        'collections' => 'Koleksiyon',
        'collections_detail' => 'Her durum için küratörlüğünde Minecraft skinleri',
        'about_skinmc' => 'SkinMC Hakkında',
        'about_find' => 'Herhangi bir skin bulun',
        'about_find_detail' => 'Bir sonraki yeni skinizi bulmak, görüntülemek ve indirmek için herhangi bir Minecraft Kullanıcı Adı için SkinMC aramasını kullanın.',
        'about_download' => 'İndirin veya düzenleyin',
        'about_download_detail' => 'Beğendiğiniz bir kaplama mı buldunuz? Favorilerinize ekleyin, düzenleyin veya indirin ve kendinize ait hale getirin.',
        'about_platform' => 'Çapraz platform',
        'about_platform_detail' => 'Dış görünümü hareket halindeyken de kullanmak ister misiniz? QR kodunu tarayın ve Minecraft PE için görüntüyü telefonunuza kaydedin.',
        'meta' => [
            'title' => 'Minecraft Skin Görüntüleyici',
            'description' => 'Minecraft skinlerini görüntüleyin ve indirin, seçilmiş koleksiyonlardaki en iyi skinleri keşfedin, kullanıcı adı kullanılabilirliğini ve geçmişini kontrol edin ve çok daha fazlasını yapın!',
        ],
        'recently_viewed' => 'Son görüntülenenler',
        'explore_title' => 'Yeni bir şey deneyin',
        'explore' => 'Yeni fikirler ve araçlar keşfedin',
        'servers_browse' => 'Sunuculara göz atın',
        'servers' => 'En iyi Minecraft Sunucularını keşfedin',
        'heads' => 'Minecraft kafaları',
        'head_description' => 'Minecraft kafaları veritabanına göz atın veya yenilerini oluşturun.',
        'achievement' => 'Başarım jeneratörü',
        'achievement_detail' => 'Kendi, özel ve kişiselleştirilmiş başarımlarınızı oluşturun.',
        'continue' => 'Göz atmaya devam edin'
    ],
    'profile' => [
        'verified' => 'Doğrulanmış profil',
        'minecraft_profile' => 'Minecraft profili',
        'show_qr_code' => 'QR kodunu göster',
        'favourite' => 'Favori',
        'user_title' => ':username Minecraft Skini',
        'user_views' => 'Görüntülenen :views time|Viewed :views süreleri',
        'uuid' => 'UUID',
        'copy' => 'Kopyala',
        'link' => 'Bağlantı',
        'skin_history' => 'Minecraft görünüm geçmişi (:skins)',
        'username_history' => 'Kullanıcı adı geçmişi',
        'username_history_name' => 'İsim',
        'username_history_timestamp' => 'Değiştirildi',
        'username_history_initial_name' => 'İlk isim',
        'user_downloads' => ':downloads download|:downloads indirmeler',
        'download_skin' => 'Skin indir',
        'apply_skin' => 'Skin uygulayın',
        'capes' => 'Pelerinler',
        'claim_profile' => 'Siz :username misiniz? Profilinizi doğrulamak ve özelleştirmek için sahiplenin!',
        'claimed' => 'Sahiplenmiş Profil',
        'meta_description' => 'Görüntüleyin ve indirin View and download :username Minecraft Skin. UUID\'lerini, isim geçmişlerini, ayrıntılı istatistiklerini ve daha fazlasını görün',
        'created_at' => 'Güncellendi: :changed_at',
        'skins' => [
            'meta_title' => ':username Minecraft Geçmişi',
            'meta_description' => 'Görünüm :username Minecraft Skinleri geçmişi ve daha önce kullanılan Skinler. Eski veya geçmişte kullanılan kaplamalara göz atmak, yedeklemek ve geri almak veya yeni kaplamalar toplamak için geçmişi kullanın.',
            'title' => 'Minecraft Skin geçmişi'
        ],
        'qr_code' => [
            'meta_title' => ':kullanıcı adının QR Kodu',
            'meta_description' => ':kullanıcı adı Özel Minecraft Profili QR Kodu'
        ],
        'sub_nav' => [
            'skin' => 'Cilt',
            'about' => 'Hakkında',
            'usernames' => 'Kullanıcı adları',
            'head' => 'Kafa',
            'comments' => 'Yorumlar'
        ],
        'cape' => 'Pelerin',
        'elytra' => 'Elitra',
        'nametag' => 'İsim etiketi',
        'animation' => 'Animasyon',
        'rotation' => 'Rotasyon',
        'none' => 'Hiçbiri',
        'idle' => 'Boşta',
        'walk' => 'Yürümek',
        'run' => 'Koşmak',
        'fly' => 'Uçmak',
        'follow' => 'Takip et',
        'following' => 'Takip etmek',
        'unfollow' => 'Takibi bırak',
        'followers' => 'Takipçi|Takipçiler',
        'toast' => [
            'following' => 'Şimdi takip ediyorsunuz :kullanıcı adı!',
            'follow-self-error' => 'Üzgünüm :kullanıcı adı, kendinizi takip edemezsiniz.',
            'unfollowed' => 'Takibi bıraktınız :username'
        ],
        'edit' => 'Profili düzenle',
        'joined' => 'Katıldım',
        'server-fav-list-empty' => 'Görünüşe göre :username kullanıcısının henüz favori sunucusu yok. :username bir sunucuyu favori olarak kaydettiğinde, onu burada görebilirsiniz.',
        'server-own-list-empty' => 'Görünüşe göre :username henüz herhangi bir sunucuya sahip değil. :username bir sunucu listelediğinde, onu burada görebilirsiniz.',
        'capes-list-empty' => 'Görünüşe göre :username henüz pelerin giymiyor. :username pelerin giydiğinde, bunu burada görebilirsiniz.',
        'feed-own-list-empty' => 'Görünüşe göre henüz feed\'e hiçbir şey göndermediniz! Gönderdiğinizde, gönderilerinizi burada görebilirsiniz.',
        'feed-list-empty' => 'Hmm, görünüşe göre :username henüz feed\'e hiçbir şey paylaşmamış. :username bir şey paylaştığında, bunu burada görebilirsiniz.',
        'following-own-list-empty' => 'Görünüşe göre henüz kimseyi takip etmiyorsunuz! İnsanları takip etmeye başladığınızda, onları burada görebilirsiniz.',
        'following-list-empty' => 'Hmm, :kullanıcı adı kimseyi takip etmiyor gibi görünüyor. Kullanıcı adı kişileri takip etmeye başladığında onları burada görebilirsiniz.',
        'followers-own-list-empty' => 'İnsanlar profilinizi takip etmeye başladığında, burada görüneceklerdir.',
        'followers-list-empty' => 'Hmm, :username kimse tarafından takip edilmiyor gibi görünüyor. Takip eden ilk kişi sen ol :username. Daha fazla kişi takip ettiğinde, onları burada görebilirsiniz.',
        'render' => 'Görüntüleyici',
        '3d' => '3D görüntü',
        '2d' => '2D görüntü',
        'name-history-info' => 'Kullanıcı Adı Geçmişi ortadan kalkıyor. Mojang, 13 Eylül 2022 tarihinde isim geçmişi API\'sine erişim desteğini kaldırdı ve bu da doğru bir isim geçmişinin artık mevcut olmamasına neden oldu. İsim geçmişinizi gizlemek istiyorsanız, profilinizi talep edin ve özel yapmak için ayarlara gidin.',
        'edit-skins' => 'Cilt geçmişini düzenleme',
        'hide-skin' => 'Cildi Gizle',
        'show-skin' => 'Cildi Göster',
        'edit-skin' => 'Cildi düzenle',
        'servers' => [
            'title' => ':username kullanıcısının sunucuları',
        ],
        'cape-list' => [
            'title' => ':username kullanıcısının pelerinleri',
        ]
    ],
    'skin' => [
        'meta' => [
            'title' => ':username Minecraft Skini',
            'description' => 'Minecraft Kaplaması. Kaplamayı indirip görüntüleyin ve hangi oyuncuların da aynı kaplamayı giydiğini görün.',
            'tags' => ':username Minecraft Cilt, :username Cilt, Minecraft Skin, :username Özel Minecraft Cildi, Cilt İndir, Aynı Cilde sahip oyuncular',
        ],
        'title' => ':username Minecraft Cildi',
        'head' => 'Baş komutları',
        'head_info' => 'Komut blokları ile kullanmak için',
        'first_wearing' => 'Bu Cildi giyen ilk oyuncu',
        'profiles' => ':profiller profil|:profiller profiller',
        'profiles_title' => ':profiles bu cilt ile profil|:profiles bu cilt ile profiller',
        'screenshot' => 'Ekran görüntüsü',
    ],
    'skins' => [
        'meta' => [
            'title' => 'Sayfa :current - Tüm Minecraft Ciltleri',
            'description' => 'Son sayfalardaki :total özel Minecraft kaplamaları listemize göz atın ve sıradaki favori kaplamanızı indirin!',
            'tags' => ':username Minecraft Cilt, :username Cilt, Minecraft Cilt, :username Özel Minecraft Cilt, Cilt İndir, Aynı Cilde sahip oyuncular',
            'tags-title' => ':tag Minecraft Ciltleri',
            'tags-description' => 'Toplam :tag Minecraft kaplamalarından oluşan :last pages listemize göz atın ve en sevdiğiniz :tag kaplamasını indirin!',
            'tags-metatags' => ':tag Minecraft Skin, :tag Skin, Minecraft Skin, :tag Özel Minecraft Skin, İndir :tag Skin, Minecraft :tag Skins',
        ],
        'title-skin-tags' => 'Etiketlenmiş Minecraft Clitleri',
        'subtitle' => 'Page :current of :last from :total Minecraft Skins',
        'subtitle-skin-tags' => 'Page :current of :last from :total Tagged Minecraft Skins',
        'sort_by' => 'Şuna göre sırala',
        'latest' => 'Son Ciltler',
        'most_profiles' => 'En çok kullanılan skinler',
        'profiles_today' => 'Bugün en çok kullanılan',
        'profiles_this_week' => 'Bu hafta en çok kullanılan',
        'profiles_this_month' => 'Bu ay en çok kullanılan',
        'default' => 'Varsayılan Sıralama',
        'this_month' => 'Bu ay eklendi',
        'this_week' => 'Bu hafta eklendi',
        'today' => 'Bugün eklendi',
        'random' => 'Rastgele',
        'similar' => 'Benzer Ciltler',
        'no_similar_skins' => 'Henüz benzer skinler bulunamadı.',
        'favorite' => ':count favori|:count favori',
    ],
    'skin-tags' => [
        'faq' => 'Etiketler nedir?',
        'about' => 'Etiketler, dış görünümlere ilgili kategoriler eklemenin bir yoludur. Etiket eklemek, beğendiğiniz daha fazla dış görünümü kolayca keşfetmenizi sağlar!',
        'guidelines' => [
            'good' => [
                'title' => 'İyi etiketler için genel kurallar şunlardır:',
                'short' => 'Kısa',
                'descriptive' => 'Tanımlayıcı & Açıklayıcı',
                'spelled' => 'Doğru Yazıldı',
            ],
            'bad' => [
                'title' => 'Gibi etiketler eklemeyin:',
                'general' => 'Çok genel',
                'specific' =>  'Çok spesifik',
                'too-many-tags' =>  'Üç ayrı etiket olmalıdır',
                'spelling' => 'Şöyle olmalı :example',
            ],
        ],
        'toast' => [
            'added' => 'Oylama için “:tag” etiketi eklendi',
            'removed' => '“:tag” etiketi kaldırıldı',
            'upvote' => '”:tag” beğenildi',
            'downvote' => '”:tag” beğenilmedi'
        ],
        'vote' => [
            'up' => 'Yukarı oy',
            'down' => 'Aşağı oy',
            'remove' => 'Oylamayı kaldır',
        ],
    ],
    'contact' => [
        'contact' => 'İletişim',
        'email' => 'Sorularınız için lütfen <a href="mailto:support@skinmc.net">support@skinmc.net</a> adresinden bize yazmaktan çekinmeyin.',
        'faq' => 'Sorunuz zaten orada yanıtlanmışsa, öncelikle <a href=":link">FAQ page</a> göz atmanızı rica ederiz.',
        'other' => 'Bağlanmanın diğer yolları',
        'other_discord' => 'Discord sunucusuna katılın ve diğer kullanıcılarla bağlantı kurun, oyunlar hakkında sohbet edin, en sevdiğiniz favori paketleri paylaşın ve topluluktan yardım alın.',
        'other_twitter' => 'Twitter\'da takip ederek yeni güncellemelerin veya özelliklerin ne zaman yayınlandığını öğrenin, haftanın temalarını görün ve daha fazlasını keşfedin.',
        'other_instagram' => 'Yeni öne çıkan harika Minecraft Ciltlerini ve görsellerine göz atmak ve keşfetmek için SkinMC\'yi Instagram\'da takip edin.',
        'other_facebook' => 'Facebook\'ta hayran olun ve Minecraft içeriğini keşfederken yorum yapabileceğiniz ve başkalarıyla konuşabileceğiniz tüm gönderileri görün.'
    ],
    'about' => [
        'intro' => '<span>Minecraft</span> <span>Skinleri</span> <span>için</span> <span>platformunuz.</span>',
        'header_credit' => 'Illustration "Epic Nether Battle" by',
        'info' => 'Her şeyin kaydını tutun.',
        'info_explainer' => 'Bir oyuncunun isim geçmişini görüntüleyin, önceki görünümlerini görün, arkadaş olarak ekleyin, görünümleri indirin ve hatta ayrıntı istatistiklerini alın.',
        'card_find_title' => 'Herhangi bir Minecraft Oyuncusunu Bul',
        'card_find_detail' => 'Get started by searching for any players username or UUID of your choice.',
        'card_view_title' => 'Görüntüle, kaydet ve düzenle',
        'card_view_detail' => 'Found a skin you like? Save it by downloading or use the editor to make it your own.',
        'card_claim_title' => 'Doğrulanın',
        'card_claim_detail' => 'Link up your Minecraft account and claim your profile to unlock cool new features!',
        'card_customise_title' => 'Profilinizi özelleştirin',
        'card_customise_detail' => 'Verified players can add their social media links and make their profile their own.',
        'card_friends_title' => 'Arkadaşlarınızı ekleyin',
        'card_friends_detail' => 'Get connected with your friends on SkinMC and show your friend list on the profile.',
        'card_history_title' => 'Kullanıcı adı ve skin geçmişi',
        'card_history_detail' => 'Use the advanced search to find and see the username/skin history of a player.',
        'founders' => 'Kurucular',
        'founders_cofounder' => 'SkinMC\'nin kurucu ortağı',
        'head_of_design' => 'Tasarım başkanı',
        'head_of_code' => 'Kod başkanı',
        'feedback' => 'Bize geri bildirimde bulunun',
        'faq' => 'Questions about Minecraft, Skins, and more? Read our FAQs with answers to most frequently asked questions.',
        'faq_link' => 'SSS merkezini ziyaret edin',
        'contact' => 'Do you want to reach out or have further questions? Contact us directly.',
        'contact_link' => 'Bize ulaşın',

    ],
    'faq' => [
        'title' => 'SSS',
        'subtitle' => 'Sıkça sorulan sorular',
        'help' => 'Daha fazla yardıma ihtiyacın mı var?',
        'discord' => 'Diğer Minecraft oyuncularıyla sohbet etmek için Discord sunucusuna katılın.',
        'contact' => 'Bize ulaşın',
        'q' => [
            'change_skin_t' => 'Minecraft Skin\'imi nasıl değiştiririm?',
            'change_skin' => '
                <p>To change your Skin do the following:</p>
                <ol>
                    <li>Visit <a href="https://my.minecraft.net/en-us/login/">https://my.minecraft.net/en-us/login/</a> and sign in with your Mojang account.</li><li>Once signed in, select <b>"Skin"</b> on the left menu.</li><li>Then, choose a Model you prefer and upload a the Skin of your liking.</li>
                </ol>',
            'change_username_t' => 'Minecraft kullanıcı adımı nasıl değiştiririm?',
            'change_username' => '
                <p>To change your Username do the following:</p>
                <ol>
                    <li>Visit <a href="https://account.mojang.com/login" target="_blank" rel="nofollow">https://account.mojang.com/login</a> and log in with your Mojang account.</li>
                    <li>Find your Minecraft Profile Name and press the <b>"(Change)"</b> button</li>
                    <li>On the next page, enter your desired new username.</li>
                    <li>Finally, confirm the changes by entering your password and pressing "Change name".</li>
                </ol>',
            'dl_t' => 'Birinin Minecraft Skin\'ini nasıl indirebilirim?',
            'dl' => '
                <p>To download anyones Minecraft Skin do the following:</p>
                <ol>
                    <li>Press on the search bar and enter the username of the player you would like to download the skin from.</li>
                    <li>On the profile page you can preview the skin</li>
                    <li>Click on the <strong>Download Skin</strong> button under the preview</li>
                </ol>',
            'submit_q' => 'Bir koleksiyona nasıl skin gönderebilirim?',
            'submit_a' => '<p>Please fill out the following short form with the usernames and their category of which you would like to add to the collections. <a href="https://forms.gle/f4Jh5RpGfsHAZ5xE8" target="_blank">Collection submission form</a>',
            'mcpe_t' => 'Minecraft PE\'de Skin kullanabilir miyim?',
            'mcpe' => '
                <p>Yes. To use the Skin in Minecraft Pocket Edition do the following:</p>
                <ol>
                    <li>Open SkinMC.net on your smartphone and tap the search bar</li>
                    <li>Enter the username of the player\'s skin you would like to download</li>
                    <li>Tap the <strong>Download Skin</strong> button under the preview </li>
                    <li>Open Minecraft PE and tap on <strong>Profile</strong> on the right side</li>
                    <li>Tap on the <strong>+</strong>, or edit character and go to the "classic skins tab"</li>
                    <li>Tap on "owned", then "import", then "choose new skin"</li>
                </ol>',
            'change_times_t' => 'Kullanıcı adımı ne sıklıkla değiştirebilirim?',
            'change_times' => '<p>You can change your Minecraft Username <strong>once</strong> every <strong>30 days</strong>.</p>',
            'available_t' => 'Kullanıcı adımı değiştirdikten sonra, diğer kullanıcılar ne zaman bu kullanıcı adını talep edebilir?',
            'available' => '<p>If you want to change back to your previous username, you can change back <strong>after 30 days.</strong> Everyone else needs to wait an additional <strong>7 days</strong> (37 days after changing) before they can claim your old username. </p>',
            'username_history_t' => 'Kullanıcı adı geçmişimi silebilir misiniz lütfen?',
            'username_history' => '
                <p>As the username history data comes from Mojang, the username history can not be removed. Mojang has previously stated that their intention was that previous usernames can be seen¹, and that they provide a direct method for the public to access this information².</p>
                <p class="font-14">¹<a href="https://help.minecraft.net/hc/en-us/articles/360034636712-Minecraft-Usernames" target="_blank" rel="noreferrer">https://help.minecraft.net/hc/en-us/articles/360034636712-Minecraft-Usernames</a></p>
                <p class="font-14 mb-0">²<a href="https://twitter.com/dinnerbone/status/554739042529849345" target="_blank" rel="noreferrer">https://twitter.com/dinnerbone/status/554739042529849345</a> (Tweet archived 2 years ago: <a href="http://archive.is/TeAyj" target="_blank" rel="noreferrer">http://archive.is/TeAyj</a>)
                </p>',
        ],
    ],
    'avatars' => [
        'start' => [
            'title' => 'Kendi Minecraft avatarınızı oluşturun',
            'subtitle' => 'Minecraft avatar oluşturucuyu kullanarak herhangi bir görünümden eğlenceli bir avatar oluşturun!',
            'avatar_face' => 'Yüz stili avatar',
            'avatar_bust' => 'Göğüs stili avatar',
            'avatar_cube' => 'Küp stili avatar',
            'avatar_head3d' => 'Özel 3D kafa',
        ],
        'user' => [
            'title' => 'Cilt Seç',
            'subtitle' => 'Oluşturmak istediğiniz avatar için Minecraft kullanıcı adını girin',
            'form_label' => 'Minecraft kullanıcı adı',
            'form_submit' => 'Devam',
        ],
        'output' => [
            'title' => 'Önizle ve kaydet',
            'subtitle' => 'Yeni Minecraft avatarınızı kullanmanın keyfini çıkarın',
            'download_info' => 'Sonuçtan memnun musunuz? Yeni avatarınızı buradan indirerek kullanmaya başlayın',
            'download_button' => 'Avatarı indir',
            'avatar_style' => 'Avatar stili',
            'skin_username' => 'Skin kullanıcı adı',
            'change' => 'Değiştir',
            'generate' => 'Oluştur',
            'avatar_colour' => 'Arka plan rengi',
            'avatar_colour_palette' => 'Palet',
            'avatar_colour_basic' => 'Temel',
        ],
        'meta' => [
            'title' => 'Minecraft Avatar Oluşturucu',
            'description' => 'Minecraft Avatar Oluşturucu: Minecraft görünümünüzü kullanarak özel Minecraft profil resimleri oluşturun',
        ],
    ],
    'totem' => [
        'title' => 'Özel Minecraft Totemi',
        'subtitle' => 'Minecraft Totem oluşturucuyu kullanarak herhangi bir görünümden Ölümsüz Totem içeren özel bir kaynak paketi oluşturun.',
        'download_info' => 'Önizlemeyi beğendiniz mi? Özel kaynak paketinizi kaydetmek için Minecraft sürümünüzü seçin:',
        'meta' => [
            'title' => 'Özel Minecraft Totemi Oluşturucu',
            'description' => 'Özel Minecraft Totemleri: Kendi veya başka oyuncuların Minecraft skin\'lerini kullanarak Ölümsüzlük Totemi ile özel bir Minecraft Kaynak Paketi oluşturun.',
        ],
        'type' => [
            'mini' => 'Skin\'inizin mini versiyonu!',
            'full' => 'Skin\'inizin tam versiyonu!',
            'model3d' => 'Skin\'inizin 3d model versiyonu!',
            'add_designs' => 'Daha fazla tasarım görmek ister misiniz? Tasarım önerinizi buradan gönderin:'
        ]
    ],
    'achievement' => [
        'header' => [
            'title' => 'Kendi Minecraft başarınızı oluşturun',
            'subtitle' => 'Use the Minecraft Achievement Generator to create your very own custom achievement and use show your advancements in anything you like to!',
        ],
        'generator' => [
            'yellow_text' => 'Sarı yazı',
            'white_text' => 'Beyaz yazı',
            'choose_icon' => 'Simge seç',
            'face' => 'Minecraft face instead of icon',
            'form_submit' => 'İndir',
            'form_label' => 'Minecraft kullanıcı adı',
            'download' => 'İndir',
            'embed' => 'Gömülü',
            'embed_copy' => 'Kopyala',
        ],
        'meta' => [
            'title' => 'Minecraft Achievement Generator',
            'description' => 'Generate custom Minecraft Achievements and Advancements with the Achievement creator. Download the image directly, use it in forum signatures, embed with HTML or BB code, and more',
        ],
    ],
    'armor' => [
        'header' => [
            'title' => 'Minecraft Armor Stand Creator',
            'subtitle' => 'Generate and create your very own custom Minecraft Armor Stands. Create different poses, positions, place items, and much more.',
        ],
        'meta' => [
            'title' => 'Minecraft Armor Stand Creator',
            'description' => 'Easily generate and create custom Minecraft Armor Stands. The editor helps you make different poses, positions, place items, custom skins, and much more.',
        ],
    ],
    'banner' => [
        'editor' => [
            'header' => [
                'title' => 'Minecraft Banner Editor',
                'subtitle' => 'Design and create your very own custom Minecraft Banners. These can be used to decorate your world or also commonly seen used as <a href="https://optifine.net" target="_blank" rel="nofollow">Optifine</a> capes.',
            ],
            'meta' => [
                'title' => 'Minecraft Banner Creator',
                'description' => 'Create and design your very own custom Minecraft Banners designs with all the patterns and colors from the game! These can be used to decorate your world or be worn as an Optifine Cape using the Banner Cape. You can generate give codes for banners or shields.',
            ],
        ],
        'gallery' => [
            'header' => [
                'title' => 'Minecraft Banner Gallery',
                'subtitle' => 'Browse the gallery of :count custom designed Minecraft Banners. You can use a Banner as a cape to make your Minecraft skin more unique, or use a Banner as a flag to decorate your world.',
            ],
            'meta' => [
                'title' => 'Minecraft Banner Gallery',
                'description' => 'Browse the gallery of :count custom designed Minecraft Banners. You can use a Banner as a cape to make your Minecraft skin more unique, or use a Banner as a flag to decorate your world.',
            ],
        ],
    ],
    'search' => [
        'meta' => [
            'title' => 'Search results: :search',
        ],
        'title' => 'Search results',
        'results' => 'Page :current for :count result|Page :current of about :count results ',
        'time' => '(:time seconds)',
        'username_available' => 'Username available*',
        'username_unavailable' => 'Username not available',
        'username_status' => 'Status',
        'username_status_available' => 'Available*',
        'username_status_unavailable' => 'Unavailable',
        'username_searches' => 'Searches',
        'username_searches_count' => ':count / day',
        'username_available_disclaimer' => '*Unless the name is temporarily or permanently banned by Mojang.',
        'no_results' => 'No profiles found. Try searching with UUID by changing the search type.',
        'no_results_tags' => 'No tagged skins found. Try searching for other tags such as "blue", "girl", "fox", etc...',
        'again' => 'Search again',
        'sorry' => 'Sssssssorry...',
        'view_profile' => 'View profile',
    ],
    'collection' => [
        'title' => 'Minecraft skin collection',
        'subtitle' => 'Minecraft skin koleksiyonumuzu inceleyin.',
        'filters' => 'Filtreler',
        'title_trending' => 'Trend olan',
        'title_all' => 'Tüm Minecraft Skin\'leri',
        'skin_tags' => 'Etiketlenmiş Skin\'ler',
        'filters_skin_type' => 'Skin türü',
        'filter_skin_type_steve' => 'Steve türü',
        'filter_skin_type_alex' => 'Alex türü',
        'cancel' => 'İptal',
        'apply' => 'Uygula',
        'username_minecraft_skin' => ':username kullanıcısının Minecraft skin\'i',
        'user_downloads' => '<span class="fw-500">:downloads</span> indirme|<span class="fw-500">:downloads</span> indirme',
    ],
    'favourites' => [
        'title' => 'Favoriler',
        'subtitle' => 'View and manage skins you saved for later in your favourites list',
        'sort' => 'Şuna göre sırala',
        'toast' => [
            'added' => 'Favoriler listenize eklendi',
            'removed' => 'Favoriler listenizden çıkarıldı'
        ],
        'skins' => [
            'button' => 'Skinler',
            'empty_headline' => 'Henüz favori skin yok',
            'empty_subtitle' => 'Henüz favoriler listenize kaydedilmiş herhangi bir skin yok. Sunucu sayfasını ziyaret edin ve bir sonraki favorinizi keşfedin!',
            'empty_browse' => 'Skinlere göz atın',
            'meta' => [
                'title' => 'Favori skinlerim',
                'description' => 'Favori kaydedilmiş Minecraft skinlerim',
            ],
        ],
        'servers' => [
            'button' => 'Sunucular',
            'empty_headline' => 'Henüz favori sunucu yok',
            'empty_subtitle' => 'Henüz favoriler listenize kaydedilmiş herhangi bir sunucu yok. Sunucu sayfasını ziyaret edin ve bir sonraki favorinizi keşfedin!',
            'empty_browse' => 'Sunuculara göz atın',
            'meta' => [
                'title' => 'Favori sunucularım',
                'description' => 'Favori Minecraft sunucularım',
             ],
        ],

    ],
    'cape' => [
        'editor' => [
            'title' => 'Minecraft pelerin düzenleyicisi',
            'subtitle' => 'Minecraft pelerin düzenleyicisini kullanarak kendi özel tasarım pelerinini oluştur.',
            'meta' => [
                'title' => 'Minecraft Pelerin Düzenleyicisi',
                'description' => 'Minecraft Pelerin Düzenleyicisi\'ni kullanarak kendi özel tasarım pelerinini oluştur.',
            ],
        ],
        'list' => [
            'title' => 'Minecraft pelerinleri',
            'subtitle' => 'Official capes of Minecraft',
            'meta' => [
                'title' => 'Minecraft Pelerin Listesi',
                'description' => 'Minecraft pelerin listesi: Mojang, Minecon, Kişisel, Özel ve süs pelerinleri dahil olmak üzere tüm resmi Minecraft pelerinlerini görüntüleyin',
            ],
        ],
        'detail' => [
            'title' => 'Pelerin :cape',
            'info' => 'Pelerin bilgileri',
            'profile_list' => 'Bu pelerinli profiller',
            'profiles' => ':profiles profil|:profiles profil',
            'meta' => [
                'title' => 'Minecraft Capes List',
                'description' => 'Minecraft cape list: View all official Minecraft capes including Mojang, Minecon, Personal, Speical and vanity capes',
            ],
        ],
        'list-custom' => [
            'title' => 'Özel Minecraft Pelerinleri',
            'description' => 'SkinMC üyeleri tarafından oluşturulan ve kullanılan özel pelerinleri göz atın ve görüntüleyin.'
        ]
    ],
    'servers' => [
        'title' => 'Minecraft sunucuları',
        'subtitle' => 'Minecraft sunucularına göz atın ve keşfedin',
        'all' => 'Tüm sunucular',
        'manage_your_servers' => 'Sunucularınızı yönetin',
        'add_new_server' => 'Yeni sunucu ekle',
        'filters' => [
            'trending' => 'Trend olan',
            'updated' => 'Güncellenen',
            'new' => 'Yeni',
            'most_viewed' => 'En çok görüntülenen',
            'top_voted' => 'Top voted',
            'sorting' => 'Sorting',
            'sort_by_latest' => 'Sort by latest',
            'sort_by_oldest' => 'Sort by oldest',
            'categories' => 'Categories',
            'server_location' => 'Server location',
            'show_results' => 'Show results',
            'show_more' => 'Show more',
            'show_less' => 'Show less',
            'clear_filters' => 'Clear filters',
            'reviews' => 'Reviews',
            'sort_by_highest_rating' => 'Sort by highest rating',
            'sort_by_lowest_rating' => 'Sort by lowest rating',
            'bedrock_and_java_support' => 'Bedrock and Java support'
        ],
        'review-count' => ':count Review|:count Reviews',
        'meta' => [
            'title' => 'Minecraft Server List',
            'description' => 'Browse and explore the Minecraft Servers list to find the best Minecraft server! Filter by the latest, most popular and much more',
        ],
        'reviews' => [
            'meta' => [
                'title' => 'Write a review',
            ],
            'editing' => 'You\'re editing your review from :date. Would you like to delete your review instead?',
            'welcome' => 'Hi :username. How was your overall experience with :servername?',
            'subtitle' => 'Leave an overall score of your past experience with the server.',
            'scale' => [
                'great' => 'Great',
                'good' => 'Good',
                'okay' => 'Okay',
                'meh' => 'Meh',
                'bad' => 'Bad',
            ],
            'rate-experience' => 'Next, rate your experience in these areas',
            'overall' => 'Overall',
            'server-team' => 'Server team',
            'community' => 'Community',
            'experience' => 'Experience',
            'availablility' => 'Uptime and availability',
            'shop' => 'Shop',
            'write-review-title' => 'Write a review',
            'write-review-subtitle' => 'Leave a few notes, you can highlight what you enjoyed, what made your experience special, or offer a few suggestions.',
            'write-review-helper' => 'Write a server review to share your experience with new players, and help the server owners with feedback.',
            'write-review-tips' => 'Here are some tips',
            'submit-title' => 'Ready to submit your review?',
            'submit-subtitle' => 'Almost done!',
            'submit-review' => 'Submit my review',
            'back' => 'Back',
            'continue' => 'Continue',
            'delete-title' => 'Are you sure you would like to delete your review?',
            'tos-checkbox-part-1' => 'By submitting this form you accept SkinMC\'s Terms of Service, Privacy Policy, and Community Guidelines. You also confirm that all of the information is accurate, and follows the',
            'tos-checkbox-part-2' => 'review guidelines.',
            'tos-checkbox-part-3' => 'Your review will be published after submission, but can be subject to review.'
        ],
        'slots' => 'Slots',
        'empty-helper' => 'You can try to do another search or',
        'empty' => 'Hmm it\'s still empty here.',
        'verified' => 'Verified',
        'review_translate_show_original' => 'Orijinalini göster',
        'review_translate' => 'İncelemeyi çevir',
        'description_translate' => 'Açıklamayı çevir',
        'create' => [
            'welcome' => 'Hoş Geldiniz',
            'basics' => 'Temel Bilgiler',
            'categories' => 'Kategoriler',
            'social_links' => 'Sosyal bağlantılar',
            'trailer_video' => 'Tanıtım videosu',
            'images' => 'Görüntüler',
            'images_description' => 'Daha sonra, sunucunuzun sunduğu hizmetleri tanıtmak için fotoğraf yükleyebilirsiniz.',
            'submit' => 'Gönder',
            'lets_get_your_server_added' => 'Sunucunuzu ekleyelim.',
            'basics-subtitle' => 'İnsanlara sunucunuzun ne hakkında olduğunu anlatın.',
            'description' => 'Açıklama',
            'description_tips' => 'İşte bazı ipuçları',
            'description_hint' => 'Yeni oyuncuları çekmek için sunucunuz için iyi bir açıklama yazın.',
            'categories-subtitle' => 'Sunucunuz için bazı kategoriler seçin',
            'missing-category' => 'Bir kategoriyi eksik mi?',
            'social_links_description' => 'Oyuncular sosyal medyada sunucunuza nereden bağlanabilirler?',
            'trailer_video_description' => 'Sunucunuzu bir YouTube videosuyla tanıtın.',
            'trailer_video_hint' => 'Video URL\'sini veya kimliğini (ID) yapıştırın:',
            'ready_to_submit_your_server' => 'Sunucunuzu göndermeye hazır mısınız?',
            'review-hint' => 'Gönderildikten sonra ekip, sunucu listeleme başvurunuzu dikkatlice inceleyecektir. Ardından karar verildikten sonra sunucunuz yayınlanacak veya yayına girmeden önce değişiklikler talep edilecektir.',
            'terms' => [
                'part-1' => 'Bu formu göndererek, SkinMC\'nin Hizmet Şartları, Gizlilik Politikası ve Topluluk Kurallarını kabul etmiş olursunuz. Ayrıca, yukarıdaki tüm bilgilerin doğru olduğunu ve',
                'part-2' => 'kurulum için sunucu gereksinimlerini',
                'part-3' => ', ve Minecraft sunucusunun temsil ettiğiniz kuruluş tarafından sahip olunduğunu ve yönetildiğini de kabul etmiş olursunuz.'
            ],
            'submit-application' => 'Başvuruyu gönder',
            'video-id-helper' => [
                'part-1' => 'The video ID is the string of numbers and letters after',
                'part-2' => 'For example if your video url is',
                'part-3' => ', then your video ID would be'
            ],
            'welcome_description' => 'In this step, we\'ll get started on adding your server. Tell us a bit about it, write a description, and in the next step you can upload some images.'
        ],
        'copy_server_ip' => 'Sunucunun IP\'sini kopyala',
        'all_minecraft_servers' => 'Tüm Minecraft Sunucuları',
        'promo' => [
            'title' => 'Bir Minecraft sunucusuna ev sahipliği yapıyor musunuz?',
            'ready_to_list_your_server' => 'Sunucunuzu listelemeye hazır mısınız?',
            'everything_you_need' => 'Sunucunuzu büyütmek için ihtiyacınız olan her şey',
            'list_your_server' => 'Sunucunuzu listeleyin',
            'list_your_server_description' => 'Sunucunuz için bir liste oluşturun, fotoğraflar, sosyal medya hesapları ve daha fazlasını ekleyin.',
            'find_players' => 'Oyuncuları bulun',
            'find_players_description' => 'Find and reach new players to join your server and grow your community.',
            'get_reviews' => 'İncelemeleri alın',
            'get_reviews_description' => 'Ask your community to review your server, and reward them in game.',
            'why_list_on_skinmc' => 'Why you should list your Server on SkinMC',
            'others' => 'Diğerleri',
            'quality_check_and_confirmation' => 'Kalite kontrolü ve onay',
            'quality_check_description' => 'Ekibimiz kaliteyi sağlamak için her sunucuyu inceler.',
            'verified_players' => 'Doğrulanmış Minecraft oyuncularının yorumları',
            'verified_players_description' => 'Votifier entegrasyonu ile meşru hesaplardan gerçek oyuncu yorumlarını toplayın.',
            'international' => 'Uluslararası',
            'international_description' => 'With translation features your listing is available to more players.',
            'server_listing_page' => 'Powerful Server listing page',
            'server_listing_page_description' => 'Add photos, description texts, youtube videos, and highlight why players should join your server.',
            'social_connections' => 'Social media connections',
            'social_connections_description' => 'Connect your Servers social accounts and show new players where they can find you.',
            'verified_badge' => 'Verification badge',
            'verified_badge_description' => 'Authentic servers can apply for a verification badge.',
            'owner_profile' => 'Owner profile',
            'owner_profile_description' => 'Add a personal touch, by completing your custom profile.',
            'categories' => 'Categories',
            'categories_description' => 'Different categories to make it easier to find your server.',
            'vote' => 'Vote',
            'vote_description' => 'Ask users to vote for your server.',
            'fair_listings' => 'Fair listings',
            'fair_listings_description' => 'Server listings can not be artificially boosted in results on SkinMC.',
            'support' => '24h support',
            'support_description' => 'Do you need help or have questions? You can always reach out and receive a fast reply.',
            'custom_features' => 'Custom features',
            'custom_features_description' => 'Missing a feature for your server? Open a ticket, and we\'ll implement it.',
            'faq' => [
                'title' => 'Answers to your questions',
                'suited-question' => 'Is my Minecraft Server suited for SkinMC?',
                'suited-answer' => 'Minecraft Players on SkinMC love to discover new experiences, content and engage with communities. On the platform you\'ll find a large variety of different, unique, fun Minecraft servers. From a large network to even a small survival server, it can make someones day!',
                'get-started-question' => 'How do I get started?',
                'get-started-answer' => 'Adding your Minecraft Server to the SkinMC Server List is very easy! You will first need to create an account, if you haven\'t already, and then follow the setup guide to get your server listed. Add a few photos and a nice description, and your server will be published in no time!',
                'players-question' => 'How can I get more players on my Minecraft Server?',
                'players-answer' => 'Building a community is the most crucial part of a long lasting Minecraft Server. Use the Minecraft Server List on SkinMC to find a new audience and continue to build your community. Ask your players to recommend your Server, or share your listing on social media platforms. Collecting good reviews can also play an important role to a great Server listing presence that attracts new players.',
                'more-question' => 'I have more questions. Where can I get help?',
                'more-answer' => 'You can reach out to SkinMC at any time, 24 hours, by using either the help button, the help desk, or by joining the Discord server.'
            ],
            'ready_to_list_description' => 'Add your Minecraft Server to the SkinMC Server List in just a few minutes. If you need any help, you can reach out around the clock and receive answers quickly.'
        ],
        'manage' => [
            'index' => [
                'welcome' => 'Welcome back, :username',
                'your_servers' => 'Your servers',
                'reviews_today' => 'Reviews today',
                'no_reviews_today' => 'No reviews today',
                'no_reviews_text' => 'Your servers haven\'t received any reviews today. Why not ask your players to leave one?',
                'tips' => [
                    'title' => 'Tips',
                    'description-title' => 'Write a good server description',
                    'description-body' => 'Helpful tips and advice to write a great server description.',
                    'images-title' => 'Adding server images',
                    'images-body' => 'Make your server listing stand out with great images.'
                ]
            ],
            'listings' => [
                'title' => 'Your Minecraft servers (:count)'
            ],
            'insights' => [
                'title' => 'Insights'
            ],
            'edit_server' => 'Edit server',
            'listing' => 'Listing',
            'to_do' => 'To do',
            'last_update' => 'Last update',
            'add_more_photos_to_publish' => 'Add more photos to publish',
            'looks_empty_here' => 'Looks empty here.',
            'get_started_by_adding_a_new_server' => 'Get started by adding a new server?'
        ],
        'status' => [
            'approved' => 'Approved',
            'pending_approval' => 'Pending approval',
            'published' => 'Published',
            'in_review' => 'In review'
        ]
    ],
    'editor' => [
        'import' => [
            'title' => 'Import Skin',
            'import_by_username' => 'Import by username',
            'import_button' => 'Import',
            'drag' => 'Drag and drop a skin here, or click',
            'click' => 'Select image'
        ],
        'download' => [
            'error' => [
                'no-data' => 'No skin data was provided. Please try again.',
                'invalid-format' => 'The skin data format is invalid. Please try again.',
                'invalid-data' => 'The skin data is corrupted. Please try again.',
                'generic' => 'Something went wrong while downloading your skin. Please try again.',
            ],
        ],
        'draw' => 'Draw',
        'eyedropper' => 'Eyedropper',
        'fill' => 'Fill',
        'move' => 'Move',
        'decrease_brightness' => 'Decrease brightness',
        'increase_brightness' => 'Increase brightness',
        'erase' => 'Erase',
        'undo' => 'Step back (CTRL+Z)',
        'redo' => 'Step forward (CTRL+Y)',
        'default_view' => 'Default view',
        'zoom_in' => 'Zoom in (CTRL +)',
        'zoom_out' => 'Zoom out (CTRL -)',
        'saved' => 'Last saved just now',
        'saving' => 'Auto saving...',
        'save_error' => 'An error occurred',
        'new_skin' => 'New skin',
        'previous_skins' => 'Previous skins',
        'backed_up_title' => 'Automatically saved skins',
        'backed_up_info' => 'Temporarily backed up to your local storage.',
        'backed_up_empty_title' => 'It\'s empty here',
        'backed_up_empty_info' => 'Once you start editing skins you\'ll see your 32 last edited skins here.',
        'backed_up_skins_count' => 'of 32 skin backups used',
        'backed_up_skins_count_info' => 'You can back up to up 32 skins. Once you reach 32 skins an older skin will be replaced with a new one.',
        'layers' => 'Layers',
        'body' => [
            'title' => 'Body',
            'overlay' => 'Overlay',
            'head' => 'Head',
            'torso' => 'Torso',
            'l_arm' => 'Left arm',
            'r_arm' => 'Right arm',
            'l_leg' => 'Left leg',
            'r_leg' => 'Right leg',
        ],
        'model' => 'Model',
        'steve' => 'Steve',
        'alex' => 'Alex',
        'stance' => [
            'title' => 'Position',
            'default' => 'Default',
            'walk' => 'Walk',
            'run' => 'Run',
            'hug' => 'T-pose',
            'fly' => 'Fly',
        ],
        'fullscreen' => 'Fullscreen',
        'fullscreen_exit' => 'Exit fullscreen',
        'grid' => 'Grid',
        'show_grid' => 'Show grid',
        'download' => [
            'title' => 'Save & Download',
            'subtitle' => 'SkinMC Account',
            'description' => 'Would you like to create a free SkinMC account to save your skin and future ones to the cloud?',
            'start_description' => 'Start download directly without saving to the cloud',
            'start' => 'Download skin',
        ],
        'help' => [
            'title' => 'Minecraft Skin Editor',
            'about' => 'Create and edit your custom Minecraft Skin easily with the SkinMC Editor. You can choose between Steve and Alex models, import skins from a file or username, and create your very own Minecraft Skin.',
            'draw' => 'Draw using the pen tool. Select a colour from the swatch to use with it.',
            'eyedropper' => 'Use the eyedropper to select a colour from your skin and add it to your current palette.',
            'fill' => 'Fill entire areas of your skin using the fill tool. Select a colour before using fill.',
            'move' => 'Pan and move around the skin editor canvas with the move tool.',
            'decrease_brightness' => 'Decrease the brightness of the currently active colour.',
            'increase_brightness' => 'Increase the brightness of the currently active colour.',
            'erase' => 'Erase pixels drawn on the secondary overlay layer.',
        ],
    ],
    'account' => [
        'level' => 'Level',
        'level_history' => 'Level history',
        'xp' => 'XP',
        'my_xp' => 'My XP',
        'xp_to_next_level' => ':xp XP to next level',
        'xp_info' => 'What are XP?',
        'xp_info_tooltip' => 'XP is earned for various activities such as adding tags to skins, inviting friends, commenting, and much more. With each XP earned you can level up and unlock cool things!',
        'settings' => [
            'title' => 'Account',
            'show_profile' => 'Go to profile',
            'friends' => 'Friends',
            'friends_detail' => 'Stay connected by using your friends list on SkinMC.',
            'security' => 'Security',
            'security_detail' => 'Update your login password and keep your account safe',
            'social' => 'Social media accounts',
            'social_detail' => 'Customise your profile by adding your social media',
            'link' => 'Link Minecraft account',
            'link_detail' => 'Link your Minecraft account and claim your profile.',
            'logout' => 'Do you want to log out from your SkinMC account?',
            'automatic_backups' => 'Automatic skin backups',
            'automatic_backups_info' => 'As a SkinMC plus member your skins are backed up daily.',
        ],
        'capes' => [
            'title' => 'SkinMC Minecraft Cape',
            'description' => 'Wear any cape you wish in-game with SkinMC Capes for free.',
            'drop' => 'Drag and drop a cape here',
            'drop-hint' => 'Dimensions 64x32px',
            'select' => 'Select image',
            'upload-cape' => 'Upload & use cape',
            'save-and-use' => 'Save & use',
            'uploaded-cape' => 'Uploaded cape',
            'no-cape' => 'No cape',
            'remove-cape' => 'Remove cape',
            'download' => 'Download the SkinMC Mod to see your and other players capes in-game.',
            'learn-more' => 'Learn more',
            'link-account' => 'Please link your Minecraft account to upload a cape.',
            'updated' => 'Your cape has been updated!',
            'removed' => 'Your cape has been removed.',
            'active' => 'Your cape is activated!'
        ],
        'favourite' => 'Favourite',
        'remove_favourite' => 'Remove favourite',
        'added_to_favourites' => 'Added to favourites',
        'removed_from_favourites' => 'Removed from favourites',
        'welcome' => 'Nice to see you!',
        'view-profile' => 'View my profile',
        'security' => [
            'title' => 'Security',
            'email' => 'Email address',
            'email-title' => 'Update your email address.',
            'save' => 'Save',
            'password' => 'Password',
            'password-title' => 'Change your password at any time.',
            'social-provider' => 'To update your account information, such as your password, please visit your login provider:',
            'social-provider-email' => 'Your associated email address with your login provider',
            'social-provider-connected' => 'Currently connected login providers',
            'current-password' => 'Current password',
            'forgot' => 'Forgot password?',
            'edit' => 'Edit',
            'delete' => 'Delete my account',
            'account-deletion' => 'Delete your SkinMC account.',
            'delete-info' => 'Please confirm to continue',
            'delete-confirmation' => 'Deleting your account is irreversible. All your personal information and content such as posts, favourites, uploaded capes, customisations, etc. will be deleted and can not be recovered.',
            'delete-confirmation-info' => 'Enter your password to continue',
            'yes-confirm-delete' => 'Yes, confirm delete',
            'account-successfully-deleted' => 'Your account and data has been successfully deleted.'
        ],
        'social' => [
            'title' => 'Social accounts',
            'edit' => 'Edit',
            'save' => 'Save',
            'link-account' => 'Link your Minecraft account to SkinMC to display your social links on your profile.',
            'finish-setup' => 'Finish setup',
            'connect-account' => 'Connect your accounts',
            'connect-description' => 'Choose which accounts you wish to connect and unlock special SkinMC integrations.',
            'empty' => 'No accounts added',
            'empty-description' => 'Your social media accounts will show up here and on your public profile. Once added they will add more personalisation to your page as well as enable integrations.',
            'connect' => 'Connect',
            'username' => 'username',
            'spotify' => 'Add your Spotify username to show your Spotify information on your profile.',
            'discord' => 'Enter your Discord username and number to display your Discord information on your SkinMC profile.',
            'youtube' => 'Add your YouTube channel to SkinMC which will display your YouTube channel on your profile.',
            'youtube-format' => 'Use the following format depending on your channel link:',
            'twitter' => 'Enter your X (formerly Twitter) username to display it on your profile.',
            'bluesky' => 'Enter your Bluesky handle e.g. username.bsky.social to display your Bluesky profile on your profile.',
            'twitch' => 'Enter your Twitch username to display your Twitch channel on your profile.',
            'reddit' => 'Enter your Reddit username to display your Reddit profile on your profile.',
            'github' => 'Enter your GitHub username to display your GitHub profile on your profile.',
            'telegram' => 'Enter your Telegram username to display your Telegram link on your profile.',
            'tiktok' => 'Enter your TikTok username to display your TikTok profile on your profile.',
            'snapchat' => 'Enter your Snapchat username to display your Snapchat profile on your profile.',
            'instagram' => 'Enter your Instagram username to display your Instagram profile on your profile.',
            'facebook' => 'Enter your Facebook username to display your Facebook profile on your profile.',
            'includes_skinmc_plus_benefits' => 'Includes SkinMC plus benefits',
        ],
        'recover' => [
            'title' => 'Recover your account',
            'subtitle' => 'Please enter your new password and confirm it to finish recovering your account.',
            'new_password' => 'New password',
            'repeat_new_password' => 'Repeat new password',
            'submit' => 'Recover account',
        ],
        'customise' => [
            'title' => 'Customise your profile',
            'description' => 'Add your social media, choose an emoji, set your location and more',
            'information' => 'Information',
            'preview' => 'Preview',
            'location' => [
                'title' => 'Location',
                'description' => 'Choose which location you would like to add to your profile.',
            ],
            'biography' => [
                'title' => 'About me',
                'description' => 'Write a bio for your profile.',
            ],
            'status' => 'Status',
            'status-toggle' => 'Show my online status',
            'emoji' => 'Emoji',
            'name-history-toggle' => 'Make username history private',
            'name-history-info' => 'Your Minecraft username history is currently',
            'name-history-toggle-on' => 'private',
            'name-history-toggle-off' => 'public',
            'theme' => 'Profile theme',
            'theme-primary' => 'Primary',
            'theme-secondary' => 'Secondary',
            'appearance' => 'Appearance',
        ],
        'link' => [
            'manage' => 'Manage linked Minecraft account',
            'description' => 'See and manage your linked Minecraft account',
            'title' => 'Linked Minecraft account',
            'current' => 'Currently linked Minecraft account.',
            'status' => 'You now have full access to all SkinMC features!',
            'linked' => 'Linked',
            'disconnect' => 'Disconnect',
            'disconnect-title' => 'Disconnect Minecraft account',
            'disconnect-info' => 'Are you sure you would like to disconnect your Minecraft account?',
            'disconnect-features' => 'You will lose access to commenting, customisation and other features which require a linked Minecraft account. To use these again you will be required to link a Minecraft account.',
            'disconnect-following' => 'Disconnecting your Minecraft account will permanently remove all your followed profiles.',
            'disconnect-posts' => 'Your created feed posts and liked will be deleted.',
            'can-not-undo' => 'This can\'t be undone.',
            'are-you-sure' => 'Are you sure?',
            'confirm' => 'Yes, confirm disconnect',
            'cancel' => 'No, cancel',
            'success' => 'Your account was successfully disconnected!'
        ],
        'finish-setup' => [
            'title' => 'Finish account setup',
            'description' => 'Finish setting up your account, and get full access to all features by linking your Minecraft account to SkinMC.',
            'link' => 'Link Minecraft account',
            'get-started' => 'Get started',
            'skip' => 'Skip',
            'claim' => 'Claim your profile',
            'customise' => 'Customise your page',
            'social' => 'Add social links',
            'comment' => 'Access to comment system',
            'direct_message' => 'Send direct messages',
            'feed' => 'Post status updates to the feed',
            'follow' => 'Follow your friends',
            'badge' => 'Badge displayed on your profile',
            'cape' => 'Custom Minecraft cape',
            'backup' => 'Automatic skin backup',
            'more' => 'And more...'
        ],
        'skins' => [
            'title' => 'Manage skins',
            'toggle' => 'Skin visibility toggled',
        ],
        'invite' => [
            'title' => 'My invites',
            'headline' => 'Invite your friends',
            'info' => 'Create an invite code to share with your friend. Once they accept it, you\'ll both earn some extra XP!',
            'description' => 'Create an invite for your friends and you\'ll both earn some extra XP.',
            'generate' => 'Create invite code',
            'empty' => 'You haven\'t created any invites yet.',
            'code' => 'Code',
            'expiry' => 'Each code works once.',
            'status' => [
                'title' => 'Status',
                'pending' => 'Pending',
                'accepted' => 'Accepted'
            ],
            'add_invite' => [
                'button' => 'Have an invite?',
                'title' => 'Add an invite code',
                'redeem' => 'Redeem invite',
            ],
            'share' => 'Send your friend an invite link'
        ],
        'emoji' => [
            'title' => 'SkinMC Emoji',
            'introducing' => 'Introducing',
            'info' => 'Customise your profile with emoji. Unlock more as you level up.',
            'unlocked_at' => 'Unlocked at level :level',
            'unlocks_at' => 'Reach level :level to unlock',
            'turn_off' => 'Show emoji'
        ]
    ],
    'notifications' => [
        'title' => 'Notifications',
        'view_all' => 'View all',
        'view_all_notifications' => 'View all notifications',
        'image' => 'Notification photo',
        'archived' => 'Archived',
        'inbox' => 'Inbox',
        'empty' => [
            'title' => 'You\'re up to date!',
            'text' => 'New notifications will show up here.',
            'text-archived' => 'Archived notifications will show up here.',
        ],
        'action' => [
            'archive' => 'Move to archive',
            'unarchive' => 'Unarchive',
            'open' => 'Tap to open',
        ],
        'toast' => [
            'archive' => 'Notification moved to archive',
            'unarchive' => 'Notification moved to inbox',
            'undo' => 'Undo',
        ]
    ],
    'error' => [
        'offline' => [
            'title' => 'No internet',
            'subtitle' => 'Your internet was disconnected. Please check your connection and reload the page to try again.',
            'try_again' => 'Try again'
        ],
        '404' => [
            'title' => '404 — Page not found.',
            'subtitle' => 'Hm, it looks like nothing was found at this location. Maybe try going back, or start a new search?',
            'try_again' => 'Back home'
        ],
    ],
    'heads' => [
        'list' => [
            'meta' => [
                'title' => 'Minecraft heads database',
                'description' => 'Explore the database of Minecraft heads to decorate your world with, or generate your own give command. View official heads, player heads and custom heads that feature textures which never change.'
            ],
            'header' => [
                'title' => 'Minecraft heads',
                'subtitle' => 'Explore our database of Minecraft heads to decorate your world, or generate your own give command. Player heads show the current skin worn by a user, and can change as the user updates their skin. Custom heads are linked to the Mojang skin file and never change. Custom heads must be summoned using a command block as the command is very long.',
            ],
            'count' => [
                'heads' => ':heads head|:heads heads',
            ],
            'customheads' => [
                'title' => 'Custom heads',
                'description' => 'Custom heads use the direct path to the texture file on the Mojang servers. Hence textures will never be deleted and the heads never change.',
                'version' => 'Minecraft 1.8 or later',
            ],
            'playerheads' => [
                'title' => 'Player heads',
                'description' => 'Player heads use the current skin texture of a Minecraft player. As they are username based, when the player changes their name or skin, the head changes.',
                'version' => 'All Minecraft versions',
            ]
        ],
    ],
    'mod' => [
        'title' => 'SkinMC Mod: Free custom capes',
        'headline' => 'Introducing the SkinMC Mod for more customisation',
        'description' => 'Giving back to the Minecraft community, with a free mod which enables players more customisation with custom capes, available and visible for anyone using the mod.',
        'download' => 'Download now',
        'download-title' => 'Download the mod',
        'requires' => 'Requires',
        'select-version' => 'Choose your Minecraft version',
        'get-started' => 'Getting started is simple',
        'step-1' => '1. Get the mod',
        'step-1-detail' => 'Install Fabric, then download the mod for your game version and install it by putting the jar in your mods folder.',
        'step-2' => '2. Link your account',
        'step-2-detail' => 'If you haven\'t already, sign up/in and connect your Minecraft account to SkinMC.',
        'step-3' => '3. Upload your cape',
        'step-3-detail' => 'Go to your account and upload your custom cape. It will be visible in-game.',
        'all-versions' => 'All versions',
        'latest' => 'Latest',
        'logged-in' => 'Upload your cape',
        'mirror' => 'Mirror',
        'download-via' => 'Download via:',
        'curseforge' => 'CurseForge',
    ],
    'app' => [
        'title' => 'SkinMC Android App',
        'headline' => 'Say hello to the SkinMC Android App.',
        'play-store-attribution' => 'Google Play ve Google Play logosu Google LLC kuruluşunun ticari markalarıdır.',
        'features' => 'Convenient features for on the go',
        'feature-qr' => 'Built in QR-Code scanner',
        'feature-qr-detail' => 'Use the built in QR-Code scanner to easily get a skin from your Desktop to the app, or scan your friends custom profile QR-Code.',
        'feature-files' => 'Saves directly to files',
        'feature-files-detail' => 'With the usage of Android Files Manager, the app can conveniently save Skins, making it easier to apply in Bedrock Edition.',
        'feature-noads' => 'No ads',
        'feature-noads-detail' => 'A clean designed interface, without distractions. Enjoy an Ad-free experience without intrusive annoyances from web to app.',
        'feature-experience' => 'Experience',
        'feature-experience-detail' => 'Enjoy the full SkinMC experience anywhere, with added features. Customise your profile, add your bio, create a fun QR-Code and more!',
        'get-app-headline' => 'Get the SkinMC App',
        'get-app-detail' => 'Your very own Minecraft companion for your Android — available for free.'
    ],
    'random' => [
        'title' => 'Loading random Minecraft skin',
        'description' => 'Loading random Minecraft skin',
        'headline' => 'Please wait...',
        'redirect' => 'You will be automatically redirected. Page not loading?',
        'click-here' => 'Click here',
        'messages' => [
            '1' => 'Loading random Minecraft skin...',
            '2' => 'Digging down...',
            '3' => 'Creeper, aw man...',
            '4' => 'Searching through chests...',
            '5' => 'Did you know the coming skin is completely random?',
            '6' => 'Random skin incoming...',
            '7' => 'One more block...',
            '8' => 'Sorting inventory...',
            '9' => 'Crafting diamond pickaxe...',
            '10' => 'Looking for Herobrine...',
        ],
    ],
    'feed' => [
        'title' => 'Feed',
        'following' => 'Following',
        'sign-up' => 'Sign up or log in to join the conversation.',
        'link-account' => 'Link your Minecraft account to join the conversation.',
        'placeholder' => 'What is happening?',
        'audience' => 'Audience',
        'audience-title' => 'Who can see this?',
        'everyone' => 'Everyone',
        'everyone-info' => 'Anyone on or off SkinMC.',
        'followers' => 'Followers',
        'followers-info' => 'Signed in or members following me.',
        'private' => 'Only me',
        'private-info' => 'Private post only I can see.',
        'submit' => 'Post',
        'like' => 'Like',
        'comment' => 'Reply',
        'share' => 'Share',
        'remaining' => 'Remaining',
        'profile' => 'Posts by :username',
        'posts' => 'All posts',
        'my-posts' => 'My posts',
        'view-all' => 'View all posts',
        'post' => [
            'meta' => ':username on SkinMC: :text',
            'title' => 'Post',
            'created' => 'Status update posted!',
            'confirm-delete' => 'Are you sure you would like to delete this post? It can not be undone.',
            'delete' => 'Delete post',
            'deleted' => 'Your post was deleted.',
        ],
        'follow-suggestions' => 'Follow the team',
        'explore' => 'Explore',
        'hashtag' => 'Hashtag',
    ],
    'private' => [
        'title' => 'Private posts',
        'text' => 'This post is private.'
    ] ,
    'liked' => [
        'title' => 'Liked'
    ],
    'following' => [
        'title' => 'Following',
        'text' => 'Sign in to view this post.'
    ],
    'tags' => [
        'empty' => 'No tags to vote on yet',
        'empty-subtitle' => 'Be the first to add one',
    ],
    'inbox' => [
        'title' => 'Messages',
        'details' => 'Details',
        'message_user' => 'Message',
        'write_message' => 'Write a message',
        'empty' => [
            'no_message_selected' => 'No message selected',
            'open_or_start_conversation' => 'Open a conversation from the message list, or start a new one.',
            'no_messages' => 'No unread messages',
            'start_conversation' => 'Once you start a new conversation, your messages will be displayed here.',
            'conversation' => 'This is the beginning of your conversation with :username.',
            'users' => 'Unable to find any users that match the current query.'
        ],
        'typing' => ':username is typing...',
        'new_message' => 'New message',
        'mark_unread' => 'Mark unread',
        'send_message' => 'Send message',
        'delete_message' => 'Delete message for you',
        'latest_conversations' => 'Latest conversations',
        'delete_conversation' => 'Delete conversation',
        'show_details' => 'Show details',
        'hide_details' => 'Hide details',
        'unread' => 'Unread',
        'deleted' => 'Deleted',
        'report_message' => 'Report message',
        'add_reaction' => 'Add reaction',
        'today' => 'Today',
        'reconnect' => 'Please reconnect your Minecraft account to chat',
        'account_disconnected' => 'This user disconnected their linked Minecraft account.',
        'saved_messages' => 'Saved messages',
        'new_message_to_label' => 'To',
        'external-link-to' => 'This link will take you to',
        'external-link-confirmation' => 'Are you sure you want to go there?',
        'external-link' => 'External link',
        'reply' => 'Reply'
    ],
    'server' => [
        'manage' => [
            'stats' => 'Stats'
        ]
    ],
    'report' => [
        'button' => 'Report',
        'title' => 'Report content',
        'describe' => 'Briefly describe why you are reporting this',
        'select' => 'Select report reason',
        'submit' => 'Submit report',
        'reasons' => [
            'INAPPROPRIATE_CONTENT' => 'Inappropriate content',
            'SPAM' => 'Spam',
            'HARASSMENT' => 'Harassment',
            'OTHER' => 'Other',
        ]
    ],
    'leaderboard' => [
        'title' => 'Leaderboard',
        'description' => 'View the SkinMC leaderboard of users.',
        'headline' => 'Top 10',
        'all-time-invites' => 'All time invites',
        'all-time-xp' => 'All time XP',
        '30-day-xp' => '30 days XP'
    ],
];
