<?php

return [
    'pronouns' => 'Pronouns',
    'pronouns_help' => 'Optional. Let people know how to refer to you.',
    'pronouns_placeholder' => 'e.g. she/her, he/him, they/them',
    'title' => 'Status',
    'add' => 'What’s happening?',
    'edit' => 'Edit status',
    'view' => 'View status',
    'placeholder' => "What's happening?",
    'message' => 'Status message',
    'emoji' => 'Choose an emoji',
    'remove_emoji' => 'Remove emoji',
    'clear_after' => 'Clear after',
    'hour' => '1 hour',
    'day' => '1 day',
    'week' => '1 week',
    'forever' => 'Until I clear it',
    'expires' => 'Clears :time',
    'save' => 'Save status',
    'saving' => 'Saving…',
    'saved' => 'Status saved',
    'cleared' => 'Status cleared',
    'clear' => 'Clear status',
    'close' => 'Close status',
    'react' => 'React to status',
    'reacted' => 'Reaction sent',
    'reply' => 'Reply to status',
    'reply_placeholder' => 'Reply…',
    'sending' => 'Sending…',
    'replied' => 'Reply sent',
    'chat_reaction' => 'Reacted to a status',
    'chat_reply' => 'Replied to a status',
    'chat_preview' => 'Status: :message',
    'sign_in' => 'Sign in to react or start a conversation',
    'restricted' => 'Status interactions are unavailable based on messaging settings.',
    'error' => 'Couldn’t update the status. Please try again.',
    'send_error' => 'Couldn’t send your response. Please try again.',
    'rate_limited' => 'Please wait a moment before sending another response.',
    'unavailable' => 'This status has changed or expired.',
    'invalid_emoji' => 'Please choose a single emoji.',
    'picker_error' => 'Couldn’t load emojis. Please try again.',
];
