<?php

return [
    'title' => 'Blocked accounts',
    'description' => 'Manage the accounts you have blocked.',
    'empty_page' => 'No blocked accounts remain on this page.',
    'empty' => 'You haven’t blocked any accounts.',
    'block' => 'Block :username',
    'unblock' => 'Unblock :username',
    'block_title' => 'Block :username?',
    'unblock_title' => 'Unblock :username?',
    'confirm_block' => 'Block',
    'confirm_unblock' => 'Unblock',
    'cancel' => 'Cancel',
    'block_description' => 'You won’t see each other’s posts or be able to message or follow each other. You’ll both be removed from each other’s followers. You can unblock them in settings.',
    'groups_description' => 'In shared groups, you’ll stay members but won’t see each other’s messages or receive notifications from each other.',
    'blocked' => 'Account blocked.',
    'unblocked' => 'Account unblocked.',
    'error' => 'Your change couldn’t be saved. Please try again.',
    'saving' => 'Saving…',
    'unavailable' => 'This interaction is unavailable.',
    'content_unavailable' => 'This content is unavailable.',
    'profile_blocked' => 'You blocked :username.',
    'profile_unavailable' => 'This account’s social content is unavailable.',
    'conversation_unavailable' => 'Messaging is unavailable for this conversation. Your previous messages are still here for reference and reporting.',
    'blocked_on' => 'Blocked :date',
    'back_settings' => 'Back to settings',
    'shared_group_notice' => 'This group includes an account you can’t interact with. Their messages and notifications will be hidden. Group membership remains visible.',
];
