<?php

return [
    'login' => [
        'title' => '登录',
        'email' => '电子邮箱地址',
        'password' => '密码',
        'button' => '登录',
        'editor_save_context' => "Log in to save your skin to the gallery. Your work won\\'t be lost.",
        'forgot' => '找回密码',
        'reset' => '重置',
        'register' => '还没有一个账户？',
        'signup' => '注册',
        'google' => '使用谷歌账户登录',
        'microsoft' => '使用微软账户登录',
        'facebook' => '使用Facebook账户登录',
        'twitter' => '使用 Twitter 账户登录',
        'divider' => '或',
    ],
    'signup' => [
        'title' => '注册',
        'existing' => '已经有一个账户？',
        'button' => '同意并继续',
        'terms_by_selecting' => '通过选择',
        'terms_agree_to' => '，我同意SkinMC的',
        'terms_acknowledge' => '并承认',
    ],
    'recover' => [
        'title' => '恢复账户',
        'description' => '丢失了您的密码？请输入您的电子邮件地址以恢复密码。',
        'button' => '发送恢复邮件',
        'found' => '忘记密码?',
    ],
    'logout' => [
        'title' => '登出',
        'description' => '您确定要登出您的 SkinMC 账户吗？',
        'logout' => '确定登出',
        'cancel' => '取消',
    ],
    'profile_qrcode' => [
        'title' => '扫描二维码',
        'done' => '已完成',
    ],
    'language' => [
        'title' => '语言',
        'description' => '选择您的语言',
        'contribute' => '协助翻译',
        'contribute_add' => '添加翻译',
        'updated' => '已设置您的语言',
    ],
    'copied' => '已复制到剪贴板！',
    'close' => '关闭',
    'feedback' => [
        'title' => '反馈意见',
        'type' => [
            'select' => '请选择反馈类型',
            'label' => '反馈类型',
            'comment' => '评论',
            'question' => '问题',
            'bug' => 'Bug反馈',
            'feature' => '功能建议',
        ],
        'submit' => '提交',
        'nps' => '从0到10，你向朋友推荐SkinMC的可能性有多大？',
        'success' => [
            'title' => '感谢!',
            'message' => '您的消息已发送，预计将很快得到回复！如有进一步的问题，请随时加入Discord或提交另一条消息。',
        ],
    ],
];
