<?php

return [
    'skins' => '皮肤',
    'avatars' => '头像',
    'editor' => '编辑器',
    'heads' => '头颅',
    'capes' => '披风',
    'servers' => '服务器',
    'achievement' => '成就',
    'armor' => '盔甲架',
    'banners' => '旗帜',
    'banner' => 'Banner Editor',
    'profile' => '个人资料',

    'generators' => '生成器',

    // Navigation dropdowns
    'feed' => 'Feed',
    'discover' => 'Discover',
    'mods' => 'Mods',
    'shaders' => 'Shaders',
    'resource_packs' => 'Resource Packs',
    'modpacks' => 'Modpacks',
    'datapacks' => 'Data Packs',
    'plugins' => 'Plugins',

    'logout' => '登出',
    'register' => '注册',
    'login' => '登录',
    'about' => '关于',
    'contact' => '联系',
    'faqs' => '常见问题',

    'minecraft_name' => 'Minecraft名字',
    'minecraft_uuid' => '我的世界 UUID',
    'what' => '什麼',
    'recent_searches' => '近期搜索',
    'username' => '用户名',
    'uuid' => 'UUID',
    'search' => '搜索',
    'search_placeholder' => '试试',
    'search_placeholder_uuid' => '输入 UUID',
    'start_search' => '开始搜索',
    'cancel_search' => '取消',
    'search_type' => '搜索类型',
    'search_type_all' => '所有结果',
    'profiles' => '个人资料',
    'view_skin' => '查看皮肤',
    'edit_skin' => '编辑皮肤',
    'make_avatar' => '制作头像',
    'find_heads' => '查找玩家的头部',

    'home' => '首页',
    'help' => '帮助',
    'tools' => '工具',
    'more-tools' => '更多工具',
    'skin_viewer' => '皮肤查看器',
    'avatar_maker' => '创建头像',
    'collections' => '收藏夹',
    'popular_skins' => '热门皮肤',
    'cartoon_skins' => '卡通皮肤',
    'animal_skins' => '动物皮肤',
    'community' => '社区',
    'imprint' => '标识',
    'cookies' => 'Cookies',
    'terms' => '《服务条款》',
    'privacy' => '隐私政策',
    'app' => '应用程序',
    'mod' => 'Mod（模组）',
    'totem' => '图腾',
    'cube' => 'Cube',
    'new' => 'New',

    'feedback' => '意见反馈',
    'status' => '状态',
    'recent_searches_placeholder' => '当您开始搜索时，您过去的搜索将显示在这里。',
    'recent_views_placeholder' => '在访问了一些个人资料之后，您过去访问过的个人资料将会显示在这里。',
    'moderate' => '审核',
    'listings' => '列表',
    'add' => '添加',

    'theme' => [
        'title' => 'Theme',
        'dark' => '暗色模式',
        'light' => '亮色模式',
        'auto' => 'Auto'
    ],
];
