<?php

return [
    'auth' => [
        'login' => [
            'title' => '欢迎使用SkinMC ！',
        ],
        'register' => [
            'title' => '注册 SkinMC',
            'subtitle' => '开始并创建您的账户以便完全访问。',
        ],
    ],

    'home' => [
        'hero_slogan' => '你的Minecraft皮肤的地方。',
        'hero_slogan_alt_1' => 'Everything Minecraft. One place.',
        'hero_slogan_alt_2' => 'Where Minecrafters meet.',
        'hero_cta' => '给我惊喜',
        'hero_explore_cta' => '探索皮肤',
        'skin_viewer' => '皮肤查看器',
        'skin_viewer_detail' => '浏览 :count 皮肤',
        'skin_editor' => '皮肤编辑器',
        'skin_editor_detail' => '设计你自己的皮肤',
        'avatar_maker' => '头像生成器',
        'avatar_maker_detail' => '生成你自定义Minecraft头像个人资料图片。',
        'trending' => '热门',
        'minecraft_skin' => 'Minecraft皮肤',
        'favourite' => '收藏',
        'collections' => '收藏夹',
        'collections_detail' => '每次管理Minecraft皮肤',
        'about_skinmc' => '关于SkinMC',
        'about_find' => '寻找任何皮肤',
        'about_find_detail' => '使用SkinMC 搜索任何Minecraft用户名来查找、查看和下载您的下一个新皮肤。',
        'about_download' => '下载或编辑',
        'about_download_detail' => '找到您喜欢的皮肤吗？将其添加到您的收藏夹中，编辑或下载并使它成为您自己的皮肤。',
        'about_platform' => '跨平台',
        'about_platform_detail' => '想把皮肤带上去吗？扫描二维码并保存您手机上的图像到Minecraft PE。',
        'meta' => [
            'title' => 'Minecraft皮肤查看器',
            'description' => '查看并下载Minecraft皮肤，发现管理收藏中最好的皮肤，检查用户名的可用性和历史记录，以及更多！',
        ],
        'recently_viewed' => '最近查看',
        'explore_title' => '尝试一些新的东西！',
        'explore' => '探索新的想法和工具',
        'servers_browse' => '浏览服务器',
        'servers' => '发现最好的 Minecraft 服务器',
        'heads' => 'Minecraft 头部',
        'head_description' => '浏览 Minecraft 头部数据库，或创建新数据库。',
        'achievement' => '成就生成器',
        'achievement_detail' => '创建您自己的自定义和个性化成就。',
        'continue' => '继续浏览',
    ],
    'profile' => [
        'verified' => '已验证的个人资料',
        'minecraft_profile' => 'Minecraft资料',
        'show_qr_code' => '显示二维码',
        'favourite' => '收藏',
        'user_title' => ':username Minecraft皮肤',
        'user_views' => '查看 :view时间 |查看 :view时间',
        'uuid' => 'UUID',
        'copy' => '复制',
        'link' => '链接',
        'skin_history' => 'Minecraft皮肤历史 (:skins)',
        'username_history' => '历史用户名',
        'username_history_name' => '名称',
        'username_history_timestamp' => '更改于',
        'username_history_initial_name' => '初始名称',
        'user_downloads' => ':downloads 下载|:downloads 下载',
        'download_skin' => '下载皮肤',
        'apply_skin' => '应用皮肤',
        'capes' => '支出',
        'claim_profile' => '您是 :username? 认领您的个人资料以验证并定制它!',
        'claimed' => '已申领的个人资料',
        'meta_description' => '查看并下载 :username Minecraft皮肤。查看他们的 UUID，名称历史，详细统计信息和更多',
        'created_at' => '更新时间：:changed_at',
        'skins' => [
            'meta_title' => ':username Minecraft历史皮肤',
            'meta_description' => '查看 :username Minecraft 皮肤历史和先前使用过的皮肤。 使用历史记录浏览旧的或过去使用过的皮肤、备份和恢复或收集新皮肤。',
            'title' => 'Minecraft皮肤历史',
        ],
        'qr_code' => [
            'meta_title' => ':username的二维码',
            'meta_description' => ':username 自定义 Minecraft 个人资料二维码',
        ],
        'sub_nav' => [
            'skin' => '皮肤',
            'about' => '关于',
            'usernames' => '用户名',
            'head' => '头部',
            'comments' => '评论',
        ],
        'cape' => '披风',
        'elytra' => '鞘翅',
        'nametag' => '名称标签',
        'animation' => '动画',
        'rotation' => '旋转',
        'none' => '无',
        'idle' => '空闲',
        'walk' => '走',
        'run' => '跑',
        'fly' => '飞',
        'follow' => '关注',
        'following' => '已关注',
        'unfollow' => '取消关注',
        'followers' => '关注者',
        'toast' => [
            'following' => '你正在关注 :username ！',
            'follow-self-error' => '对不起:username, 你不能关注自己。',
            'unfollowed' => '你已经取消关注 :用户名',
        ],
        'edit' => '编辑个人资料',
        'joined' => '注册时间',
        'role' => 'Role',
        'server-fav-list-empty' => '似乎 :username 尚未收藏任何服务器。如果 :username 收藏了服务器，您可以在这里看到。',
        'server-own-list-empty' => '似乎 :username 尚未设置拥有的服务器。如果 :username 设置了服务器，您可以在这里看到。',
        'capes-list-empty' => '似乎 :username 尚未穿戴任何披风。如果 :username 穿戴了披风，您可以在这里看到。',
        'feed-own-list-empty' => '看起来你还没有发布任何内容！如果你发布了，你可以在这里看到你的帖子。',
        'feed-list-empty' => '唔...，似乎 :username 还没有发布任何内容。如果 :username 发布了一些内容，您可以在这里看到。',
        'following-own-list-empty' => '看起来你还没有关注任何人！一旦你开始关注人，你可以在这里看到他们。',
        'following-list-empty' => '嘿，看起来 :username 好像没有关注任何人。一旦 :username 开始关注其他人，你就可以在这里看到。',
        'followers-own-list-empty' => '一旦人们开始关注您的个人资料，他们就会出现在这里。',
        'followers-list-empty' => 'Hmm，看起来没有任何人跟随 :username。 成为第一个跟随 :username的人。一旦有更多人跟随，你可以在这里看到他们。',
        'render' => '渲染器',
        '3d' => '3D 渲染',
        '2d' => '2D 渲染',
        'name-history-info' => '用户名历史记录正在消失。 Mojang已经在2022年9月13日取消了对访问名字历史API的支持，因此不再提供准确的名字历史。 如果您想要隐藏您的名称历史，请确认您的个人资料并转到设置以使其成为隐私。',
        'edit-skins' => '编辑皮肤历史记录',
        'hide-skin' => '隐藏皮肤',
        'show-skin' => '显示皮肤',
        'edit-skin' => '编辑皮肤',
        'servers' => [
            'title' => ':username 的服务器',
        ],
        'cape-list' => [
            'title' => ':username 的披风',
        ],
    ],
    'skin' => [
        'meta' => [
            'title' => ':username Minecraft皮肤',
            'description' => 'Minecraft皮肤。下载并查看皮肤，看看哪些玩家也穿着同一个皮肤。',
            'tags' => ':username Minecraft 皮肤, :username 皮肤, Minecraft 皮肤, :username 自定义 Minecraft 皮肤, 下载皮肤, 拥有相同皮肤的玩家',
        ],
        'title' => ':username Minecraft皮肤',
        'head' => '头部指令',
        'head_info' => '使用命令块',
        'first_wearing' => '首次看到玩家戴着这个皮肤：',
        'profiles' => ':profiles 个人资料|:profiles 个人资料',
        'profiles_title' => ':profiles 个人资料带有此皮肤|:profiles 个人资料带有此皮肤',
        'screenshot' => 'Screenshot',
    ],
    'skins' => [
        'meta' => [
            'title' => '页面 :current - 所有Minecraft皮肤',
            'description' => '浏览我们的 :last 页共计:total 自定义Minecraft皮肤，下载您最喜欢的下一款皮肤！',
            'tags' => ':usernameMinecraft皮肤，:username皮肤，Minecraft皮肤，:username自定义Minecraft皮肤，下载皮肤，拥有相同皮肤的玩家',
            'tags-title' => ':tag Minecraft皮肤',
            'tags-description' => '浏览我们的 :last 页共计:total :tag Minecraft皮肤，下载您最喜欢的 :tag 皮肤！',
            'tags-metatags' => ':tagMinecraft皮肤，:tag皮肤，Minecraft皮肤，:tag自定义Minecraft皮肤，下载:tag皮肤,，Minecraft:tag皮肤',
        ],
        'title-skin-tags' => '已标记的Minecraft皮肤',
        'subtitle' => '第 :current 页，共 :last 页，共计 :total Minecraft皮肤',
        'subtitle-skin-tags' => '第 :current 页，共 :last 页，共计 :total 已标记的Minecraft皮肤',
        'sort_by' => '排序方式',
        'latest' => '最新皮肤',
        'most_profiles' => '使用次数最多的皮肤',
        'profiles_today' => '今天使用次数最多的',
        'profiles_this_week' => '本周使用次数最多的',
        'profiles_this_month' => '本月使用次数最多的',
        'default' => '默认排序',
        'this_month' => '本月添加',
        'this_week' => '本周添加',
        'today' => '今日添加',
        'random' => '随机排序',
        'similar' => '相似皮肤',
        'no_similar_skins' => '尚未找到相似的皮肤。',
        'favorite' => ':count 收藏|:count 收藏夹',
    ],
    'skin-tags' => [
        'faq' => '什么是标签？',
        'about' => '标签是您添加皮肤到相关类别的一种方式。添加标签可以让您轻松地发现更多皮肤！',
        'guidelines' => [
            'good' => [
                'title' => '关于良好标签的一般准则是：',
                'short' => '短',
                'descriptive' => '说明',
                'spelled' => '正确写法',
            ],
            'bad' => [
                'title' => '请不要添加以下标签',
                'general' => '过于笼统',
                'specific' => '太特定的',
                'too-many-tags' => '应该是三个独立的标签',
                'spelling' => '应该是 :example',
            ],
        ],
        'toast' => [
            'added' => '标签 ":tag" 已添加到投票',
            'removed' => '标签 ":tag" 已被移除',
            'upvote' => '已对 ":tag" 表示赞成。',
            'downvote' => '已对 ":tag" 表示反对。',
        ],
        'vote' => [
            'up' => '赞成票',
            'down' => '反对票',
            'remove' => '删除投票',
        ],
    ],
    'contact' => [
        'contact' => '联系人',
        'email' => '如果您有任何问题，请随时在 <a href="mailto:support@skinmc.net">support@skinmc.net</a> 上向我们进行反馈。',
        'faq' => '我们恳请您先查看 <a href=":link">常见问题</a> 页面，或许您的问题将在此得到解答。',
        'other' => '其他连接',
        'other_discord' => '加入Discord服务器并与他人建立联系，聊聊关于游戏的事情，分享您最喜欢的整合包，并获得来自社区的帮助。',
        'other_twitter' => '在 Twitter 上关注以查看新更新或功能发布的时间，查看每周皮肤等等。',
        'other_instagram' => '在Instagram上关注SkinMC，浏览并发现酷炫的新特色Minecraft皮肤和图像。',
        'other_facebook' => '在Facebook上成为粉丝，查看所有帖子，在探索《我的世界》内容时，您可以在这些帖子中发表评论并与他人交谈。',
    ],
    'about' => [
        'intro' => '</span>你的</span> </span>Minecraft</span> </span>皮肤</span> <span>平台</span>
//</span>你</span> </span>的</span> </span>Minecraft</span> </span>皮</span> </span>肤</span> <span>平</span> </span>台</span>',
        'header_credit' => '示例“Epic Nether Battle”By',
        'info' => '跟上一切进度。',
        'info_explainer' => '查看玩家历史名称，查看他们以前的皮肤，将他们添加为朋友，下载皮肤，甚至获取详细统计。',
        'card_find_title' => '查找任何Minecraft玩家',
        'card_find_detail' => '通过搜索您选择的任何玩家用户名或 UUID 来开始。',
        'card_view_title' => '查看、保存&编辑',
        'card_view_detail' => '找到你喜欢的皮肤了吗？通过下载或使用编辑器将其保存为你自己的皮肤。',
        'card_claim_title' => '获取验证',
        'card_claim_detail' => '连接您的Minecraft账户并索取您的个人资料以解锁更多精彩功能！',
        'card_customise_title' => '自定义你的个人资料',
        'card_customise_detail' => '已验证的玩家可以添加他们的社交媒体链接并自行设置他们的个人资料。',
        'card_friends_title' => '添加好友',
        'card_friends_detail' => '在 SkinMC 上与您的朋友连接，然后在个人资料中显示您的朋友列表。',
        'card_history_title' => '用户名&历史皮肤',
        'card_history_detail' => '使用高级搜索来查找和查看玩家的用户名/皮肤历史记录。',
        'founders' => '创建者',
        'founders_cofounder' => 'SkinMC联合创始人',
        'head_of_design' => '设计主管',
        'head_of_code' => '代码负责人',
        'feedback' => '向我们发送反馈',
        'faq' => '有关Minecraft、皮肤和更多的问题？阅读我们的常见问题解答。',
        'faq_link' => '访问常见问题中心',
        'contact' => '您想要联系或有进一步的问题吗？直接联系我们。',
        'contact_link' => '联系我们',

    ],
    'faq' => [
        'title' => '常见问题解答',
        'subtitle' => '常见问题',
        'help' => '需要更多帮助?',
        'discord' => '加入Discord服务器来与其他Minecraft玩家聊天。',
        'contact' => '联系我们',
        'q' => [
            'change_skin_t' => '如何更改我的Minecraft皮肤？',
            'change_skin' => '
                <p>要更改皮肤，请执行以下操作：</p>
                <ol>
                    <li>访问<a href="https://my.minecraft.net/zh-hans/login/">“登录|Minecraft”</a>并使用您的账户登录</li><li>登录后，选择左侧菜单上的我的游戏→<b>“更改皮肤”</b></li><li>然后，选择你喜欢的模型并上传你喜欢的皮肤。</li>
                </ol>',
            'change_username_t' => '如何更改我的Minecraft用户名？',
            'change_username' => '
                <p>要更改您的用户名，请做以下操作：</p>
                <ol>
                    <li>访问 <a href="https://account.mojang.com/login" target="_blank" rel="nofollow">https://account.mojang.com/login</a> 并使用您的 Mojang 帐户登录。</li>
                    <li>查找您的Minecraft 配置文件名并按 <b>"(更改)"</b> 按钮</li>
                    <li>在下一页， 输入您所需的新用户名。</li>
                    <li>通过输入密码确认更改并按“更改名称”。</li>
                </ol>',
            'dl_t' => '如何下载某人的Minecraft皮肤？',
            'dl' => '
                <p>要下载任何一款Minecraft皮肤，请执行以下操作：</p>
                <ol>
                    <li>按下搜索栏，输入要下载皮肤的玩家的用户名。</li>
                    <li>在个人资料页面上，您可以预览皮肤</li>
                    <li>点击预览下的<strong>下载皮肤</strong>按钮</li>
                </ol>',
            'submit_q' => '如何向收藏提交皮肤？',
            'submit_a' => '<p>请填写以下简短表格，其中包含要添加到收藏中的用户名及其类别。 <a href="https://forms.gle/f4Jh5RpGfsHAZ5xE8" target="_blank">收藏提交表</a>',
            'mcpe_t' => '我可以在 Minecraft PE 上使用皮肤吗？',
            'mcpe' => '
                <p>对要在Minecraft PE（手机版）中使用皮肤，请执行以下操作：</p>
                <ol>
                    <li>在手机上打开SkinMC.net，然后点击搜索栏r</li>
                    <li>输入您想要下载的玩家皮肤的用户名</li>
                    <li>点击预览下的<strong>下载皮肤</strong>按钮 </li>
                    <li>打开Minecraft PE，点击右侧的<strong>个人资料</strong></li>
                    <li>点击<strong>+</strong>，或编辑角色并转到“经典皮肤选项卡”</li>
                    <li>点击“拥有”，然后点击“导入”，然后单击“选择新皮肤”</li>
                </ol>',
            'change_times_t' => '我可以多长时间更改我的用户名？',
            'change_times' => '<p>您可以<strong>每30天</strong>更改<strong>一次</strong>您的Minecraft用户名</p>',
            'available_t' => '在我更改了我的用户名后，他人何时可以申请它？',
            'available' => '<p>如果你想要改回你以前的用户名, 你可以在 <strong>30天后</strong>重新更改。其他所有人都需要等待额外的<strong>7天</strong> (更改后37天)才能申领您的旧用户名。 </p>',
            'username_history_t' => '你可以删除我的用户名历史记录吗？',
            'username_history' => '
                <p>由于用户名历史数据来自Mojang，因此无法删除用户名历史。Mojang之前曾表示，他们的意图是可以看到以前的用户名¹，并为公众提供了一种直接访问这些信息的方法²。</p>
                <p class="font-14">¹<a href="https://help.minecraft.net/hc/en-us/articles/360034636712-Minecraft-Usernames" target="_blank" rel="noreferrer">https://help.minecraft.net/hc/en-us/articles/360034636712-Minecraft-Usernames</a></p>
                <p class="font-14 mb-0">²<a href="https://twitter.com/dinnerbone/status/554739042529849345" target="_blank" rel="noreferrer">https://twitter.com/dinnerbone/status/554739042529849345</a>（2年前存档的推文：<a href="http://archive.is/TeAyj" target="_blank" rel="noreferrer">http://archive.is/TeAyj</a>）
                </p>',
        ],
    ],
    'avatars' => [
        'start' => [
            'title' => '创建您自己的Minecraft头像',
            'subtitle' => '使用Minecraft头像生成器从任何皮肤创建一个有趣的头像！',
            'avatar_face' => '面部样式头像',
            'avatar_bust' => '半身像',
            'avatar_cube' => '立体风格头像',
            'avatar_head3d' => '自定义3D 头部',
        ],
        'user' => [
            'title' => '选择皮肤',
            'subtitle' => '输入您想要生成的头像的Minecraft用户名',
            'form_label' => 'Minecraft用户名',
            'form_submit' => '继续',
        ],
        'output' => [
            'title' => '预览并保存',
            'subtitle' => '使用您新的Minecraft头像享受游戏',
            'download_info' => '喜欢这个结果吗？开始使用您的新头像，请在这里下载它',
            'download_button' => '下载头像',
            'avatar_style' => '头像样式',
            'skin_username' => '皮肤用户名',
            'change' => '更改',
            'generate' => '生成',
            'avatar_colour' => '背景色',
            'avatar_colour_palette' => '调色板',
            'avatar_colour_basic' => '基本',
        ],
        'meta' => [
            'title' => 'Minecraft头像生成器',
            'description' => '创建Minecraft头像：使用Minecraft皮肤创建自定义Minecraft个人资料图片',
        ],
    ],
    'totem' => [
        'title' => '自定义Minecraft图腾',
        'subtitle' => '使用Minecraft 图腾生成器创建一个自定义资源包，其中包含任何皮肤的不死图腾。',
        'download_info' => '喜欢这个预览吗？选择您的Minecraft版本来保存您的自定义资源包：',
        'meta' => [
            'title' => 'Minecraft自定义图腾生成器',
            'description' => '自定义Minecraft物品：使用您或任何其他玩家的Minecraft皮肤生成和创建一个自定义Minecraft资源包，带有不死图腾。',
        ],
        'type' => [
            'mini' => '你的皮肤的迷你版本！',
            'full' => '你的皮肤完整版本！',
            'model3d' => '你的皮肤的3d模型！',
            'add_designs' => '想要看到更多的设计吗？在这里提交您的设计建议：',
        ],
    ],
    'achievement' => [
        'header' => [
            'title' => '创建你自己的Minecraft成就',
            'subtitle' => '使用Minecraft成就生成器创建您自己的自定义成就，并在您喜欢的任何东西中显示您的进度！',
        ],
        'generator' => [
            'yellow_text' => '黄色文本',
            'white_text' => '白色文本',
            'choose_icon' => '选择图标',
            'face' => 'Minecraft面部而非图标',
            'form_submit' => '下载',
            'form_label' => 'Minecraft用户名',
            'download' => '下载',
            'embed' => '嵌入',
            'embed_copy' => '复制',
        ],
        'meta' => [
            'title' => 'Minecraft成就生成器',
            'description' => '与成就创建者生成自定义Minecraft成就和进度。 直接下载图像，将其用于论坛签名，嵌入HTML或 BB 代码，以及更多',
        ],
    ],
    'armor' => [
        'header' => [
            'title' => 'Minecraft盔甲架创作者',
            'subtitle' => '生成并创建您自己的自定义Minecraft盔甲架。创建不同的姿势、位置、放置项目等等。',
        ],
        'meta' => [
            'title' => 'Minecraft盔甲架创作者',
            'description' => '轻松生成和创建自定义的Minecraft盔甲架。编辑器可以帮助您制作不同的姿势、位置、放置项目、自定义皮肤等等。',
        ],
    ],
    'banner' => [
        'editor' => [
            'header' => [
                'title' => 'Minecraft 旗帜编辑器',
                'subtitle' => '设计和创建您自己的自定义Minecraft旗帜。这些可以用来装饰你的世界，也可以被视为<a href="https://optifine.net" target="_blank" rel="nofollow">可选</a>皮肤。',
            ],
            'meta' => [
                'title' => 'Minecraft 旗帜创作者',
                'description' => '使用游戏中的所有图案和颜色创建和设计您自己的自定义Minecraft 旗帜设计！这些可以用来装饰你的世界，也可以用旗帜披风作为可选披风穿着。你可以生成旗帜或盾牌的代码。',
            ],
        ],
        'gallery' => [
            'header' => [
                'title' => 'Minecraft 旗帜画廊',
                'subtitle' => '浏览 :count 个自定义设计的Minecraft旗帜。你可以用旗帜作为斗篷，让你的Minecraft皮肤更加独特，或者用旗帜作为彩旗来装饰你的世界。',
            ],
            'meta' => [
                'title' => 'Minecraft 旗帜画廊',
                'description' => '浏览 :count 个自定义设计的Minecraft旗帜。你可以用旗帜作为斗篷，让你的Minecraft皮肤更加独特，或者用旗帜作为彩旗来装饰你的世界。',
            ],
        ],
    ],
    'search' => [
        'meta' => [
            'title' => '搜索结果：:search',
        ],
        'title' => '搜索结果',
        'results' => '第:current页，共:count页结果|第:current页，共约:count个结果 ',
        'time' => '(:time 秒)',
        'username_available' => '用户名可用*',
        'username_unavailable' => '用户名不可用',
        'username_status' => '状态',
        'username_status_available' => '有效的*',
        'username_status_unavailable' => '无效的',
        'username_searches' => '搜索',
        'username_searches_count' => ':count/天',
        'username_available_disclaimer' => '*除非该名称被Mojang暂时或永久禁止。',
        'no_results' => '未找到个人资料。尝试通过更改搜索类型使用UUID进行搜索。',
        'no_results_tags' => '找不到标签的皮肤。试着搜索其他标签，如“蓝色”、“女孩”、“fox”等...',
        'again' => '重新搜索',
        'sorry' => '啊哦，实在抱歉~~',
        'view_profile' => '查看个人资料',
    ],
    'collection' => [
        'title' => 'Minecraft皮肤收藏',
        'subtitle' => '浏览我们管理过的Minecraft皮肤收藏。',
        'filters' => '筛选',
        'title_trending' => '热门',
        'title_all' => '所有Minecraft皮肤',
        'skin_tags' => '标记的皮肤',
        'filters_skin_type' => '皮肤类型',
        'filter_skin_type_steve' => 'Steve类型',
        'filter_skin_type_alex' => 'Alex类型',
        'cancel' => '取消',
        'apply' => '应用',
        'username_minecraft_skin' => ':username的Minecraft 皮肤',
        'user_downloads' => '<span class="fw-500">:downloads</span> 下载 |<span class="fw-500">:downloads</span> 下载',
    ],
    'favourites' => [
        'title' => '收藏夹',
        'subtitle' => '查看和管理您保存到您的收藏夹中的皮肤和服务器',
        'sort' => '排序方式',
        'toast' => [
            'added' => '已添加到您的收藏列表',
            'removed' => '已从您的收藏列表中移除',
        ],
        'skins' => [
            'button' => '皮肤',
            'empty_headline' => '还没有收藏皮肤',
            'empty_subtitle' => '您还没有保存任何皮肤到您的收藏夹。访问服务器页面并发现您的下一个收藏！',
            'empty_browse' => '浏览皮肤',
            'meta' => [
                'title' => '我收藏的皮肤',
                'description' => '我已经收藏的皮肤',
            ],
        ],
        'servers' => [
            'button' => '服务器',
            'empty_headline' => '还没有收藏服务器',
            'empty_subtitle' => '您还没有保存任何服务器到您的收藏夹。访问服务器页面并发现您的下一个收藏！',
            'empty_browse' => '浏览服务器',
            'meta' => [
                'title' => '我最喜欢的服务器',
                'description' => '我最喜欢的Minecraft服务器',
            ],
        ],

    ],
    'cape' => [
        'editor' => [
            'title' => 'Minecraft披风编辑器',
            'subtitle' => '使用Minecraft披风编辑器来创建你自己的自定义披风。',
            'meta' => [
                'title' => 'Minecraft披风编辑器',
                'description' => '使用Minecraft披风编辑器来创建你自己的自定义披风。',
            ],
        ],
        'list' => [
            'title' => 'Minecraft披风',
            'subtitle' => 'Minecraft官方斗篷。斗篷是一种纪念物品，除了作为玩家的皮肤外，还可以佩戴。当戴上鞘翅时，它们也可以改变外观。',
            'meta' => [
                'title' => 'Minecraft披风列表',
                'description' => 'Minecraft披风列表：查看所有官方Minecraft披风，包括Mojang、Minecon、Personal、Special和虚荣披风',
            ],
        ],
        'detail' => [
            'title' => ':cape 披风',
            'info' => '披风信息',
            'profile_list' => '带有此斗篷的配置文件',
            'profiles' => ':profiles 个人资料|:profiles 个人资料',
            'meta' => [
                'title' => ':cape Minecraft披风',
                'description' => '查看 :cape Minecraft披风并看看玩家穿着它！',
            ],
        ],
        'list-custom' => [
            'title' => '自定义Minecraft披风',
            'description' => '浏览和查看已经创建并被SkinMC 成员使用的自定义披风。',
        ],
    ],
    'servers' => [
        'title' => 'Minecraft服务器',
        'subtitle' => '浏览并探索Minecraft服务器',
        'all' => '所有服务器',
        'manage_your_servers' => '管理您的服务器',
        'add_new_server' => '添加新的服务器',
        'filters' => [
            'trending' => '热门',
            'updated' => '已更新',
            'new' => '最新的',
            'most_viewed' => '访问最多',
            'top_voted' => '最高点赞',
            'sorting' => '排序中',
            'sort_by_latest' => '按照最新排序',
            'sort_by_oldest' => '按最老的排序',
            'categories' => '类别',
            'server_location' => '服务器地址',
            'show_results' => '显示结果',
            'show_more' => '显示更多',
            'show_less' => '收起',
            'clear_filters' => '清空筛选',
            'reviews' => '评论',
            'sort_by_highest_rating' => '按最高评分排序',
            'sort_by_lowest_rating' => '按最低评分排序',
            'bedrock_and_java_support' => '基岩 和 Java 支持',
        ],
        'review-count' => ':count 评论 |:count 评论',
        'meta' => [
            'title' => 'Minecraft服务器列表',
            'description' => '浏览并探索Minecraft服务器列表以找到最好的 Minecraft 服务器！筛选最晚、最受欢迎和更多的类型',
        ],
        'reviews' => [
            'meta' => [
                'title' => '写一个评论',
            ],
            'editing' => '您正在从 :date编辑您的评论。您想要删除您的评论吗？',
            'welcome' => 'Hi :username. 您在 :servername 上的总体体验如何？',
            'subtitle' => '根据你的印象对服务器打个分吧！',
            'scale' => [
                'great' => '优',
                'good' => '良',
                'okay' => '可',
                'meh' => '及',
                'bad' => '差',
            ],
            'rate-experience' => '接下来，对以下方面打个分吧！',
            'overall' => '整体',
            'server-team' => '服务器团队',
            'community' => '社区',
            'experience' => '体验',
            'availablility' => 'Uptime and availability',
            'shop' => '商店',
            'write-review-title' => '撰写评论',
            'write-review-subtitle' => '您可以写一些您喜欢的东西，或者一些特殊的体验，或者提出一些建议。',
            'write-review-helper' => '撰写服务器评论，与新玩家分享您的体验，并给予服务器拥有者一些反馈。',
            'write-review-tips' => '一些小提示',
            'submit-title' => '确定提交您的评论？',
            'submit-subtitle' => '就差一步！',
            'submit-review' => '提交评论',
            'back' => '上一步',
            'continue' => '继续',
            'delete-title' => '您确定要删除您的评论吗？',
            'tos-checkbox-part-1' => '提交此表格即表示您接受SkinMC的服务条款、隐私政策和社区指南。您还确认所有信息都是准确的，并遵循',
            'tos-checkbox-part-2' => '审评准则。',
            'tos-checkbox-part-3' => '您的评论将在提交后发布，但可能会受到审查。',
        ],
        'slots' => '栏位',
        'empty-helper' => '您可以尝试其他搜索或',
        'empty' => 'Hmm 这里仍然是空的。',
        'verified' => '已验证',
        'review_translate_show_original' => '显示原始内容',
        'review_translate' => '翻译评论',
        'description_translate' => '翻译描述信息',
        'create' => [
            'welcome' => '欢迎',
            'basics' => '基本资料',
            'categories' => '类别',
            'social_links' => '社交链接',
            'trailer_video' => '预告片视频',
            'images' => '图片',
            'images_description' => '您可以上传照片，以展示您的服务器提供的内容。',
            'submit' => '提交',
            'lets_get_your_server_added' => '让我们添加您的服务器吧。',
            'basics-subtitle' => '让人们知道你的服务器是关于什么的。',
            'description' => '描述',
            'description_tips' => '这里有一些小提示',
            'description_hint' => '为您的服务器撰写一个很好地描述来吸引新的玩家。',
            'categories-subtitle' => '为您的服务器选择某些类别',
            'missing-category' => '缺少类别？',
            'social_links_description' => '玩家在哪里可以在社交媒体上连接到你的服务器',
            'trailer_video_description' => '用YouTube视频展示您的服务器。',
            'trailer_video_hint' => '粘贴视频 URL 或 ID：',
            'ready_to_submit_your_server' => '准备好提交您的服务器了吗？',
            'review-hint' => '在提交后，团队将仔细审查您的服务器列表应用程序。然后根据决定，您的服务器将被发布，或者在运行前请求更改。',
            'terms' => [
                'part-1' => '通过提交此表格，您有权接受SkinMC的服务条款、隐私政策和社区指南。您还确认以上所有信息都是准确的，您已正确遵循。',
                'part-2' => '服务器安装要求',
                'part-3' => '，Minecraft服务器由您所代表的实体所有和管理。',
            ],
            'submit-application' => '提交申请',
            'video-id-helper' => [
                'part-1' => '视频ID是数字和字母的字符串',
                'part-2' => '例如，如果您的视频URL是',
                'part-3' => '，然后您的视频 ID 将是',
            ],
            'welcome_description' => '在这一步骤中，我们将开始添加您的服务器。 告诉我们一点有关它的信息，写一个描述，下一步你可以上传一些图像。',
        ],
        'copy_server_ip' => '复制服务器IP',
        'all_minecraft_servers' => '所有Minecraft服务器',
        'promo' => [
            'title' => '您是Minecraft服务器的服主吗？',
            'ready_to_list_your_server' => '准备好列出您的服务器吗？',
            'everything_you_need' => '发展服务器所需的一切',
            'list_your_server' => '列出您的服务器',
            'list_your_server_description' => '为您的服务器创建一个列表、添加照片、社交媒体等等。',
            'find_players' => '查找玩家',
            'find_players_description' => '寻找和接触新玩家以加入您的服务器并扩大您的社团。',
            'get_reviews' => '获得评论',
            'get_reviews_description' => '请您的社团查看您的服务器，并在游戏中奖励他们。',
            'why_list_on_skinmc' => '为什么你应该在SkinMC上列出你的服务器',
            'others' => '其它',
            'quality_check_and_confirmation' => '质量检查与确认',
            'quality_check_description' => '我们的团队审查每个服务器以确保质量。',
            'verified_players' => '已验证的Minecraft玩家的评论',
            'verified_players_description' => '从 Votifier 整合的合法账户中收集真实玩家的评论。',
            'international' => '多语言环境',
            'international_description' => '通过翻译功能，您的列表可供更多玩家使用。',
            'server_listing_page' => '强大的服务器列表页面',
            'server_listing_page_description' => '添加照片，描述文本，YouTube视频，并突出显示玩家加入您的服务器的理由。',
            'social_connections' => '社交媒体连接',
            'social_connections_description' => '连接您的服务器社交账户，显示新的玩家可以找到您。',
            'verified_badge' => '验证徽章',
            'verified_badge_description' => '验证服务器可以申请验证徽章。',
            'owner_profile' => '所有者个人资料',
            'owner_profile_description' => '通过自定义您的个人资料，增加个人魅力。',
            'categories' => '类别',
            'categories_description' => '不同的类别将更容易找到您的服务器。',
            'vote' => '投票',
            'vote_description' => '请用户为您的服务器投票。',
            'fair_listings' => '公平列表',
            'fair_listings_description' => 'Server listings can not be artificially boosted in results on SkinMC.',
            'support' => '24小时支持',
            'support_description' => '您需要帮助吗？还是有一些疑问？您可以随时联系，我们会尽快回复。',
            'custom_features' => 'Custom features',
            'custom_features_description' => 'Missing a feature for your server? Open a ticket, and we\'ll implement it.',
            'faq' => [
                'title' => '常见问题',
                'suited-question' => '我的Minecraft服务器是否适合SkinMC？',
                'suited-answer' => 'SkinMC上的Minecraft体玩家热衷于探索新的验、内容和社区交流。 在这个平台上，您会找到各种不同的、独特的、有趣的Minecraft服务器。 不管是一个庞大的服务器，或是一个小的生存服务器，都有其独特的乐趣！',
                'get-started-question' => '我该如何使用？',
                'get-started-answer' => '将您的Minecraft服务器添加到SkinMC 服务器列表非常简单！您将首先需要创建一个SkinMC帐户（如果您尚未创建的话），然后按照设置指南提交您的服务器。 添加几张照片和一些精彩的描述，您的服务器将立即发布！',
                'players-question' => '如何为我的Minecraft服务器吸引更多玩家？',
                'players-answer' => 'Building a community is the most crucial part of a long lasting Minecraft Server. Use the Minecraft Server List on SkinMC to find a new audience and continue to build your community. Ask your players to recommend your Server, or share your listing on social media platforms. Collecting good reviews can also play an important role to a great Server listing presence that attracts new players.',
                'more-question' => '我还有一些问题，我可以从哪里得到解答？',
                'more-answer' => '您可以随时点击帮助按钮，与SkinMC联系， 或加入我们的Discord服务器。',
            ],
            'ready_to_list_description' => '只需几分钟即可将您的Minecraft服务器添加到SkinMC服务器列表。 如果您需要帮助，您可以随时随地联系我们，我们会尽快回复。',
        ],
        'manage' => [
            'index' => [
                'welcome' => '欢迎回来，:username',
                'your_servers' => '您的服务器',
                'reviews_today' => '今日评论',
                'no_reviews_today' => '今天没有评论',
                'no_reviews_text' => '您的服务器今天没有收到任何评论。试着让您的玩家撰写一些？',
                'tips' => [
                    'title' => '小提示',
                    'description-title' => '写一个好的服务器描述',
                    'description-body' => '写一个精美的服务器描述的一些提示和建议',
                    'images-title' => '添加一些服务器图片',
                    'images-body' => '用精美的图片装饰你的服务器页面',
                ],
            ],
            'listings' => [
                'title' => '您的 Minecraft 服务器 (:count)',
            ],
            'insights' => [
                'title' => '数据分析',
            ],
            'edit_server' => '编辑服务器',
            'listing' => '列表',
            'to_do' => '待办',
            'last_update' => '最后更新',
            'add_more_photos_to_publish' => '添加更多照片到发布',
            'looks_empty_here' => '这里看起来是空的。',
            'get_started_by_adding_a_new_server' => '从添加新服务器开始吗？',
        ],
        'status' => [
            'approved' => '已审批',
            'pending_approval' => '等待审批',
            'published' => '已发布',
            'in_review' => '审核中',
        ],
    ],
    'editor' => [
        'import' => [
            'title' => '导入皮肤',
            'import_by_username' => '通过用户名导入',
            'import_button' => '导入',
            'drag' => '拖放皮肤到此处，或点击',
            'click' => '选择图片',
        ],
        'download' => [
            'error' => [
                'no-data' => 'No skin data was provided. Please try again.',
                'invalid-format' => 'The skin data format is invalid. Please try again.',
                'invalid-data' => 'The skin data is corrupted. Please try again.',
                'generic' => 'Something went wrong while downloading your skin. Please try again.',
            ],
        ],
        'draw' => '画笔',
        'eyedropper' => '吸管工具',
        'fill' => '填充',
        'move' => '移动',
        'decrease_brightness' => '降低亮度',
        'increase_brightness' => '增加亮度',
        'erase' => '橡皮擦',
        'undo' => '后退(CTRL+Z)',
        'redo' => '前进(CTRL+Y)',
        'default_view' => '默认视图',
        'zoom_in' => '放大(CTRL +)',
        'zoom_out' => '缩小 (CTRL -)',
        'saved' => '刚刚保存最后一个',
        'saving' => '自动保存中...',
        'save_error' => '出现了错误。',
        'new_skin' => '新建皮肤',
        'previous_skins' => '上一个皮肤',
        'backed_up_title' => '自动保存的皮肤',
        'backed_up_info' => '临时备份到您的本地存储。',
        'backed_up_empty_title' => '这里是空的',
        'backed_up_empty_info' => '一旦你开始编辑皮肤，你会在这里看到你最后编辑的32个皮肤。',
        'backed_up_skins_count' => '32个皮肤备份已使用',
        'backed_up_skins_count_info' => '你可以备份多达32个皮肤。一旦你达到32个皮肤，旧皮肤将被新皮肤替换。',
        'layers' => '图层',
        'body' => [
            'title' => '身体',
            'overlay' => '皮肤外层',
            'head' => '头部',
            'torso' => '躯干',
            'l_arm' => '左臂',
            'r_arm' => '右臂',
            'l_leg' => '左腿',
            'r_leg' => '右腿',
        ],
        'model' => '模型',
        'steve' => 'Steve',
        'alex' => 'Alex',
        'stance' => [
            'title' => '动作',
            'default' => '默认',
            'walk' => '走',
            'run' => '跑',
            'hug' => 'T型',
            'fly' => '飞',
        ],
        'fullscreen' => '全屏模式',
        'fullscreen_exit' => '退出全屏',
        'grid' => '网格',
        'show_grid' => '显示网格',
        'download' => [
            'title' => '保存并下载',
            'subtitle' => 'SkinMC 账户',
            'description' => '您想要创建一个免费的 SkinMC 账户来将您的皮肤和未来的皮肤保存到云端吗？',
            'start_description' => '不保存到云端，直接开始下载',
            'start' => '下载皮肤',
        ],
        'help' => [
            'title' => 'Minecraft皮肤编辑器',
            'about' => '轻松地使用自定义Minecraft皮肤编辑器创建和编辑您的皮肤。 您可以在Steve和Alex模型之间进行选择，从文件或用户名导入皮肤，并创建自己的 Minecraft 皮肤。',
            'draw' => '使用钢笔工具绘制。从样例中选择要与之一起使用的颜色。',
            'eyedropper' => '使用滴管从皮肤中选择一种颜色，并将其添加到当前调色板中。',
            'fill' => '使用填充工具填充整个皮肤区域。在使用填充之前选择一种颜色。',
            'move' => '使用移动工具在皮肤编辑器画布上平移和移动。',
            'decrease_brightness' => '降低当前激活颜色的亮度。',
            'increase_brightness' => '增加当前激活颜色的亮度。',
            'erase' => '擦除在辅助覆盖层上绘制的像素。',
            'minimap' => 'Minimap',
            'minimap_info' => 'The minimap can show you the skin texture in a flat view while in 3D mode. In 2D mode the minimap switches to a 3D preview of your skin. You can zoom in and out.',
            'autosave' => 'Autosave',
            'autosave_info' => 'The autosave feature saves your skin automatically every 30 seconds. You can access the autosaved skins in the editor by pressing the folder icon, and choosing "Previous skins".',
            '2d_editor' => '2D and 3D editor',
            '2d_editor_info' => 'Toggle between editing your Minecraft skin in 2D or 3D mode.',
        ],
    ],
    'account' => [
        'level' => '等级',
        'level_history' => '等级历史记录',
        'xp' => 'XP',
        'my_xp' => '我的XP',
        'xp_to_next_level' => ':xp XP 到下一等级',
        'xp_info' => '什么是 XP？',
        'xp_info_tooltip' => 'XP是通过各种活动获得的，比如为皮肤添加标签、邀请朋友、评论等等。每获得XP，您就可以升级并解锁酷炫的东西！',
        'settings' => [
            'title' => '账户',
            'show_profile' => '前往个人资料',
            'friends' => '好友',
            'friends_detail' => '使用 SkinMC 上的好友列表保持连接。',
            'security' => '帐号安全',
            'security_detail' => '修改您的登录密码并保证您的帐户安全',
            'social' => '社交媒体帐户',
            'social_detail' => '通过添加您的社交媒体来自定义您的个人资料',
            'link' => '链接Minecraft帐户',
            'link_detail' => '链接您的Minecraft账户并获取您的个人资料。',
            'logout' => '您想要退出登录吗？',
            'automatic_backups' => '自动备份皮肤',
            'automatic_backups_info' => '作为 SkinMC puls 会员，您的皮肤每天都会备份。',
        ],
        'capes' => [
            'title' => 'SkinMC Minecraft 披风',
            'description' => '使用SkinMC Capes穿戴你想要在游戏中显示的披风，此功能是免费的',
            'drop' => '拖放披风图片到这里',
            'drop-hint' => '尺寸仅限 64x32px',
            'select' => '选择图片',
            'upload-cape' => '上传并使用披风',
            'save-and-use' => '保存并使用',
            'uploaded-cape' => '已上传的披风',
            'no-cape' => '无披风',
            'remove-cape' => '移除披风',
            'download' => '下载 SkinMC Mod 以查看您和其他玩家在游戏中的披风。',
            'learn-more' => '了解更多',
            'link-account' => '要上传斗篷，请先链接您的 Minecraft 帐户。',
            'updated' => '您的披风已更新！',
            'removed' => '您的披风已被移除。',
            'active' => '你的披风已激活！',
        ],
        'favourite' => '收藏',
        'remove_favourite' => '取消收藏',
        'added_to_favourites' => '已添加到收藏列表',
        'removed_from_favourites' => '从收藏夹中移除',
        'welcome' => 'Nice to see you!',
        'view-profile' => '查看我的个人资料',
        'security' => [
            'title' => '帐号安全',
            'email' => '电子邮件地址',
            'email-title' => '更新您的电子邮件地址。',
            'save' => '保存',
            'password' => '密码',
            'password-title' => '随时更改您的密码。',
            'social-provider' => 'To update your account information, such as your password, please visit your login provider:',
            'social-provider-email' => 'Your associated email address with your login provider',
            'social-provider-connected' => '当前已链接的其他账号',
            'current-password' => '旧密码',
            'forgot' => '忘记密码？',
            'edit' => '编辑',
            'delete' => '删除我的账户',
            'account-deletion' => '删除您的 SkinMC 帐户。',
            'delete-info' => '请再次确认以继续',
            'delete-confirmation' => '删除帐户是不可逆的。您的所有个人信息和内容，例如帖子、收藏夹、上传的披风、自定义信息等等，都将被删除，无法恢复。',
            'delete-confirmation-info' => '输入您的密码以继续',
            'yes-confirm-delete' => '是的，确认删除',
            'account-successfully-deleted' => '您的帐户和数据已经成功删除。',
        ],
        'social' => [
            'title' => '社交媒体帐户',
            'edit' => '修改',
            'save' => '保存',
            'link-account' => '将您的 Minecraft 账户链接到SkinMC 以在您的个人资料上显示您的社交链接。',
            'finish-setup' => '完成设置',
            'connect-account' => '绑定你的账号',
            'connect-description' => 'Choose which accounts you wish to connect and unlock special SkinMC integrations.',
            'empty' => '未添加账户',
            'empty-description' => '您的社交媒体账户将显示在这里和您的公开个人资料中。 一旦添加，他们将添加更多的个性化到您的页面，并启用集成。',
            'connect' => '连接',
            'username' => 'username',
            'spotify' => '添加您的 Spotify 用户名来显示您的 Spotify 信息到您的个人资料中。',
            'discord' => '输入您的 Discord 用户名和号码以在您的 SkinMC 配置文件中显示您的 Discord 信息。',
            'youtube' => '添加您的 YouTube 频道到 SkinMC ，这将在您的个人资料中显示您的 YouTube 频道。',
            'youtube-format' => 'Use the following format depending on your channel link:',
            'twitter' => 'Enter your X (formerly Twitter) username to display it on your profile.',
            'bluesky' => 'Enter your Bluesky handle e.g. username.bsky.social to display your Bluesky profile on your profile.',
            'twitch' => '输入您的Twitch用户名以在您的个人资料上显示您的Twitch频道。',
            'reddit' => '输入您的Reddit用户名以在您的个人资料上显示您的Reddit信息。',
            'github' => '输入您的GitHub用户名以在您的个人资料上显示您的GitHub信息。',
            'telegram' => '输入您的Telegram用户名以在您的个人资料上显示您的Telegram信息。',
            'tiktok' => '输入您的TikTok用户名以在您的个人资料上显示您的TikTok信息。',
            'snapchat' => '输入您的Snapchat用户名以在您的个人资料上显示您的Snapchat信息。',
            'instagram' => '输入您的Instagram用户名以在您的个人资料上显示您的Instagram信息。',
            'facebook' => '输入您的Facebook用户名以在您的个人资料上显示您的Facebook信息。',
            'includes_skinmc_plus_benefits' => 'Includes SkinMC plus benefits',
        ],
        'recover' => [
            'title' => 'Recover your account',
            'subtitle' => 'Please enter your new password and confirm it to finish recovering your account.',
            'new_password' => 'New password',
            'repeat_new_password' => 'Repeat new password',
            'submit' => 'Recover account',
        ],
        'customise' => [
            'title' => '自定义你的个人资料',
            'description' => 'Add your social media, choose an emoji, set your location and more',
            'information' => 'Information',
            'preview' => 'Preview',
            'location' => [
                'title' => 'Location',
                'description' => '选择您想要添加到您的个人资料的位置。',
            ],
            'biography' => [
                'title' => 'About me',
                'description' => '为您的个人资料写一个自传。',
            ],
            'status' => 'Status',
            'status-toggle' => 'Show my online status',
            'emoji' => 'Emoji',
            'name-history-toggle' => 'Make username history private',
            'name-history-info' => 'Your Minecraft username history is currently',
            'name-history-toggle-on' => 'private',
            'name-history-toggle-off' => 'public',
            'theme' => '个人资料主题',
            'theme-primary' => 'Primary',
            'theme-secondary' => 'Secondary',
            'appearance' => 'Appearance',
        ],
        'link' => [
            'manage' => 'Manage linked Minecraft account',
            'description' => 'See and manage your linked Minecraft account',
            'title' => 'Linked Minecraft account',
            'current' => 'Currently linked Minecraft account.',
            'status' => 'You now have full access to all SkinMC features!',
            'linked' => 'Linked',
            'disconnect' => 'Disconnect',
            'disconnect-title' => 'Disconnect Minecraft account',
            'disconnect-info' => 'Are you sure you would like to disconnect your Minecraft account?',
            'disconnect-features' => 'You will lose access to commenting, customisation and other features which require a linked Minecraft account. To use these again you will be required to link a Minecraft account.',
            'disconnect-following' => '断开您的 Minecraft 账户将永久移除您关注的所有个人资料。',
            'disconnect-posts' => 'Your created feed posts and liked will be deleted.',
            'can-not-undo' => 'This can\'t be undone.',
            'are-you-sure' => 'Are you sure?',
            'confirm' => 'Yes, confirm disconnect',
            'cancel' => 'No, cancel',
            'success' => 'Your account was successfully disconnected!',
        ],
        'finish-setup' => [
            'title' => 'Finish account setup',
            'description' => 'Finish setting up your account, and get full access to all features by linking your Minecraft account to SkinMC.',
            'link' => 'Link Minecraft account',
            'get-started' => 'Get started',
            'skip' => 'Skip',
            'claim' => '确认您的个人资料',
            'customise' => 'Customise your page',
            'social' => 'Add social links',
            'comment' => 'Access to comment system',
            'direct_message' => 'Send direct messages',
            'feed' => 'Post status updates to the feed',
            'follow' => 'Follow your friends',
            'badge' => '您的个人资料上显示的徽章',
            'cape' => 'Custom Minecraft cape',
            'backup' => 'Automatic skin backup',
            'more' => 'And more...',
        ],
        'skins' => [
            'title' => 'Manage skins',
            'toggle' => 'Skin visibility toggled',
        ],
        'invite' => [
            'title' => 'My invites',
            'headline' => 'Invite your friends',
            'info' => 'Create an invite code to share with your friend. Once they accept it, you\'ll both earn some extra XP!',
            'description' => 'Create an invite for your friends and you\'ll both earn some extra XP.',
            'generate' => 'Create invite code',
            'empty' => 'You haven\'t created any invites yet.',
            'code' => 'Code',
            'expiry' => 'Each code works once.',
            'status' => [
                'title' => 'Status',
                'pending' => 'Pending',
                'accepted' => 'Accepted',
            ],
            'add_invite' => [
                'button' => 'Have an invite?',
                'title' => 'Add an invite code',
                'redeem' => 'Redeem invite',
            ],
            'share' => 'Send your friend an invite link',
        ],
        'emoji' => [
            'title' => 'SkinMC Emoji',
            'introducing' => 'Introducing',
            'info' => '使用Emoji自定义您的个人资料。当您升级时解锁更多。',
            'unlocked_at' => 'Unlocked at level :level',
            'unlocks_at' => 'Reach level :level to unlock',
            'turn_off' => 'Show emoji',
        ],
    ],
    'notifications' => [
        'title' => 'Notifications',
        'view_all' => 'View all',
        'view_all_notifications' => 'View all notifications',
        'image' => 'Notification photo',
        'archived' => 'Archived',
        'inbox' => 'Inbox',
        'empty' => [
            'title' => 'You\'re up to date!',
            'text' => 'New notifications will show up here.',
            'text-archived' => 'Archived notifications will show up here.',
        ],
        'action' => [
            'archive' => 'Move to archive',
            'unarchive' => 'Unarchive',
            'open' => 'Tap to open',
        ],
        'toast' => [
            'archive' => 'Notification moved to archive',
            'unarchive' => 'Notification moved to inbox',
            'undo' => 'Undo',
        ],
    ],
    'error' => [
        'offline' => [
            'title' => 'No internet',
            'subtitle' => 'Your internet was disconnected. Please check your connection and reload the page to try again.',
            'try_again' => 'Try again',
        ],
        '404' => [
            'title' => '404 — Page not found.',
            'subtitle' => 'Hm, it looks like nothing was found at this location. Maybe try going back, or start a new search?',
            'try_again' => 'Back home',
        ],
    ],
    'heads' => [
        'list' => [
            'meta' => [
                'title' => 'Minecraft heads database',
                'description' => 'Explore the database of Minecraft heads to decorate your world with, or generate your own give command. View official heads, player heads and custom heads that feature textures which never change.',
            ],
            'header' => [
                'title' => 'Minecraft heads',
                'subtitle' => 'Explore our database of Minecraft heads to decorate your world, or generate your own give command. Player heads show the current skin worn by a user, and can change as the user updates their skin. Custom heads are linked to the Mojang skin file and never change. Custom heads must be summoned using a command block as the command is very long.',
            ],
            'count' => [
                'heads' => ':heads head|:heads heads',
            ],
            'customheads' => [
                'title' => 'Custom heads',
                'description' => 'Custom heads use the direct path to the texture file on the Mojang servers. Hence textures will never be deleted and the heads never change.',
                'version' => 'Minecraft 1.8 or later',
            ],
            'playerheads' => [
                'title' => 'Player heads',
                'description' => 'Player heads use the current skin texture of a Minecraft player. As they are username based, when the player changes their name or skin, the head changes.',
                'version' => 'All Minecraft versions',
            ],
        ],
    ],
    'mod' => [
        'title' => 'SkinMC Mod: Free custom capes',
        'headline' => 'Introducing the SkinMC Mod for more customisation',
        'description' => 'Giving back to the Minecraft community, with a free mod which enables players more customisation with custom capes, available and visible for anyone using the mod.',
        'download' => 'Download now',
        'download-title' => 'Download the mod',
        'requires' => 'Requires',
        'select-version' => 'Choose your Minecraft version',
        'get-started' => 'Getting started is simple',
        'step-1' => '1. Get the mod',
        'step-1-detail' => 'Install Fabric, then download the mod for your game version and install it by putting the jar in your mods folder.',
        'step-2' => '2. Link your account',
        'step-2-detail' => 'If you haven\'t already, sign up/in and connect your Minecraft account to SkinMC.',
        'step-3' => '3. Upload your cape',
        'step-3-detail' => 'Go to your account and upload your custom cape. It will be visible in-game.',
        'all-versions' => 'All versions',
        'latest' => 'Latest',
        'logged-in' => 'Upload your cape',
        'mirror' => 'Mirror',
        'download-via' => 'Download via:',
        'curseforge' => 'CurseForge',
    ],
    'app' => [
        'title' => 'SkinMC Android App',
        'headline' => 'Say hello to the SkinMC Android App.',
        'play-store-attribution' => 'Google Play and the Google Play logo are trademarks of Google LLC.',
        'features' => 'Convenient features for on the go',
        'feature-qr' => 'Built in QR-Code scanner',
        'feature-qr-detail' => '使用二维码扫描器内置的功能来轻松地从桌面获取皮肤到应用程序，或扫描您朋友自定义个人资料的二维码。',
        'feature-files' => 'Saves directly to files',
        'feature-files-detail' => 'With the usage of Android Files Manager, the app can conveniently save Skins, making it easier to apply in Bedrock Edition.',
        'feature-noads' => 'No ads',
        'feature-noads-detail' => 'A clean designed interface, without distractions. Enjoy an Ad-free experience without intrusive annoyances from web to app.',
        'feature-experience' => 'Experience',
        'feature-experience-detail' => '随时随地享受完整的 SkinMC 体验，添加功能。自定义您的个人资料，添加您的个人资料，创建一个有趣的二维码和更多！',
        'get-app-headline' => 'Get the SkinMC App',
        'get-app-detail' => 'Your very own Minecraft companion for your Android — available for free.',
    ],
    'random' => [
        'title' => 'Loading random Minecraft skin',
        'description' => 'Loading random Minecraft skin',
        'headline' => 'Please wait...',
        'redirect' => 'You will be automatically redirected. Page not loading?',
        'click-here' => 'Click here',
        'messages' => [
            '1' => 'Loading random Minecraft skin...',
            '2' => 'Digging down...',
            '3' => 'Creeper, aw man...',
            '4' => 'Searching through chests...',
            '5' => 'Did you know the coming skin is completely random?',
            '6' => 'Random skin incoming...',
            '7' => 'One more block...',
            '8' => 'Sorting inventory...',
            '9' => 'Crafting diamond pickaxe...',
            '10' => 'Looking for Herobrine...',
        ],
    ],
    'feed' => [
        'title' => 'Feed',
        'following' => 'Following',
        'sign-up' => 'Sign up or log in to join the conversation.',
        'link-account' => 'Link your Minecraft account to join the conversation.',
        'placeholder' => 'What is happening?',
        'audience' => 'Audience',
        'audience-title' => 'Who can see this?',
        'everyone' => 'Everyone',
        'everyone-info' => 'Anyone on or off SkinMC.',
        'followers' => 'Followers',
        'followers-info' => 'Signed in or members following me.',
        'private' => 'Only me',
        'private-info' => 'Private post only I can see.',
        'submit' => 'Post',
        'like' => 'Like',
        'comment' => 'Reply',
        'share' => 'Share',
        'remaining' => 'Remaining',
        'profile' => 'Posts by :username',
        'posts' => 'All posts',
        'my-posts' => 'My posts',
        'view-all' => 'View all posts',
        'post' => [
            'meta' => ':username on SkinMC: :text',
            'title' => 'Post',
            'created' => 'Status update posted!',
            'confirm-delete' => 'Are you sure you would like to delete this post? It can not be undone.',
            'delete' => 'Delete post',
            'deleted' => 'Your post was deleted.',
        ],
        'repost' => [
            'button' => 'Repost',
            'quote_button' => 'Quote',
            'title' => 'Repost this post',
            'quote_title' => 'Quote post',
            'quote_label' => 'Add a comment (optional)',
            'quote_placeholder' => 'Add your thoughts...',
            'reposted' => 'reposted',
            'success' => 'Reposted!',
            'removed' => 'Repost removed.',
            'already_reposted' => 'You have already reposted this.',
            'undo' => 'Undo repost',
            'original_deleted' => 'The original post has been deleted.',
            'deleted_post' => 'This post has been deleted',
        ],
        'hashtags' => [
            'title' => 'Trending',
            'trending-now' => 'Trending now',
            'post' => 'post',
            'posts' => 'posts',
            'hashtag' => 'Hashtag',
            'hashtags' => 'Hashtags',
            'no-results' => 'No hashtags found',
        ],
        'search' => [
            'title' => 'Search',
            'placeholder' => 'Search posts, hashtags...',
            'no-results' => 'No results found',
            'posts' => 'Posts',
            'no-hashtags-found' => 'No hashtags found matching ":query"',
            'no-results-found' => 'No results found for ":query"',
        ],
        'poll' => [
            'title' => 'Poll',
            'create' => 'Create a poll',
            'option' => 'Option',
            'add_option' => 'Add option',
            'duration' => 'Duration',
            'duration_1' => '1 day',
            'duration_3' => '3 days',
            'duration_7' => '7 days',
            'votes' => '{0} votes|{1} vote|[2,*] votes',
            'ended' => 'Poll ended',
            'ends_in' => 'Ends :time',
            'login_required' => 'Sign in to vote',
        ],
        'gif' => [
            'title' => 'GIF',
            'search_placeholder' => 'Search KLIPY for GIFs...',
            'no_results' => 'No GIFs found',
            'powered_by' => 'Powered by',
            'categories' => 'Categories',
            'trending' => 'Trending',
        ],
        'media' => 'Media',
        'follow-suggestions' => 'Follow the team',
        'explore' => 'Explore',
        'hashtag' => 'Hashtag',
        'no_users' => 'No users found.',
        'stories' => [
            'archive' => [
                'title' => 'Story Archive',
                'subtitle' => 'Your archived stories are only visible to you',
                'empty' => 'No archived stories yet',
                'empty-description' => 'Stories you post will appear here after 24 hours.',
                'action' => 'Archive',
                'archived' => 'Story moved to archive.',
                'already-archived' => 'Story is already archived.',
            ],
        ],
    ],
    'private' => [
        'title' => 'Private posts',
        'text' => 'This post is private.',
    ],
    'liked' => [
        'title' => 'Liked',
    ],
    'following' => [
        'title' => 'Following',
        'text' => 'Sign in to view this post.',
    ],
    'tags' => [
        'empty' => 'No tags to vote on yet',
        'empty-subtitle' => 'Be the first to add one',
    ],
    'inbox' => [
        'title' => 'Messages',
        'details' => 'Details',
        'message_user' => 'Message',
        'write_message' => 'Write a message',
        'empty' => [
            'no_message_selected' => 'No message selected',
            'open_or_start_conversation' => 'Open a conversation from the message list, or start a new one.',
            'no_messages' => 'No unread messages',
            'start_conversation' => 'Once you start a new conversation, your messages will be displayed here.',
            'conversation' => 'This is the beginning of your conversation with :username.',
            'users' => 'Unable to find any users that match the current query.',
        ],
        'typing' => ':username is typing...',
        'new_message' => 'New message',
        'mark_unread' => 'Mark unread',
        'send_message' => 'Send message',
        'delete_message' => 'Delete message for you',
        'latest_conversations' => 'Latest conversations',
        'delete_conversation' => 'Delete conversation',
        'show_details' => 'Show details',
        'hide_details' => 'Hide details',
        'unread' => 'Unread',
        'deleted' => 'Deleted',
        'report_message' => 'Report message',
        'add_reaction' => 'Add reaction',
        'today' => 'Today',
        'reconnect' => 'Please reconnect your Minecraft account to chat',
        'account_disconnected' => 'This user disconnected their linked Minecraft account.',
        'saved_messages' => 'Saved messages',
        'new_message_to_label' => 'To',
        'external-link-to' => 'This link will take you to',
        'external-link-confirmation' => 'Are you sure you want to go there?',
        'external-link' => 'External link',
        'reply' => 'Reply',
    ],
    'server' => [
        'manage' => [
            'stats' => 'Stats',
        ],
    ],
    'report' => [
        'button' => 'Report',
        'title' => 'Report content',
        'describe' => 'Briefly describe why you are reporting this',
        'select' => 'Select report reason',
        'submit' => 'Submit report',
        'reasons' => [
            'INAPPROPRIATE_CONTENT' => 'Inappropriate content',
            'SPAM' => 'Spam',
            'HARASSMENT' => 'Harassment',
            'OTHER' => 'Other',
        ],
    ],
    'leaderboard' => [
        'title' => 'Leaderboard',
        'description' => 'View the SkinMC leaderboard of users.',
        'headline' => '前 10',
        'all-time-invites' => 'All time invites',
        'all-time-xp' => '全部时间 XP',
        '30-day-xp' => '30 天 XP',
    ],
];
