<?php

return [
    'auth' => [
        'login' => [
            'title' => '欢迎使用SkinMC ！',
        ],
        'register' => [
            'title' => '注册 SkinMC',
            'subtitle' => '开始并创建您的账户以便完全访问。',
        ],
    ],

    'home' => [
        'hero_slogan' => '你的Minecraft皮肤的地方。',
        'hero_slogan_alt_1' => 'Everything Minecraft. One place.',
        'hero_slogan_alt_2' => 'Where Minecrafters meet.',
        'hero_cta' => '给我惊喜',
        'hero_explore_cta' => '探索皮肤',
        'skin_viewer' => '皮肤查看器',
        'skin_viewer_detail' => '浏览 :count 皮肤',
        'skin_editor' => '皮肤编辑器',
        'skin_editor_detail' => '设计你自己的皮肤',
        'avatar_maker' => '头像生成器',
        'avatar_maker_detail' => '生成你自定义Minecraft头像个人资料图片。',
        'trending' => '热门',
        'minecraft_skin' => 'Minecraft皮肤',
        'favourite' => '收藏',
        'collections' => '收藏夹',
        'collections_detail' => '每次管理Minecraft皮肤',
        'creations_title' => 'Skin creations',
        'creations_description' => 'Browse and upload custom Minecraft skin creations.',
        'about_skinmc' => '关于SkinMC',
        'about_find' => '寻找任何皮肤',
        'about_find_detail' => '使用SkinMC 搜索任何Minecraft用户名来查找、查看和下载您的下一个新皮肤。',
        'about_download' => '下载或编辑',
        'about_download_detail' => '找到您喜欢的皮肤吗？将其添加到您的收藏夹中，编辑或下载并使它成为您自己的皮肤。',
        'about_platform' => '跨平台',
        'about_platform_detail' => '想把皮肤带上去吗？扫描二维码并保存您手机上的图像到Minecraft PE。',
        'meta' => [
            'title' => 'Minecraft皮肤查看器',
            'description' => '查看并下载Minecraft皮肤，发现管理收藏中最好的皮肤，检查用户名的可用性和历史记录，以及更多！',
        ],
        'recently_viewed' => '最近查看',
        'explore_title' => '尝试一些新的东西！',
        'explore' => '探索新的想法和工具',
        'servers_browse' => '浏览服务器',
        'servers' => '发现最好的 Minecraft 服务器',
        'heads' => 'Minecraft 头部',
        'head_description' => '浏览 Minecraft 头部数据库，或创建新数据库。',
        'achievement' => '成就生成器',
        'achievement_detail' => '创建您自己的自定义和个性化成就。',
        'continue' => '继续浏览',
        'totem' => 'Minecraft 图腾生成器',
        'totem_description' => '创建一个带有来自任何皮肤的不死图腾的自定义资源包。',
        'banner' => 'Minecraft 旗帜生成器',
        'banner_description' => '生成并预览自定义的Minecraft旗帜和图案。',
        'capes' => 'Minecraft 披风',
        'capes_description' => '浏览收藏量最高的披风，或创建您自己的披风。',

    ],
    'profile' => [
        'verified' => '已验证的个人资料',
        'minecraft_profile' => 'Minecraft资料',
        'show_qr_code' => '显示二维码',
        'favourite' => '收藏',
        'user_title' => ':username Minecraft皮肤',
        'user_views' => '查看 :view时间 |查看 :view时间',
        'uuid' => 'UUID',
        'copy' => '复制',
        'link' => '链接',
        'skin_history' => 'Minecraft皮肤历史 (:skins)',
        'username_history' => '历史用户名',
        'username_history_name' => '名称',
        'username_history_timestamp' => '更改于',
        'username_history_initial_name' => '初始名称',
        'user_downloads' => ':downloads 下载|:downloads 下载',
        'download_skin' => '下载皮肤',
        'apply_skin' => '应用皮肤',
        'capes' => '支出',
        'claim_profile' => '您是 :username? 认领您的个人资料以验证并定制它!',
        'claimed' => '已申领的个人资料',
        'meta_description' => '查看并下载 :username Minecraft皮肤。查看他们的 UUID，名称历史，详细统计信息和更多',
        'created_at' => '更新时间：:changed_at',
        'skins' => [
            'meta_title' => ':username Minecraft历史皮肤',
            'meta_description' => '查看 :username Minecraft 皮肤历史和先前使用过的皮肤。 使用历史记录浏览旧的或过去使用过的皮肤、备份和恢复或收集新皮肤。',
            'title' => 'Minecraft皮肤历史',
        ],
        'qr_code' => [
            'meta_title' => ':username的二维码',
            'meta_description' => ':username 自定义 Minecraft 个人资料二维码',
        ],
        'sub_nav' => [
            'skin' => '皮肤',
            'about' => '关于',
            'usernames' => '用户名',
            'head' => '头部',
            'comments' => '评论',
        ],
        'cape' => '披风',
        'elytra' => '鞘翅',
        'nametag' => '名称标签',
        'animation' => '动画',
        'rotation' => '旋转',
        'none' => '无',
        'idle' => '空闲',
        'walk' => '走',
        'run' => '跑',
        'fly' => '飞',
        'follow' => '关注',
        'following' => '已关注',
        'unfollow' => '取消关注',
        'followers' => '关注者',
        'toast' => [
            'following' => '你正在关注 :username ！',
            'follow-self-error' => '对不起:username, 你不能关注自己。',
            'unfollowed' => '你已经取消关注 :用户名',
        ],
        'edit' => '编辑个人资料',
        'joined' => '注册时间',
        'role' => '角色',
        'server-fav-list-empty' => '似乎 :username 尚未收藏任何服务器。如果 :username 收藏了服务器，您可以在这里看到。',
        'server-own-list-empty' => '似乎 :username 尚未设置拥有的服务器。如果 :username 设置了服务器，您可以在这里看到。',
        'capes-list-empty' => '似乎 :username 尚未穿戴任何披风。如果 :username 穿戴了披风，您可以在这里看到。',
        'feed-own-list-empty' => '看起来你还没有发布任何内容！如果你发布了，你可以在这里看到你的帖子。',
        'feed-list-empty' => '唔...，似乎 :username 还没有发布任何内容。如果 :username 发布了一些内容，您可以在这里看到。',
        'following-own-list-empty' => '看起来你还没有关注任何人！一旦你开始关注人，你可以在这里看到他们。',
        'following-list-empty' => '嘿，看起来 :username 好像没有关注任何人。一旦 :username 开始关注其他人，你就可以在这里看到。',
        'followers-own-list-empty' => '一旦人们开始关注您的个人资料，他们就会出现在这里。',
        'followers-list-empty' => 'Hmm，看起来没有任何人跟随 :username。 成为第一个跟随 :username的人。一旦有更多人跟随，你可以在这里看到他们。',
        'render' => '渲染器',
        '3d' => '3D 渲染',
        '2d' => '2D 渲染',
        'name-history-info' => '用户名历史记录正在消失。 Mojang已经在2022年9月13日取消了对访问名字历史API的支持，因此不再提供准确的名字历史。 如果您想要隐藏您的名称历史，请确认您的个人资料并转到设置以使其成为隐私。',
        'edit-skins' => '编辑皮肤历史记录',
        'hide-skin' => '隐藏皮肤',
        'show-skin' => '显示皮肤',
        'edit-skin' => '编辑皮肤',
        'servers' => [
            'title' => ':username 的服务器',
        ],
        'cape-list' => [
            'title' => ':username 的披风',
        ],
    ],
    'skin' => [
        'meta' => [
            'title' => ':username Minecraft皮肤',
            'description' => 'Minecraft皮肤。下载并查看皮肤，看看哪些玩家也穿着同一个皮肤。',
            'tags' => ':username Minecraft 皮肤, :username 皮肤, Minecraft 皮肤, :username 自定义 Minecraft 皮肤, 下载皮肤, 拥有相同皮肤的玩家',
        ],
        'title' => ':username Minecraft皮肤',
        'head' => '头部指令',
        'head_info' => '使用命令块',
        'first_wearing' => '首次看到玩家戴着这个皮肤：',
        'profiles' => ':profiles 个人资料|:profiles 个人资料',
        'profiles_title' => ':profiles 个人资料带有此皮肤|:profiles 个人资料带有此皮肤',
        'screenshot' => '屏幕截图',
    ],
    'skins' => [
        'meta' => [
            'title' => '页面 :current - 所有Minecraft皮肤',
            'description' => '浏览我们的 :last 页共计:total 自定义Minecraft皮肤，下载您最喜欢的下一款皮肤！',
            'tags' => ':usernameMinecraft皮肤，:username皮肤，Minecraft皮肤，:username自定义Minecraft皮肤，下载皮肤，拥有相同皮肤的玩家',
            'tags-title' => ':tag Minecraft皮肤',
            'tags-description' => '浏览我们的 :last 页共计:total :tag Minecraft皮肤，下载您最喜欢的 :tag 皮肤！',
            'tags-metatags' => ':tagMinecraft皮肤，:tag皮肤，Minecraft皮肤，:tag自定义Minecraft皮肤，下载:tag皮肤,，Minecraft:tag皮肤',
        ],
        'title-skin-tags' => '已标记的Minecraft皮肤',
        'subtitle' => '第 :current 页，共 :last 页，共计 :total Minecraft皮肤',
        'subtitle-skin-tags' => '第 :current 页，共 :last 页，共计 :total 已标记的Minecraft皮肤',
        'sort_by' => '排序方式',
        'latest' => '最新皮肤',
        'most_profiles' => '使用次数最多的皮肤',
        'profiles_today' => '今天使用次数最多的',
        'profiles_this_week' => '本周使用次数最多的',
        'profiles_this_month' => '本月使用次数最多的',
        'default' => '默认排序',
        'this_month' => '本月添加',
        'this_week' => '本周添加',
        'today' => '今日添加',
        'random' => '随机排序',
        'similar' => '相似皮肤',
        'no_similar_skins' => '尚未找到相似的皮肤。',
        'favorite' => ':count 收藏|:count 收藏夹',
    ],
    'skin-tags' => [
        'faq' => '什么是标签？',
        'about' => '标签是您添加皮肤到相关类别的一种方式。添加标签可以让您轻松地发现更多皮肤！',
        'guidelines' => [
            'good' => [
                'title' => '关于良好标签的一般准则是：',
                'short' => '短',
                'descriptive' => '说明',
                'spelled' => '正确写法',
            ],
            'bad' => [
                'title' => '请不要添加以下标签',
                'general' => '过于笼统',
                'specific' => '太特定的',
                'too-many-tags' => '应该是三个独立的标签',
                'spelling' => '应该是 :example',
            ],
        ],
        'toast' => [
            'added' => '标签 ":tag" 已添加到投票',
            'removed' => '标签 ":tag" 已被移除',
            'upvote' => '已对 ":tag" 表示赞成。',
            'downvote' => '已对 ":tag" 表示反对。',
        ],
        'vote' => [
            'up' => '赞成票',
            'down' => '反对票',
            'remove' => '删除投票',
        ],
    ],
    'contact' => [
        'contact' => '联系人',
        'email' => '如果您有任何问题，请随时在 <a href="mailto:support@skinmc.net">support@skinmc.net</a> 上向我们进行反馈。',
        'faq' => '我们恳请您先查看 <a href=":link">常见问题</a> 页面，或许您的问题将在此得到解答。',
        'other' => '其他连接',
        'other_discord' => '加入Discord服务器并与他人建立联系，聊聊关于游戏的事情，分享您最喜欢的整合包，并获得来自社区的帮助。',
        'other_twitter' => '在 Twitter 上关注以查看新更新或功能发布的时间，查看每周皮肤等等。',
        'other_instagram' => '在Instagram上关注SkinMC，浏览并发现酷炫的新特色Minecraft皮肤和图像。',
        'other_bluesky' => '关注SkinMC在Bluesky发布的更新和新功能，查看本周精选皮肤及更多内容。',
    ],
    'about' => [
        'intro' => '</span>你的</span> </span>Minecraft</span> </span>皮肤</span> <span>平台</span>
//</span>你</span> </span>的</span> </span>Minecraft</span> </span>皮</span> </span>肤</span> <span>平</span> </span>台</span>',
        'header_credit' => '示例“Epic Nether Battle”By',
        'info' => '跟上一切进度。',
        'info_explainer' => '查看玩家历史名称，查看他们以前的皮肤，将他们添加为朋友，下载皮肤，甚至获取详细统计。',
        'card_find_title' => '查找任何Minecraft玩家',
        'card_find_detail' => '通过搜索您选择的任何玩家用户名或 UUID 来开始。',
        'card_view_title' => '查看、保存&编辑',
        'card_view_detail' => '找到你喜欢的皮肤了吗？通过下载或使用编辑器将其保存为你自己的皮肤。',
        'card_claim_title' => '获取验证',
        'card_claim_detail' => '连接您的Minecraft账户并索取您的个人资料以解锁更多精彩功能！',
        'card_customise_title' => '自定义你的个人资料',
        'card_customise_detail' => '已验证的玩家可以添加他们的社交媒体链接并自行设置他们的个人资料。',
        'card_friends_title' => '添加好友',
        'card_friends_detail' => '在 SkinMC 上与您的朋友连接，然后在个人资料中显示您的朋友列表。',
        'card_history_title' => '用户名&历史皮肤',
        'card_history_detail' => '使用高级搜索来查找和查看玩家的用户名/皮肤历史记录。',
        'founders' => '创建者',
        'founders_cofounder' => 'SkinMC联合创始人',
        'head_of_design' => '设计主管',
        'head_of_code' => '代码负责人',
        'feedback' => '向我们发送反馈',
        'faq' => '有关Minecraft、皮肤和更多的问题？阅读我们的常见问题解答。',
        'faq_link' => '访问常见问题中心',
        'contact' => '您想要联系或有进一步的问题吗？直接联系我们。',
        'contact_link' => '联系我们',

    ],
    'faq' => [
        'title' => '常见问题解答',
        'subtitle' => '常见问题',
        'help' => '需要更多帮助?',
        'discord' => '加入Discord服务器来与其他Minecraft玩家聊天。',
        'contact' => '联系我们',
        'q' => [
            'change_skin_t' => '如何更改我的Minecraft皮肤？',
            'change_skin' => '
                <p>要更改皮肤，请执行以下操作：</p>
                <ol>
                    <li>访问<a href="https://my.minecraft.net/zh-hans/login/">“登录|Minecraft”</a>并使用您的账户登录</li><li>登录后，选择左侧菜单上的我的游戏→<b>“更改皮肤”</b></li><li>然后，选择你喜欢的模型并上传你喜欢的皮肤。</li>
                </ol>',
            'change_username_t' => '如何更改我的Minecraft用户名？',
            'change_username' => '
                <p>要更改您的用户名，请做以下操作：</p>
                <ol>
                    <li>访问 <a href="https://account.mojang.com/login" target="_blank" rel="nofollow">https://account.mojang.com/login</a> 并使用您的 Mojang 帐户登录。</li>
                    <li>查找您的Minecraft 配置文件名并按 <b>"(更改)"</b> 按钮</li>
                    <li>在下一页， 输入您所需的新用户名。</li>
                    <li>通过输入密码确认更改并按“更改名称”。</li>
                </ol>',
            'dl_t' => '如何下载某人的Minecraft皮肤？',
            'dl' => '
                <p>要下载任何一款Minecraft皮肤，请执行以下操作：</p>
                <ol>
                    <li>按下搜索栏，输入要下载皮肤的玩家的用户名。</li>
                    <li>在个人资料页面上，您可以预览皮肤</li>
                    <li>点击预览下的<strong>下载皮肤</strong>按钮</li>
                </ol>',
            'submit_q' => '如何向收藏提交皮肤？',
            'submit_a' => '<p>请填写以下简短表格，其中包含要添加到收藏中的用户名及其类别。 <a href="https://forms.gle/f4Jh5RpGfsHAZ5xE8" target="_blank">收藏提交表</a>',
            'mcpe_t' => '我可以在 Minecraft PE 上使用皮肤吗？',
            'mcpe' => '
                <p>对要在Minecraft PE（手机版）中使用皮肤，请执行以下操作：</p>
                <ol>
                    <li>在手机上打开SkinMC.net，然后点击搜索栏r</li>
                    <li>输入您想要下载的玩家皮肤的用户名</li>
                    <li>点击预览下的<strong>下载皮肤</strong>按钮 </li>
                    <li>打开Minecraft PE，点击右侧的<strong>个人资料</strong></li>
                    <li>点击<strong>+</strong>，或编辑角色并转到“经典皮肤选项卡”</li>
                    <li>点击“拥有”，然后点击“导入”，然后单击“选择新皮肤”</li>
                </ol>',
            'change_times_t' => '我可以多长时间更改我的用户名？',
            'change_times' => '<p>您可以<strong>每30天</strong>更改<strong>一次</strong>您的Minecraft用户名</p>',
            'available_t' => '在我更改了我的用户名后，他人何时可以申请它？',
            'available' => '<p>如果你想要改回你以前的用户名, 你可以在 <strong>30天后</strong>重新更改。其他所有人都需要等待额外的<strong>7天</strong> (更改后37天)才能申领您的旧用户名。 </p>',
            'username_history_t' => '你可以删除我的用户名历史记录吗？',
            'username_history' => '
                <p>由于用户名历史数据来自Mojang，因此无法删除用户名历史。Mojang之前曾表示，他们的意图是可以看到以前的用户名¹，并为公众提供了一种直接访问这些信息的方法²。</p>
                <p class="font-14">¹<a href="https://help.minecraft.net/hc/en-us/articles/360034636712-Minecraft-Usernames" target="_blank" rel="noreferrer">https://help.minecraft.net/hc/en-us/articles/360034636712-Minecraft-Usernames</a></p>
                <p class="font-14 mb-0">²<a href="https://twitter.com/dinnerbone/status/554739042529849345" target="_blank" rel="noreferrer">https://twitter.com/dinnerbone/status/554739042529849345</a>（2年前存档的推文：<a href="http://archive.is/TeAyj" target="_blank" rel="noreferrer">http://archive.is/TeAyj</a>）
                </p>',
        ],
    ],
    'avatars' => [
        'start' => [
            'title' => '创建您自己的Minecraft头像',
            'subtitle' => '使用Minecraft头像生成器从任何皮肤创建一个有趣的头像！',
            'avatar_face' => '面部样式头像',
            'avatar_bust' => '半身像',
            'avatar_cube' => '立体风格头像',
            'avatar_head3d' => '3D headshot',
            'avatar_bust3d' => '3D bust',
        ],
        'user' => [
            'title' => '选择皮肤',
            'subtitle' => '输入您想要生成的头像的Minecraft用户名',
            'form_label' => 'Minecraft用户名',
            'form_submit' => '继续',
        ],
        'output' => [
            'title' => '预览并保存',
            'subtitle' => '使用您新的Minecraft头像享受游戏',
            'download_info' => '喜欢这个结果吗？开始使用您的新头像，请在这里下载它',
            'download_button' => '下载头像',
            'avatar_style' => '头像样式',
            'skin_username' => '皮肤用户名',
            'change' => '更改',
            'generate' => '生成',
            'avatar_colour' => '背景色',
            'avatar_colour_palette' => '调色板',
            'avatar_colour_basic' => '基本',
            'show_nametag' => 'Show nametag',
            'loading_3d' => 'Loading 3D viewer…',
        ],
        'meta' => [
            'title' => 'Minecraft头像生成器',
            'description' => '创建Minecraft头像：使用Minecraft皮肤创建自定义Minecraft个人资料图片',
        ],
    ],
    'totem' => [
        'title' => '自定义Minecraft图腾',
        'subtitle' => '使用Minecraft 图腾生成器创建一个自定义资源包，其中包含任何皮肤的不死图腾。',
        'download_info' => '喜欢这个预览吗？选择您的Minecraft版本来保存您的自定义资源包：',
        'download_failed' => '无法加载皮肤图像，请检查用户名或试试上传一个图像。',
        'base64_size' => '图像的大小应小于256KB。',
        'meta' => [
            'title' => 'Minecraft自定义图腾生成器',
            'description' => '自定义Minecraft物品：使用您或任何其他玩家的Minecraft皮肤生成和创建一个自定义Minecraft资源包，带有不死图腾。',
        ],
        'type' => [
            'mini' => '你的皮肤的迷你版本！',
            'full' => '你的皮肤完整版本！',
            'model3d' => '你的皮肤的3d模型！',
            'add_designs' => '想要看到更多的设计吗？在这里提交您的设计建议：',
        ],
    ],
    'achievement' => [
        'header' => [
            'title' => '创建你自己的Minecraft成就',
            'subtitle' => '使用Minecraft成就生成器创建您自己的自定义成就，并在您喜欢的任何东西中显示您的进度！',
        ],
        'generator' => [
            'yellow_text' => '黄色文本',
            'white_text' => '白色文本',
            'choose_icon' => '选择图标',
            'face' => 'Minecraft面部而非图标',
            'form_submit' => '下载',
            'form_label' => 'Minecraft用户名',
            'download' => '下载',
            'embed' => '嵌入',
            'embed_copy' => '复制',
        ],
        'meta' => [
            'title' => 'Minecraft成就生成器',
            'description' => '与成就创建者生成自定义Minecraft成就和进度。 直接下载图像，将其用于论坛签名，嵌入HTML或 BB 代码，以及更多',
        ],
    ],
    'armor' => [
        'header' => [
            'title' => 'Minecraft盔甲架创作者',
            'subtitle' => '生成并创建您自己的自定义Minecraft盔甲架。创建不同的姿势、位置、放置项目等等。',
        ],
        'meta' => [
            'title' => 'Minecraft盔甲架创作者',
            'description' => '轻松生成和创建自定义的Minecraft盔甲架。编辑器可以帮助您制作不同的姿势、位置、放置项目、自定义皮肤等等。',
        ],
    ],
    'banner' => [
        'editor' => [
            'header' => [
                'title' => 'Minecraft 旗帜编辑器',
                'subtitle' => '设计和创建您自己的自定义Minecraft旗帜。这些可以用来装饰你的世界，也可以被视为<a href="https://optifine.net" target="_blank" rel="nofollow">可选</a>皮肤。',
            ],
            'meta' => [
                'title' => 'Minecraft 旗帜创作者',
                'description' => '使用游戏中的所有图案和颜色创建和设计您自己的自定义Minecraft 旗帜设计！这些可以用来装饰你的世界，也可以用旗帜披风作为可选披风穿着。你可以生成旗帜或盾牌的代码。',
            ],
            'toolbar' => [
                'title' => '旗帜编辑器',
                'randomise' => 'Randomise',
                'clear_layers' => '清空图层',
                'help' => '帮助',
                'save_banner' => '保存旗帜',
                'submit_to_gallery' => '添加到图库',
                'reset_from_url' => '从链接中加载',
                'minecraft_version' => 'Minecraft 版本',
                'texture_type' => '纹理类型',
                'banner' => '旗帜',
                'shield' => '盾牌',
                'version_1_21' => '1.21+',
                'version_1_16' => '1.16 - 1.20',
                'version_1_13' => '1.13 - 1.15',
                'version_1_8' => '1.8 - 1.12',
            ],
            'tools' => [
                'share_link' => '分享链接',
                'share_link_placeholder' => '分享链接',
                'generate_codes' => '生成码',
                'target_selector' => '目标选择器',
                'command_give' => 'Give',
                'command_setblock' => 'Setblock',
                'command_replaceitem_shield' => '盾牌',
                'code_placeholder' => '选择一个命令以生成代码',
                'import_code' => '导入代码',
                'background_grass' => '草地背景',
            ],
            'modal' => [
                'save_banners' => '保存的旗帜',
                'share_saved_gallery' => '分享保存的相册',
                'share_saved_gallery_placeholder' => '分享保存的相册',
                'export_to_chest' => '导出至箱子',
                'delete_all' => '全部删除',
            ],
        ],
        'gallery' => [
            'header' => [
                'title' => 'Minecraft 旗帜画廊',
                'subtitle' => '浏览 :count 个自定义设计的Minecraft旗帜。你可以用旗帜作为披风，让你的Minecraft皮肤更加独特，或者用旗帜作为彩旗来装饰你的世界。',
            ],
            'meta' => [
                'title' => 'Minecraft 旗帜画廊',
                'description' => '浏览 :count 个自定义设计的Minecraft旗帜。你可以用旗帜作为披风，让你的Minecraft皮肤更加独特，或者用旗帜作为彩旗来装饰你的世界。',
            ],
            'add_design' => '新建设计',
            'sort' => '排序：',
            'sort_trending' => '热门',
            'sort_best' => '最佳的',
            'sort_newest' => '最新',
            'sort_oldest' => '最早',
            'sort_favorites' => '最受欢迎',
            'sort_views' => '最多浏览',
            'sort_last_week' => '上周',
            'sort_last_30d' => '最近30天',
            'clear_filters' => '清除筛选器',
            'no_banners' => '尚未有旗帜',
            'no_banners_message' => '还没有这样的设计。成为第一个设计并共享的人吧。',
            'create_banner' => '创建一个旗帜',
        ],
        'publish' => [
            'title' => '发布一个旗帜',
            'publish_button' => '发布',
            'title_label' => '标题',
            'description_label' => '描述',
            'tags_label' => '标签',
            'tags_max_reached' => '已达到最多5个标签',
            'tags_add_placeholder' => '添加一个标签',
            'tags_help' => '按回车键、标签或逗号来添加标签。',
            'tags_max_error' => '您最多可以添加5个标签。',
            'generate_banner_error' => '先创建一个设计。',
            'invalid_code_format' => '无效的旗帜代码格式。',
            'invalid_base_color' => '无效的基色。应当介于0到15之间。',
            'invalid_patterns_format' => '无效的图案格式。',
            'invalid_pattern_structure' => '无效的图案结构。',
            'invalid_pattern_unknown' => '未知图案。',
            'invalid_pattern_color' => '无效的图案基色。应当介于0到15之间。',
        ],
        'edit' => [
            'title' => '编辑旗帜',
            'title_label' => '标题',
            'description_label' => '描述',
            'tags_label' => '标签',
            'tags_max_reached' => '已达到最多5个标签',
            'tags_add_placeholder' => '添加一个标签',
            'tags_help' => '按回车键、标签或逗号来添加标签。',
            'tags_max_error' => '您最多可以添加5个标签。',
            'save_changes' => '保存变更',
            'cancel' => '取消',
            'edit_details' => '编辑旗帜的细节',
            'delete' => '删除旗帜',
            'delete_confirm' => '确定删除此旗帜？此操作无法撤销。',
        ],
        'show' => [
            'edit_design' => '编辑设计',
            'banner_give_command' => '获取旗帜的指令',
            'setblock_command' => 'Setblock指令',
            'shield_give_command' => '盾牌获取指令',
            'views_count' => ':count 评论 |:count 评论',
            'favourites_count' => ':count 收藏|:count 收藏夹',
            'favourite_label' => '收藏',
            'favourites_label' => '收藏夹',
            'similar_banners' => '相似的旗帜',
        ],
        'already_exists' => '此旗帜已经在图库中。',
    ],
    'skin_creations' => [
        'search_tab' => 'Creations',
        'gallery' => [
            'title' => 'Skin Creations',
            'description' => 'Browse :count custom Minecraft skin creations.',
            'header' => [
                'title' => 'Skin Creations',
                'subtitle' => ':count creation|:count creations',
            ],
            'tab_creations' => 'Creations',
            'upload' => 'Upload skin',
            'downloadable_only' => 'Downloadable only',
            'sort_trending' => 'Trending',
            'sort_best' => 'Best',
            'sort_newest' => 'Newest',
            'sort_oldest' => 'Oldest',
            'sort_favorites' => 'Most favourites',
            'sort_views' => 'Most views',
            'sort_last_week' => 'Last week',
            'sort_last_30d' => 'Last 30 days',
            'sort_recently_updated' => 'Recently updated',
            'empty_title' => 'No creations yet',
            'empty_message' => 'Be the first to share a skin creation.',
            'clear_filters' => 'Clear',
        ],
        'upload' => [
            'title' => 'Upload skin creation',
            'description' => 'Upload a Minecraft skin to the gallery.',
            'heading' => 'Upload skin',
            'subtitle' => 'Drag and drop a PNG or choose a file. Add a title, description, and tags.',
            'drop_here' => 'Drop here',
            'drag_or_click' => 'Drag and drop a skin or click to choose',
            'format_hint' => 'PNG · 64×32 or 64×64',
            'choose_file' => 'Choose file',
            'title_label' => 'Title',
            'title_placeholder' => 'e.g. Mystical Warrior Skin',
            'description_label' => 'Description',
            'description_placeholder' => 'Tell others about your skin creation...',
            'tags_label' => 'Tags',
            'tags_placeholder' => 'e.g. fantasy, knight, blue',
            'tags_hint' => 'Up to 12 tags, comma-separated.',
            'downloadable' => 'Allow download',
            'downloadable_hint' => 'Allow other users to directly download your creation.',
            'visibility_label' => 'Visibility',
            'more_options' => 'More options',
            'credit_label' => 'Credit',
            'credit_placeholder' => 'Optional credit or attribution',
            'alt_text_label' => 'Alt text',
            'alt_text_subtitle' => 'This helps people using screen readers understand what your skin is about.',
            'alt_text_placeholder' => 'Describe what your skin looks like (optional)',
            'submit' => 'Publish',
            'cancel' => 'Cancel',
            'edit_in_editor' => 'Edit skin',
            'please_upload_skin' => 'Please upload a skin first.',
            'remixable' => 'Allow remixing',
            'remixable_hint' => 'Allow other users to remix your creation.',
        ],
        'edit' => [
            'title' => 'Edit skin creation',
            'description' => 'Edit your skin creation.',
            'heading' => 'Edit creation',
            'subtitle' => 'Update title, description, tags, or re-upload the skin.',
            'submit' => 'Save changes',
        ],
        'show' => [
            'download' => 'Download',
            'download_button' => 'Download skin',
            'open_in_editor' => 'Open in editor',
            'edit' => 'Edit details',
            'delete' => 'Delete',
            'delete_confirm' => 'Delete this creation? This cannot be undone.',
            'similar' => 'Similar creations',
            'created_at_ago' => 'Created :time',
            'updated_at_ago' => 'Updated :time',
            'created_and_updated' => 'Created :created · Updated :updated',
            'version_number' => 'Version :number',
            'version_history' => 'Version history',
            'iterations' => 'Iterations',
            'before_after' => 'Before & after',
            'previous' => 'Previous',
            'current' => 'Current',
            'tagged' => 'Tagged',
            'tagged_alt' => 'Tagged',
            'no_tags' => 'No tags',
            'stats' => 'Stats',
            'no_stats' => 'No stats',
        ],
        'validation' => [
            'invalid_skin_format' => 'Invalid skin format. Minecraft skins must be 64×32 or 64×64 PNG.',
            'tags_max_error' => 'You can add a maximum of 12 tags.',
        ],
        'deleted' => 'Creation deleted.',
        'download_disabled' => 'This creation is not available for download.',
        'editor' => [
            'save_to_gallery' => 'Save to gallery',
            'save_new_version' => 'Save new version',
            'save_updated_skin_version' => 'Save updated skin version',
            'save_as_new_creation' => 'Save as new creation',
            'published_successfully' => 'Your skin has been published successfully!',
            'saved_new_version' => 'New version saved.',
            'previous_skin_available' => 'A previously edited skin was found. Would you like to restore it?',
            'restore_skin' => 'Restore',
            'skin_loaded' => 'Skin loaded successfully',
            'preparing_upload' => 'Preparing your upload…',
            'bridge_fail_missing' => 'Your skin is still safe in the editor. Try saving to gallery again.',
            'bridge_fail_invalid' => 'Your skin is still safe in the editor. We couldn\'t use the saved copy — please try saving to gallery again.',
            'bridge_fail_server' => 'Your skin is still safe in the editor. Something went wrong — please try saving to gallery again.',
            'pending_replaced' => 'Your previous pending upload was replaced with your latest skin.',
            'claim_step' => 'Step 1 of 2',
            'claim_title' => 'Link your Minecraft account',
            'claim_description' => 'To publish skins to the gallery, link your Minecraft account first. This is a quick, one-time setup.',
            'claim_skin_safe' => 'Your skin is saved and will be ready to publish right after linking.',
            'claim_button' => 'Link Minecraft Account',
            'claim_reassurance' => 'Your skin is safe — you\'ll continue to publishing after linking.',
            'claim_posting' => 'Saving your skin…',
            'claim_fail' => 'Something went wrong — your skin is safe in the editor. Please try again.',
        ],
        'visibility' => [
            'public' => 'Public',
            'unlisted' => 'Unlisted',
            'draft' => 'Draft',
        ],
    ],
    'search' => [
        'meta' => [
            'title' => '搜索结果：:search',
        ],
        'what_are_you_searching_for' => '您在寻找什么？',
        'title' => '搜索结果',
        'results' => '第:current页，共:count页结果|第:current页，共约:count个结果 ',
        'results_count' => ':count 结果|:count 结果总数',
        'time' => '(:time 秒)',
        'username_available' => '用户名可用*',
        'username_unavailable' => '用户名不可用',
        'username_status' => '状态',
        'username_status_available' => '有效的*',
        'username_status_unavailable' => '无效的',
        'username_searches' => '搜索',
        'username_searches_count' => ':count/天',
        'username_available_disclaimer' => '*除非该名称被Mojang暂时或永久禁止。',
        'no_results' => '未找到个人资料。尝试通过更改搜索类型使用UUID进行搜索。',
        'no_results_tags' => '找不到标签的皮肤。试着搜索其他标签，如“蓝色”、“女孩”、“fox”等...',
        'again' => '重新搜索',
        'sorry' => '啊哦，实在抱歉~~',
        'view_profile' => '查看个人资料',
        'view_all' => '查看全部',
        'filters' => '筛选器',
        'more_results' => '更多结果',
        'more_results_fallback' => '更多结果',
        'close' => '关闭',
        'clear_filters' => '全部清除',
        'profiles' => '个人资料',
        'verified_only' => '仅已认证',
        'verification' => '认证',
        'all' => '全部',
        'verified' => '已认证',
        'not_verified' => '未认证',
        'country' => '国家',
        'country_placeholder' => '例如：US, UK',
        'no_types_found' => '没有找到此搜索的项目类型',
        'no_categories_found' => '没有找到此搜索的项目类型',
        'featured' => '精选',
        'yes' => '是',
        'no' => '否',
        'skins' => '皮肤',
        'tags' => '标签',
        'no_tags_found' => '没有找到此搜索的标签',
        'min_profiles' => 'Min profiles using',
        'try_different' => '尝试另一个搜索词',
        'skins_no_results' => '未发现皮肤',
        'empty_state' => [
            'title' => 'No matches this time',
            'message' => "我们没有找到任何搜索结果。请尝试调整您的关键字或看看别的。",
        ],
    ],
    'collection' => [
        'title' => 'Minecraft皮肤收藏',
        'subtitle' => '浏览我们管理过的Minecraft皮肤收藏。',
        'filters' => '筛选',
        'title_trending' => '热门',
        'title_all' => '所有Minecraft皮肤',
        'skin_tags' => '标记的皮肤',
        'filters_skin_type' => '皮肤类型',
        'filter_skin_type_steve' => 'Steve类型',
        'filter_skin_type_alex' => 'Alex类型',
        'cancel' => '取消',
        'apply' => '应用',
        'username_minecraft_skin' => ':username的Minecraft 皮肤',
        'user_downloads' => '<span class="fw-500">:downloads</span> 下载 |<span class="fw-500">:downloads</span> 下载',
    ],
    'favourites' => [
        'title' => '收藏夹',
        'subtitle' => '查看和管理您保存到您的收藏夹中的皮肤和服务器',
        'sort' => '排序方式',
        'toast' => [
            'added' => '已添加到您的收藏列表',
            'removed' => '已从您的收藏列表中移除',
            'login_required' => '登录以添加到收藏夹',
        ],
        'skins' => [
            'button' => '皮肤',
            'empty_headline' => 'No skins saved yet.',
            'empty_subtitle' => 'Skins you save will appear here.',
            'empty_browse' => '浏览皮肤',
            'meta' => [
                'title' => '我收藏的皮肤',
                'description' => '我已经收藏的皮肤',
            ],
        ],
        'creations' => [
            'heading' => 'Skin creations',
            'empty_headline' => 'No favourite skin creations yet',
        ],
        'servers' => [
            'button' => '服务器',
            'empty_headline' => 'No servers saved yet.',
            'empty_subtitle' => 'Save servers you want to revisit later.',
            'empty_browse' => '浏览服务器',
            'meta' => [
                'title' => '我最喜欢的服务器',
                'description' => '我最喜欢的Minecraft服务器',
            ],
        ],
        'banners' => [
            'button' => 'Banners',
            'empty_headline' => 'No banners saved yet.',
            'empty_subtitle' => 'Banners you save will be shown here.',
            'empty_browse' => 'Browse banners',
            'meta' => [
                'title' => 'My favourite banners',
                'description' => 'My favourite Minecraft banners',
            ],
        ],
    ],
    'cape' => [
        'editor' => [
            'title' => 'Minecraft披风编辑器',
            'subtitle' => '使用Minecraft披风编辑器来创建你自己的自定义披风。',
            'meta' => [
                'title' => 'Minecraft披风编辑器',
                'description' => '使用Minecraft披风编辑器来创建你自己的自定义披风。',
            ],
        ],
        'list' => [
            'title' => 'Minecraft披风',
            'subtitle' => 'Minecraft官方斗篷。斗篷是一种纪念物品，除了作为玩家的皮肤外，还可以佩戴。当戴上鞘翅时，它们也可以改变外观。',
            'meta' => [
                'title' => 'Minecraft披风列表',
                'description' => 'Minecraft披风列表：查看所有官方Minecraft披风，包括Mojang、Minecon、Personal、Special和虚荣披风',
            ],
        ],
        'detail' => [
            'title' => ':cape 披风',
            'info' => '披风信息',
            'profile_list' => '带有此斗篷的配置文件',
            'profiles' => ':profiles 个人资料|:profiles 个人资料',
            'meta' => [
                'title' => ':cape Minecraft披风',
                'description' => '查看 :cape Minecraft披风并看看玩家穿着它！',
            ],
        ],
        'list-custom' => [
            'title' => '自定义Minecraft披风',
            'description' => '浏览和查看已经创建并被SkinMC 成员使用的自定义披风。',
        ],
    ],
    'servers' => [
        'title' => 'Minecraft服务器',
        'subtitle' => '浏览并探索Minecraft服务器',
        'all' => '所有服务器',
        'manage_your_servers' => '管理您的服务器',
        'add_new_server' => '添加新的服务器',
        'filters' => [
            'trending' => '热门',
            'updated' => '已更新',
            'new' => '最新的',
            'most_viewed' => '访问最多',
            'top_voted' => '最高点赞',
            'sorting' => '排序中',
            'sort_by_latest' => '按照最新排序',
            'sort_by_oldest' => '按最老的排序',
            'categories' => '类别',
            'server_location' => '服务器地址',
            'show_results' => '显示结果',
            'show_more' => '显示更多',
            'show_less' => '收起',
            'clear_filters' => '清空筛选',
            'reviews' => '评论',
            'sort_by_highest_rating' => '按最高评分排序',
            'sort_by_lowest_rating' => '按最低评分排序',
            'bedrock_and_java_support' => '基岩 和 Java 支持',
        ],
        'review-count' => ':count 评论 |:count 评论',
        'meta' => [
            'title' => 'Minecraft服务器列表',
            'description' => '浏览并探索Minecraft服务器列表以找到最好的 Minecraft 服务器！筛选最晚、最受欢迎和更多的类型',
        ],
        'reviews' => [
            'meta' => [
                'title' => '写一个评论',
            ],
            'editing' => '您正在从 :date编辑您的评论。您想要删除您的评论吗？',
            'welcome' => 'Hi :username. 您在 :servername 上的总体体验如何？',
            'subtitle' => '根据你的印象对服务器打个分吧！',
            'scale' => [
                'great' => '优',
                'good' => '良',
                'okay' => '可',
                'meh' => '及',
                'bad' => '差',
            ],
            'rate-experience' => '接下来，对以下方面打个分吧！',
            'overall' => '整体',
            'server-team' => '服务器团队',
            'community' => '社区',
            'experience' => '体验',
            'availablility' => '更新时间和可用性',
            'shop' => '商店',
            'write-review-title' => '撰写评论',
            'write-review-subtitle' => '您可以写一些您喜欢的东西，或者一些特殊的体验，或者提出一些建议。',
            'write-review-helper' => '撰写服务器评论，与新玩家分享您的体验，并给予服务器拥有者一些反馈。',
            'write-review-tips' => '一些小提示',
            'submit-title' => '确定提交您的评论？',
            'submit-subtitle' => '就差一步！',
            'submit-review' => '提交评论',
            'back' => '上一步',
            'continue' => '继续',
            'delete-title' => '您确定要删除您的评论吗？',
            'tos-checkbox-part-1' => '提交此表格即表示您接受SkinMC的服务条款、隐私政策和社区指南。您还确认所有信息都是准确的，并遵循',
            'tos-checkbox-part-2' => '审评准则。',
            'tos-checkbox-part-3' => '您的评论将在提交后发布，但可能会受到审查。',
        ],
        'slots' => '栏位',
        'empty-helper' => '您可以尝试其他搜索。',
        'empty' => 'Hmm 这里仍然是空的。',
        'verified' => '已验证',
        'review_translate_show_original' => '显示原始内容',
        'review_translate' => '翻译评论',
        'description_translate' => '翻译描述信息',
        'create' => [
            'welcome' => '欢迎',
            'basics' => '基本资料',
            'categories' => '类别',
            'social_links' => '社交链接',
            'trailer_video' => '预告片视频',
            'images' => '图片',
            'images_description' => '您可以上传照片，以展示您的服务器提供的内容。',
            'submit' => '提交',
            'lets_get_your_server_added' => '让我们添加您的服务器吧。',
            'basics-subtitle' => '让人们知道你的服务器是关于什么的。',
            'description' => '描述',
            'description_tips' => '这里有一些小提示',
            'description_hint' => '为您的服务器撰写一个很好地描述来吸引新的玩家。',
            'categories-subtitle' => '为您的服务器选择某些类别',
            'missing-category' => '缺少类别？',
            'social_links_description' => '玩家在哪里可以在社交媒体上连接到你的服务器',
            'trailer_video_description' => '用YouTube视频展示您的服务器。',
            'trailer_video_hint' => '粘贴视频 URL 或 ID：',
            'ready_to_submit_your_server' => '准备好提交您的服务器了吗？',
            'review-hint' => '在提交后，团队将仔细审查您的服务器列表应用程序。然后根据决定，您的服务器将被发布，或者在运行前请求更改。',
            'terms' => [
                'part-1' => '通过提交此表格，您有权接受SkinMC的服务条款、隐私政策和社区指南。您还确认以上所有信息都是准确的，您已正确遵循。',
                'part-2' => '服务器安装要求',
                'part-3' => '，Minecraft服务器由您所代表的实体所有和管理。',
            ],
            'submit-application' => '提交申请',
            'video-id-helper' => [
                'part-1' => '视频ID是数字和字母的字符串',
                'part-2' => '例如，如果您的视频URL是',
                'part-3' => '，然后您的视频 ID 将是',
            ],
            'welcome_description' => '在这一步骤中，我们将开始添加您的服务器。 告诉我们一点有关它的信息，写一个描述，下一步你可以上传一些图像。',
        ],
        'copy_server_ip' => '复制服务器IP',
        'all_minecraft_servers' => '所有Minecraft服务器',
        'promo' => [
            'title' => '您是Minecraft服务器的服主吗？',
            'ready_to_list_your_server' => '准备好列出您的服务器吗？',
            'everything_you_need' => '发展服务器所需的一切',
            'list_your_server' => '列出您的服务器',
            'list_your_server_description' => '为您的服务器创建一个列表、添加照片、社交媒体等等。',
            'find_players' => '查找玩家',
            'find_players_description' => '寻找和接触新玩家以加入您的服务器并扩大您的社团。',
            'get_reviews' => '获得评论',
            'get_reviews_description' => '请您的社团查看您的服务器，并在游戏中奖励他们。',
            'why_list_on_skinmc' => '为什么你应该在SkinMC上列出你的服务器',
            'others' => '其它',
            'quality_check_and_confirmation' => '质量检查与确认',
            'quality_check_description' => '我们的团队审查每个服务器以确保质量。',
            'verified_players' => '已验证的Minecraft玩家的评论',
            'verified_players_description' => '从 Votifier 整合的合法账户中收集真实玩家的评论。',
            'international' => '多语言环境',
            'international_description' => '通过翻译功能，您的列表可供更多玩家使用。',
            'server_listing_page' => '强大的服务器列表页面',
            'server_listing_page_description' => '添加照片，描述文本，YouTube视频，并突出显示玩家加入您的服务器的理由。',
            'social_connections' => '社交媒体连接',
            'social_connections_description' => '连接您的服务器社交账户，显示新的玩家可以找到您。',
            'verified_badge' => '验证徽章',
            'verified_badge_description' => '验证服务器可以申请验证徽章。',
            'owner_profile' => '所有者个人资料',
            'owner_profile_description' => '通过自定义您的个人资料，增加个人魅力。',
            'categories' => '类别',
            'categories_description' => '不同的类别将更容易找到您的服务器。',
            'vote' => '投票',
            'vote_description' => '请用户为您的服务器投票。',
            'fair_listings' => '公平列表',
            'fair_listings_description' => 'SkinMC 上的服务器列表无法人为提升搜索结果排名。',
            'support' => '24小时支持',
            'support_description' => '您需要帮助吗？还是有一些疑问？您可以随时联系，我们会尽快回复。',
            'custom_features' => '自定义功能',
            'custom_features_description' => '您的服务器缺少一个功能？打开一个工单，我们会实现它。',
            'faq' => [
                'title' => '常见问题',
                'suited-question' => '我的Minecraft服务器是否适合SkinMC？',
                'suited-answer' => 'SkinMC上的Minecraft体玩家热衷于探索新的验、内容和社区交流。 在这个平台上，您会找到各种不同的、独特的、有趣的Minecraft服务器。 不管是一个庞大的服务器，或是一个小的生存服务器，都有其独特的乐趣！',
                'get-started-question' => '我该如何使用？',
                'get-started-answer' => '将您的Minecraft服务器添加到SkinMC 服务器列表非常简单！您将首先需要创建一个SkinMC帐户（如果您尚未创建的话），然后按照设置指南提交您的服务器。 添加几张照片和一些精彩的描述，您的服务器将立即发布！',
                'players-question' => '如何为我的Minecraft服务器吸引更多玩家？',
                'players-answer' => '建设一个社区是一个Minecraft 服务器持久的的最关键部分。 使用 SkinMC 上的 Minecraft 服务器列表来寻找新的受众并继续建立您的社区。 请玩家推荐您的服务器，或在社交媒体平台上分享您的列表。 收集好的评论对于吸引新玩家的优秀服务器列表也可以发挥重要作用。',
                'more-question' => '我还有一些问题，我可以从哪里得到解答？',
                'more-answer' => '您可以随时点击帮助按钮，与SkinMC联系， 或加入我们的Discord服务器。',
            ],
            'ready_to_list_description' => '只需几分钟即可将您的Minecraft服务器添加到SkinMC服务器列表。 如果您需要帮助，您可以随时随地联系我们，我们会尽快回复。',
        ],
        'manage' => [
            'index' => [
                'welcome' => '欢迎回来，:username',
                'your_servers' => '您的服务器',
                'reviews_today' => '今日评论',
                'no_reviews_today' => '今天没有评论',
                'no_reviews_text' => '您的服务器今天没有收到任何评论。试着让您的玩家撰写一些？',
                'tips' => [
                    'title' => '小提示',
                    'description-title' => '写一个好的服务器描述',
                    'description-body' => '写一个精美的服务器描述的一些提示和建议',
                    'images-title' => '添加一些服务器图片',
                    'images-body' => '用精美的图片装饰你的服务器页面',
                ],
            ],
            'listings' => [
                'title' => '您的 Minecraft 服务器 (:count)',
            ],
            'insights' => [
                'title' => '数据分析',
            ],
            'edit_server' => '编辑服务器',
            'listing' => '列表',
            'to_do' => '待办',
            'last_update' => '最后更新',
            'add_more_photos_to_publish' => '添加更多照片到发布',
            'looks_empty_here' => '这里看起来是空的。',
            'get_started_by_adding_a_new_server' => '从添加新服务器开始吗？',
        ],
        'status' => [
            'approved' => '已审批',
            'pending_approval' => '等待审批',
            'published' => '已发布',
            'in_review' => '审核中',
        ],
    ],
    'editor' => [
        'import' => [
            'title' => '导入皮肤',
            'import_by_username' => '通过用户名导入',
            'import_button' => '导入',
            'drag' => '拖放皮肤到此处，或点击',
            'click' => '选择图片',
        ],
        'download' => [
            'error' => [
                'no-data' => '没有提供皮肤数据。请重试。',
                'invalid-format' => '皮肤数据格式无效。请再试一次。',
                'invalid-data' => '皮肤数据损坏。请重试。',
                'generic' => '下载皮肤时出了错。请再试一次。',
            ],
        ],
        'draw' => '画笔',
        'eyedropper' => '吸管工具',
        'fill' => '填充',
        'move' => '移动',
        'decrease_brightness' => '降低亮度',
        'increase_brightness' => '增加亮度',
        'erase' => '橡皮擦',
        'undo' => '后退(CTRL+Z)',
        'redo' => '前进(CTRL+Y)',
        'default_view' => '默认视图',
        'zoom_in' => '放大(CTRL +)',
        'zoom_out' => '缩小 (CTRL -)',
        'saved' => '刚刚保存最后一个',
        'saving' => '自动保存中...',
        'save_error' => '出现了错误。',
        'new_skin' => '新建皮肤',
        'automatically_saved_skins' => 'Automatically saved skins',
        'recovered_skins' => 'Recovered skins',
        'load' => 'Load',
        'delete' => 'Delete',
        'backed_up_title' => '自动保存的皮肤',
        'backed_up_info' => '临时备份到您的本地存储。',
        'backed_up_empty_title' => '这里是空的',
        'backed_up_empty_info' => '一旦你开始编辑皮肤，你会在这里看到你最后编辑的32个皮肤。',
        'recovered_empty_title' => 'No recovered skins',
        'recovered_empty_info' => 'Recovered skins will appear here when you navigate away or close the editor.',
        'backed_up_skins_count' => '32个皮肤备份已使用',
        'backed_up_skins_count_info' => '你可以备份多达32个皮肤。一旦你达到32个皮肤，旧皮肤将被新皮肤替换。',
        'layers' => '图层',
        'body' => [
            'title' => '身体',
            'overlay' => '皮肤外层',
            'head' => '头部',
            'torso' => '躯干',
            'l_arm' => '左臂',
            'r_arm' => '右臂',
            'l_leg' => '左腿',
            'r_leg' => '右腿',
        ],
        'model' => '模型',
        'steve' => 'Steve',
        'alex' => 'Alex',
        'stance' => [
            'title' => '动作',
            'default' => '默认',
            'walk' => '走',
            'run' => '跑',
            'hug' => 'T型',
            'fly' => '飞',
        ],
        'fullscreen' => '全屏模式',
        'fullscreen_exit' => '退出全屏',
        'grid' => '网格',
        'show_grid' => '显示网格',
        'download' => [
            'title' => '保存并下载',
            'subtitle' => 'SkinMC 账户',
            'description' => '您想要创建一个免费的 SkinMC 账户来将您的皮肤和未来的皮肤保存到云端吗？',
            'start_description' => '不保存到云端，直接开始下载',
            'start' => '下载皮肤',
        ],
        'help' => [
            'title' => 'Minecraft皮肤编辑器',
            'about' => '轻松地使用自定义Minecraft皮肤编辑器创建和编辑您的皮肤。 您可以在Steve和Alex模型之间进行选择，从文件或用户名导入皮肤，并创建自己的 Minecraft 皮肤。',
            'draw' => '使用钢笔工具绘制。从样例中选择要与之一起使用的颜色。',
            'eyedropper' => '使用滴管从皮肤中选择一种颜色，并将其添加到当前调色板中。',
            'fill' => '使用填充工具填充整个皮肤区域。在使用填充之前选择一种颜色。',
            'move' => '使用移动工具在皮肤编辑器画布上平移和移动。',
            'decrease_brightness' => '降低当前激活颜色的亮度。',
            'increase_brightness' => '增加当前激活颜色的亮度。',
            'erase' => '擦除在辅助覆盖层上绘制的像素。',
            'minimap' => 'Minimap',
            'minimap_info' => '在3D 模式下，minimap可以在平坦视图中显示您的皮肤纹理。 在 2D 模式下，minimap切换到您的皮肤的3D预览。您可以放大或缩小视图。',
            'autosave' => '自动保存',
            'autosave_info' => '自动保存功能将会在每30秒时自动保存您的皮肤。 您可以通过点击文件夹图标并选择“先前的皮肤”来访问编辑器中的自动化皮肤。',
            '2d_editor' => '2D和3D编辑器',
            '2d_editor_info' => '在 2D 或 3D 模式中编辑您的 Minecraft 皮肤。',
        ],
    ],
    'account' => [
        'level' => '等级',
        'level_history' => '等级历史记录',
        'xp' => 'XP',
        'my_xp' => '我的XP',
        'xp_to_next_level' => ':xp XP 到下一等级',
        'xp_info' => '什么是 XP？',
        'xp_info_tooltip' => 'XP是通过各种活动获得的，比如为皮肤添加标签、邀请朋友、评论等等。每获得XP，您就可以升级并解锁酷炫的东西！',
        'table' => [
            'description' => 'Description',
            'points' => 'Points',
        ],
        'my_stuff' => [
            'title' => 'My stuff',
            'creations' => 'Creations',
            'collections' => 'Collections',
            'favourites' => 'Favourites',
            'skins' => 'Manage skins',
            'capes' => 'Capes',
            'banners' => 'Banners',
            'servers' => 'Servers',
        ],
        'settings' => [
            'title' => '账户',
            'show_profile' => '前往个人资料',
            'friends' => '好友',
            'friends_detail' => '使用 SkinMC 上的好友列表保持连接。',
            'security' => '帐号安全',
            'security_detail' => '修改您的登录密码并保证您的帐户安全',
            'social' => '社交媒体帐户',
            'social_detail' => '通过添加您的社交媒体来自定义您的个人资料',
            'link' => '链接Minecraft帐户',
            'link_detail' => '链接您的Minecraft账户并获取您的个人资料。',
            'logout' => '您想要退出登录吗？',
            'automatic_backups' => '自动备份皮肤',
            'automatic_backups_info' => '作为 SkinMC puls 会员，您的皮肤每天都会备份。',
        ],
        'capes' => [
            'title' => 'SkinMC Minecraft 披风',
            'description' => '使用SkinMC Capes穿戴你想要在游戏中显示的披风，此功能是免费的',
            'drop' => '拖放披风图片到这里',
            'drop-hint' => '尺寸仅限 64x32px',
            'select' => '选择图片',
            'upload-cape' => '上传并使用披风',
            'save-and-use' => '保存并使用',
            'uploaded-cape' => '已上传的披风',
            'no-cape' => '无披风',
            'remove-cape' => '移除披风',
            'download' => '下载 SkinMC Mod 以查看您和其他玩家在游戏中的披风。',
            'learn-more' => '了解更多',
            'link-account' => '要上传斗篷，请先链接您的 Minecraft 帐户。',
            'updated' => '您的披风已更新！',
            'removed' => '您的披风已被移除。',
            'active' => '你的披风已激活！',
        ],
        'favourite' => '收藏',
        'remove_favourite' => '取消收藏',
        'added_to_favourites' => '已添加到收藏列表',
        'removed_from_favourites' => '从收藏夹中移除',
        'welcome' => '很高兴见到您！',
        'view-profile' => '查看我的个人资料',
        'security' => [
            'title' => '帐号安全',
            'email' => '电子邮件地址',
            'email-title' => '更新您的电子邮件地址。',
            'save' => '保存',
            'password' => '密码',
            'password-title' => '随时更改您的密码。',
            'social-provider' => '要更新您的账户信息，例如您的密码，请访问您的登录提供商：',
            'social-provider-email' => '您与您登录提供商关联的电子邮件地址',
            'social-provider-connected' => '当前已链接的其他账号',
            'current-password' => '旧密码',
            'forgot' => '忘记密码？',
            'edit' => '编辑',
            'delete' => '删除我的账户',
            'account-deletion' => '删除您的 SkinMC 帐户。',
            'delete-info' => '请再次确认以继续',
            'delete-confirmation' => '删除帐户是不可逆的。您的所有个人信息和内容，例如帖子、收藏夹、上传的披风、自定义信息等等，都将被删除，无法恢复。',
            'delete-confirmation-info' => '输入您的密码以继续',
            'delete-confirmation-info-social' => '输入 "delete" 以确认帐户删除',
            'type-delete' => '输入 "delete" 以确认',
            'type-delete-label' => '输入 "delete" 以确认',
            'yes-confirm-delete' => '是的，确认删除',
            'account-successfully-deleted' => '您的帐户和数据已经成功删除。',
        ],
        'social' => [
            'title' => '社交媒体帐户',
            'edit' => '修改',
            'save' => '保存',
            'link-account' => '将您的 Minecraft 账户链接到SkinMC 以在您的个人资料上显示您的社交链接。',
            'finish-setup' => '完成设置',
            'connect-account' => '绑定你的账号',
            'connect-description' => 'Choose which accounts you wish to connect and unlock special SkinMC integrations.',
            'empty' => '未添加账户',
            'empty-description' => '您的社交媒体账户将显示在这里和您的公开个人资料中。 一旦添加，他们将添加更多的个性化到您的页面，并启用集成。',
            'connect' => '连接',
            'username' => '用户名',
            'spotify' => '添加您的 Spotify 用户名来显示您的 Spotify 信息到您的个人资料中。',
            'discord' => '输入您的 Discord 用户名和号码以在您的 SkinMC 配置文件中显示您的 Discord 信息。',
            'youtube' => '添加您的 YouTube 频道到 SkinMC ，这将在您的个人资料中显示您的 YouTube 频道。',
            'youtube-format' => '根据您的频道链接，使用以下格式：',
            'twitter' => '输入您的X(旧名 Twitter)用户名以在您的个人资料中显示它。',
            'bluesky' => '请输入你的Bluesky ，例如username.bsky.social，以便在你的个人资料上显示你的Bluesky 个人信息。',
            'twitch' => '输入您的Twitch用户名以在您的个人资料上显示您的Twitch频道。',
            'reddit' => '输入您的Reddit用户名以在您的个人资料上显示您的Reddit信息。',
            'github' => '输入您的GitHub用户名以在您的个人资料上显示您的GitHub信息。',
            'telegram' => '输入您的Telegram用户名以在您的个人资料上显示您的Telegram信息。',
            'tiktok' => '输入您的TikTok用户名以在您的个人资料上显示您的TikTok信息。',
            'snapchat' => '输入您的Snapchat用户名以在您的个人资料上显示您的Snapchat信息。',
            'instagram' => '输入您的Instagram用户名以在您的个人资料上显示您的Instagram信息。',
            'facebook' => '输入您的Facebook用户名以在您的个人资料上显示您的Facebook信息。',
            'includes_skinmc_plus_benefits' => 'Includes SkinMC plus benefits',
        ],
        'recover' => [
            'title' => '恢复您的账户',
            'subtitle' => '请输入您的新密码并确认新密码以完成恢复您的帐户。',
            'new_password' => '新密码',
            'repeat_new_password' => '再次输入新的密码',
            'submit' => '恢复账户',
        ],
        'customise' => [
            'title' => '自定义你的个人资料',
            'description' => '添加您的社交媒体，选择一个emoji表情，设置您的位置并做更多',
            'information' => '信息',
            'preview' => '预览',
            'location' => [
                'title' => '位置',
                'description' => '选择您想要添加到您的个人资料的位置。',
            ],
            'biography' => [
                'title' => '个人信息',
                'description' => '为您的个人资料写一个自传。',
            ],
            'status' => '状态',
            'status-toggle' => '显示我的在线状态',
            'emoji' => 'Emoji',
            'name-history-toggle' => '将用户名更变历史设为私人',
            'name-history-info' => '您的 Minecraft 用户名历史记录目前是',
            'name-history-toggle-on' => '私有的',
            'name-history-toggle-off' => '公开',
            'theme' => '个人资料主题',
            'theme-primary' => 'Primary',
            'theme-secondary' => 'Secondary',
            'appearance' => '外观',
        ],
        'link' => [
            'manage' => '管理关联的 Minecraft 账户',
            'description' => '查看和管理您关联的 Minecraft 帐户',
            'title' => '链接的Minecraft帐户',
            'current' => '当前关联的 Minecraft 账户。',
            'status' => '您现在可以完全访问所有 SkinMC 功能！',
            'linked' => '已关联',
            'disconnect' => '取消关联',
            'disconnect-title' => '取消关联的Minecraft账号',
            'disconnect-info' => '您确定要断开您的 Minecraft 帐户吗？',
            'disconnect-features' => '您将无法访问评论、定制和需要关联的 Minecraft 账户的其他功能。 若要再次使用这些，您将被要求链接到Minecraft账户。',
            'disconnect-following' => '断开您的 Minecraft 账户将永久移除您关注的所有个人资料。',
            'disconnect-posts' => '您创建的帖子和赞将被删除。',
            'can-not-undo' => '此操作无法撤消。',
            'are-you-sure' => '您确定吗？',
            'confirm' => '是，确认断开连接',
            'cancel' => '否，取消',
            'success' => '您的账户已成功断开连结！',
        ],
        'finish-setup' => [
            'title' => '完成账户设置',
            'description' => '完成设置您的帐户，并通过链接您的 Minecraft 帐户到 SkinMC 获得所有功能的完全访问权限。',
            'link' => '链接 Minecraft 账号',
            'get-started' => '开始',
            'skip' => '跳过',
            'download_skin' => 'Download skin',
            'claim' => '确认您的个人资料',
            'pending_upload' => 'Link your Minecraft account to finish publishing your skin.',
            'customise' => '自定义你的个人资料',
            'social' => '添加社会链接',
            'comment' => '访问评论系统',
            'direct_message' => '发送私信',
            'feed' => '发布状态更新到 Feed',
            'follow' => '关注您的朋友',
            'badge' => '您的个人资料上显示的徽章',
            'cape' => '自定义Minecraft披风',
            'backup' => '自动备份皮肤',
            'more' => '以及更多……',
        ],
        'creations' => [
            'title' => 'Creations',
            'published' => 'Published',
            'private' => 'Private',
            'unlisted' => 'Unlisted',
            'drafts' => 'Drafts',
            'empty_title' => 'No creations yet',
            'empty_published' => 'You have no published creations. Upload a skin and set visibility to "Public" to show it here.',
            'empty_private' => 'You have no private (unlisted) creations.',
            'empty_unlisted' => 'You have no unlisted creations.',
            'empty_drafts' => 'You have no drafts. Save a creation as draft from the editor or upload page.',
            'empty_browse' => 'Browse gallery',
            'empty_upload' => 'Upload skin',
            'meta' => [
                'title' => 'My creations',
                'description' => 'View and manage your skin creations.',
            ],
        ],
        'banners' => [
            'title' => 'Banners',
            'published' => 'Published',
            'drafts' => 'Drafts',
            'empty_title' => 'No banners yet',
            'empty_published' => 'You have no published banners. Create a banner in the editor and publish it to show it here.',
            'empty_drafts' => 'You have no draft banners. Create a banner in the editor without publishing to save as draft.',
            'empty_browse' => 'Browse gallery',
            'empty_create' => 'Create banner',
            'meta' => [
                'title' => 'My banners',
                'description' => 'View and manage your Minecraft banners.',
            ],
        ],
        'skins' => [
            'title' => '管理皮肤',
            'subtitle' => 'Choose which skins appear on your profile. Your current Minecraft skin is always shown.',
            'toggle' => '皮肤可见性切换',
            'section_currently_worn' => 'Currently worn in Minecraft',
            'section_profile_skins' => 'Skins on your profile',
            'active_badge' => 'Active in Minecraft',
            'active_synced_copy' => 'Synced from your Minecraft account.',
            'active_action_copy' => 'Always visible on your profile. To hide it, change your skin in Minecraft.',
            'open_minecraft_skin_settings' => 'Open Minecraft skin settings',
            'show_on_profile' => 'Show on profile',
            'show_on_profile_tooltip' => 'Controls visibility on your SkinMC profile.',
            'empty' => 'No skins in your history yet. Skins you wear in Minecraft will appear here.',
            'empty_other' => 'No other skins yet. Skins you have worn will appear here; you can show or hide them on your profile.',
        ],
        'invite' => [
            'title' => '我的邀请',
            'headline' => '邀请你的朋友',
            'info' => '创建一个邀请码与您的朋友分享。一旦他们接受，您都会赚到一些额外的 XP！',
            'description' => '为你的朋友创建一个邀请函，你们都会赚到一些额外的 XP。',
            'generate' => '创建邀请码',
            'empty' => '您尚未创建任何邀请。',
            'code' => '邀请代码',
            'expiry' => '每个邀请代码只能用一次。',
            'status' => [
                'title' => '状态',
                'pending' => '处理中',
                'accepted' => '已接受',
            ],
            'add_invite' => [
                'button' => '有邀请？',
                'title' => '添加一个邀请代码',
                'redeem' => '兑换邀请代码',
            ],
            'share' => '向您的朋友发送一个邀请链接',
        ],
        'emoji' => [
            'title' => 'SkinMC Emoji',
            'introducing' => '关于',
            'info' => '使用Emoji自定义您的个人资料。当您升级时解锁更多。',
            'unlocked_at' => '在级别：级别解锁',
            'unlocks_at' => '达到等级 :level 以解锁',
            'turn_off' => '显示更多emoji',
        ],
    ],
    'notifications' => [
        'title' => '通知',
        'view_all' => '查看全部',
        'view_all_notifications' => '查看所有通知',
        'image' => '通知照片',
        'archived' => '已归档',
        'inbox' => '收件箱',
        'empty' => [
            'title' => '已是最新版本！',
            'text' => '新通知将在这里显示。',
            'text-archived' => '已归档的通知将在这里显示。',
        ],
        'action' => [
            'archive' => '存档',
            'unarchive' => '取消存档',
            'open' => '单击来打开',
        ],
        'toast' => [
            'archive' => '通知已移动到存档',
            'unarchive' => '通知已移动到收件箱',
            'undo' => '撤销',
        ],
    ],
    'error' => [
        'offline' => [
            'title' => '无互联网连接',
            'subtitle' => '您的网络已断开。请检查您的连接并重新加载页面以重试。',
            'try_again' => '请再试一次',
        ],
        '404' => [
            'title' => '404 - 找不到页面。',
            'subtitle' => 'Hm，似乎在这个地方找不到任何东西。或许试着返回，或开始新的搜索？',
            'try_again' => '返回首页',
        ],
    ],
    'heads' => [
        'list' => [
            'meta' => [
                'title' => 'Minecraft Head数据库',
                'description' => '探索Minecraft头颅的数据库，以装饰您的世界或生成您自己的Give命令。 查看官方头部、玩家头部和自定义头部，这些头部具有永远不变的纹理功能。',
            ],
            'header' => [
                'title' => 'Minecraft heads',
                'subtitle' => 'Explore our database of Minecraft heads to decorate your world, or generate your own give command. Player heads show the current skin worn by a user, and can change as the user updates their skin. Custom heads are linked to the Mojang skin file and never change. Custom heads must be summoned using a command block as the command is very long.',
            ],
            'count' => [
                'heads' => ':heads head|:heads heads',
            ],
            'customheads' => [
                'title' => 'Custom heads',
                'description' => 'Custom heads use the direct path to the texture file on the Mojang servers. Hence textures will never be deleted and the heads never change.',
                'version' => 'Minecraft 1.8 或更高版本',
            ],
            'playerheads' => [
                'title' => '玩家头部',
                'description' => '玩家头使用当前Minecraft玩家的皮肤纹理. 因为他们是基于用户名的，当玩家更改名字或皮肤时，头部会改变。',
                'version' => '所有Minecraft版本',
            ],
        ],
    ],
    'mod' => [
        'title' => 'SkinMC Mod: 自由定义披风',
        'headline' => '介绍SkinMC Mod以便更多的自定义',
        'description' => 'Giving back to the Minecraft community, with a free mod which enables players more customisation with custom capes, available and visible for anyone using the mod.',
        'download' => '立即下载',
        'download-title' => '下载模组',
        'requires' => '需求',
        'select-version' => '选择您的Minecraft版本',
        'get-started' => '入门很简单',
        'step-1' => '1. 获取模组',
        'step-1-detail' => '安装Fabric，然后为您的游戏版本下载模组并将下载的jar文件放到相应的模组文件夹中。',
        'step-2' => '2. 链接您的帐户',
        'step-2-detail' => '如果您还没有做好准备，注册/登录并连接到您的 Minecraft 帐户到 SkinMC。',
        'step-3' => '3. 上传您的披风',
        'step-3-detail' => '转到您的帐户并上传您的自定义披风。它将在游戏中显示。',
        'all-versions' => '所有版本',
        'latest' => '最新的',
        'logged-in' => '上传您的披风',
        'mirror' => '镜像',
        'download-via' => '通过这些下载：',
        'curseforge' => 'CurseForge',
    ],
    'app' => [
        'title' => 'SkinMC 安卓应用程序',
        'headline' => '跟SkinMC安卓应用程序打个招呼。',
        'play-store-attribution' => 'Google Play和Google Play标志是Google LLC的商标。',
        'features' => 'Convenient features for on the go',
        'feature-qr' => '以二维码扫描器生成',
        'feature-qr-detail' => '使用二维码扫描器内置的功能来轻松地从桌面获取皮肤到应用程序，或扫描您朋友自定义个人资料的二维码。',
        'feature-files' => '直接保存到文件',
        'feature-files-detail' => '通过Android 文件管理器的使用，应用程序可以方便地保存皮肤，使其更容易应用到基岩版中。',
        'feature-noads' => '无广告',
        'feature-noads-detail' => 'A clean designed interface, without distractions. Enjoy an Ad-free experience without intrusive annoyances from web to app.',
        'feature-experience' => 'Experience',
        'feature-experience-detail' => '随时随地享受完整的 SkinMC 体验，添加功能。自定义您的个人资料，添加您的个人资料，创建一个有趣的二维码和更多！',
        'get-app-headline' => 'Get the SkinMC App',
        'get-app-detail' => 'Your very own Minecraft companion for your Android — available for free.',
    ],
    'random' => [
        'title' => 'Loading random Minecraft skin',
        'description' => 'Loading random Minecraft skin',
        'headline' => 'Please wait...',
        'redirect' => 'You will be automatically redirected. Page not loading?',
        'click-here' => 'Click here',
        'messages' => [
            '1' => 'Loading random Minecraft skin...',
            '2' => 'Digging down...',
            '3' => 'Creeper, aw man...',
            '4' => 'Searching through chests...',
            '5' => 'Did you know the coming skin is completely random?',
            '6' => 'Random skin incoming...',
            '7' => 'One more block...',
            '8' => 'Sorting inventory...',
            '9' => 'Crafting diamond pickaxe...',
            '10' => 'Looking for Herobrine...',
        ],
    ],
    'feed' => [
        'title' => 'Feed',
        'following' => 'Following',
        'sign-up' => 'Sign up or log in to join the conversation.',
        'link-account' => '链接您的 Minecraft 帐户以加入讨论。',
        'placeholder' => '发生了什么事？',
        'audience' => '观众',
        'audience-title' => '谁可以看到这个？',
        'everyone' => '所有人',
        'everyone-info' => '无论是否在 SkinMC 上，任何人都可以。',
        'followers' => '粉丝',
        'followers-info' => '登入或关注我的人。',
        'private' => '只有我',
        'private-info' => '只有我可以看到私人帖子。',
        'submit' => '帖子',
        'like' => '赞',
        'comment' => '回复',
        'share' => '分享',
        'remaining' => '剩余',
        'profile' => '由 :username 发布的帖子',
        'posts' => '所有帖子',
        'my-posts' => '我的帖子',
        'view-all' => '查看所有帖子',
        'post' => [
            'meta' => ':username on SkinMC: :text',
            'title' => '帖子',
            'created' => '状态更新已发布！',
            'confirm-delete' => '您确定要删除此帖子？它不能撤消。',
            'delete' => '删除帖子',
            'deleted' => '您的帖子已被删除。',
        ],
        'repost' => [
            'button' => '转发',
            'quote_button' => '引用',
            'title' => '举报这则帖文',
            'quote_title' => '引用帖文',
            'quote_label' => '添加评论(可选)',
            'quote_placeholder' => '添加您的想法……',
            'reposted' => '已转发',
            'success' => '已转发！',
            'removed' => '转发已删除。',
            'already_reposted' => '您已经转发了这个内容。',
            'undo' => '取消转发',
            'original_deleted' => '原帖已被删除。',
            'deleted_post' => '这则帖文已被删除',
        ],
        'hashtags' => [
            'title' => '热门',
            'trending-now' => '现在流行',
            'post' => '帖子',
            'posts' => '帖子',
            'posts-count' => ':count post|:count posts',
            'hashtag' => 'Hashtag',
            'hashtags' => 'Hashtags',
            'no-results' => 'No hashtags found',
        ],
        'search' => [
            'title' => 'Search',
            'placeholder' => 'Search posts, hashtags...',
            'no-results' => 'No results found',
            'posts' => 'Posts',
            'no-hashtags-found' => 'No hashtags found matching ":query"',
            'no-results-found' => 'No results found for ":query"',
        ],
        'poll' => [
            'title' => 'Poll',
            'create' => 'Create a poll',
            'option' => 'Option',
            'add_option' => 'Add option',
            'duration' => 'Duration',
            'duration_1' => '1 day',
            'duration_3' => '3 days',
            'duration_7' => '7 days',
            'votes' => '{0} votes|{1} vote|[2,*] votes',
            'ended' => 'Poll ended',
            'ends_in' => 'Ends :time',
            'login_required' => 'Sign in to vote',
        ],
        'gif' => [
            'title' => 'GIF',
            'search_placeholder' => 'Search KLIPY for GIFs...',
            'no_results' => 'No GIFs found',
            'powered_by' => 'Powered by',
            'categories' => 'Categories',
            'trending' => 'Trending',
        ],
        'media' => 'Media',
        'follow-suggestions' => 'Follow the team',
        'explore' => 'Explore',
        'hashtag' => 'Hashtag',
        'no_users' => 'No users found.',
        'stories' => [
            'archive' => [
                'title' => 'Story Archive',
                'subtitle' => 'Your archived stories are only visible to you',
                'empty' => 'No archived stories yet',
                'empty-description' => 'Stories you post will appear here after 24 hours.',
                'action' => 'Archive',
                'archived' => 'Story moved to archive.',
                'already-archived' => 'Story is already archived.',
            ],
        ],
    ],
    'private' => [
        'title' => 'Private posts',
        'text' => 'This post is private.',
    ],
    'liked' => [
        'title' => 'Liked',
    ],
    'following' => [
        'title' => 'Following',
        'text' => 'Sign in to view this post.',
    ],
    'tags' => [
        'empty' => 'No tags to vote on yet',
        'empty-subtitle' => 'Be the first to add one',
    ],
    'inbox' => [
        'title' => 'Messages',
        'details' => 'Details',
        'message_user' => 'Message',
        'write_message' => 'Write a message',
        'empty' => [
            'no_message_selected' => 'No message selected',
            'open_or_start_conversation' => 'Open a conversation from the message list, or start a new one.',
            'no_messages' => 'No unread messages',
            'start_conversation' => 'Once you start a new conversation, your messages will be displayed here.',
            'conversation' => 'This is the beginning of your conversation with :username.',
            'users' => 'Unable to find any users that match the current query.',
        ],
        'typing' => ':username is typing...',
        'new_message' => 'New message',
        'mark_unread' => 'Mark unread',
        'send_message' => 'Send message',
        'delete_message' => 'Delete message for you',
        'latest_conversations' => 'Latest conversations',
        'delete_conversation' => 'Delete conversation',
        'show_details' => 'Show details',
        'hide_details' => 'Hide details',
        'unread' => 'Unread',
        'deleted' => 'Deleted',
        'report_message' => 'Report message',
        'add_reaction' => 'Add reaction',
        'today' => 'Today',
        'reconnect' => 'Please reconnect your Minecraft account to chat',
        'account_disconnected' => 'This user disconnected their linked Minecraft account.',
        'saved_messages' => 'Saved messages',
        'new_message_to_label' => 'To',
        'external-link-to' => 'This link will take you to',
        'external-link-confirmation' => 'Are you sure you want to go there?',
        'external-link' => 'External link',
        'reply' => 'Reply',
    ],
    'server' => [
        'manage' => [
            'stats' => 'Stats',
        ],
    ],
    'report' => [
        'button' => 'Report',
        'title' => 'Report content',
        'describe' => 'Briefly describe why you are reporting this',
        'select' => 'Select report reason',
        'submit' => 'Submit report',
        'reasons' => [
            'INAPPROPRIATE_CONTENT' => 'Inappropriate content',
            'SPAM' => 'Spam',
            'HARASSMENT' => 'Harassment',
            'OTHER' => 'Other',
        ],
    ],
    'leaderboard' => [
        'title' => 'Leaderboard',
        'description' => 'View the SkinMC leaderboard of users.',
        'headline' => '前 10',
        'all-time-invites' => 'All time invites',
        'all-time-xp' => '全部时间 XP',
        '30-day-xp' => '30 天 XP',
    ],
    'boards' => [
        'title' => 'Boards',
        'meta_title' => 'My Boards',
        'meta_description' => 'Organize your saved Minecraft skins, creations, and banners into boards.',
        'all_pins' => 'All Pins',
        'save' => 'Save',
        'saved' => 'Saved',
        'save_to_board' => 'Save to board',
        'save_to_label' => 'Save to: :board',
        'saved_to_label' => 'Saved to :board',
        'choose_board' => 'Choose board',
        'search_boards' => 'Search',
        'no_boards' => 'No boards yet',
        'no_boards_match' => 'No boards found',
        'create_board' => 'Create board',
        'create' => 'Create',
        'cancel' => 'Cancel',
        'add' => 'Add',
        'create_placeholder' => 'Like "Medieval Builds" or "PvP Loadouts"',
        'field_name' => 'Name',
        'secret_label' => 'Secret',
        'secret_description' => 'So only you and collaborators can see it.',
        'keep_secret' => 'Keep this board secret',
        'add_collaborators' => 'Add collaborators (optional)',
        'collaborator_search_placeholder' => 'Search by name or email',
        'edit_board' => 'Edit board',
        'leave_board' => 'Leave board',
        'leave_board_confirm' => 'Leave this board? You will no longer be able to add pins to it.',
        'delete_board' => 'Delete board',
        'delete_confirm' => 'Are you sure you want to delete this board? All pins will be removed.',
        'empty_headline' => 'No pins yet',
        'empty_subtitle' => 'Start saving skins, creations, and banners to this board.',
        'empty_boards_headline' => 'No boards yet',
        'empty_boards_subtitle' => 'Save your first skin to automatically create a board.',
        'browse_skins' => 'Browse skins',
        'pins_count' => '{0} No pins|{1} 1 pin|[2,*] :count pins',
        'secret_badge' => 'Secret',
        'public_boards' => 'Boards',
        'collaborator_unknown_user' => 'Someone',
        'collaborating' => 'Collaborating',
        'your_boards' => 'Your boards',
        'boards_you_collaborate_on' => 'Boards you collaborate on',
        'empty_collaborating' => 'No boards you collaborate on yet.',
        'toast' => [
            'saved_to' => 'Saved to :board',
            'removed' => 'Pin removed',
            'created' => 'Board created',
            'updated' => 'Board updated',
            'deleted' => 'Board deleted',
            'collaborator_added' => 'Collaborator added',
            'collaborator_removed' => 'Collaborator removed',
            'left_board' => 'You left the board',
        ],
    ],
];
