<?php

return [
    'title' => 'Заблокированные аккаунты',
    'description' => 'Управляйте заблокированными аккаунтами.',
    'empty_page' => 'Нет заблокированных аккаунтов на этой странице.',
    'empty' => 'Вы не заблокировали ни одного аккаунта.',
    'block' => 'Заблокировать :username',
    'unblock' => 'Разблокировать :username',
    'block_title' => 'Заблокировать :username?',
    'unblock_title' => 'Разблокировать :username?',
    'confirm_block' => 'Заблокировать',
    'confirm_unblock' => 'Разблокировать',
    'cancel' => 'Отмена',
    'block_description' => 'Вы не будете видеть публикации друг друга, писать друг другу и подписываться друг на друга. Вы оба будете удалены из подписчиков друг друга. Вы можете разблокировать их в настройках.',
    'groups_description' => 'В общих группах вы останетесь участниками, но не будете видеть сообщения друг друга и получать уведомления друг от друга.',
    'blocked' => 'Аккаунт заблокирован.',
    'unblocked' => 'Аккаунт разблокирован.',
    'error' => 'Не удалось сохранить изменение. Попробуйте ещё раз.',
    'saving' => 'Сохранение…',
    'unavailable' => 'Это действие недоступно.',
    'content_unavailable' => 'Этот контент недоступен.',
    'profile_blocked' => 'Вы заблокировали :username.',
    'profile_unavailable' => 'Социальный контент этого аккаунта недоступен.',
    'conversation_unavailable' => 'Messaging is unavailable for this conversation. Your previous messages are still here for reference and reporting.',
    'blocked_on' => 'Заблокирован :date',
    'back_settings' => 'Назад к настройкам',
    'shared_group_notice' => 'This group includes an account you can’t interact with. Their messages and notifications will be hidden. Group membership remains visible.',
];
