<?php

return [
    'skins' => 'Скины',
    'avatars' => 'Аватары',
    'editor' => 'Редактор',
    'heads' => 'Головы',
    'capes' => 'Плащи',
    'servers' => 'Серверы',
    'achievement' => 'Достижения',
    'armor' => 'Стойка для брони',
    'banners' => 'Баннеры',
    'banner' => 'Редактор флагов',
    'banner_gallery' => 'Banner Gallery',
    'profile' => 'Мой профиль',

    'generators' => 'Генераторы',

    // Navigation dropdowns
    'feed' => 'Лента',
    'discover' => 'Исследуйте',
    'mods' => 'Моды',
    'shaders' => 'Шейдеры',
    'resource_packs' => 'Наборы ресурсов',
    'modpacks' => 'Модпаки',
    'datapacks' => 'Набор ресурсов',
    'plugins' => 'Плагины',

    'logout' => 'Выйти',
    'register' => 'Регистрация',
    'login' => 'Вход',
    'about' => 'О программе',
    'contact' => 'Обратная связь',
    'faqs' => 'ЧАВО',

    'minecraft_name' => 'Название Minecraft',
    'minecraft_uuid' => 'Minecraft UUID',
    'what' => 'Что',
    'recent_searches' => 'Недавние запросы',
    'username' => 'Логин',
    'uuid' => 'UUID',
    'search' => 'Искать',
    'search_placeholder' => 'Попробовать',
    'search_placeholder_uuid' => 'Введите UUID',
    'start_search' => 'Начать поиск',
    'cancel_search' => 'Отмена',
    'search_type' => 'Тип поиска',
    'search_type_all' => 'Все результаты',
    'profiles' => 'Профили',
    'view_skin' => 'Посмотреть скин',
    'edit_skin' => 'Изменить скин',
    'make_avatar' => 'Сделать аватар',
    'find_heads' => 'Найти головы игроков',
    'no_results_found' => 'Пока нет предложений. Нажмите Enter, чтобы выполнить поиск.',

    'home' => 'Главная страница',
    'help' => 'Справка',
    'tools' => 'Инструменты',
    'more-tools' => 'Больше инструментов',
    'skin_viewer' => 'Просмотр скинов',
    'avatar_maker' => 'Создать аватар',
    'collections' => 'Коллекции',
    'popular_skins' => 'Популярные скины',
    'cartoon_skins' => 'Скины из мультфильмов',
    'animal_skins' => 'Скины животных',
    'community' => 'Сообщество',
    'imprint' => 'Отпечаток',
    'cookies' => 'Файлы cookie',
    'terms' => 'Условия использования',
    'privacy' => 'Политика конфиденциальности',
    'app' => 'Приложение',
    'mod' => 'Мод',
    'totem' => 'Тотемы',
    'cube' => 'Куб',
    'new' => 'Новые',

    'feedback' => 'Обратная связь',
    'status' => 'Статус',
    'recent_searches_placeholder' => 'Когда вы начинаете поиск, ваши прошлые запросы будут показаны здесь.',
    'recent_views_placeholder' => 'После посещения некоторых профилей, ваши прошлые посещения будут показаны здесь.',
    'moderate' => 'Модерировать',
    'listings' => 'Списки',
    'add' => 'Добавить',

    // Autocomplete types
    'autocomplete' => [
        'profile' => 'Профиль',
        'server' => 'Сервер',
        'project' => 'Проект',
        'skin_tag' => 'Метка скина',
        'server_category' => 'Категория Сервера',
        'modrinth_category' => 'Категория Проекта',
    ],

    'theme' => [
        'title' => 'Темы',
        'dark' => 'Тёмная',
        'light' => 'Светлая',
        'auto' => 'Авто',
    ],

    'language' => 'Language',
];
